EOS-15172: Create enums or constants for validator parameters
Seagate/cortx-utils pull request #101
Opened 2020-11-20 12:55 UTC by sanjognaik

- Created config.py as placeholder for validation enums or constants
- Added enums for validation types
- Added some constants in config file for few validations.

Signed-off-by: Sanjog Vikram Naik <sanjog.naik@seagate.com>

2020-11-23 12:00 UTC, ujjwalpl requested changes

2020-11-23 12:00 UTC, ujjwalpl commented on py-utils/src/utils/validator/config.py
> +class Bmc_V_Types(Enum):
What is the objective of this change ? 
Can we consider JSON format for storing these details ?

2020-11-24 08:24 UTC, dmitrydb commented on py-utils/src/utils/validator/config.py
> +class Bmc_V_Types(Enum):
@ujjwalpl It is needed to make provisioner code clear and improve readability after integration with the validation framework. No JSON is needed here. It is the best practice and generic approach for python. So it is correct what @sanjognaik implemented. It is really needed for the provisioner.

2020-12-09 08:17 UTC, ujjwalpl requested changes

2020-12-09 08:17 UTC, ujjwalpl commented on py-utils/src/utils/validator/config.py
> +class Bmc_V_Types(Enum):
These enums should be moved to respective modules and not place at one place. We need to write loose coupled disjoint code as per the guidelines issued to the teams. 

This is avoid changing N different places/files when something changes and this is major source of bugs where teams fix issue but forgot to update other files that had related code.

2021-06-14 05:31 UTC, closed without merging