EOS-15071: Add support for enclosure controller accessibility validator
Seagate/cortx-utils pull request #104
Opened 2020-11-26 08:01 UTC by mariyappanp

2020-12-01 11:11 UTC, cdeshmukh approved these changes

2020-12-09 04:20 UTC, ujjwalpl requested changes

2020-12-09 04:20 UTC, ujjwalpl commented on py-utils/test/validator/test_controller_validator.py
> +        result = salt.client.Caller().function(func, arg)
Please remove any code that talks to salt such. There are APIs to talk to salt which should be used.

2020-12-09 11:42 UTC, mariyappanp commented on py-utils/test/validator/test_controller_validator.py
> +        result = salt.client.Caller().function(func, arg)
Looks I need to write GrainsStorage class like PillarStorage under kvstore
Because 'cluster_id' and other static information are available only with salt '*' grains.items
I will create a separate task for this.

2021-02-11 05:06 UTC, mariyappanp commented on py-utils/test/validator/test_controller_validator.py
> +        result = salt.client.Caller().function(func, arg)
Now test takes <ip> <username> <password> from command line. So I removed salt call and password decryption here.
Please review. @ujjwalpl @cdeshmukh

2021-02-11 05:12 UTC, ujjwalpl requested changes

2021-02-11 05:12 UTC, ujjwalpl commented on py-utils/test/validator/test_controller_validator.py
> +    """Test storage contoller related validations"""
""" Test storage controller related validations """

1. Spell error
2. Please follow consistent style for comment.

2021-02-11 05:12 UTC, ujjwalpl commented on py-utils/test/validator/test_controller_validator.py
> +        """ Check 'accessible' validation for an unsupported bundle version of controller"""
""" Check 'accessible' validation for an unsupported bundle version of controller """

2021-02-11 05:12 UTC, ujjwalpl commented on py-utils/test/validator/test_controller_validator.py
> +        """ Check 'accessible' validation type for invalid ip"""
""" Check 'accessible' validation type for invalid ip """

2021-02-11 05:12 UTC, ujjwalpl commented on py-utils/test/validator/test_controller_validator.py
> +        """ Check 'accessible' validation type for invalid ip"""
Please correct style errors all over .

2021-02-11 05:57 UTC, mariyappanp commented on py-utils/test/validator/test_controller_validator.py
> +    """Test storage contoller related validations"""
Corrected.
Now all comments are following the expected and same style of other tests.

2021-02-11 05:57 UTC, mariyappanp commented on py-utils/test/validator/test_controller_validator.py
> +        """ Check 'accessible' validation for an unsupported bundle version of controller"""
Done.

2021-02-11 05:57 UTC, mariyappanp commented on py-utils/test/validator/test_controller_validator.py
> +        """ Check 'accessible' validation type for invalid ip"""
Done.

2021-02-18 04:37 UTC, ujjwalpl requested changes

2021-02-18 04:37 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_controller.py
> +            sshError = traceback.format_exc()
sshError - We do not use canonical naming anywhere in the code, except for the class names.

2021-02-18 04:40 UTC, ujjwalpl requested changes

2021-02-18 04:40 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_controller.py
> +                errno.EINVAL, f"Command failure on controller, '{self.version_cmd}'")
Include output as well to know what went wrong.

2021-02-18 12:37 UTC, ujjwalpl approved these changes

2021-02-19 03:52 UTC, sachinpunadikar approved these changes
+1

2021-02-19 03:52 UTC, merged