EOS-15347: Fixing 'None type object has no debug' logger issue
Seagate/cortx-utils pull request #110
Opened 2020-11-30 07:21 UTC by mariyappanp

[root@smc5-m11 utils]# **python3 -m unittest -v cortx/test/test_ssh_connection.py**
test_command_execution_ok (cortx.test.test_ssh_connection.TestSSHChannel)
Check if command is executed successfully ... Creating mailbox file: File exists
ok
test_connection_ok (cortx.test.test_ssh_connection.TestSSHChannel)
Check if ssh connection is alive ... Creating mailbox file: File exists
ok
test_reconnect_ok (cortx.test.test_ssh_connection.TestSSHChannel)
Check ssh re-connect after disconnection caller ... Creating mailbox file: File exists
ok
test_recv_file (cortx.test.test_ssh_connection.TestSSHChannel) ... Creating mailbox file: File exists
ok
test_send_file (cortx.test.test_ssh_connection.TestSSHChannel) ... Creating mailbox file: File exists
ok

----------------------------------------------------------------------
Ran 5 tests in 29.262s

OK

2020-11-30 08:22 UTC, cdeshmukh requested changes

2020-11-30 08:22 UTC, cdeshmukh commented on py-utils/src/utils/ssh.py
> +                                pkey=self.__pkey,
why removing 'key_filename'? Both are optional arguments and safe to be passed together.

2020-11-30 08:22 UTC, cdeshmukh commented on py-utils/src/utils/ssh.py
> +                self.__pkey = paramiko.RSAKey.from_private_key_file(self.pkey_filename)
Why extracting private key explicitly at corx layer, i believe paramiko will extract automatically & use internally. Memory dump of this object has potential to expose private key of the server otherwise. Do we really need it?

2020-11-30 08:22 UTC, cdeshmukh commented on py-utils/src/utils/ssh.py
> +        Log.debug(f'\nCommand: {command}\nOutput: {output}')
This must be breaking code already i guess.

2020-11-30 08:24 UTC, mariyappanp commented on py-utils/src/utils/ssh.py
> +        Log.debug(f'\nCommand: {command}\nOutput: {output}')
Yes, Somehow it is removed after the unittest.

2020-11-30 08:34 UTC, mariyappanp commented on py-utils/src/utils/ssh.py
> +                                pkey=self.__pkey,
This case(private key/file) we take when we establish the connection without having value for password argument.

Prvisioner creates id_rsa_prvsnr file under ~/.ssh
While I go ahead by passing the filename, I got "**RSA key check invalid private key**" issue. I believe the RSA file didn't met paramiko criteria and so we get this issue. 

To test the private key without validating the file is, pkey argument. This worked fine here.

2020-11-30 08:41 UTC, mariyappanp commented on py-utils/src/utils/ssh.py
> +                self.__pkey = paramiko.RSAKey.from_private_key_file(self.pkey_filename)
Agreed if memory dump originally will hold private key. 
This is optional and only for passwordless communication. 
Ex: We have BMC validation on node, where we earlier used `ssh {node} ipmitool ....`. Then asked to use SSHChannel for executing the commands.

2020-11-30 08:58 UTC, mariyappanp commented on py-utils/src/utils/ssh.py
> +                self.__pkey = paramiko.RSAKey.from_private_key_file(self.pkey_filename)
If it is still vulnerable, key_filename argument is the alternative. But paramiko throws value error on id_rsa_prvsnr file.
So I handled this way.

2020-11-30 10:09 UTC, cdeshmukh commented on py-utils/src/utils/ssh.py
> +                self.__pkey = paramiko.RSAKey.from_private_key_file(self.pkey_filename)
Can we check whats the error for provisioner file, may be file permissions and get that fixed, possibly with provisining team's help, instead of adopting a new layer. But on other side, paramiko itself giving that option, so most code out in the world already using that way. How can we save from staling that pkey value? 
@ujjwalpl what you think? May be its ok.

2020-11-30 10:10 UTC, cdeshmukh commented on py-utils/src/utils/ssh.py
> +                                pkey=self.__pkey,
Ok. Comment on line 62 applies still.

2020-11-30 10:31 UTC, mariyappanp commented on py-utils/src/utils/ssh.py
> +                self.__pkey = paramiko.RSAKey.from_private_key_file(self.pkey_filename)
This is a known issue in the version of paramiko(2.7.2). This version is not available now.
I checked csm requirements.txt which uses paramiko 2.7.1. So I uninstalled 2.7.2 and installed 2.7.1.
While testing with this version, RSA key issue is not reproduced. 

Looks we can go ahead now with pkey_filename argument.
@cdeshmukh

2020-11-30 10:37 UTC, mariyappanp commented on py-utils/src/utils/ssh.py
> +                self.__pkey = paramiko.RSAKey.from_private_key_file(self.pkey_filename)
Please review.

2020-11-30 10:37 UTC, mariyappanp commented on py-utils/src/utils/ssh.py
> +                                pkey=self.__pkey,
New commit carries the requested changes.

2020-11-30 11:29 UTC, cdeshmukh approved these changes

2020-11-30 12:00 UTC, ujjwalpl commented on py-utils/src/utils/ssh.py
> +Log = logging.getLogger(__name__)
We need to avoid logging in utils for performance reasons. Think like C++ STL does not generate any logs. I assume this logging will be disabled by default and used only in the dev. Please confirm.

2020-11-30 15:00 UTC, mariyappanp commented on py-utils/src/utils/ssh.py
> +Log = logging.getLogger(__name__)
I faced issue with logging while doing unittest. So I have separately created this logger which is for dev purpose. I removed this and Log.debug in the new commit.
Thanks.
I had sync up with Naval Patel on this Log object(Singleton by cortx-manager) and understood better.

2020-12-01 08:26 UTC, mariyappanp commented on py-utils/src/utils/ssh.py
> +        Log.debug(f'\nCommand: {command}\nOutput: {output}')
I requested @ajaysrivas to merge this ASAP since its breaking RPM generation.

2020-12-01 09:22 UTC, ajaysrivas approved these changes

2020-12-01 09:48 UTC, ujjwalpl approved these changes

2020-12-01 11:16 UTC, merged