Message Bus Send/Receive
Seagate/cortx-utils pull request #117
Opened 2020-12-08 09:39 UTC by selvakumaar5496

2020-12-08 09:59 UTC, ujjwalpl requested changes

2020-12-08 09:59 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/bus_frame.py
> +#!/usr/bin/env python3
Please move these files directly under message_bus.

2020-12-08 09:59 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/bus_frame.py
> +#!/usr/bin/env python3
Also, rename this file to utils/message_bus/message_bus.py (try to align with the class name)

2020-12-08 09:59 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/callback.py
> +#!/usr/bin/env python3
Please remove this code from this patch. This code should be part of subscription patch.

2020-12-08 09:59 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/client.py
> +#!/usr/bin/env python3
1. Rename this class to MessageBusClient. 
2. Merge this class to utils/message_bus/message_bus.py (with class MessageBus)

2020-12-08 10:04 UTC, ujjwalpl requested changes

2020-12-08 10:04 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/bus_frame.py
> +class MessageBus(metaclass=Singleton):
There is no need for this code to be singleton class.

2020-12-08 10:04 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/topic.py
> +#!/usr/bin/env python3
Please remove this class. There is nothing called "Topic" in Message Bus Design.

2020-12-08 10:04 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/topic_schema.py
> +#!/usr/bin/env python3
Please remove this class if not required. Also please merge all related things into single python file.

2020-12-08 10:04 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/config.py
> +#!/usr/bin/env python3
Please use schema/conf.py for representing the conf.

2020-12-08 10:26 UTC, ujjwalpl requested changes

2020-12-08 10:26 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/topic_in_message.py
> +#!/usr/bin/env python3
This is redundant class, please remove it.

2020-12-08 10:26 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/producer.py
> +    def send(self, message):
`def send(self, messages):`

2020-12-08 10:26 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/producer.py
> +class MessageProducer(BusClient):
Please add comments to each class.

2020-12-08 10:26 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_queue_factory.py
> +class KafkaFactory(Factory):
This class does not make sense. Ideally there should be MessageBrokerFactory which takes input as MessageServer Type and outputs a class of instance of MessageBroker. 
Also, this should be part of message_broker.py itself.

2020-12-08 10:26 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/bus_frame.py
> +    def __load_topic(self):
Message Bus does not have any concept of topics. Please remove any mention of topics as it confuses. 

You should either rename to MessageType and merge all topics related classes into message_type.py.

2020-12-08 16:12 UTC, ujjwalpl requested changes

2020-12-08 16:12 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/exceptions.py
> +class ClientNotfoundError(BaseError):
Lets have only one exception for message bus for now until we have a exception framework

```
class MessageBusError(BaseError): 
   def __init__(self, rc=0, message_id=None, message_args=None):
        super(BaseError, self).__init__(rc, None, message_id, message_args)
```

2020-12-08 16:17 UTC, ujjwalpl requested changes

2020-12-08 16:17 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/bus_frame.py
> +        self.notifier = None
Remove these parameters like notifier, mapper, callables, callback. This will be added once we have subscription.

2020-12-08 16:24 UTC, ujjwalpl requested changes

2020-12-08 16:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/client.py
> +        self.role = role
instead of role it should be id, i.e. client_id.

2020-12-08 16:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/client.py
> +    def __init__(self, bus_handle, role, consumer_group=None, message_type=None, auto_offset_reset=None):
Change bus_handle -> message_bus. We should constantly be using one name for one thing. 
Consumer Group looks specific to Consumer. 

```
class BusClient():
    def __init__(self, message_bus, id, message_type, consumer_group=None, reset_offset=None)
        self._id = id
        self._message_bus = message_bus
        self._message_type = message_type
        self._client_group = client_group
        self._reset_offset = reset_offset
```

2020-12-08 16:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/client.py
> +        self.message_type = message_type
Please use _var (_ as prefix) for all internal variables.

2020-12-08 16:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/client.py
> +        self.bus_handle.send(self.bus_client, message, self.message_type)
This code is incorrect. send takes list of messages.

2020-12-08 16:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/client.py
> +    def send(self, message):
def send(self, messages):

2020-12-09 05:09 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/bus_frame.py
> +#!/usr/bin/env python3
Renamed aligned under utils/message_bus/message_bus.py

2020-12-09 05:10 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/callback.py
> +#!/usr/bin/env python3
Removed this code and its implementations

2020-12-09 05:17 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/client.py
> +#!/usr/bin/env python3
Class named is renamed and it is merged to message_bus.py

2020-12-09 05:17 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/bus_frame.py
> +class MessageBus(metaclass=Singleton):
Removed Singleton implementation

2020-12-09 05:19 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/producer.py
> +    def send(self, message):
changed to messages since it is list of messages

2020-12-09 05:23 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/client.py
> +    def send(self, message):
Renamed to messages

2020-12-09 07:17 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/client.py
> +        self.bus_handle.send(self.bus_client, message, self.message_type)
Send takes List of messages only

2020-12-09 07:22 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/client.py
> +        self.role = role
changed to client_id

2020-12-09 07:26 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/client.py
> +        self.message_type = message_type
added prefix

2020-12-09 07:27 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/client.py
> +    def __init__(self, bus_handle, role, consumer_group=None, message_type=None, auto_offset_reset=None):
changed to generic

2020-12-09 08:19 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/bus_frame.py
> +        self.notifier = None
Removed unused parameters and variables

2020-12-09 08:25 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/topic.py
> +#!/usr/bin/env python3
Removed Topic Class

2020-12-09 08:26 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/topic_schema.py
> +#!/usr/bin/env python3
Removed Topic schema class

2020-12-09 08:27 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/topic_in_message.py
> +#!/usr/bin/env python3
Removed the class

2020-12-09 08:28 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/bus_frame.py
> +    def __load_topic(self):
renamed all to message_type and removed Topics concept from the patch

2020-12-09 08:44 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/exceptions.py
> +class ClientNotfoundError(BaseError):
Limited to one exception

2020-12-10 12:17 UTC, ujjwalpl requested changes

2020-12-10 12:17 UTC, ujjwalpl commented on py-utils/test/message_bus_simple_example.py
> +#!/usr/bin/env python3
Please follow the naming convention. This file should be in 

test/test_message_bus/test_message_bus_basic.py 

Also, it should follow the test spec. Please refer to other tests.

2020-12-10 12:28 UTC, ujjwalpl requested changes

2020-12-10 12:28 UTC, ujjwalpl commented on py-utils/src/template/factory.py
> +        return self.m_dict[config['message_broker']]()
Generic class can not have message_broker

2020-12-10 12:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/bus/__init__.py
> +#!/usr/bin/env python3
Remove "bus" folder.

2020-12-10 12:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/consumer.py
> +        Keyword Arguments:
Please format the comment to make it readable. 
```
Parameters: 
message_bus        An instance of message bus class.
consumer_group     A String that represents Consumer Group ID.
                   Group of consumers can process messages
message_type       This is essentially equivalent to the queue/topic name. e.g. "Alert"
offset             Can be set to "earliest" (default) or "latest".
                   "earliest" will cause messages to be read from the beginning
```

2020-12-10 12:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/consumer.py
> +    def __init__(self, message_bus, consumer_group=None, message_type=None, offset=None):
Why is consumer ID removed from the input ?

2020-12-10 12:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/exceptions.py
> +class MessageBusError(BaseError):
This is not in line with my comment. Please refer to my old comment and declare is as-is.

2020-12-10 12:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/kafka_message_broker.py
> +    A type of broker to send or receive messages across any component
This is not accurate comment. 

"""
Kafka Server based message broker implementation
"""

2020-12-10 12:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/kafka_message_broker.py
> +    def create_admin(self):
All internal functions should start with _

2020-12-10 12:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/kafka_message_broker.py
> +        #producer.flush()
Remove commented code from all over

2020-12-10 12:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/kafka_message_broker.py
> +            self.producer = Producer(**config)
What is Producer ? Does this code even work ?

2020-12-10 12:50 UTC, ujjwalpl requested changes

2020-12-10 12:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_factory.py
> +from src.utils.message_bus.kafka_message_broker import KafkaMessageBroker
Merge this code to message_broker.py itself.

2020-12-10 12:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message/message.py
> +#!/usr/bin/env python3
Remove this from patch. We will add it later as part of value added functions.

2020-12-10 15:11 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/bus/__init__.py
> +#!/usr/bin/env python3
Removed this folder since it is of no use

2020-12-11 07:51 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/config.py
> +#!/usr/bin/env python3
Removed config.py and used existing conf

2020-12-11 07:52 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/producer.py
> +class MessageProducer(BusClient):
Added comments to all classes

2020-12-11 07:52 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/consumer.py
> +class MessageConsumer(BusClient):
Added comments to all classes

2020-12-11 07:52 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_queue_factory.py
> +class KafkaFactory(Factory):
changed to MessageBrokerFactory

2020-12-11 08:00 UTC, selvakumaar5496 commented on py-utils/src/template/factory.py
> +        return self.m_dict[config['message_broker']]()
Removed this class since it is of no use.

2020-12-11 08:34 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message/message.py
> +#!/usr/bin/env python3
Removed entire message directory

2020-12-11 08:37 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/kafka_message_broker.py
> +            self.producer = Producer(**config)
Yes. A common method to create producer or consumer with configurations

2020-12-11 08:44 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/kafka_message_broker.py
> +    def create_admin(self):
it is not an internal function. It is called from another interface

2020-12-11 08:44 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/kafka_message_broker.py
> +        #producer.flush()
Removed all commented code

2020-12-11 09:14 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/exceptions.py
> +class MessageBusError(BaseError):
Implemented wrt to old comment

2020-12-11 09:15 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/kafka_message_broker.py
> +    A type of broker to send or receive messages across any component
corrected

2020-12-11 09:15 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_factory.py
> +from src.utils.message_bus.kafka_message_broker import KafkaMessageBroker
have conflict

2020-12-14 11:48 UTC, closed without merging