Conf store/feature/conf store
Seagate/cortx-utils pull request #119
Opened 2020-12-10 10:34 UTC by suryakumar1024

**Changes**
created new package for kvstore and renamed to kv_store -> existing kvstore directory remains the same
Added confStore and FileStorage with api's. Currently works with jsonfilestore
Added load, get, set and save for json filestore.

2020-12-10 12:01 UTC, ujjwalpl requested changes

2020-12-10 12:01 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/file_storage.py
> +class FileStorage(KvStorage):
This class should be part of kv_store

2020-12-10 12:01 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/kvstore_factory.py
> +class KvStoreFactory:
This class should be part of kv_store

2020-12-10 12:01 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/storage/json_storage.py
> +import json
This class should be part of kv_store

2020-12-16 06:24 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +from src.utils.schema.payload import Payload
Updated in current patch. Kept the same code as ConfCache inside conf_store

2020-12-16 06:24 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +    def load(self, index, value):
Updated in current patch

2020-12-16 06:28 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +    def get(self, index, key=None, default_value = None):
Updated in current patch

2020-12-16 06:28 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +       self.payload = Payload
updated in current patch. Copied payload as in the name of ConfCache

2020-12-16 06:29 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +            print('Value for given key index not found')
Removed this code. updated with new code in current patch

2020-12-16 06:29 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_storage.py
> +    def copy(self, index1, index2):
updated in current patch

2020-12-16 06:29 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_type.py
> +class ConfType():
updated in current patch. removed ConfType class from confStore

2020-12-16 06:30 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/file_storage.py
> +class FileStorage(KvStorage):
updated code. current implementation is different from previous code architecture

2020-12-16 06:31 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/kvstore_factory.py
> +class KvStoreFactory:
updated in current patch. current implementation doesn't have this code

2020-12-16 06:31 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/storage/json_storage.py
> +import json
updated in current patch. current implementation doesn't have this code file

2020-12-16 12:41 UTC, ujjwalpl requested changes

2020-12-16 12:41 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +    def __init__(self, kv_store_instance):
```
def __init__(self, kv_store: KvStore):

2020-12-16 12:41 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        Args:
```
parameters:
index:     Identifier for the config loaded from the KV Store
kv_store:  KV Store (Conf Backend)
overwrite: When False, it throws exception if index already exists. 
           Default: False 
callback:  Callback for the config changes in the KV Store
```

2020-12-16 12:46 UTC, ujjwalpl requested changes

2020-12-16 12:46 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +    def load(self, index, kvStore, force=False, callback=None) -> None:
kvStore is incorrect variable name. We use underscore naming conventions. Please use consistent coding conventions.

2020-12-18 07:06 UTC, suryakumar1024 commented
Have raised new PR with new Architectural level changes.  So closing this

2020-12-18 07:06 UTC, closed without merging