Kvstore feedback changes
Seagate/cortx-utils pull request #121
Opened 2020-12-11 08:36 UTC by suryakumar1024

KvStore code restructure

2020-12-11 09:44 UTC, ujjwalpl requested changes

2020-12-11 09:44 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/conf_cache.py
> +class ConfCache:
Please add copyright license notice to all the files.

2020-12-11 09:44 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/conf_cache.py
> +    def __init__(self, doc):
def __init__(self, kvstore):

2020-12-11 09:44 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/conf_cache.py
> +    def convert(self, map, payload):
This interface is not required. ConfCache itself is payload.

2020-12-11 09:44 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_storage/file_kv_storage.py
> +import os, errno, sys
Please keep all the files in kv_store directory itself. No need to create file_storage.

2020-12-11 09:53 UTC, ujjwalpl requested changes

2020-12-11 09:53 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_storage/file_kv_storage.py
> +class FileKvStorage:
Please add comment to all the classes.

2020-12-11 09:58 UTC, ujjwalpl requested changes

2020-12-11 09:58 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +    This class will take KvStorage implementation as input and be front facing
Need to be accurate and precise

"Class for Abstraction over all kinds of KV based Storage"

2020-12-11 09:58 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_storage/yaml_kv_storage.py
> +from src.utils.kv_store.file_storage.file_kv_storage import FileKvStorage
No need to separate classes into separate files. You should merge similar category classes into one file.

2020-12-11 10:01 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/conf_cache.py
> +class ConfCache:
Updated with copyright license notice

2020-12-11 10:01 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/conf_cache.py
> +    def __init__(self, doc):
Updated doc to kvstore

2020-12-11 10:01 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/conf_cache.py
> +    def convert(self, map, payload):
Removed convert API from the confcache

2020-12-11 10:02 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/file_storage/file_kv_storage.py
> +import os, errno, sys
Updated directory structure as metioned

2020-12-11 10:18 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +    This class will take KvStorage implementation as input and be front facing
noted. will updated that

2020-12-11 10:19 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/file_storage/yaml_kv_storage.py
> +from src.utils.kv_store.file_storage.file_kv_storage import FileKvStorage
merged into single file

2020-12-11 10:55 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/file_storage/file_kv_storage.py
> +class FileKvStorage:
Added comments to all pre-implemented classes

2020-12-11 11:28 UTC, ujjwalpl requested changes

2020-12-11 11:28 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_storage/json_kv_storage.py
> +from src.utils.kv_store.file_storage.file_kv_storage import FileKvStorage
Merge this into the file "kv_store/file_kv_storage.py"

2020-12-11 11:28 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_storage/file_kv_storage_factory.py
> +
Please merge this with kv_store/file_kv_storage.py

2020-12-11 11:28 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/conf_cache.py
> +class ConfCache:
This file should be part of conf_store module and not kv_store

2020-12-11 11:28 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        return self._storage.delete(key)
Please add test code.

2020-12-11 12:00 UTC, ujjwalpl requested changes

2020-12-11 12:00 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_kv_storage_factory.py
> +
Merge this into file_kv_storage.py. Refer to code example, I provided to know how to do this.

2020-12-11 12:01 UTC, ujjwalpl requested changes

2020-12-11 12:01 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_storage_collections.py
> +from src.utils.kv_store.file_kv_storage import FileKvStorage
Rename this file to kv_file_storage_collections.py. There will be another collection for dist_kv_storage.

2020-12-11 12:10 UTC, ujjwalpl requested changes

2020-12-11 12:10 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_storage_collections.py
> +
Remove blank line. Please be consistent w.r.t. spacing.

2020-12-11 12:10 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_storage_collections.py
> +        """
Please use """ or '''. Please be consistent

2020-12-15 04:26 UTC, suryakumar1024 commented
Closing this PR since change in architecture

2020-12-15 04:26 UTC, closed without merging