Message bus Send/Receive messages
Seagate/cortx-utils pull request #124
Opened 2020-12-11 17:03 UTC by selvakumaar5496

2020-12-11 17:30 UTC, ujjwalpl requested changes

2020-12-11 17:30 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/consumer.py
> +class MessageConsumer(MessageBusClient):
Add Class Descritption

2020-12-11 17:30 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/consumer.py
> +            message_bus: An instance of message bus class.
Please format. Refer to my comment for example.

2020-12-11 17:34 UTC, ujjwalpl requested changes

2020-12-11 17:34 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/exceptions.py
> +#!/usr/bin/env python3
Rename this file to error.py as per the conventions already followed in the code.

2020-12-11 17:34 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/exceptions.py
> +class MessageBusError(BaseError):
rc is not used. rc needs to be decided by the caller. 
```
class MessageBusError(BaseError):
    def __init__(self, rc=0, message, *args):
        desc = message % args
        super().__init__(rc, desc)
```

2020-12-11 17:38 UTC, ujjwalpl requested changes

2020-12-11 17:38 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collections.py
> +    def __init__(self):
Add a blank line before this. Please use consistent spacing. 

```
class ABC: 
    """ This is a sample class """

    def __init__(self):
        """ This is a sample function comment """
        ....
```

2020-12-11 17:38 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collections.py
> +class MessageBroker:
Move this class to message_broker.py. We decided to have two files 

1. message_broker.py containing classes MessageBroker and MessageBrokerFactory
2. message_broker_collections.py containing classes KafkaMessageBroker and RabbitmqMessageBroker.

2020-12-11 17:44 UTC, ujjwalpl requested changes

2020-12-11 17:44 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collections.py
> +    def create_admin(self):
This should be called from the constructor itself. OR Rename it to 'connect'

2020-12-11 17:44 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +    def create(self, client, client_id, consumer_group=None, message_type=None, offset=None):
Message Bus does not have any interface called "create" Please refer to the spec.

2020-12-11 17:47 UTC, ujjwalpl requested changes

2020-12-11 17:47 UTC, ujjwalpl commented on py-utils/test/test_message_bus/test_message_bus_basic.py
> +def main():
Please follow unit test format. Refer to the other test classes.

2020-12-11 17:47 UTC, ujjwalpl commented on py-utils/src/utils/schema/conf.py
> +        Conf._payloads[index] = CommonPayload(doc)
You should not make any changes to this class. This will break other code. 

Try test_conf.py to learn how conf is used.

2020-12-11 17:47 UTC, ujjwalpl commented on py-utils/src/utils/schema/conf.py
> +        return Conf._payloads[index].load().get(key)
This change is not correct. It changes the spec. Need to revert.

2020-12-11 17:48 UTC, ujjwalpl requested changes

2020-12-11 17:48 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/producer.py
> +class MessageProducer(MessageBusClient):
Please add class description without fail.

2020-12-11 17:48 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/producer.py
> +        Keyword Arguments:
Please format to make it readable. Refer to the example I gave in my earlier comment.

2020-12-11 17:52 UTC, ujjwalpl requested changes

2020-12-11 17:52 UTC, ujjwalpl commented on py-utils/src/utils/schema/conf.py
> +from src.utils.schema.payload import *
This change will break. This link is created by rpm install so must be maintained. Please learn how to use cortx-utils  from CSM team. Saurabh can help getting help on this.

2020-12-11 17:52 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/producer.py
> +#!/usr/bin/env python3
Please merge MessageBusClient, Producer and Consumer classes into mesage_bus_client.py

2020-12-11 17:52 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +class MessageBusClient:
This should be moved to message_bus_client.py

2020-12-11 17:52 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_factory.py
> +class MessageBrokerFactory:
Move this to message_bus.py

2020-12-11 17:55 UTC, ujjwalpl requested changes

2020-12-11 17:55 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collections.py
> +    def create(self, client, client_id, consumer_group, message_type, offset):
create interface is not required. Please refer to the spec

2020-12-12 09:41 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/consumer.py
> +class MessageConsumer(MessageBusClient):
Added Description

2020-12-12 09:41 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/consumer.py
> +            message_bus: An instance of message bus class.
Formatted

2020-12-12 09:42 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/exceptions.py
> +#!/usr/bin/env python3
Renamed the file

2020-12-12 09:43 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collections.py
> +    def __init__(self):
Have used consistent spacing after comments

2020-12-12 09:44 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collections.py
> +class MessageBroker:
Merged all into a single file

2020-12-12 09:45 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/producer.py
> +class MessageProducer(MessageBusClient):
added class description

2020-12-12 09:46 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/producer.py
> +        Keyword Arguments:
Formatted according to previous comment

2020-12-12 09:46 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/producer.py
> +#!/usr/bin/env python3
Merged into a single file mesage_bus_client.py

2020-12-12 09:47 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +class MessageBusClient:
Merged into a single file mesage_bus_client.py

2020-12-12 09:47 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_factory.py
> +class MessageBrokerFactory:
Merged into a single file mesage_broker.py

2020-12-14 05:33 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +    def create(self, client, client_id, consumer_group=None, message_type=None, offset=None):
removed create method

2020-12-14 05:33 UTC, selvakumaar5496 commented on py-utils/src/utils/schema/conf.py
> +        Conf._payloads[index] = CommonPayload(doc)
reverted back to old change

2020-12-14 05:34 UTC, selvakumaar5496 commented on py-utils/src/utils/schema/conf.py
> +        return Conf._payloads[index].load().get(key)
reverted back to old change

2020-12-14 05:35 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collections.py
> +    def create(self, client, client_id, consumer_group, message_type, offset):
removed this interface

2020-12-14 06:54 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collections.py
> +    def create_admin(self):
removed create methods

2020-12-14 11:56 UTC, ujjwalpl requested changes

2020-12-14 11:56 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +class MessageBusError(BaseError):
Change this class to look like this... 

```
class MessageBusError(Exception):
    """ Generic Exception with error code and output """

    def __init__(self, rc, message, *args):
        self._rc = rc
        self._desc = message % (args)

    @property
    def rc(self):
        return self._rc

    @property
    def desc(self):
        return self._desc

    def __str__(self):
        if self._rc == 0: return self._desc
        return "error(%d): %s" %(self._rc, self._desc)
```

2020-12-14 11:59 UTC, selvakumaar5496 commented on py-utils/src/utils/schema/conf.py
> +from src.utils.schema.payload import *
Reverted back this changes

2020-12-14 12:00 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_message_bus_basic.py
> +def main():
Have followed unit test format. Will try to write more test cases

2020-12-14 12:00 UTC, ujjwalpl requested changes

2020-12-14 12:00 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/__init__.py
> +from src.utils.message_bus.message_broker import MessageBroker, MessageBrokerFactory, KafkaMessageBroker
See if you can avoid importing KafkaMessageBroker and move it to specific messagebroker implementation.

2020-12-14 12:00 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/exceptions.py
> +class MessageBusError(BaseError):
this is been fixed.

2020-12-14 12:04 UTC, ujjwalpl requested changes

2020-12-14 12:04 UTC, ujjwalpl commented on py-utils/test/test_message_bus/test_message_bus_basic.py
> +def main():
No! This is still not the format. Refer to test/kvstore/test_store.py

2020-12-14 12:11 UTC, ujjwalpl requested changes

2020-12-14 12:11 UTC, ujjwalpl commented on py-utils/test/test_message_bus/test_message_bus.py
> +sys.path.insert(1, '../../')
Please remove this line. This is not required. You need to fix this in your test environment. Add README about changes to the env if required.

2020-12-14 12:11 UTC, ujjwalpl commented on py-utils/test/test_message_bus/test_message_bus.py
> +#!/usr/bin/env python3
Send and Receive are not the correct tests. No need to print anything on the screen. 

Tests should be
1. 1 Message Producer and 1 Message Consumer. 
    Send 1000 messages, receive 1000 messages. Test pass if all the 1000 messages are received. 
1. 1 Message Producer and 2 Message Consumers. 
    Send 1000 messages, receive 1000 messages from the consumers. 
    Test pass if all the 1000 messages are received on both the consumers.

2020-12-14 12:12 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/exceptions.py
> +class MessageBusError(BaseError):
Refer to the new comments. We need to write this differently until we have the exception framework.

2020-12-14 12:14 UTC, ujjwalpl requested changes

2020-12-14 12:14 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/__init__.py
> +from src.utils.message_bus.message_bus import MessageBus
Please change all src.utils to cortx.utils.

2020-12-14 12:19 UTC, ujjwalpl requested changes

2020-12-14 12:19 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +    """
One line comment should look like this.. Please use consistent conventions. 

""" Kafka Server based message broker implementation """

2020-12-14 12:19 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +    def __init__(self, message_broker):
def __init__(self, message_broker_name: string):

2020-12-14 12:19 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +            raise MessageBusError(f"Invalid Broker. {e}")
raise MessageBusError(errno.EINVAL, f"Invalid brokern name %s. %s", e)

2020-12-14 12:21 UTC, ujjwalpl requested changes

2020-12-14 12:21 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +    def create(self, role):
Please remove this interface. This is not part of the spec.

2020-12-14 12:24 UTC, ujjwalpl requested changes

2020-12-14 12:24 UTC, ujjwalpl commented on py-utils/test/test_message_bus/kafka_producer.py
> +#!/usr/bin/env python3
Test must start with test_. Rename this file to test_producer.py.  Why even kafka ?

2020-12-14 12:24 UTC, ujjwalpl commented on py-utils/test/test_message_bus/kafka_consumer.py
> +#!/usr/bin/env python3
Test must start with test_ Rename this file to test_consumer.py. Why even kafka ?

2020-12-14 12:24 UTC, ujjwalpl commented on py-utils/src/utils/schema/__init__.py
> +
Please do not use src.utils anywhere in the code.

2020-12-14 12:29 UTC, ajaysrivas requested changes

2020-12-14 12:29 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.producer = Producer(**self.config)
producer_id is ignored. Need to set client.id.

2020-12-14 12:29 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.producer = Producer(**self.config)
method is ignored too. Please look at Producer interface defined in wiki.

2020-12-14 12:29 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.config['enable.auto.commit'] = False
This is always false while consumer can set it to true. Please look at consumer interface.

2020-12-14 12:29 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.consumer = Consumer(**self.config)
consumer_id is ignored. Set it to client.id.

2020-12-14 12:29 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.consumer.subscribe(self.message_type)
subscribe? I thought that we are not implementing it.

2020-12-14 12:29 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker.py
> +                if client_config['offset']:
Requires a validation if the string value passed is correct or not.

2020-12-14 12:29 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker.py
> +class KafkaMessageBroker(MessageBroker):
Don't see Ack() implemented?

2020-12-14 12:29 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker.py
> +                    yield ConsumerRecord(msg.topic(), msg.value(), msg.partition(), msg.offset(), str(msg.key()))
receive interface is defined for returning list of messaged (msg.value()) while this is returning list of ConsumerRecord?

2020-12-14 12:40 UTC, ujjwalpl requested changes

2020-12-14 12:40 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        """
Use conventions for one line comment 
""" comment """

2020-12-14 12:40 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def __init__(self, message_bus, client, **client_config):
P

2020-12-14 12:40 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        self._bus_client = self._message_bus(self._client, **client_config)
Please avoid this kind of calling the class. This is non readable. Its better to define an interface like Init and call that instead so that we can avoid calling it twice by mistake.

2020-12-14 12:40 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +    An interface that creates message brokers
""" Message Bus Framework over various types of Message Brokers """

2020-12-14 12:40 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +            Conf.load('global', Json('/etc/cortx/message_bus.json'))
```
if not os.path.exists('/etc/cortx/message_bus.conf'):
    raise MessageBusError(errno.ENOENT, "Config file /etc/cortx/message_bus.conf not present")
Conf.load('global', Json('/etc/cortx/message_bus.conf'))
```

Lets use message_bus.conf instead of message_bus.json

2020-12-14 12:40 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +    def __call__(self, client, **client_config):
We need to avoid provide this kind of loopholes. There needs to be proper interface to expose the function.

2020-12-14 12:40 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +            message_broker_factory = MessageBrokerFactory(self.message_broker['type'])
MessageBrokerFactory MUST not be instantiated. Its only purpose is to create instances of MessageBroker based on the given message broker type.

```
self._message_broker = MessageBrokerFactory.get_instance(self.message_conf['message_broker.type']
```

2020-12-14 12:40 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +            self.adapter = message_broker_factory.adapter
Dont call it adapter. Its the pointer to message_broker. It should be self._message_broker.

2020-12-14 12:40 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +            self.message_broker = Conf.get('global', 'message_broker')
```
self.message_bus_conf = Conf.get('global', 'message_broker.server')
```

2020-12-14 12:52 UTC, ujjwalpl requested changes

2020-12-14 12:52 UTC, ujjwalpl commented on py-utils/test/test_message_bus/test_message_bus_basic.py
> +sys.path.insert(1, '../../')
Please remove this.

2020-12-14 12:52 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def __init__(self, message_bus, consumer_id=None, consumer_group=None, message_type=None, offset=None):
Please add the type of each parameter 
```
def __init__(self, message_bus, consumer_id=None: str, consumer_group=None: str, 
             message_type=None: str, offset=None: int): 
```

2020-12-14 12:52 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        """
def receive(self) -> list[str]:  
""" Receive messages from message and return the same """

2020-12-14 12:52 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def __init__(self, message_bus, producer_id, message_type):
```
def __init__(self, message_bus: MessageBus, producer_id: str, message_type: str):
```

2020-12-14 13:13 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +    def create(self, role):
Removed this interface

2020-12-14 13:19 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def __init__(self, message_bus, producer_id, message_type):
type added

2020-12-14 13:20 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        """
type and comment added

2020-12-14 13:27 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +            self.adapter = message_broker_factory.adapter
renamed to _message_broker

2020-12-14 13:29 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +    An interface that creates message brokers
comment updated

2020-12-14 13:30 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +            Conf.load('global', Json('/etc/cortx/message_bus.json'))
updated to conf

2020-12-14 13:32 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        """
taken care

2020-12-14 13:49 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +            message_broker_factory = MessageBrokerFactory(self.message_broker['type'])
instance created for this class

2020-12-14 13:49 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def __init__(self, message_bus, consumer_id=None, consumer_group=None, message_type=None, offset=None):
added parameter type

2020-12-14 13:50 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_message_bus_basic.py
> +sys.path.insert(1, '../../')
Removed

2020-12-14 13:51 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +            self.message_broker = Conf.get('global', 'message_broker')
did this way using '.'

2020-12-14 13:53 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/kafka_producer.py
> +#!/usr/bin/env python3
renamed with prefix 'test_'

2020-12-14 13:53 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/kafka_consumer.py
> +#!/usr/bin/env python3
renamed with prefix 'test_'

2020-12-14 13:53 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +    def __init__(self, message_broker):
added type

2020-12-14 13:55 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +    """
followed conventions

2020-12-14 13:55 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/__init__.py
> +from src.utils.message_bus.message_bus import MessageBus
taken care

2020-12-14 13:56 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_message_bus.py
> +sys.path.insert(1, '../../')
sure. will add it.

2020-12-14 14:30 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        self._bus_client = self._message_bus(self._client, **client_config)
added an interface get_client

2020-12-14 14:30 UTC, selvakumaar5496 commented on py-utils/src/utils/schema/__init__.py
> +
taken care

2020-12-14 14:31 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +    def __call__(self, client, **client_config):
added an interface get_client

2020-12-14 15:14 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/error.py
> +class MessageBusError(BaseError):
Implemented this structure

2020-12-14 15:15 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/__init__.py
> +from src.utils.message_bus.message_broker import MessageBroker, MessageBrokerFactory, KafkaMessageBroker
removed this import

2020-12-14 15:15 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +            raise MessageBusError(f"Invalid Broker. {e}")
added this snippet

2020-12-14 15:30 UTC, ujjwalpl requested changes

2020-12-14 15:30 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +
Need to add Ack() interface as per the Spec.

2020-12-14 15:30 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +    def __init__(self, config):
Conf value should be resolved in the MessageBroker itself. 
```
def __init__(self, message_servers: list(str)): 
```
or 
```
def __init__(self, **mb_config):
    mb_servers = mb_config['message_broker_servers'] 
    mb_xxx = mb_config['message_broker_xxx']
```

2020-12-14 16:00 UTC, ujjwalpl requested changes

2020-12-14 16:00 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +    def __call__(self, client, **client_config):
Change this interface to get_client()

2020-12-15 05:42 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.producer = Producer(**self.config)
producer_id is set to client.id

2020-12-15 05:43 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.consumer = Consumer(**self.config)
consumer_id is set to client.id

2020-12-15 05:43 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.consumer.subscribe(self.message_type)
confluent works based on subscription

2020-12-15 07:42 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +    def __call__(self, client, **client_config):
changed this interface

2020-12-15 07:52 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +        servers = ','.join([str(server) for server in config.get('global', 'message_broker')['servers']])
handled in super class MessageBroker

2020-12-15 08:05 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +    def __init__(self, config):
read in MessageBroker

2020-12-15 13:52 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_message_bus.py
> +#!/usr/bin/env python3
added these test cases

2020-12-15 13:53 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.producer = Producer(**self.config)
not ignored. Mapping the config to confluent Producer interface

2020-12-15 13:54 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +                self.config['enable.auto.commit'] = False
will make it configurable

2020-12-15 13:54 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +class KafkaMessageBroker(MessageBroker):
ack is implemented

2020-12-15 13:55 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +                if client_config['offset']:
validated all strings, will make it configurable.

2020-12-15 13:58 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +                    yield ConsumerRecord(msg.topic(), msg.value(), msg.partition(), msg.offset(), str(msg.key()))
returns list of named tuple to be conscious of message_type, offset etc

2020-12-15 13:58 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +
Implemented ack

2020-12-15 14:28 UTC, ujjwalpl requested changes

2020-12-15 14:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +    def __init__(self):
MessageBrokerFactory will never be instantiated. Please remove this interface.

2020-12-15 14:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +        try:
Reason we have _brokers is to cache the broker and return next time someone tries to get instance. 

```
if broker_type in MessageBrokerFactory._brokers.keys(): 
    return _broker[broker_type]
```

2020-12-15 14:28 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +                    if broker_type == cls.name:
```
if broker_type == cls.name:
    message_broker = cls(Conf)
    self._brokers[broker_type] = message_broker
    return message_broker
```

2020-12-15 16:08 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/exceptions.py
> +class MessageBusError(BaseError):
Implemented as per new comments

2020-12-15 16:08 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_message_bus_basic.py
> +def main():
that file from old patch and is deleted.

2020-12-15 16:10 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +    def __init__(self):
Removed this interface

2020-12-15 16:12 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +        try:
stored in _brokers

2020-12-15 16:12 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +                    if broker_type == cls.name:
stored in _brokers

2020-12-16 06:23 UTC, closed without merging