Conf store/feature/kv store factory
Seagate/cortx-utils pull request #125
Opened 2020-12-11 17:28 UTC by suryakumar1024

KvStoreFactory class added
KvStore code refactor
Removed confcache class

2020-12-11 18:00 UTC, ujjwalpl requested changes

2020-12-11 18:00 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/error.py
> +    def __init__(self, rc, desc):
This is not in line with the example, I gave you. The Convention is "ModuleError", i.e. KvStoreError. It should be... 

```
class KvStoreError(Exception):
    def __init__(self, rc, message, *args):
        self._rc = rc
        self._message = message % (args)

    def __str__(self):
        return "%d: %s" %(self._rc, self._message)
```

2020-12-11 18:00 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_kv_storage.py
> +    '''
Please use """ style as that is used in all the other place. Please be consistent

2020-12-11 18:00 UTC, ujjwalpl commented on py-utils/src/utils/kvstore/kvstore.py
> +#     read store delete
Remove this code.

2020-12-11 18:01 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_storage_collections.py
> +class TextKvStorage(FileKvStorage):
Please add class description to all the classes

2020-12-11 18:05 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_storage_collections.py
> +class JsonMessageKvStorage(JsonKvStorage):
Add Class Description.

2020-12-11 18:07 UTC, ujjwalpl commented on py-utils/test/kv_store/test_kv_store.py
> +print(kv_store.load())
Please write tests for all the file format. 

test_file_kv_store.c - Cover all file format.

2020-12-11 18:07 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_storage_factory.py
> +# CORTX Python common library.
Copyright should be at the top.

2020-12-11 18:08 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_kv_storage_factory.py
> +            "json": JsonKvStorage, "yaml": YamlKvStorage, "toml": TomlKvStorage
This does not follow the source code I sent as an example.

2020-12-11 18:09 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_kv_storage_factory.py
> +class FileKvStorageFactory:
Merge this class into file_kv_storage.py refer to the example I sent

2020-12-11 18:13 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/file_kv_storage_factory.py
> +#!/bin/python3
Copyright ???

2020-12-14 16:58 UTC, ujjwalpl requested changes

2020-12-14 16:58 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/error.py
> +# TODO: Test Code - To be removed
Please remove this code.

2020-12-14 16:58 UTC, ujjwalpl commented on py-utils/test/kv_store/conf_sample_json.py
> +sample_config={
This is a JSON file and not a python file. Rename to sample_conf.json.

2020-12-14 16:58 UTC, ujjwalpl commented on py-utils/test/kv_store/test_kv_store.py
> +from __future__ import absolute_import
Add a blank line above this.

2020-12-14 16:58 UTC, ujjwalpl commented on py-utils/test/kv_store/test_kv_store.py
> +    with open(r'/tmp/sample.yaml', 'w+') as file:
Where is the sample.yaml file ? You need to ensure you copy them to /tmp in the test or test will fail.

2020-12-14 17:04 UTC, ujjwalpl requested changes

2020-12-14 17:04 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +            raise KvStoreError(errno.EINVAL, "Mismatched keys & values %s:%s",\
raise KvStoreError(errno.EINVAL, f"Mismatched keys & values %s:%s",\

2020-12-14 17:04 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        raise KvStoreError(errno.ENOSYS, "%s:load() not implemented", \
raise KvStoreError(errno.ENOSYS, f"%s:load() not implemented", \

2020-12-14 17:04 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        raise KvStoreError(errno.ENOSYS, "%s:dump() not implemented", \
raise KvStoreError(errno.ENOSYS, f"%s:dump() not implemented", \

2020-12-14 17:04 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_factory.py
> +        raise KvStoreError(errno.EINVAL, "Invalid store type %s", store_type)
raise KvStoreError(errno.EINVAL, f"Invalid store type %s", store_type)

2020-12-15 04:36 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/file_kv_storage.py
> +    '''
This file was removed from currect kvstore code.

2020-12-15 04:37 UTC, suryakumar1024 commented on py-utils/test/kv_store/test_kv_store.py
> +from src.utils.kv_store import KvStoreFactory
Yes updated. And followed the same format as you said.

2020-12-15 05:44 UTC, ujjwalpl requested changes

2020-12-15 05:44 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def load(self):
```
    def load(self) -> dict:
```

2020-12-15 05:44 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def load(self):
```
    def load(self) -> dict:
```

2020-12-15 06:26 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_storage_collections.py
> +class TextKvStorage(FileKvStorage):
This file was removed in current patch

2020-12-15 06:27 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_storage_collections.py
> +class JsonMessageKvStorage(JsonKvStorage):
Added and updated.

2020-12-15 06:27 UTC, suryakumar1024 commented on py-utils/test/kv_store/test_kv_store.py
> +print(kv_store.load())
Done with the test cases and updated the same in current patch

2020-12-15 06:28 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_storage_factory.py
> +# CORTX Python common library.
updated in current patch.

2020-12-15 06:28 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/file_kv_storage_factory.py
> +            "json": JsonKvStorage, "yaml": YamlKvStorage, "toml": TomlKvStorage
Current patch doesn't has this file

2020-12-15 06:29 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/file_kv_storage_factory.py
> +class FileKvStorageFactory:
Current patch doesn't has this file

2020-12-15 06:29 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/file_kv_storage_factory.py
> +#!/bin/python3
Current patch doesn't has this file. But added on all other files

2020-12-15 08:00 UTC, suryakumar1024 commented on py-utils/test/kv_store/test_kv_store.py
> +    with open(r'/tmp/sample.yaml', 'w+') as file:
w+ will checks for file if not exist it will create that file. So only i used that way of writing file.

2020-12-15 08:01 UTC, suryakumar1024 commented on py-utils/test/kv_store/test_kv_store.py
> +from __future__ import absolute_import
Updated in recent patch.

2020-12-15 08:02 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/error.py
> +# TODO: Test Code - To be removed
Updated in recent patch

2020-12-15 08:19 UTC, suryakumar1024 commented on py-utils/test/kv_store/conf_sample_json.py
> +sample_config={
Updated in current patch

2020-12-15 08:19 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def load(self):
updated in current patch

2020-12-15 08:20 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def load(self):
updated in current patch

2020-12-15 08:20 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_factory.py
> +        raise KvStoreError(errno.EINVAL, "Invalid store type %s", store_type)
updated in current patch

2020-12-15 08:20 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +        raise KvStoreError(errno.ENOSYS, "%s:dump() not implemented", \
updated in recent patch

2020-12-15 08:20 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +        raise KvStoreError(errno.ENOSYS, "%s:load() not implemented", \
updated in recent patch

2020-12-15 08:20 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +            raise KvStoreError(errno.EINVAL, "Mismatched keys & values %s:%s",\
updated in recent patch

2020-12-15 08:22 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/error.py
> +    def __init__(self, rc, desc):
Updated and pushed the code to repo

2020-12-16 05:08 UTC, suryakumar1024 commented on py-utils/src/utils/kvstore/kvstore.py
> +#     read store delete
No this was old existing code we kept out new code in kv_sore directory. If you are ok with then i will remove this kvstore directory from this check-in. Kindly confirm

2020-12-16 05:08 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_storage_factory.py
> +class KvStoreFactory:
Merged and updated in current patch

2020-12-16 08:00 UTC, ujjwalpl commented on py-utils/src/utils/kvstore/kvstore.py
> +#     read store delete
My point we should not make any changes to kvstore/kvstore.c. Please remove this from your patch.

2020-12-16 08:09 UTC, ujjwalpl approved these changes

2020-12-21 10:01 UTC, suryakumar1024 commented
Closing this PR. Since ujjwal already merged this KvStore code 
PR: https://github.com/Seagate/cortx-utils/pull/129

2020-12-21 10:01 UTC, closed without merging