Passed test cases
Seagate/cortx-utils pull request #128
Opened 2020-12-16 06:15 UTC by selvakumaar5496

2020-12-16 06:28 UTC, ujjwalpl approved these changes

2020-12-17 07:17 UTC, ujjwalpl requested changes

2020-12-17 07:17 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +        print(self._desc)
Please remove this print.

2020-12-17 07:27 UTC, ujjwalpl requested changes

2020-12-17 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +class MessageBroker:git
Why ":git" ?

2020-12-17 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +        # TODO: Handle ports
Remove TODO

2020-12-17 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            for entry in ['offset', 'consumer_group', 'message_type', 'auto_ack']:
add group.id to the list for validation.

2020-12-17 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def send(self, message_type: str, method: str, messages: list, client_id: str):
Call it producer_id and as first parameter
```
    def send(self, producer_id: str, message_type: str, method: str, messages: list):
```

2020-12-17 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, client_id, timeout=0.5) -> list:
```
    def receive(self, consumer_id: str, timeout=0.5) -> list:
```

2020-12-17 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +
Remove this blank line.

2020-12-17 07:40 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/error.py
> +        print(self._desc)
happened while rebasing

2020-12-17 07:40 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +class MessageBroker:git
happened while rebasing

2020-12-17 07:47 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +
cleared

2020-12-17 07:48 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +        # TODO: Handle ports
Removed

2020-12-17 07:50 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            for entry in ['offset', 'consumer_group', 'message_type', 'auto_ack']:
validated

2020-12-17 07:50 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def send(self, message_type: str, method: str, messages: list, client_id: str):
added as first parameter

2020-12-17 07:50 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, client_id, timeout=0.5) -> list:
renamaed to consumer_id

2020-12-17 09:42 UTC, ujjwalpl requested changes

2020-12-17 09:42 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +        self._servers = ','.join(x["server"]+':'+x['port'] for x in \
```
self._servers = ','.join(x['server']+':'+x['port'] for x in 
```

2020-12-17 10:00 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker.py
> +        self._servers = ','.join(x["server"]+':'+x['port'] for x in \
Implemented single quote in all required places, to look consistent

2020-12-17 10:05 UTC, ujjwalpl requested changes

2020-12-17 10:05 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def send(self, messages: str):
def send(self, messages: list):

2020-12-17 10:05 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def send(self, messages: list):
Remove this interface. Not required.

2020-12-17 10:05 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def receive(self) -> list:
Remove this interface. Not required.

2020-12-17 10:05 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def ack(self):
Remove this interface. Not required.

2020-12-17 10:09 UTC, ujjwalpl requested changes

2020-12-17 10:09 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def ack(self, consumer_id:str):
```
def ack(self, consumer_id: str):
```

2020-12-17 10:13 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def receive(self) -> list:
removed

2020-12-17 10:13 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def ack(self):
removed

2020-12-17 10:13 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def ack(self, consumer_id:str):
indented

2020-12-17 10:13 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def send(self, messages: list):
removed

2020-12-17 10:14 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def send(self, messages: str):
changed type here and message_bus as well

2020-12-17 10:20 UTC, ujjwalpl requested changes

2020-12-17 10:20 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            sys.stderr.write('%% Aborted by user\n')
Remove write. You are not allowed to print onto the screen. You only can return MessageBusError

2020-12-17 10:20 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EINVAL, "init_client is not called")
raise MessageBusError(errno.EINVAL, "Consumer %s not initialized" %consumer_id)

2020-12-17 10:20 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                producer.flush()
We need have only one flush remove flush if sync is not specified.

2020-12-17 10:20 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EINVAL, "init_client is not called")
raise MessageBusError(errno.EINVAL, "Producer %s is not initialized" %producer_id)

2020-12-17 10:20 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    raise MessageBusError(errno.EINVAL, "Missing conf entry %s"\
Comma needs to with previous line. 

raise MessageBusError(errno.EINVAL, "Missing conf entry %s", \

2020-12-17 10:20 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            for entry in ['offset', 'consumer_group', 'message_type', 'auto_ack'\
```
for entry in ['offset', 'consumer_group', 'message_type', 'auto_ack', \
```

2020-12-17 10:23 UTC, ujjwalpl requested changes

2020-12-17 10:23 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +ConsumerRecord = namedtuple("ConsumerRecord", ["message_type", "message",\
```
ConsumerRecord = namedtuple("ConsumerRecord", ["message_type", "message", \
```

2020-12-17 10:38 UTC, ujjwalpl requested changes

2020-12-17 10:38 UTC, ujjwalpl commented on py-utils/test/test_message_bus/test_multiple_consumers.py
> +        #consumer.ack()
Remove commented code.

2020-12-17 10:45 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    raise MessageBusError(errno.EINVAL, "Missing conf entry %s"\
taken care

2020-12-17 10:46 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            for entry in ['offset', 'consumer_group', 'message_type', 'auto_ack'\
space added

2020-12-17 10:46 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +ConsumerRecord = namedtuple("ConsumerRecord", ["message_type", "message",\
space added

2020-12-17 10:46 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_multiple_consumers.py
> +        #consumer.ack()
added this code

2020-12-17 10:47 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EINVAL, "init_client is not called")
altered statement

2020-12-17 10:47 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EINVAL, "init_client is not called")
altered statement

2020-12-17 11:04 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                producer.flush()
removed

2020-12-17 11:05 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            sys.stderr.write('%% Aborted by user\n')
if i raise MessageBusError, My test case wont pass since it catches an Error

2020-12-17 11:44 UTC, ujjwalpl requested changes

2020-12-17 11:44 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            sys.stderr.write('%% Aborted by user\n')
write is not an option for us. This is a service and does not have tty attached. 
Your test can catch MessageBus error.

2020-12-17 13:52 UTC, ujjwalpl requested changes

2020-12-17 15:05 UTC, ujjwalpl requested changes

2020-12-17 15:05 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    raise MessageBusError(errno.EINVAL, "Missing conf entry \
```
raise MessageBusError(errno.EINVAL, "Missing conf entry %s", entry)
```
Please note its comma. We need to pass message_format and args to the exception 
Please fix this at all the places.

2020-12-17 15:57 UTC, ujjwalpl approved these changes

2020-12-18 12:38 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        consumer.commit()
async=false

2020-12-21 04:30 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        consumer.commit()
Hi Ajay. Implemented async on commit

2020-12-21 05:42 UTC, ajaysrivas approved these changes

2020-12-22 05:23 UTC, closed without merging