Conf store changes
Seagate/cortx-utils pull request #130
Opened 2020-12-17 17:25 UTC by suryakumar1024

Conf Store changes:
Updated conf_store file and added conf class which works on top of conf_store
fixed numeric key value handling.
fixed file load.
updated test cased for both ConfStore and Conf.

2020-12-17 17:35 UTC, ujjwalpl requested changes

2020-12-17 17:35 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    """  Represents a YAML File Store """
INI File Store

2020-12-17 17:35 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kvstore.py
> +#!/bin/python3
Remove this file. This is not needed any more. There is already a kv_store.py.

2020-12-17 17:35 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/pillar.py
> +#!/bin/python3
Remove this. This is already a part of kv_store_collection.py

2020-12-17 17:35 UTC, ujjwalpl commented on py-utils/test/conf_store_example.py
> +import sys
Remove this file. test should only contain test cases not the example code. 
OR 
convert this into a test using test format.

2020-12-17 17:35 UTC, ujjwalpl commented on py-utils/test/conf_store_example.py
> +from src.utils.conf_store import ConfStore, KvStorageFactory, KvStore
from cortx.utils.conf_store

2020-12-17 17:35 UTC, ujjwalpl commented on py-utils/test/test_conf_store/test_conf_store.py
> +        result_data = conf_store.get('test_local', 'bridge.no_name_field', default_val=None)
Follow 80 char limit

2020-12-17 17:38 UTC, ujjwalpl requested changes

2020-12-17 17:38 UTC, ujjwalpl commented on py-utils/test/test_conf_store/test_conf.py
> +conf = Conf()
No need to instantiate Conf class. You can directly use it.

2020-12-17 17:43 UTC, ujjwalpl requested changes

2020-12-17 17:43 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +                if type(data[key]) == str or type(data[key]) == int: self._keys.append(nkey)
Follow indentation

2020-12-17 17:43 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +CONF_CACHE = ConfCache
No need to declare this. Pls remove

2020-12-17 17:43 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +    def get(self, key: str):
We can add key=None condition here. 

``` 
def get(self, key: str = None):
    if key is None: return self._data
    return self._get(self._data, key)
```

2020-12-17 17:43 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        if key is not None:
This condition can be delegated down to conf_cache.

2020-12-17 17:43 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kvstore.py
> +#!/bin/python3
Removed from kv_store in current patch. I have already removed but still i can see this file.

2020-12-17 17:43 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/pillar.py
> +#!/bin/python3
Removed from kv_store in current patch.

2020-12-17 17:44 UTC, suryakumar1024 commented on py-utils/test/conf_store_example.py
> +import sys
Already testcases created for this package. So removed in current patch

2020-12-17 17:44 UTC, suryakumar1024 commented on py-utils/test/conf_store_example.py
> +from src.utils.conf_store import ConfStore, KvStorageFactory, KvStore
This file was removed.

2020-12-17 17:52 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf.py
> +conf = Conf()
Updated in current patch

2020-12-17 17:54 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +                if type(data[key]) == str or type(data[key]) == int: self._keys.append(nkey)
Update in current patch.

2020-12-17 17:54 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_store.py
> +        result_data = conf_store.get('test_local', 'bridge.no_name_field', default_val=None)
Update in current patch

2020-12-17 17:54 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    """  Represents a YAML File Store """
Update in current patch

2020-12-17 18:29 UTC, ujjwalpl requested changes

2020-12-17 18:29 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                          key, ex)
Use single tab only.

2020-12-17 18:29 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                                        f"Key not present")
Use single tab

2020-12-18 07:10 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        if key is not None:
Updated. Move this condition to Conf_cache

2020-12-18 07:10 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +    def get(self, key: str):
Updated same with the code

2020-12-18 07:10 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                          key, ex)
Updated in current patch

2020-12-18 07:10 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                                        f"Key not present")
updated in current patch

2020-12-18 07:10 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +CONF_CACHE = ConfCache
Updated in current patch

2020-12-18 10:03 UTC, suryakumar1024 commented
I have raised new PR as requested by ujjwal. new PR link https://github.com/Seagate/cortx-utils/pull/131

2020-12-18 10:03 UTC, closed without merging