ConfStore Phase1
Seagate/cortx-utils pull request #131
Opened 2020-12-18 10:02 UTC by suryakumar1024

Includes :
ConfStore class
Conf Class
Test cases for both ConfStore and Conf classes

2020-12-21 05:38 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +        if key is None:
Fixed in current patch. That If key is None: condition is not required here as i already handled it in the same get method itself.

2020-12-21 09:05 UTC, ujjwalpl approved these changes

2020-12-21 11:14 UTC, ajaysrivas approved these changes

2020-12-21 11:57 UTC, ujjwalpl requested changes

2020-12-21 11:57 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +                key = next(i_src)
Please remove this and change to the logic as per the patch I sent.

2020-12-21 15:49 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +                key = next(i_src)
Updated in current patch.

2020-12-22 03:18 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_cache.py
> +        self._delete(self._data, key)
After deleting the key, shouldn't we mark as dirty (like the way it has been done for set operation) ?

2020-12-22 03:23 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_store.py
> +        Paraeters:
Add comment here (which was wrongly mentioned for other method):
Obtain value for the key from given configuration

2020-12-22 03:25 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_store.py
> +        Obtain value for the given configuration
Incorrect comment, we are setting value here, not obtaining

2020-12-22 03:43 UTC, sachinpunadikar requested changes
Few comments, address them as appropriate

2020-12-22 05:26 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        Obtain value for the given configuration
Updated comment in current patch

2020-12-22 05:26 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        Paraeters:
Updated comment in current patch

2020-12-22 05:26 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +        self._delete(self._data, key)
Updated and added this logic in current patch

2020-12-22 05:38 UTC, sachinpunadikar approved these changes
Looks good to me

2020-12-22 05:49 UTC, ujjwalpl requested changes

2020-12-22 05:49 UTC, ujjwalpl commented on py-utils/setup.py
> +                'cortx.utils.test_kv_store',
You dont need to export test_kv_store. test should not even be part of rpm. This is why its outside of src.

2020-12-22 06:01 UTC, suryakumar1024 commented on py-utils/setup.py
> +                'cortx.utils.test_kv_store',
Updated in current patch @ujjwalpl

2020-12-22 06:57 UTC, ujjwalpl approved these changes

2020-12-22 07:17 UTC, merged