Cs delim changes
Seagate/cortx-utils pull request #142
Opened 2020-12-28 12:17 UTC by suryakumar1024

Updated default delim to '>'
Delim is configurable at init method for both Conf and __init__ constructor for ConfStore classes
Updated KvStore to handle configurable delim

2020-12-28 12:47 UTC, ujjwalpl requested changes

2020-12-28 12:47 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def __init__(self, store_loc, store_path, delim):
def __init__(self, store_loc, store_path, delim='>'):

2020-12-28 13:24 UTC, ujjwalpl requested changes

2020-12-28 13:24 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        """
"""
        kvstore will be initialized at the time of load
        delim is used to split key into hierarchy, e.g. "k1>2" or "k1.k2"
        """

2020-12-28 13:24 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +                                 index)
Fix indentation

2020-12-28 13:24 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        delim: defines how to split the given key chain
"""
    kvstore will be initialized at the time of load
    delim is used to split key into hierarchy, e.g. "k1>2" or "k1.k2"
    """

2020-12-28 13:24 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        delim: defines how to split the given key chain
"""
Args:
data: Dictionary representing keys (hierarchical) and values
delim: It is used to split key into hierarchy, e.g. "k1>2" or "k1.k2"
"""

2020-12-28 13:24 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        store_loc: store location
"""
Args:
...
delim: It is used to split key into hierarchy, e.g. "k1>2" or "k1.k2"
"""

2020-12-28 13:26 UTC, ujjwalpl requested changes

2020-12-28 13:26 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def __init__(self, store_loc, store_path, delim):
def __init__(self, store_loc, store_path, delim='>':

2020-12-28 13:48 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def __init__(self, store_loc, store_path, delim):
Updated same in current patch.

2020-12-28 13:48 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +                                 src_index)
Updated same in current patch.

2020-12-28 13:48 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        """
Updated same in current patch.

2020-12-28 13:49 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +                                 index)
this was auto indented by editor.

2020-12-28 13:50 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +        delim: defines how to split the given key chain
Updated same in current patch.

2020-12-28 13:50 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +        delim: defines how to split the given key chain
This comment was updated in current patch.

2020-12-28 13:50 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +        store_loc: store location
Updated same in current patch.

2020-12-28 13:50 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def __init__(self, store_loc, store_path, delim):
Updated same in current patch.

2020-12-29 04:39 UTC, ujjwalpl requested changes

2020-12-29 04:39 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +from cortx.utils.kv_store.kv_store import KvStore, KvData
conf_cache.py does not use KvData. Please remove this.

2020-12-29 04:53 UTC, ujjwalpl requested changes

2020-12-29 04:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +                                 index)
Indentation.

2020-12-29 05:26 UTC, ujjwalpl requested changes

2020-12-29 05:26 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +                                 index)
Please use editor settings

2020-12-29 06:10 UTC, ujjwalpl requested changes

2020-12-29 06:10 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +            if hasattr(cls, 'name') and name != "KvStore" \
Change this condition to ... 
```
if hasattr(cls, 'name') and cls.name == store_type:
    KvStoreFactory._stores[store_url] = \
        cls(store_loc, store_path, delim)
```

2020-12-29 06:11 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +                                 index)
Updated in current patch

2020-12-29 06:11 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +from cortx.utils.kv_store.kv_store import KvStore, KvData
Updated in current patch

2020-12-29 06:11 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +                                 index)
Fixed and updated in current patch

2020-12-29 06:13 UTC, ujjwalpl requested changes

2020-12-29 06:13 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def __init__(self, configparser, delim=">"):
For single char/word use single quote
```
def __init__(self, configparser, delim='>'):
```

2020-12-29 06:18 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +            if hasattr(cls, 'name') and name != "KvStore" \
i added name !="KvStore" since KvStore class dosen't have name attribute which will through error. that's why added this condition. Kindly let me know if you want me to change it anyway.

2020-12-29 06:22 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def __init__(self, configparser, delim=">"):
updated the same in current patch.

2020-12-29 06:40 UTC, ujjwalpl requested changes

2020-12-29 06:40 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        if index in self._cache.keys() and not overwrite:
Need to handle kwargs

```
        overwrite = False
        for key, val in kwargs.items():
            if key == 'overwrite':
                overwrite = True
            elif key == 'callback':
                self._callbacks[index] = val // add self._callbacks = {} in the init for this
            else:
                raise ConfStoreError("Invalid parameter %s", key)
```

2020-12-29 06:42 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +            if hasattr(cls, 'name') and name != "KvStore" \
No! This is not correct. If KvStore class dosen't have name attribute, first condition should evaluate to false and second condition wont be looked at.

2020-12-29 07:17 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        if index in self._cache.keys() and not overwrite:
Updated same in current patch

2020-12-29 07:27 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +            if hasattr(cls, 'name') and name != "KvStore" \
Ok im updating the condition.

2020-12-29 07:27 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +            if hasattr(cls, 'name') and name != "KvStore" \
Updated

2020-12-29 08:19 UTC, ujjwalpl requested changes

2020-12-29 08:19 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +                raise ConfStoreError("Invalid parameter %s", key)
raise ConfStoreError(errno.EINVAL, "Invalid parameter %s", key)

2020-12-29 09:06 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +                raise ConfStoreError("Invalid parameter %s", key)
Updated in current patch.

2020-12-29 11:40 UTC, ujjwalpl requested changes

2020-12-29 11:40 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        Args:
```
"""
Args:
store_loc:  store location
store_path: store path from where to load data
delim:      It is used to split key into hierarchy, e.g. "k1>2" or  "k1.k2"
""""
```

2020-12-29 11:48 UTC, ujjwalpl requested changes

2020-12-29 11:48 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        """ Initializing KvStoreFactory"""
```
""" Initializing KvStoreFactory """
```

2020-12-29 11:48 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        """ Deletes given set of keys from the store"""
""" Deletes given set of keys from the store """

2020-12-29 12:29 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +        Args:
Updated in current patch

2020-12-29 12:30 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +        """ Initializing KvStoreFactory"""
Updated in current patch

2020-12-29 12:30 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +        """ Deletes given set of keys from the store"""
Updated current patch

2020-12-29 12:52 UTC, ujjwalpl approved these changes

2020-12-30 09:01 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_store.py
>          callback:  Callback for the config changes in the KV Sto
Correct the comment. It should be "KV Store" instead of "KV Sto"

2020-12-30 09:11 UTC, sachinpunadikar requested changes
A minor change reqd

2020-12-30 09:32 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
>          callback:  Callback for the config changes in the KV Sto
Updated in current patch

2020-12-30 11:16 UTC, sachinpunadikar approved these changes
+1

2020-12-30 11:18 UTC, merged