Message Bus Purge Implementation
Seagate/cortx-utils pull request #143
Opened 2020-12-28 16:24 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

2020-12-29 05:08 UTC, ujjwalpl requested changes

2020-12-29 05:08 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def delete(self, message_type: str):
This interface does not match the specification. 

`def delete(self, message_type: str, **criteria):`

Fix the Spec as well.

2020-12-29 05:11 UTC, ujjwalpl requested changes

2020-12-29 05:11 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def delete(self, filters: str):
def delete(self, **criteria):

2020-12-29 05:18 UTC, ujjwalpl requested changes

2020-12-29 05:18 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        resource.set_config('retention.ms', 604800000)
Avoid hard coding in the code. You need to reset is back to original value and not the hard coded one. 

```
saved_retention = resource.get_config('retention.ms')
resource.set_config('retention.ms', 1)
self._admin.alter_configs([resource])
resource.set_config('retention.ms', saved_retention)
self._admin.alter_configs([resource])
```

2020-12-29 05:22 UTC, ujjwalpl requested changes

2020-12-29 05:22 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        self._admin.alter_configs([resource])
Why is return of self._admin.alter_configs([resource]) not handled ?

2020-12-29 08:45 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        resource.set_config('retention.ms', 604800000)
called describe_config(get_config) to get the default value. Taken care

2020-12-29 08:54 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        self._admin.alter_configs([resource])
handled this alter_config

2020-12-29 08:55 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def delete(self, filters: str):
changed to kwargs params

2020-12-29 12:48 UTC, ujjwalpl approved these changes

2020-12-30 11:53 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        saved_retention = int(default_configs['retention.ms'].__dict__['value'])
This can be saved at the time of instantiating. This is going to be fixed for the setup. So we can avoid this call for every delete request.

2020-12-30 11:57 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EINVAL, "Unknown configuration for \
I suppose here we found that original retention period is not restored. So it means that all new messages will have retention period of 1 ms.
This is not acceptable. Better destroy the topic & recreate. @ajaysrivas your view on this

2020-12-30 12:00 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def delete(self, **criteria: dict):
Either do not accept criteria or log a message that criteria is not supported.
This will mislead users.

2020-12-30 12:02 UTC, sachinpunadikar commented on py-utils/test/test_message_bus/test_purge.py
> +        producer.delete(filters=None)
Not clear on how you are verifying that messages are deleted indeed.

2020-12-30 12:03 UTC, sachinpunadikar requested changes
Work on the comments

2020-12-30 12:35 UTC, ajaysrivas commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EINVAL, "Unknown configuration for \
If there is an error, then the operation can be retried. What if creation of topic fails after topic is deleted?

2020-12-30 12:49 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EINVAL, "Unknown configuration for \
Good suggestion @ajaysrivas 
@selvakumaar5496  please rewrite the code for 3 attempts, and if still failure then raise exception.

2020-12-30 13:42 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EINVAL, "Unknown configuration for \
Above suggested idea is implemented

2020-12-30 13:44 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        saved_retention = int(default_configs['retention.ms'].__dict__['value'])
this part of code is moved to a place where producer is initialized

2020-12-30 13:44 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def delete(self, **criteria: dict):
Not accepting criteria for this patch. wil add in future patches

2020-12-30 13:45 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_purge.py
> +        producer.delete(filters=None)
A consumer check is done after deletion

2020-12-30 17:38 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        for i in range(0, 3):
consider using range(3)

2020-12-30 17:39 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        for i in range(0, 3):
Use range(3)

2020-12-30 17:43 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            conf = self._admin.describe_configs([self._resource])
Shouldn't we check success of "describe_conf" call ?

2020-12-30 17:45 UTC, sachinpunadikar requested changes
Please address the comments

2020-12-31 04:16 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        for i in range(0, 3):
altered

2020-12-31 04:17 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        for i in range(0, 3):
altered

2020-12-31 05:26 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            conf = self._admin.describe_configs([self._resource])
validated and handled exceptions

2020-12-31 06:20 UTC, sachinpunadikar approved these changes
+1

2020-12-31 06:20 UTC, merged