ConfStore cli interface program
Seagate/cortx-utils pull request #148
Opened 2021-01-11 08:07 UTC by suryakumar1024

Signed-off-by: surya <k.suryakumar1024@gmail.com>

py-utils/src/utils/conf_store/conf_cli.py has following code changes

2021-01-11 09:12 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_cli.py
> +import sys
Add copyright text here
Also add below as the first line  
#!/usr/bin/python3

2021-01-11 09:21 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_cli.py
> +parser.add_argument("key_value", help="key_value could be a list of single or"
its always not a key-value pair .. for get and delete its just key or list of keys, only for set it is kay-value pair(s)

2021-01-11 09:28 UTC, sachinpunadikar requested changes
work on the comments

2021-01-11 10:07 UTC, ujjwalpl requested changes

2021-01-11 10:07 UTC, ujjwalpl commented on README.md
> +We are excited about your interest in CORTX and hope you will join us. We take our community very seriously, and we are committed to creating a community built on respectful interactions and inclusiv
Where is the code to install CLI or include it in the rpm ?

2021-01-11 10:38 UTC, ujjwalpl requested changes

2021-01-11 10:38 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +parser.add_argument("url", help="Location of the config file")
parser.add_argument("url", help="URL of the config location")

2021-01-11 10:38 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +parser.add_argument("key_value", help="key_value could be a list of single or"
Correct. We need to call it kv_spec and have the usage printed accordingly. Refer to the spec.

2021-01-11 10:38 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +key_val = args.key_value
kv_spec = args.key_value
kv_list = kv_spec.split(';')

2021-01-11 10:46 UTC, ujjwalpl requested changes

2021-01-11 10:46 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +if command == "set":
Better to create a class. 
```
class ConfCli:
    _index = "conf_cli"
    def __init__(self, url):
        self._conf = Conf.load(self._index, url)

    def set(self, kv_list): 
        for kv in kv_list:
            key, val = kv.split('=')
            Conf.set(key, val)

    def get(self, key_list):
        val = []
        for key in key_list:
            val.append(Conf.get(key))
        return val
```

2021-01-11 10:49 UTC, ujjwalpl requested changes

2021-01-11 10:49 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +elif command == 'get_keys':
get_keys is not required for now.

2021-01-13 10:18 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +parser.add_argument("key_value", help="key_value could be a list of single or"
Updated in current patch

2021-01-13 10:18 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +
Updated in current patch

2021-01-13 10:25 UTC, suryakumar1024 commented on README.md
> +We are excited about your interest in CORTX and hope you will join us. We take our community very seriously, and we are committed to creating a community built on respectful interactions and inclusiv
Now the CLI will be install along with the cortx-py-utils package itself

2021-01-13 10:25 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +parser.add_argument("url", help="Location of the config file")
Updated in current patch

2021-01-13 10:26 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +key_val = args.key_value
updated in current patch

2021-01-13 10:28 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +if command == "set":
Handled in different way to fit in a single callable main function so as to link in setup.py

2021-01-13 10:30 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +elif command == 'get_keys':
updated in current patch

2021-01-13 11:35 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +import sys
Updated in current patch

2021-01-13 12:55 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_cli/__init__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Please correct the year as 2021

2021-01-13 12:55 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_cli/__main__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Update the year here as well

2021-01-13 13:02 UTC, sachinpunadikar requested changes
Minor comments, please work on the same

2021-01-14 04:59 UTC, sachinpunadikar approved these changes
+1

2021-01-14 05:01 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +if command == "set":
That is not correct. You can refer to the function with class as well. 
Class makes the code readable and manageable. 
Currently code looks difficult to read and unstructured.

2021-01-15 19:27 UTC, closed without merging

2021-01-15 19:28 UTC, ujjwalpl commented
This work is completed via another PR https://github.com/Seagate/cortx-utils/pull/155