EOS-16256:Create IEM class for storing IEM alert message.
Seagate/cortx-utils pull request #150
Opened 2021-01-12 12:39 UTC by Prabh2301

2021-01-12 16:27 UTC, sachinpunadikar commented on py-utils/src/utils/IEM_framework/IEM_framework.py
> +class IEM:
Need copyright text

2021-01-12 16:27 UTC, sachinpunadikar commented on py-utils/src/utils/IEM_framework/IEM_framework.py
> +    def __init__(self):
Constructor should accept all the parameters

2021-01-12 16:28 UTC, sachinpunadikar commented on py-utils/src/utils/IEM_framework/IEM_framework.py
> +        self.severity=severity
Add validation code for each argument being passed

2021-01-12 16:28 UTC, sachinpunadikar commented on py-utils/src/utils/IEM_framework/IEM_framework.py
> +
Add print method

2021-01-12 16:31 UTC, sachinpunadikar requested changes
Work on the review comments.
Additionally you need to add test cases for every dev code

2021-02-02 06:13 UTC, selvakumaar5496 requested changes

2021-02-09 07:12 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-07-07 04:40 UTC, sachinpunadikar commented
No more needed

2021-07-07 04:40 UTC, closed without merging