EOS 16418 : MessageBus confirms message deletion
Seagate/cortx-utils pull request #157
Opened 2021-01-18 13:20 UTC by selvakumaar5496

2021-01-18 14:35 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def __get_log__(self, message_type: str):
IMHO, __get_log_size__ would be proper name for this function

2021-01-18 14:57 UTC, ujjwalpl requested changes

2021-01-18 14:57 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            to_str = run_result[0].decode('utf-8')
Please give proper names to following based on the contents they store
1. to_str
2. x
3. l
4. e

2021-01-18 15:00 UTC, ujjwalpl requested changes

2021-01-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +            if Conf._payloads == {}:
No need to access internal variables of Conf, i.e. Conf._payloads. Use Conf as a black box.

2021-01-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    retention for %s", message_type)
Indentation missing.

2021-01-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        for i in range(1,7):
Change i to retry_count to make it more meaningful.

2021-01-18 16:23 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        for i in range(1,7):
renamed it to retry_count

2021-01-18 16:23 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    retention for %s", message_type)
indendation is taken care

2021-01-18 16:24 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def __get_log__(self, message_type: str):
changed the method name to **get_log_size**

2021-01-18 16:34 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            to_str = run_result[0].decode('utf-8')
renamed all variables

2021-01-19 04:51 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +            if Conf._payloads == {}:
removed this check. MessageBus can be instantiated only once

2021-01-19 06:03 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            """ Set retention to default value if fetching from admin fails """
admin  -> admin interface

2021-01-19 06:15 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            """ Set retention to default value if fetching from admin fails """
taken care as per suggestion

2021-01-19 06:26 UTC, sachinpunadikar approved these changes
+1

2021-01-20 08:08 UTC, saurabhkhanvilkar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            self._saved_retention = 604800000 if self._saved_retention == 1 \
can we use a variable (or macro; not sure if python supports macros) instead of such magic numbers? same in other places in this code change... some examples -
- self._saved_retention == 1
- for retry_count in range(1,7):
- if retry_count > 5:
it will be good to have a descriptive name instead of numbers...

2021-01-20 12:08 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            self._saved_retention = 604800000 if self._saved_retention == 1 \
changed numbers and used global variables

2021-01-20 15:01 UTC, ujjwalpl requested changes

2021-01-20 15:01 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            self._resource.set_config('retention.ms', MIN_MSG_RETENTION_TIME_MS)
For consistency 
```for i in range(3): --> for i in range(<var>):```

2021-01-20 15:14 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +DEFAULT_MSG_RETENTION_TIME_MS = 604800000
moved variables inside class as mentioned

2021-01-20 15:14 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            self._resource.set_config('retention.ms', MIN_MSG_RETENTION_TIME_MS)
consistency is maintained

2021-01-21 11:02 UTC, ujjwalpl approved these changes

2021-01-21 11:02 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        """ Gets size of log across all the partitions"""
""" Gets size of log across all the partitions """

2021-01-21 11:51 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        """ Gets size of log across all the partitions"""
fixed

2021-01-21 17:01 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_purge.py
> +                self.assertEqual(count, 10)
checks count after purge

2021-01-21 17:01 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            if retry_count > 5:
replaced numbers by constants

2021-01-21 17:16 UTC, saurabhkhanvilkar approved these changes

2021-01-21 17:19 UTC, saurabhkhanvilkar commented on py-utils/test/test_message_bus/test_purge.py
> +                self.assertEqual(count, 10)
ok...

2021-01-22 03:33 UTC, merged