EOS-16519 : Adding common utils functions
Seagate/cortx-utils pull request #161
Opened 2021-01-20 12:11 UTC by satish-seagate

Signed-off-by: Satish Darade <satish.darade@seagate.com>

2021-01-20 12:18 UTC, cdeshmukh reviewed
Add @ujjwalpl too as reviewer

2021-01-20 12:18 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> +            print(f"Failed to take action on {self._service} with an error : {err}")
print(f"Failed to {self._action} on {self._service} due to error : {err}")

2021-01-20 12:18 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> +            else:
check for disable specifically & then default case

2021-01-20 12:18 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> +            print(f"Failed to take action on {self._service} with an error : {err}")
print(f"Failed to {self._action} on {self._service} due to error : {err}")

2021-01-20 12:19 UTC, cdeshmukh commented
> Add @ujjwalpl too as reviewer

Ok Ujjwal is already there in reviewers list

2021-01-20 12:24 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +            print(f"Failed to take action on {self._service} with an error : {err}")
Done

2021-01-20 12:24 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +            else:
Done

2021-01-20 12:24 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +            print(f"Failed to take action on {self._service} with an error : {err}")
Done

2021-01-20 12:29 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> +                self.dbus_manager.EnableUnitFiles([f'{self._service}'], False, True)
where is default case, which will handle arguments beyond enable or disable ?

2021-01-20 12:46 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +                self.dbus_manager.EnableUnitFiles([f'{self._service}'], False, True)
Done

2021-01-20 12:47 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +                self.dbus_manager.EnableUnitFiles([f'{self._service}'], False, True)
https://github.com/Seagate/cortx-utils/pull/161/files#diff-b8b791d690e1f8b19c5e49f3b5a32ecf3e4fb22a31313e390fe9d4e82fa49389R33

2021-01-20 13:28 UTC, cdeshmukh approved these changes

2021-01-21 03:45 UTC, saurabhkhanvilkar requested changes

2021-01-21 03:45 UTC, saurabhkhanvilkar commented on py-utils/src/utils/service.py
> +
Please add some comments describing the added utility functions and their use.

2021-01-21 03:45 UTC, saurabhkhanvilkar commented on py-utils/src/utils/service.py
> +class Service:
Please add a comment describing this class

2021-01-21 03:45 UTC, saurabhkhanvilkar commented on py-utils/src/utils/service.py
> +class EnableDisableService(Service):
Please add a comment describing this class

2021-01-21 03:45 UTC, saurabhkhanvilkar commented on py-utils/src/utils/service.py
> +class SystemctlServiceAction(Service):
Please add a comment describing this class

2021-01-21 06:04 UTC, ujjwalpl requested changes

2021-01-21 06:04 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +class EnableDisableService(Service):
Please merge this class EnableDisableService and SystemctlServiceAction into the Service class itself. The derivation does not follow "_is_a_" true relation.

2021-01-21 09:03 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> +                error = "Please provide an appropriate action to be taken against the service."
include invalid action string as part of the error str

2021-01-21 09:24 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +        system_bus = dbus.SystemBus()
Done

2021-01-21 09:24 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +    def process(self, action: str, service_name: str):
Done

2021-01-21 09:24 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +                error = "Please provide an appropriate action to be taken against the service."
Added inline no 79.

2021-01-21 09:35 UTC, ujjwalpl requested changes

2021-01-21 09:35 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +                error = "Please provide an appropriate action to be taken against the service."
If you add the code above, you can remove this from here. This is so that we do not mix DBus error and this error.

2021-01-21 09:35 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +        try:
if action not in ['enable', 'disable', ....]: 
    raise ServiceError(errno.EINVAL, "Invalid action '%s' for the service %s" %(action, service_name))

Please note, do not use f" " string in exceptions.

2021-01-21 09:35 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +            raise ServiceError(errno.EINVAL, f"Failed to {action} on {service_name} due to error : {err}")
Please avoid f" " strings in Exceptions to allow it to be translated. 

raise ServiceError(<get DBus Error>, "Failed to perform dbus action. %s" %err)

2021-01-21 09:51 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +        try:
Done

2021-01-21 09:51 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +            raise ServiceError(errno.EINVAL, f"Failed to {action} on {service_name} due to error : {err}")
Done

2021-01-21 10:55 UTC, ujjwalpl requested changes

2021-01-21 10:55 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +        try:
I dont see this code yet. 

```
if action not in ['enable', 'disable', ....]:
raise ServiceError(errno.EINVAL, "Invalid action '%s' for the service %s" %(action, service_name))
```

2021-01-21 10:57 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +        try:
https://github.com/Seagate/cortx-utils/pull/161/files#diff-b8b791d690e1f8b19c5e49f3b5a32ecf3e4fb22a31313e390fe9d4e82fa49389R74
above code serving the same goal

2021-01-21 10:57 UTC, ujjwalpl requested changes

2021-01-21 10:57 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +    def process(self, action: str, service_name: str):
def process(self, action: str, **args):

2021-01-21 11:26 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +        try:
Done.

2021-01-21 11:26 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +    def process(self, action: str, service_name: str):
Done

2021-01-21 12:27 UTC, cdeshmukh approved these changes

2021-01-21 12:40 UTC, ujjwalpl requested changes

2021-01-21 12:40 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +            raise ServiceError(errno.EINVAL, "Invalid action '%s' for the service %s" %(action, service_name))
```
raise ServiceError(errno.EINVAL, "Invalid action '%s' for the service %s" \
    %(action, service_name))
```

2021-01-21 12:43 UTC, ujjwalpl requested changes

2021-01-21 12:43 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +            raise ServiceError(errno.EINVAL, "Failed to '%s' on '%s' due to error :%s" %(action, service_name, err))
Please do not exceed 80 chars. Also note. full stop after the message.
```
raise ServiceError(errno.EINVAL, "Failed to '%s' on '%s' due to error. %s" \
    %(action, service_name, err))
```

2021-01-21 13:09 UTC, ujjwalpl approved these changes

2021-01-21 16:47 UTC, saurabhkhanvilkar approved these changes

2021-01-21 17:08 UTC, sachinpunadikar approved these changes
+1

2021-01-21 17:09 UTC, merged