EOS-16423: S3 Mini-provisioner: Validations in post_install
Seagate/cortx-utils pull request #162
Opened 2021-01-20 15:54 UTC by pratyush-seagate

commit 125555be232337ef9c2ebac20d26ad26c158b69c
Author: pratyush-seagate <pratyush.k.khan@seagate.com>
Date:   Wed Jan 20 08:36:43 2021 -0700

        EOS-16423: S3 Mini-provisioner: Validations in post_install
        Change description:
                Add new validator APIs to check if services are running and if rpm or pip3 packages are installed on local or remote host
        Files edited/added:
                modified:   src/utils/validator/commands.py
                new file:   src/utils/validator/v_pkg.py
                new file:   src/utils/validator/v_service.py
                modified:   src/utils/validator/validate.py
                new file:   test/validator/test_pkg_validator.py
                new file:   test/validator/test_service_validator.py
        Testing done:
                Used newly created unit tests to verify the new APIs. used test_pkg_validator.py and test_service_validator.py
                        > pip3 uninstall dist/cortx_py_utils-1.0.0-py3-none-any.whl -y;  rm -rf dist/* ;  python3 setup.py bdist_wheel && pip3 install dist/

                        Successfully installed cortx-py-utils-1.0.0
                        .Password:
                        .Password:
                        Password:
                        ..
                        ----------------------------------------------------------------------
                        Ran 4 tests in 13.438s

                        OK
                        Password:
                        Password:
                        ..
                        ----------------------------------------------------------------------
                        Ran 2 tests in 4.679s

                        OK

    Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

2021-01-20 17:01 UTC, ujjwalpl requested changes

2021-01-20 17:01 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +def search_pkg(cmd):
Please avoid global functions.

2021-01-20 17:01 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +		if v_type == "validate_rpms":
v_type must not include "validate_"

2021-01-20 17:29 UTC, pratyush-seagate commented on py-utils/src/utils/validator/v_pkg.py
> +def search_pkg(cmd):
Addressed.

2021-01-20 17:29 UTC, pratyush-seagate commented on py-utils/src/utils/validator/v_pkg.py
> +		if v_type == "validate_rpms":
Addressed.

2021-01-20 17:33 UTC, ujjwalpl approved these changes

2021-01-21 06:54 UTC, AjinkyaDhumal commented on py-utils/README.md
> +
Please add below documentation for all the utility methods we are adding.
###
Short description about function usage
Description on the function paratmeters
Note, if any
###

2021-01-21 07:16 UTC, pratyush-seagate commented on py-utils/README.md
> +
Addressed.

2021-01-21 08:36 UTC, AjinkyaDhumal approved these changes

2021-01-21 16:54 UTC, sachinpunadikar approved these changes
+1

2021-01-21 17:01 UTC, merged