WIP: setup script for Mini provisioner for cortx-py-utils
Seagate/cortx-utils pull request #163
Opened 2021-01-21 15:37 UTC by sachinpunadikar

Enhance setup script to support post_install, config, test phases

2021-01-22 09:33 UTC, ujjwalpl requested changes

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/setup_cli.py
> +
Remove one extra line and keep only two blank lines

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +class UtilsError(Exception):
Lets rename this as SetupError(...). We Utils is generic.

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +def send_msg(message_bus, message):
Lets avoid global functions. We should make it a part of class. 

class MessageBusClient:
    __init__(message_bus)
    send_msg(message)
    receive_msg(message)

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +        print("topic created .. ")
We should not be printing anything from utils. Return 0 in case of success or SetupError() in case of error.

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +        print(msg)
Same here as well.

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +
Remote extra line. there should be just 2 blank lines.

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +            return 1
We need to delete the test topic in case of exception or at the end.

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +        cmd = "/root/kafka_2.13-2.7.0/bin/kafka-topics.sh --create" + \
Instead of preparing topic here, we can include it in the MessageBusClient class constructor and topic will be removed automatically in the descructor. This way no specific handling for deleting topic elsewhere.

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +
Use cortx.utils.validator for validation of packages like kafka here.

2021-01-22 09:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +        cmd = "/opt/kafka/bin/kafka-topics.sh --list --bootstrap-server "\
This can be moved to validation. cortx.utils.validator. src/utils/validator/service.py similar to v_elasticsearch.py

2021-01-22 09:34 UTC, ujjwalpl approved these changes

2021-01-22 17:35 UTC, sachinpunadikar commented on py-utils/src/utils/setup/setup_cli.py
> +
Done

2021-01-22 17:35 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +def send_msg(message_bus, message):
Done

2021-01-22 17:36 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +class UtilsError(Exception):
Done

2021-01-22 17:37 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        cmd = "/root/kafka_2.13-2.7.0/bin/kafka-topics.sh --create" + \
Done

2021-01-22 17:38 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        print("topic created .. ")
Done

2021-01-22 17:38 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        print(msg)
Done

2021-01-22 17:38 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +            return 1
Done

2021-01-22 17:38 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +
Done

2021-01-23 05:23 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +
Kafka is tar ball .. hence not going for package validation

2021-01-25 07:46 UTC, saurabhkhanvilkar approved these changes

2021-01-27 04:49 UTC, selvakumaar5496 requested changes

2021-01-27 04:49 UTC, selvakumaar5496 commented on py-utils/src/utils/setup/setup_cli.py
> +        """ Add Command args for parsing."""
""" Add Command args for parsing. """

2021-01-27 04:49 UTC, selvakumaar5496 commented on py-utils/src/utils/setup/utils.py
> +        """Sends a  message """
""" Sends a  message """

2021-01-28 03:50 UTC, sachinpunadikar commented on py-utils/src/utils/setup/setup_cli.py
> +        """ Add Command args for parsing."""
Done

2021-01-28 03:50 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        """Sends a  message """
Done

2021-01-28 04:20 UTC, suryakumar1024 commented on py-utils/src/utils/setup/utils.py
> +        except Exception as e:
If e is not used then we can remove that from here.

2021-01-28 04:23 UTC, selvakumaar5496 approved these changes

2021-01-28 04:24 UTC, selvakumaar5496 commented on py-utils/src/utils/setup/utils.py
> +        except Exception as e:
I hope this will come under codacy code analysis check.

2021-01-28 05:46 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        except Exception as e:
Done.

2021-01-28 06:15 UTC, suryakumar1024 approved these changes

2021-01-28 06:28 UTC, s-arya approved these changes

2021-01-28 06:29 UTC, merged