EOS-16507 : Receive API -  blocking and non-blocking
Seagate/cortx-utils pull request #167
Opened 2021-01-27 07:55 UTC by selvakumaar5496

2021-01-28 06:44 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                # if blocking is True, NoneType messages are ignored
In case of blocking call , on blocking == true, we should go back to consumer.poll again  
So here a while loop is needed. Exit the while loop when msg is not none.

2021-01-28 07:10 UTC, sachinpunadikar requested changes
Logic for blocking needs improvement

2021-02-01 06:47 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                # if blocking is True, NoneType messages are ignored
dealt with this change

2021-02-01 08:30 UTC, ujjwalpl requested changes

2021-02-01 08:30 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, consumer_id: str, blocking: bool, timeout=0.5) -> list:
Please add description about this interface.

2021-02-01 08:35 UTC, ujjwalpl requested changes

2021-02-01 08:35 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, consumer_id: str, blocking: bool, timeout=0.5) -> list:
Interface needs to be
receive(self, consumer_id: str, timeout=0.5)
 
If timeout == 0, then it should be blocking call. It does not make sense to add blocking as prameter.

2021-02-01 10:58 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, consumer_id: str, blocking: bool, timeout=0.5) -> list:
removed blocking parameter

2021-02-01 12:05 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        timeout = self._default_timeout if input_timeout == 0 else input_timeout
Should it be just 0 or 0.0 (this may be specific to C)?

2021-02-01 12:09 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        timeout = self._default_timeout if input_timeout == 0 else input_timeout
If input_timeout is none ( means no value passed), then what is the behavior ?

2021-02-01 12:11 UTC, sachinpunadikar requested changes
Work on the comments

2021-02-01 12:53 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        timeout = self._default_timeout if input_timeout == 0 else input_timeout
if input_timeout is none, timeout = 0.5 (refer py-utils/src/utils/message_bus/message_bus_client.py)

2021-02-01 14:09 UTC, ujjwalpl requested changes

2021-02-01 14:09 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, consumer_id: str, input_timeout: float) -> list:
Please rename input_timeout as "timeout". Even consumer_id is also input. 

Please add description indicating the meaning of input parameters
```
""" 
Receives list of messages from Kafka Message Server
Input Parameters: 
consumer_id - Consumer ID for which messages are to be retrieved 
timeout     - Time in seconds to wait for the message.     
              Timeout of 0 will lead to blocking indefinitely for the message
"""
```

2021-02-01 14:14 UTC, ujjwalpl requested changes

2021-02-01 14:14 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        timeout = self._default_timeout if input_timeout == 0 else input_timeout
Here is the correct code.
```
def receive(self, consumer_id: str, timeout: float = None) -> list:
    ...
    if timeout == None: timeout = self._default_timeout
```

2021-02-01 14:15 UTC, ujjwalpl requested changes

2021-02-01 14:15 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        """ Interface to receive messages """
Add the description here.

```
""" 
Receives list of messages from Kafka Message Server
Input Parameters: 
consumer_id - Consumer ID for which messages are to be retrieved 
timeout     - Time in seconds to wait for the message. Default is 0.5 seconds
              Timeout of 0 will lead to blocking indefinitely for the message
"""
```

2021-02-01 14:16 UTC, ujjwalpl requested changes

2021-02-01 14:16 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    if not input_timeout:
`if timeout == 0:`

2021-02-01 15:45 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        """ Interface to receive messages """
description added

2021-02-01 15:45 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    if not input_timeout:
done

2021-02-01 15:46 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, consumer_id: str, input_timeout: float) -> list:
description added and renamed as timeout

2021-02-01 16:34 UTC, ujjwalpl requested changes

2021-02-01 16:34 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, consumer_id: str, timeout: float) -> list:
def receive(self, consumer_id: str, timeout: float = None) -> list:

2021-02-01 16:35 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, consumer_id: str, input_timeout: float) -> list:
Comment is not yet incorporated

2021-02-01 16:48 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def receive(self, consumer_id: str, timeout: float) -> list:
done

2021-02-01 16:50 UTC, ujjwalpl requested changes

2021-02-01 16:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                        return msg
Optimized code. No need of `return msg`
```
while True:
    msg = consumer.poll(timeout=timeout)
    if msg is None:
        if timeout > 0: 
            return None
    elif msg.error():
        raise MessageBusError(...)
    else:
        return msg.value()
```

2021-02-01 16:56 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                        return msg
done.

2021-02-01 17:02 UTC, ujjwalpl approved these changes

2021-02-01 17:36 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    if timeout > 0:
You have already changed the value of timeout.
So it never be a blocking call

2021-02-01 17:37 UTC, sachinpunadikar requested changes
Logic is incorrect

2021-02-02 04:11 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    if timeout > 0:
we are changing only if it is None and not for 0

2021-02-02 05:56 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    if timeout > 0:
ok, got it

2021-02-02 05:57 UTC, sachinpunadikar approved these changes
+1

2021-02-02 06:03 UTC, merged