EOS-16847-ConfStore-load config traceback change
Seagate/cortx-utils pull request #168
Opened 2021-01-27 09:14 UTC by suryakumar1024

Loading file with wrong protocol will raise exception now to avoid data loss incase of accidental write action on wrong fileformat which leads empty file.

confcli post delete save changes
now the confcli will ensure that, the key passed is acually exist (some cases key won't be there in store so confstore simply return none) and deleted from the file so that the changes need to be saved.

Conf CLI:
now deleting non existing key won't do conf.save(). (Check if really requires to save the file then call the conf.save)

Conf load
now loading file with wrong protocol is restricted with a traceback as stated below

JSON:
conf json:///tmp/bug_test.toml get test
error(22): Invalid JSON format Expecting value: line 1 column 1 (char 0)

YAML:
conf yaml:///tmp/bug_test.toml get test
error(22): Invalid YAML format expected '', but found '['
in "/tmp/bug_test.toml", line 17, column 1

TOML:
conf toml:///tmp/file1.json get test
error(22): Invalid TOML format Found invalid character in key name: '}'. Try quoting the key name. (line 1 column 2 char 1)

INI:
conf ini:///tmp/bug_test.toml get test
error(22): Invalid INI format File contains no section headers.
file: '/tmp/bug_test.toml', line: 5
'title = "TOML Example"\n'

Signed-off-by: surya <k.suryakumar1024@gmail.com>

2021-01-28 04:06 UTC, sachinpunadikar commented on py-utils/src/utils/kv_store/kv_payload.py
> +                return None
Shouldn't it be false ?

2021-01-28 04:10 UTC, sachinpunadikar commented on py-utils/src/utils/kv_store/kv_payload.py
>              return
Should it be just return or "return false/true" ?

2021-01-28 04:14 UTC, sachinpunadikar requested changes
Please see the comments and make appropriate changes

2021-01-29 07:07 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_payload.py
> +                return None
Yes can be changed it won't affect anything. Updated in current patch.

2021-01-29 07:07 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_payload.py
>              return
Yes can be changed it won't affect anything. Updated in current patch

2021-01-29 11:55 UTC, sachinpunadikar commented on py-utils/src/utils/kv_store/kv_payload.py
> +            return False
I think this return statement is not reachable  .. check once & if not needed can be removed.

2021-01-29 11:56 UTC, sachinpunadikar requested changes
check if the return statement can be removed

2021-02-08 12:37 UTC, sachinpunadikar approved these changes
+1

2021-02-08 13:54 UTC, selvakumaar5496 commented on py-utils/src/utils/conf_store/conf_cache.py
>          """ Delets a given key from the config """
""" Deletes a given key from the config """

2021-02-08 14:00 UTC, ujjwalpl requested changes

2021-02-08 14:00 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +        result = self._data.delete(key)
Please update the function description with the change and conventions about return value e.g. What it means to return 0

2021-02-08 14:03 UTC, selvakumaar5496 requested changes

2021-02-08 14:03 UTC, selvakumaar5496 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                                   terr.__str__())
Indent to 4 tab spaces

2021-02-08 15:07 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
>          KvStore.__init__(self, store_loc, store_path, delim)
since both serves the purpose. So i keep as it is

2021-02-08 15:12 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                                   terr.__str__())
Here we can use like this. Only at the time of multiple or long next line we have to follow 4 space tab indent.

2021-02-08 15:12 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
>          """ Delete given set of keys from the config """
Updated

2021-02-08 15:12 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +        result = self._data.delete(key)
updated

2021-02-08 15:12 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
>          """ Delets a given key from the config """
updated

2021-02-08 15:24 UTC, ujjwalpl requested changes

2021-02-08 15:24 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +        """ Delete a given key from the config and
"""
Delete a given key from the config.  
Return Value: 
return boolean true for success else false
"""

2021-02-08 15:59 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cache.py
> +        """ Delete a given key from the config and
Updated in recent patch commit

2021-02-10 09:47 UTC, ujjwalpl approved these changes

2021-02-10 10:43 UTC, selvakumaar5496 approved these changes

2021-02-10 10:46 UTC, merged