Install required packages as pre-install step
Seagate/cortx-utils pull request #176
Opened 2021-02-01 14:05 UTC by sachinpunadikar

"cortx-py-utils" depends on various python packages. Current method
to install these packages was to install them as post-install step.
This was leading to erroneous state of "cortx-py-utils" installation.
Corrected this, and now these packages will get installed as
pre-install step.

2021-02-01 15:10 UTC, ujjwalpl requested changes

2021-02-01 15:10 UTC, ujjwalpl commented on py-utils/utils-pre-install
> +#!/bin/bash
What is utils-pre-install ? There is not such a thing.
It should be utils-postinstall actually.

2021-02-01 15:12 UTC, ujjwalpl requested changes

2021-02-01 15:12 UTC, ujjwalpl commented on py-utils/utils-pre-install
> +#!/bin/bash
Add license text and also the description about the usage and purpose of this script ?

2021-02-07 06:44 UTC, sachinpunadikar commented
Closing this PR, as handling this python package installation as part of post_install phase of utils_setup

2021-02-07 06:44 UTC, closed without merging