Install python packages in post_install of utils_setup
Seagate/cortx-utils pull request #182
Opened 2021-02-03 11:26 UTC by sachinpunadikar

Currently, required python packages are getting installed as part of
"%post" phase of rpm. This is incorrect way and need to handle the
package dependency in "post_install" phase of miniprovisioner.

2021-02-03 11:42 UTC, ujjwalpl requested changes

2021-02-03 11:42 UTC, ujjwalpl commented on py-utils/src/utils/setup/msg_bus_test.py
> +#!/bin/env python3
This needs to be moved to test folder.

2021-02-03 11:42 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +              + "/opt/seagate/cortx/utils/conf/requirements.txt"
This can be a relative path w.r.t. current file.

2021-02-03 11:42 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +        msg_test = MessageBusTest()
Need to invoke test from the test folder.

2021-02-03 11:42 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +        kafka_server_list = []
Move kafka related code to config\_kafka() and call from config().

2021-02-03 11:44 UTC, ujjwalpl requested changes

2021-02-03 11:44 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +                                 "Python Package installation failed")
res\_rc must be reported through exception.

2021-02-03 11:48 UTC, ujjwalpl requested changes

2021-02-03 11:48 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +        Conf.load("my_index", conf_url)
rename "my\_index" to meaningful name like "deployment", "cluster\_config", etc.

2021-02-03 11:53 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +              + "/opt/seagate/cortx/utils/conf/requirements.txt"
Here we are reading the installed file, hence using absolute path.

2021-02-03 13:21 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        Conf.load("my_index", conf_url)
Done

2021-02-03 13:27 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +                                 "Python Package installation failed")
Done

2021-02-03 13:29 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        kafka_server_list = []
Above code is for reading the required keys. Using these keys message bus config file is created. Hence no need to move out this code.

2021-02-03 13:36 UTC, sachinpunadikar commented on py-utils/src/utils/setup/msg_bus_test.py
> +#!/bin/env python3
As I observe, we are not installing test code as part rpm installation, hence can not move this piece of code

2021-02-03 13:52 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        msg_test = MessageBusTest()
Test code is not available as part of rpm installation, hence this can not be done.

2021-02-03 15:21 UTC, ujjwalpl requested changes

2021-02-03 15:21 UTC, ujjwalpl commented on py-utils/src/utils/setup/msg_bus_test.py
> +#!/bin/env python3
Ok! Lets defer this and add another task to create test rpm and use that when test is called. If test rpm is not installed, this will be a no-op.

2021-02-03 15:21 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +        kafka_server_list = []
Its about moving the code. its about structuring. We need to add a number of more things in future and need structure in place. 

```
def config_xxx():
    ...

def config_yyy(): 
    ...

def config(): 
    config_xxx()
    config_yyy()
    
```

2021-02-03 15:21 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +        msg_test = MessageBusTest()
Lets add a TODO to move this to test and create test RPM and use that. We need to add a number of things in future, we do not want a parallel track for test code.

2021-02-03 16:18 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        msg_test = MessageBusTest()
Sure

2021-02-03 16:18 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +        kafka_server_list = []
Got your point. Made the changes

2021-02-03 16:40 UTC, ujjwalpl requested changes

2021-02-03 16:40 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +def msg_bus_keys(conf_url):
Interface should be a verb. The this function returns kafka\_server\_list. 

So it should be renamed to \_get\_kafka\_server\_list(). xx because this is an internal function.

2021-02-03 16:40 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +def msg_bus_keys(conf_url):
Please avoid global functions. This should be part of a utils class itself.

2021-02-03 16:40 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils.py
> +def create_msg_bus_config(kafka_server_list):
Need to avoid global functions. Also please rename to _create_msg_bus_config(...) as its internal function.

2021-02-03 17:27 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +def create_msg_bus_config(kafka_server_list):
done.

2021-02-03 18:45 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +def msg_bus_keys(conf_url):
done

2021-02-03 18:47 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils.py
> +def msg_bus_keys(conf_url):
Having these functions part of Utils class is leading to NameError, hence keeping as global function for now

2021-02-04 04:07 UTC, ujjwalpl approved these changes

2021-02-04 04:10 UTC, saurabhkhanvilkar approved these changes

2021-02-04 15:39 UTC, merged