Create, Delete and Increase Partitions of Message Type
Seagate/cortx-utils pull request #184
Opened 2021-02-03 11:46 UTC by selvakumaar5496

2021-02-10 13:08 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/__init__.py
> +from cortx.utils.message_bus.message_bus_client import MessageProducer, MessageConsumer, MessageBusAdmin
Remove this from this place, and add it at appropriate place.

2021-02-10 13:09 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +from confluent_kafka.admin import AdminClient, ConfigResource, NewTopic, \
Remove this from here and add it at appropriate place.

2021-02-10 13:19 UTC, sachinpunadikar requested changes
Make required changes.
Please note that there will not be any dependent python packages installed, when cortx-py-utils get installed. A quick test would be to install the rpm on fresh VM and run post_install phase of utils_setup

2021-02-11 11:17 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/__init__.py
> +from cortx.utils.message_bus.message_bus_client import MessageProducer, MessageConsumer, MessageBusAdmin
Its okay to have it here.

2021-02-11 11:18 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +from confluent_kafka.admin import AdminClient, ConfigResource, NewTopic, \
Its okay to have it here

2021-02-15 11:01 UTC, sachinpunadikar approved these changes
+1

2021-02-15 11:31 UTC, ujjwalpl requested changes

2021-02-15 11:31 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def register_message_type(self, admin_id: str, message_type: list, \
```def register_message_type(self, admin_id: str, message_types: list, \```

Reflect the variable names correctly as per the types. There are multiple message types.

2021-02-15 11:31 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def deregister_message_type(self, admin_id: str, message_type: list):
Same here

2021-02-15 11:31 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def increase_parallelism(self, admin_id: str, message_type: list, \
Change the name to set_... as you are specying a fixed value. 
```def set_parallelism(self, admin_id: str, message_types: list, \```

Increase would mean increase by N, e.g. +1

2021-02-15 11:31 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            new_total_count=partitions) for each_message_type in message_type]
What if the new count is less than the old count ? Should we report an error ?

2021-02-15 11:31 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        partitions       Integer that represents number of partitions to be
What about decrease ?

2021-02-15 12:26 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        partitions       Integer that represents number of partitions to be
Number of partitions for a topic can only be increased, never decreased

2021-02-15 12:27 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            new_total_count=partitions) for each_message_type in message_type]
yes, Kafka throws an error if the number of partitions is less than the existing number

2021-02-15 12:27 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def increase_parallelism(self, admin_id: str, message_type: list, \
yes, we can only increase by N

2021-02-15 12:40 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def register_message_type(self, admin_id: str, message_type: list, \
changed as suggested

2021-02-15 12:42 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def deregister_message_type(self, admin_id: str, message_type: list):
changed as suggested

2021-02-15 17:31 UTC, ujjwalpl requested changes

2021-02-15 17:32 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            new_total_count=partitions) for each_message_type in message_type]
We need to catch and throw a Message Bus Error. Can you confirm if this is the case ?

2021-02-15 17:33 UTC, ujjwalpl requested changes

2021-02-15 17:33 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        partitions       Integer that represents number of partitions to be
```def increase_parallelism(self, message_types: list, partitions: int):```

2021-02-16 05:31 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        partitions       Integer that represents number of partitions to be
taken care

2021-02-16 05:35 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            new_total_count=partitions) for each_message_type in message_type]
This exception is caught in **def _task_status(self, tasks :dict):** method

2021-02-16 07:03 UTC, ujjwalpl requested changes

2021-02-16 07:03 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            message_type=message_types, auto_ack=auto_ack, offset=offset)
List is assigned to a str.

2021-02-16 07:10 UTC, ujjwalpl requested changes

2021-02-16 07:10 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            conf = admin.describe_configs([self._resource])
Please note client_conf['message_type'] has multiple message types. Change the key to reflect the same, i.e. "message_types"

2021-02-16 08:26 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            conf = admin.describe_configs([self._resource])
changed for consumer, since it takes list of message_types

2021-02-16 09:41 UTC, ujjwalpl approved these changes

2021-02-17 03:32 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            message_type=message_types, auto_ack=auto_ack, offset=offset)
taken care

2021-02-17 06:39 UTC, merged