Cs properties test cases with fix
Seagate/cortx-utils pull request #199
Opened 2021-02-10 12:41 UTC by suryakumar1024

Added test cases for kv_store, conf and conf_cli
Added fix for loading wrong data from properties  files store

2021-02-10 15:44 UTC, ujjwalpl requested changes

2021-02-10 17:09 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        """For testing seek writing multiple lines into the file"""
Removed this comment since any how the purpose is to create a sample file for testing.

2021-02-10 17:22 UTC, ujjwalpl requested changes

2021-02-10 17:22 UTC, ujjwalpl commented on py-utils/test/test_conf_store/test_conf_store.py
> +        """Test by loading the give properties config file to in-memory"""
""" Test by loading the give properties config file to in-memory """

2021-02-10 17:26 UTC, ujjwalpl requested changes

2021-02-10 17:26 UTC, ujjwalpl commented on py-utils/test/test_conf_store/test_conf_store.py
> +    def test_conf_store_by_load_and_get(self):
Indentation issue ? Why this has a different indentation ?

2021-02-11 07:35 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_store.py
> +        """Test by loading the give properties config file to in-memory"""
Updated in current patch

2021-02-11 07:36 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_store.py
> +    def test_conf_store_by_load_and_get(self):
No I checked and could see correct indent in my code even I tried to execute the same file

2021-02-11 08:09 UTC, sachinpunadikar commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        result_data = subprocess.check_output(['conf',
Use simpleprocess calss here

2021-02-11 08:10 UTC, sachinpunadikar commented on py-utils/test/test_conf_store/test_conf_cli.py
> +            subprocess.check_output(['conf', 'properties:///tmp/file1.json',
Use simpleprocess class it is part of py-utils code

2021-02-11 08:11 UTC, sachinpunadikar requested changes
Make required changes

2021-02-11 08:59 UTC, ujjwalpl approved these changes

2021-02-11 12:28 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_cli.py
> +            subprocess.check_output(['conf', 'properties:///tmp/file1.json',
Updated in current patch

2021-02-11 12:28 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        result_data = subprocess.check_output(['conf',
updated in current patch

2021-02-11 15:36 UTC, sachinpunadikar commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        cmd_1 = "conf json:///tmp/file1.json set bridge>cli_name='client';bridge>has_internet='no'"
Indentation do not look correct

2021-02-11 15:37 UTC, sachinpunadikar reviewed
check the comment

2021-02-16 03:14 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        cmd_1 = "conf json:///tmp/file1.json set bridge>cli_name='client';bridge>has_internet='no'"
Fixed in current patch

2021-02-16 05:35 UTC, sachinpunadikar commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        cmd_1 = "conf json:///tmp/file1.json set bridge>cli_name='client';" \
I think '+' is missing here

2021-02-16 05:35 UTC, sachinpunadikar commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        cmd_2 = "conf json:///tmp/file1.json get bridge>cli_name;" \
same here

2021-02-16 05:38 UTC, sachinpunadikar commented on py-utils/test/test_kv_store/test_kv_store.py
> -#!/usr/bin/env python3
Why this entire file is changed ? Is this due to ^M characters ?

2021-02-16 05:38 UTC, sachinpunadikar requested changes
Please work on review comments

2021-02-16 05:43 UTC, suryakumar1024 commented on py-utils/test/test_kv_store/test_kv_store.py
> -#!/usr/bin/env python3
The code in main branch shows entire file as new one while fixing conflicts

2021-02-16 05:44 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        cmd_2 = "conf json:///tmp/file1.json get bridge>cli_name;" \
+ is not required if i use \ back slash also it was considered as single line

2021-02-16 05:44 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        cmd_1 = "conf json:///tmp/file1.json set bridge>cli_name='client';" \
+ is not required if i use \ back slash also it was considered as single line

2021-02-22 06:10 UTC, suryakumar1024 commented on py-utils/test/test_kv_store/test_kv_store.py
> -#!/usr/bin/env python3
This is because of ^M character fix patch

2021-02-23 07:28 UTC, sachinpunadikar approved these changes
+1

2021-02-23 13:27 UTC, selvakumaar5496 requested changes

2021-02-23 13:27 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
>  from cortx.utils.schema.payload import *
Please remove this line since this is not required

2021-02-23 13:33 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus.py
>  from cortx.utils.schema.payload import *
Updated in recent patch code

2021-02-23 14:08 UTC, ujjwalpl requested changes

2021-02-23 14:08 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                    key, val = line.rstrip('\n').split('=')
key, val = line.rstrip('\n').split('=', 1)

2021-02-23 14:20 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                    key, val = line.rstrip('\n').split('=')
updated in current patch code

2021-02-23 16:19 UTC, selvakumaar5496 approved these changes

2021-02-23 17:13 UTC, merged