Implementing lazy imports for json, toml and yaml modules
Seagate/cortx-utils pull request #205
Opened 2021-02-17 05:31 UTC by rahul-tripathi-git

The imports modules has been moved from usual top lines to methods
where they are actually used.

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

2021-02-17 05:32 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-02-17 06:45 UTC, selvakumaar5496 approved these changes

2021-02-17 07:30 UTC, sachinpunadikar commented on py-utils/src/utils/kv_store/kv_store_collection.py
>  from json.decoder import JSONDecodeError
Is this part of json module ? If so shouldn't it be moved to relevant place ?

2021-02-17 07:33 UTC, sachinpunadikar requested changes
one minor comment. See if it needs any action.

2021-02-18 07:48 UTC, ujjwalpl approved these changes

2021-02-22 11:51 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
>  from json.decoder import JSONDecodeError
just moved import JSONDecodeError just before it is being used.

2021-02-22 12:08 UTC, rahul-tripathi-git commented
> one minor comment. See if it needs any action.

Done.

2021-02-22 12:27 UTC, ujjwalpl approved these changes

2021-02-22 13:25 UTC, selvakumaar5496 commented on py-utils/src/utils/kv_store/kv_store_collection.py
class TomlKvStore(KvStore):
    """  Represents a TOML File Store """

**Remove one space**
class TomlKvStore(KvStore):
    """ Represents a TOML File Store """

2021-02-22 13:54 UTC, selvakumaar5496 requested changes

2021-02-22 13:54 UTC, selvakumaar5496 commented on py-utils/src/utils/kv_store/kv_store_collection.py
>          """Get pillar data for key."""
""" Get pillar data for key """

2021-02-22 13:54 UTC, selvakumaar5496 commented on py-utils/src/utils/schema/payload.py
class Tar(Doc):
    """Represents Tar File"""

**Add spacing**

class Tar(Doc):
    """ Represents Tar File """

2021-02-22 14:10 UTC, rahul-tripathi-git commented on py-utils/src/utils/schema/payload.py
done

2021-02-22 14:15 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
Done

2021-02-22 14:15 UTC, rahul-tripathi-git commented on py-utils/src/utils/schema/payload.py
Done

2021-02-22 15:38 UTC, selvakumaar5496 approved these changes

2021-02-22 16:32 UTC, sachinpunadikar approved these changes
+1

2021-02-22 16:33 UTC, merged