ConfStore CLI: Added new cli optional argument for Set operation -d kv_delim
Seagate/cortx-utils pull request #209
Opened 2021-02-21 17:56 UTC by suryakumar1024

Added conf cli -d optional kv_delim api feature
Added testcases for new optional argument

Usage:

For using  : as delim instead of =

"conf json:///tmp/file1.json set -d : key1>key_2:values_here"

Signed-off-by: suryakumar <suryakumar.kumaravelan@seagate.com>

2021-02-22 04:12 UTC, ujjwalpl requested changes

2021-02-22 04:12 UTC, ujjwalpl commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        set_cmd = "conf json:///tmp/file1.json set -d : cluster>id=093d"
Need to add few more test cases..
1. Multiple delim, i.e. a=b=c 
2. Add a delim which is outside of the acceptable list of delims.

2021-02-22 04:12 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        kv_delim = '=' if args.kv_delim == None else args.kv_delim
Add a validation that kv_delim must be from a set of predefined delimeters, i.e. cant use an arbitratory character.

2021-02-22 10:50 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_cli.py
> +        set_cmd = "conf json:///tmp/file1.json set -d : cluster>id=093d"
Updated in current patch. possible delim [':', '>', '.', '|', '/']. 
semicolon ';' not in the list since we using that same delim for splitting multiple set key, values

2021-02-22 10:51 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +        kv_delim = '=' if args.kv_delim == None else args.kv_delim
Validation added and updated in current patch

2021-03-01 08:30 UTC, ujjwalpl approved these changes

2021-03-01 10:34 UTC, sachinpunadikar approved these changes
+1

2021-03-01 10:34 UTC, merged