WIP: Add pre-install checks for required python packages
Seagate/cortx-utils pull request #212
Opened 2021-02-25 12:55 UTC by sachinpunadikar

"cortx-py-utils" rpm depends on various python packages.
The %pre phase should check whether these python packages are
installed or not. If these packages do not exists, then throw
message asking to install them

2021-02-25 14:15 UTC, rahul-tripathi-git approved these changes
Looks Good to me.

2021-02-26 09:51 UTC, sachinpunadikar commented
Please ignore the mini-provisioner failure. Earlier job went well
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-utils/84/console

2021-02-26 09:53 UTC, ujjwalpl requested changes

2021-02-26 09:53 UTC, ujjwalpl commented on py-utils/utils-pre-install
> +PACKAGE_LIST="aiohttp==3.6.1
Can we generate this from requiremets.txt during build time to avoid possibility of manual error.

2021-03-01 07:57 UTC, sachinpunadikar commented on py-utils/utils-pre-install
> +PACKAGE_LIST="aiohttp==3.6.1
@ujjwalpl, I was not able to locate any method, which will help in updating/generating a file when we run setup.py bdist_rpm. Let me know if you have any idea on how to do that.

2021-03-04 18:27 UTC, sachinpunadikar commented on py-utils/utils-pre-install
> +PACKAGE_LIST="aiohttp==3.6.1
@ujjwalpl as suggested, created a wrapper script for building cortx-py-utils. This takes care of generating "utils-pre-install".

2021-03-05 11:41 UTC, rahul-tripathi-git approved these changes

2021-03-05 13:02 UTC, ujjwalpl requested changes

2021-03-05 13:02 UTC, ujjwalpl commented on py-utils/rpm_build.sh
> +#!/bin/bash
Lets keep this to the following location to be consistent. 
<repo root>/jenkins/build.sh

2021-03-08 05:28 UTC, sachinpunadikar commented on py-utils/rpm_build.sh
> +#!/bin/bash
Done

2021-03-08 08:44 UTC, ujjwalpl approved these changes

2021-03-08 09:40 UTC, merged