validator - PkgV - Add version check on installed python 3rd party packages
Seagate/cortx-utils pull request #214
Opened 2021-03-01 04:10 UTC by mariyappanp

2021-03-04 04:44 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_pkg.py
> +	def validate_pip3s(self, host, pkgs, skip_version_check=True):
We can rename to more inuitive name validate_pip3_pkgs()

2021-03-04 04:44 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_pkg.py
>  	def validate_rpms(self, host, pkgs):
Need version check provision too, same as pip3 pkgs

2021-03-05 09:04 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
>  	def validate_rpms(self, host, pkgs):
Done.

2021-03-05 09:05 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +	def validate_pip3s(self, host, pkgs, skip_version_check=True):
Done.

2021-03-05 12:15 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_pkg.py
> +			result = self.__search_pkg(f"ssh {host} rpm -qa")
I feel if & else case can just have 'cmd' generation statement and then call to search_pkg () at one place.

Same applies for validate_pip3_pkgs()

2021-03-05 12:16 UTC, cdeshmukh reviewed
minor comments to address

2021-03-08 12:41 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +			result = self.__search_pkg(f"ssh {host} rpm -qa")
Done.

2021-03-08 13:24 UTC, thavanathan approved these changes

2021-03-09 05:15 UTC, ujjwalpl requested changes

2021-03-09 05:15 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +		if host != None:
You can write this one line as 

`cmd = "ssh %s rpm -qa" % host if host != None else "rpm -qa"`

2021-03-09 05:15 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +		if host != None:
Same here

2021-03-09 05:15 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +					err_desc = "pip3 pkg: %s is not having expected version. " + \
Keep it readable. No need of variable. 

```
raise VError(errno.EINVAL, "Mismatched version for pip3 package %s. " \
    "Installed %s. Expected %s." %(pkg, installed_version, expected_version))
```

2021-03-09 05:15 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +							"pip3 pkg: %s not found" % pkg)
Incorrect indentation. I think it can fit in same line within 80 char. If it can not then it can be like this. 
```
raise VError(errno.EINVAL, 
    "pip3 pkg %s not installed" % pkg)
```

2021-03-09 05:15 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +					err_desc = "rpm pkg: %s is not having expected version. " + \
Keep it readable. No need of variable. 

```
raise VError(errno.EINVAL, "Mismatched version for rpm package %s. " \
    "Installed %s. Expected %s." %(pkg, installed_version, expected_version))
```

2021-03-09 07:22 UTC, cdeshmukh approved these changes
Am ok, after Ujjwal's comments are addressed

2021-03-09 07:37 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +		if host != None:
Sure. I brought the requested changes now.

2021-03-09 07:38 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +		if host != None:
Done.

2021-03-09 07:38 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +					err_desc = "pip3 pkg: %s is not having expected version. " + \
Okay.

2021-03-09 07:38 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +					err_desc = "rpm pkg: %s is not having expected version. " + \
Done.

2021-03-09 07:39 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +							"pip3 pkg: %s not found" % pkg)
Not exceeded 80 char. Now its one line statement.

2021-03-09 15:25 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +				matched_str = re.search(f"{pkg}-([^-][0-9.]+)-", result)
The earlier version of this file is indented such a way.
Let me change tab size to 4 space.

2021-03-09 15:44 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +				matched_str = re.search(f"{pkg}-([^-][0-9.]+)-", result)
Done. @ujjwalpl

2021-03-09 15:44 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +								"Installed %s. Expected %s." %(pkg, installed_version, expected_version))
Done.

2021-03-09 15:45 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +								"Installed %s. Expected %s." %(pkg, installed_version, expected_version))
Its within 80 chars only.

2021-03-09 16:51 UTC, ujjwalpl requested changes

2021-03-09 16:51 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +                     "cmd: %s failed with error code: %d, stderr: %s"
Indentation for this should be 4 chars. Currently its 8 chars

2021-03-09 16:51 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +                            "Installed %s. Expected %s." %(pkg, installed_version, expected_version))
Use 4 chars indentation

2021-03-09 16:51 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +                            "Installed %s. Expected %s." %(pkg, installed_version, expected_version))
Use 4 chars indentation

2021-03-09 16:51 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +        cmd = "ssh %s rpm -qa" % host if host != None else "rpm -qa"
If its other host then you should be using SSHChannel::execute().

2021-03-09 16:51 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
host should be host_url in case password less ssh connectivity is not established. example: user:password@server.com:port

2021-03-09 16:51 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +                     "cmd: %s failed with error code: %d, stderr: %s"
The message does not indicate output of search package. It looks like wrapper of a command. It should be more intuitive. 
    "Package dependency check failed. cmd: %s. %s" %(cmd, err)

Please ensure the message is clearly indicating the package and its name is called out.

2021-03-09 17:22 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
This validation is intended to run on passwordless ssh configured host. Otherwise validation will fail at the earliest.
```
        if host:
            NetworkV().validate('passwordless',
                [pwd.getpwuid(os.getuid()).pw_name, host])
```
I have to handle the connectivity error and try with host_url then. In this case, Pkg validator must be modified to receive username and password as well.  I try to introduce the required changes at minimal as per the ticket. Advice me if still this needs to be addressed with this PR. @ujjwalpl

2021-03-09 17:25 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +        cmd = "ssh %s rpm -qa" % host if host != None else "rpm -qa"
If its other host still passwordless ssh helps, rather than to use SSHChannel.

2021-03-09 17:43 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +                     "cmd: %s failed with error code: %d, stderr: %s"
__search_pkg() is defined to execute below two commands to get all the installed packages. 
1. pip3 list
2. rpm -qa
This doesn't search for any specific package. If you feel the method name is not suitable, I will modify it.

2021-03-09 17:50 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +								"Installed %s. Expected %s." %(pkg, installed_version, expected_version))
I corrected the indentation with new commit.

2021-03-09 17:52 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +                            "Installed %s. Expected %s." %(pkg, installed_version, expected_version))
Done.

2021-03-09 17:55 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +                     "cmd: %s failed with error code: %d, stderr: %s"
Done. I modified the error message.

2021-03-09 18:33 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
@ujjwalpl as far as i know, provisioner is going to keep password less ssh across cluster nodes, as was the case in Cortxv1. And our immediate & basic need is to check on local node actually so we are keeping it simple. Whoever needs it with user:password can extend it

2021-03-09 18:33 UTC, cdeshmukh approved these changes

2021-03-10 07:49 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
I have extended the functionality for passwordless ssh not configured host.
Please review. @cdeshmukh @ujjwalpl 
Also the unittest result is added in this PR.

2021-03-10 08:11 UTC, ujjwalpl requested changes

2021-03-10 08:11 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +        # print(f"Running {cmd}")
Remove all such temp code.

2021-03-10 08:11 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +                    raise VError(
There is no need to catch and rethrow error unless you plan to catch some other exception. 
Moreover the error sent by earlier exception is lost here because you dont catch it properly

2021-03-10 08:11 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
We should make no assumptions about dependency on what provisioner will do. The code will run in all kinds of environment including QA. We should be able to validate all the cases of misconfigurations without hidden assumptions.

2021-03-10 09:08 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +                    raise VError(
When passwordless ssh is not configured on that host network validator throws VError. Here we catch that specific exception purposefully and validate the host url in exception block.
Let me make it more clear.

2021-03-10 09:13 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +        cmd = "ssh %s rpm -qa" % host if host != None else "rpm -qa"
Done.

2021-03-10 09:14 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +        # print(f"Running {cmd}")
Removed.

2021-03-10 09:15 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +                    raise VError(
As not catching none other exception, I removed `except VError` and now its generic.

2021-03-10 09:16 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
Ack.

2021-03-10 09:59 UTC, ujjwalpl requested changes

2021-03-10 09:59 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +                    raise VError(
Again the reason to catch and rethrow is not clear. 
except: --> Issue. Exception information is lost. 
except VError: --> Issue. Exception information is lost. 
except DivideByZero as e: OK. exception information is in 'e'

2021-03-10 09:59 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
Another way to handle this is to detect that password less is not setup and throw a more accurate error asking user to setup password less setup.

2021-03-10 11:46 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
I reverted the host_url validation as we fail if host is not passwordless ssh configured.
If passwordless ssh is not setup on the host, a detailed error message(`Passwordless ssh not configured for localhost` with full error stack) can be seen.

2021-03-10 11:47 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +                    raise VError(
As discussed, I'm proceeding with passwordless ssh validation approach and removed host_url approach.
Hence the previous version is reverted.

2021-03-10 12:35 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
>Passwordless ssh not configured for <hostname>

Hostname needed right, why localhost in comment?

2021-03-10 13:06 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
`Hostname needed right, why localhost in error message?` Its just by unittest on `test/validator/test_pkg_validator.py`.

2021-03-10 13:12 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
`erroring out is just another way of handling, first approach is still to make use of host_url.` @cdeshmukh, we caught exception during passwordless ssh validation. Ujjwal commented like to throw the exception. If so why we need to validate host_url then. If passwordless ssh validation is success then also host_url is not required.

If I go ahead to use host_url approach, the I should hide passwordless ssh validation exception.

2021-03-10 14:07 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
> test/validator/test_pkg_validator.py. The host variable is set to 'localhost'.

Ok

> Ujjwal commented like to throw the exception. If so why we need to validate host_url then. 

Not to validate host_url but just try ssh with or without host_url depending on input and if failed, throw the relevant exception.

> If I go ahead to use host_url approach, then I should hide passwordless ssh validation exception and handle it by host_url validation.
Rather than validation of input, try the operation with input & then handle relevant excepion i mean, why to validate host_url where we cant know its correctness until tried.

2021-03-10 14:49 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_pkg.py
> +    def validate_rpm_pkgs(self, host, pkgs, skip_version_check=True):
Am ok either way, having exception if password less ssh fails, that will keep this code simple

2021-03-11 13:03 UTC, mariyappanp commented on py-utils/src/utils/validator/v_pkg.py
> +                    raise VError(
Code is committed with some identified use cases now.

2021-03-12 10:49 UTC, ujjwalpl approved these changes

2021-03-12 12:06 UTC, cdeshmukh approved these changes

2021-03-12 12:37 UTC, sachinpunadikar approved these changes
+1

2021-03-13 15:21 UTC, merged