Gets the count of unread messages from MessageBus
Seagate/cortx-utils pull request #215
Opened 2021-03-01 09:47 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

2021-03-02 05:41 UTC, ujjwalpl requested changes

2021-03-02 05:41 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def get_unread_count(self, consumer_group: str = None):
This interface should be wrapped by consumer class with consumer_group predefined.

2021-03-02 07:45 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def get_unread_count(self, consumer_group: str = None):
@ujjwalpl  if we make that change, then we are always going to get the unread count for the default consumer_group. Getting the unread count for another consumer_group from consumer side will not be possible. I hope this is as expected.

2021-03-04 06:38 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def get_unread_count(self, consumer_group: str = None):
Yes! This is what we need. We need for the current consumer group only.

2021-03-04 13:15 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def get_unread_count(self, consumer_group: str = None):
done, as suggested.

2021-03-04 13:36 UTC, ujjwalpl approved these changes

2021-03-05 07:38 UTC, sachinpunadikar approved these changes
+1

2021-03-05 08:05 UTC, merged