ConfStore: Properties file with empty and commented lines
Seagate/cortx-utils pull request #216
Opened 2021-03-01 17:59 UTC by suryakumar1024

Handled Empty lines and Commented lines while reading Properties file

below example properties file works
------------------------------------------------------
example.properties
------------------------------------------------------
bridge = {'name': 'Homebridge', 'username': 'CC:22:3D:E3:CE:30', 'manufacturer'$
name = Homebridge

username = CC:22:3D:E3:CE:30
manufacturer = homebridge.io
# model details
model = homebridge
pin = 031-45-154
port = 51826
lte_type = [{'name': '3g'}, {'name': '4g'}]
------------------------------------------------------

Signed-off-by: suryakumar <suryakumar.kumaravelan@seagate.com>

2021-03-02 05:38 UTC, ujjwalpl requested changes

2021-03-02 05:38 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                    if line.strip() and line.strip()[0] != '#':
Multiple strip calls and also strip(\n) can be avoided with this to be efficient. 

```
for line in f.readlines(): 
    line = line.strip()
    if not line or line[0] == '#': 
        continue
    key, val = line.split('=', 1)
    data[key.strip()] = val.strip()
```

2021-03-02 05:38 UTC, ujjwalpl commented on py-utils/test/test_kv_store/test_kv_store.py
> +        file.write("# Comments section test")
We should cover following cases. 
1. "# normal comment" 
2. " # space before comment"
3. "\n" Empty line in the middle
4. "k = v#dd"
5. "Invalid line with # in the middle" should result in error

2021-03-02 09:54 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                    if line.strip() and line.strip()[0] != '#':
Updated in current patch

2021-03-02 14:14 UTC, suryakumar1024 commented on py-utils/test/test_kv_store/test_kv_store.py
> +        file.write("# Comments section test")
Updated in current patch

2021-03-03 13:26 UTC, ujjwalpl approved these changes

2021-03-03 14:46 UTC, sachinpunadikar approved these changes
+1

2021-03-03 14:46 UTC, merged