EOS-17636: Added function in Service file to get service information.
Seagate/cortx-utils pull request #220
Opened 2021-03-05 16:28 UTC by shriya-deshmukh

2021-03-08 04:42 UTC, sumedhak27 commented on py-utils/src/utils/service.py
> +        # Possible substates: failed, running, exited.
some more substates examples : stop-sigterm, stop-post, dead, start-pre

2021-03-08 05:27 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +        # Possible substates: failed, running, exited.
Thanks @sumedhak27, 
Added above substates into the substates list.

2021-03-08 06:03 UTC, sumedhak27 approved these changes

2021-03-08 07:02 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +    def get_service_information(self, service_name):
We have a class in which we are taking/processing values using system dbus. I am seeing this method is using only system dbus functionality to take the information.
Can we move that all methods to DbusServiceHandler class?
@thavanathan @cdeshmukh ?

2021-03-08 07:02 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +    def check_service_is_enabled(self, service_name):
same comments as above.

2021-03-08 07:02 UTC, satish-seagate commented on py-utils/src/utils/service.py
> +dbus_manager = dbus.Interface(systemd1, 'org.freedesktop.systemd1.Manager')
why we moved this code outside the class?

2021-03-08 08:21 UTC, gargpalak048 commented on py-utils/src/utils/service.py
> +dbus_manager = dbus.Interface(systemd1, 'org.freedesktop.systemd1.Manager')
@shriya-deshmukh Can't we keep this code in some function like get_interface() and return the interface manager?
So that if required, other classes can make api calls on this interface?

2021-03-08 10:07 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    def get_service_information(self, service_name):
Moved functions to DbusServiceHandler class.

2021-03-08 10:08 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    def check_service_is_enabled(self, service_name):
Moved this function to DbusServiceHandler class.

2021-03-08 10:09 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +dbus_manager = dbus.Interface(systemd1, 'org.freedesktop.systemd1.Manager')
Added this in get_systemd_interface function.

2021-03-08 10:49 UTC, satish-seagate approved these changes

2021-03-09 07:19 UTC, cdeshmukh approved these changes

2021-03-09 07:19 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> +        # Possible substates: failed, running, exited.
@shriya-deshmukh where these other substates added suggested by Sumedh, i dont see it in comment @ line 88 too

2021-03-09 13:11 UTC, ajaysrivas commented on py-utils/src/utils/service.py
>          if action not in ['enable', 'disable', 'start', 'stop', 'restart']:
systemctl already has these commands, so why are we implementing it here?

2021-03-09 13:14 UTC, cdeshmukh commented on py-utils/src/utils/service.py
>          if action not in ['enable', 'disable', 'start', 'stop', 'restart']:
its not implementing systemctl commands, but exposing it through SSPL actuators for any service control, needed for 3rd party services

2021-03-09 13:22 UTC, ajaysrivas commented on py-utils/src/utils/service.py
>          if action not in ['enable', 'disable', 'start', 'stop', 'restart']:
Then why do we have process function. Shouldn't we have enable, disable, start, stop and restart as function? An action is a function.

2021-03-09 13:26 UTC, cdeshmukh commented on py-utils/src/utils/service.py
>          if action not in ['enable', 'disable', 'start', 'stop', 'restart']:
all actions are applied in same manner, so doing it through one common function, whats the point of duplicating code for every action type, when no special code exist for each.

2021-03-09 13:28 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
>          if action not in ['enable', 'disable', 'start', 'stop', 'restart']:
service enable, disable, start, stop, restart functionality was already present in this class, instead of duplicating code we have used this same functions in sspl code.  
and through this PR , have added one more function in this class to get_service information like pid, state, substate, command_line path and used same in sspl code.

2021-03-09 13:33 UTC, ajaysrivas commented on py-utils/src/utils/service.py
>          if action not in ['enable', 'disable', 'start', 'stop', 'restart']:
If we are using classes we should use OOPS concept. Service(Object) has behaviors - enable, disable, start, stop and restart. These behaviors must be methods/functions. Common code can always be put under a private function.

2021-03-09 14:32 UTC, ujjwalpl requested changes

2021-03-09 14:32 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +    def get_systemd_interface(self):
This relates to earlier code. Please derive class DbusServiceHandler from ServiceHandler

2021-03-09 14:32 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +    def check_service_is_enabled(self, service_name):
Class name is ServiceHandler so using service is repeatition. Interface name should be "is_enabled"

2021-03-09 14:32 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +    def get_systemd_interface(self):
Service is the base class and should know nothing about the derived class. Please remove this function from this class. 

get_systemd_interface() should be private interface of DbusServiceHandler class. 
Rename to _get_systemd_interface()

2021-03-09 14:32 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +    def get_systemd_interface(self):
Rename to _get_systemd_interface() as this is private interface of the class.

2021-03-09 14:32 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +    def check_service_is_enabled(self, service_name):
is_enabled()

2021-03-09 14:32 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +    def get_service_information(self, service_name):
Interface name is not indicative of what it returns. Fundamental issue in returning several values under a vague contract i.e. info.
Please make the following changes
1. create a new class named "ServiceStatus" or "ServiceState" which represents a service in terms of state, substate, etc. 
2. Change the name of the interface to get_state()
3. Return ServiceState populated with all the values. 
```
class ServiceState:
    @property
    def pid(self):
        return self.pid

    @property
    def state(self):
        return state

    ....

class ServiceHandler
    def get_state(service_name):
        """ Returns ServiceState of the Service """
        ss = ServiceState()
        ss.pid = ...
        ss.state = ....
        ....
        return ss
```

2021-03-09 14:38 UTC, ujjwalpl requested changes

2021-03-09 14:38 UTC, ujjwalpl commented on py-utils/src/utils/service.py
>          if action not in ['enable', 'disable', 'start', 'stop', 'restart']:
Agree! If ServiceHandler is a standalone class then it should expose interfaces for all the operations that can be performed on the service. 

process() is the interface of the wrapper validator class where the purpose is to process the request. For some reason this was skipped through the initial review. Better to fix this ASAP.

2021-03-09 17:19 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    def get_systemd_interface(self):
Done.

2021-03-09 17:19 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    def get_systemd_interface(self):
Done.

2021-03-09 17:20 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
>          if action not in ['enable', 'disable', 'start', 'stop', 'restart']:
Removed process() function and added functions for each operation (start/stop/restart/enable/disable).

2021-03-09 17:20 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    def get_service_information(self, service_name):
Done.

2021-03-09 17:21 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    def check_service_is_enabled(self, service_name):
Renamed to is_enabled.

2021-03-09 17:21 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    def get_systemd_interface(self):
Done.

2021-03-09 17:21 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    def check_service_is_enabled(self, service_name):
done.

2021-03-09 18:14 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> +            _, dbus_manager = DbusServiceHandler._get_systemd_interface()
Just check if this dbus_manager obj doesnt need to be destroyed manually or else would result in lot of memory leak over time, per service operation performed.

2021-03-09 18:14 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> +        service_state.pid = pid
Where these member variables in ServiceState() class defined, which are being set here now, like pid, state, sub_state, command_line_path

2021-03-09 18:46 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +        service_state.pid = pid
we  have defined/fetched pid,state,substate ..etc values in get_state function(line 114-117).
"service_state.pid = pid" this calls  @pid.setter functions present in ServiceState() cls, which sets values.
and here at last we are returning service_state obj which will have all these values.

2021-03-09 18:51 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +            _, dbus_manager = DbusServiceHandler._get_systemd_interface()
added. "del dbus_manger".

2021-03-10 04:25 UTC, shriya-deshmukh commented
vm-deployment check is failing for this PR during sspl deployment, because cortx-utils PR - #220 and cortx-monitor PR- 326 is interdependent on each other.
In cortx-utils PR - we have added stop/start/restart/enable/disable functions in Service class and removed process function,
this change we need to add in sspl code also that I have done in #326 PR (not merged)
But sspl main branch still calling process function, hence VM deployment is failing.

2021-03-10 10:12 UTC, ujjwalpl requested changes

2021-03-10 10:12 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +    def stop(self, service_name: str):
Please add one line comment to all the interfaces.

2021-03-10 10:12 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +        service_state = ServiceState()
Since you have all the state parameters, you can use constructor to pass those values instead of settr. 

service_state = ServiceState(pid, state,....)

2021-03-10 10:12 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +    @pid.setter
If you set these values in the constructor then you dont need setters.

2021-03-10 10:12 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +            _, dbus_manager = DbusServiceHandler._get_systemd_interface()
Instead of getting and deleting dbus_manager in every interface, you can swith to doing this in constructor and deleting the same in the destructor. 

```
__init__(): 
    _, self._dbus_manager = DbusServiceHandler._get_systemd_interface()

def enable():
    self._dbus_manager.EnableUnitFiles([f'{service_name}'], False, True)
    self._dbus_manager.Reload()

def __cleanup__():
    del self._dbus_manager
```

2021-03-10 11:16 UTC, ujjwalpl requested changes

2021-03-10 11:16 UTC, ujjwalpl commented on py-utils/src/utils/service.py
> +class DbusServiceHandler(ServiceHandler):
Can you please also move this to utils/service/service_handler.py ?

2021-03-10 13:47 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    def stop(self, service_name: str):
Done.

2021-03-10 13:47 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +        service_state = ServiceState()
Done.

2021-03-10 13:48 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +    @pid.setter
Removed setters and used constructor to set values.

2021-03-10 13:48 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> +            _, dbus_manager = DbusServiceHandler._get_systemd_interface()
done.

2021-03-10 14:35 UTC, cdeshmukh approved these changes
Looks much more cleansed now

2021-03-10 14:35 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> -class ServiceHandler:
No other component using this? I know SSPL had introduced it so we scanned through our code base, can you scan through whole cortx repo also just to be sure we are not breaking someone else code flow. 
VM deployment, once SSPL errors resolved, would also show this, but why to wait till that moment.

2021-03-10 14:44 UTC, ujjwalpl requested changes

2021-03-10 14:44 UTC, ujjwalpl commented on py-utils/src/utils/service/service_handler.py
> +                                DbusServiceHandler._get_systemd_interface()
Please fix indentation at this and all the places. Indentation needs to be 4 spaces.

2021-03-10 14:44 UTC, ujjwalpl commented on py-utils/src/utils/service/service_handler.py
> +    def __init__(self, handler_type: str):
You dont need to pass service name to all the interfaces. Service is representing one Service. 

```
def __init__(self, service_name: str, handler_type: str):
    self._service_name = service_name 
    ....

def start(self):
    self._handler.start(self, self._service_name)
    ....
```

2021-03-10 15:21 UTC, shriya-deshmukh commented on py-utils/src/utils/service.py
> -class ServiceHandler:
checked - "grep -nre 'from cortx.utils.service'" for other cortx components, No one using this file/class other than the cortx-monitor.

2021-03-10 15:24 UTC, cdeshmukh commented on py-utils/src/utils/service.py
> -class ServiceHandler:
Great, thanks. 

Am not getting 'Resolve' option for any comments here, so all here remaining open

2021-03-10 15:25 UTC, cdeshmukh approved these changes

2021-03-10 17:01 UTC, ujjwalpl approved these changes

2021-03-10 17:11 UTC, sachinpunadikar approved these changes
+1

2021-03-10 17:14 UTC, merged