Conf: Added Setup Framework
Seagate/cortx-utils pull request #221
Opened 2021-03-09 07:02 UTC by ujjwalpl

Signed-off-by: Ujjwal Lanjewar <ujjwal.lanjewar@seagate.com>

2021-03-10 11:08 UTC, sachinpunadikar commented on py-utils/src/utils/setup/utils/setup_cli.py
> +        pass
Need to return 0 to indicate a success.
If "pass" is taking care of that , then no change is needed

2021-03-10 11:45 UTC, sachinpunadikar commented on py-utils/src/utils/setup/kafka/kafka_setup.py
> +        pass
Need to return 0 to indicate success. If "pass" is capable of doing this, then ignore this comment.
Take care of all the commands likewise.

2021-03-10 11:49 UTC, sachinpunadikar commented on py-utils/src/utils/setup/kafka/kafka.py
> +class Utils:
I suppose the class name should be Kafka

2021-03-10 11:55 UTC, sachinpunadikar requested changes
Please check the comments and make changes accordingly

2021-03-12 08:22 UTC, andkononykhin2 commented on py-utils/setup.py
> +                     ('/opt/seagate/cortx/utils/conf', ['requirements.txt', 'src/utils/setup/utils/setup.yaml'])],
@ujjwalpl @sachinpunadikar It's not a change of the current PR but I've just noticed that you install some data files into global locations. Is root-based installation considered only? Would it be possible to use cortx-utils in non-root python isolated environment as it usually happens for python projects?

2021-03-15 14:36 UTC, sachinpunadikar commented on py-utils/setup.py
> +                     ('/opt/seagate/cortx/utils/conf', ['requirements.txt', 'src/utils/setup/utils/setup.yaml'])],
@andkononykhin2, currently we are considering root-based installations. But in future we can work on non-root based environment.

2021-03-16 10:27 UTC, ujjwalpl commented on py-utils/src/utils/setup/utils/setup_cli.py
> +        pass
Done

2021-03-16 10:27 UTC, ujjwalpl commented on py-utils/src/utils/setup/kafka/kafka_setup.py
> +        pass
Done

2021-03-16 10:27 UTC, ujjwalpl commented on py-utils/src/utils/setup/kafka/kafka.py
> +class Utils:
Done

2021-03-17 03:17 UTC, sachinpunadikar approved these changes
+1

2021-03-17 03:18 UTC, sachinpunadikar commented
Please work on the conflicting files.

2021-03-17 17:46 UTC, rahul-tripathi-git approved these changes
+1

2021-03-17 17:59 UTC, sachinpunadikar commented
RPM installation is failing. Need to fix this. I did mentioned this earlier as well .. post_install script will need change.
23:24:41      Running transaction
23:24:41        Installing : cortx-py-utils-2.0.0-174_fb22b99.noarch                      1/1
23:24:41      /bin/cp: cannot stat '/usr/lib/python3.6/site-packages/cortx/utils/setup/setup_cli.py': No such file or directory
23:24:41      /bin/chmod: cannot access '/opt/seagate/cortx/utils/bin/utils_setup': No such file or directory
23:24:41      warning: %post(cortx-py-utils-2.0.0-174_fb22b99.noarch) scriptlet failed, exit status 1

2021-03-18 04:36 UTC, s-arya approved these changes

2021-03-18 12:51 UTC, merged