Rest interface of message bus
Seagate/cortx-utils pull request #222
Opened 2021-03-09 07:07 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

2021-03-09 07:27 UTC, ujjwalpl requested changes

2021-03-09 07:27 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/message_bus_rest.py
> +#!/usr/bin/env python3
REST server for Message Bus needs to be in the Message Bus and not outside as it is integral component of Message Bus.

2021-03-09 07:27 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/error.py
> +class RestServerError(Exception):
Rest Server needs to handle HTTP error codes.

2021-03-09 07:27 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/message_bus_rest.py
> +def message_bus_rest(message_type: str):
We dont define global functions. Please come up with class structure

2021-03-09 07:27 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/rest.service
> +ExecStart=/usr/bin/python3 /usr/lib/python3.6/site-packages/cortx/utils/rest_server/message_bus_rest.py
Execution Command needs to be a command and not a python file.

2021-03-09 08:24 UTC, selvakumaar5496 commented on py-utils/src/utils/rest_server/rest.service
> +ExecStart=/usr/bin/python3 /usr/lib/python3.6/site-packages/cortx/utils/rest_server/message_bus_rest.py
This is a how I read in a post(same is available in many sites). Could you suggest an alternate way

2021-03-09 08:29 UTC, selvakumaar5496 commented on py-utils/src/utils/rest_server/error.py
> +class RestServerError(Exception):
Http codes will be a part on client code right ?
for ex: 
import requests
response = requests.get(url)
response.status_code ---> will return error code if not 200

2021-03-09 15:04 UTC, ujjwalpl requested changes

2021-03-09 15:04 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/message_bus_rest.py
> +#!/usr/bin/env python3
You can have a separate folder for REST server framework which should be independent of message bus. 
Any message bus code must be in the message_bus folder only. 
Its like we have utils and utils_cli in the same place. 

Following all the things should be in message bus whenever they are implemented. 
message_bus
message_bus_server (Can use generic rest server framework)
message_bus_cli
message_bus_api
etc.

2021-03-09 15:04 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/message_bus_rest.py
> +def message_bus_rest(message_type: str):
We decide to have GET PUT. Why POST ?

2021-03-09 15:04 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/rest.service
> +ExecStart=/usr/bin/python3 /usr/lib/python3.6/site-packages/cortx/utils/rest_server/message_bus_rest.py
You need to have a command. You need to define an endpoint in the setup.py name message_bus_server and call that from here.

2021-03-09 15:04 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/message_bus_rest.py
> +#!/usr/bin/env python3
Rename this file to message_bus_server.py and move to message_bus. Separate REST server framework part if any which can be in this folder.

2021-03-10 12:36 UTC, selvakumaar5496 commented on py-utils/src/utils/rest_server/message_bus_rest.py
> +def message_bus_rest(message_type: str):
Changed to PUT

2021-03-11 03:42 UTC, selvakumaar5496 commented on py-utils/src/utils/rest_server/message_bus_rest.py
> +#!/usr/bin/env python3
changed location

2021-03-11 03:43 UTC, selvakumaar5496 commented on py-utils/src/utils/rest_server/message_bus_rest.py
> +#!/usr/bin/env python3
renamed and moved

2021-03-18 07:27 UTC, ujjwalpl requested changes

2021-03-18 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server
> +                message = consumer.receive()
We need to see if we can return multiple messages. as network calls expensive

2021-03-18 07:27 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/rest.service
> +[Unit]
REST code should be generic and not have anything called message_bus in it. 

Move this file to message_bus_server folder.

2021-03-18 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server
> +app = Flask(__name__)
Can we avoid using global variable ? Why cant we do in MessageBusServer.__init__() ?

2021-03-18 07:27 UTC, ujjwalpl commented on py-utils/requirements.txt
> +flask==1.1.2
You need to ensure and get approval from RE if this is already a used package. If not initiate fresh approval of including a new opensource package. Check with CSM team which REST package they use.

2021-03-18 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server
> +                raise MessageBusError(_error_status, "Unable to receive messages \
On, Error you should send REST error response back to the REST Client not throw exception. Server never should die.

2021-03-18 07:27 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server
> +            except Exception as e:
On, Error you should send REST error response back to the REST Client not throw exception. Server never should die.

2021-03-25 08:08 UTC, selvakumaar5496 commented
Requirement got changed. Flask is not a approved library

2021-03-25 08:08 UTC, closed without merging