ConfStore: get_keys API
Seagate/cortx-utils pull request #227
Opened 2021-03-11 17:52 UTC by suryakumar1024

Updated self._keys in kv_payload
updated existing set, delete api code to support get_keys

Signed-off-by: suryakumar <suryakumar.kumaravelan@seagate.com>

2021-03-12 04:55 UTC, sachinpunadikar requested changes
Get rid of not required print.
Also provide sample example & o/p of the same

2021-03-12 10:42 UTC, ujjwalpl requested changes

2021-03-12 10:42 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        key_index_status = True if (args.key_index == None or
```
key_index = 'true' if args.key_index == None else args.key_index.lower().strip()
key_index = True if key_index == 'true' else False if key_index == 'false' else None
if key_index == None:
        raise Error(...)
return Conf.get_keys(ConfCli._index, key_index=key_index)
```

2021-03-12 10:42 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +class Get_KeysCmd:
You can remove _ from class name. Class names are with Canonical names. 

class GetKeysCommand:

2021-03-12 10:42 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "# conf json:///tmp/csm.conf get_keys -key_index true\n\n")
"# conf json:///tmp/csm.conf get_keys -key_index false\n\n")

2021-03-12 10:42 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "when False, returns keys including array index\n"
when True, returns keys including array index.

2021-03-12 10:42 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_payload.py
> +                    when False, returns keys including array index
when True, returns keys including array index

2021-03-12 10:42 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                keys.append(f"{section}>{key}")
keys.append(f"{section}{delim}{key}")

Please change to delim. There are few more places where '>' is used.

2021-03-12 12:14 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +        key_index_status = True if (args.key_index == None or
Updated in current patch

2021-03-12 12:14 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +class Get_KeysCmd:
Updated in current patch

2021-03-12 12:14 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "# conf json:///tmp/csm.conf get_keys -key_index true\n\n")
Updated in current patch

2021-03-12 12:14 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "when False, returns keys including array index\n"
Updated comment in current patch

2021-03-12 12:15 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_payload.py
> +                    when False, returns keys including array index
Updated comment in current patch

2021-03-12 12:15 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                keys.append(f"{section}>{key}")
Updated including inikvstore get, set and delete delim changes.

2021-03-12 12:20 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +        print(key_index_status)
Removed those 88 and 89 line statements. Updated in current patch

2021-03-22 18:11 UTC, sachinpunadikar approved these changes
+1

2021-03-24 09:43 UTC, ujjwalpl requested changes

2021-03-24 09:43 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +    def get_keys(args) -> str:
This should be returning list of keys ?

2021-03-24 09:43 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +    def get_keys(self, index: str, **filters):
Returns ? i.e.g "-> list" ?

2021-03-24 09:43 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +    def get_keys(index: str, **filters):
Returns ?

2021-03-24 09:43 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_payload.py
> +    def get_keys(self, **filters):
Returns ?

2021-03-24 09:43 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def _get_keys(self, keys: list, data, pkey: str = None,
Returns ?

2021-03-29 13:00 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
> +    def get_keys(args) -> str:
Updated in recent patch

2021-03-29 13:01 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +    def get_keys(self, index: str, **filters):
Updated in recent patch

2021-03-29 13:01 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +    def get_keys(index: str, **filters):
Updated in recent patch

2021-03-29 13:01 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_payload.py
> +    def get_keys(self, **filters):
Updated in recent patch

2021-03-29 13:01 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def _get_keys(self, keys: list, data, pkey: str = None,
Updated in recent patch

2021-03-30 05:14 UTC, ujjwalpl approved these changes

2021-04-01 13:56 UTC, s-arya approved these changes

2021-04-02 07:53 UTC, mukul-seagate11 commented
ok to test

2021-04-02 07:53 UTC, mukul-seagate11 commented
run mini-provisioning

2021-04-02 09:38 UTC, merged