EOS-18797: [cortx-utils] Add confstore key validator in confstore
Seagate/cortx-utils pull request #235
Opened 2021-03-17 05:27 UTC by pratyush-seagate

commit 7a1a1ed2f94a4165650255f491eb5d1f5bed28f3
Author: pratyush-seagate <pratyush.k.khan@seagate.com>
Date:   Tue Mar 16 15:01:33 2021 -0600

        EOS-18797: [cortx-utils] Add confstore key validator in confstore
            Change description:
                A confstore key validator v_confkeys, associated unit tests, update readme and usage info fix in commands.py
            Added/modified/deleted files:
                modified:   py-utils/README.md
                modified:   py-utils/src/utils/validator/commands.py
                new file:   py-utils/src/utils/validator/v_confkeys.py
                modified:   py-utils/src/utils/validator/validate.py
                new file:   py-utils/test/validator/test_confkeys_validator.py
            Unit test:
                    Run new associated added unit tests.
                        python3.6 py-utils/test/validator/test_confkeys_validator.py
                        ..
                        ----------------------------------------------------------------------
                        Ran 2 tests in 0.007s

                        OK

    Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

2021-03-17 06:48 UTC, amitwac2608 reviewed
minor comments, look good.

2021-03-17 06:48 UTC, amitwac2608 commented on py-utils/src/utils/validator/commands.py
> +    """Verify if constore contains the provided keys."""
typo in 'constore'

2021-03-17 06:48 UTC, amitwac2608 commented on py-utils/src/utils/validator/commands.py
> +        """Validate if constore contains the provided keys."""
typo

2021-03-18 07:36 UTC, sachinpunadikar commented on py-utils/src/utils/validator/v_confkeys.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
correct the year 
2020 -> 2021

2021-03-18 07:38 UTC, sachinpunadikar commented on py-utils/test/validator/test_confkeys_validator.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
correct the year

2021-03-18 07:46 UTC, sachinpunadikar approved these changes
Minor comments, please work on that.
Approving

2021-03-18 08:15 UTC, pratyush-seagate commented
> 
> 
> Minor comments, please work on that.
> Approving

thanks. Please check now.

2021-03-18 08:32 UTC, ujjwalpl requested changes

2021-03-18 08:32 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +        self._confkeys.validate(self.v_confkeys, self.args)
Where is self.v_confkeys initialized ? shouldnt it be self.v_type ?

2021-03-18 08:45 UTC, pratyush-seagate commented on py-utils/src/utils/validator/commands.py
> +        self._confkeys.validate(self.v_confkeys, self.args)
thanks for catching this, fixed.

2021-03-18 11:41 UTC, ujjwalpl approved these changes

2021-03-18 13:33 UTC, udayan-y21 approved these changes

2021-03-18 17:13 UTC, merged