Cs pillar set delete
Seagate/cortx-utils pull request #238
Opened 2021-03-18 18:52 UTC by suryakumar1024

KvStorePillar Set API
KvStorePillar Delete API

Eg Code:

2021-03-30 16:13 UTC, ujjwalpl requested changes

2021-03-30 16:13 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    _pillar_root="/srv/pillar/"
Why is this a hard code value ? It should be part of the URL.

2021-03-30 16:13 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                        yaml.dump(yaml.safe_load(data), f, default_flow_style=False)
Why yaml.dump ?

2021-03-30 16:17 UTC, ujjwalpl requested changes

2021-03-30 16:17 UTC, ujjwalpl commented on py-utils/test/test_kv_store/test_kv_store.py
> +    def test_kv_pillar_support(self):
Need to add test for dump as well. 

test cases should be
1. Set a new value
2. Modify an existing value
3. Delete an existing value
4. Negative tests load non existent pillar store. 
5. Try to set / dump empty data set. 
6. Delete all the values.

2021-03-31 10:27 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                        yaml.dump(yaml.safe_load(data), f, default_flow_style=False)
There is no straightforward way to set a value to pillar store. And all the configurations for pillar is kept as .sls files (yaml). So, the only way is to set operation is to updated the files using yaml package.

2021-03-31 10:29 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    _pillar_root="/srv/pillar/"
Updated. 

Current url now -> pillar:///srv/pillar@srvnode-1

where /srv/pillar is location of pillar 
srvnode-1 is target node

2021-04-16 04:12 UTC, sachinpunadikar commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        self._tragets are required to run a slat command.
typo  slat  -> salt

2021-04-16 04:12 UTC, sachinpunadikar commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        sls files need to be stored
sls -> "*.sls"

2022-01-07 04:12 UTC, suryakumar1024 commented
Closing this PR. Requirement no longer valid

2022-01-07 04:12 UTC, closed without merging