MessageBus: To increase concurrency for a message_type
Seagate/cortx-utils pull request #245
Opened 2021-03-22 12:39 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

2021-03-22 13:22 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        new_partition = [NewPartitions(message_type, \
Add check for if the new value is less than or equal to existing value.
If so, do nothing and return error / success likewise. Error should say "can not decrease the concurrency count"

2021-03-22 13:23 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        for list_retry in range(1, self._max_list_message_type_count+2):
Add a comment on what is this retry for ?

2021-03-22 13:23 UTC, sachinpunadikar requested changes
Work on the comments

2021-03-23 07:45 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        new_partition = [NewPartitions(message_type, \
Kafka handles this error

2021-03-23 07:45 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        for list_retry in range(1, self._max_list_message_type_count+2):
done. added

2021-03-24 12:40 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        # Retries for an amount of time to increase the partition
Better wording would be
"Waiting for few seconds/milliseconds to complete the partition addition process"
Mention exact waiting period if known

2021-03-24 12:44 UTC, sachinpunadikar approved these changes
+1
A minor comment. Work on that

2021-03-24 15:06 UTC, ujjwalpl requested changes

2021-03-24 15:06 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def add_concurrency(self, admin_id: str, message_type: str, \
Concurrency and replication are two things. Concurrency is the performance measure. This one is more related to replication.

2021-03-25 05:00 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    def add_concurrency(self, admin_id: str, message_type: str, \
Discussed and finalized to go with concurrency

2021-03-26 04:38 UTC, ujjwalpl approved these changes

2021-04-02 07:43 UTC, mukul-seagate11 commented
ok to test

2021-04-02 07:44 UTC, mukul-seagate11 commented
run mini-provisioning

2021-04-02 09:39 UTC, merged