WIP: Adedd syetemd Unit files for Kafka and Zookeeper
Seagate/cortx-utils pull request #246
Opened 2021-03-23 04:13 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

2021-03-23 04:18 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-03-23 04:27 UTC, sachinpunadikar commented on py-utils/src/utils/setup/kafka/kafka-zookeeper.service
> +ExecStart=/opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties
What abt JAVA_HOME ? Is that not required ?

2021-03-23 16:26 UTC, rahul-tripathi-git commented on py-utils/src/utils/setup/kafka/kafka-zookeeper.service
> +ExecStart=/opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties
Yes @sachinpunadikar  It is not required. Kafka will refer to Java present in system. We dont need to mention it exclusively.

2021-03-23 16:40 UTC, ujjwalpl requested changes

2021-03-23 16:40 UTC, ujjwalpl commented on py-utils/utils-post-install
> +/bin/chmod +x /opt/seagate/cortx/utils/bin/kafka_setup
Please keep all the setup related files only in /opt/seagate/cortx/utils/conf/

Also, I dont see setup.yaml for kafka setup.

2021-03-23 17:48 UTC, sachinpunadikar commented on py-utils/utils-post-install
> +/bin/chmod +x /opt/seagate/cortx/utils/bin/kafka_setup
@ujjwalpl  as such  kafka_setup and related files is responsibility of provisioner team. So setup.yaml should be coming from them.

2021-03-23 18:48 UTC, sachinpunadikar approved these changes
+1

2021-03-23 18:50 UTC, sachinpunadikar commented
@ypise  please review the service files for kafka broker & zoo-keeper. More precisely the paths being used.

2021-03-23 19:30 UTC, rahul-tripathi-git commented on py-utils/utils-post-install
> +/bin/chmod +x /opt/seagate/cortx/utils/bin/kafka_setup
@ujjwalpl kafka_setup to /opt/seagate/cortx/utils/conf/

2021-03-24 16:21 UTC, ujjwalpl requested changes

2021-03-24 16:21 UTC, ujjwalpl commented on py-utils/utils-post-install
> +/bin/chmod +x /opt/seagate/cortx/utils/bin/kafka_setup
/bin/chmod +x /opt/seagate/cortx/utils/conf/kafka_setup

2021-03-24 18:13 UTC, rahul-tripathi-git commented on py-utils/utils-post-install
> +/bin/chmod +x /opt/seagate/cortx/utils/bin/kafka_setup
@ujjwalpl, corrected this.

2021-03-25 07:35 UTC, ypise reviewed
@sachinpunadikar 
I'm submitting my feedback on this review. Please do use your discretion to accept or override the feedback comments.

2021-03-25 07:35 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka-zookeeper.service
> +Type=simple
Does Kafka not use a nologin user?
If it does, we need these entries:
```
User=kafka
Group=kafka
```

2021-03-25 07:35 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka.py
>          return 0
`return 0` here means nothing.
What we want is something equivalent to `exit 0` in bash. It can be achieved using `exit(0)`, but that would be unclean exit, unless we are using context managers.

Have no returns to the method and have exceptions for any anomalies, so that they automatically ensure non-zero return.

2021-03-25 07:35 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka.py
>          return 0
With same reasoning as above,
have no returns to the method and have exceptions for any anomalies, so that they automatically ensure non-zero return.

2021-03-25 07:35 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka.py
>          return 0
With same reasoning as above,
have no returns to the method and have exceptions for any anomalies, so that they automatically ensure non-zero return.

2021-03-25 07:35 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka.py
>          return 0
With same reasoning as above,
have no returns to the method and have exceptions for any anomalies, so that they automatically ensure non-zero return.

2021-03-25 07:35 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka.py
>          return 0
With same reasoning as above,
have no returns to the method and have exceptions for any anomalies, so that they automatically ensure non-zero return.

2021-03-25 07:35 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka.service
> +ExecStop=/opt/kafka/bin/kafka-server-stop.sh
Does Kafka not use a nologin user?
If it does, we need these entries:
```
User=kafka
Group=kafka
```

It's usually a good practice to have a no-login user for a service.

2021-03-25 07:35 UTC, ypise commented on py-utils/utils-post-install
>  # For any questions about this software or licensing,
Also, along with this file provide a reset/cleanup (@sachinpunadikar, @nitin-seagate please help with the right interface candidate here), to undo the changes made by this file.

2021-03-25 07:35 UTC, ypise commented on py-utils/utils-post-install
> +/bin/chmod +x /opt/seagate/cortx/utils/conf/kafka_setup
It would be a good idea to check if nologin kafka user and group are created by rpm, if not create them here.

2021-03-25 17:42 UTC, rahul-tripathi-git commented on py-utils/utils-post-install
>  # For any questions about this software or licensing,
@ypise, yes this has been already incorporated in utils-post-uninstall phase.

2021-09-02 13:39 UTC, rahul-tripathi-git commented
Closing this PR. 
Designed was changed and kafka service files and all related settings was added to a separate rpm created for kafka.

2021-09-02 13:39 UTC, closed without merging