Added deepcopy functionality for get api return value
Seagate/cortx-utils pull request #248
Opened 2021-03-24 10:33 UTC by suryakumar1024

Fix for get api return value
Fix for:
if return value modified from used side then the conf in-memory value also get affected 

Added deepcopy method which used to return only copy of the object instead of returning the actual object ref.

Signed-off-by: suryakumar <suryakumar.kumaravelan@seagate.com>

2021-03-24 11:56 UTC, sachinpunadikar approved these changes
+1

2021-03-25 05:28 UTC, ujjwalpl requested changes

2021-03-25 05:28 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        ret_val = default_val if val is None else val
This is changing the ConfStore Spec. Users can do the copy if required. This does not require ConfStore fix.

2021-03-29 04:22 UTC, suryakumar1024 commented
Closing this PR since the change was not required.
ref -> EOS-18898 for any further history of this task.

2021-03-29 04:22 UTC, closed without merging