WIP:Add template files for utils_setup
Seagate/cortx-utils pull request #249
Opened 2021-03-24 11:33 UTC by sachinpunadikar

"utils_setup" has various phases like post_install, prepare, config,
init, test, reset and cleanup. By default we need to pass on the config
file for every phase. If a phase do not need any keys, the template file
is empty.

2021-03-24 13:39 UTC, ujjwalpl requested changes

2021-03-24 13:39 UTC, ujjwalpl commented on py-utils/setup.py
> +                     ('/opt/seagate/cortx/utils/conf', ['requirements.txt', 'src/setup/setup.yaml',
Can we maintain indentation and avoid spilling over to the next line ?

2021-03-24 14:50 UTC, rahul-tripathi-git commented
Just a suggestion, Shall we create a a separate dir for all the template files inside py-utils/src/setup/ ?

2021-03-24 14:58 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +                     ('/opt/seagate/cortx/utils/conf', ['requirements.txt', 'src/setup/setup.yaml',
a suggestion, shall we create a separate function call to fetch all the template files just like we are doing it for specs ?

for example:

def fun():
    return [4, 5, 6]
print([1, 2, 3, *fun()])

OUT: [ 1, 2, 3, 4, 5, 6 ]

2021-03-24 15:06 UTC, rahul-tripathi-git reviewed
Just a suggestion, Shall we create a a separate dir for all the template files inside py-utils/src/setup/ ?

2021-03-24 15:06 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +                     ('/opt/seagate/cortx/utils/conf', ['requirements.txt', 'src/setup/setup.yaml',
A suggestion, shall we create a separate function call to fetch all the template files just like we are doing it for specs ?

for example:

def fun():
return [4, 5, 6]

print([1, 2, 3, *fun()])

OUT: [ 1, 2, 3, 4, 5, 6 ]

2021-03-24 16:22 UTC, sachinpunadikar commented on py-utils/setup.py
> +                     ('/opt/seagate/cortx/utils/conf', ['requirements.txt', 'src/setup/setup.yaml',
Made the indentation changes

2021-03-24 16:31 UTC, ujjwalpl requested changes

2021-03-24 16:31 UTC, ujjwalpl commented on py-utils/src/setup/templates/utils.config.tmpl.1-node
> +      - TMPL_KAFKA_SERVER1_FQDN:TMPL_KAFKA_SERVER1_PORT
- TMPL_KAFKA_SERVER1_FQDN:TMPL_KAFKA_SERVER1_PORT
- TMPL_KAFKA_SERVER2_FQDN:TMPL_KAFKA_SERVER2_PORT
- TMPL_KAFKA_SERVER3_FQDN:TMPL_KAFKA_SERVER3_PORT

2021-03-24 16:31 UTC, ujjwalpl commented on py-utils/utils-post-install
>  /bin/cp -f /usr/lib/python3.6/site-packages/cortx/setup/utils_setup.py /opt/seagate/cortx/utils/bin/utils_setup
/opt/seagate/cortx/utils/bin/utils_setup -> /opt/seagate/cortx/utils/conf/utils_setup

2021-03-24 16:33 UTC, ujjwalpl approved these changes

2021-03-25 07:00 UTC, sachinpunadikar commented on py-utils/setup.py
> +                     ('/opt/seagate/cortx/utils/conf', ['requirements.txt', 'src/setup/setup.yaml',
@rahul-tripathi-git , made required change to get the list instead of mentioning each & every file

2021-03-25 07:48 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-03-25 07:49 UTC, rahul-tripathi-git approved these changes
+1

2021-03-25 07:50 UTC, merged