MessageBus: Implement Singleton Class
Seagate/cortx-utils pull request #250
Opened 2021-03-25 07:30 UTC by selvakumaar5496

2021-03-25 08:34 UTC, ujjwalpl requested changes

2021-03-25 08:34 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        self._message_bus = MessageBus() if client_conf['message_bus'] is None \
self._message_bus = MessageBus() if 'message_bus' not in client_conf.keys() or client_conf['message_bus'] is None \

2021-03-25 08:34 UTC, ujjwalpl commented on py-utils/test/test_message_bus/test_singleton.py
> +    def test_singleton(self):
Test does not test mesage_bus == None case.  Add a test where you do not instantiate MesssageBus at all. Directly start with MessageProducer().

2021-03-25 08:41 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        self._message_bus = MessageBus() if client_conf['message_bus'] is None \
'message_bus' will always be a part of client_conf.keys(). The value of it will be either None or MessageBus() instance. Hence not checking **if 'message_bus' not in client_conf.keys()**

2021-03-25 10:37 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_singleton.py
> +    def test_singleton(self):
Added more test cases 
        Message Bus is None. Checked with Admin, Producer, Consumer.
	MessageBus is instantiated only once. Checked with Admin, Producer, Consumer.
	MessageBus is Instantiated more than once(3). Checked with Admin, Producer, Consumer.

2021-03-25 11:42 UTC, ujjwalpl requested changes

2021-03-25 11:42 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        self._message_bus = MessageBus() if client_conf['message_bus'] is None \
Code needs to be assumption free and should not break for external assumptions.

2021-03-25 13:30 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        self._message_bus = MessageBus() if client_conf['message_bus'] is None \
added

2021-03-25 17:42 UTC, ujjwalpl approved these changes

2021-03-26 04:45 UTC, sachinpunadikar approved these changes
+1

2021-03-26 08:57 UTC, rahul-tripathi-git approved these changes
looks good to me.

2021-04-01 11:00 UTC, ujjwalpl approved these changes

2021-04-02 07:59 UTC, mukul-seagate11 commented
ok to test

2021-04-02 07:59 UTC, mukul-seagate11 commented
run mini-provisioning

2021-04-05 06:14 UTC, merged