Kafka
Seagate/cortx-utils pull request #252
Opened 2021-03-30 05:10 UTC by anurag-modi

Added code for Kafka server start.

2021-03-30 05:13 UTC, anurag-modi commented
@andkononykhin @ypise please review

2021-03-30 09:59 UTC, andkononykhin2 reviewed
@anurag-modi Please check my suggestions in comments. Thank you

2021-03-30 09:59 UTC, andkononykhin2 commented on py-utils/src/utils/setup/kafka/kafka_states.py
> +        logging.exception(e)
@anurag-modi you don't need two separate calls for logging: [logging.exception](https://docs.python.org/3.6/library/logging.html#logging.exception) considers itself a message as a first arg and doesn't need an exception since it can find out that itself.

2021-03-30 09:59 UTC, andkononykhin2 commented on py-utils/src/utils/setup/kafka/kafka_states.py
> +            "/opt/kafka/kafka_"+kafka_version
I would suggest to make path to executable a constant-like template:
```python
ZOOKEEPER_BIN_TMPL = (
    "/opt/kafka/kafka_{kafka_version}/bin/zookeeper-server-start.sh"
)
     ...
    zookeper_bin = ZOOKEEPER_BIN_TMPL.format(kafka_version)
    subprocess.run(
            f"{zookeeper_bin} -daemon config/zookeeper.properties"
        )
```

2021-03-30 09:59 UTC, andkononykhin2 commented on py-utils/src/utils/setup/kafka/kafka_states.py
> +        sys.exit(1)
as long as it is a library layer `exit` is not good here, please use `raise` instead and let tool layer takes care about the exit

2021-03-30 09:59 UTC, andkononykhin2 commented on py-utils/src/utils/setup/kafka/kafka_states.py
> +        start_zookeeper_server = subprocess.run(
In [provisioner repository](https://github.com/Seagate/cortx-prvsnr/blob/66b90f4f0091df035eabb046c5e399829ac42e0a/srv/components/misc_pkgs/kafka/start.sls#L23-L24) we have additional logic that adds conditional on current status of `zookeper` process and takes care about the current working directory. I believe we should respect the same here.

2021-03-30 09:59 UTC, andkononykhin2 commented on py-utils/src/utils/setup/kafka/kafka_states.py
> +# TODO remove once dummy testing is done
I believe we don't need these debug-related lines anymore here.

2021-03-30 18:09 UTC, ypise requested changes

2021-03-30 18:09 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka_states.py
> +        start_zookeeper_server = subprocess.run(
We are not handling sub-process non-zero exits.
```
start_zookeeper_server.check_returncode()
```
is essential here.

Ref: https://github.com/Seagate/cortx-prvsnr/blob/pre-cortx-1.0/srv/_modules/sync.py#L208

2021-03-30 18:09 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka_states.py
> +        start_zookeeper_server = subprocess.run(
`/bin/zookeeper-server-start.sh -daemon config/zookeeper.properties` shall go in systemd service unit file.
Check with @sachinpunadikar and @shailesh-vaidya regarding plans for installing Kafka as an rpm.
Ensure, the service unit file is embedded in the rpm.
Then make systemd calls in the method.

2021-03-30 18:09 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka.py
> +        # TODO check either arbitrary JSON can be expected here
These configs should be part of config method.
post_install addresses creation of systemd service unit file if that is not addressed by generation of rpm for Kafka.

2021-03-30 18:09 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka.py
>      def init(self):
Service start call happens here in `init` method.

2021-03-30 18:09 UTC, ypise commented on py-utils/src/utils/setup/kafka/kafka.py
>      def init(self):
Under reset we need to replicate the behavior from:
https://github.com/Seagate/cortx-prvsnr/blob/66b90f4f0091df035eabb046c5e399829ac42e0a/srv/components/misc_pkgs/kafka/teardown.sls

2021-03-30 18:12 UTC, ypise commented
@rahul-tripathi-git , @sachinpunadikar 
This PR is similar to https://github.com/Seagate/cortx-utils/pull/246/files

Do consider this while you are working on #246

2021-09-02 13:17 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-09-02 13:39 UTC, rahul-tripathi-git commented
Closing this PR. 
Designed was changed and kafka service files and all related settings was added to a separate rpm created for kafka.

2021-09-02 13:39 UTC, closed without merging