WIP: Added Validation for confstore cluster config keys in utils_setup
Seagate/cortx-utils pull request #253
Opened 2021-03-30 18:32 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

2021-03-30 18:32 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-03-30 18:40 UTC, rahul-tripathi-git commented
run mini-provisioning

2021-03-31 04:56 UTC, ujjwalpl requested changes

2021-03-31 04:56 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +    ConfKeysV.validate(v_type="exists", index="cluster_config", keylist=["cortx>software>common>message_bus_type"])
keylist needs to include all the keys. 
```
keylist = [ 'cortx>software>common>message_bus_type', 'cortx>software>common>message_servers' ]
ConfKeysV.validate("exists", "cluster_config", keylist)
```
Also, take care of indentation and line exceeding 80 chars.

2021-03-31 05:36 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +    ConfKeysV.validate(v_type="exists", index="cluster_config", keylist=["cortx>software>common>message_bus_type"])
Thanks for pointing these out @ujjwalpl , fixed both, and tested locally.

2021-04-01 10:57 UTC, ujjwalpl requested changes

2021-04-01 10:57 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +
Please move global functions to within the class.

2021-04-01 11:25 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +
Thanks for pointing this out @ujjwalpl, made the suggested changes.

2021-04-05 06:10 UTC, ujjwalpl approved these changes

2021-04-05 18:08 UTC, rahul-telawade approved these changes
Look ok for me

2021-04-07 15:00 UTC, rahul-tripathi-git commented
run mini-provisioning

2021-04-09 03:49 UTC, suryakumar1024 approved these changes

2021-04-09 05:02 UTC, merged