MessageBus: Rest Interface using aiohttp
Seagate/cortx-utils pull request #254
Opened 2021-03-31 10:27 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

2021-03-31 18:13 UTC, ujjwalpl requested changes

2021-03-31 18:13 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/messagebus-rest.service
> +ExecStart=/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_bus_server
Path should be /opt/seagate/cortx/utils/message_bus/message_bus_server. Add this path in setup.py

2021-03-31 18:13 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server
> +#!/usr/bin/env python3
Where is the test code ?

2021-03-31 18:16 UTC, ujjwalpl requested changes

2021-04-01 08:58 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_server
> +    @routes.put('/MessageBus/{message_type}')
Ip and port allocated as per the Spec document

2021-04-01 08:59 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_server
> +    @routes.get('/MessageBus/{message_type}')
separate RestServer class is created and MessageBusRestServer is a subclass of it. Any new rest server implementation can use RestServer interface

2021-04-01 11:07 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_server
> +#!/usr/bin/env python3
Test code is added

2021-05-18 10:27 UTC, selvakumaar5496 commented
created a new PR for this, hence closing this.

2021-05-18 10:27 UTC, closed without merging