machine_id api implemented
Seagate/cortx-utils pull request #255
Opened 2021-04-05 04:29 UTC by suryakumar1024

Add method get_machine_id in Conf class. This will read from
file /etc/machine-id and return the unique id.

Example:
from cortx.utils.conf_store import Conf
Conf.load("index_1", "json:///tmp/cloud.json")
mc_id = Conf.get_machine_id()
print(f"mc_id {mc_id}") # will print machine id

Signed-off-by: suryakumar <suryakumar.kumaravelan@seagate.com>

2021-04-05 06:26 UTC, ujjwalpl requested changes

2021-04-05 06:26 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        self._get_machine_id()
As per the name it should return machine_id. It should be written as 
```
self._machine_id = self._get_machine_id()
```

2021-04-05 06:26 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +    @staticmethod
Please use @property

2021-04-05 12:12 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +    @staticmethod
@ujjwalpl If we want to use @property then we have to initialize the class Eg. Conf()  before returning the property value, else we get property object like below

Conf.machine_id

<property object at 0x7fa23f6961d8>

2021-04-05 12:26 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        self._get_machine_id()
Updated in recent patch.

2021-04-05 14:03 UTC, ujjwalpl requested changes

2021-04-05 15:23 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_store.py
> +    def test_conf_store_get_machin_id(self):
Updated test case in current patch

2021-04-05 15:23 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +    @staticmethod
Updated code in current patch

2021-04-06 05:01 UTC, ujjwalpl requested changes

2021-04-07 09:22 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +
Updated in current patch

2021-04-07 09:22 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        Conf._conf = ConfStore()
Updated in current patch

2021-04-07 09:22 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +            Conf._machine_id = Conf._conf.machine_id
updated current patch

2021-04-07 09:22 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        if Conf._conf == None:
update current patch

2021-04-07 09:37 UTC, ujjwalpl requested changes

2021-04-07 09:37 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        from pathlib import Path
I dont see pathlib installed by default in the system. We need to avoid adding new dependencies.

2021-04-07 09:37 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +            return machine_id
return machine_id.strip()

I tested this code and it returns \n as well. 
```
>>> from pathlib import Path
>>> machine_id_file = Path("/etc/machine-id")
>>> if machine_id_file.is_file() and machine_id_file.stat().st_size > 0:
...     with open("/etc/machine-id", 'r') as mc_id_file:
...             machine_id = mc_id_file.read()
...
>>> print(machine_id)
c1fee10274fe49589802d114a863176f

>>> print(machine_id.strip())
c1fee10274fe49589802d114a863176f
>>>
```

2021-04-07 09:40 UTC, ujjwalpl requested changes

2021-04-07 09:40 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        Conf._conf = ConfStore(delim=Conf._delim)
We are introducing calls to conf.init(). Imagine if in multithreaded env, Init is called multiple times you will end up overwriting

```
if Conf._conf is None: 
    for key, val in kwargs.items():
        setattr(Conf, f"_{key}", val)
    Conf._conf = ConfStore(delim=Conf._delim)
    Conf._machine_id = Conf._conf.machine_id
```

2021-04-07 13:01 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        from pathlib import Path
No need to install pathlib package separately, Since it was inbuild one after 3.3 > above python versions

2021-04-07 14:12 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        Conf._conf = ConfStore(delim=Conf._delim)
Updated in current patch

2021-04-07 14:12 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +            return machine_id
updated in current patch. Testcase also updated

2021-04-08 09:11 UTC, ujjwalpl approved these changes

2021-04-09 08:30 UTC, rahul-tripathi-git commented
Kindly proceed with the single node manual provisioning steps.

2021-04-14 05:57 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-04-15 11:35 UTC, sachinpunadikar commented on py-utils/test/test_conf_store/test_conf_store.py
> +        cs_inst = ConfStore(delim=Conf._delim)
why ConfStore is called here ? why can't below be used ?
mc_id = Conf.machine_id

2021-04-15 11:37 UTC, sachinpunadikar requested changes
Use Conf in test code

2021-04-15 11:57 UTC, suryakumar1024 commented on py-utils/test/test_conf_store/test_conf_store.py
> +        cs_inst = ConfStore(delim=Conf._delim)
Since we implemented Conf as singleton. We can't reinitialize it so for testing purpose i used ConfStore class directly just to verify the things working proper even the file is not there.

2021-04-15 13:24 UTC, sachinpunadikar approved these changes
+1

2021-04-15 13:25 UTC, merged