WIP: MessageBus: Rest Interface using aiohttp
Seagate/cortx-utils pull request #257
Opened 2021-04-06 14:20 UTC by rahul-tripathi-git

This commit incorporated all the changes of PR 254.
And a few modifications as well.

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

2021-04-06 14:22 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-04-06 15:01 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                return web.Response(text=json.dumps(response_obj), status=500)
Instead of using a fixed status i.e. 500, we can return more appropriate error code. 

1. Define Error class. Take existing classes as example. It should have mapping to REST code. 
```
class MessageServerError(Exception): 
    """ Generic Exception with error code and output """

    def __init__(self, rc, message, *args):
        self._rc = rc
        self._desc = message % (args)

    @property
    def rc(self):
        return self._rc

    @property
    def desc(self):
        return self._desc

    def __str__(self):
        if self._rc == 0: return self._desc
        return "error(%d): %s" %(self._rc, self._desc)

class RestError(Exception):  (Should be part of rest_server)
      def __init__(self, e):
                self._e = e

     def http_error(self):
        return self._http_error(e.rc)

    def _http_error(rc): 
        # map rc to HTTP error code. 
```

2. Code should be 
```
try:
...
except MessageServerError as e: 
     ....
     status = RestServerError(e).http_error()
     return web.Response(text=json.dumps(response_obj), status=status)
```

2021-04-06 15:03 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                payload = await request.json()
Why do we assume that payload is being sent in json ? There can be other formats as well. Please see KvPayload

2021-04-06 15:05 UTC, ujjwalpl commented on py-utils/setup.py
> +                     ('/etc/systemd/system', ['src/utils/message_bus/messagebus-rest.service'])],
Lets use message_bus consistently. Avoid "-" unless its a convention.

2021-04-16 03:21 UTC, rahul-tripathi-git commented
run mini-provisioning

2021-04-16 09:45 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +                     ('/etc/systemd/system', ['src/utils/message_bus/messagebus-rest.service'])],
Yes @ujjwalpl, Looks like "-" is a convention for .service files.

2021-04-20 13:52 UTC, rahul-tripathi-git commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                payload = await request.json()
Tested with HTML as a message payload, and it is working fine.

2021-04-21 08:10 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +                     ('/etc/systemd/system', ['src/utils/message_bus/messagebus-rest.service'])],
changed to cortx-restserver.service

2021-04-29 12:29 UTC, selvakumaar5496 requested changes

2021-04-29 12:29 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_rest_server.py
> +        response = requests.put(url=url, data=data, headers=headers)
response = requests.post(url=url, data=data, headers=headers)

2021-05-03 10:24 UTC, rahul-tripathi-git commented on py-utils/src/utils/message_bus/message_bus_server.py
> +    _msg_bus = MessageBus()
Done

2021-05-03 10:25 UTC, rahul-tripathi-git commented on py-utils/test/test_message_bus/test_rest_server.py
> +        response = requests.put(url=url, data=data, headers=headers)
Done

2021-05-04 14:45 UTC, selvakumaar5496 approved these changes

2021-05-12 03:23 UTC, rahul-tripathi-git commented on py-utils/src/utils/message_bus/error.py
> +class MessageServerError(Exception):
Done

2021-05-12 03:23 UTC, rahul-tripathi-git commented on py-utils/src/utils/message_bus/cortx-restserver.service
> +[Unit]
renames to cortx_message_bus.service

2021-05-14 04:50 UTC, ujjwalpl requested changes

2021-05-14 04:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +
MessageBusError needs to be imported.

2021-05-15 14:22 UTC, ujjwalpl requested changes

2021-05-15 14:22 UTC, ujjwalpl commented on py-utils/utils-post-install
> +/bin/cp -f /usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_bus_server.py /opt/seagate/cortx/utils/message_bus/message_bus_server
it should be link and the place should be /opt/seagate/cortx/utils/bin/message_bus_server.

2021-05-17 04:22 UTC, rahul-tripathi-git commented on py-utils/utils-post-install
> +/bin/cp -f /usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_bus_server.py /opt/seagate/cortx/utils/message_bus/message_bus_server
While using pip installation (wheel package) for cortx-py-utils the library installation path may change.. Hence the link created will be broken in this specific case.

Changed the path to /opt/seagate/cortx/utils/bin/message_bus_server. Done.

2021-05-17 14:11 UTC, ujjwalpl requested changes

2021-05-17 14:11 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +            except Exception as e:
When we make any call to Message Bus Interfaces like MessageConsumer, we must catch MessageBusError Exception. 

```
    except MessageBusError as e:
        ...

    except Exception as e: # In case any exception is left. 
        ...
```
Please do this in all the places.

2021-05-17 15:45 UTC, rahul-tripathi-git commented on py-utils/src/utils/message_bus/message_bus_server.py
> +            except Exception as e:
Done.

2021-05-18 07:57 UTC, ujjwalpl approved these changes

2021-05-18 10:36 UTC, sachinpunadikar requested changes
Please correct the copyright year .. it shd be 2021

2021-05-18 13:54 UTC, sachinpunadikar commented on py-utils/setup.py
> +# Copyright (c) 2021Seagate Technology LLC and/or its Affiliates
2021Seagate -> 2021 Seagate

2021-05-18 16:23 UTC, sachinpunadikar approved these changes
+1

2021-05-18 16:58 UTC, merged