EOS-18850: Update py-utils code wrt Elasticsearch and Kibana OpenDistro v7.10
Seagate/cortx-utils pull request #258
Opened 2021-04-12 07:15 UTC by avrnv

# Backend
## Problem Statement
Story Ref (if any): [EOS-18850](https://jts.seagate.com/browse/EOS-18850)
## Unit testing on RPM done
Yes
## Problem Description
Migration from ElasticSearch 6 to open distro ElasticSearch 7.10.
## Solution
Remove mapping types references from ElasticSearch client's internal implemenation.
## Unit Test Cases
- run py-utils/src/utils/data/db/examples/elasticsearch_storage.py

2021-04-12 13:30 UTC, udayan-y21 commented on py-utils/requirements.txt
> +elasticsearch>=7.0.0,<8.0.0
I guess we also need to update.. Global sitepackages https://github.com/Seagate/cortx-re/blob/main/scripts/third-party-rpm/python-requirements.txt and CSM Local reference python packages..

Also `>=7.0.0,<8.0.0` will not match the version from pip3 freeze which will fail package validation for mini provisioning.

@kupranay @pawankumarsrivastava Your review on this.

2021-04-14 07:56 UTC, udayan-y21 requested changes
Please address the comment provided below. https://github.com/Seagate/cortx-utils/pull/258#discussion_r611630151

2021-04-14 08:58 UTC, avrnv commented on py-utils/requirements.txt
> +elasticsearch>=7.0.0,<8.0.0
Updated to the exact version from `pip freeze` output.

2022-08-08 15:06 UTC, hessio commented
@avrnv is this PR still necessary, if not can we close it?

2022-08-08 20:43 UTC, avrnv commented
> @avrnv is this PR still necessary, if not can we close it?

The PR is no longer necessary, closing.

2022-08-08 20:43 UTC, closed without merging