EOS-18850 : ElasticSearch host to incorporate the multi-node cluster
Seagate/cortx-utils pull request #260
Opened 2021-04-15 04:12 UTC by Pranali04796

### Backend

### Problem statement:
Story Ref (if any): [ EOS-18850](https://jts.seagate.com/browse/EOS-18850)

### Problem Description
ElasticSearch host to incorporate the multi-node cluster

2021-04-15 04:13 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-04-20 05:40 UTC, pawankumarsrivastava requested changes

2021-04-20 05:40 UTC, pawankumarsrivastava commented on py-utils/src/utils/schema/database.py
> +                "hosts": ["localhost"],
localhost -> 127.0.0.1

2021-04-20 05:40 UTC, pawankumarsrivastava commented on py-utils/src/utils/schema/database.py
> +                "hosts": ["localhost"],
localhost -> 127.0.0.1

2021-04-20 06:19 UTC, Pranali04796 commented on py-utils/src/utils/schema/database.py
> +                "hosts": ["localhost"],
Updated required changes in database.py

2021-04-20 07:08 UTC, Pranali04796 commented on py-utils/src/utils/schema/database.py
> +                "hosts": ["localhost"],
Updated required changes in database.py by replacing  localhost -> 127.0.0.1  as suggested by @pawankumarsrivastava

2021-05-07 06:14 UTC, udayan-y21 commented on py-utils/src/utils/schema/database.py
> +                "hosts": ["127.0.0.1"],
For 3-node deployment, do we have only single entry? How this will update at the time of 3-node deployment?
ex: `"hosts": ["127.0.0.1","127.0.0.1","127.0.0.1"],`

2021-05-28 11:35 UTC, pawankumarsrivastava approved these changes

2021-05-31 11:14 UTC, udayan-y21 approved these changes

2021-06-10 08:14 UTC, kupranay approved these changes

2021-06-10 09:21 UTC, sachinpunadikar requested changes
file py-utils/requirements.txt got renamed.
Please rebase your code to reflect this

2021-06-11 03:40 UTC, sachinpunadikar approved these changes
+1

2021-06-15 13:40 UTC, sachinpunadikar commented
Custom deployment was successful
https://seagate-systems.atlassian.net/wiki/spaces/~340452269/pages/361563003/Opendistro+for+Elasticsearch+and+Kibana
Going ahead with merge

2021-06-15 13:40 UTC, merged