WIP: Adding validations for kafka and zookeeper
Seagate/cortx-utils pull request #261
Opened 2021-04-16 15:15 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

2021-04-16 15:18 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-04-17 03:17 UTC, ujjwalpl requested changes

2021-04-17 03:17 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +    def validate_kafka_zookeeper_servers(cmds):
This is incorrect. Please use validator framework. Refer to utils.validator.xxx code. There should not be any code in this file just a call to validate.xxx.yyy() one line

2021-04-17 03:17 UTC, ujjwalpl commented on py-utils/src/utils/process.py
> +        cmd = self._cmd
You are modifying a fundamental class. There are many parts of the code which make use of this. 
You will have to ensure that nothing is broken due to this change. Better to avoid changes to this class.

2021-04-17 03:17 UTC, ujjwalpl commented on py-utils/src/utils/process.py
> +            list_cmds = [x.split() for x in cmd.split(' | ')]
Why " | " ? This is not a standard for any process output. It should be done at the caller end. Different command may have different output. You cant generalize it as it is not a convention.

2021-04-17 09:43 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +    def validate_kafka_zookeeper_servers(cmds):
We are using pipe commands for checking server status, then we need to add in our utils.validator.v_service.py module. then we call v_service module method here. Is this allowed?

2021-04-19 04:07 UTC, vastradparayya commented on py-utils/src/utils/process.py
> +        cmd = self._cmd
Ok @ujjwalpl. I will check and remove if needed

2021-04-19 06:28 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +import subprocess
This import will not be required here

2021-04-19 08:17 UTC, vastradparayya commented on py-utils/src/setup/test_subprocess_warning.py
> +                     stderr=subprocess.PIPE, shell=False, cwd=None,
Same subprocess.run is being used in existing SimpleProcess class of process module

2021-04-19 08:20 UTC, vastradparayya commented on py-utils/src/setup/test_subprocess_warning.py
> +                     stderr=subprocess.PIPE, shell=False, cwd=None,
Same subprocess.run is being used in existing SimpleProcess class of process module

2021-04-19 11:17 UTC, vastradparayya commented on py-utils/src/utils/process.py
> +        cmd = self._cmd
Hi @ujjwalpl , PipedClass of process module is unimplemented and not being used in any part of code

2021-04-21 04:18 UTC, closed without merging