EOS19189-LDAP Provisioner: Create configure_ldap API in cortx-utils
Seagate/cortx-utils pull request #262
Opened 2021-04-19 06:02 UTC by shalakadharap

2021-04-20 12:38 UTC, SaumitraK531 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +    print('Error while deleting ' + module1File)
Remove one more module file '/etc/openldap/slapd.d/cn=config/cn=module{2}.ldif' which is used in ldap replication for ldap idempotency.

2021-05-04 06:59 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +    print('Error while deleting ' + module1File)
Done

2021-06-28 04:38 UTC, bkirunge7 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        userSchemaFile = '/etc/openldap/slapd.d/cn=config/cn=schema/cn={1}s3user.ldif'
can you move all cleanup in different function

2021-06-28 04:38 UTC, bkirunge7 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        userSchemaFile = '/etc/openldap/slapd.d/cn=config/cn=schema/cn={1}s3user.ldif'
Also please move code to different functions as much as possible

2021-06-28 04:38 UTC, bkirunge7 commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +            value="rid=00"+str(ridnum)+" provider=ldap://"+host+":389/ bindmethod=simple binddn=\"cn=admin,dc=seagate,dc=com\" credentials="+pwd+" searchbase=\"dc=seagate,dc=com\" scope=sub schemache
can you read this from ldif file

2021-06-28 04:38 UTC, bkirunge7 commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +            print('Current host entry is not present in input host file')
print all variables here host name, id

2021-06-28 05:00 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +            value="rid=00"+str(ridnum)+" provider=ldap://"+host+":389/ bindmethod=simple binddn=\"cn=admin,dc=seagate,dc=com\" credentials="+pwd+" searchbase=\"dc=seagate,dc=com\" scope=sub schemache
We cannot

2021-06-28 05:05 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +            print('Current host entry is not present in input host file')
Printed hostname. id is counter so not printing it.

2021-06-28 05:20 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        userSchemaFile = '/etc/openldap/slapd.d/cn=config/cn=schema/cn={1}s3user.ldif'
done

2021-06-28 07:01 UTC, bkirunge7 approved these changes

2021-06-28 11:23 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
correct the year  2020 -> 2021

2021-06-28 11:24 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +import ldap
Is this a new package required ?

2021-06-28 11:27 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        userSchemaFile = '/etc/openldap/slapd.d/cn=config/cn=schema/cn={1}s3user.ldif'
As a coding guidelines for utils, we do not make use of camelCase. Please see the guidelines at https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/349175953/Cortx+Foundation+Python+Coding+Guidelines#Naming-convention

2021-06-28 11:30 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        module2File = '/etc/openldap/slapd.d/cn=config/cn=module{2}.ldif'
Optimize the code having a loop over filenames (module0, module1 & module2 file).

2021-06-28 11:33 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        INSTALLDIR="/opt/seagate/cortx/s3/install/ldap"
It is expected to get the install directory path from file /etc/cortx.conf file. Do not hardcode the install path.
@rahul-tripathi-git please provide a example

2021-06-28 11:34 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +                ROOTDNPASSWORD = input("Enter password for LDAP RootDN ")
Can't we mandate to provide the password ?

2021-06-28 11:36 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +                ROOTDNPASSWORD = 'seagate'
This is problematic. This is disclosing the default password to the entire word. And utils code should not assume any default password, one should pass in the default password.
CC - @ujjwalpl

2021-06-28 11:38 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        l = ldap.initialize("ldapi:///")
can we have more meaningful name rather than 'l' ?

2021-06-28 11:47 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +import sys
Generic observation on coding guidelines. camelCase is not supposed to be used. Refer to https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/349175953/Cortx+Foundation+Python+Coding+Guidelines#Naming-convention

2021-06-28 11:49 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +import sys
Copyright missing

2021-06-28 11:50 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +#!/usr/bin/env python3
Do not use print , instead log those error messages

2021-06-28 11:50 UTC, sachinpunadikar requested changes
Please work on the comments

2021-06-28 15:33 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +            print('Error while deleting '+ userSchemaFile)
Raise exception instead of printing

2021-06-28 15:37 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        module2File = '/etc/openldap/slapd.d/cn=config/cn=module{2}.ldif'
for module_file in enumerate(module_files):
   try:
       os.remove(module_file)
   except OSError as e:
       raise Exception

2021-06-28 15:43 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        copyfile(INSTALLDIR+'/olcDatabase={2}mdb.ldif' , '/etc/openldap/slapd.d/cn=config/olcDatabase={2}mdb.ldif')
Make sure this line does not cross 80 char. If so truncate to next line

2021-06-28 16:04 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        os.system('systemctl restart slapd')
use SimpleProcess instead of os.system(). 
os.system does not return exception

2021-06-28 16:05 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        l.simple_bind_s("cn=admin,dc=seagate,dc=com",ROOTDNPASSWORD)
provide space after every comma

2021-06-28 16:06 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        l.simple_bind_s("cn=admin,dc=seagate,dc=com",ROOTDNPASSWORD)
Please follow this everywhere

2021-06-28 16:07 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        mod_attrs = [( ldap.MOD_REPLACE, 'olcSuffix', [b'dc=seagate,dc=com'] )]
remove unwanted spaces

`mod_attrs = [(ldap.MOD_REPLACE, 'olcSuffix', [b'dc=seagate,dc=com'])]`

2021-06-28 16:09 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +
the code can be very much simplified. Use a for loop to perform l.modify_s.

Take mod_attrs in a single list and iterate through it

2021-06-28 16:11 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +
2 line spaces before class Implementation

2021-06-28 16:12 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +        Lines=file.readlines()
Lines=file.readlines()
Provide spaces

2021-06-28 16:14 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +                print(host + ' is valid and reachable.')
avoid printing.

If exitcode !=0:
    quit()
log('host is valid')

2021-06-28 16:14 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +        mod_attrs = [( ldap.MOD_ADD, attrToAdd, bytes(str(value), 'utf-8')  )]
Remove unwanted spaces

2021-06-28 16:16 UTC, selvakumaar5496 requested changes
Raise an exception in except block in all places. Avoid printing

2021-06-29 05:37 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +#!/usr/bin/env python3
Done

2021-06-29 05:38 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Done

2021-06-29 05:39 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +import ldap
its not required. I just thought of keeping in a separate package

2021-06-29 07:20 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +            print('Error while deleting '+ userSchemaFile)
done

2021-06-29 08:35 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        module2File = '/etc/openldap/slapd.d/cn=config/cn=module{2}.ldif'
Done

2021-06-29 08:52 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        l = ldap.initialize("ldapi:///")
fixed

2021-06-29 08:54 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        l.simple_bind_s("cn=admin,dc=seagate,dc=com",ROOTDNPASSWORD)
space is failing ldap connection

2021-06-29 09:03 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +import sys
Fixed

2021-06-29 09:05 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +                print(host + ' is valid and reachable.')
done

2021-06-29 09:05 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +
DOne

2021-06-29 09:09 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +                ROOTDNPASSWORD = input("Enter password for LDAP RootDN ")
This design was already in place in S3Server. I just incorporated it to cortx-utils

2021-06-29 10:20 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        copyfile(INSTALLDIR+'/olcDatabase={2}mdb.ldif' , '/etc/openldap/slapd.d/cn=config/olcDatabase={2}mdb.ldif')
splitted into 2 parts

2021-06-29 10:23 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        mod_attrs = [( ldap.MOD_REPLACE, 'olcSuffix', [b'dc=seagate,dc=com'] )]
Its for parameter separation view. We follow it for better code visibility

2021-06-29 10:25 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +
If we create list of olcAccess values then the code will look messy there.
For better visibility, implemented this way.
This way code looks neatt and clean

2021-06-29 10:26 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +        Lines=file.readlines()
done

2021-06-29 12:23 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        os.system('systemctl restart slapd')
Not very sure on this

2021-06-29 12:24 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +                ROOTDNPASSWORD = 'seagate'
Can we take this pwd thing for next sprint considering this current design in place

2021-06-30 10:46 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        l.simple_bind_s("cn=admin,dc=seagate,dc=com",ROOTDNPASSWORD)
Not inside the string, after the string
 l.simple_bind_s("cn=admin,dc=seagate,dc=com", ROOTDNPASSWORD)

2021-06-30 10:47 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        mod_attrs = [( ldap.MOD_REPLACE, 'olcSuffix', [b'dc=seagate,dc=com'] )]
Not the inbetween ones. Trialing and ending spaces

2021-06-30 10:49 UTC, selvakumaar5496 commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +        mod_attrs = [( ldap.MOD_ADD, attrToAdd, bytes(str(value), 'utf-8')  )]
Having trial and ending spaces are not good practice. Having space after every comma is accepted
 mod_attrs = [(ldap.MOD_ADD, attrToAdd, bytes(str(value), 'utf-8'))]

2021-06-30 11:34 UTC, rahul-tripathi-git commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +        INSTALLDIR="/opt/seagate/cortx/s3/install/ldap"
`        config_file_path = "/etc/cortx/cortx.conf"
        Conf.load('config_file', f'yaml:///{config_file_path}')
        install_path = Conf.get(index='config_file', key='install_path')`
        
@shalakadharap, you may use the above code to get the install path. The idea is to not to hardcode the install path and keep it configurable. 

To read the install path from /etc/cortx/cortx.conf file, confstore utility can be used as mentioned in the above example

2021-07-02 06:26 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +                ROOTDNPASSWORD = 'seagate'
Fixed. Made pwd mandatory argument

2021-07-02 06:26 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +                ROOTDNPASSWORD = input("Enter password for LDAP RootDN ")
Fixed

2021-07-05 04:33 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/setupReplication.py
> +        mod_attrs = [( ldap.MOD_ADD, attrToAdd, bytes(str(value), 'utf-8')  )]
done

2021-07-06 14:19 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +import ldap
I was talking "ldap" .. is that a new python package ? If so you need to get permission from Ujjwal & John to use it.

2021-07-06 14:24 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +                BaseConfig.safe_remove(f)
Suggestion -
Instead of removing all files 1 by 1, can't we delete the directory & recreate it again ?

2021-07-06 14:31 UTC, sachinpunadikar commented on py-utils/utils-post-install
> +cp -f ./../src/utils/third_party/openldap/olcDatabase\=\{2\}mdb.ldif $utils_path/conf
This is incorrect, never going to work as on the system where installation is happening there is no src directory

2021-07-06 14:32 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +            print('Please provide the password for ldap configuration')
This should be logged rather than printing

2021-07-06 14:33 UTC, sachinpunadikar requested changes
Work on comments

2021-07-07 07:28 UTC, selvakumaar5496 reviewed
Consistency required across the PR:
1. provide a space after every comma in function call.
For ex: Log.init('baseConfigLog','/var/log/seagate/s3',level='DEBUG') --> Log.init('baseConfigLog', '/var/log/seagate/s3', level='DEBUG')
2. Separate names using underscore if it is a two-worded word. 
For ex:  policyfile --> policy_file,  filelist --> file_list, forceclean --> force_clean
3. Provide spaces before and after variable initialization.
For ex: forceclean=False  --> forceclean = False,
           ROOTDNPASSWORD=None --> ROOTDNPASSWORD = None

2021-07-07 11:40 UTC, shalakadharap commented on py-utils/utils-post-install
> +cp -f ./../src/utils/third_party/openldap/olcDatabase\=\{2\}mdb.ldif $utils_path/conf
Can you suggest, where can I keep olcDatabase\=\{2\}mdb.ldif file in utils repo?

2021-07-07 12:33 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +            print('Please provide the password for ldap configuration')
done

2021-07-07 12:35 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +                BaseConfig.safe_remove(f)
To avoid deletion and recreation we are removing files 1 by 1.
Efficiency wise I find this is good option as it will not put overhead of dir re-creation

2021-07-19 10:48 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +import ldap
Already got the permission. Forwarded that mail to you.

2021-07-19 10:50 UTC, shalakadharap commented on py-utils/utils-post-install
> +cp -f ./../src/utils/third_party/openldap/olcDatabase\=\{2\}mdb.ldif $utils_path/conf
Removed this code and handled it separately

2021-07-19 11:16 UTC, shalakadharap commented on py-utils/utils-post-install
> +cp -f ./../src/utils/third_party/openldap/olcDatabase\=\{2\}mdb.ldif $utils_path/conf
https://github.com/Seagate/cortx-utils/pull/383/files

2021-07-19 11:17 UTC, shalakadharap commented
Worked on Comments by Sachin and Selva both
Please review final set of changes under below PR-
https://github.com/Seagate/cortx-utils/pull/383

2021-07-29 09:45 UTC, vimalraghwani20 commented
closing this PR as it is already taken care

2021-07-29 09:45 UTC, closed without merging