Adding cffi to requirements.txt
Seagate/cortx-utils pull request #269
Opened 2021-04-28 03:18 UTC by rahul-tripathi-git

This is done to avoid UserWarning: implicit cast from 'char *'
to a different pointer type: will be forbidden in the future
(check that the types are as you expect; use an explicit ffi.cast()
if they are correct)

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

2021-05-04 09:56 UTC, rahul-tripathi-git commented
I was able to reproduce the error with cffi==1.9.1

It was resolved when upgraded to cffi==1.14.5

2021-05-04 17:03 UTC, sachinpunadikar commented on py-utils/requirements.txt
> +
Remove this new line

2021-05-04 17:19 UTC, rahul-tripathi-git commented on py-utils/requirements.txt
> +
Done

2021-05-04 17:24 UTC, sachinpunadikar approved these changes
+1

2021-05-07 09:54 UTC, sachinpunadikar approved these changes
+1

2021-05-07 09:59 UTC, selvakumaar5496 requested changes

2021-05-07 10:44 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        open('/opt/seagate/cortx/utils/conf/requirements.ext.txt') as extfile :
Done

2021-05-07 10:44 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +                raise SetupError(errno.EINVAL, "Required python package %s is missing" % package)
package needs to be in error message string.

2021-05-07 10:59 UTC, selvakumaar5496 approved these changes

2021-05-07 13:15 UTC, ujjwalpl requested changes

2021-05-07 13:15 UTC, ujjwalpl commented on py-utils/setup.py
> +         open('requirements.ext.txt') as extreq:
What is one of the file does not exist both will fail. Did you test this code with removing requiremrents.ext.txt ?

2021-05-07 13:15 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        with open('/opt/seagate/cortx/utils/conf/requirements.txt') as file, \
Same here

2021-05-10 04:22 UTC, ujjwalpl requested changes

2021-05-10 04:22 UTC, ujjwalpl commented on jenkins/build.sh
> +if [ -f "requirements.ext.txt" ]; then
There was a discussion on python_requirements.txt so separate from rpm one. How will you define rpm pre-reqs ?

2021-05-10 04:22 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        with open('/opt/seagate/cortx/utils/conf/requirements.txt') as file:
Need to avoid hard coding of the path. It should be relative path.

2021-05-10 05:35 UTC, rahul-tripathi-git commented on jenkins/build.sh
> +if [ -f "requirements.ext.txt" ]; then
we first check the packages mentioned in requirements./ext.txt and block the installation of cortx-utils rpm if the packages are not present, with proper error msgs.

2021-05-10 07:40 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        with open('/opt/seagate/cortx/utils/conf/requirements.txt') as file:
Hi @ujjwalpl
Mentioned file is present in /opt/seagate/cortx/utils path and the parent(utils.py) file will be inside .../site-packages/cortx/utils... (library) path. Relative path wont be a good option in such case. Please correct me if I am wrong.

2021-05-10 08:02 UTC, selvakumaar5496 commented on py-utils/setup.py
> +    except FileNotFoundError:
should'nt we raise SetupError on top of this ?

2021-05-10 08:29 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +    except FileNotFoundError:
The reason to use try except is to avoid any exception and the execution flow should not break.
As this file might get removed at any point of time in future.

2021-05-10 09:38 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +        with open('/opt/seagate/cortx/utils/conf/requirements.txt') as file:
@ujjwalpl above location is where the file gets installed when we install cortx-py-utils rpm.

2021-05-10 10:28 UTC, ujjwalpl requested changes

2021-05-10 10:28 UTC, ujjwalpl commented on jenkins/build.sh
> +if [ -f "requirements.ext.txt" ]; then
What if we depend on say a rpm xxx-123.rpm. Where do you specify that dependency ?

2021-05-10 10:30 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        with open('/opt/seagate/cortx/utils/conf/requirements.txt') as file:
What if I want to install cortx-utils to a different install path e.g. "/opt/cortx/utils/...". We need to avoid tight coupling to paths and use relative path as far as possible. This is one place I think we can use relative path for sure

2021-05-10 10:41 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +         open('requirements.ext.txt') as extreq:
Done

2021-05-10 10:41 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        with open('/opt/seagate/cortx/utils/conf/requirements.txt') as file, \
Done.

2021-05-10 10:47 UTC, sachinpunadikar commented on jenkins/build.sh
> +if [ -f "requirements.ext.txt" ]; then
@ujjwalpl mentioning RPM dependency is easy, and that can be provided while creating rpm itself. Mentioning python-package dependency was not that straightforward, hence we adopted this way of checking python dependency.

2021-05-10 11:34 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        with open('/opt/seagate/cortx/utils/conf/requirements.txt') as file:
Defined a utils install_directory as /opt/seagate/cortx/utils

2021-05-11 10:53 UTC, ujjwalpl requested changes

2021-05-11 10:53 UTC, ujjwalpl commented on py-utils/setup.py
> +    except FileNotFoundError:
Yes! Its about handling the exception generated from os / python.

2021-05-11 10:53 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +    utils_install_dir = "/opt/seagate/cortx/utils/"
Need to avoid hard coding of the paths anywhere except for build file setup.py.

2021-06-01 04:21 UTC, sachinpunadikar commented on py-utils/setup.py
> +from fnmatch import fnmatch
Please ensure this is not a additional python module.

2021-06-01 04:25 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +            with open(f"{utils_path}/conf/python_requirements.ext.txt") as extfile :
Why we are not checking if the file exists. If exists go for reading it.

2021-06-01 04:25 UTC, sachinpunadikar commented on py-utils/setup.py
> +        with open('python_requirements.ext.txt') as extreq:
Why we are not checking if the file exists. If exists go for reading it.

2021-06-01 04:26 UTC, sachinpunadikar commented on py-utils/setup.py
> +                     ('/etc/systemd/system', ['src/utils/message_bus/'
fix the codacy issue

2021-06-01 04:26 UTC, sachinpunadikar requested changes
Please work on comments

2021-06-01 04:42 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +from fnmatch import fnmatch
Yes it is part of standard library.

2021-06-01 04:43 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +        with open('python_requirements.ext.txt') as extreq:
We have a try catch mechanism for that.

2021-06-01 04:47 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +            with open(f"{utils_path}/conf/python_requirements.ext.txt") as extfile :
try except block is there for the same.

2021-06-01 06:25 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +            with open(f"{utils_path}/conf/python_requirements.ext.txt") as extfile :
How a read error will be handled (when file exists, but unable to read) ?

2021-06-01 09:31 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +                     ('/etc/systemd/system', ['src/utils/message_bus/'
Done

2021-06-01 18:39 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +            with open(f"{utils_path}/conf/python_requirements.ext.txt") as extfile :
As discussed, now catching all the exceptions/errors

2021-06-02 04:08 UTC, ujjwalpl approved these changes

2021-06-10 05:02 UTC, sachinpunadikar approved these changes
+1

2021-06-10 06:05 UTC, sachinpunadikar commented
Going ahead with merging this PR as custom deployment is passed.

2021-06-10 06:05 UTC, merged