Reset offset when purge is called
Seagate/cortx-utils pull request #270
Opened 2021-04-28 06:52 UTC by selvakumaar5496

Offsets are not refreshed if purge is called. Hence the get_unread_count() interface was returning a wrong count if purge(delete) is called. 
This PR contains the code which resets the offset if purge is being called.

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

2021-04-28 10:02 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                if 'Error' in decoded_string:
I think "Error" will be string when res_rc != 0

2021-04-28 10:05 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        if self.get_log_size(message_type) == 0:
Add comment on why we are doing this

2021-04-28 10:07 UTC, sachinpunadikar requested changes
Check the comments.
Not seeing any test cases / or change in test case. Please ensure to have test cases for both classes producer, consumer.

2021-04-29 11:31 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        if self.get_log_size(message_type) == 0:
Added

2021-04-29 11:33 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                if 'Error' in decoded_string:
I get errors when rc is 0 as well. Hence checking the output(decoding bytes to string)

2021-05-03 05:48 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        # Update the offsets if purge is called
The comment should be .. "if purge was called"

2021-05-03 06:23 UTC, sachinpunadikar commented on py-utils/test/test_message_bus/test_unread_count.py
> +    def test_delete_count(self):
rename  test_delete_messages

2021-05-03 06:23 UTC, sachinpunadikar commented on py-utils/test/test_message_bus/test_unread_count.py
> +    def test_send_count(self):
rename test_producer_read_count

2021-05-03 06:24 UTC, sachinpunadikar commented on py-utils/test/test_message_bus/test_unread_count.py
> +    def test_receive_count(self):
rename test_consumer_read_count

2021-05-03 06:24 UTC, sachinpunadikar commented on py-utils/test/test_message_bus/test_unread_count.py
>          """ Test Unread Message Count """
Test Unread Message Count From Consumer side

2021-05-03 06:25 UTC, sachinpunadikar commented on py-utils/test/test_message_bus/test_unread_count.py
>          """ Test Send Message """
Test Unread Message Count From Producer side

2021-05-03 06:26 UTC, sachinpunadikar requested changes
Please work on the comments, minor changes needed.

2021-05-03 07:14 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        # Update the offsets if purge is called
Done

2021-05-03 07:15 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_unread_count.py
> +    def test_delete_count(self):
renamed

2021-05-03 07:15 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_unread_count.py
> +    def test_send_count(self):
renamed

2021-05-03 07:15 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_unread_count.py
> +    def test_receive_count(self):
renamed

2021-05-03 07:18 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_unread_count.py
>          """ Test Unread Message Count """
Done

2021-05-03 07:18 UTC, selvakumaar5496 commented on py-utils/test/test_message_bus/test_unread_count.py
>          """ Test Send Message """
Done

2021-05-03 08:02 UTC, sachinpunadikar approved these changes
+1

2021-05-03 08:06 UTC, merged