KvStore: Added Directory as store with DirKvStore class and dir as protocol
Seagate/cortx-utils pull request #272
Opened 2021-04-30 02:44 UTC by suryakumar1024

Added Support for Directory as Store.

Example URL:
store_url = dir:///tmp/cloud_configurations

kv_store = KvStoreFactory.get_instance(store_url)

#GET
kv_store.get(["cluster_uuid"])  #return none since no key file present in new directory created
#######OUTPUT#############
[]

#SET
kv_store.set(["cluster_uuid"], ["F40987Fu"])

#GET
kv_store.get(["cluster_uuid"]) 

#######OUTPUT#############
["F40987Fu"]

#DELETE
kv_store.delete(["cluster_uuid"]) 

#GET
kv_store.get(["cluster_uuid"]) 

#######OUTPUT#############
[]

2021-06-02 10:34 UTC, selvakumaar5496 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                pass
shouldn't we raise an exception ?

2021-06-02 11:38 UTC, ujjwalpl requested changes

2021-06-02 11:38 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store.py
> +        for key in payload.get_keys():
for loop can be converted to map
`map(lambda x: p_payload.set(x, payload.get[x]), payload.get_keys())`

2021-06-02 11:38 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        for key in keys:
`vals = [payload[key] for key in keys]`

2021-06-02 11:38 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +            for file_name in file_names:
`keys = [f'{key_prefix}{path}{f}' for f in file_names]`

2021-06-02 11:38 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                pass
We should check and raise if error is not ENOENT
```
except OSError as e:
    if e.errno != errno.ENOENT: 
        raise KvError(e.errno, "Can not delete entry %s" %(key_file))
```

2021-06-02 19:58 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                pass
Updated in current patch

2021-06-02 19:58 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store.py
> +        for key in payload.get_keys():
Updated in current patch

2021-06-02 19:58 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        for key in keys:
Updated in current patch

2021-06-02 19:58 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +            for file_name in file_names:
Updated in current patch

2021-06-04 11:41 UTC, ujjwalpl approved these changes

2021-06-04 14:04 UTC, sachinpunadikar approved these changes
+1

2021-06-07 07:21 UTC, merged