Support for Reset & Cleanup phase in utils_Setup
Seagate/cortx-utils pull request #274
Opened 2021-05-04 07:31 UTC by vastradparayya

In utils_setup reset phase - Delete any existing message types (Kafka Topics)

In utils_setup cleanup phase - Remove /etc/cortx/message_bus.conf file

2021-05-04 07:34 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-05-04 07:59 UTC, selvakumaar5496 requested changes
Please work on the comments

2021-05-04 07:59 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        print("Reset completed successfully!")
Remove print. We never print anything and anyways returning 0 on success

2021-05-04 07:59 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        print("Cleanup completed successfully!")
Remove print. We never print anything and anyways returning 0 on success

2021-05-04 07:59 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +            print("Reset/Cleanup already done or config file not found!")
Do not print error and exit. Please raise exception

2021-05-04 16:42 UTC, rahul-tripathi-git commented
run mini-provisioner

2021-05-04 17:03 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-05-04 17:17 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +        """ Reset all the data that was created after post install """
Reset -> Remove / Delete

2021-05-04 17:20 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +        server = Conf.get("index", 'message_broker>cluster[0]>server')
Get the entire list of servers, not just one.
Use that list later in the code. It may happen that the only server you are using in this piece of code is down and reset will fail.

2021-05-04 17:21 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +        topic_list_cmd = f"/opt/kafka/bin/kafka-topics.sh --list --bootstrap-server {server}:9092"
Use all available servers here.

2021-05-04 17:21 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +            cmd = f"/opt/kafka/bin/kafka-topics.sh --delete --topic {topics} --bootstrap-server {server}:9092"
Use all available servers

2021-05-04 17:22 UTC, sachinpunadikar requested changes
work on the comments

2021-05-05 10:46 UTC, selvakumaar5496 requested changes

2021-05-05 10:46 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +                                 "Unable to list topics created. Make sure that message servers are running!")
Also append the error message. So that we know what exact error it is.
 "Unable to list topics created. Make sure that message servers are running. %s", res_err)

2021-05-05 10:57 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +                                 "Unable to list topics created. Make sure that message servers are running!")
No one shd use kafka specific terminology  .. stick to messagebus terminology  .. use message-type instead of topic   message servers -> MessageBus servers

2021-05-05 10:57 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +                    raise SetupError(errno.EIO, "Error while deleting topic!")
topic -> message-type

2021-05-05 11:32 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +                                 "Unable to list topics created. Make sure that message servers are running!")
@selvakumaar5496 If we append res_err to user-defined error, that will look very big(Like unreadable). Is this Okay to append res_err? @sachinpunadikar

2021-05-06 15:20 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +    UNKNOWNTPOIC = 3
Do you mean UNKNOWNTOPIC ? Rather it should be UNKNOWNMESSAGETYPE.
And I am not seeing this value is used anywhere in the code added by you.

2021-05-06 15:22 UTC, sachinpunadikar requested changes
work on the comment

2021-05-06 16:22 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +            cmd = f"/opt/kafka/bin/kafka-topics.sh --delete --topic {topics} --bootstrap-server {servers}"
@selvakumaar5496  will this delete all topics ? Or need to call separately for every message_type ?

2021-05-06 17:24 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +    UNKNOWNTPOIC = 3
This is added by mistake. I removed this Sachin

2021-05-06 17:26 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            cmd = f"/opt/kafka/bin/kafka-topics.sh --delete --topic {topics} --bootstrap-server {servers}"
Yes Sachin. This will delete all topics. Here topics will contain all message_types from all listed servers as a comma separated string.

2021-05-07 03:20 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +            cmd = f"/opt/kafka/bin/kafka-topics.sh --delete --topic {topics} --bootstrap-server {servers}"
@sachinpunadikar we can delete all mentioned message_types in one go

2021-05-07 05:27 UTC, sachinpunadikar approved these changes
+1

2021-05-07 05:36 UTC, selvakumaar5496 requested changes

2021-05-07 05:36 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        servers = Conf.get("index", 'message_broker>cluster')
Please use consistent quotes

2021-05-07 05:36 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        topics = ",".join([x for x in res_op.decode("utf-8").split('\n') if x])
Please use consistent quotes

2021-05-07 06:44 UTC, selvakumaar5496 approved these changes

2021-05-07 07:01 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +        cmd = "rm -rf /etc/cortx/message_bus.conf"
Please check if the config exists, and then go for deleting it. If config file do not exists, return success.

2021-05-07 07:01 UTC, sachinpunadikar requested changes
improvement in cleanup logic needed.

2021-05-07 09:48 UTC, sachinpunadikar approved these changes
+1

2021-05-07 09:49 UTC, merged

2021-05-07 09:55 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        topic_list_cmd = f"/opt/kafka/bin/kafka-topics.sh --list --bootstrap-server {servers}"
This should be called from within kafka mini provisioner.