EOS-19737 : Support for Reset & Cleanup phase in utils_Setup
Seagate/cortx-utils pull request #277
Opened 2021-05-10 06:49 UTC by vastradparayya

This provides reset/cleanup interface

Jira ticket reference - [EOS-19737](https://jts.seagate.com/browse/EOS-19737)

2021-05-10 06:52 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-05-10 07:04 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        if not os.path.exists(conf_file):
@sachinpunadikar , Does reset requires this check? Anyways messageBus throws an error if conf file does not exist.

2021-05-10 07:26 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +        if not os.path.exists(conf_file):
@selvakumaar5496 , the MessageBus error will not provide the message (reset/cleanup already done), which we want to convey  .. rt ?

2021-05-12 14:17 UTC, ujjwalpl requested changes

2021-05-12 14:17 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            raise SetupError(errno.EIO, "Error while deleting config file %s", res_err)
Please add the file as parameter that you are trying to delete.

2021-05-12 14:17 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        cmd_proc = SimpleProcess(cmd)
Why dont we simple os.remove() ?

2021-05-12 19:34 UTC, closed without merging