Implementation of Iem set and print method
Seagate/cortx-utils pull request #278
Opened 2021-05-10 08:50 UTC by selvakumaar5496

IEM Alerts can be created either by initializing it or by set method.
It can be sent or received through message_bus

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

2021-05-12 09:54 UTC, sachinpunadikar commented on py-utils/src/utils/iem_framework/event_message.py
> +    def __init__(self, component_id: str, source_id: str):
Provide explicit init method like send

2021-05-12 09:56 UTC, ujjwalpl requested changes

2021-05-12 09:56 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +class EventMessage:
This needs to be singleton class.

2021-05-12 09:56 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +    def validate(obj: object, min_id: int, attributes: list, max_ids: list):
There is no interface called validate. This should be internal function i.e. _validate

2021-05-12 10:00 UTC, sachinpunadikar commented on py-utils/src/utils/iem_framework/error.py
> +class IemError(Exception):
Instead of IemError , lets call it as EventMsgError or EventError

2021-05-12 10:01 UTC, sachinpunadikar requested changes
Work on the comments

2021-05-12 10:05 UTC, ujjwalpl requested changes

2021-05-12 10:05 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +    _HEX_BASE = 16
Input should be normal int and not assumed to be hex. Ignore all hax treatment for now. Treat as integer.

2021-05-12 10:43 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    def __init__(self, component_id: str, source_id: str):
Taken care

2021-05-12 10:43 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +class EventMessage:
Done

2021-05-12 10:46 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    def validate(obj: object, min_id: int, attributes: list, max_ids: list):
handled as internal function

2021-05-12 10:47 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/error.py
> +class IemError(Exception):
changed to EventMessageError

2021-05-12 16:53 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +        #TODO : producer.send(alert)
Implemented.

2021-05-13 19:18 UTC, rahul-tripathi-git reviewed
Flow of execution:

1. EventMessage.init(component_id, source_id) 
2. EventMessage.send(module_id, event_id, severity, message, host, rc) 

We need to save the reference either in global or class scope

2021-05-14 11:21 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    def validate(obj: object, min_id: int, attributes: list, max_ids: list):
Removed this method since we dont go for hex validation now

2021-05-14 11:21 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    _HEX_BASE = 16
changed to str and int

2021-05-14 11:22 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    def send(self, module_id: str, event_id: str, severity: str, message: str, \
Send uses class attributes hence need refrence
Made as @classmethod, hence no ned to create instance separately before send

2021-05-14 11:23 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    def init(self, component_id: str, source_id: str):
Implemented as singleton, hence same instance will be used.

2021-05-14 13:49 UTC, ujjwalpl requested changes

2021-05-14 13:49 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +    _conf_file = 'json:///etc/cortx.conf'
We need to follow same conventions. For message bus we have /etc/cortx/message_bus.conf. We should stick to that. Conf File should be /etc/cortx/cluster.conf or something like that.  

Also please make sure this file is created during mini provisioner phase.

2021-05-14 13:49 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +        'H': 'Hardware',
Try to be consistent 
'A': 'alert', <<< alert starts with small letter 
'H': 'Hardware', <<<<< Hardware starts with capital letter

2021-05-14 13:49 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +        if alert is not None:
Where is the test code ? No code without test code should be checked in.

2021-05-14 13:49 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +            Conf.load('iem', cls._conf_file)
You are trying to load cluster conf. Lets try to avoid too many config files. 

Conf.load('cluster', cls._conf_file)

2021-05-14 13:57 UTC, ujjwalpl requested changes

2021-05-14 13:57 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +            raise EventMessageError(errno.EINVAL, 'Invalid component type: %s', \
Please use "..." for all the strings. This is being followed all across the code.

2021-05-14 13:57 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +    @classmethod
Please add event_messge_cli.py. Take conf_cli.py as examaple. You can defer this as well. Create a JIRA ticket for that if you plan to push it.

2021-05-14 13:57 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +        for attributes in ['module', 'event_id', 'message']:
attributes -> attribute. Its singular.

2021-05-14 14:07 UTC, ujjwalpl requested changes

2021-05-14 14:07 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +                'sensor_response_type': {
There is nothing called sensor in IEM. Lets use a better term and define the IEM Message Spec and add to the Spec Doc.

2021-05-14 14:08 UTC, ujjwalpl requested changes

2021-05-14 14:08 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +            return json.loads(alert.decode('utf-8'))
json.loads() may fail. Protect with try, catch.

2021-05-14 14:12 UTC, ujjwalpl requested changes

2021-05-14 14:12 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/error.py
> +class EventMessageError(Exception):
Since this definition is same as other exception. You can move this logic to src/utils/error.py as class UtilsError class, import and derrive from it. 

```
class EventMessageError(UtilsError):
    def __init__(self, rc, message, *args):
        super().__init__(rc, message, args)
```

2021-05-14 17:17 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +        for attributes in ['module', 'event_id', 'message']:
done

2021-05-14 17:18 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +            return json.loads(alert.decode('utf-8'))
taken care

2021-05-14 17:32 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +            raise EventMessageError(errno.EINVAL, 'Invalid component type: %s', \
changed to "..."

2021-05-14 17:32 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +            Conf.load('iem', cls._conf_file)
done

2021-05-14 17:33 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    @classmethod
A separate ticket for this is already created. Rohit is working on it

2021-05-14 17:36 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +                'sensor_response_type': {
Was following older structure. Resolved it

2021-05-14 17:37 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +        if alert is not None:
Added

2021-05-14 17:40 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    _conf_file = 'json:///etc/cortx.conf'
Changed the dir. will be taken care in mini provisioning

2021-05-14 17:40 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +        'H': 'Hardware',
done

2021-05-14 18:06 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/error.py
> +class EventMessageError(Exception):
derived from UtilsError

2021-05-15 12:15 UTC, ujjwalpl requested changes

2021-05-15 12:15 UTC, ujjwalpl commented on py-utils/src/utils/errors.py
> +class UtilsError(Exception):
BaseError was already there. You can reuse the same.

2021-05-15 12:15 UTC, ujjwalpl commented on py-utils/test/iem_framework/test_iem.py
> +            EventMessage.send(severity='B', module='mod', event_id='500', \
Better to maintain parameter sequence as module, event_id, severity, message, ...

2021-05-15 12:26 UTC, ujjwalpl requested changes

2021-05-15 12:26 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +        for attribute in ['module', 'event_id', 'message']:
Something wrong here. What are you validating, string ? Condition will always be false. 
This should be...
```
for attribute in [module, event_id, message]:
    if attribute is None:
        ....
```
```

2021-05-15 12:38 UTC, ujjwalpl requested changes

2021-05-15 12:38 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +            'message': {
Schema needs to be defined and reviewed with other teams. 
@sachinpunadikar please help define this schema. Please make it simple. 
Structure should be ... 
```
{
        header: {
                type: H|S|...
                location: 
                        site_id, rack_id, node_id, etc
               source: 
                        component_id, module_id, resource, etc
        }
        contents: { 
                payload: Message Payload
                args: ...
        }
}
```

2021-05-15 12:41 UTC, ujjwalpl requested changes

2021-05-15 12:41 UTC, ujjwalpl commented on py-utils/test/iem_framework/test_iem.py
> +class TestMessage(unittest.TestCase):
Please ensure following tests are covered
- send message
- send 1000 messages in a row. Ensure 1000 messages are received
- receive message
- receive 1000 messages in a row. 
- send message - negative. Pass invalid component, none message. tc. 
- receive message - negative. Pass invalid value
- Two process P1: send 1000 message. P2: Receive all 1000 messages

2021-05-15 13:15 UTC, selvakumaar5496 commented on py-utils/src/utils/errors.py
> +class UtilsError(Exception):
Removed BaseError

2021-05-15 13:24 UTC, selvakumaar5496 commented on py-utils/test/iem_framework/test_iem.py
> +            EventMessage.send(severity='B', module='mod', event_id='500', \
Taken care

2021-05-15 13:37 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +        for attribute in ['module', 'event_id', 'message']:
changed this. 
Reason: It never throwed an error. I removed _validate method which takes input as string. My bad

2021-05-17 15:40 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +            'message': {
Done

2021-05-17 15:41 UTC, selvakumaar5496 commented on py-utils/test/iem_framework/test_iem.py
> +class TestMessage(unittest.TestCase):
Have covered these testcases

2021-05-17 15:49 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +            'message': {
done

2021-05-17 15:49 UTC, selvakumaar5496 commented on py-utils/test/iem_framework/test_iem.py
> +class TestMessage(unittest.TestCase):
Covered

2021-05-18 05:28 UTC, ujjwalpl requested changes

2021-05-18 05:28 UTC, ujjwalpl commented on py-utils/src/utils/errors.py
> +class InternalError(Exception):
Please ensure this does not break anything. There are other modules using it and any changes to this will introduce a bug. Please take a look at all the places where it is used.

2021-05-18 05:28 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +                'Location': {
'location'

2021-05-18 05:28 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +                'Source': {
'source'

2021-05-18 05:28 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +                'Contents': {
'contents'

2021-05-18 05:31 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +                'Location': {
Already taken care on commit 187d238

2021-05-18 05:31 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +                'Source': {
Already taken care on commit 187d238

2021-05-18 05:31 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +                'Contents': {
Already taken care on commit 187d238

2021-05-18 05:32 UTC, selvakumaar5496 commented on py-utils/src/utils/errors.py
> +class InternalError(Exception):
It is not used anywhere else.

2021-05-18 16:09 UTC, ujjwalpl approved these changes

2021-05-18 16:49 UTC, rahul-tripathi-git approved these changes
Looks good.

2021-05-18 17:25 UTC, sachinpunadikar approved these changes
+1

2021-05-18 17:30 UTC, merged