[WIP] CLI framework movement to py-utils
Seagate/cortx-utils pull request #279
Opened 2021-05-10 14:24 UTC by udayan-y21

Signed-off-by: Udayan Yaragattikar <udayan.yaragattikar@seagate.com>

2021-05-17 04:23 UTC, sachinpunadikar commented on py-utils/src/utils/cli/__init__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Correct the copyright year.

2021-05-17 05:05 UTC, udayan-y21 commented on py-utils/src/utils/cli/__init__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
okay. iwill update

2021-05-17 12:24 UTC, udayan-y21 commented on py-utils/src/utils/cli/__init__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Comment resolved Please review.

2021-05-17 18:16 UTC, pawankumarsrivastava requested changes

2021-05-17 18:16 UTC, pawankumarsrivastava commented on py-utils/src/utils/cli/cli_client.py
> +        super(DirectClient, self).__init__(None)
DirectClient or RestClient?

2021-05-18 05:26 UTC, udayan-y21 commented on py-utils/src/utils/cli/cli_client.py
> +        super(DirectClient, self).__init__(None)
Sorry itwas mistake.. Resolved comment.

2021-05-18 09:15 UTC, soniyamoholkar approved these changes

2021-05-18 09:36 UTC, pawankumarsrivastava approved these changes

2021-05-18 11:28 UTC, sachinpunadikar commented on py-utils/src/utils/cli/command.py
> +        self._output = options["output"]
Please keep consistency , use single quotes as those were used most of the places. Revisit your changes to stick to a consistent pattern of single quotes or double quotes.

2021-05-18 12:10 UTC, udayan-y21 commented on py-utils/src/utils/cli/command.py
> +        self._output = options["output"]
Changes implemeted. Please review

2021-05-18 14:03 UTC, sachinpunadikar approved these changes
+1

2021-05-18 15:00 UTC, ujjwalpl requested changes

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/setup.py
> +		        'cortx.utils.setup', 'cortx.utils.setup.kafka',
Fix indentation.

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/cli_client.py
> +# CORTX-Py-Utils: CORTX Python common library.
please change the dir name to cli_framework

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/cli_validators.py
> +class CommonValidators:
Move this to validator framework in terms of generalized validation and call from CLI code.

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/cli_validators.py
> +    def positive_int(value):
All the private interfaces muste start with _

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/command.py
> +
Use 2 lines space between the class definitions

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/terminal.py
> +
Comment

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/schema/cli_default_roles.json
> +{
Is this sample ? If not these should be in the consuming component.

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/command_factory.py
> +        default_commands = os.listdir(const.COMMAND_DIRECTORY)
COMMAND_DIRECTORY should be a variable and input to the interface. Not hard coded.

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/const.py
> +BASE_DIR = "/opt/seagate/cortx"
We need to avoid hard coding of paths in the code.

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/const.py
> +NO_AUTH_COMMANDS = ["support_bundle", "bundle_generate", "csm_bundle_generate",
This should be in the CSM or in the consumer.

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/const.py
> +HIDDEN_COMMANDS = ["bundle_generate", "csm_bundle_generate",]
Same here.

2021-05-18 15:00 UTC, ujjwalpl commented on py-utils/src/utils/cli/errors.py
> +class ArgumentError(argparse.ArgumentError):
Will be good to call CliError. Argument Error can be an input.

2021-05-18 16:24 UTC, udayan-y21 commented on py-utils/setup.py
> +		        'cortx.utils.setup', 'cortx.utils.setup.kafka',
![image](https://user-images.githubusercontent.com/66424882/118688152-6acb3300-b823-11eb-8579-ad203d867f5d.png)
No identation issue observed. I guess Github is showing incorreeectly

2021-05-18 16:25 UTC, udayan-y21 commented on py-utils/src/utils/cli/cli_client.py
> +# CORTX-Py-Utils: CORTX Python common library.
Modifications done.

2021-05-18 16:26 UTC, udayan-y21 commented on py-utils/src/utils/cli/command.py
> +
Modifications done

2021-05-18 17:25 UTC, udayan-y21 commented on py-utils/src/utils/cli/command_factory.py
> +        default_commands = os.listdir(const.COMMAND_DIRECTORY)
@ujjwalpl COMMAND_DIRECTORY common contains schema files which is extended with component schema files
```
        default_commands = os.listdir(const.COMMAND_DIRECTORY)
        commands_files = os.listdir(component_cmd_dir)
        commands_files.extend(default_commands)
```

2021-05-18 18:03 UTC, udayan-y21 commented on py-utils/src/utils/cli/errors.py
> +class ArgumentError(argparse.ArgumentError):
Modifications done.

2021-05-18 18:06 UTC, udayan-y21 commented on py-utils/src/utils/cli/const.py
> +HIDDEN_COMMANDS = ["bundle_generate", "csm_bundle_generate",]
Modifications Done.
Removed from cli framework. Added to CSM. 
Kept `HIDDEN_COMMANDS = []`  for placeholder incase of any hidden commands to be added here.

2021-05-18 18:06 UTC, udayan-y21 commented on py-utils/src/utils/cli/const.py
> +NO_AUTH_COMMANDS = ["support_bundle", "bundle_generate", "csm_bundle_generate",
Modifications Done.
Removed from cli framework. Added to CSM. 
Kept `NO_AUTH_COMMANDS  = []`  for placeholder incase of any noauth  commands to be added here.

2021-05-19 07:31 UTC, udayan-y21 commented on py-utils/src/utils/cli/cli_validators.py
> +    def positive_int(value):
Modifications done.

2021-05-19 07:32 UTC, udayan-y21 commented on py-utils/src/utils/cli/cli_validators.py
> +class CommonValidators:
Modifications done.

2021-05-19 09:24 UTC, udayan-y21 commented on py-utils/src/utils/cli/const.py
> +BASE_DIR = "/opt/seagate/cortx"
For hardcoaded paths, I talked to sachin, He saaid there is already task in pipeline for this and will be taken care in this or next sprint. Once the solution is implemented i will make the changes accordingly.

2021-05-19 14:15 UTC, ujjwalpl commented on py-utils/setup.py
> +		        'cortx.utils.setup', 'cortx.utils.setup.kafka',
There is a tab before 'cortx.utils.setup'

2021-05-19 14:15 UTC, ujjwalpl commented on py-utils/src/utils/validator/cli_validators.py
> +class CommonValidators:
Validators have an objectives. We cant have a generic one called common validators. 

_positive_int is just one line code and can be there in the main code itself. 

Other one can be FormatV.
```
class FileV: 
     def validate(type): 
          ... 
```

Refer to the other validators already checked into the dir.

2021-05-19 14:18 UTC, ujjwalpl requested changes

2021-05-19 14:18 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/cli_client.py
> +class RestClient(CliClient):
As per the discussion, we need to RestClient at the base and CLI will use Rest. Derivation does not look currently. You can rename base class as just the 'Client' to solve this.

2021-05-19 18:21 UTC, udayan-y21 commented on py-utils/src/utils/validator/cli_validators.py
> +class CommonValidators:
@ujjwalpl Agreed to your comment. 
`_positive_int` and `_file_parser` are the static methods. They are consumed into cli framework directly with classnames.
Other validators in dir are not static methods.
You can say it as the limitation for the current CLI framework implementation to consume only static validators methods.

This is how its written in command json
```
{
            "flag": "-o",
            "type": "CommonValidators._positive_int",
            "type_target": "cortx.utils.validator.cli_validators",
            "dest": "offset",
            "help": "Amount of users you want to get",
            "params": true
},
```

2021-05-19 18:25 UTC, udayan-y21 commented on py-utils/setup.py
> +		        'cortx.utils.setup', 'cortx.utils.setup.kafka',
Modifications Done

2021-05-19 18:43 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/cli_client.py
> +class RestClient(CliClient):
@ujjwalpl 
Reason behind doing this was: 
Actually there are 2 ways of  communication the 
![image](https://user-images.githubusercontent.com/66424882/118866304-78ee8180-b8ff-11eb-9d3f-1ee777473853.png)

1. Direct call to method of the class
```
"comm": {
        "type": "direct",
        "target": "csm.cli.support_bundle",
        "method": "bundle_generate",
        "class": "SupportBundle",
        "is_static": true
      }
```
This implemetation is at py-utils because its independent of any component. It can call any "method" from "class" at given "target"

2. Rest api call
```
 "comm": {
        "type": "rest",
        "method": "get",
        "target": "/{version}/csm/users",
        "version": "v2"
      },
```
This implementation is at CSM side because it was coupled with csm rest api services

I may be interpreting your comment wrongly. Please let me know.

2021-05-20 03:52 UTC, ujjwalpl requested changes

2021-05-20 03:52 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/cli_client.py
> +class RestClient(CliClient):
Base class still should be called "Client" and not "CliClient" it does not have any CLI element / features. 

Also looking at the diagram and comment, you need a new class called CliClient which will be base for other Apps. 

Client 
RestClient -> Client (Is_a relationship)
DirectClient -> Client (Is_a relationship)
CliClient -> Client (Is_a relationship) 
CliClient -o RestClient (using/has_a relationship. Uses RestClient for its purpose)

2021-05-20 04:02 UTC, ujjwalpl requested changes

2021-05-20 04:02 UTC, ujjwalpl commented on py-utils/src/utils/validator/cli_validators.py
> +class CommonValidators:
CommonValidators cant be used. We need proper classes. CommonValidators does not represent any Entity. 
Static or non static members do not impact the class definition. There can be a proper validator class with static member.

2021-05-20 04:19 UTC, ujjwalpl requested changes

2021-05-20 04:19 UTC, ujjwalpl commented on py-utils/test/test_cli_framework/cli_test_data/users_command_output.json
> +{
Please rename test_cli_framework. to cli_framework. Its test/cli_framework. We are in the process of renaming others.

2021-05-20 04:19 UTC, ujjwalpl commented on py-utils/src/utils/providers.py
> +#!/usr/bin/env python3
We should avoid adding any new file at the root level, i.e. utils. Please move this to cli_framework or another folder "schema" which is meant for defining the schema base classes.

2021-05-20 04:31 UTC, ujjwalpl requested changes

2021-05-20 04:31 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/command.py
> +        return output_obj.dump(out, err, **self._output,
Indentation being followed in the code is... 

```
return output_obj.dump(out, err, **self._output, 
    output_type=self._options.get("format", "success"))
```

2021-05-20 04:31 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/command.py
> +             sub_parser = sub_parser.add_parser(data["name"],
Indentation
```
sub_parser = sub_parser.add_parser(data["name"], 
    help=data["description"])
```

2021-05-20 04:31 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/command.py
> +            sub_parser.set_defaults(command=Command,
indentation as above
```
first line
<4 spaces>second line
<4 spaces>third line
```

2021-05-20 04:34 UTC, ujjwalpl requested changes

2021-05-20 04:34 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/const.py
> +BASE_DIR = "/opt/seagate/cortx"
Need to avoid hard coding. This is for new code.

2021-05-20 04:34 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/const.py
> +NO_AUTH_COMMANDS = []
This is not used anywhere and should be removed.

2021-05-20 04:34 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/terminal.py
> +                                f"Current {Terminal.EMPTY_PASS_FIELD}")
1. Error strings should not use format string. It cant be translated. It shoudl be 
2. Error string is unclear. It should be human readable. 

"Could not obtain current password %s"...

2021-05-20 08:32 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/cli_client.py
> +class RestClient(CliClient):
Modifications done

2021-05-20 09:49 UTC, udayan-y21 commented on py-utils/test/test_cli_framework/cli_test_data/users_command_output.json
> +{
Modifications done

2021-05-20 10:13 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/command.py
> +        return output_obj.dump(out, err, **self._output,
Modifications done

2021-05-20 10:13 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/command.py
> +             sub_parser = sub_parser.add_parser(data["name"],
Modifications done

2021-05-20 12:31 UTC, ujjwalpl requested changes

2021-05-20 12:31 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/cli_client.py
> +class DirectClient(Client):
With the structure, this class become CliClient as it deals with command. Commands are applicable in CLI.

2021-05-20 13:12 UTC, ujjwalpl requested changes

2021-05-20 13:12 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/const.py
> +BASE_DIR = "/opt/seagate/cortx"
Please discuss with Foundation Team. This will be taken from a conf file. 
install_path=Conf.get(globals, "INSTALL_PATH")

2021-05-20 13:12 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/terminal.py
> +class Terminal:
Add comment.

2021-05-21 05:15 UTC, closed without merging