EOS-19838 - [Openldap provisioning] Implement post_install with all validations in cortx-utils repository
Seagate/cortx-utils pull request #282
Opened 2021-05-12 11:55 UTC by shahidSTX

This branch is cloned from parent branch `br/ms/EOS-19838-Openldap_provisioning` which has enabled the openldap provisioning and provides all necessary interfaces for phase-wise provisioning.

This branch implements the validations for post_install phase of openldap provisioning, as observed in the [HLD](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/268829518/OpenLDAP+in+CORTX+Environment).

Code implemented :
* openldap_setup binary ready for consumption/testing.
* Pre-requisites and keys validation in place for post_install.

To be done :
* Add templates for post_install 1-node and 3-node.
* Add code to generate openldapsetup_prereqs.json file and templates during installation.

Testing in progress, update so far :
* openldap_setup binary is available and accepts post_install argument.

Testing to be done :
* Test post_install argument with appropriate parameter.
* Test pre-requisite validation and keys validation for each phase.

2021-05-14 08:19 UTC, amitwac2608 requested changes

2021-05-14 08:19 UTC, amitwac2608 commented on py-utils/setup.py
> +		'cortx.utils.setup', 'cortx.utils.setup.kafka',
indentation

2021-05-14 08:19 UTC, amitwac2608 commented on py-utils/src/utils/setup/openldap/configcmd.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
copyright 2021

2021-05-14 08:19 UTC, amitwac2608 commented on py-utils/src/utils/setup/openldap/__init__.py
> +#!/bin/python3
I don't think we need to put anything in the __init__.py file.

2021-05-14 08:19 UTC, amitwac2608 commented on py-utils/src/utils/setup/openldap/configcmd.py
> +      self.update_cluster_id()
I don't think we need to update clusterID anywhere !!

2021-05-14 08:19 UTC, amitwac2608 commented on py-utils/src/utils/setup/openldap/configcmd.py
> +    os.system('python3 ./../../third_party/openldap/base_configure_ldap.py --forceclean True --rootdnpasswd ' + rootdn_passwd)
why need to run the python script ? Lets call the required function from the bas_configure_ldap module.

2021-05-14 08:19 UTC, amitwac2608 commented on py-utils/src/utils/setup/openldap/openldapsetup_prereqs.json
> +  }
need comma

2021-05-17 05:44 UTC, shahidSTX commented on py-utils/setup.py
> +		'cortx.utils.setup', 'cortx.utils.setup.kafka',
Updated.

2021-05-17 05:44 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/configcmd.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Done.

2021-05-17 05:44 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/__init__.py
> +#!/bin/python3
Removed.

2021-05-17 05:44 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldapsetup_prereqs.json
> +  }
Added

2021-05-17 11:38 UTC, amitwac2608 commented on py-utils/src/utils/setup/openldap/openldap.py
> +        with open('/etc/machine-id') as f:
handle the case where machine-id file does not exist.

2021-05-17 11:38 UTC, amitwac2608 commented on py-utils/src/utils/setup/openldap/openldap.py
> +        if not os.path.isfile(self._preqs_conf_file):
this file is being validated here, but we already accessed this in constructor !!! this check should be in constructor as well.

2021-05-17 11:38 UTC, amitwac2608 commented on py-utils/src/utils/setup/openldap/openldap_setup.py
> +        self.openldap.validate("post_install")
call validate and key_validate functions from post_install() function.

2021-05-17 11:40 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        with open('/etc/machine-id') as f:
Or we can add this to package validation?
"files" : ["file:/etc/machine-id"]

2021-05-17 11:41 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        if not os.path.isfile(self._preqs_conf_file):
I'll move this code block to constructor.

2021-05-17 11:43 UTC, amitwac2608 commented on py-utils/src/utils/setup/openldap/openldap.py
> +        with open('/etc/machine-id') as f:
constructor would be called before validations function.

2021-05-17 12:08 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        with open('/etc/machine-id') as f:
Done, added this to constructor.

2021-05-17 12:08 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        if not os.path.isfile(self._preqs_conf_file):
Done.

2021-05-17 12:08 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap_setup.py
> +        self.openldap.validate("post_install")
Done.

2021-05-17 12:09 UTC, amitwac2608 approved these changes

2021-05-17 12:13 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/configcmd.py
> +      self.update_cluster_id()
This will be taken up in feature branch `br/ms/EOS-19838-Openldap_provisioning` check-in.

2021-05-17 12:13 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/configcmd.py
> +    os.system('python3 ./../../third_party/openldap/base_configure_ldap.py --forceclean True --rootdnpasswd ' + rootdn_passwd)
This will be taken up in feature branch `br/ms/EOS-19838-Openldap_provisioning` check-in.

2021-05-17 13:59 UTC, ujjwalpl requested changes

2021-05-17 13:59 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +    _preqs_conf_file = "/opt/seagate/cortx/setup/openldap/openldapsetup_prereqs.json"
Please avoid hard coding of paths. Please separate install path and then relative path from there. For example it should be possible to install onto <Install Path>/setup/openldap/openldapsetup_prereqs.json"

2021-05-17 13:59 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +    def key_value_verify(self, key: str):
All functions which are not interfaces must start with _

2021-05-17 13:59 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +    def extract_yardstick_list(self, phase_name: str):
def _extract_yardstick_list....

2021-05-17 13:59 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +        value = Conf.get(self.index)
Conf.get() takes key as mandatory parameter.

2021-05-17 13:59 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +        with open('/etc/machine-id') as f:
Conf Store support machine. It should be obtained from Conf Store.

2021-05-17 13:59 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +            sys.stdout.write("Validation complete\n")
We need to avoid printing anything on the output. If needed things should be logged. Use logger framework for that purpose. py-utils/src/utils/log.py

2021-05-17 14:00 UTC, ujjwalpl requested changes

2021-05-17 14:00 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +        self.keys_validate("post_install")
Please add the test code for ldap setup in py-utils/test/openldap_setup/test_openldap_setup.py

2021-05-17 14:02 UTC, ujjwalpl requested changes

2021-05-17 14:02 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +        # The openldap prov config file has below pairs :
Comment style, please use 
"""
comment
"""

2021-05-17 14:04 UTC, ujjwalpl requested changes

2021-05-17 14:04 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +                if (
There is not need to split the code into multiple lines for consistency and readability. 
```
if phase_name in ["TEST", "RESET", "CLEANUP"]: 
    continue
```
This is small and readable.

2021-05-17 14:05 UTC, ujjwalpl requested changes

2021-05-17 14:05 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +                            for key_x,key_y in zip(key_yard_token_list, key_arg_token_list):
Please use a whitespace after evert ","

2021-05-17 14:06 UTC, ujjwalpl requested changes

2021-05-17 14:06 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +    def keys_validate(self, phase_name: str):
def _keys_validate(self, phase_name: str):

2021-05-17 14:26 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        value = Conf.get(self.index)
Done.

2021-05-17 14:26 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +            sys.stdout.write("Validation complete\n")
This is planned to be taken up in next sprint, new JIRA will be logged.

2021-05-17 14:29 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        self.keys_validate("post_install")
This needs to be added to DoD and will be taken up next.

2021-05-17 14:31 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +                if (
Done.

2021-05-17 14:32 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +                            for key_x,key_y in zip(key_yard_token_list, key_arg_token_list):
Done.

2021-05-17 14:33 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +    _preqs_conf_file = "/opt/seagate/cortx/setup/openldap/openldapsetup_prereqs.json"
#TODO : Agreed, this change will be included in the feature branch which will maintain install path and relative path info, only file name will be used here.

2021-05-17 14:34 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +    def key_value_verify(self, key: str):
Done.

2021-05-17 14:43 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +    def extract_yardstick_list(self, phase_name: str):
Done.

2021-05-17 14:43 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        with open('/etc/machine-id') as f:
Done.

2021-05-17 14:43 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        # The openldap prov config file has below pairs :
Done.

2021-05-17 14:44 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +    def keys_validate(self, phase_name: str):
Done.

2021-05-18 11:25 UTC, ujjwalpl requested changes

2021-05-18 11:25 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +        For such examples, we skip and continue with
Can we reduce the truncating comments too early like this line. Can be written in one line and continue until 80 column. This will help make better use of real estate and readability. 

**For such examples, we skip and continue with remaining keys.**

2021-05-18 11:25 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +        self.cluster_id_key = Conf.get(self.prov, 'CONFIG>CONFSTORE_CLUSTER_ID_KEY').replace("machine-id", self.machine_id)
split the line at max 80 char
```
self.cluster_id_key = Conf.get(self.prov, 'CONFIG>CONFSTORE_CLUSTER_ID_KEY').replace( \
    "machine-id", self.machine_id)
```

2021-05-18 11:33 UTC, ujjwalpl requested changes

2021-05-18 11:33 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +        Once a key from yardstick file has found a
Wrap around column 80 to make good use of real estate. Example...

```
matching pair in argument file, the value of that key from 
argument file needs to be verified. It should be neither none,
empty nor any undesirable value.
```

2021-05-18 11:58 UTC, ujjwalpl requested changes

2021-05-18 11:58 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +        except Exception as e:
Refer to KafkaSetupError. Create a exception class which holds all the context about openldap like what was the error code, why things failed, what was the parameters, etc.

2021-05-28 10:02 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +    _preqs_conf_file = "/opt/seagate/cortx/setup/openldap/openldapsetup_prereqs.json"
Done.

2021-05-28 10:44 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +            sys.stdout.write("Validation complete\n")
Added

2021-05-29 11:45 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        For such examples, we skip and continue with
Done.

2021-05-29 11:45 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        self.cluster_id_key = Conf.get(self.prov, 'CONFIG>CONFSTORE_CLUSTER_ID_KEY').replace("machine-id", self.machine_id)
Done.

2021-05-29 11:46 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        Once a key from yardstick file has found a
Done.

2021-05-29 11:50 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        except Exception as e:
Done.

2021-05-29 12:30 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +        self.keys_validate("post_install")
Taking this up in [EOS-19841](https://jts.seagate.com/browse/EOS-19841)

2021-06-01 10:08 UTC, bkirunge7 commented on py-utils/src/utils/setup/openldap/openldap.py
> +                if services:
is this error condition and need to exit if services is empty

2021-06-01 10:30 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +            Log.debug("Validation complete\n")
Add stage and phase name to log.

2021-06-01 10:49 UTC, ujjwalpl requested changes

2021-06-01 10:49 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +from cortx.utils.log import Log
OpenldapSetupError should be derived from BaseError

2021-06-01 10:49 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +            raise FileNotFoundError(f'pre-requisite json file: \
Please raise OpenldapSetupError with error code and error description. 
Avoid using formatted string f"" while raising due to translation requirement.

2021-06-01 10:50 UTC, ujjwalpl requested changes

2021-06-01 10:50 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +            raise Exception(f'Empty value for key : {key}')
raise OpenldapSetupError with proper error code. Avoid formatted string

2021-06-01 10:50 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +                raise Exception(f'No match found for {key_yard}')
raise OpenldapSetupError with proper error code. Avoid formatted string

2021-06-01 10:50 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/openldap.py
> +            raise Exception(f'ERROR : Validating keys failed, exception {e}\n')
raise OpenldapSetupError with proper error code. Avoid formatted string

2021-06-15 06:55 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +                raise Exception(f'No match found for {key_yard}')
Will be taken up in [EOS-19841](https://jts.seagate.com/browse/EOS-19841)

2021-06-15 06:59 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +                if services:
Will be taken up in [EOS-19841](https://jts.seagate.com/browse/EOS-19841)

2021-06-15 07:01 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +from cortx.utils.log import Log
`from BaseError import rc, error`
This is the base error that will now be derived by `OpenldapSetupError`

2021-06-15 08:15 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +            raise FileNotFoundError(f'pre-requisite json file: \
Updated with OpenldapSetupError and removed f"" formatting.

2021-06-15 08:15 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +            raise Exception(f'Empty value for key : {key}')
Updated with OpenldapSetupError and removed f"" formatting.

2021-06-15 08:15 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +                raise Exception(f'No match found for {key_yard}')
Updated with OpenldapSetupError and removed f"" formatting.

2021-06-15 08:15 UTC, shahidSTX commented on py-utils/src/utils/setup/openldap/openldap.py
> +            raise Exception(f'ERROR : Validating keys failed, exception {e}\n')
Updated with OpenldapSetupError and removed f"" formatting.

2021-06-15 08:25 UTC, bkirunge7 approved these changes

2021-06-15 09:52 UTC, shahidSTX commented
Merging the changes from post_install branch to feature branch, all pending changes will be tracked in [EOS-19841](https://jts.seagate.com/browse/EOS-19841)

2021-06-15 09:53 UTC, merged