EOS-19737 : Added Reset/Cleanup for utils_setup
Seagate/cortx-utils pull request #284
Opened 2021-05-12 19:12 UTC by vastradparayya

This provides support for Reset/Cleanup for utils_setup
Associated jira - https://jts.seagate.com/browse/EOS-19737

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

2021-05-12 19:13 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-05-13 10:26 UTC, ujjwalpl requested changes

2021-05-13 10:26 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            raise SetupError(errno.ENOENT, "Reset/Cleanup has already done or config file not found! ")
We should not throw error in this case. If someone accidently deletes this file, you will never cleanup message bus.

2021-05-13 10:26 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            raise SetupError(errno.ENOENT, "Cleanup has already done or config file not found! ")
Same case here as well. Reset / Cleanup and other ops are idempotent ops i.e. they can be run multiple times and must not throw error.

2021-05-15 11:50 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            raise SetupError(errno.ENOENT, "Reset/Cleanup has already done or config file not found! ")
Done. Made the changes

2021-05-15 11:51 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            raise SetupError(errno.ENOENT, "Cleanup has already done or config file not found! ")
Done. Made the changes

2021-05-15 12:03 UTC, ujjwalpl requested changes

2021-05-15 12:03 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        rc = Utils.cleanup()
Why not call validate here ? like we do for reset ?

2021-05-15 12:09 UTC, ujjwalpl requested changes

2021-05-15 12:09 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +                raise SetupError(errno.EINTR, "Error deleting config file %s, %s", config_file, err)
```
except OSError as e:
    raise SetupError(e.errno, "Error deleting config file %s, %s", config_file, e)
```

2021-05-15 12:28 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        rc = Utils.cleanup()
As of now we are not doing validation. Utils.validate('reset'), it has empty implementation

2021-05-15 12:44 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +                raise MessageBusError(errno.ETIMEDOUT, "Error while resetting! %s", err)
Done. Made the changes

2021-05-15 12:45 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +                raise SetupError(errno.EINTR, "Error deleting config file %s, %s", config_file, err)
Done. Made the changes

2021-05-15 12:59 UTC, ujjwalpl requested changes

2021-05-15 12:59 UTC, ujjwalpl commented on py-utils/src/utils/errors.py
> +OP_FAILED = 200
200 was just an example. We need to pick up a number in the series like 0x1006
```
INTERNAL_ERROR = 0x1005
OP_FAILED = 0x1006
```

2021-05-15 13:00 UTC, ujjwalpl requested changes

2021-05-15 13:00 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            except Exception as e:
This does not follow the code I suggested. There are still errror. Message Bus throws MessageBusError. You must catch it.

2021-05-17 06:28 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            except Exception as e:
Done.

2021-05-17 06:28 UTC, vastradparayya commented on py-utils/src/utils/errors.py
> +OP_FAILED = 200
Done

2021-05-17 07:28 UTC, ujjwalpl requested changes

2021-05-17 07:28 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +                raise SetupError(errno.ETIMEDOUT, "Can not reset Message Bus. %s", e)
raise SetupError(e.rc, "Can not reset Message Bus. %s", e)

2021-05-17 07:44 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +                raise SetupError(errno.ETIMEDOUT, "Can not reset Message Bus. %s", e)
Sorry Ujjwal, got it.
Done

2021-05-17 08:04 UTC, ujjwalpl approved these changes

2021-05-17 08:19 UTC, rahul-tripathi-git reviewed
+1

2021-05-17 08:20 UTC, rahul-tripathi-git approved these changes
+1

2021-05-17 08:54 UTC, sachinpunadikar approved these changes
+1

2021-05-17 08:55 UTC, merged