EOS-19829 : Msgbus should send appropriate Error Codes for failures scenarios
Seagate/cortx-utils pull request #285
Opened 2021-05-14 07:26 UTC by vastradparayya

Return code picked automatically from MessageBusError based on passed exception
Associated jira - https://jts.seagate.com/browse/EOS-19829

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

2021-05-14 07:28 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-05-14 08:48 UTC, ujjwalpl requested changes

2021-05-14 08:48 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +    # common error codes
There are generic REST error codes and should be there in the rest_server.py with generic names

2021-05-14 08:49 UTC, ujjwalpl requested changes

2021-05-14 08:49 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +                       self.MB_TOPIC_ALREADY_EXISTS: ["TOPIC_ALREADY_EXISTS"],
Why is "TOPIC_ALREADY_EXISTS" a string ? If its a String, then it should be written properly like

"Topic %s Already Exists"

2021-05-14 10:42 UTC, ujjwalpl requested changes

2021-05-14 10:42 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            raise MessageBusError("Invalid entry %s. %s", key, "NOENT")
What is "NOENT" ? Doesnt make sense. 
Also there is single %s and two params looks to be incorrect.

2021-05-14 10:42 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +        for key, value in error_codes.items():
The mapping should be in other way so you dont have to scan.

2021-05-14 10:46 UTC, vastradparayya commented on py-utils/src/utils/message_bus/error.py
> +                       self.MB_TOPIC_ALREADY_EXISTS: ["TOPIC_ALREADY_EXISTS"],
Yes @ujjwalpl , it is a string. "Topic %s Already Exists" will be returned to user.
**example output -** cortx.utils.message_bus.error.MessageBusError: error(152): Admin operation fails for Alert. KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'Alert' already exists."}

We are checking this string in caught exception, if it is in caught exception we will return respective return code.
Eg: if "TOPIC_ALREADY_EXISTS" in "KafkaError{code=TOPIC_ALREADY_EXISTS,val=36,str="Topic 'Alert' already exists."}" then return error_code(In this case - 152)

2021-05-14 11:07 UTC, ujjwalpl requested changes

2021-05-14 11:07 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError("Invalid client type %s - %s", client_type, "INVALID_CLIENT_TYPE")
raise MessageBusError(ERR_INVALID_CLIENT_TYPE, "Invalid client type %s", client_type)

ERR_INVALID_CLIENT_TYPE should be integer. 

update MessageBusError class

2021-05-14 11:16 UTC, ujjwalpl requested changes

2021-05-14 11:16 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +                       self.MB_TOPIC_ALREADY_EXISTS: ["TOPIC_ALREADY_EXISTS"],
It should be code. Example...
MessageBusError(ERR_TOPIC_ALREADY_EXISTS, Topic %s Already Exists", topic)

2021-05-14 11:31 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError("Invalid client type %s - %s", client_type, "INVALID_CLIENT_TYPE")
We have defined error codes as integers in MessageBusError class and integers picked based on exception passed or parameter passed

2021-05-14 16:52 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/error.py
> +    # common error codes
The MessageBus client is trying to reach out to Broker , and above error codes are related to that connection. This is not related to REST server. We will handle REST server related errors in REST server related PR.

2021-05-14 16:57 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/error.py
> +                       self.MB_TOPIC_ALREADY_EXISTS: ["TOPIC_ALREADY_EXISTS"],
We are getting error messages from Kafka library, which contains above keywords (like TOPIC_ALREADY_EXISTS). As we are not receiving any error code, but the string, we need to parse. Hence we come up with logic where we return error code from MessageBus , based on the keyword we find in kafka error message.

2021-05-14 16:58 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/error.py
> +        for key, value in error_codes.items():
As explained above, we need to scan the keywords in kafka error message.

2021-05-15 11:55 UTC, vastradparayya commented on py-utils/src/utils/message_bus/error.py
> +                       self.MB_TOPIC_ALREADY_EXISTS: ["TOPIC_ALREADY_EXISTS"],
@ujjwalpl Done changes, kindly review.

2021-05-15 11:55 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            raise MessageBusError("Invalid entry %s. %s", key, "NOENT")
@ujjwalpl Done changes, kindly review.

2021-05-15 11:56 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError("Invalid client type %s - %s", client_type, "INVALID_CLIENT_TYPE")
Done changes, kindly review.

2021-05-15 14:12 UTC, ujjwalpl requested changes

2021-05-15 14:12 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +    ERR_MB_REQUEST_TIMED_OUT = 100
These can be generic error messages. We can remove _MB_ unless any error is specifically applicatble to only Message Bus. e.g. REQUEST_TIMED_OUT is a common error.

2021-05-15 14:18 UTC, ujjwalpl requested changes

2021-05-15 14:18 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +    # common error codes
Agree. I thought these are REST error since they start with 101, 201, etc. 
However, errors need to be generic like you see in the REST or unix errno. REQUEST_TIMED_OUT is a common error. There can be very specific error which can remain like MB_BROKER_NOT_AVAILABLE.

2021-05-15 14:18 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +        raise MessageBusError(MessageBusError.ERR_MB_INVALID_BROKER_TYPE, \
raise (error.ERR_MB_INVALID_BROKER_TYPE, ...)

2021-05-15 14:18 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +    ERR_MB_BROKER_NOT_AVAILABLE = 101
Use src/utils/error.py for these error codes. We will try to work common unique error codes.

2021-05-17 08:30 UTC, vastradparayya commented on py-utils/src/utils/message_bus/error.py
> +    ERR_MB_BROKER_NOT_AVAILABLE = 101
We are specifying error codes related to Message Bus in 'CORTX Message Bus Specifications ' document for more description about error code.  Do we need to keep these in CORTX Message Bus Specifications  document.

2021-05-19 07:52 UTC, vastradparayya commented on py-utils/src/utils/message_bus/error.py
> +    # common error codes
Done

2021-05-19 07:55 UTC, vastradparayya commented on py-utils/src/utils/message_bus/error.py
> +    ERR_MB_REQUEST_TIMED_OUT = 100
Done

2021-05-19 07:55 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker.py
> +        raise MessageBusError(MessageBusError.ERR_MB_INVALID_BROKER_TYPE, \
Done

2021-05-20 03:10 UTC, ujjwalpl requested changes

2021-05-20 03:10 UTC, ujjwalpl commented on py-utils/src/utils/errors.py
> +ERR_INVALID_CONFIG = 0x1502
ERR_INVALID_CONFIG can be removed and error can be mapped to ERR_MISSING_CONFIG_ENTRY or ERR_MISSING_CONFIG_PARAMS

2021-05-20 03:10 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +ERR_LEADER_NOT_AVAILABLE = 0x1601
Please place all the errors in the errors.py only.

2021-05-20 03:10 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +ERR_INVALID_BROKER_TYPE = 0x1604
Invalid Service Name

2021-05-20 03:24 UTC, ujjwalpl requested changes

2021-05-20 03:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            raise MessageBusError(errno.EINVAL, \
Dont truncate text before 80 chars for readability. Also Error number can be more relevant now that you have defined new ones.

2021-05-20 03:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +                "Invalid entry %s.", key)
Invalid entry is too generic and does not provide any information. 
"Could not find key %s in conf file %s"

2021-05-20 03:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +                "Invalid conf in %s. %s ", self.conf_file, e)
"Error while parsing configuration file %s. %s.

2021-05-20 03:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                'Consumer %s is not initialized.', consumer_id)
ERR_CLIENT_NOT_FOUND == ENOENT or ENOTFOUND

2021-05-20 03:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/error.py
> +ERR_DEFAULT_ERROR_CODE = 0x1699
There can not be such error. We need to map every error to a valid error code. Please remove this.

2021-05-20 03:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                'Cant Receive - KeyboardInterrupt')
Message needs to be meaningful You need to include parameter 
Use Error Code. EINTR
"Received Keyboard interrupt while trying to receive message for consumer %s"

2021-05-20 03:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                        'Cant receive. %s', msg.error())
Message needs to be meaningful You need to include parameter 
Use meaningful Error Code. Refer to this table https://man7.org/linux/man-pages/man3/errno.3.html  
"Could not receive message for consumer %s. %s"

2021-05-20 03:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                'Consumer %s is not initialized.', consumer_id)
Use meaningful Error Code. Refer to this table https://man7.org/linux/man-pages/man3/errno.3.html

2021-05-20 03:24 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                "Unable to get the message count. %s.", e)
Use meaningful Error Code. Refer to this table https://man7.org/linux/man-pages/man3/errno.3.html
Message needs to be meaningful You need to include parameter
"Could not get message count for consumer group %s. %s", consumer_group, ...

2021-05-20 03:41 UTC, ujjwalpl requested changes

2021-05-20 03:41 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    'Unable to delete messages for %s.', message_type)
1. Use "..." and not '...' for consistency all over. For single word we use '..'
2. Print all the context properly. 
"Unable to delete messages for type %s using admin %s after %d retries"

2021-05-20 05:11 UTC, vastradparayya commented on py-utils/src/utils/message_bus/error.py
> +ERR_DEFAULT_ERROR_CODE = 0x1699
When we do not know which error can happen then we are passing this default code and based on passed exception according exception return code is returned.

2021-05-20 17:46 UTC, vastradparayya commented on py-utils/src/utils/errors.py
> +ERR_INVALID_CONFIG = 0x1502
Done

2021-05-20 17:47 UTC, vastradparayya commented on py-utils/src/utils/message_bus/error.py
> +ERR_LEADER_NOT_AVAILABLE = 0x1601
Done. All common errors moved to errors.py

2021-05-20 17:47 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            raise MessageBusError(errno.EINVAL, \
Done

2021-05-20 17:47 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_client.py
> +                "Invalid entry %s.", key)
Done

2021-05-20 17:47 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus.py
> +                "Invalid conf in %s. %s ", self.conf_file, e)
Done

2021-05-20 17:48 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                'Consumer %s is not initialized.', consumer_id)
Done

2021-05-20 17:48 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                'Cant Receive - KeyboardInterrupt')
Done

2021-05-20 17:50 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                        'Cant receive. %s', msg.error())
Done

2021-05-22 06:51 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    'Unable to delete messages for %s.', message_type)
Done

2021-05-22 06:51 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                "Unable to get the message count. %s.", e)
Done

2021-05-22 06:57 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                'Consumer %s is not initialized.', consumer_id)
Done

2021-05-25 09:43 UTC, rahul-tripathi-git requested changes
Please consider the comments as suggestions, use your best judgement.

2021-05-25 09:43 UTC, rahul-tripathi-git commented on py-utils/src/utils/errors.py
> +ERR_MISSING_CONFIG_ENTRY = 0x1502
Can this be changed to errno.ENOKEY ?

2021-05-25 09:43 UTC, rahul-tripathi-git commented on py-utils/src/utils/errors.py
> +ERR_SERVICE_NOT_AVAILABLE = 0x1501
Looks like, it is not used anywhere anymore. this may be removed.

2021-05-25 09:43 UTC, rahul-tripathi-git commented on py-utils/src/utils/errors.py
> +ERR_UNSUPPORTED_VERSION = 0x1503
Please remove all the error codes which are not used anymore.

2021-05-25 11:50 UTC, vastradparayya commented on py-utils/src/utils/errors.py
> +ERR_SERVICE_NOT_AVAILABLE = 0x1501
Yes Rahul, but we have listed possible error code can occur.

2021-05-25 11:51 UTC, vastradparayya commented on py-utils/src/utils/errors.py
> +ERR_MISSING_CONFIG_ENTRY = 0x1502
Done

2021-05-25 11:52 UTC, vastradparayya commented on py-utils/src/utils/errors.py
> +ERR_UNSUPPORTED_VERSION = 0x1503
We have listed possible error code can occur.

2021-05-25 12:34 UTC, rahul-tripathi-git commented on py-utils/src/utils/errors.py
> +ERR_UNSUPPORTED_VERSION = 0x1503
cool.

2021-05-25 12:36 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-05-25 12:46 UTC, vastradparayya commented on py-utils/src/utils/message_bus/error.py
> +ERR_DEFAULT_ERROR_CODE = 0x1699
Done

2021-05-25 13:26 UTC, ujjwalpl requested changes

2021-05-25 13:26 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errors.ERR_UNABLE_TO_LIST_MSG_TYPE, \
```
except KafkaException as e:
    raise MessageBusError(errors.ERR_OP_FAILED, "list_topic() failed. %s. Check if Kafka service is running successfully")
```
Ref: 
https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html
https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.KafkaError

2021-05-25 13:29 UTC, ujjwalpl requested changes

2021-05-25 13:29 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EHOSTDOWN, \
raise MessageBusError(errors.ERR_SERVICE_UNAVAILABLE, "Kafka service(s) unavailable. %s", err)

2021-05-25 13:50 UTC, ujjwalpl requested changes

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            raise MessageBusError(errno.ENOKEY, "Could not find key %s in " +\
raise MessageBusError(errno.ENOENT, ...

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus.py
> +            raise MessageBusError(errno.ENOENT, "Error while parsing " +\
```
except ConfError as e:
    raise MessageBusError(e.rc, ...
```

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.ENOENT, "Consumer %s is not " +\
raise MessageBusError(errors.SERVICE_NOT_INITIALIZED, ...

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    raise MessageBusError(errors.ERR_UNABLE_TO_RECEIVE_MSG, \
raise MessageBusError(errors.ERR_OP_FAILED, "poll(%s) for consumer %s failed to receive message. %s" \
    %(timeout, consumer_id, msg.error())

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.ENOENT, "Consumer %s is not" + \
raise MessageBusError(errors.SERVICE_NOT_INITIALIZED, "consumer %s not initialized"...

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                raise MessageBusError(errors.ERR_UNABLE_TO_GET_MSG_COUNT, \
raise MessageBusError(errors.ERR_OP_FAILED, "command %s failed for consumer group %s. %s.)

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errors.ERR_UNABLE_TO_GET_MSG_COUNT, "Could" +\
This exception is wrongly placed. There is no operation which will throw error.

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    raise MessageBusError(errors.ERR_UNABLE_TO_RESET_OFFSET,\
raise MessageBusError(errors.ERR_OP_FAILED, "Command %s failed for consumer group %s. %s"...

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                        errors.ERR_UNABLE_TO_CHANGE_RETENTION, "Unable to " +\
errors.ERR_OP_FAILED, "alter_configs() for resource %s failed using admin %s for message type %s"

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errors.ERR_UNABLE_TO_FETCH_LOG_SIZE,\
raise MessageBusError(errors.ERR_OP_FAILED, "Command %s failed for message type  %s" (cmd,. ...)

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    raise MessageBusError(
raise MessageBusError(errno.E2BIG, ...

2021-05-25 13:50 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                            errors.ERR_MAX_RETRIES_DELETE_MESSAGE_TYPE, \
raise MessageBusError(errno.ETIMEDOUT, "Timed out after %s retries...

2021-05-25 18:16 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    raise MessageBusError(
Done

2021-05-25 18:16 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errors.ERR_UNABLE_TO_FETCH_LOG_SIZE,\
Done

2021-05-25 18:16 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                        errors.ERR_UNABLE_TO_CHANGE_RETENTION, "Unable to " +\
Done

2021-05-25 18:16 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    raise MessageBusError(errors.ERR_UNABLE_TO_RESET_OFFSET,\
Done

2021-05-25 18:16 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errors.ERR_UNABLE_TO_GET_MSG_COUNT, "Could" +\
Done

2021-05-25 18:17 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                raise MessageBusError(errors.ERR_UNABLE_TO_GET_MSG_COUNT, \
Done

2021-05-25 18:17 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.ENOENT, "Consumer %s is not" + \
Done

2021-05-25 18:17 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    raise MessageBusError(errors.ERR_UNABLE_TO_RECEIVE_MSG, \
Done

2021-05-25 18:17 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.ENOENT, "Consumer %s is not " +\
Done

2021-05-25 18:17 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus.py
> +            raise MessageBusError(errno.ENOENT, "Error while parsing " +\
Done

2021-05-25 18:19 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.EHOSTDOWN, \
Done

2021-05-25 18:19 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errors.ERR_UNABLE_TO_LIST_MSG_TYPE, \
Done

2021-05-26 11:47 UTC, ujjwalpl approved these changes

2021-05-27 02:29 UTC, sachinpunadikar approved these changes
+1

2021-05-27 03:03 UTC, merged