EOS-20462: Adding rsyslog service restart.
Seagate/cortx-utils pull request #286
Opened 2021-05-14 10:18 UTC by udayan-y21

Audit logs and csm logs were not generated as rsyslog wasnt restarts after copying rsyslog config files to /etc/rsyslog.d
Ryslog restart logic added to pyutils and consumed in csm-setup postinstall 

Signed-off-by: Udayan Yaragattikar <udayan.yaragattikar@seagate.com>

2021-05-14 13:23 UTC, kupranay approved these changes

2021-05-14 14:31 UTC, pawankumarsrivastava requested changes

2021-05-14 14:31 UTC, pawankumarsrivastava commented on py-utils/src/utils/rsyslog/rsyslog.py
> +from cortx.utils.validator.v_service import ServiceV
@udayan-y21 Please change the folder name from rsyslog to services. This will be common for all the services. 
Have a base class services which will contain start, stop, restart, reload as the methods. 
Derive rsyslog service and implement the methods.

2021-05-14 15:29 UTC, pawankumarsrivastava commented
@udayan-y21  Please refer this for your changes - https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/utils/service/service_handler.py

2021-05-15 06:55 UTC, udayan-y21 commented on py-utils/src/utils/rsyslog/rsyslog.py
> +from cortx.utils.validator.v_service import ServiceV
okay

2021-05-15 06:55 UTC, udayan-y21 commented
> @udayan-y21 Please refer this for your changes - https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/utils/service/service_handler.py

Okay

2021-05-15 10:00 UTC, udayan-y21 commented on py-utils/src/utils/rsyslog/rsyslog.py
> +from cortx.utils.validator.v_service import ServiceV
Please check latest PR changes

2021-05-15 11:52 UTC, pawankumarsrivastava approved these changes

2021-05-17 06:55 UTC, soniyamoholkar approved these changes

2021-05-17 09:57 UTC, sachinpunadikar approved these changes
+1

2021-05-18 14:35 UTC, merged