EOS-20687: Utils_setup - Create and cleanup cluster.conf
Seagate/cortx-utils pull request #297
Opened 2021-05-19 13:21 UTC by selvakumaar5496

utils_setup config phase creates /etc/cortx/cluster.conf
utils_setup init phase creates relevant message_type
utils_setup cleanup phase removes /etc/cortx/cluster.conf

2021-05-19 13:25 UTC, selvakumaar5496 commented
this includes commits of previous PR's. Hence closing this

2021-05-19 18:44 UTC, rahul-tripathi-git requested changes
Please check if the template file for single-node and multi-node mini-provisioning needs to be updated. If yes, this is a must have.

Please consider all other comments as suggestions, use your best judgement.

2021-05-19 18:44 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        config_files = ['/etc/cortx/message_bus.conf', '/etc/cortx/cluster.conf']
Instead of hardcoding, you may look for all the ".conf" files present in /etc/cortx/
Just a suggestion.

2021-05-19 18:44 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        from cortx.utils.conf_store import Conf
We may move this import to the top as it is being used several times now.
There are 2 more imports in this patch.

2021-05-19 18:44 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        except Exception as e:
simpler shutil.copy can be used instead of SimpleProcess.

2021-05-19 18:44 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        if kafka_server_list is None:
Good catch!

2021-05-19 18:44 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        """ Cleanup all the configs and logs. """
It may be just, "Cleanup configs and logs".
Just a suggestion.

2021-05-20 03:05 UTC, ujjwalpl requested changes

2021-05-20 03:05 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            raise SetupError(errno.EINVAL, "No server info provided")
Message needs to be crystal clear. 
"Could not find server information in %s", conf_url)

2021-05-20 03:05 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        if kafka_server_list is None:
Also error message needs to be crystal clear
"Could not find kafka server information in %s", conf_url)

2021-05-20 03:05 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            admin = MessageBusAdmin(admin_id='create_message_type')
create_message_type doesnt look like admin_id. In general recommended to use better and consistent naming.

2021-05-20 03:05 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        cmd = "/bin/mv /etc/cortx/cluster.conf.new" + \
Why not use python OS os.rename() ? SimpleProcess should not be used for os commands.

2021-05-20 03:05 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        with open(r'/etc/cortx/cluster.conf.new', 'w+') as file:
Why the file name is new ? There should be only two files. 
1. conf.sample
2. actual conf

2021-05-20 04:07 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +            raise SetupError(errno.EINVAL, "No server info provided")
Done

2021-05-20 04:10 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +            admin = MessageBusAdmin(admin_id='create_message_type')
done

2021-05-20 05:06 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        with open(r'/etc/cortx/cluster.conf.new', 'w+') as file:
Done

2021-05-20 05:06 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        cmd = "/bin/mv /etc/cortx/cluster.conf.new" + \
Done

2021-05-20 05:07 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        """ Cleanup all the configs and logs. """
Done

2021-05-20 05:07 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        except Exception as e:
used os.rename

2021-05-20 05:08 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        from cortx.utils.conf_store import Conf
agreee! moved

2021-05-20 05:19 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        config_files = ['/etc/cortx/message_bus.conf', '/etc/cortx/cluster.conf']
Yeah, done.

2021-05-20 16:51 UTC, ujjwalpl approved these changes

2021-05-20 16:51 UTC, ujjwalpl approved these changes

2021-05-21 06:01 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +        config_files = [_config_dir + conf_file for conf_file in \
Why we are creating list of all files like /etc/cortx/*.conf ? This may lead to deleting files created by other components. Stick to the files created by utils.

2021-05-21 06:02 UTC, sachinpunadikar requested changes
Work on the comment

2021-05-21 06:32 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        config_files = [_config_dir + conf_file for conf_file in \
done

2021-05-21 11:22 UTC, rahul-tripathi-git approved these changes
+1

2021-05-24 05:54 UTC, sachinpunadikar approved these changes
+1

2021-05-24 05:55 UTC, sachinpunadikar commented
Please ensure that mini-provisioning is working correctly

2021-05-25 02:44 UTC, merged