EOS-13611 LDR: Encryption / Decryption Logic separated from CORTX
Seagate/cortx-utils pull request #30
Opened 2020-09-30 19:15 UTC by thavanathan

2020-10-01 02:49 UTC, ujjwalpl requested changes

2020-10-01 02:49 UTC, ujjwalpl commented on py-utils/src/utils/security/cipher.py
> +        if os.path.exists('/opt/seagate/cortx/extension/cortxsec'):
If path is used multiple times then better to define it in a variable. So that in case we need to change, we will change only at one place. 
cortxsec_cmd = '/opt/seagate/cortx/extension/cortxsec'

2020-10-01 02:49 UTC, ujjwalpl commented on py-utils/src/utils/security/cipher.py
> +            if strs:
Avoid using if as far as possible. Code can be written like this to avoid if...

getkey_cmd = f'/opt/seagate/cortx/extension/cortxsec getkey {str1} {str2} %s' % ' '.join(strs)

2020-10-01 02:49 UTC, ujjwalpl commented on py-utils/src/utils/security/cipher.py
> +            resp = subprocess.check_output(getkey_cmd.split())
How to handle if command failed ? 

Try following Test scenario
1. cmd path exists. command succeeds
2. cmd path exists. command fails with an error code for wrong key / user
3. cmd path does not exist

2020-10-01 05:22 UTC, cdeshmukh commented on py-utils/src/utils/security/cipher.py
> +        if os.path.exists('/opt/seagate/cortx/extension/cortxsec'):
@ujjwalpl Agree. Also, feel cortxsec should be under bin folder
cortxsec_cmd = '/opt/seagate/cortx/extension/bin/cortxsec'

2020-10-01 05:22 UTC, cdeshmukh commented on py-utils/src/utils/security/cipher.py
> +            resp = subprocess.check_output(getkey_cmd.split())
We also may wanto put this under try exception block, CalledProcessError() would come specifically. Also rc check is must, in addition to o/p

2020-10-01 07:40 UTC, thavanathan commented on py-utils/src/utils/security/cipher.py
> +            resp = subprocess.check_output(getkey_cmd.split())
1. b'oIxZMnOdD9JsVRTBMby_3TYzgHCOIE7wYAgtp0hkRXs='
2. b'error(1): Could not obtain key'
3. b'oIxZMnOdD9JsVRTBMby_3TYzgHCOIE7wYAgtp0hkRXs='

2020-10-01 07:54 UTC, thavanathan commented on py-utils/src/utils/security/cipher.py
> +            resp = subprocess.check_output(getkey_cmd.split())
Done

2020-10-01 08:57 UTC, ujjwalpl requested changes

2020-10-01 08:57 UTC, ujjwalpl commented on py-utils/src/utils/security/cipher.py
> +            resp = subprocess.check_output(getkey_cmd.split())
Why does it print b'xxx'. We should only print the key

2020-10-01 08:57 UTC, ujjwalpl commented on py-utils/src/utils/security/cipher.py
> +        if os.path.exists('/opt/seagate/cortx/extension/cortxsec'):
extension is not a component. It may be split into N different plugins. Hence bin is not suited here. We need to try to keep path optimized. We may not have other folder than bin. So lets keep this as '/opt/seagate/cortx/extension/cortxsec'

2020-10-01 09:03 UTC, thavanathan commented on py-utils/src/utils/security/cipher.py
> +            resp = subprocess.check_output(getkey_cmd.split())
Done

2020-10-01 09:26 UTC, ujjwalpl requested changes

2020-10-01 09:26 UTC, ujjwalpl commented on py-utils/src/utils/security/cipher.py
> +                resp = subprocess.check_output(getkey_cmd.split(), stderr=subprocess.STDOUT)
Need to check the return code (rc) of the process. If process returns code of say 2, then what value is returned by this function ? There is no code to check rc.

2020-10-01 11:59 UTC, cdeshmukh commented on py-utils/src/utils/security/cipher.py
> +        if os.path.exists(cortxsec_cmd):
os.path.isfile() would suit better as we are specifically looking for a file. Above call would work for file or dir also

2020-10-01 11:59 UTC, cdeshmukh commented on py-utils/src/utils/security/cipher.py
> +                resp = subprocess.check_output(getkey_cmd.split(), stderr=subprocess.STDOUT)
process rc is still not validated. Say process invocation went fine but process returned some error code in rc, then error log would be generated currently. We need to propagate error on any rc!=0

2020-10-01 12:42 UTC, ujjwalpl approved these changes

2020-10-01 12:52 UTC, thavanathan commented on py-utils/src/utils/security/cipher.py
> +        if os.path.exists(cortxsec_cmd):
yea. good to have feature. For now I don't see a point of someone creating a directory cortxsec within extension. will address later.

2020-10-01 14:02 UTC, cdeshmukh approved these changes

2020-10-01 17:59 UTC, ujjwalpl approved these changes

2020-10-01 18:23 UTC, s-arya approved these changes
Approved for merge since it has +1 from 2 SMEs

2020-10-02 06:10 UTC, sachinpunadikar approved these changes
+1

2020-10-02 13:50 UTC, merged