Eos 20329 cli framework movement
Seagate/cortx-utils pull request #303
Opened 2021-05-21 06:35 UTC by udayan-y21

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-05-26 05:43 UTC, rahul-tripathi-git requested changes

2021-05-26 05:43 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        Conf.save("conf_index")
A sample file for /etc/cortx/cortx.conf with install_path in it is checked-in along with utils code as a part of another work item.
This method might be removed.

2021-05-26 05:43 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +
Same for this call.

2021-05-26 05:43 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +
Please directly use it like: (pseudo-code)
Conf.load("conf_index", "json:///etc/cortx/cluster.conf")
Conf.get("conf_index", "install_path")

2021-05-26 14:11 UTC, udayan-y21 commented on py-utils/src/setup/utils.py
> +        Conf.save("conf_index")
Okay removed. Please review.

2021-05-26 14:11 UTC, udayan-y21 commented on py-utils/src/setup/utils.py
> +
Removed this part of code. Please review

2021-05-27 13:18 UTC, soniyamoholkar approved these changes

2021-05-27 15:55 UTC, pawankumarsrivastava approved these changes

2021-05-31 09:32 UTC, kupranay approved these changes

2021-05-31 11:07 UTC, kupranay approved these changes

2021-06-01 12:59 UTC, sachinpunadikar approved these changes
Looks okay to me

2021-06-01 12:59 UTC, sachinpunadikar commented
test this please

2021-06-01 13:33 UTC, ujjwalpl requested changes

2021-06-01 13:33 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/command.py
> +    def check_permissions(self, sub_command):
All the internal interfaces must start with _

2021-06-01 13:38 UTC, ujjwalpl requested changes

2021-06-01 13:38 UTC, ujjwalpl commented on py-utils/src/utils/validator/cli_validators.py
> +class CliValidators:
1. Please follow naming conventions of the validator classes. Please refer to the other classes. 
2. Also name should singular.
3. There is nothing about CLI validation in this class. It should be called "FormatV" as its validating format. 
    Interface name should be "validate(format_type)"
4. There is no public interface to this class. There needs to be at least one public interface.

2021-06-01 13:43 UTC, ujjwalpl requested changes

2021-06-01 13:43 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/command.py
> +    def dump_success(output: Any, **kwargs):
return str.

2021-06-01 13:43 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/command_factory.py
> +class ArgumentParser(argparse.ArgumentParser):
This class should be moved with CommandParser class preferably in a separate file called parser.py

2021-06-02 14:25 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/command.py
> +    def dump_success(output: Any, **kwargs):
Modifications done

2021-06-02 14:32 UTC, udayan-y21 commented on py-utils/src/utils/validator/cli_validators.py
> +class CliValidators:
> 1. Please follow naming conventions of the validator classes. Please refer to the other classes.

Done

> 2. Also name should singular. 

Done. 

> 3. There is nothing about CLI validation in this class. It should be called "FormatV" as its validating format.
Interface name should be "validate(format_type)"

Class name changed to FormatV. 
"validate(format_type, args)' --> currently framework is not supporting multiple arguments.
SO kept as `_validate_positive_int(value)` and `_validate_file_format(value)`

> 4. There is no public interface to this class. There needs to be at least one public interface.

Didnt understand, what do you mean "public interface"

2021-06-02 14:33 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/command.py
> +    def check_permissions(self, sub_command):
Modifications done

2021-06-03 07:17 UTC, udayan-y21 commented on py-utils/src/utils/validator/cli_validators.py
> +class CliValidators:
@ujjwalpl Added public interface validate() 
Please review

2021-06-03 08:36 UTC, ujjwalpl requested changes

2021-06-03 08:36 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_format.py
> +    def _validate_positive_int(value):
Remove this. This is a simple one line if condition. You dont need validations. Validations are needed for subsystems.

2021-06-03 12:23 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/terminal.py
> +    def get_current_password(value):
This is called from cortxcli 
```
          "flag": "-cp",
          "dest": "current_password",
          "type": "Terminal.get_current_password",
          "type_target": "cortx.utils.cli_framework.terminal",
          "suppress_help": true,
          "help": "",
```

2021-06-04 06:20 UTC, udayan-y21 commented on py-utils/test/cli_framework/cli_test_data/users.json
> +            "type": "CliValidators._positive_int",
Modifications done

2021-06-04 06:21 UTC, udayan-y21 commented on py-utils/src/utils/validator/v_format.py
> +    def _validate_positive_int(value):
Modifications done

2021-06-04 07:21 UTC, ujjwalpl requested changes

2021-06-04 07:21 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/arg_validate.py
> +from cortx.utils.cli_framework.errors import CliError
Change the file name to arg_type or arg_validator.py

2021-06-04 07:21 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/arg_validate.py
> +
Add description to the every class you declare.

2021-06-04 07:21 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/arg_validate.py
> +from cortx.utils.cli_framework.errors import CliError
license header missing

2021-06-04 07:26 UTC, ujjwalpl requested changes

2021-06-04 07:26 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/parser.py
> +
There should be exactly two blank lines.

2021-06-04 07:26 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/command_factory.py
> +    def edit_arguments(namespace):
This is internal function and must start with _

2021-06-04 07:26 UTC, ujjwalpl commented on py-utils/test/cli_framework/cli_test_data/users_show_table_output
> ++-----------+-----------+---------------------+-----------------------------------+-----------------------------------+
Please rename cli_test_data to test_data. Its already qualified by parent.

2021-06-04 07:28 UTC, ujjwalpl requested changes

2021-06-04 07:28 UTC, ujjwalpl commented on py-utils/test/cli_framework/cli_test_data/users.json
> +            "type": "IntType.validate",
You should only specify type here, i.e. 
    "type": "IntType"

.validate should be suffixed during processing.

2021-06-04 08:01 UTC, udayan-y21 commented on py-utils/test/cli_framework/cli_test_data/users_show_table_output
> ++-----------+-----------+---------------------+-----------------------------------+-----------------------------------+
Modifications done

2021-06-04 08:01 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/command_factory.py
> +    def edit_arguments(namespace):
Modifications done

2021-06-04 08:02 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/parser.py
> +
Modifications done

2021-06-04 08:02 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/arg_validate.py
> +from cortx.utils.cli_framework.errors import CliError
Modifications done

2021-06-04 08:02 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/arg_validate.py
> +
Modifications done

2021-06-04 08:02 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/arg_validate.py
> +from cortx.utils.cli_framework.errors import CliError
Modifications done

2021-06-04 08:11 UTC, udayan-y21 commented on py-utils/test/cli_framework/cli_test_data/users.json
> +            "type": "IntType.validate",
Evalution of `"type"` and `"type_target"` is done in common place in framework code.. as below
```python
                   if each_args.get("type_target"):
                        module_obj = import_module(each_args.pop("type_target"))
                        each_args["type"] = eval(f"module_obj.{each_args['type']}")
                    else:
                        each_args["type"] = eval(each_args["type"])
```
This part of code executes at various place.. some of the examples are: 
```
          "type": "FormatV.validate",
          "type_target": "cortx.utils.validator.v_format",
```
```
          "type": "IntType.validate",
          "type_target": "cortx.utils.cli_framework.arg_validator",
```
```          
          "type": "Terminal.get_password",
          "type_target": "cortx.utils.cli_framework.terminal"
```
So adding class name `(IntType)` to `"type"` will not work...

2021-06-04 08:32 UTC, ujjwalpl requested changes

2021-06-04 08:32 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/arg_validator.py
> +    def validate(self, val):
@staticmethod

2021-06-04 08:32 UTC, ujjwalpl commented on py-utils/test/cli_framework/test_data/users.json
> +            "type": "IntType.validate",
"type": "IntType",

2021-06-04 08:33 UTC, ujjwalpl commented on py-utils/test/cli_framework/cli_test_data/users.json
> +            "type": "IntType.validate",
each_args["type"] = eval(f"module_obj.{each_args['type']}.validate")

2021-06-04 08:35 UTC, udayan-y21 commented on py-utils/test/cli_framework/test_data/users.json
> +            "type": "IntType.validate",
Please check my reply https://github.com/Seagate/cortx-utils/pull/303#discussion_r645379133

2021-06-04 08:42 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/arg_validator.py
> +    def validate(self, val):
Modifications done

2021-06-04 11:42 UTC, ujjwalpl requested changes

2021-06-04 11:42 UTC, ujjwalpl commented on py-utils/test/cli_framework/test_data/users.json
> +            "type": "IntType.validate",
We need to be consistent in the CLI Spec. 
"type": "<Has to be type>"
"validator": "<Has to be validator>"

2021-06-07 15:12 UTC, udayan-y21 commented on py-utils/test/cli_framework/cli_test_data/users.json
> +            "type": "IntType.validate",
@ujjwalpl Modifications done
As per discussion with Pranay and Pawan,
We have decided that Validations will be handled by api for which its called(seperate ticket will be created for that).
As these validations should  be the part of functionality underlying to it and not framework. 
 
CLI-framework will provide
**type**: <defined-data-type, ex: int, str, etc>,
**type_method** : < specific method of class to be executed for that arg>,
**type_target**:< import path of type_method>,


**Basic validations** like ( int is int, str is str, etc) is handled by Argparse library itself
```
Ex:
cortxcli$ users show -o apple
usage: cortxcli.py users show [-h] [-o OFFSET] [-l LIMIT]
                              [-s {user_id,user_type,created_time,updated_time}]
                              [-d {desc,asc}] [-f {table,xml,json}]
Error: Argument -o: invalid int value: 'apple'
cortxcli$
 
cortxcli$ users show -o 1.1
usage: cortxcli.py users show [-h] [-o OFFSET] [-l LIMIT]
                              [-s {user_id,user_type,created_time,updated_time}]
                              [-d {desc,asc}] [-f {table,xml,json}]
Error: Argument -o: invalid int value: '1.1'
```

2021-06-07 15:12 UTC, udayan-y21 commented on py-utils/test/cli_framework/test_data/users.json
> +            "type": "IntType.validate",
Please review

2021-06-08 04:46 UTC, ujjwalpl requested changes

2021-06-08 04:46 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/cli_client.py
> +class DirectClient(Client):
Rename this class to CliClient if this meant for CLI.

2021-06-08 04:51 UTC, ujjwalpl requested changes

2021-06-08 04:51 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/terminal.py
> +            raise CliError(errno.EINVAL, Terminal.EMPTY_PASS_FIELD)
For consistency please replace  EMPTY_PASS_FIELD with actual message. This is the only place where it is used.

2021-06-08 04:54 UTC, ujjwalpl requested changes

2021-06-08 04:54 UTC, ujjwalpl commented on py-utils/src/utils/cli_framework/cli_client.py
> +    def call(self, command):
Merge call and process_request. They are the same thing. Derived classes should implement the same interface.

2021-06-08 05:40 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/cli_client.py
> +    def call(self, command):
Modifications done

2021-06-08 05:41 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/terminal.py
> +            raise CliError(errno.EINVAL, Terminal.EMPTY_PASS_FIELD)
Modifications done

2021-06-08 05:41 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/cli_client.py
> +# CORTX-Py-Utils: CORTX Python common library.
Modifications done

2021-06-08 05:41 UTC, udayan-y21 commented on py-utils/src/utils/cli_framework/cli_client.py
> +class DirectClient(Client):
Modifications done

2021-06-08 06:52 UTC, ujjwalpl approved these changes

2021-06-08 08:10 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-06-08 12:54 UTC, merged