EOS-18899: Rest server for Message Bus using aiohttp
Seagate/cortx-utils pull request #308
Opened 2021-05-24 03:53 UTC by rahul-tripathi-git

# Problem Statement
- Message_Bus rest server

# Design
-  https://seagatetechnology.sharepoint.com/:w:/r/sites/gteamdrv1/tdrive1224/_layouts/15/doc2.aspx?sourcedoc=%7BE1CB4240-87F6-4786-9C8C-2FB51DFAE7F7%7D&file=REST%20interface%20for%20Message%20Bus.docx&action=default&mobileredirect=true

# Coding 
-  Coding conventions are followed and code is consistent [Y]: 
-  Confirm All CODACY errors are resolved [Y]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

Note: Reraised this PR for https://github.com/Seagate/cortx-utils/pull/257

2021-05-24 09:48 UTC, selvakumaar5496 requested changes

2021-05-24 09:48 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                response_obj = {'error_code': status_code, 'exception': ["MessageBusError", {'message' : error_message}]}
"MessageBusError" --> 'MessageBusError'

2021-05-24 09:55 UTC, sachinpunadikar commented on py-utils/setup.py
> +                'cortx.utils.rest_server'
should we call this also "messagebus_server" package ?

2021-05-24 10:05 UTC, sachinpunadikar commented on py-utils/src/utils/rest_server/error.py
> +        ret_code_map['KeyError'] = (418, "Wrong Key in payload!") # wrong key from client
should it be in ' ' instead of " "  ?

2021-05-24 10:34 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +                'cortx.utils.rest_server'
This directory contains implementation just for rest server. This can be reused for any other sub - component in utils.

2021-05-24 10:34 UTC, rahul-tripathi-git commented on py-utils/src/utils/rest_server/error.py
> +        ret_code_map['KeyError'] = (418, "Wrong Key in payload!") # wrong key from client
Done

2021-05-24 10:34 UTC, rahul-tripathi-git commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                response_obj = {'error_code': status_code, 'exception': ["MessageBusError", {'message' : error_message}]}
Done

2021-05-24 17:01 UTC, sachinpunadikar approved these changes
+1

2021-05-24 17:40 UTC, selvakumaar5496 approved these changes

2021-05-25 09:11 UTC, rahul-tripathi-git commented
run vm deployment

2021-05-25 09:50 UTC, sachinpunadikar commented
test this please

2021-05-26 03:17 UTC, sachinpunadikar commented
test this please

2021-05-26 04:24 UTC, merged