EOS-20131: Discovery module interface
Seagate/cortx-utils pull request #310
Opened 2021-05-24 12:13 UTC by mariyappanp

Signed-off-by: MARIYAPPAN PONNUSAMY <mariyappan.ponnusamy@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-05-24 14:43 UTC, sachinpunadikar requested changes
Please fill up the PR template. Without which review is not possible

2021-05-27 05:43 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +class Cmd:
Discovery module will have python interfaces only, CLI commands will be supported by NodeCLI based on DM APIs.

2021-05-27 05:45 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +    def add_args(parser: str, cls: str, name: str):
again commands & arg parsing we dont need and only limit to python APIs

2021-05-27 05:46 UTC, cdeshmukh commented on py-utils/utils-pre-install
> +aiohttp==3.6.1
any extra pkgs we need and if its not covered in cortx-prereqs then we need to raise the list to Ujjwal with justification, and then RE team will add that after approval

2021-05-27 06:29 UTC, mariyappanp commented on py-utils/utils-pre-install
> +aiohttp==3.6.1
Sorry, its because of rebase. That has been removed from cortx-utils.

2021-05-31 05:28 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +    """A common interface of node health generator."""
It will be used for resource map, health & manifest generation

2021-05-31 05:28 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +            "no-cluster>site_001>rack_001>cortx_node_1>sm_001>hw>disks>disk_001"
change these examples to start from cortx node, as discovery will limit to data & config limiting within cortx node only
> cortx_node_1>sm_001>hw>disks>disk_001"

2021-05-31 05:28 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        print(json.dumps(health_info))
no json direct use, need to go through kv store apis, to read any data format like json, xml, yamlt. etc.

2021-05-31 05:28 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health_generator.py
> +class NodeHealthGenerator:
This is where generic interfaces will be put, which will be implemented by SSPL class later !?

2021-05-31 05:28 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        pass
We need to use kvstore apis to return back keys, stating the resource types which will be supported in rpath

2021-05-31 14:31 UTC, sachinpunadikar commented on py-utils/src/utils/discovery/discovery.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-05-31 14:33 UTC, sachinpunadikar commented on py-utils/src/utils/discovery/discovery.py
> +        """This method generates node resource map and health information.
Follow the standard of multi-line comment
"""
My multi-line comment
"""

2021-05-31 14:34 UTC, sachinpunadikar commented on py-utils/src/utils/discovery/discovery.py
> +        """Returns the below status on last node health generation request.
Use multi-line comment example as shown above

2021-05-31 14:38 UTC, sachinpunadikar commented on py-utils/src/utils/discovery/discovery.py
> +        print(json.dumps(health_info))
print is in-appropriate here. You may want to write to a file.
Utils is framework library, hence print should not be used.

2021-05-31 14:41 UTC, sachinpunadikar requested changes
Work on the comments. Commented on first instance only. Review all other places for applicability of these comments.

2021-05-31 19:19 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +class Cmd:
Addressed.

2021-05-31 19:19 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +class Cmd:
Done.

2021-05-31 19:19 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    def add_args(parser: str, cls: str, name: str):
Addressed,
Done.

2021-05-31 19:19 UTC, mariyappanp commented on py-utils/utils-pre-install
> +aiohttp==3.6.1
Done.

2021-05-31 19:19 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    """A common interface of node health generator."""
Done.

2021-05-31 19:20 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +            "no-cluster>site_001>rack_001>cortx_node_1>sm_001>hw>disks>disk_001"
Done.

2021-05-31 19:20 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        print(json.dumps(health_info))
Done.

2021-05-31 19:21 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health_generator.py
> +class NodeHealthGenerator:
Added generic interface and ResourceFactory.

2021-05-31 19:21 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health_generator.py
> +class NodeHealthGenerator:
Done.

2021-05-31 19:22 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        pass
Done.

2021-05-31 19:22 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Done.

2021-05-31 19:22 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        """This method generates node resource map and health information.
Done.

2021-05-31 19:22 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        """Returns the below status on last node health generation request.
Done.

2021-05-31 19:25 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        print(json.dumps(health_info))
This is the ask if I'm not wrong.
node_cli requires DiscoveryModule (DM) to expose show_resource_map interface. Hence used print statement.

However, I changed the interface to get_resource_map() and removed print statement.
cc: @cdeshmukh

2021-06-01 07:13 UTC, ujjwalpl requested changes

2021-06-01 07:13 UTC, ujjwalpl commented on py-utils/src/utils/discovery/resource_map.py
> +    def load():
Call this method as init(). It should take the URL for storing the resource information.

2021-06-01 07:13 UTC, ujjwalpl commented on py-utils/src/utils/discovery/resource_map.py
> +            ResourceMap._conf.load(ResourceMap.index, ResourceMap.url)
Use KV Store instead of conf store. 
Refer to this as example: https://github.com/Seagate/cortx-utils/compare/task

2021-06-01 07:13 UTC, ujjwalpl commented on py-utils/src/utils/discovery/resource_map.py
> +data_file = os.path.join(os.path.dirname(script_path), "node_health_info.json")
Need to avoid global and hard coded path in the utils. It comes from the component above.

2021-06-01 07:31 UTC, ujjwalpl requested changes

2021-06-01 07:31 UTC, ujjwalpl commented on py-utils/src/utils/discovery/resource_collection.py
> +class Disks:
Declare a common base class named "Resource". All classes needs to be derived from that.

2021-06-01 07:31 UTC, ujjwalpl commented on py-utils/src/utils/discovery/resource_collection.py
> +class Hardware(Disks, Psus):
Hardware contains Disks and PSUs. They themselves are Disks/PSUs.
Please adhere to "is_a" and "has_a" relationship between the classes. 

Maruti Car is a Car - is_a
Car has 4 tyres - has_a

``` 
class Resource: 
     init(instances = 1, child_resources[] = None):
        ....

class Disk(Resource):
    init(instances): 
        super.init(instances)
    
class Psu(Resource):
    init(instances): 
        super.init(instances)

class Storage(Resource): 
    init(child_resources[]): 
        super.init(1, child_resources)

class Compute(Resource): 
    init(child_resources[]): 
        super.init(1, child_resources)

class Network(Resource): 
    init(child_resources[]): 
        super.init(1, child_resources)

class Node(Resource):
    init(compute, storage, network):

```

2021-06-01 07:37 UTC, ujjwalpl requested changes

2021-06-01 07:37 UTC, ujjwalpl commented on py-utils/src/utils/discovery/node_health_generator.py
> +    def get_instance(rpath):
This interface should return instance or class Resource or the ResourceMap. Not the ResourceFactory itself.

2021-06-01 07:37 UTC, ujjwalpl commented on py-utils/src/utils/discovery/node_health_generator.py
> +class NodeHealthGenerator:
Please rename this class as "NodeHealth" or "SystemHealth" to be more generic. generate() and refresh() should be interfaces. Verb should preferably in the interfaces and class names to be preferably noun.

2021-06-01 07:37 UTC, ujjwalpl commented on py-utils/src/utils/discovery/error.py
> +class DiscoveryError(Exception):
Derive this from BaseError.

2021-06-01 10:19 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health_generator.py
> +    def get_instance(rpath):
get_instance() is not returning ResourceFactory, but its returning instance of resource class.
`
        # Get corresponding class instance
        from cortx.utils.discovery import resource_collection
        resources = inspect.getmembers(resource_collection, inspect.isclass)
        for _, cls in resources:
            if hasattr(cls, 'name') and leaf_node == cls.name:
                ResourceFactory._resources[rpath] = cls(leaf_node, rpath)
                return ResourceFactory._resources[rpath]
`
Let me know if there is a gap.

2021-06-03 07:25 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource_map.py
> +    def load():
Done.

2021-06-03 07:25 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource_map.py
> +            ResourceMap._conf.load(ResourceMap.index, ResourceMap.url)
Done.

2021-06-03 07:26 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource_collection.py
> +class Disks:
Done.

2021-06-03 07:27 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health_generator.py
> +    def get_instance(rpath):
Done.

2021-06-03 07:27 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health_generator.py
> +class NodeHealthGenerator:
Done.

2021-06-03 07:27 UTC, mariyappanp commented on py-utils/src/utils/discovery/error.py
> +class DiscoveryError(Exception):
Done.

2021-06-03 10:12 UTC, cdeshmukh reviewed
Review still in progress. Am still not getting enough time to finish it becoz of meetings

2021-06-03 10:59 UTC, satish-seagate commented on py-utils/src/utils/discovery/node_health.py
> +    GEN_MARKER = "/tmp/dm_inprogress"
avoid /tmp location. use /var/cortx/... if possible.

2021-06-06 19:12 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm/storage.py
> +        self.__passwd = "!manage"
@cdeshmukh, Need your opinion on how to get storage controller inputs?
If I keep this file under SSPL repo, it can serve the need. But SSPL must be provisioned to feed these input values.

2021-06-07 03:14 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm/storage.py
> +        self.__passwd = "!manage"
I think, we need to lookup provisioner config supplied during cortx-utils setup.

2021-06-07 06:52 UTC, cdeshmukh requested changes
As discussed, this PR needs to have a mock module which would serve mocked health data to DM interfaces as of today, until backend SSPL code is ready, so DM interfaces can be consumed by NodeCLI soon enough

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +        res = re.search(r"(\w+)\[([\d]+)\]|(\w+)", node)
Can you add example of string which this trying to parse

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +        return node, inst
what node detailed being seeked..

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +        os.removedirs(NodeHealth.GEN_MARKER)
Need to be careful to remove the marker file in case of error too, like under exception handling

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +            # Parse rpath and find left node
what this function is doing? And also any logic to get health data should be there in backend component only

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +    def get_health_info(self):
Ok got now why you have generic name get_health_info()  in Storage & server class, which is fine.

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +    def set(key: str, value: str):
set() not needed by DM i believe, do you have any usecase ? 

But yes if / when HA plans to use this class, then it may need to update resource state based on alerts it receives.

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +            ['psus[0]>type[0]', 'psus[0]>type[1]', 'psus>[1]>>test', 'disks>id']
Am little confused, within a rpath related to PSU, why disk data will be seen ? This function is giving leaf node keys basically as i see

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +        """Returns instance of ResourceFactory for given rpath"""
>  """Returns instance of ResourceFactory for given rpath"""

How a resource  class instance can be limited by rpath?

Can you add some examples

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +                ResourceFactory._resources[rpath]["instance"] = cls
Not clear, explain with example plz

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource_collection.py
> +class Resource:
As discussed, we cant have Resource class again here. It needs to be referred from resource.py

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource_collection.py
> +def module_from_file(module_name, file_path):
This helps with dynamic module import as i understand, can you add function description plz. Though i dont see anything using it still.
get_health_provider_module() imports module dynamically based on config i/p, then why this is needed?

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource_collection.py
> +    def child_resource(self):
any exclusive functions here can move to Resource class in resource.py

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource_collection.py
> +                info = cls().get_health_info(rid)
great!!

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/test/test_discovery/test_discovery.py
> +            status, ["Ready", "Success"], "DM inprogress unexpectedly.")
>DM inprogress unexpectedly

Should be just In-progress ? Also 'Failed' status needs to be there

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/test/test_discovery/test_discovery.py
> +            status, "Success", "Failed to generate node health")
> "Failed to generate node health"

why not just 'Failed' ?

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/test/test_discovery/test_discovery.py
> +            "Health information not fouhd for given rpath.")
Type in statement here.
Also not checking for 'ok' health status here !?

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/test/test_discovery/test_discovery.py
> +        self.assertTrue(
Not enough asserts?

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +    def get_node_health(rpath: str = None):
As discussed, this will just return URL to backend where data will be available. So consumer can start reading that with half available data and do needed filtering. rpath filter here wont help if when we need to give backend URL

2021-06-07 06:52 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +    def get_resource_map(rpath: str = None, delim: str = ">"):
This function can be commented for now, as it doesnt good anymore given get_node_health() plans to give backend URL and consumer can apply / extract data as needed, including resource map here

2021-06-07 14:37 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource_collection.py
> +class Hardware(Disks, Psus):
Done

2021-06-07 14:38 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health_generator.py
> +    def get_instance(rpath):
Addressed in new commit.

2021-06-07 14:39 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    A common interface of Discovery Module(DM). This will be used for
Done.

2021-06-07 14:39 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        Health information will be stored in Fs and therefore it fetches
Done.

2021-06-07 14:39 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +            return "Failed - Node health generator is busy in processing "\
Done.

2021-06-07 14:42 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        self.health_gen = NodeHealthGenerator()
As per recent changes, __init__() method of NodeHealth is having variable initialization only.
So ignoring error handling.

2021-06-07 14:45 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +    GEN_MARKER = "/tmp/dm_inprogress"
GEN_MARKER is removed now. In worst situation like, system restart the file will exist after restart and still Node generator will think request is in-progress and so new request won't be allowed.
Recent commit overcomes this issue. Now NodeHealth.STATUS is handling this.

2021-06-07 14:46 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm/storage.py
> +        self.__passwd = "!manage"
Sure, removed this class files from DM.

2021-06-07 14:47 UTC, mariyappanp commented on py-utils/test/test_discovery/conf_sample.json
> +          "last_fetched": "Wed May 19 16:53:02 2021",
Done.

2021-06-07 14:47 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm/storage.py
> +
Done.

2021-06-07 14:47 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm/storage.py
> +    URI_CLIAPI_LOGIN = "/login/"
Added mock module and data. Removed this class file.

2021-06-07 14:50 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm/storage.py
> +    def get_health_info(self, rid):
Scope:
https://github.com/Seagate/cortx-utils/pull/310#discussion_r646300648

2021-06-07 14:50 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm/storage.py
> +    def build_controllers_cache(self):
Removed this file and this will be put in SSPL later as planned.

2021-06-07 14:50 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm/webservices.py
> +
Removed this file and this will be put in SSPL later as planned.

2021-06-07 14:51 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm_config.ini
> +[HEALTH_PROVIDER]
Changed to 'yaml' format.
Done.

2021-06-07 14:51 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm_config.ini
> +    storage: dm
Done.

2021-06-07 14:51 UTC, mariyappanp commented on py-utils/test/test_discovery/conf_sample.json
> +{
Done.

2021-06-07 14:52 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +    GEN_MARKER = "/var/cortx/dm/dm_inprogress"
https://github.com/Seagate/cortx-utils/pull/310#discussion_r646656750

2021-06-07 14:53 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +        res = re.search(r"(\w+)\[([\d]+)\]|(\w+)", node)
Done. Basically to split the string and find node and its instance.
```
    @staticmethod
    def get_node_details(node):
        """
        Parse node information and returns left string and instance.
        Example
            "storage"    -> ("storage", "*")
            "storage[0]" -> ("storage", "0")
        """
```

2021-06-07 14:56 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +        return node, inst
nodes are from rpath.
rpath = "nodes[0]>storage[0]>hw>Disks"
Then we parse it and find nodes for validating the rpath meet resource health schema.
We iterate one by one and create resource instance on it.

2021-06-07 14:57 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +        os.removedirs(NodeHealth.GEN_MARKER)
https://github.com/Seagate/cortx-utils/pull/310#discussion_r646656750

2021-06-07 15:01 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +            # Parse rpath and find left node
The generate logic is not here. 
This is just validating parent and child node for following health schema structure.
This will get health information from resources after backend component call and updated health map.

2021-06-07 15:01 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
> +    def get_health_info(self):
Yeah.

2021-06-07 15:03 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
> +    def set(key: str, value: str):
Ref: node_health.py
Once health information from backend component is collected, we call this interface to update health map.
```
            Resource.set(rpath, info)
```

2021-06-07 15:06 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
> +            ['psus[0]>type[0]', 'psus[0]>type[1]', 'psus>[1]>>test', 'disks>id']
This method is now not required as we commented Dscovery.get_resource_map() method.
Traverse through dictionary is to find leaf node.
For example I kept psu and disk in this dict. Obviously traversing dict of "nodes[0]>compute[0]>hw" dict will be like this.

2021-06-07 15:08 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
> +        """Returns instance of ResourceFactory for given rpath"""
Added the purpose in docstring now.
```
    @staticmethod
    def get_instance(node: str, rpath: str) -> Resource:
        """
        Returns instance of ResourceFactory for given rpath.

        Created cls instance will be reused if generate node
        health is called for same rpath again.
        """
```

2021-06-07 15:09 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
> +        """Returns instance of ResourceFactory for given rpath"""
Its all about saving system memory by reusing class resources.

2021-06-07 15:09 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource_collection.py
> +class Resource:
Done.

2021-06-07 15:11 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource_collection.py
> +def module_from_file(module_name, file_path):
I missed to use absolute path of health provider.
Now dm_config.yaml is updated as planned and removed this method.

2021-06-07 15:13 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource_collection.py
> +    def child_resource(self):
Specific to childs of the node.
I will think about it again.

2021-06-07 15:16 UTC, mariyappanp commented on py-utils/test/test_discovery/test_discovery.py
> +            status, "Success", "Failed to generate node health")
Done.

2021-06-07 15:18 UTC, mariyappanp commented on py-utils/test/test_discovery/test_discovery.py
> +            "Health information not fouhd for given rpath.")
As planned, now get_node_health() is returning backend URL. So we could validate the url is valid only.
Ref new commit.
```
    def test_get_node_health(self):
        """Check for fetching node health backend URL"""
        url = discovery.get_node_health()
        self.assertEqual(url, NodeHealth.URL,
            "Node health backend url is invalid.")
```

2021-06-07 15:20 UTC, mariyappanp commented on py-utils/test/test_discovery/test_discovery.py
> +        self.assertTrue(
Removed this test as per the discussion on below required APIs.

Discovery.generate_node_health()
Discovery.get_gen_node_health_status()
Discovery.get_node_health()

2021-06-07 15:20 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    def get_node_health(rpath: str = None):
Done.

2021-06-07 15:20 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    def get_resource_map(rpath: str = None, delim: str = ">"):
Done.

2021-06-07 17:07 UTC, cdeshmukh approved these changes

2021-06-07 17:07 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +            ['psus[0]>type[0]', 'psus[0]>type[1]', 'psus>[1]>>test', 'disks>id']
alright. examples helping here too

2021-06-08 04:49 UTC, cdeshmukh commented on py-utils/src/utils/discovery/dm_config.yaml
> +    storage: /usr/lib/python3.6/site-packages/cortx/utils/discovery/mocked_health_gen
@mariyappanp as discussed, packages under site-packages may not need absolute path, so we can try with relative path for these.

2021-06-08 05:13 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        gen_status = self.get_gen_node_health_status()
>Request acceptance status - success (accepted) / failed (denied)

This api should just return success or or failed, not in-progress, as status is about whether request accepted or not.

2021-06-08 07:01 UTC, ujjwalpl requested changes

2021-06-08 07:01 UTC, ujjwalpl commented on py-utils/src/utils/discovery/discovery.py
> +    # @staticmethod
Remove commented code if not required.

2021-06-08 07:01 UTC, ujjwalpl commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.URL
We shouldnt be returning a hard coded URL. URL can be contrusted from ID. e.g. 
json://<fixed_location>/health/<id>.yaml

2021-06-08 07:04 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        return gen_status
ID is needed when we support multiple health collection requests with different rpath. This we decided to keep as future enhancement, to keep current implementation simple & allow just one health request at a time.

2021-06-08 07:06 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +    def get_gen_node_health_status(self):
same as comment on line 46

2021-06-08 07:07 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.URL
where is the ID in this example. Also, using ID per health request is not planned in current design

2021-06-08 08:39 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    # @staticmethod
Done.

2021-06-08 08:39 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +            return "Failed - Node health generation is in-progress " \
Done.

2021-06-08 08:42 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        gen_status = self.get_gen_node_health_status()
generate_node_health()  --> Returns "Success" or "Failed(with reason)" status upon request
get_gen_node_health_status() --> Returns node health scanning status "Ready", "In-progress", "Success", "Failed"

2021-06-08 08:53 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm_config.yaml
> +    storage: /usr/lib/python3.6/site-packages/cortx/utils/discovery/mocked_health_gen
Then we need to handle the path before importing the module.
Like,
```
if path.startswith("/"):
      # import absolute path
else:
      # import relative path
```
Fine?

2021-06-08 09:24 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm_config.yaml
> +    storage: /usr/lib/python3.6/site-packages/cortx/utils/discovery/mocked_health_gen
Done. Please review.

2021-06-08 10:31 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +            return "Failed - Node health generation is in-progress " \
Its a status string.
@cdeshmukh, do we need to raise the error on request denial?

2021-06-09 07:31 UTC, cdeshmukh commented
@mariyappanp as told yday, am not getting option to resolve comments for this PR for some reason (@mukul-seagate11 , can you please check & suggest), so feel free to resolve comments i initiated here

2021-06-09 08:00 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +    GEN_MARKER = "/tmp/dm_inprogress"
Ack.

2021-06-10 14:25 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        return gen_status
@mariyappanp is working on return request ID, even when we are going to support single request execution at a time, so interface response doesnt change later, when DM support multiple requests with different rpaths

2021-06-10 14:25 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.URL
yes, will be addressed

2021-06-11 04:01 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.URL
Done

2021-06-11 04:01 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    def get_gen_node_health_status(self):
Done.

2021-06-11 04:01 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        return gen_status
Done.

2021-06-11 04:02 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +            return "Failed - Node health generation is in-progress " \
Done. It will throw exception.

2021-06-11 05:47 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.URL
Guess there is some mis-understanding @ujjwalpl, we cant have separate backend health data maintained separately per request ID, and so the static backend health file URL. Health data will be updated in same backend file from different requests and consumers will filter & use the data as needed !

2021-06-11 07:24 UTC, sachinpunadikar commented on py-utils/src/utils/discovery/discovery.py
> +                os.removedirs(NodeHealth.GEN_MARKER)
Shouldn't it be try block ?

2021-06-11 07:35 UTC, sachinpunadikar requested changes
Check if we need to add os related calls/actions in try block

2021-06-11 08:14 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +                os.removedirs(NodeHealth.GEN_MARKER)
If that directory can not be deleted, we expect the raw error thrown by itself. So no special handling added on this.

2021-06-11 12:35 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.URL
Discovery.get_node_health(rpath) --> This will provide backend URL for the given rpath.
After the discussion, we decided to generate resource map per rpath and not by request ID.
So backend URL won't have request ID as we proceed with rpath. But still backend URL will be dynamic at rpath level.

2021-06-11 17:36 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.URL
@cdeshmukh, how to maintain unique backend url per rpath? Can you provide url format?

2021-06-14 05:30 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +            last_reboot = int(psutil.boot_time())
Any stale marker older than half an hour should be removed, as discovery code not supposed to take that much time anyways. So better to clean it up

2021-06-14 05:30 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +                os.removedirs(NodeHealth.GEN_MARKER)
If removedirs() raises an exception, its not being catched explicitly, means its not getting handled gracefully. Better to have try-exception block & then raise the Discovery error.

>GEN_MARKER = "/var/cortx/dm/dm_genhealth_inprogress"

Also os.rmdir() is what we need i believe, given removedirs() tries to remove parent directories too if they are empty, which we dont intend to do here. In rare case where parent dirs are empty, they would get deleted too, which is bound to create bigger problems then.

os.removedirs(name)
>Remove directories recursively. Works like rmdir() except that, if the leaf directory is successfully removed, removedirs() tries to successively remove every parent directory mentioned in path until an error is raised (which is ignored, because it generally means that a parent directory is not empty). For example, os.removedirs('foo/bar/baz') will first remove the directory 'foo/bar/baz', and then remove 'foo/bar' and 'foo' if they are empty. Raises OSError if the leaf directory could not be successfully removed.

2021-06-14 05:30 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        request_id = str(time.time()).replace(".", "")
Will we able to recreate the timestamp if we remove the dot? We need the ability to do that so if manually we want to get the request time, we should be able to just feed that to time converter and figure out

2021-06-14 09:19 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        request_id = str(time.time()).replace(".", "")
This is just for unique request id. This won't be used for time reference.
Request time we map to request during node health generation. 
node_health.py
```
    @staticmethod
    def add_dm_request(rpath, req_id, url):
        """Updates new request information"""
        Conf.set(dm_requests, "%s>rpath" % req_id, rpath)
        Conf.set(dm_requests, "%s>status" % req_id, NodeHealth.INPROGRESS)
        Conf.set(dm_requests, "%s>url" % req_id, url)
        Conf.set(dm_requests, "%s>time" % req_id, int(time.time()))
        Conf.save(dm_requests)
```

2021-06-14 09:21 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        print(json.dumps(health_info))
This line is removed now as we are returning only backend URL.

2021-06-14 09:24 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource_map.py
> +data_file = os.path.join(os.path.dirname(script_path), "node_health_info.json")
Okay, backend_url from discovery.generate_node_health() will be used for updating resource map.
As per today's discussion, this will be planned in upcoming sprint.
Optional param is added for that.
`generate_node_health(rpath: str = None, backend_url: str = None)`

2021-06-14 09:28 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.URL
Done in new commit, backend URL will have request_id added  in the name.
```
>>> Discovery.get_node_health(16236628453910334)
'json:///var/cortx/dm/resource_map/node_health_info_16236628453910334.json'
```

2021-06-14 09:30 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +                os.removedirs(NodeHealth.GEN_MARKER)
Request blocking is removed as the current implementation will allow multiple request at a time.
So this GEN_MARKER directory creation and removal steps are removed.

2021-06-14 09:34 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +            last_reboot = int(psutil.boot_time())
GEN_MARKER is removed as DM is capable of processing multiple requests.

2021-06-14 13:31 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        request_id = str(time.time()).replace(".", "")
No request time not in data, but for debugging i meant to extract request time from id itself, can get helpful to map last_updated field with request time (id)
Its not a must, future PR we can think of improving

2021-06-14 13:31 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +        Otherwise Node Health scan status is "Ready" or "Success".
Success or Failed status ... nothing like Ready DM will give back

2021-06-14 13:31 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +        status = Conf.get(dm_requests, "%s>status" % req_id)
We should really explore in future to use kvstore apis instead of confstore, as we are not dealing with conf here. I know you had told functionality we need same, so we will be duplicating code from confstore, if we have to do same data handling. Keep a TODO for now

2021-06-14 13:31 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +            if (last_reboot > req_start_time) and status is NodeHealth.INPROGRESS:
keep in-progress request time max as half an hour or else marked failed. In worst case, thread which is responsible for updating health data may hang or raise exception, where this request status should get updated

2021-06-14 19:00 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        request_id = str(time.time()).replace(".", "")
Sure. Noted.

2021-06-14 19:01 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +store_type = "json"
Done.

2021-06-14 19:07 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +dm_requests = "dm_requests"
Addressed and avoided this name on vars.

Dicovery class <-- NodeHealth map class <-- Resource class
Loading DM config in Discovery and importing it in other classes brings cyclic dependency issue.
Since NodeHealth is where we register/handle any request, dm_config is required to load here. So that config gives store_type, store path and so on.

2021-06-14 19:08 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +        json.dump({}, f, indent=2)
Addressed.
Now used kv_store to replace these.

2021-06-14 19:09 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +        Conf.set(dm_requests, "%s>rpath" % req_id, rpath)
Syntax: `Conf.set(index, key, value)`
Now kv_store is introduced in recent commit.

2021-06-14 19:09 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +        Otherwise Node Health scan status is "Ready" or "Success".
Addressed.

2021-06-14 19:10 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +        status = Conf.get(dm_requests, "%s>status" % req_id)
New commit replaced this by kv_store.
Done.

2021-06-14 19:10 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +            if (last_reboot > req_start_time) and status is NodeHealth.INPROGRESS:
Done.

2021-06-15 02:56 UTC, sachinpunadikar commented on py-utils/src/utils/discovery/discovery.py
> +        if backend_url:
Please add TODO for backend_url. What you are going to do with backend_url in future
This will help understand the use of backend_url in the passed in parameters.

2021-06-15 03:45 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        if backend_url:
Done.

2021-06-15 08:06 UTC, cdeshmukh approved these changes

2021-06-15 08:06 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        request_id = str(time.time()).replace(".", "")
Guess we can just do it manually, pickup whole timestamp from here, and we just need to know the position (6th from left ?) to put the decimal & then its ready to be converted to required timezone time value. So no need to change anything in code atleast

2021-06-15 08:29 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    """Common interfaces of Discovery Module(DM)"""
Sure, I checked across this package. This is the only place needed modification.

2021-06-15 08:30 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    """Common interfaces of Discovery Module(DM)"""
Done

2021-06-15 08:34 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        request_id = str(time.time()).replace(".", "")
Okay

2021-06-15 09:12 UTC, sachinpunadikar approved these changes
+1

2021-06-15 11:50 UTC, ujjwalpl commented on py-utils/src/utils/discovery/resource_map.py
> +data_file = os.path.join(os.path.dirname(script_path), "node_health_info.json")
Please add a #todo

2021-06-15 11:57 UTC, ujjwalpl requested changes

2021-06-15 11:57 UTC, ujjwalpl commented on py-utils/src/utils/discovery/mocked_health_gen/mocked_health_gen.py
> +#!/bin/python3
Please move this code to test folder as per convention.

2021-06-15 11:57 UTC, ujjwalpl commented on py-utils/src/utils/discovery/dm_config.yaml
> +HEALTH_PROVIDER:
There is a common cortx.conf and these information should be moved to that file. It is ok to do in next sprint however this MUST be done. We need to avoid many config files.

2021-06-15 11:57 UTC, ujjwalpl commented on py-utils/src/utils/discovery/dm_config.yaml
> +REQUEST_REGISTER:
Use small letters as per convention used on the cortx.conf to make it easy to move

2021-06-15 11:57 UTC, ujjwalpl commented on py-utils/src/utils/discovery/dm_config.yaml
> +RESOURCE_MAP:
Its better to have one common config i.e. and use the same for health and resources as they are all related. 
resource: 
     location: /var/cortx/resources/

2021-06-15 11:57 UTC, ujjwalpl commented on py-utils/src/utils/discovery/dm_config.yaml
> +    server: cortx/utils/discovery/mocked_health_gen
Why mocked ? We should not have anything mocked in the production code.

2021-06-15 11:58 UTC, ujjwalpl requested changes

2021-06-15 11:58 UTC, ujjwalpl commented on py-utils/src/utils/const.py
> +DM_RESOURCE_MAP_PATH = "/var/cortx/dm/resource_map/"
This is hard code and also in the conf file. why two places ? Use one place.

2021-06-15 12:04 UTC, cdeshmukh commented on py-utils/src/utils/discovery/dm_config.yaml
> +    server: cortx/utils/discovery/mocked_health_gen
This PR is to mainly unblock NodeCLI, making interfaces available and since backend health data collection code not fully ready, this mocked data was discussed and added. In coming PRs it will be replaced with SSPL backend

2021-06-15 14:48 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm_config.yaml
> +HEALTH_PROVIDER:
Moved to cortx.conf.
Done

2021-06-15 14:49 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm_config.yaml
> +REQUEST_REGISTER:
These are moved to cortx.conf

2021-06-15 14:49 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm_config.yaml
> +RESOURCE_MAP:
Addressed. 
Please review cortx.conf

2021-06-15 14:56 UTC, mariyappanp commented on py-utils/src/utils/discovery/mocked_health_gen/mocked_health_gen.py
> +#!/bin/python3
This is not for test purpose.
Reason is mentioned in  https://github.com/Seagate/cortx-utils/pull/310#discussion_r651722581

2021-06-15 14:58 UTC, mariyappanp commented
Testing is not done yet since prerequisites like cortx-prereq and cortx-py-utils RPM installation is failing.

2021-06-15 15:59 UTC, cdeshmukh commented on py-utils/src/utils/discovery/dm_config.yaml
> +# CORTX-PY-UTILS: CORTX common utility code
Do we need this file now, given all conf moved to cortx.conf

2021-06-15 16:08 UTC, cdeshmukh commented on py-utils/src/utils/discovery/mocked_health_gen/mocked_health_gen.py
> +#!/bin/python3
@ujjwalpl  its not test code, its one of the backend module serving the health data. its different story that its giving mocked data, to serve our purpose of integration.

2021-06-15 16:11 UTC, ujjwalpl commented on py-utils/src/utils/discovery/dm_config.yaml
> +    server: cortx/utils/discovery/mocked_health_gen
We should not calling it mock. Call with actual names. Mock is confusing.

2021-06-15 16:11 UTC, mariyappanp commented on py-utils/src/utils/const.py
> +DM_RESOURCE_MAP_PATH = "/var/cortx/dm/resource_map/"
Done.

2021-06-15 16:15 UTC, cdeshmukh commented on py-utils/src/utils/discovery/dm_config.yaml
> +    server: cortx/utils/discovery/mocked_health_gen
Actual name? This is static data we are serving, to help Node CLI understand how response will look like, until whole SSPL backend is ready to serve actual data

2021-06-15 16:15 UTC, ujjwalpl commented on py-utils/src/utils/discovery/mocked_health_gen/mocked_health_gen.py
> +#!/bin/python3
We should not be adding mock / throwable code. Unimplemented and throw away code are different.

2021-06-15 16:23 UTC, ujjwalpl requested changes

2021-06-15 16:23 UTC, ujjwalpl commented on py-utils/src/utils/discovery/dm_config.yaml
> +# CORTX-PY-UTILS: CORTX common utility code
Not used anywhere. Needs to be removed from the patch.

2021-06-15 16:23 UTC, ujjwalpl commented on py-utils/src/utils/discovery/mocked_health_gen/mocked_health_gen.py
> +#!/bin/python3
Lets remove in the next sprint and have this in a way that there is no dummy required. Absence trigger default behavior.

2021-06-15 16:23 UTC, ujjwalpl approved these changes

2021-06-15 18:16 UTC, mariyappanp commented on jenkins/build.sh
> +INSTALL_PATH=$(grep install_path cortx.conf.sample |  cut -d " " -f 4 | sed -e 's/^"//' -e 's/",$//')
@sachinpunadikar, this is newly added in recent commit.
install_path was invalid after adding some entries in cortx.conf.sample. That caused RPM installation failure.
This resolved the problem.

2021-06-15 18:19 UTC, mariyappanp commented on py-utils/src/utils/discovery/mocked_health_gen/mocked_health_gen.py
> +#!/bin/python3
Okay.
In addition to this, mock data reference will be removed from package and data_files in setup.py.
@sachinpunadikar @cdeshmukh @ujjwalpl

2021-06-15 18:21 UTC, mariyappanp commented on py-utils/src/utils/discovery/dm_config.yaml
> +# CORTX-PY-UTILS: CORTX common utility code
Done.

2021-06-15 18:32 UTC, mariyappanp commented
Testing completed.
```
[740517 2021-06-15 discovery]$ sudo python3 test_discovery.py  -v
test_generate_node_health (__main__.TestDiscovery)
Check for immediate request id ... ok
test_generate_node_health_on_invalid_rpath (__main__.TestDiscovery)
Check for failed status on invalid rpath ... ok
test_get_gen_node_health_status_success (__main__.TestDiscovery)
Check for node health status using valid request_id ... ok
test_get_gen_node_health_status_with_invalid_id (__main__.TestDiscovery)
Check for node health status with invalid request id ... ok
test_get_node_health (__main__.TestDiscovery)
Check for generated recource map location ... ok
test_get_node_health_with_invalid_id (__main__.TestDiscovery)
Check for node health backend url with invalid id ... ok

----------------------------------------------------------------------
Ran 6 tests in 2.056s
```

2021-06-16 03:01 UTC, cdeshmukh approved these changes

2021-06-16 11:06 UTC, ujjwalpl approved these changes

2021-06-16 14:17 UTC, merged