Rest setup
Seagate/cortx-utils pull request #313
Opened 2021-05-25 11:57 UTC by selvakumaar5496

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-05-25 12:24 UTC, rahul-tripathi-git requested changes

2021-05-25 12:24 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        except OSError as e:
If service is not available, there will not be any OSError, Hence in this case we might need to use simpleprocess.

2021-05-25 12:24 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        except OSError as e:
Same applies here, we might need to check return code.

2021-05-25 12:43 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        except OSError as e:
again checking rc value. Please check below

2021-05-25 12:50 UTC, ujjwalpl requested changes

2021-05-25 12:50 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        if rc != 0:
os.system('command') returns a 16 bit number, which first 8 bits from left(lsb) talks about signal used by os to close the command, Next 8 bits talks about return code of command. rc cant be compared with 0. You need to obtain high order 8 bits, from rc. 

```
>>> rc = os.system("ls /dfsfds")
ls: cannot access /dfsfds: No such file or directory
>>> print(rc)
512
>>> print(rc>>8)
2
```

2021-05-25 12:50 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        if rc != 0:
Same here

2021-05-25 13:54 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        if rc != 0:
done

2021-05-25 13:54 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        if rc != 0:
Done

2021-05-25 14:13 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        except OSError as e:
again checking rc value. Please check below

2021-05-26 17:12 UTC, ujjwalpl requested changes

2021-05-26 17:12 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        try:
systemctl requires root privileges. Please add a check somewehere in the validate that root privilege is present.

2021-05-26 17:12 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        except OSError as e:
os.system is incorrect logic. It does not throw exception. 

```
>>> try:
...     rc = os.system("systemctl start xxx")
... except:
...     print("exception")
...
Failed to start xxx.service: Unit not found.
>>>
```

2021-05-26 19:12 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        try:
running as root

2021-05-26 19:13 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        except OSError as e:
used SimpleProcess

2021-05-27 15:05 UTC, ujjwalpl requested changes

2021-05-27 15:05 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        try:
We need to add a check in case someone runs it as non root user.

2021-05-27 15:18 UTC, ujjwalpl requested changes

2021-05-27 15:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +                raise SetupError(res_rc, "Unable to start MessageBus rest \
"Unable to start MessageBus Service. %s"

2021-05-27 15:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        except Exception as e:
No need to handle exception. SimpleProcess already does this.

2021-05-27 15:22 UTC, ujjwalpl requested changes

2021-05-27 15:22 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        except Exception as e:
No need to handle exception. SimpleProcess does not throw any exception.

2021-05-27 16:43 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        except Exception as e:
done, removed

2021-05-27 16:43 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        except Exception as e:
done, removed

2021-05-27 16:43 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +                raise SetupError(res_rc, "Unable to start MessageBus rest \
done

2021-05-28 04:44 UTC, ujjwalpl approved these changes

2021-06-01 04:08 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +
After starting the service check the status to ensure it has been started correctly. And then return success or failure

2021-06-01 04:10 UTC, sachinpunadikar requested changes
Add status check after starting the service

2021-06-01 05:44 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +
Done

2021-06-01 06:26 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +
fix the codacy issue

2021-06-01 06:27 UTC, sachinpunadikar requested changes
fix codacy issue

2021-06-01 06:38 UTC, sachinpunadikar approved these changes
+1

2021-06-01 06:56 UTC, rahul-tripathi-git approved these changes
+1

2021-06-01 09:51 UTC, sachinpunadikar commented
test this please

2021-06-01 17:42 UTC, sachinpunadikar commented
test this please

2021-06-02 10:14 UTC, sachinpunadikar commented
Custom VM deployment is going through clean - http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.8/job/cortx-custom-ci/1528/

2021-06-02 10:16 UTC, merged