EOS-20722: Remove hardcoded install_path from build scripts
Seagate/cortx-utils pull request #314
Opened 2021-05-26 04:08 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

# Problem Statement
- install path needed to be removed from build script. Moved it to the top as a configurable variable.

# Design
-  NA

# Coding 
-  Coding conventions are followed and code is consistent [Y]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-05-26 09:12 UTC, sachinpunadikar commented on py-utils/setup.py
> +install_path = "/opt/seagate"
Read it from cortx.conf.sample file

2021-05-26 09:14 UTC, sachinpunadikar commented on py-utils/utils-post-install
> +install_path="/opt/seagate"
read from cortx.conf.sample file

2021-05-26 09:21 UTC, sachinpunadikar commented on py-utils/utils-post-install
> +  cp ./cortx.conf.sample /etc/cortx/cortx.conf
"./cortx.conf.sample" <- this is incorrect. You will get failure as file not found.

2021-05-26 09:24 UTC, sachinpunadikar commented on py-utils/setup.py
> +                     (conf_dir, tmpl_files)],
You missed to copy the cortx.conf.sample file. This file will be referred after installation

2021-05-26 09:25 UTC, sachinpunadikar requested changes
Please work on the comments

2021-05-28 15:08 UTC, closed without merging

2021-05-28 15:08 UTC, rahul-tripathi-git commented
Duplicate PR