EOS-19858: utils_setup should log its activity
Seagate/cortx-utils pull request #315
Opened 2021-05-26 15:55 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- utils_setup should log its activity

# Design
-  JIRA - [EOS-19858](https://jts.seagate.com/browse/EOS-19858)

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: Y
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-05-26 16:53 UTC, sachinpunadikar requested changes
Generic comment / observation:
Log.info should be used to describe the status like post_install passed. Rest all should be changed as Log.debug. By default there should be minimum logging and that should be useful.
Please make corrections likewise.

2021-05-27 14:59 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        Conf.load("cluster_config", conf_url)
single quote

2021-05-27 14:59 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        if str(msg.decode("utf-8")) != "Test Message":
('utf-8')

2021-05-27 16:00 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            Log.exception(f"Failed to create {conf_file} - {e}")
No need to log here. Exception logging can be at one place where SetupError is caught.

2021-05-27 16:18 UTC, ujjwalpl requested changes

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Received {argv[1]} command to run")
Message should be professional. 
Log.info(f"Starting utils_setup {argv[1]}...")

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +            Log.error(f"Could not able to run {argv[1]}")
Incorrect grammar and place 
```
rc = command.process()
Log.info(f"Command {command} {argv[1]} finished with exit code {rc}")
sys.exit(rc)
```

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.exception(f"Failed to run {argv[1]} - {e}")
```
except SetupError as e:
    sys.stderr.write("error: %s\n\n" % str(e))
    sys.stderr.write("%s\n" % traceback.format_exc())
    Cmd.usage(argv[0])
except SetupError as e:
    sys.stderr.write("%s\n" % traceback.format_exc())
```

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.info(f"Utils cleanup was successful with rc {rc}")
No need to print info level. It should only be at the main entry point and exit point. Remove this, its anyway going to print this message.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated cleanup using Utils.validate('cleanup') and " \
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated reset using Utils.validate('reset') and doing " \
Remove this log. Not required.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated test using Utils.validate('test') and doing " \
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated init using Utils.validate('init') and doing "\
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated config and doing utils config now")
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated post_install and doing utils post_install" +\
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Listed all members {sys.modules[__name__]}")
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Listed filtered classes of phases - {cmds}")
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Parsing command line {argv} for returning command")
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Parsed command line {argv} and returning cmd "\
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Log.info("Utils post_install phase successful - All python packages"\
No need to print info level. It should only be at the main entry point and exit point. Remove this, its anyway going to print this message.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Log.info("Utils init passed successfully")
No need to print info level. It should only be at the main entry point and exit point. Remove this, its anyway going to print this message.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Log.info("Utils config phase done successfully")
No need to print info level. It should only be at the main entry point and exit point. Remove this, its anyway going to print this message.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Log.info("Utils test phase was successful")
No need to print info level. It should only be at the main entry point and exit point. Remove this, its anyway going to print this message.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Log.info("Utils reset was successful")
No need to print info level. It should only be at the main entry point and exit point. Remove this, its anyway going to print this message.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Log.info("utils cleanup was successful")
No need to print info level. It should only be at the main entry point and exit point. Remove this, its anyway going to print this message.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            Log.error(f"No valid Kafka server info provided for Config Key "\
log.error(f"Missing config entry {key_list} in config file {conf_file")

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            os.rename(f'{conf_file}.sample', conf_file)
We dont want to overwrite if conf file exists already. We need to merge to it.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Log.debug("Validated. Both zookeeper and kafka services are running.")
Please remove this log. No need of excessive logging.

2021-05-27 16:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            Log.debug(f"cmd {cmd} executed, List of installed packages "\
Refer to v_pkg.py It already has way to check installed pip3 package, please use that.

2021-05-28 06:38 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            Log.debug(f"cmd {cmd} executed, List of installed packages "\
In v_pkg.py there is 'pip3 list' cmd usage and we are using requirements.txt (pip3 freeze)to verify , they do not match

pip3 list -> aiohttp (3.6.1)
pip3 freeze -> aiohttp==3.6.1

2021-05-28 18:10 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            os.rename(f'{conf_file}.sample', conf_file)
We will not be having multiple values in cluster.conf similar to message_bus.conf
{
  "server_node": {
    "site_id": 123,
    "rack_id": 456,
    "node_id": 789
  }
}

2021-05-29 02:54 UTC, vastradparayya commented on py-utils/src/utils/log.py
> +            if not logger.hasHandlers():
For removal of duplicate entry in log.

2021-05-29 13:51 UTC, ujjwalpl requested changes

2021-05-29 13:51 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            os.rename(f'{conf_file}.sample', conf_file)
Today we dont. We will have several values tomorrow. We need to write generic logic.

2021-05-29 13:51 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +        Log.info(f"Command {command} {argv[1]} finished with exit " \
Not only non exception but finished log should be printed in all the cases. 
Move this line to the end after exception. 
try: 
    log.info(starting...)
    xxx
excpt:
    yyy
log.info(Command finished with exit code ...)

2021-05-31 07:03 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            os.rename(f'{conf_file}.sample', conf_file)
@ujjwalpl This is node specific as per format . Can you give me a example so I can understand more clearly.



<!--StartFragment-->cortx:  software:    common:      message_bus_type: kafka # kafka is the only supported type    kafka:      servers:      # Value should be in format &lt;FQDN&gt;:&lt;port&gt;. Port is optional      - TMPL_KAFKA_SERVER1_FQDN:TMPL_KAFKA_SERVER1_PORT      - TMPL_KAFKA_SERVER2_FQDN:TMPL_KAFKA_SERVER2_PORT      - TMPL_KAFKA_SERVER3_FQDN:TMPL_KAFKA_SERVER3_PORTserver_node:  TMPL_MACHINE_ID:    site_id: TMPL_SITE_ID    rack_id: TMPL_RACK_ID    node_id: TMPL_NODE_ID<!--EndFragment-->

2021-05-31 12:13 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.info(f"Command {command} {argv[1]} finished with exit " \
Done

2021-05-31 12:26 UTC, ujjwalpl requested changes

2021-05-31 12:26 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +            Log.info(f"Command {command} {argv[1]} finished with exit " \
No need of this check and log. Last line already covers this. 
```
    ...
        rc = command.process()

    except SetupError as e:
        sys.stderr.write("error: %s\n\n" % str(e))
        sys.stderr.write("%s\n" % traceback.format_exc())
        Cmd.usage(argv[0])
    except Exception as e:
        sys.stderr.write("error: %s\n\n" % str(e))
        sys.stderr.write("%s\n" % traceback.format_exc())
    
    Log.info(f"Command {command} {argv[1]} finished with exit " \
        f"code {rc}")
```

2021-05-31 12:33 UTC, ujjwalpl requested changes

2021-05-31 12:33 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            Log.error("Could not test utils config, fails in matching sent " +\
Please use the same message as the exception.

2021-05-31 12:33 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            SetupError(e.rc, "Unable to load servers from config file %s %s",\
raise ?

2021-05-31 12:33 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            SetupError(errors.ERR_OP_FAILED, "Unable to load servers from "\
raise ?

2021-05-31 13:20 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            SetupError(errors.ERR_OP_FAILED, "Unable to load servers from "\
Done

2021-05-31 13:20 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            SetupError(e.rc, "Unable to load servers from config file %s %s",\
Done

2021-05-31 13:20 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            Log.error("Could not test utils config, fails in matching sent " +\
Done

2021-05-31 13:20 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +            Log.info(f"Command {command} {argv[1]} finished with exit " \
Done

2021-05-31 13:21 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            Log.debug(f"cmd {cmd} executed, List of installed packages "\
Done

2021-05-31 13:21 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        Log.debug("Validated. Both zookeeper and kafka services are running.")
Done

2021-05-31 13:21 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            os.rename(f'{conf_file}.sample', conf_file)
Done

2021-05-31 13:21 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            Log.error(f"No valid Kafka server info provided for Config Key "\
Done

2021-05-31 13:21 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        Log.info("utils cleanup was successful")
Done

2021-05-31 13:22 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        Log.info("Utils reset was successful")
Done

2021-05-31 13:22 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        Log.info("Utils test phase was successful")
Done

2021-05-31 13:22 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        Log.info("Utils config phase done successfully")
Done

2021-05-31 13:22 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        Log.info("Utils init passed successfully")
Done

2021-05-31 13:22 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        Log.info("Utils post_install phase successful - All python packages"\
Done

2021-05-31 13:22 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Parsed command line {argv} and returning cmd "\
Done

2021-05-31 13:22 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Parsing command line {argv} for returning command")
Done

2021-05-31 13:23 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Listed filtered classes of phases - {cmds}")
Done

2021-05-31 13:23 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Listed all members {sys.modules[__name__]}")
Done

2021-05-31 13:23 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated post_install and doing utils post_install" +\
Done

2021-05-31 13:23 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated config and doing utils config now")
Done

2021-05-31 13:23 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated init using Utils.validate('init') and doing "\
Done

2021-05-31 13:23 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated test using Utils.validate('test') and doing " \
Done

2021-05-31 13:23 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated reset using Utils.validate('reset') and doing " \
Done

2021-05-31 13:24 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug("Validated cleanup using Utils.validate('cleanup') and " \
Done

2021-05-31 13:24 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.info(f"Utils cleanup was successful with rc {rc}")
Done

2021-05-31 13:24 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.exception(f"Failed to run {argv[1]} - {e}")
Done

2021-05-31 13:24 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +            Log.error(f"Could not able to run {argv[1]}")
Done

2021-05-31 13:24 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +        Log.debug(f"Received {argv[1]} command to run")
Done

2021-05-31 13:25 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            Log.exception(f"Failed to create {conf_file} - {e}")
Done

2021-05-31 13:25 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            os.rename(f'/{conf_file}.sample', conf_file)
Done

2021-05-31 13:25 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +         file_size_in_mb=5, syslog_server=None, syslog_port=None)
Done

2021-05-31 13:25 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        if str(msg.decode("utf-8")) != "Test Message":
Done

2021-05-31 13:25 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        Conf.load("cluster_config", conf_url)
Done

2021-05-31 13:25 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +Log.init('utils', '/var/log/cortx/utils', level='INFO', backup_count=100,\
Done

2021-05-31 14:18 UTC, ujjwalpl requested changes

2021-05-31 14:18 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            Conf.save('index')
You are updating sample file. You should update original conf file.

2021-06-01 09:54 UTC, ujjwalpl requested changes

2021-06-01 09:54 UTC, ujjwalpl commented on py-utils/src/setup/utils_setup.py
> +Log.init('utils_setup', '/var/log/cortx/utils', level='INFO', backup_count=5,\
Log.init should be called only once from the main program.

2021-06-01 09:57 UTC, ujjwalpl requested changes

2021-06-01 09:57 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            Log.error(f"Message Bus do not support message bus type "\
Log.error(f"Message bus type {msg_bus_type} is not supported")

2021-06-01 12:53 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            Log.error(f"Message Bus do not support message bus type "\
Done

2021-06-01 12:54 UTC, vastradparayya commented on py-utils/src/setup/utils_setup.py
> +Log.init('utils_setup', '/var/log/cortx/utils', level='INFO', backup_count=5,\
Done

2021-06-01 13:53 UTC, ujjwalpl approved these changes

2021-06-01 16:13 UTC, rahul-tripathi-git approved these changes
+1

2021-06-02 04:11 UTC, selvakumaar5496 approved these changes

2021-06-07 06:09 UTC, sachinpunadikar approved these changes
+1

2021-06-07 06:15 UTC, merged