Renamed test directories to module name.
Seagate/cortx-utils pull request #318
Opened 2021-05-27 11:41 UTC by veerendra-simha-garikipati

Signed-off-by: Veerendra Garikipati <veerendra.garikipati@seagate.com>

# Problem Statement
- Renamed test directory names to module names

# Design
-  NA

# Coding 
-  NA

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-05-27 11:43 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-05-27 11:58 UTC, sachinpunadikar commented on py-utils/test/setup.py
> -        "cortx.utils.test.kvstore",
Why kvstore is not part of packages ?

2021-05-27 11:59 UTC, sachinpunadikar requested changes
Please include kvstore in packages for test rpm

2021-05-27 12:03 UTC, veerendra-simha-garikipati commented on py-utils/test/setup.py
> -        "cortx.utils.test.kvstore",
Hi Sachin,
I have moved the file contents of kvstore directory to test_kv_store directory and renamed test_kv_store to kv_store.

2021-05-27 16:00 UTC, rahul-tripathi-git approved these changes
Looks good to me

2021-05-28 03:15 UTC, sachinpunadikar approved these changes
+1

2021-05-28 03:25 UTC, sachinpunadikar commented
test this please

2021-05-28 04:38 UTC, merged