WIP EOS-20722: Remove hardcoded install_path from build scripts
Seagate/cortx-utils pull request #320
Opened 2021-05-27 17:01 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

# Problem Statement
- Removal of hardcoded install paths from build scripts

# Design
- NA

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Yes
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-05-28 15:12 UTC, rahul-tripathi-git commented on jenkins/build.sh
> +echo $VER > VERSION
Creating this file in build time to be read in setup.py and get version info

2021-05-28 15:13 UTC, rahul-tripathi-git commented on jenkins/build.sh
> +INSTALL_PATH=`grep install_path cortx.conf.sample |  cut -d " " -f 4 | sed -e 's/^"//' -e 's/"$//'`
Replacing place holder in utils-post-install script with install path.

**NOTE**: The install_path is read from cortx.conf.sample file to maintain consistency between build-time and runtime.

2021-05-28 15:16 UTC, rahul-tripathi-git commented on jenkins/build.sh
> +/bin/python3.6 setup.py bdist_rpm --release="$REL" --pre-install utils-pre-install \
Version argument is removed as it was troublesome. Now versioning is working correctly as expected

2021-05-28 15:17 UTC, rahul-tripathi-git commented on py-utils/utils-post-uninstall
> +    /bin/rm -f /etc/cortx/cortx.conf
This will be called only when there is an un-install or rpm.

2021-05-28 17:12 UTC, sachinpunadikar approved these changes
+1

2021-05-28 18:43 UTC, rahul-tripathi-git commented
test this please

2021-05-29 14:09 UTC, ujjwalpl requested changes

2021-05-29 14:09 UTC, ujjwalpl commented on py-utils/utils-post-install
> +if [ ! -f "/etc/cortx/cortx.conf" ]; then
This can be written as 
```
[ -f "/etc/cortx/cortx.conf" ] || cp -n $conf_dir/cortx.conf.sample /etc/cortx/cortx.conf
```

2021-05-29 14:09 UTC, ujjwalpl commented on py-utils/utils-post-install
> +/bin/cp -f /usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_bus_server.py $bin_dir/message_bus_server
It should be link and not cp

2021-05-29 14:09 UTC, ujjwalpl commented on py-utils/utils-post-install
> +/bin/cp -f /usr/lib/python3.6/site-packages/cortx/setup/utils_setup.py $bin_dir/utils_setup
it should be link and not cp

2021-05-29 14:09 UTC, ujjwalpl commented on py-utils/utils-post-install
> +bin_dir=$install_path/cortx/utils/bin
For readability, declare only one var named utils_path=$install_path/cortx/utils

2021-05-29 14:09 UTC, ujjwalpl commented on py-utils/utils-post-install
> +/bin/chmod +x $bin_dir/utils_setup
chmod +x $utils_path/bin/utils_setup

2021-05-29 14:09 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +  "install_path": "/opt/seagate"
Make it to include cortx as well. 
"install_path": "/opt/seagate/cortx"

2021-05-29 14:09 UTC, ujjwalpl commented on py-utils/setup.py
> +with open("cortx.conf.sample") as conf_file:
Use proper path. setup will not be called from pwd.

2021-05-29 14:09 UTC, ujjwalpl commented on py-utils/setup.py
> +conf_dir = "%s/cortx/utils/conf" % install_path
User utils_path and use it allover the code for easy read.

2021-05-31 04:18 UTC, sachinpunadikar commented on py-utils/cortx.conf.sample
> +  "install_path": "/opt/seagate"
As per our earlier discussion, we want to provide an option to change the path where cortx will get installed. If we include cortx here , and if someone makes it like "/opt/my_co/my_prod", then cortx will go out of picture.

2021-05-31 15:05 UTC, rahul-tripathi-git commented on py-utils/utils-post-install
> +if [ ! -f "/etc/cortx/cortx.conf" ]; then
Done

2021-05-31 15:06 UTC, rahul-tripathi-git commented on py-utils/utils-post-install
> +/bin/cp -f /usr/lib/python3.6/site-packages/cortx/setup/utils_setup.py $bin_dir/utils_setup
Done

2021-05-31 15:06 UTC, rahul-tripathi-git commented on py-utils/utils-post-install
> +bin_dir=$install_path/cortx/utils/bin
Done

2021-05-31 15:06 UTC, rahul-tripathi-git commented on py-utils/utils-post-install
> +/bin/chmod +x $bin_dir/utils_setup
Done

2021-05-31 15:09 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +with open("cortx.conf.sample") as conf_file:
we are doing cd to this path before setup is called. Please see below line from build.sh
https://github.com/rahul-tripathi-git/cortx-utils/blob/ca14dd566eea81fb1ab59c31c6970e195c6249c6/jenkins/build.sh#L53

The code is well tested.

2021-05-31 15:10 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +conf_dir = "%s/cortx/utils/conf" % install_path
Done

2021-06-01 04:15 UTC, sachinpunadikar commented on py-utils/setup.py
> +
remove this extra new line

2021-06-01 04:17 UTC, sachinpunadikar approved these changes
A minor comment.
Rest all looks good

2021-06-01 04:40 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +
Done

2021-06-01 07:12 UTC, rahul-tripathi-git commented on py-utils/setup.py
>  _ROOT = os.path.abspath(os.path.dirname(__file__)) + "/" + SPEC_DIR
As discussed marking it as resolved.

2021-06-01 14:25 UTC, ujjwalpl requested changes

2021-06-01 14:25 UTC, ujjwalpl commented on py-utils/setup.py
> +with open("cortx.conf.sample") as conf_file:
This code will not work if you dont run from current folder. You can not assume caller will always do this.

2021-06-01 14:25 UTC, ujjwalpl commented on py-utils/setup.py
> +with open("VERSION") as v_file:
Please use proper path in all the cases. You can assume you are in the current folder.

2021-06-01 16:21 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +with open("cortx.conf.sample") as conf_file:
applied a check to check for existence of file

2021-06-01 16:21 UTC, rahul-tripathi-git commented on py-utils/setup.py
> +with open("VERSION") as v_file:
applied a check to check for existence of file

2021-06-01 18:01 UTC, sachinpunadikar commented
test this please

2021-06-01 18:14 UTC, rahul-tripathi-git commented on py-utils/utils-post-install
> +/bin/cp -f /usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_bus_server.py $bin_dir/message_bus_server
Done

2021-06-02 04:12 UTC, ujjwalpl requested changes

2021-06-02 04:12 UTC, ujjwalpl commented on py-utils/setup.py
> +    print("cortx.conf.sample file not found!")
`print("error: cortx.conf.sample file not found!", file=sys.stderr)`

2021-06-02 04:40 UTC, ujjwalpl approved these changes

2021-06-08 04:37 UTC, merged