CLI for Comparing two strings for a given key
Seagate/cortx-utils pull request #321
Opened 2021-05-28 12:39 UTC by venkuppu-chn

# Problem Statement
- While SW upgrade, not able to compare the current version with future version in cortx stack

# Design
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 
https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/284099843/CORTX+ISO+Package+Structure

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: N
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-05-28 19:11 UTC, rahul-tripathi-git reviewed
Who all components are the intended user of get_diff() feature of conf_cli?

Also please use your best judgement, consider all the comments as suggestions. Hence not requesting for changes.
@sachinpunadikar and @ujjwalpl  please provide your feedback.

2021-05-28 19:11 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_cli.py
> +    def get_diff(args) -> str:
This is the core logic for get_diff, this might needs to go inside conf_cache, conf_store, kv_payload, kv_store etc.. please check out the flow for other methods.

2021-05-28 19:16 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "# conf yaml:///tmp/csm.conf get_diff 'k6' -i yaml:///tmp/csm.conf \n\n")
both the file names may be different to give a better understanding to user.

2021-05-28 19:24 UTC, rahul-tripathi-git requested changes
Requesting changes to add test cases.

2021-05-31 11:50 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        ps = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
> Who all components are the intended user of get_diff() feature of conf_cli?
> 
The consumer of this cli is all components in the cortx.

2021-05-31 11:54 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        ps = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
> https://github.com/Seagate/cortx-utils/blob/67f1f7e46ba94b1e4de9571a69626340d5993f38/py-utils/src/utils/process.py#L28
> 
> SimpleProcess might be used instead of subprocess.Popen directly please see above link.

As suggested, I have changed the subprocess to SimpleProcess.

2021-05-31 12:00 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +    def get_diff(args) -> str:
It will not have any impact on other functionalities, since the get_diff function calls ConfCli.get(args) two times for two different files and compare the strings.

2021-05-31 13:23 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "# conf yaml:///tmp/csm.conf get_diff 'k6' -i yaml:///tmp/csm.conf \n\n")
Changed the file name

2021-05-31 13:25 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        """ Compare two diffenent string value for the given keys """
The current description is not clear?

2021-05-31 14:56 UTC, ujjwalpl requested changes

2021-05-31 14:56 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-f', dest='format', help=
Why -f option ?

2021-05-31 14:58 UTC, ujjwalpl requested changes

2021-05-31 14:58 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        cmd_proc = SimpleProcess([cmd])
This is not the real diff. Real diff should be to diff the keys. We need to understand and define the use case. For example if you do json diff it wont be readable.

2021-06-01 05:50 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-f', dest='format', help=
It will be helpful for the user to compare the difference in specified output format such as json or yaml.

2021-06-01 06:03 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        cmd_proc = SimpleProcess([cmd])
The diff will work for any input file type which has conf cli support. Kindly refer below output for json.

Moreover, the flow of this function is, it get the value from two various release file for a given key using conf get cli and compare the strings using linux diff command.

[root@ssc-vm-4102 utils]# conf json:///root/file.json diff "VERSION" -i json:///root/file1.json
1c1
< [2.0.0]
---
> [2.0.1]

[root@ssc-vm-4102 utils]#

2021-06-01 07:41 UTC, ujjwalpl requested changes

2021-06-01 07:41 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +
Please add test code.

2021-06-01 08:42 UTC, venkuppu-chn commented
> **Please add test cases for get_diff** in https://github.com/Seagate/cortx-utils/blob/main/py-utils/test/conf_store/test_conf_cli.py file

Thanks Rahul for pointing this. I have added the testcase for new cli.
![image](https://user-images.githubusercontent.com/62052913/120293920-54bd7800-c2e3-11eb-95d0-7f6b2b306627.png)

2021-06-01 08:44 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +
Added the test case. Kindly refer below screenshot.
![image](https://user-images.githubusercontent.com/62052913/120294196-98b07d00-c2e3-11eb-9e46-26f1323fec63.png)

2021-06-01 08:47 UTC, venkuppu-chn commented
> Please update Conf_store spec document for get_diff feature in cli section.
> [Conf_store Spec document](https://seagatetechnology.sharepoint.com/:w:/r/sites/gteamdrv1/tdrive1224/_layouts/15/Doc.aspx?sourcedoc=%7BA68B2DB0-B041-4136-8F51-94F0A4685D1E%7D&file=ConfStore_Specification.docx&action=default&mobileredirect=true)

Updated the document

2021-06-01 08:48 UTC, venkuppu-chn commented
> Please update Conf_store spec document for get_diff feature in cli section.
> [Conf_store Spec document](https://seagatetechnology.sharepoint.com/:w:/r/sites/gteamdrv1/tdrive1224/_layouts/15/Doc.aspx?sourcedoc=%7BA68B2DB0-B041-4136-8F51-94F0A4685D1E%7D&file=ConfStore_Specification.docx&action=default&mobileredirect=true)

Updated the document.

2021-06-01 09:03 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-f', dest='format', help=
Here is the screenshot for various diff output based on file type.
![image](https://user-images.githubusercontent.com/62052913/120296871-2f7e3900-c2e6-11eb-807d-6972e26d0d98.png)

2021-06-01 10:08 UTC, ujjwalpl requested changes

2021-06-01 10:08 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-f', dest='format', help=
Output is not in yaml format. Its diff format. As discussed, lets remove -f as it does not add any value.

2021-06-01 10:08 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        string_1 = ConfCli.get(args).replace('"', '\"')
Its not a good idea to pass args directly to ConfCli. Please refer to the other commands. 
```
params = args.args
key_list = params[0].split(';')
url = args.url
```

```

2021-06-01 10:09 UTC, ujjwalpl requested changes

2021-06-01 10:09 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "Example(s): 'k1', 'k1>k2;k3', 'k4[2]>k5', 'k6>k4[2]>k5'\n\n"
Can you add a test case for multiple keys as explained here. 
```
# conf yaml://xxx diff 'version;release' -i yaml://yyy
```

2021-06-01 10:13 UTC, ujjwalpl requested changes

2021-06-01 10:13 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-i', dest='diff', help=
I would prefer if we can change the spec as 

```
# conf yaml://xxx diff yaml://yyy -k 'version;release' 
```

This way we can accommodate several use cases like... 
```
# conf yaml://xxx diff yaml://yyy <<<<<<<< Gets key diff 
# conf yaml://xxx diff yaml://yyy -k 'version' <<<<<<< Gets diff of value
# conf yaml://xxx diff yaml://yyy -k 'version;release' <<<<< Gets diff of values
```

2021-06-01 13:38 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        cmd_proc = SimpleProcess([cmd])
Not done. Will address it in EOS-20963

2021-06-01 13:38 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "Example(s): 'k1', 'k1>k2;k3', 'k4[2]>k5', 'k6>k4[2]>k5'\n\n"
Done

2021-06-01 13:38 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-i', dest='diff', help=
Not done. Will address it in EOS-20963

2021-06-01 13:39 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-f', dest='format', help=
Done

2021-06-01 13:39 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        string_1 = ConfCli.get(args).replace('"', '\"')
Done

2021-06-01 13:59 UTC, ujjwalpl requested changes

2021-06-01 13:59 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-i', dest='diff', help=
This is required to be done now. We wont be changing the interface later.

2021-06-01 14:49 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-i', dest='diff', help=
Done.

![image](https://user-images.githubusercontent.com/62052913/120343789-a29fa380-c316-11eb-99d1-b9ca20d58675.png)

2021-06-01 15:08 UTC, ujjwalpl requested changes

2021-06-01 15:08 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-i', dest='diff', help=
Need to stick to this
```
# conf yaml://xxx diff yaml://yyy -k 'version;release' 
```

2021-06-01 16:14 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +        s_parser.add_argument('-i', dest='diff', help=
Done

2021-06-01 16:22 UTC, ujjwalpl approved these changes

2021-06-02 06:31 UTC, rahul-tripathi-git approved these changes
+1

2021-06-02 11:59 UTC, sachinpunadikar approved these changes
+1

2021-06-02 16:52 UTC, sachinpunadikar commented
Console output for cortx-custom-ci
http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.8/job/cortx-custom-ci/1534/consoleFull
 
Console output for custom-cortx-py-utils
http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.8/job/custom-cortx-py-utils/3050/consoleFull

2021-06-02 16:52 UTC, merged

2021-06-03 13:46 UTC, balajiramachandran-seagate commented
Created PR for Conf CLI to get the diff of all the keys between two release.info files. 
https://github.com/Seagate/cortx-utils/pull/324
Reference ticket - EOS-20963

Test Case:
![image](https://user-images.githubusercontent.com/64014432/120655276-20db8180-c4a0-11eb-92e4-7aebc3567904.png)