WIP: EOS-20737 get_keys iteration in lists
Seagate/cortx-utils pull request #322
Opened 2021-05-31 12:34 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

# Problem Statement
- This is an add-on requirement for get_keys method in confstore.
Previously the get_keys method was not iterating through the
lists due to which the key structre generated by get_method was
limited till the parent of the list.

# Design
-  N/A

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-01 06:48 UTC, selvakumaar5496 requested changes

2021-06-01 06:48 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store.py
> +        'bridge>model', 'bridge>pin', 'bridge>lte_type[0]>name',
indent 4 spaces

2021-06-01 06:48 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store.py
> +        'bridge>model', 'bridge>pin', 'bridge>lte_type>name']
indent 4 spaces

2021-06-01 06:48 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store.py
>          key_lst = Conf.get_keys("getKeys_local", key_index=True)
single quote  'getKeys_local'

2021-06-01 07:44 UTC, rahul-tripathi-git commented on py-utils/test/conf_store/test_conf_store.py
> +        'bridge>model', 'bridge>pin', 'bridge>lte_type>name']
Done

2021-06-01 07:44 UTC, rahul-tripathi-git commented on py-utils/test/conf_store/test_conf_store.py
>          key_lst = Conf.get_keys("getKeys_local", key_index=True)
Done

2021-06-01 07:44 UTC, rahul-tripathi-git commented on py-utils/test/conf_store/test_conf_store.py
> +        'bridge>model', 'bridge>pin', 'bridge>lte_type[0]>name',
Done

2021-06-01 08:17 UTC, selvakumaar5496 approved these changes

2021-06-01 10:34 UTC, ujjwalpl requested changes

2021-06-01 10:34 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_payload.py
> +                    if key_index:
This block can be reduced to two lines 
```
index_suffix = "[{index}]" if key_index else ""
newkey = None if not pkey else "%s[%d]" % (pkey, index)
```

2021-06-01 10:34 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_payload.py
> +                    if pkey:
`if pkey` is not required. 
```
>>> a = None
>>> b = ['1', '2']
>>> if a not in b:
...     print("yes")
...
yes
```

2021-06-01 10:37 UTC, ujjwalpl requested changes

2021-06-01 10:37 UTC, ujjwalpl commented on py-utils/test/conf_store/test_conf_store.py
> +        key_lst = Conf.get_keys('getKeys_local', key_index=True)
Can you try to test this command, just to check the regression. You can also add this test case. 
```
# conf "json:///tmp/file.yaml" set "a>b[4]>s" 10 
```

2021-06-01 18:35 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_payload.py
> +                    if pkey:
Removed as suggested!

2021-06-01 18:35 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_payload.py
> +                    if key_index:
Done

2021-06-01 18:35 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_payload.py
> +                # raise KvError KvError(rc, message, *args)
Done

2021-06-02 04:14 UTC, ujjwalpl approved these changes

2021-06-15 06:07 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                raise KvError(errno.EACCES, "Cant set key %s. %s", key, e)
Error code correction. This is not related to this PR

2021-06-15 13:44 UTC, sachinpunadikar approved these changes
+1

2021-06-18 08:33 UTC, ujjwalpl requested changes

2021-06-18 08:33 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_payload.py
> +        if len(key_split) == 1:
Can you split this function into parts and individual functions ? This is too complex to understand and fix in case of issues.

2021-06-18 08:33 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_payload.py
> +            for index, d in enumerate(data):
To support backward compatibility lets change the signature to

get_keys(deep_scan=False). 

If deep_scan is True, then we will return all the keys. New users will use get_keys(True) call.

2021-06-23 05:06 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_payload.py
> +            for index, d in enumerate(data):
Done

2021-06-24 16:07 UTC, ujjwalpl requested changes

2021-06-24 16:07 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_payload.py
> +    def get_keys(self, deep_scan: bool = True, **filters) -> list:
Looks like key_index and deep_scan are the same thing. If so lets merge them together.

2021-06-25 11:10 UTC, ujjwalpl requested changes

2021-06-25 11:10 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +    def __init__(self, kv_store: KvStore, delim='>', deep_scan=True):
Please use recurse as the option name as its more intuitive.

2021-06-27 13:41 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_payload.py
> +    def get_keys(self, deep_scan: bool = True, **filters) -> list:
They are different. 
Key_index is to get the indexes present in lists(array) type hierarchy, while 
deep_scan is to recurse in the the those k/v structure and get the complete keys in get_keys.

2021-06-28 14:41 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_cache.py
> +    def __init__(self, kv_store: KvStore, delim='>', deep_scan=True):
Done

2021-06-28 16:07 UTC, sachinpunadikar approved these changes
+1

2021-06-29 10:53 UTC, ujjwalpl requested changes

2021-06-29 10:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +                continue
```
recurse = True
for ....
elif key == 'recurse':
    if val not in [True, False]: 
        raise ConfError(errno.EINVAL, "Invalid value for recurse %s"...)
    recurse = val
```

2021-06-29 10:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        self._cache[index] = ConfCache(kv_store, self._delim, recurse=kwargs['recurse'])
This will result in error if recurse is not part of kwargs. Use "recurse" variable here.

2021-06-29 10:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +            key_list = self._cache[src_index].get_keys(key_index=recurse)
If key_index != recurse. Why do we relate them here ? We should have
get_keys(recurse=recurse)

2021-06-29 10:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +    def load(index: str, url: str, recurse=True,**kwargs):
There is always a space after comma.

2021-06-29 10:53 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        return KvPayload(data, self._delim, recurse = kwargs['recurse'])
We should avoid assuming that recurse is in kwargs. 

recurse = True
if 'recurse' in kwargs.keys(): 
    recurse = kwargs['recurse']
....
return KvPayload(data, self._delim, recurse=recurse)

Also please use space consistently. Somewhere you are using "func(a=b)" and elsewhere "func(a = b)"

2021-06-29 10:53 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        return KvPayload(data, self._delim, recurse = kwargs['recurse'])
Same comment here. Avoid using kwargs directly.

2021-06-29 10:53 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        return KvPayload(data, self._delim, recurse = kwargs['recurse'])
Same comment here.

2021-06-29 15:51 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_store.py
> +    def load(index: str, url: str, recurse=True,**kwargs):
done

2021-06-29 15:51 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_store.py
> +            key_list = self._cache[src_index].get_keys(key_index=recurse)
Done

2021-06-29 15:52 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_store.py
> +        self._cache[index] = ConfCache(kv_store, self._delim, recurse=kwargs['recurse'])
Done

2021-06-29 15:52 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_store.py
> +                continue
Done

2021-06-29 16:38 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        return KvPayload(data, self._delim, recurse = kwargs['recurse'])
Done.

2021-06-29 16:38 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        return KvPayload(data, self._delim, recurse = kwargs['recurse'])
Done.

2021-06-29 16:51 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        return KvPayload(data, self._delim, recurse = kwargs['recurse'])
Done

2021-06-29 16:53 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_store.py
> +            key_list = self._cache[src_index].get_keys(key_index=recurse)
for deep_scan, along with copy, we needed to have keys with indexes, before this change, key_index was se to false by default. I have separated the conditions for both.

2021-06-29 17:45 UTC, ujjwalpl approved these changes

2021-06-30 05:06 UTC, merged