Add subscribe interface to receive alerts
Seagate/cortx-utils pull request #323
Opened 2021-06-02 06:55 UTC by selvakumaar5496

# Problem Statement
- IEM improvement

# Design
https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/316735500/IEM+Framework 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [x] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [x] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [x] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [x] Check Acceptance Criterion is defined. 
- [x] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [x] Changes done to WIKI / Confluence page

2021-06-02 12:28 UTC, ujjwalpl requested changes

2021-06-02 12:28 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +    def init(cls, component: str, source: str):
Please note site_id, rack_id and node_id can be string, so treat them as string.

2021-06-02 12:51 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +        alert = cls._consumer.receive()
done

2021-06-02 12:51 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +            message_type='IEM', method='sync')
done

2021-06-02 12:52 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    def init(cls, component: str, source: str):
done

2021-06-02 13:39 UTC, ujjwalpl requested changes

2021-06-02 13:39 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +    def init(cls, component: str, source: str):
Who calls __init__ ? Why is it not part ot init() ?

2021-06-02 13:41 UTC, ujjwalpl requested changes

2021-06-02 13:41 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +        alert = cls._consumer.receive()
Please print component and module. So that when it is printed in the logs you know which component has the issue.

2021-06-02 13:57 UTC, ujjwalpl requested changes

2021-06-02 13:57 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +            cls._site_id = ids['site_id']
cls.consumer = None
cls.producer = None

2021-06-02 13:57 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +        site_id: str = None, rack_id: str = None, node_id: str = None, \
check producer in case init is not called. 
```
if producer == None: 
   raise
```

2021-06-02 13:58 UTC, ujjwalpl requested changes

2021-06-02 13:58 UTC, ujjwalpl commented on py-utils/test/iem_framework/test_iem.py
> +    def test_subscribe_validation(self):
Please add Negative test, e.g. 
1. Dont call init and send
2. Dont call subscribe and try to receive

2021-06-03 04:24 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +            cls._site_id = ids['site_id']
done

2021-06-03 04:24 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +    def init(cls, component: str, source: str):
callend implicitly by init() on line no: 70

2021-06-03 04:25 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +        site_id: str = None, rack_id: str = None, node_id: str = None, \
done

2021-06-03 04:25 UTC, selvakumaar5496 commented on py-utils/test/iem_framework/test_iem.py
> +    def test_subscribe_validation(self):
above testcases do exist already.

2021-06-03 13:07 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +        alert = cls._consumer.receive()
We dont have any other information than _counsumer attribute in receive interface

2021-06-03 15:56 UTC, ujjwalpl requested changes

2021-06-03 15:56 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/event_message.py
> +    def init(cls, component: str, source: str):
line no 68 is... 
```
        """ Set the Event Message context """
```

2021-06-08 04:33 UTC, ujjwalpl approved these changes

2021-06-08 05:14 UTC, sachinpunadikar requested changes
Please work comments.
Also add test case to validate problem location & source location is working correct. One test case for not providing problem location

2021-06-08 05:43 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +                    'site_id': site_id,
Done.

2021-06-08 08:35 UTC, sachinpunadikar approved these changes
+1

2021-06-08 08:42 UTC, merged