EOS-20963 - Updated conf_cli.py for diff of all the keys between two files
Seagate/cortx-utils pull request #324
Opened 2021-06-03 12:57 UTC by balajiramachandran-seagate

Signed-off-by: Balaji Ramachandran <balaji.ramachandran@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-03 13:37 UTC, balajiramachandran-seagate commented
Test cases:
Tested for build 552 and 61.
[root@ssc-vm-c-456 conf_store]# conf yaml:///tmp/RELEASE.INFO diff yaml:///tmp/RELEASE_1.INFO -k "BUILD"
1c1
< [552]
---
> [61]

Difference in the Keys between both the release.info files.
[root@ssc-vm-c-456 conf_store]# conf yaml:///tmp/RELEASE.INFO diff yaml:///tmp/RELEASE_1.INFO
1c1
< ['NAME', 'VERSION', 'BUILD', 'OS', 'DATETIME', 'KERNEL', 'COMPONENTS[0]', 'COMPONENTS[1]', 'COMPONENTS[2]', 'COMPONENTS[3]', 'COMPONENTS[4]', 'COMPONENTS[5]', 'COMPONENTS[6]', 'COMPONENTS[7]', 'COMPONENTS[8]', 'COMPONENTS[9]', 'COMPONENTS[10]', 'COMPONENTS[11]', 'COMPONENTS[12]', 'COMPONENTS[13]', 'COMPONENTS[14]']
---
> ['NAME', 'VERSION', 'BRANCH', 'THIRD_PARTY_VERSION', 'BUILD', 'OS', 'DATETIME', 'KERNEL', 'COMPONENTS[0]', 'COMPONENTS[1]', 'COMPONENTS[2]', 'COMPONENTS[3]', 'COMPONENTS[4]', 'COMPONENTS[5]', 'COMPONENTS[6]', 'COMPONENTS[7]', 'COMPONENTS[8]', 'COMPONENTS[9]', 'COMPONENTS[10]', 'COMPONENTS[11]', 'COMPONENTS[12]', 'COMPONENTS[13]', 'COMPONENTS[14]', 'COMPONENTS[15]', 'COMPONENTS[16]']

2021-06-03 13:47 UTC, balajiramachandran-seagate commented
Test case Screen shot:

![image](https://user-images.githubusercontent.com/64014432/120655469-554f3d80-c4a0-11eb-84cc-3c919eccbc87.png)

2021-06-03 15:36 UTC, ujjwalpl requested changes

2021-06-03 15:36 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +
Remove extra lines

2021-06-03 15:36 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +            cmd = """bash -c "diff <(echo \\"%s\\") <(echo \\"%s\\")" """ %(string_1, string_2)
This line can be common for if and else.

2021-06-04 08:51 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +
Removed extra lines

2021-06-04 12:07 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +            cmd = """bash -c "diff <(echo \\"%s\\") <(echo \\"%s\\")" """ %(string_1, string_2)
Updated the line common for both if and else.
cmd = """bash -c "diff <(echo \\"%s\\") <(echo \\"%s\\")" """ %(string_1, string_2)

2021-06-09 06:31 UTC, ujjwalpl requested changes

2021-06-09 06:31 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +            ConfCli._index = "string_diff"
You can not overwrite _index as it is initialized at the time of init which is one time activity.

2021-06-09 08:37 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +            cmd = """bash -c "diff <(echo \\"%s\\") <(echo \\"%s\\")" """ %(string_1, string_2)
Done. LGTM

2021-06-09 08:46 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +            ConfCli._index = "string_diff"
Yes correct if we are processing one file at a time. If we have to process two files we have to set the index twice.

2021-06-09 08:46 UTC, venkuppu-chn commented on py-utils/src/utils/conf_store/conf_cli.py
> +
Done.

2021-06-15 06:28 UTC, balajiramachandran-seagate commented
Output:

![image](https://user-images.githubusercontent.com/64014432/122003673-058e4180-cdd1-11eb-93b5-4830caf307cd.png)

2021-06-17 05:57 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +            ConfCli._index = "string_diff"
Done. LGTM

2021-06-17 06:01 UTC, ujjwalpl requested changes

2021-06-17 06:01 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +            ConfCli._index = "string_diff"
I still see _index being modified. we can not modify _index. Its reserved for current config only.

2021-06-21 08:37 UTC, balajiramachandran-seagate commented
@ujjwalpl , Updated  _index . Please review once and let me know for any changes.

2021-06-22 09:51 UTC, balajiramachandran-seagate reviewed
@sachinpunadikar, Please review the changes.

2021-06-22 09:51 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +    def get_keys(args, index: str = None) -> list:
Updated with index parameter

2021-06-22 09:51 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +        if key_index is None:
Updated the syntax.

2021-06-22 09:51 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +        return Conf.get_keys(index, key_index=key_index)
Added the if condition

2021-06-22 09:52 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +    def get_keys(args, index: str = None) -> list:
@sachinpunadikar , Pls review the changes

2021-06-22 09:53 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +        if key_index is None:
@sachinpunadikar , Pls review the changes

2021-06-22 09:53 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +        return Conf.get_keys(index, key_index=key_index)
@sachinpunadikar , Pls review the changes

2021-06-22 14:26 UTC, ujjwalpl requested changes

2021-06-22 14:26 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +            string_2 = ConfCli.get_keys(args)
string_2 = ConfCli.get_keys(args, diff_index)

2021-06-23 07:44 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +            string_2 = ConfCli.get_keys(args)
@ujjwalpl , Updated the changes

2021-06-23 16:14 UTC, ujjwalpl approved these changes

2021-06-24 05:01 UTC, ujjwalpl approved these changes

2021-06-24 05:05 UTC, sachinpunadikar commented on py-utils/test/conf_store/test_conf_cli.py
> -
Keep this new line  .. there shd be 2 blank lines after class definition

2021-06-24 05:08 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_cli.py
> +            args.format = None
its repeat in if & else block. Take it out

2021-06-24 05:09 UTC, sachinpunadikar requested changes
Please work on the comments

2021-06-24 05:10 UTC, sachinpunadikar commented
@rahul-tripathi-git please review this PR. It has reference to get_keys

2021-06-24 13:51 UTC, suryakumar1024 commented on py-utils/test/conf_store/test_conf_cli.py
> -
We should keep blank links at end of every script files.

2021-06-24 13:52 UTC, suryakumar1024 commented on py-utils/test/conf_store/test_conf_cli.py
> +        cmd = "conf json:///tmp/file1.json diff json:///tmp/file2.json"
Kindly add test cases for negative scenarios

2021-06-24 13:53 UTC, suryakumar1024 commented on py-utils/test/conf_store/test_conf_cli.py
> +        cmd = "conf json:///tmp/file1.json diff json:///tmp/file2.json"
What if we passed like below
1) "conf json:///tmp/file1.json diff "
2) "conf json:///tmp/file1.json diff json:///tmp/not exist file"

2021-06-24 13:55 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
>          key_index = 'true' if args.key_index == None else args.key_index.lower().strip()
Shall we update this 'true' to True

2021-06-24 13:57 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_cli.py
>          key_index = True if key_index == 'true' else False if key_index == 'false' else None
Same here we update this 'true' to True.

Kindly let me know from where do we get 'false' value here

2021-06-25 01:32 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-06-25 02:43 UTC, rahul-tripathi-git commented
Hi @sachinpunadikar 
By default it will take the default deep_scan=True.

2021-06-25 08:05 UTC, balajiramachandran-seagate commented on py-utils/test/conf_store/test_conf_cli.py
> -
Done

2021-06-25 08:05 UTC, balajiramachandran-seagate commented on py-utils/src/utils/conf_store/conf_cli.py
> +            args.format = None
Done

2021-06-25 08:06 UTC, balajiramachandran-seagate commented on py-utils/test/conf_store/test_conf_cli.py
> -
Done

2021-06-28 05:54 UTC, sachinpunadikar approved these changes
+1

2021-06-28 06:47 UTC, suryakumar1024 approved these changes

2021-06-28 08:18 UTC, s-arya approved these changes

2021-06-28 09:45 UTC, mukul-seagate11 commented
@Gatekeepers, can this PR be merged as its already approved?

2021-06-28 09:53 UTC, merged