Exposed overwrite functionality for conf index load api
Seagate/cortx-utils pull request #325
Opened 2021-06-04 06:58 UTC by suryakumar1024

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-04 07:49 UTC, ujjwalpl requested changes

2021-06-04 07:49 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +    def load(index: str, url: str, **kwargs):
We need to add 3 modes
fail_reload - Fail on reload
	skip_reload - Dont reload. But Dont generate error. 
	reload - Just reload, i.e.  fail_reload = False, skip_reload = False 

Default behaviour - fail_reload = True, skip_reload = False

2021-06-07 07:00 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +    def load(index: str, url: str, **kwargs):
Updated the code in current patch

2021-06-07 07:50 UTC, ujjwalpl requested changes

2021-06-07 07:50 UTC, ujjwalpl commented on py-utils/test/conf_store/test_conf_store.py
> +
Remove extra lines. Max 2 line space.

2021-06-07 07:53 UTC, selvakumaar5496 requested changes

2021-06-07 07:53 UTC, selvakumaar5496 commented on py-utils/src/utils/conf_store/conf_store.py
> +                   Default: False
a contradiction in comments and code.
fail_reload is set to True but Default value is mentioned as False

2021-06-07 09:01 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +                   Default: False
Updated current patch

2021-06-07 09:01 UTC, suryakumar1024 commented on py-utils/test/conf_store/test_conf_store.py
> +
Updated in current patch

2021-06-07 11:37 UTC, ujjwalpl approved these changes

2021-06-07 12:05 UTC, selvakumaar5496 approved these changes

2021-06-07 13:47 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_store.py
> +        skip_reload: When True, it skips reloading a index configuration.
skip_reload: When True, it skips reloading a index configuration. If True, it overrides fail_reload

2021-06-07 13:52 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_store.py
> +        fail_reload: When True, it reloads the conf. into existing index
fail_reload: When True, and if index already exists, load() throws exception. 
                  When True, and if index do not exists, load() succeeds.
                  When false, irrespective of index status, load() succeeds

2021-06-07 13:53 UTC, sachinpunadikar requested changes
Please rectify the comments. Take help of suggestion provided.

2021-06-07 14:33 UTC, sachinpunadikar approved these changes
+1

2021-06-07 14:35 UTC, merged