WIP - EOS-20929: ConfStore Merge: Merge functionality for Conf Store
Seagate/cortx-utils pull request #326
Opened 2021-06-04 07:58 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-06 17:45 UTC, ujjwalpl requested changes

2021-06-06 17:45 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        Merges the content of src_index and dest_index file
Please highlight where does the result go, i.e. 
Merges the content of src_index and dest_index file into src_index.

2021-06-06 17:45 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        Conf._conf.merge(src_index, dest_index)
We should add CLI extension as well in separate patch.

2021-06-06 18:00 UTC, ujjwalpl requested changes

2021-06-06 18:00 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +    def merge(self, src_index: str, dest_index: str):
Accept optional parameter as keys[]. Only the keys will be merged not everything.

2021-06-07 03:21 UTC, ujjwalpl requested changes

2021-06-07 03:21 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        dest_key_max_indexes = [int(i[0]) for i in [re.findall('\d+',key)
Please ensure there is a space after every comma i the code.

2021-06-07 03:21 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        for key in self._cache[src_index].get_keys():
This is too complex algo. There is an easy way using set and get
```
for key in src.get_keys(): 
    if not key in dst.get_keys(): 
        dst.set(key, src.get(key))
```

2021-06-07 03:23 UTC, ujjwalpl requested changes

2021-06-07 03:23 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        Conf._conf.save(dest_index)
save should be left to the user. Merge is in memory only. Should be added to the spec.

2021-06-07 07:53 UTC, ujjwalpl requested changes

2021-06-07 07:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +                values = self.get_values([], self._cache[
We dont have to merge values. Its only about the keys.

2021-06-07 08:11 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +                values = self.get_values([], self._cache[
@ujjwalpl as we discussed in call, you said that result should be union of both contents. You gave a example - 
'If conf has 6 entries and .sample has 8 then conf file should have those additional entries. Existing entries should remain.'

2021-06-07 12:48 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +    def get_values(self, values: list, data: str) -> list:
get_values name gives different meaning here the API purpose is to just get value of particular List. Kindly update  the name of API.

2021-06-07 12:52 UTC, suryakumar1024 commented on py-utils/src/utils/conf_store/conf_store.py
> +        for key in data:
@ujjwalpl kindly confirm this.
Do we have to concern about what is inside list while merge operation

Eg. 
config_1 = { 'a' : [1,2,4,5] }
config_2 = { 'a' : [1,5,3,2] }

current implementation returns 

output:
{ 'a' : [1,2,4,5,3] }

Is this correct?

2021-06-07 13:12 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +                values = self.get_values([], self._cache[
@ujjwalpl Should we consider list keys?
Example keys - 
cortx>software>common>message_bus_type
cortx>software>kafka>servers[0]
cortx>software>kafka>servers[1]
cortx>software>kafka>servers[2]

2021-06-08 06:01 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        Merges the content of src_index and dest_index file
Done

2021-06-08 06:01 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        Conf._conf.merge(src_index, dest_index)
Done. Created a separate jira ticket

2021-06-08 06:02 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +    def merge(self, src_index: str, dest_index: str):
Done.

2021-06-08 06:02 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        dest_key_max_indexes = [int(i[0]) for i in [re.findall('\d+',key)
Done.

2021-06-08 06:04 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        for key in self._cache[src_index].get_keys():
Done. 
My understanding was wrong. I was merging both keys and values. Now only keys being merged

2021-06-08 06:04 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        Conf._conf.save(dest_index)
Done

2021-06-08 06:08 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +    def get_values(self, values: list, data: str) -> list:
Done.
My understanding was wrong. I was merging both keys and values. Now only keys being merged

2021-06-08 06:08 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        for key in data:
This code is removed

2021-06-08 12:29 UTC, ujjwalpl requested changes

2021-06-08 12:33 UTC, ujjwalpl requested changes

2021-06-08 12:33 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +            raise ConfError(errno.EINVAL, "config index %s is not loaded",
EINVAL = Use NOT_INITIALIZED or equivalent.

2021-06-08 12:56 UTC, ujjwalpl requested changes

2021-06-08 12:56 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +            for key in self._cache[src_index].get_keys():
Further the logic can be much simplified

```
def merge(self, dst, src, keys=None):
    for key in keys: 
        if not self._cache[src_index].get(key) : 
            raise ConfError(errno.ENOENT, "%s is not present in %s" %(key, src))
    if keys is None: 
        keys = self._cache[src_index].get_keys()
    self._merge(dst, src, keys)

def _merge(self, dst, src, keys): 
    for key in keys:
           if key not in self._cache[dest_index].get_keys():
               self._cache[dest_index].set(key, self._cache[src_index].get(key))
```

2021-06-08 16:04 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +            for key in self._cache[src_index].get_keys():
Done

2021-06-08 16:06 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +            for key in keys:
Covered in last comment

2021-06-08 16:31 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +            raise ConfError(errno.EINVAL, "config index %s is not loaded",
Done

2021-06-08 18:07 UTC, ujjwalpl requested changes

2021-06-08 18:07 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        if keys is None:
This is incorrect. Sequence needs to be reversed. 
```
        for key in keys:
            if not self._cache[src_index].get(key):
                raise ConfError(errno.ENOENT, "%s is not present in %s", \
                    key, src_index)
        if keys is None:
            keys = self._cache[src_index].get_keys()
```

2021-06-09 02:52 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        if keys is None:
If we loop keys in first place, we can get error if keys is None-
'TypeError: 'NoneType' object is not iterable'

2021-06-09 03:43 UTC, ujjwalpl requested changes

2021-06-09 03:43 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        if keys is None:
You can fix as 
```
if keys is None:
    keys = self._cache[src_index].get_keys()
else: 
    for key in keys: 
        if not self._cache[src_index].get(key): 
            raise ConfError(errno.ENOENT, "key %s not present in %s", \
                key, src_index) 
```

2021-06-09 03:55 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        if keys is None:
Done

2021-06-09 07:05 UTC, ujjwalpl approved these changes

2021-06-09 10:47 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_store.py
> +        src_index - Source Index, From which we overwriting/merging key values
src_index - Source Index, From which new keys (and related values) are picked up for merging

2021-06-09 10:47 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_store.py
> +        keys - optional parameter, Only specified keys will be merged.
keys - optional parameter, Only these keys (and related values) from src_index will be merged.

2021-06-09 11:14 UTC, sachinpunadikar requested changes
Please work on the comments

2021-06-09 11:23 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        src_index - Source Index, From which we overwriting/merging key values
Done

2021-06-09 11:23 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_store.py
> +        keys - optional parameter, Only specified keys will be merged.
Done

2021-06-09 12:15 UTC, sachinpunadikar approved these changes
+1

2021-06-14 09:57 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-06-14 10:33 UTC, merged