WIP: EOS-17772: Implementation of IEM rest interface
Seagate/cortx-utils pull request #328
Opened 2021-06-08 12:34 UTC by selvakumaar5496

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-15 12:45 UTC, ujjwalpl requested changes

2021-06-15 12:45 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/__init__.py
> +from cortx.utils.iem_framework.iem_server import IemRestHandler
Please avoid using Rest. Change to IemRequestHandler.

2021-06-15 12:49 UTC, ujjwalpl approved these changes

2021-06-16 07:11 UTC, sachinpunadikar approved these changes
+1

2021-06-16 07:14 UTC, sachinpunadikar commented
test this please

2021-06-16 11:38 UTC, merged