WIP - EOS-20261: Rest server | Logging
Seagate/cortx-utils pull request #329
Opened 2021-06-09 05:29 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- Rest server | Logging

# Design
-  [EOS-20261](https://jts.seagate.com/browse/EOS-20261)

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-09 16:02 UTC, ujjwalpl requested changes

2021-06-09 16:02 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                Log.info(f"Sending messages using {request.method} method "
Log.debug(). Info will generate excessive logging.

2021-06-09 16:02 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +            Log.info(f"Sending messages using message bus rest server's "
Log.debug().

2021-06-09 16:02 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +             backup_count=5, file_size_in_mb=5)
There should be an info level log when Rest Server starts.

2021-06-10 04:30 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                Log.error(f"Unable to send message for message_type "\
Can we log ':' separated values for better readability

Log.error(f"Unable to send message for message_type: {message_type}, status code: {status_code}, error:  {error_message}")

2021-06-10 05:53 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +             backup_count=5, file_size_in_mb=5)
Added in rest_server.py, which logs when Rest Server starts. Example log

2021-06-10 11:19:38 rest_server INFO [__init__] Rest server started on host 127.0.0.1:28300

2021-06-10 05:56 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                Log.error(f"Unable to send message for message_type "\
Done

2021-06-10 06:02 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +            Log.info(f"Sending messages using message bus rest server's "
Done

2021-06-10 06:02 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                Log.info(f"Sending messages using {request.method} method "
Done

2021-06-10 16:07 UTC, ujjwalpl requested changes

2021-06-10 16:07 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +    Log.init('rest_server', '/var/log/cortx/utils/rest_server', level='INFO',
We can not hard code level = INFO. Two options
1. Level can come from the config file with default value as INFO. There should be a way e.g. kill -HUP to reread the config to switch from INFO to debug at run time. 
2. Level can be provided as input 
Option 1 is preferred.

2021-06-14 04:16 UTC, ujjwalpl requested changes

2021-06-14 04:16 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +}
Use yaml format. Its easy to read/edit

```
utils:
  install_path: /opt/seagate
  log_level: INFO
```

2021-06-14 04:16 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +            Log.debug(f"Sending messages using message bus rest server's "
1. All incoming messages should be at log.INFO
2. Messages need to be accurate. You are not using message bus rest server. 
Message should be .. 
"Received POST request for message type %s. Processing message"

2021-06-14 04:16 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                Log.error(f"Unable to send message for message_type: " \
Since this is unknown exception... 

Log.error(f"Internal error while sending message  of type ..."

2021-06-14 04:16 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                Log.debug(f"Sending messages using {request.method} method "
print message type or any other meaningful information which will help with debugging.

2021-06-14 04:16 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +            Log.debug(f"Receiving messages using message bus rest server's "
log.info("Received GET request for message type %s..."

2021-06-14 04:16 UTC, ujjwalpl commented on py-utils/src/utils/rest_server/rest_server.py
> +        Log.info(f"Rest server started on host {host}:{port}")
Starting Message Server on host port... Avoid calling Rest.

2021-06-14 04:16 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +    Conf.load('config_file', 'yaml:///etc/cortx/cortx.conf')
Please note, sample corxt.conf.sample is in JSON. It should be in yaml. Did you test this code ?

2021-06-14 04:16 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +    Log.init('rest_server', '/var/log/cortx/utils/rest_server', \
Avoid calling rest server. REST is just a protocol. Call it message_server.

2021-06-14 07:15 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +    Log.init('rest_server', '/var/log/cortx/utils/rest_server', \
Done

2021-06-14 07:17 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +    Conf.load('config_file', 'yaml:///etc/cortx/cortx.conf')
Yes Ujjwal, I tested it, It is working. Converted cortx.conf file from json to yaml

2021-06-14 07:18 UTC, vastradparayya commented on py-utils/src/utils/rest_server/rest_server.py
> +        Log.info(f"Rest server started on host {host}:{port}")
Done

2021-06-14 07:18 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +            Log.debug(f"Receiving messages using message bus rest server's "
Done

2021-06-14 07:20 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                Log.debug(f"Sending messages using {request.method} method "
Done. Added more info for debugging

2021-06-14 07:21 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +                Log.error(f"Unable to send message for message_type: " \
Done

2021-06-14 07:21 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +            Log.debug(f"Sending messages using message bus rest server's "
Done

2021-06-14 07:39 UTC, vastradparayya commented on py-utils/cortx.conf.sample
> +}
Changed to below structure as it being used in other parts of code. Will discuss with Sachin and create a separate ticket for converting to above format
install_path: /opt/seagate
log_level: INFO

2021-06-14 07:41 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +    Log.init('rest_server', '/var/log/cortx/utils/rest_server', level='INFO',
Done. Followed option 1.

2021-06-15 10:27 UTC, vastradparayya commented on jenkins/build.sh
> +INSTALL_PATH=$(grep install_path cortx.conf.sample |  cut -d " " -f 4 | sed -e 's/^"//' -e 's/",$//')
Discussed and updated for path issue

2021-06-15 11:43 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +}
You need to fix the issue with yaml. Since you are facing ModuleNotFoundError, it means that yaml is not installed. 
sudo pip3 install pyyaml

2021-06-15 13:12 UTC, ujjwalpl requested changes

2021-06-15 13:12 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +}
In all cases, we should the following two keys
1. utils>install_path
2. utils>log_level

2021-06-16 05:59 UTC, sachinpunadikar commented on py-utils/cortx.conf.sample
> +}
@ujjwalpl, as per our discussion install_path is for CORTX and not for individual components/sub-components. So having utils specific install path is incorrect, and we should avoid that

2021-06-16 06:01 UTC, sachinpunadikar commented on py-utils/cortx.conf.sample
> +}
@ujjwalpl , about usage of YAML, even after installing yaml, setup utility fails to import it (it may be relying on some basic packages) and hence json format is being used.

2021-06-17 08:32 UTC, vastradparayya commented on py-utils/cortx.conf.sample
>    "install_path": "/opt/seagate",
https://github.com/Seagate/cortx-utils/pull/329#discussion_r652373390

2021-06-17 08:33 UTC, vastradparayya commented on py-utils/cortx.conf.sample
> +  },
https://github.com/Seagate/cortx-utils/pull/329#discussion_r652373390

2021-06-17 15:20 UTC, ujjwalpl requested changes

2021-06-17 15:20 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +    "log_level": "INFO"
Please move install_path as well into utils.

2021-06-17 15:25 UTC, ujjwalpl requested changes

2021-06-17 15:25 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/iem_server.py
> +        Log.info("Received POST request for EventMessage")
This is invalid message as it does not print any meaningful information. Delete or print meaningful information.

2021-06-17 15:25 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_server.py
> +        Log.info(f"Received GET request for message type " \
There will be milions of message requests. This will be fill log with same information in short time. Need to avoid or move to debug. Info level logging should be minimum.

2021-06-17 15:25 UTC, ujjwalpl commented on py-utils/src/utils/utils_server/utils_server.py
> +        Log.info("Starting Message Server on host,port- 127.0.0.1:28300")
There is always space after comma. OR Message can be more professional. 

Log.info("Starting Message Server on port 28300....")

2021-06-17 15:26 UTC, ujjwalpl requested changes

2021-06-17 15:26 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/iem_server.py
> +        Log.info(f"Received GET request for component " \
There will be milions of message requests. This will be fill log with same information in short time. Need to avoid or move to debug. Info level logging should be minimum.

2021-06-17 15:30 UTC, ujjwalpl requested changes

2021-06-18 04:26 UTC, ujjwalpl requested changes

2021-06-18 04:26 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +    "log_level": "INFO"
Changing my stand. Let the install_path be at the root level like it is now. 
This will be across all the components and can be used by all the components.

2021-06-18 04:28 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +}
We need to solve this problem separately. import yaml can not fail.

2021-06-18 18:51 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +        Log.info(f"Received POST request for message type " \
Done

2021-06-18 18:51 UTC, vastradparayya commented on py-utils/src/utils/iem_framework/iem_server.py
> +        Log.info(f"Received GET request for component " \
Done

2021-06-18 18:51 UTC, vastradparayya commented on py-utils/src/utils/utils_server/utils_server.py
> +        Log.info("Starting Message Server on host,port- 127.0.0.1:28300")
Done

2021-06-18 18:51 UTC, vastradparayya commented on py-utils/src/utils/message_bus/message_bus_server.py
> +        Log.info(f"Received GET request for message type " \
Done

2021-06-18 18:52 UTC, vastradparayya commented on py-utils/src/utils/iem_framework/iem_server.py
> +        Log.info("Received POST request for EventMessage")
Removed the log

2021-06-28 17:17 UTC, sachinpunadikar commented on py-utils/src/utils/iem_framework/iem_server.py
> +            Log.debug(f"Subscribed to component {component} and received " \
Suggestion - 
            Log.debug(f"GET method finished with status code: {status_code}" \
            f"for component {component} and received " \
                f"event message alert info. - {alert['iem']['info']}. " )

2021-06-28 17:18 UTC, sachinpunadikar requested changes
Work on suggestion

2021-06-28 17:36 UTC, vastradparayya commented on py-utils/src/utils/iem_framework/iem_server.py
> +            Log.debug(f"Subscribed to component {component} and received " \
Done

2021-06-29 14:00 UTC, ujjwalpl approved these changes

2021-06-29 14:03 UTC, sachinpunadikar approved these changes
+1

2021-06-29 18:51 UTC, merged