<WIP> EOS-13787:[Enabler] NFS ADDB: Explore how to implement add2db.py, nfs_req.py and hist.py for CORTXFS FSAL Operations (phase 1, addb2db_nfs.py)
Seagate/cortx-utils pull request #33
Opened 2020-10-04 21:52 UTC by pratyush-seagate

commit 8a96b6ef51123e771030e9c7cd8acf80c65998e0
Author: pratyush-seagate <pratyush.k.khan@seagate.com>
Date:   Sun Oct 4 15:40:30 2020 -0600

            EOS-13787:[Enabler] NFS ADDB: Explore how to implement add2db.py, nfs_req.py and hist.py for CORTXFS FSAL Operations (phase 1, addb2db_nfs.py)
            List of modified files:
                new file:   addb2db_nfs.py
            Change description:
                    Add python script to read and convert the text performance dump to sql database file
            Unit test:
                Based on EOS-8947, using the new script, read the filtered text dump file containing the new
                nfs-cortxfs performance counters (state, map and attribute) and create a sql3 database file.
                Verify the sql3 database file is ok.
                test O/P:
                        cd /home/751521/EOS-13787
                        m0addb2dump -p /usr/lib64/libcortx-utils.so -- /$(ls -t addb* | head -n 1 | sed 's/://')/o/100000000000000\:2 | grep fsuser &> perfc_raw_dump
                        python3 /home/751521/repos/github/repo4/cortx-posix/utils/c-utils/src/addb/addb2db_nfs.py --dumps ./perfc_raw_dump --db DB2
                        # ll
                        total 13664
                        -rw-r--r-- 1 root root 11476077 Oct  4 15:37 addb_27527.tar.gz
                        -rw-r--r-- 1 root root   963584 Oct  4 15:39 DB2
                        -rw-r--r-- 1 root root      395 Oct  4 15:39 logfile.txt
                        -rw-r--r-- 1 root root  1541590 Oct  4 15:38 perfc_raw_dump

                        sqlite3 ./DB2
                        sqlite> .schema
                                CREATE TABLE "entity_attributes" ("id" INTEGER NOT NULL PRIMARY KEY, "pid" INTEGER NOT NULL, "time" INTEGER NOT NULL, "tsdb_mod" TEXT NOT NULL, "fn
                                CREATE TABLE "entity_maps" ("id" INTEGER NOT NULL PRIMARY KEY, "pid" INTEGER NOT NULL, "time" INTEGER NOT NULL, "tsdb_mod" TEXT NOT NULL, "fn_tag"
                                CREATE TABLE "entity_states" ("id" INTEGER NOT NULL PRIMARY KEY, "pid" INTEGER NOT NULL, "time" INTEGER NOT NULL, "tsdb_mod" TEXT NOT NULL, "fn_tag

                        sqlite> select * from "entity_states";
                        ....
                        5330|14|1601437968920457574|fsuser_state|fsal_read|state|30133|finish

                        sqlite> select * from "entity_attributes";
                        ....
                        6273|14|1601437968920456127|fsuser_attribute|fsal_read|attribute|30133|read_result_major_code|0

                        sqlite> select * from "entity_maps";
                        ....
                        2510|14|1601437968918784740|fsuser_map|kvs_alloc|map|16|0|30133

                Note: python3 libs needed: sudo pip3 install numpy plumbum  tqdm peewee

2020-10-05 11:59 UTC, vimalraghwani20 reviewed
IMO, We need to follow the folder structure of S3 for decoder plugin and scripts.
addb/plugin/
addb/addb-py/chronometry/

2020-10-05 12:03 UTC, vimalraghwani20 approved these changes
I tried using this script and able to create a database with the records.
Patch looks good to me

2020-10-06 06:38 UTC, Shreya-18 commented on c-utils/src/addb/addb2db_nfs.py
> +    def clean_yaml(yml):
I see this `clean_yaml(yml):` is not being used anywhere. Could you please check whether it can be removed?

2020-10-06 06:39 UTC, Shreya-18 commented on c-utils/src/addb/addb2db_nfs.py
> +import yaml
Also, can this import yaml can be removed if not used?

2020-10-06 06:42 UTC, Shreya-18 commented on c-utils/src/addb/addb2db_nfs.py
> +    def __init__(self, what):
Can we have a one-liner comment describing the **user-defined** context manager class here?

2020-10-06 09:33 UTC, pratyush-seagate commented
@Shreya-18  addressed all the review comments.
@sachinpunadikar  @AtitaShirwaikar  all the codacy comments are resolved except the last one, this is due to https://github.com/PyCQA/pydocstyle/issues/141
IMO, we should disable this check due to the conflicting rules.

![image](https://user-images.githubusercontent.com/67319330/95184455-03f19000-07e5-11eb-95ff-605770040cef.png)

2020-10-06 09:44 UTC, Shreya-18 approved these changes
Looks good to me. Nice usage of context managers for resource handling. +1 from my side.

2020-10-06 10:34 UTC, sachinpunadikar commented on c-utils/src/addb/addb2db_nfs.py
> +#
wondering whether should be part of py-utils folder ?
or check with S3 team on how they are processing ADDB captured data

2020-10-06 11:00 UTC, pratyush-seagate commented on c-utils/src/addb/addb2db_nfs.py
> +#
Thanks Sachin, let me refactor this code and update the PR.

2020-10-06 14:14 UTC, pratyush-seagate commented on c-utils/src/addb/addb2db_nfs.py
> +#
Hi Sachin,
The python script is now moved to py-utils and added to py-utils build.
Regarding the refactoring, after looking into details, it might take more time to decouple the NFS performance counters and create sub-modules. The S3 team's scripts are also not refactored. If it is ok with you, can I create a JIRA story to track the future refactoring work to make these scripts more modular?

2020-10-06 15:00 UTC, pratyush-seagate commented on c-utils/src/addb/addb2db_nfs.py
> +#
The JIRA story created to track the end to end documentation work: https://jts.seagate.com/browse/EOS-14033
The JIRA story created to track the refactoring work for python scripts: https://jts.seagate.com/browse/EOS-14034

2020-10-06 16:08 UTC, sachinpunadikar commented on py-utils/src/utils/addb/addb2db_nfs.py
> +#
Shouldn't the name of script be adddb2db_cortxfs ? I do not see anywhere it is only for NFS

2020-10-06 16:10 UTC, sachinpunadikar commented on py-utils/setup.py
> +                'cortx.utils.addb',
Remove from here .. as this will affect the package cortx.utils , which is being used by other teams. We need to be in agreement with other team before changing anything there.
I hope we can use the scripts in standalone method

2020-10-06 16:11 UTC, sachinpunadikar requested changes
Please work on review comments

2020-10-06 16:20 UTC, pratyush-seagate commented on py-utils/setup.py
> +                'cortx.utils.addb',
Done

2020-10-06 16:20 UTC, pratyush-seagate commented on py-utils/src/utils/addb/addb2db_nfs.py
> +#
Done

2020-10-06 16:21 UTC, pratyush-seagate commented
> 
> 
> Please work on review comments

Done

2020-10-06 16:25 UTC, sachinpunadikar approved these changes
+1

2020-10-06 16:28 UTC, merged