WIP: Message Bus Logger implementation
Seagate/cortx-utils pull request #330
Opened 2021-06-10 06:54 UTC by suryakumar1024

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-15 09:08 UTC, selvakumaar5496 reviewed
Instead of **successfully completed**, can we have what is completed?
 For ex: Topic created successfully

2021-06-15 12:55 UTC, ujjwalpl requested changes

2021-06-15 12:55 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +        Log.info(f"MessageBrokerFactory: involked with arguments broker_type:" \
We shouldnt be printing lot of info level logs. Change to debug level, i.e. log.debug(...)

2021-06-15 12:55 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +            Log.info(f"Successfully returned existing {broker_type} " \
Remove this or merge this log with the previous one. We need to avoid printing excessive logs.

2021-06-15 12:55 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker.py
> +                    Log.debug(f"Successfully created and returned " \
This is not required. If no error is returned, it means call returned successfully. Entry level log is enough.

2021-06-15 12:55 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.info(f"KafkaMessageBroker: initialized with broker " \
log.debug(...). Main MessageBus should have info at one place. Try to dissable debug and check there should be only one line printed for a session.

2021-06-15 12:55 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                Log.debug("Successfully initialized AdminClient()")
Remove this code. Avoid excessive logging without any meaningful information printed.

2021-06-15 12:55 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        Log.info(f"MessageBusClient: initialized with arguments" \
log.debug(..) Message Client is going to be initialized many times by many modules. Can be debug level.

2021-06-16 12:09 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker.py
> +        Log.info(f"MessageBrokerFactory: involked with arguments broker_type:" \
Updated in current patch.

2021-06-16 12:09 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker.py
> +            Log.info(f"Successfully returned existing {broker_type} " \
Updated in current patch.

2021-06-16 12:10 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker.py
> +                    Log.debug(f"Successfully created and returned " \
Updated in current patch.

2021-06-16 12:10 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.info(f"KafkaMessageBroker: initialized with broker " \
Updated in current patch.

2021-06-16 12:11 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                Log.debug("Successfully initialized AdminClient()")
Removed. Updated in current patch.

2021-06-16 12:11 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        Log.info(f"MessageBusClient: initialized with arguments" \
Updated in current patch.

2021-06-16 16:11 UTC, ujjwalpl requested changes

2021-06-16 16:11 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    Log.debug(f"Received messages: {msg.value()}")
Message may have password or sensitive information. We should avoid printing message.

2021-06-16 16:11 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug(f"Involked with arguments admin_id={admin_id}, " \
Message needs to be more clear, Example: 
Log.debug("Register message type {message_type} using {admin_id} with partitions")

2021-06-16 16:11 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug(f"Successfully Created given list of message types.")
Remove this message. If there is no error then its assumed to be success. This message does not print any variable.

2021-06-16 16:11 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug(f"Involked with admin_id:" \
Same here. Please make message more meaningful like "deregistering message type...."

2021-06-16 16:11 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    Log.debug(f"Successfully deleted given list of message" \
Same here. Remove this message as it does not print any value.

2021-06-17 06:59 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    Log.debug(f"Received messages: {msg.value()}")
Removed and Updated in current patch.

2021-06-17 07:00 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug(f"Involked with arguments admin_id={admin_id}, " \
All the log messages updated in current patch

2021-06-17 07:00 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug(f"Successfully Created given list of message types.")
Removed and updated in current patch

2021-06-17 07:01 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug(f"Involked with admin_id:" \
Updated all the messages to give informative information in meaningful way. updated in current patch

2021-06-17 07:02 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    Log.debug(f"Successfully deleted given list of message" \
Removed and updated in current patch.

2021-06-23 04:25 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-06-29 04:02 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker.py
> +        Log.debug(f"MessageBrokerFactory: involked with arguments broker_type:" \
involked -> invoked

2021-06-29 10:56 UTC, ujjwalpl requested changes

2021-06-29 10:56 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +  "log_level": {
"utils" { 
    "log_level": "INFO"
}

2021-06-29 14:45 UTC, suryakumar1024 commented on py-utils/cortx.conf.sample
> +  "log_level": {
Updated in recent patch

2021-06-29 14:45 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker.py
> +        Log.debug(f"MessageBrokerFactory: involked with arguments broker_type:" \
Updated in recent patch

2021-06-29 17:03 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-06-30 06:13 UTC, ujjwalpl approved these changes

2021-06-30 07:03 UTC, sachinpunadikar approved these changes
+1

2021-06-30 07:26 UTC, selvakumaar5496 approved these changes

2021-06-30 11:12 UTC, merged