Eos 20346 support bundle movement
Seagate/cortx-utils pull request #333
Opened 2021-06-10 09:36 UTC by udayan-y21

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-15 14:35 UTC, ujjwalpl requested changes

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +  "install_path": "/opt/seagate",
Please use following keys 
```
utils>install_path
support>support_bundle_path
support>tmp_path
```

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            Conf.set("cluster", f"node_host_mapping>{node_name}", hostname)
Where is "cluster" loaded ? If its outside of this code then it must be passed as input and not hard coded here. 
Instead of "node_host_mapping" call it "cluster" because this is going to be cluster information.

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        for _, node_data in cluster_data.items():
Instead of this complex logic use Conf.copy()

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Utils._set_cluster_hostname_nodename_mapping(conf_url)
Name _set_cluster_hostname_nodename_mapping is big and specific. Must be generic. 

Utils._copy_cluster_map(in_conf_index, out_conf_index)

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/src/utils/errors.py
> +class InvalidRequest(BaseError):
We need to move away from extending errors. Please use module specific exception.

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/0-support_bundle.conf
> +# CORTX-Py-Utils: CORTX Python common library.
Change the containing directory name to support to represent support tools.

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/0-support_bundle.conf
> +#$ModLoad imudp
Remove commented code or uncomment and use them or add enough comments about their usage.

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/setup_path.yaml
> +  health_map:
We need to create support.yaml. We should not use setup.yaml and overload that for support.

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/setup_path.yaml
> +  s3server:
Also, need to standardize the paths. So config should only contain in the input config file, i.e. cortx.conf 

support>component_list = [ "motr", "s3server", ...] 

We should scan the list and construct the path on the fly. This file should be dissolved.

2021-06-15 14:35 UTC, ujjwalpl commented on py-utils/utils-post-install
> +sed -i -e "s|<CORTX_PATH>|${cortx_path}|g" $utils_path/conf/setup_path.yaml
we should not mix setup with support. Also, need to avoid setup_path.yaml. It should be constructed on the fly.

2021-06-18 05:42 UTC, udayan-y21 commented on py-utils/src/setup/utils.py
> +        for _, node_data in cluster_data.items():
Reason behind adding for loop is .. For N-node.. (N>1)
Loop over server info and collect all minionid and hostname
ex: 
``` 
{
srvnode-1: srvnode1.FQDN.colo.seagate.com,
srvnode-2: srvnode2.FQDN.colo.seagate.com,
srvnode-3: srvnode3.FQDN.colo.seagate.com
}
```

`Conf.copy("source-index", "dest-index", [list-of-keys])` requires list of keys which will include `server_node>{machinid}` where machineid of other node is difficult to predict.

2021-06-18 05:50 UTC, udayan-y21 commented on py-utils/src/setup/utils.py
> +            Conf.set("cluster", f"node_host_mapping>{node_name}", hostname)
>Where is "cluster" loaded ?

Its loaded in another method which is called before this method. 

> Instead of "node_host_mapping" call it "cluster" because this is going to be cluster information.

Okay

2021-06-21 09:39 UTC, udayan-y21 commented on py-utils/src/utils/support_bundle/bundle_generate.py
> +        Log.init("support_bundle",
Moved Log,init to __init__.py

2021-06-21 09:43 UTC, udayan-y21 commented on py-utils/src/utils/support_bundle/setup_path.yaml
> +  health_map:
Currently all components have there support_bundle commands in setup.yaml. For the change we need to ask all the components to create there support.yaml and add the support_bundle cmd in it.
We will create the seperate ticket of componenet to create and publish support .yaml details. Will consider this task in future sprint.

2021-06-21 09:44 UTC, udayan-y21 commented on py-utils/src/utils/support_bundle/setup_path.yaml
> +  s3server:
[COPYING THE COMMENT FROM LAST ONE]
> Currently all components have there support_bundle commands in setup.yaml. For the change we need to ask all the components to create there support.yaml and add the support_bundle cmd in it.
We will create the seperate ticket of componenet to create and publish support .yaml details. Will consider this task in future sprint.

2021-06-21 10:00 UTC, udayan-y21 commented on py-utils/utils-post-install
> +sed -i -e "s|<CORTX_PATH>|${cortx_path}|g" $utils_path/conf/setup_path.yaml
The time when the change for setup.yaml will be taken in future sprint, this line will be removed.

2021-06-21 11:21 UTC, ujjwalpl requested changes

2021-06-21 11:21 UTC, ujjwalpl commented on py-utils/utils-post-install
> +sed -i -e "s|<CORTX_PATH>|${cortx_path}|g" $utils_path/conf/setup_path.yaml
Its just a matter of using support.yaml instead of setup.yaml.

2021-06-21 11:35 UTC, ujjwalpl requested changes

2021-06-21 11:35 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +    "utils": {
Looks like we need to revert this change so that install_path can be common to all the components.  
```
"install_path": "/opt/seagate"
```

2021-06-21 11:35 UTC, ujjwalpl commented on py-utils/src/utils/support/support_bundle.py
> +    async def fetch_active_nodes_hosts():
Rename to get_active_nodes()

2021-06-21 11:35 UTC, ujjwalpl commented on py-utils/src/utils/support/support_bundle.py
> +    async def bundle_generate(command) -> sys.stdout:
Rename to generate_bundle()

2021-06-21 11:35 UTC, ujjwalpl commented on py-utils/src/utils/support/support_bundle.py
> +    async def bundle_status(command):
Rename to get_bundle_status()

2021-06-21 14:23 UTC, udayan-y21 commented on py-utils/src/utils/support/support_bundle.py
> +    async def bundle_status(command):
Modifications done

2021-06-21 14:24 UTC, udayan-y21 commented on py-utils/src/utils/support/support_bundle.py
> +    async def bundle_generate(command) -> sys.stdout:
Modifications done

2021-06-21 14:24 UTC, udayan-y21 commented on py-utils/src/utils/support/support_bundle.py
> +    async def fetch_active_nodes_hosts():
Modifications done

2021-06-21 14:24 UTC, udayan-y21 commented on py-utils/cortx.conf.sample
> +    "utils": {
Modifications done

2021-06-21 14:24 UTC, udayan-y21 commented on py-utils/utils-post-install
> +sed -i -e "s|<CORTX_PATH>|${cortx_path}|g" $utils_path/conf/setup_path.yaml
Modifications done

2021-06-21 14:25 UTC, udayan-y21 commented on py-utils/src/utils/support_bundle/0-support_bundle.conf
> +#$ModLoad imudp
Modifications done

2021-06-21 14:25 UTC, udayan-y21 commented on py-utils/src/setup/utils.py
> +        Utils._set_cluster_hostname_nodename_mapping(conf_url)
Modifications done

2021-06-21 14:25 UTC, udayan-y21 commented on py-utils/cortx.conf.sample
> +      "symlink_path": "/tmp/support_bundle/"
Modifications done

2021-06-21 16:46 UTC, udayan-y21 commented on py-utils/cortx.conf.sample
> +  "install_path": "/opt/seagate",
Modifications done

2021-06-21 17:40 UTC, ujjwalpl requested changes

2021-06-21 17:40 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        with open(r'/etc/cortx/cluster.conf.sample', 'w+') as file:
We should not update  conf.sample. Its read only and not available for edits.

2021-06-21 17:43 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/setup_path.yaml
> +  health_map:
All the components will use move the definition from setup.yaml to support.yaml. This is a small patch.

2021-06-21 17:45 UTC, ujjwalpl requested changes

2021-06-21 17:45 UTC, ujjwalpl commented on py-utils/src/utils/support/__init__.py
> +Log.init("support_bundle",
We can not include global code. Log.init must be somewhere where init is called.

2021-06-21 18:33 UTC, ujjwalpl requested changes

2021-06-21 18:33 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Utils._copy_cluster_map()
We need to reflect cluster conf to the actual conf file and not to the sample conf.

2021-06-25 07:26 UTC, udayan-y21 commented on py-utils/src/setup/utils.py
> +        Utils._copy_cluster_map()
Modification done.
First coped sample file to /etc/cortx location and then /etc/cortx/cluster.conf file is modified.
Sample file kept as it is

2021-06-25 07:26 UTC, udayan-y21 commented on py-utils/src/utils/support/__init__.py
> +Log.init("support_bundle",
Modifications done. 
Added in init() method

2021-06-25 07:27 UTC, udayan-y21 commented on py-utils/src/setup/utils.py
> +        with open(r'/etc/cortx/cluster.conf.sample', 'w+') as file:
Modification done.
First coped sample file to /etc/cortx location and then /etc/cortx/cluster.conf file is modified.
Sample file kept as it is

2021-06-29 11:23 UTC, ujjwalpl approved these changes

2021-06-29 14:05 UTC, sachinpunadikar approved these changes
+1

2021-06-29 14:07 UTC, sachinpunadikar commented
VM deployment can be skipped as this is just code addition. The code is not going to get executed

2021-06-29 14:07 UTC, merged