WIP - EOS-21062: ConfStore: Support "merge" option in conf CLI
Seagate/cortx-utils pull request #335
Opened 2021-06-14 12:56 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- ConfStore: Support "merge" option in conf CLI

# Design
-  [EOS-21062](https://jts.seagate.com/browse/EOS-21062)

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-16 04:15 UTC, ujjwalpl requested changes

2021-06-16 04:15 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        ConfCli._index = 'src_index'
Please avoid changing _index. Add a new interface for handling this. 
```
def _load(index, url): 
    Conf.load(index, url)
```

2021-06-17 12:25 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_cli.py
> +        ConfCli._index = 'src_index'
Done

2021-06-17 15:18 UTC, ujjwalpl requested changes

2021-06-17 15:18 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +        src_index = 'src_index'
src_index should be declared earlier, i.e.. 
```
src_index = 'src_index'
dest_index = ConfCli._index
ConfCli.load(args.src_url, src_index)
....
```

2021-06-18 03:39 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_cli.py
> +        src_index = 'src_index'
Done

2021-06-18 05:47 UTC, ujjwalpl approved these changes

2021-06-18 09:56 UTC, sachinpunadikar commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "Merges contents of source and destination conf files\n."
Merges contents of source file into destination conf files\n.

2021-06-18 10:19 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "Merges contents of source and destination conf files\n."
Done

2021-06-18 10:19 UTC, vastradparayya commented on py-utils/src/utils/conf_store/conf_cli.py
> +        """ merges source and dest. conf files """
Done

2021-06-18 10:29 UTC, sachinpunadikar approved these changes
+1

2021-06-18 11:57 UTC, selvakumaar5496 approved these changes

2021-06-18 11:58 UTC, sachinpunadikar commented
Deployment is successful 
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/PyUtils/502/

2021-06-18 11:58 UTC, merged