WIP: Msg setup test
Seagate/cortx-utils pull request #336
Opened 2021-06-15 10:15 UTC by suryakumar1024

# Problem Statement
- Swap kafka topic script with message bus admin in message_bus_test.py

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-15 11:17 UTC, selvakumaar5496 commented on py-utils/src/setup/msg_bus_test.py
>          self._server = Conf.get("index",'message_broker>cluster[0]>server')
These are unused and can be removed

from cortx.utils.conf_store import Conf
Conf.load("index", "json:///etc/cortx/message_bus.conf")        
self._server = Conf.get("index",'message_broker&gt;cluster[0]&gt;server')

2021-06-15 11:18 UTC, selvakumaar5496 commented on py-utils/src/setup/msg_bus_test.py
> +            if "mytest" not in list_topic:
if **"mytest"** not in list_topic: --> **'mytest'**

2021-06-15 12:28 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
>          self._server = Conf.get("index",'message_broker>cluster[0]>server')
Updated in recent patch commit.

2021-06-15 12:31 UTC, vastradparayya commented on py-utils/src/setup/msg_bus_test.py
> +            admin = MessageBusAdmin(admin_id = 'admins')
Are spaces required (admin_id = 'admins')?
@suryakumar1024 @selvakumaar5496

2021-06-15 12:35 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +            if "mytest" not in list_topic:
Updated in recent patch commit.

2021-06-15 12:35 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +            admin = MessageBusAdmin(admin_id = 'admins')
Updated in recent patch commit.

2021-06-21 08:12 UTC, selvakumaar5496 commented on py-utils/src/setup/msg_bus_test.py
>          # Create a test topic
Create a test message_type

2021-06-21 08:14 UTC, selvakumaar5496 commented on py-utils/src/setup/msg_bus_test.py
> +            admin = MessageBusAdmin(admin_id='admins')
Can have some meaningful admin_ id.
For ex : admin_id='register'

2021-06-21 08:15 UTC, selvakumaar5496 commented on py-utils/src/setup/msg_bus_test.py
> +            list_topic = admin.list_message_types()
change list_topic -> list_message_type
Use message_type instead of topic wherever it applies

2021-06-21 08:16 UTC, selvakumaar5496 commented on py-utils/src/setup/msg_bus_test.py
> +            admin = MessageBusAdmin(admin_id='admins')
Can have some meaningful admin_ id.
For ex : admin_id='deregister'

2021-06-21 09:59 UTC, rahul-tripathi-git reviewed
Wherever there is topic, please swap it with message_type/s.
Instead of EINVAL, please check for a more relevant return code.


Consider the comments as suggestions, please use your best judgement to cater these.

2021-06-21 09:59 UTC, rahul-tripathi-git commented on py-utils/src/setup/msg_bus_test.py
> +                    "Topic creation failed.")
1. Maybe we should provide the topic name/message_type in the error message?
2. Instead of topic creation failed, we should mention, "Failed to create message_type".

@selvakumaar5496, please suggest.

2021-06-21 09:59 UTC, rahul-tripathi-git commented on py-utils/src/setup/msg_bus_test.py
> +                raise SetupError(errno.EINVAL, "Failed to test the config." \
Kindly use a more relevant error code if there is one, rather than EINVAL

2021-06-21 09:59 UTC, rahul-tripathi-git commented on py-utils/src/setup/msg_bus_test.py
> +                             "Failed to test the config, %s", e)
Same goes for this error code

2021-06-21 10:14 UTC, selvakumaar5496 commented on py-utils/src/setup/msg_bus_test.py
> +                    "Topic creation failed.")
@rahul-tripathi-git , I have already posted comments regarding the same. (changing topic to message_type).
And I agree, It is good to have the message_type in error message.

2021-06-22 20:57 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +            admin = MessageBusAdmin(admin_id='admins')
Updated in recent patch.

2021-06-22 20:57 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +            list_topic = admin.list_message_types()
Updated in recent patch.

2021-06-22 20:57 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +            admin = MessageBusAdmin(admin_id='admins')
Updated in recent patch.

2021-06-22 20:57 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
>          # Create a test topic
Updated in recent patch.

2021-06-22 20:58 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +                    "Topic creation failed.")
Updated in recent patch.

2021-06-23 04:20 UTC, selvakumaar5496 requested changes

2021-06-23 04:20 UTC, selvakumaar5496 commented on py-utils/src/setup/msg_bus_test.py
> +                             "Failed to test the config, %s", e)
take care of indentation as well

2021-06-25 06:19 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +            admin.register_message_type(message_types=['mytest'], partitions = 1)
Updated in recent patch changes

2021-06-25 06:20 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +                             "Failed to test the config, %s", e)
Updated in recent patch changes

2021-06-25 06:20 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +                raise SetupError(errno.EINVAL, "Failed to test the config." \
Updated in recent patch changes

2021-06-28 13:57 UTC, sachinpunadikar approved these changes
+1

2021-06-29 08:46 UTC, selvakumaar5496 commented on py-utils/src/setup/msg_bus_test.py
> +                    " config. Deregister messge_type: mytest failed")
Dereigster **message_type**

2021-06-29 11:05 UTC, ujjwalpl commented on py-utils/src/setup/msg_bus_test.py
> +                raise SetupError(errors.ERR_OP_FAILED, "Failed to receive messages" \
Print consumer_id and other details which are used to receive on the channel for debugging. without these details it wont be possble to debug.

2021-06-29 14:35 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +                raise SetupError(errors.ERR_OP_FAILED, "Failed to receive messages" \
Updated exception message.

2021-06-29 14:35 UTC, suryakumar1024 commented on py-utils/src/setup/msg_bus_test.py
> +                    " config. Deregister messge_type: mytest failed")
updated in recent patch

2021-06-29 17:08 UTC, rahul-tripathi-git approved these changes
+1

2021-06-30 04:25 UTC, selvakumaar5496 approved these changes

2021-06-30 14:52 UTC, ujjwalpl approved these changes

2021-07-01 14:16 UTC, merged