EOS-20902: SimpleProcess().run() produces incorrect output/ does not split the cmd string correctly
Seagate/cortx-utils pull request #338
Opened 2021-06-21 07:19 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- SimpleProcess().run() produces incorrect output/ does not split the cmd string correctly
- **BUG**

# Design
-  https://jts.seagate.com/browse/EOS-20902

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-21 08:12 UTC, vastradparayya commented on py-utils/src/utils/process.py
> -            cmd = self._cmd.split() if type(self._cmd) is str else self._cmd
Previous output was - 
cmd = '/usr/bin/ipmisimtool sdr type "Fan"'
['/usr/bin/ipmisimtool', 'sdr', 'type', '"Fan"']

2021-06-21 08:13 UTC, vastradparayya commented on py-utils/src/utils/process.py
> +            cmd = shlex.split(self._cmd) if isinstance(self._cmd, str) else self._cmd
Present output - 
cmd = '/usr/bin/ipmisimtool sdr type "Fan"'
['/usr/bin/ipmisimtool', 'sdr', 'type', 'Fan']

2021-06-21 08:43 UTC, ujjwalpl requested changes

2021-06-21 08:43 UTC, ujjwalpl commented on py-utils/src/utils/process.py
> +        import shlex
Is shlex a new dependency ? If so, we need to avoid adding new dependency.

2021-06-21 08:44 UTC, vastradparayya commented on py-utils/src/utils/process.py
> +        import shlex
No @ujjwalpl . It is inbuilt library

2021-06-21 09:07 UTC, rahul-tripathi-git requested changes
Kindly cater PipedProcess class as well with the similar (shlex) splitting.

2021-06-21 09:52 UTC, vastradparayya commented
> Kindly cater PipedProcess class as well with the similar (shlex) splitting.

@rahul-tripathi-git Done.

2021-06-23 04:15 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-06-28 17:36 UTC, sachinpunadikar commented on py-utils/src/utils/process.py
> +import shlex
Is this a new package ?

2021-06-28 17:41 UTC, vastradparayya commented on py-utils/src/utils/process.py
> +import shlex
No @sachinpunadikar , It is in built package in python3.

2021-06-29 09:06 UTC, sachinpunadikar approved these changes
+1

2021-06-29 13:59 UTC, ujjwalpl approved these changes

2021-06-29 19:18 UTC, merged