EOS-20937: Add store url argument support in generate node health
Seagate/cortx-utils pull request #339
Opened 2021-06-21 16:02 UTC by mariyappanp

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-22 14:30 UTC, ujjwalpl requested changes

2021-06-22 14:30 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +  "discovery": {
As per the discussion, we need to derive this path from the solution (product) name. This configuration will be be removed.

2021-06-24 09:45 UTC, mariyappanp commented on py-utils/cortx.conf.sample
> +  "discovery": {
Done. Please review this again.

2021-06-24 10:29 UTC, ujjwalpl approved these changes

2021-06-24 11:09 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +                    errno.EINVAL,
>errno.ENOENT
No such file or directory

suits better here

2021-06-24 11:09 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
>          raise DiscoveryError(
raise will be invoked irrespective of the if condition above. It should be under else case i believe

2021-06-24 11:29 UTC, mariyappanp commented on py-utils/cortx.conf.sample
> +  "product_id": "lr_r2",
This is referred as the package name later. 
os.path.join(solution_platform_monitor, product_id)

Thats why this naming convention followed based on Ujjwal's suggestion.
Otherwise we need to have mapping in code.

2021-06-24 11:42 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +os.makedirs(common_config.get(["discovery>resource_map>location"])[0], exist_ok=True)
If this directory already exists or user has sudo privilege, this won't fail on permission.
Otherwise, we should raise exception like below
```
try:
    os.makedirs(common_config.get(["discovery>resource_map>location"])[0], exist_ok=True)
except PermissionError as err:
    raise DiscoveryError(errno.EACCES, "Failed to create default response store directory. %s" % err)
```
So the output message will be:
`DiscoveryError: Failed to create default response store directory.  [Errno 13] Permission denied: '/var/cortx/resources/test'`

shall I add the above @cdeshmukh ?

2021-06-24 11:49 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +        elif not store_url and rpath:
It is always non-null from `Discovery.generate_node_health` to `node_health.generate`.

req_id id will be used in store_url name only when user don't send custom store_url. 
So  `elif not store_url and rpath:` is taking care of it. Otherwise static url which doesn't need req_id.

2021-06-24 11:49 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +                    errno.EINVAL,
Okay, I will address it.

2021-06-24 11:53 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
>          raise DiscoveryError(
No, if the expected resource class name is not matched in members list, we expect error thrown. If matched, return from the function. Its a validation kind of. Let me know if comment line before this exception or clarification is needed still.

2021-06-24 12:35 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +os.makedirs(common_config.get(["discovery>resource_map>location"])[0], exist_ok=True)
Done. @cdeshmukh

2021-06-24 12:35 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +            NodeHealth.add_dm_request(rpath, req_id, store_url)
Done.

2021-06-24 12:35 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +                    errno.EINVAL,
Done.

2021-06-24 18:20 UTC, cdeshmukh approved these changes

2021-06-24 18:20 UTC, cdeshmukh commented on py-utils/cortx.conf.sample
> +  "product_id": "lr_r2",
you mean current 'product_id' value is lr_r2, given by provisioner? Then lets keep a TODO to change it LRR2, and address it when provisioner does the change too

2021-06-24 18:20 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +except PermissionError as err:
permission issue was one example. other possible exception from this api is FileExistsError, though in that case we dont need to act, so we are covered there

2021-06-24 18:20 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +        elif not store_url and rpath:
got it, thanks

2021-06-24 18:20 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
>          raise DiscoveryError(
ok, i missed reading 'return' there. its fine

2021-06-25 05:25 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +                errno.EINVAL,
errno.ENODATA
No data available

would serve better

2021-06-25 07:59 UTC, mariyappanp commented on py-utils/cortx.conf.sample
> +  "product_id": "lr_r2",
Nitin asked me to refer ConfStore for product
'release>product' ==> "LR2"
@cdeshmukh 
What I should take, LR2 or LR_R2?

2021-06-25 08:13 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
> +                errno.EINVAL,
I think `ENOENT - No such file or directory` can suit for module not found.

2021-06-25 08:38 UTC, cdeshmukh commented on py-utils/cortx.conf.sample
> +  "product_id": "lr_r2",
Use the name what exist today, LR2 then

2021-06-25 08:39 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +                errno.EINVAL,
>ENOENT - No such file or directory

How this make sense to api consumer, it didnt ask for any file but health data

2021-06-25 08:52 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
> +                errno.EINVAL,
This is just doing only module import, @cdeshmukh. Nothing related to health data response.
`module.get_health_info()` is after this.

2021-06-25 10:00 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +                errno.EINVAL,
As discussed, lets keep same errno (given no existing errno relates to this config error), but in exception message, update it to reflect clearly as config error

2021-06-25 11:06 UTC, mariyappanp commented on py-utils/cortx.conf.sample
> +  "product_id": "lr_r2",
Done.

2021-06-25 11:27 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +except PermissionError as err:
ok

2021-06-25 11:35 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
> +                errno.EINVAL,
Acknowledged.

2021-06-25 11:39 UTC, cdeshmukh approved these changes
Resolve my comments, as am not getting that option

2021-06-25 17:22 UTC, sachinpunadikar approved these changes
+1

2021-06-25 17:24 UTC, merged