Send and receive kv_payload as message
Seagate/cortx-utils pull request #341
Opened 2021-06-22 15:45 UTC by selvakumaar5496

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-28 17:06 UTC, sachinpunadikar approved these changes
+1

2021-06-29 10:32 UTC, ujjwalpl requested changes

2021-06-29 10:32 UTC, ujjwalpl commented on py-utils/test/message_bus/test_kvpayload_message.py
> +        payload = TestKVPayloadMessage._kv_store.get_data()
payload need not come from the config file. Payload is any data in message. Example payload. 

```
payload = KvPayload{ 
    'attr1': 'val1',
    'attr2': 'val2', 
    ...
}
```

2021-06-29 10:32 UTC, ujjwalpl commented on py-utils/test/message_bus/test_kvpayload_message.py
> +    _kv_store = KvStoreFactory.get_instance('json:///etc/cortx/message_bus.conf')
There is no need to use kv_store for instantiating kv_payload. 
```
from kv_store.kv_payload import KvPayload
payload = KvPayload({....})
```

2021-06-29 10:32 UTC, ujjwalpl commented on py-utils/test/message_bus/test_kvpayload_message.py
> +        TestKVPayloadMessage._producer.send([json.dumps(payload)])
We need to send KvPayload as is without converting. 
```
producer.send(payload)
```

JSON could be a separate test and has nothing to do with KvPayload. Test name indicates that this is KvPayload test hence including JSON will be invalid or you can change the name of the test to say test_message_format.py

2021-06-29 10:48 UTC, selvakumaar5496 commented on py-utils/test/message_bus/test_kvpayload_message.py
> +    _kv_store = KvStoreFactory.get_instance('json:///etc/cortx/message_bus.conf')
done

2021-06-29 10:48 UTC, selvakumaar5496 commented on py-utils/test/message_bus/test_kvpayload_message.py
> +        payload = TestKVPayloadMessage._kv_store.get_data()
done

2021-06-29 10:55 UTC, selvakumaar5496 commented on py-utils/test/message_bus/test_kvpayload_message.py
> +        TestKVPayloadMessage._producer.send([json.dumps(payload)])
MessageBus takes list of strings as input. KvPayload.get_data returns a dict. Hence converting it to sting obj and sending

2021-06-29 10:57 UTC, selvakumaar5496 commented on py-utils/test/message_bus/test_kvpayload_message.py
> +        TestKVPayloadMessage._producer.send([json.dumps(payload)])
KvPayload.get_data(format_type='yaml') and KvPayload.get_data(format_type='toml') returns string hence no serialization required.

2021-06-29 11:08 UTC, ujjwalpl requested changes

2021-06-29 11:08 UTC, ujjwalpl commented on py-utils/test/message_bus/test_kvpayload_message.py
> +        message = TestKVPayloadMessage._payload.get_data()
We need to send payload itself. Not the data
message = Payload(....)
TestKVPayloadMessage._producer.send(message)

2021-07-01 04:30 UTC, selvakumaar5496 commented
Merged into single PR
https://github.com/Seagate/cortx-utils/pull/356

2021-07-01 04:30 UTC, closed without merging