Enhanced utils_setup to include test suite entrypoint from test_rpm
Seagate/cortx-utils pull request #346
Opened 2021-06-24 11:23 UTC by veerendra-simha-garikipati

Signed-off-by: Veerendra Garikipati <veerendra.garikipati@seagate.com>

# Problem Statement
- Enhanced utils_setup to include test suite entrypoint from test_rpm 

# Design
-  JIRA - https://jts.seagate.com/browse/EOS-17786
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-24 11:44 UTC, ujjwalpl requested changes

2021-06-24 11:44 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            raise SetupError(errno.EINVAL, "test_rpm is not installed - %s", e)
Need to be specific on the name of the test rpm. test_rpm does not represent actual name. There are several test rpms like S3, CSM, etc. 
Message: "Failed to import. Ensure that <rpm> is installed". No need to print include e.

2021-06-24 11:44 UTC, ujjwalpl commented on py-utils/test/entrypoint_test_suite.py
> +#!/usr/bin/env python3
Too big and strange name. Can we make it more intuitive and easy like
- run_test.py 
- main.py

2021-06-25 11:52 UTC, veerendra-simha-garikipati commented on py-utils/src/setup/utils.py
> +            raise SetupError(errno.EINVAL, "test_rpm is not installed - %s", e)
Done, updated message to "Failed to import, Ensure cortx-py-utils-test rpm is installed"

2021-06-25 11:52 UTC, veerendra-simha-garikipati commented on py-utils/test/entrypoint_test_suite.py
> +#!/usr/bin/env python3
Done, renamed file to "run_test.py"

2021-06-26 05:28 UTC, ujjwalpl requested changes

2021-06-26 05:28 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            from cortx.utils.test.run_test import TestSuite
We need to take input plan and create test suite as per the plan. 

utils_setup --plan regression

In this case only the regression test suite will run.

2021-06-30 13:19 UTC, sachinpunadikar commented on py-utils/test/cli_framework/__init__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
copyright year 2020 -> 2021 at all applicable places

2021-07-01 06:59 UTC, veerendra-simha-garikipati commented on py-utils/test/cli_framework/__init__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Done, changed copyright year to 2021 at all applicable places.

2021-07-01 07:13 UTC, veerendra-simha-garikipati commented on py-utils/src/setup/utils.py
> +            from cortx.utils.test.run_test import TestSuite
Done, utils_setup test phase will take the test_plan as input from conf_url and based on the test_plan, tests will be executed.
as of now we will be running all py-utils tests for sanity and regression test plans

test suite creation based on test plan functionality will be taken up in test framework development ticket.

2021-07-01 10:05 UTC, ujjwalpl requested changes

2021-07-01 10:05 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        Conf.load('plan_info', conf_url)
Plan is passed as the input and not through conf. Refer to my earlier example

utils_seutp --conf <conf> --plan <test plan name>

You need to take the plan name call "run_test --plan <plan>"

2021-07-01 10:05 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            from cortx.utils.test.run_test import TestSuite
As per the spec, plan name is passed as command line input and not as conf_url

2021-07-05 13:25 UTC, veerendra-simha-garikipati commented on py-utils/src/setup/utils.py
> +            from cortx.utils.test.run_test import TestSuite
Done, test plan is passed from command line using --plan argument in test phase.

2021-07-05 13:27 UTC, veerendra-simha-garikipati commented on py-utils/src/setup/utils.py
> +        Conf.load('plan_info', conf_url)
Done, --plan argument functionality is implemented, test plan can be passed in command line using --plan argument.

if test plan is not passed using --plan, then default test plan will be sanity.

2021-07-05 13:30 UTC, veerendra-simha-garikipati commented on py-utils/src/setup/utils.py
> +            from cortx.utils.test.run_test import TestSuite
The existing MessageBusTest code was removed from test phase

2021-07-05 13:51 UTC, ujjwalpl requested changes

2021-07-05 13:51 UTC, ujjwalpl commented on py-utils/src/setup/setup.yaml
> +        args: --config $URL --plan sanity
Please confirm this spec from Nitin. It should be... 

args: --config $URL --plan $PLAN

2021-07-05 13:51 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +            test_plan = plan
What is the use of creating new var test_plan here ? We can pass plan itself to run_test_suite directly. Will save this extra line.

2021-07-05 13:51 UTC, ujjwalpl commented on py-utils/test/run_test.py
> +    def run_test_suite(self, test_plan):
TestSuite is already a class name. No need to repeat the same. It should look like 

test_suite.run()

Rename the interface to say run() or run_test()

2021-07-05 13:51 UTC, ujjwalpl commented on py-utils/test/run_test.py
> +    def run_test_suite(self, test_plan):
Also, Test Plan should be passed in the constructor to represent 1:1 relation between TestSuite and TestPlan. They are the same thing. Something like...

test_suite = TestSuite(plan_name)
test_suite.run()

2021-07-05 13:51 UTC, ujjwalpl commented on py-utils/test/run_test.py
> +        if test_plan == 'sanity' or test_plan == 'regression':
There is no need for this check. Plan name can be anything. As long as the plan exists we will run it. 
For example there can be a plan named "xyz". If underlying dir path has "xyz" it would work. There is no need to prevent this.

2021-07-05 13:51 UTC, ujjwalpl commented on py-utils/test/run_test.py
> +            raise SetupError(errno.EINVAL, "Ensure correct test_plan is \
raise SetupError(errno.EINVAL, "Unable to run test plan %s. Possibly invalid name. Check and confirm the plan name is correct"...)

2021-07-05 13:51 UTC, ujjwalpl commented on py-utils/test/run_test.py
> +            test_suite = loader.discover(dir_path, pattern='test*.py', \
There should be a file called sanity.plan which contains list of test cases. Similarly I can create new plans e.g. xyz.plan to include same or lesser or more test cases into the plan.

2021-07-13 07:24 UTC, veerendra-simha-garikipati commented on py-utils/src/setup/setup.yaml
> +        args: --config $URL --plan sanity
Discussed this with Nitin, he said as string replacement logic is not implemented from provisioner end, we can go with 
'--plan sanity' for now.

2021-07-13 07:24 UTC, veerendra-simha-garikipati commented on py-utils/src/setup/utils.py
> +            test_plan = plan
Done, removed.

2021-07-13 07:26 UTC, veerendra-simha-garikipati commented on py-utils/test/run_test.py
> +    def run_test_suite(self, test_plan):
Removed class in run_test.py as run_test.py will be an executable file.

2021-07-13 07:26 UTC, veerendra-simha-garikipati commented on py-utils/test/run_test.py
> +        if test_plan == 'sanity' or test_plan == 'regression':
Done, implemented this logic in run_test.py

2021-07-13 07:27 UTC, veerendra-simha-garikipati commented on py-utils/test/run_test.py
> +            raise SetupError(errno.EINVAL, "Ensure correct test_plan is \
Done, updated the error message.

2021-07-13 07:29 UTC, veerendra-simha-garikipati commented on py-utils/test/run_test.py
> +            test_suite = loader.discover(dir_path, pattern='test*.py', \
Done, run_test.py will take the path of <plan>.pln file and execute the testsuite
created a directory 'plans' in test directory, we can create new plan files and can append test cases in plan files

2021-07-26 14:43 UTC, ujjwalpl approved these changes

2021-07-26 14:54 UTC, sachinpunadikar approved these changes
+1

2021-07-26 17:15 UTC, merged