Added README, SUPPORT, SECURITY, CODE_OF_CONDUCT, CONTRIBUTING
Seagate/cortx-utils pull request #35
Opened 2020-10-05 14:39 UTC by Saumya-Sunder

Added README, SUPPORT, SECURITY, CODE_OF_CONDUCT, CONTRIBUTING files.

Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

2020-10-06 04:43 UTC, sachinpunadikar commented on README.md
> +The cortx-utils repository contains utility tools and code for various CORTX submodules. For example, S3 and NFS submodules use code from the cortx-utils repos.
The cortx-utils repository contains utility tools and code for various components in CORTX stack. For example, S3 and NFS components use code from the cortx-utils repo.

2020-10-06 04:45 UTC, sachinpunadikar requested changes
Look at the codacy issues and other suggestions

2020-10-18 04:42 UTC, sachinpunadikar commented
@Saumya-Sunder Please work on the suggested change.

2020-10-19 05:27 UTC, s-arya approved these changes

2020-10-19 06:58 UTC, sachinpunadikar approved these changes
+1

2020-10-19 06:59 UTC, merged