Utils support bundle
Seagate/cortx-utils pull request #352
Opened 2021-06-29 04:02 UTC by suryakumar1024

# Problem Statement
- Write a support bundle script that should collect following log files and generate a py-utils.tar.gz as end-output:
- Kafka log files (server.logs, etc)
- Message bus log files.
- Utils_setup log files.
- Rest server log files 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-29 07:53 UTC, ujjwalpl requested changes

2021-06-29 07:53 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/support_bundle.py
> +    def generate_support_bundle(self):
Support Bundle is already the class name. Repeating the same in function seems inappropriate. 
Name should be such that someone can type "SupportBundle.generate()"

2021-06-29 07:53 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/support_bundle.py
> +        self.path = "/tmp/cortx/support_bundle/"
Avoid hard coding of parameters. It should be passed input or values from be taken from config.

2021-06-29 07:53 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/support_bundle.py
> +    def generate_tar(self):
Internal functions should start with _

2021-06-29 10:23 UTC, ujjwalpl requested changes

2021-06-29 10:23 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/support_bundle.py
> +        self.path = "/tmp/cortx/support_bundle/"
To be more specific, target path is specified by the caller and should be taken as input to generate() interface.

2021-06-30 20:24 UTC, suryakumar1024 commented on py-utils/src/utils/support_bundle/support_bundle.py
> +    def generate_tar(self):
Updated in recent patch.

2021-06-30 20:24 UTC, suryakumar1024 commented on py-utils/src/utils/support_bundle/support_bundle.py
> +        self.path = "/tmp/cortx/support_bundle/"
Updated in recent patch.

2021-06-30 20:24 UTC, suryakumar1024 commented on py-utils/src/utils/support_bundle/support_bundle.py
> +    def generate_support_bundle(self):
Updated in recent patch.

2021-07-01 03:09 UTC, ujjwalpl requested changes

2021-07-01 03:09 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/support_bundle.py
> +#!/bin/python3
Change the folder to "support", i.e. utils/support/support_bundle.py

2021-07-01 03:14 UTC, ujjwalpl requested changes

2021-07-01 03:14 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/support_bundle.py
> +    def __kafka_get_log_location_and_copy():
Avoid using long names. Use short and relevant names, like... _collect_kafka_logs()

2021-07-01 03:14 UTC, ujjwalpl commented on py-utils/src/utils/support_bundle/support_bundle.py
> +        "message_bus": "/var/log/cortx/utils/message_bus/MessageBus.log",
Why Message Bus Log is caps and other small letters ? it should be message_bus.log

2021-07-05 15:48 UTC, suryakumar1024 commented on py-utils/src/utils/support_bundle/support_bundle.py
> +        "message_bus": "/var/log/cortx/utils/message_bus/MessageBus.log",
### Updated in current patch

2021-07-05 16:12 UTC, suryakumar1024 commented on py-utils/src/utils/support_bundle/support_bundle.py
> +    def __kafka_get_log_location_and_copy():
Updated in current patch

2021-07-05 16:12 UTC, suryakumar1024 commented on py-utils/src/utils/support_bundle/support_bundle.py
> +#!/bin/python3
Updated in current patch

2021-07-09 04:51 UTC, selvakumaar5496 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +class SupportBundleError(Exception):
Please inherit UtilsError from py-utils/src/utils/errors.py

2021-07-13 05:54 UTC, selvakumaar5496 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +    """ Generate support bundle for py-utils"""
""" Generate support bundle for py-utils""" --> Provide space at the end of comment

2021-07-13 05:55 UTC, selvakumaar5496 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +    }
Change all the above to single quote. Everything is treated as a single word.

2021-07-13 06:04 UTC, selvakumaar5496 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +        """ Clean tmp files after support bundle generation completed """
""" Clean tmp files after support bundle generation is complete """

2021-07-13 06:07 UTC, selvakumaar5496 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +                    shutil.copytree(value, UtilsSupportBundle._tmp_src + key)
UtilsSupportBundle._tmp_src + key --> It is always good to use os.path.join if you are trying to concat a dir path.

2021-07-13 06:08 UTC, selvakumaar5496 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +                'kafka_zookeeper', "dataDir", "/var/zookeeper")
Inconsistent use of quotes

2021-07-13 06:15 UTC, selvakumaar5496 requested changes
Please work on the comments

2021-07-13 06:23 UTC, ujjwalpl commented on py-utils/src/setup/templates/utils_support_bundle.py
> +#!/usr/bin/env python3
Why is this part of templates folder ? 
It should be in src/support/utils_support_bundle.py

2021-07-13 09:50 UTC, suryakumar1024 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +#!/usr/bin/env python3
Hi Ujjwal, Scope of the script is to generate a tar file for py-utils. 
All this kind of script files for each component should be kept in the below path  /opt/seagate/cortx/<component>/conf/<script>.<py/sh>

So I kept this script file in the templates directory. since, as part of the installation step, I move this file to the respected path that is: 
/opt/seagate/cortx/utils/conf/utils_support_bundle.py

2021-07-13 10:11 UTC, suryakumar1024 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +import os.path
Since I need particularly os.path method I avoided importing the entire package.

2021-07-13 10:16 UTC, suryakumar1024 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +                'kafka_zookeeper', "dataDir", "/var/zookeeper")
Updated in current patch.

2021-07-13 10:17 UTC, suryakumar1024 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +                    shutil.copytree(value, UtilsSupportBundle._tmp_src + key)
Updated in current patch.

2021-07-13 10:17 UTC, suryakumar1024 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +        """ Clean tmp files after support bundle generation completed """
Updated in current patch.

2021-07-13 10:17 UTC, suryakumar1024 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +            raise SupportBundleError(errno.EINVAL, "File not found %s", fe)
Updated in current patch.

2021-07-13 10:17 UTC, suryakumar1024 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +    }
Updated in the current patch.

2021-07-13 10:17 UTC, suryakumar1024 commented on py-utils/src/setup/templates/utils_support_bundle.py
> +    """ Generate support bundle for py-utils"""
Updated in the current patch.

2021-07-13 11:36 UTC, ujjwalpl requested changes

2021-07-22 06:49 UTC, sachinpunadikar commented on py-utils/VERSION
> +2.0.0
This change is not required, remove this

2021-07-22 06:51 UTC, sachinpunadikar commented on py-utils/src/support/utils_support_bundle.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-07-22 06:52 UTC, sachinpunadikar commented on py-utils/src/support/utils_support_bundle.py
> +        'iem_and_rest':
iem_and_rest -> utils_server

2021-07-22 06:54 UTC, sachinpunadikar commented on py-utils/src/support/utils_support_bundle.py
> +        'kafka_zookeeper': '/opt/kafka/config/zookeeper.properties'
Add kafka logs
Add o/p of systemctl status kafka , systemctl status kafka-zookeeper

2021-07-22 06:59 UTC, sachinpunadikar commented on py-utils/utils-post-install
> +## Replace /opt/seagate with cortx installation path example: /opt/seagate
This change is not required, revert back

2021-07-22 06:59 UTC, sachinpunadikar commented on py-utils/utils-post-install
> +install_path=/opt/seagate
This change is not required, revert back

2021-07-22 07:00 UTC, sachinpunadikar commented on py-utils/utils-pre-install
> +#!/bin/bash
This file should not be checked-in

2021-07-22 07:01 UTC, sachinpunadikar commented on py-utils/setup.py
> +                'cortx.utils.support', 'cortx.utils.cli_framework',
Add 'cortx.support' to the list

2021-07-22 07:02 UTC, sachinpunadikar commented on py-utils/src/support/utils_support_bundle.py
> +    def __collect_kafka_logs():
Add o/p of systemctl status kafka , systemctl status kafka-zookeeper

2021-07-22 07:03 UTC, sachinpunadikar requested changes
Work on the comments

2021-07-22 13:37 UTC, suryakumar1024 commented on py-utils/setup.py
> +                'cortx.utils.support', 'cortx.utils.cli_framework',
Updated in recent patch

2021-07-22 13:50 UTC, suryakumar1024 commented on py-utils/src/support/utils_support_bundle.py
> +    def __collect_kafka_logs():
Updated in recent patch

2021-07-22 14:55 UTC, suryakumar1024 commented on py-utils/VERSION
> +2.0.0
Reverted version number

2021-07-22 14:55 UTC, suryakumar1024 commented on py-utils/src/support/utils_support_bundle.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Updated in recent patch

2021-07-22 14:56 UTC, suryakumar1024 commented on py-utils/src/support/utils_support_bundle.py
> +        'iem_and_rest':
Updated in recent patch

2021-07-22 14:56 UTC, suryakumar1024 commented on py-utils/utils-post-install
> +## Replace /opt/seagate with cortx installation path example: /opt/seagate
reverted and updated in recent patch.

2021-07-22 14:56 UTC, suryakumar1024 commented on py-utils/utils-post-install
> +install_path=/opt/seagate
reverted and updated in recent patch.

2021-07-22 14:57 UTC, suryakumar1024 commented on py-utils/utils-pre-install
> +#!/bin/bash
reverted.

2021-07-22 15:17 UTC, selvakumaar5496 approved these changes

2021-07-22 18:02 UTC, sachinpunadikar commented on py-utils/VERSION
> +1.0.0
As mentioned remove this file.

2021-07-22 18:11 UTC, sachinpunadikar commented
A minor comment, work on it

2021-07-23 04:18 UTC, sachinpunadikar commented on py-utils/utils-post-install
> +## Replace /opt/seagate with cortx installation path example: /opt/seagate
Again this change is coming in .. when you build py-utils, you will find this change. So if you are pushing changes after verifying build, then manually revert back this change & then push it

2021-07-23 04:22 UTC, suryakumar1024 commented on py-utils/VERSION
> +1.0.0
Updated in recent patch.

2021-07-23 04:43 UTC, sachinpunadikar approved these changes
+1

2021-07-26 04:25 UTC, ujjwalpl requested changes

2021-07-26 04:25 UTC, ujjwalpl commented on py-utils/setup.py
> +                                 'src/utils/support/command.yaml',
why name changed to command.yaml. It should be support.yaml only.

2021-07-26 04:25 UTC, ujjwalpl commented on py-utils/src/setup/setup.yaml
> +    - python3 /opt/seagate/cortx/utils/conf/support/utils_support_bundle.py
This should be a command and not the path to py file. py file should be copied to /opt/seagate/cortx/utils/bin during rpm installation.

2021-07-26 04:28 UTC, ujjwalpl requested changes

2021-07-26 04:28 UTC, ujjwalpl commented on py-utils/utils-post-install
> +sed -i -e "s|<CORTX_PATH>|${cortx_path}|g" $utils_path/conf/command.yaml
Name should be support.yaml only.

2021-07-26 04:28 UTC, ujjwalpl commented on py-utils/src/support/utils_support_bundle.py
> +#!/usr/bin/env python3
File name should be "support_bundle.py" to make it simple.

2021-07-26 05:25 UTC, sachinpunadikar commented on py-utils/utils-post-install
> +sed -i -e "s|<CORTX_PATH>|${cortx_path}|g" $utils_path/conf/command.yaml
@ujjwalpl , this is internal file, and this is temporary arrangement , so that it will not conflict with final support.yaml file.

2021-07-26 05:27 UTC, sachinpunadikar commented on py-utils/src/support/utils_support_bundle.py
> +#!/usr/bin/env python3
This is utils specific support bundle code. We have support bundle framework having name support_bundle.py, hence picking up different name.

2021-07-26 05:28 UTC, sachinpunadikar commented on py-utils/setup.py
> +                                 'src/utils/support/command.yaml',
@ujjwalpl , this is internal file, and this is temporary arrangement , so that it will not conflict with final support.yaml file.
In due course this command.yaml file will be removed.

2021-07-26 14:27 UTC, suryakumar1024 commented on py-utils/src/setup/setup.yaml
> +    - python3 /opt/seagate/cortx/utils/conf/support/utils_support_bundle.py
updated in recent patch.

2021-07-27 04:49 UTC, ujjwalpl approved these changes

2021-07-27 07:41 UTC, merged