WIP: EOS-17767 Add consul as a confstore backend
Seagate/cortx-utils pull request #353
Opened 2021-06-29 04:43 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

# Problem Statement
- Implement consul as a Confstore backend

# Design
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-07-28 04:10 UTC, selvakumaar5496 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        key_list =  self._consul.kv.get("", keys=True)[1]
single quote

2021-07-28 04:10 UTC, selvakumaar5496 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        """ Return a list of all the keys present"""
Inconsistent spacing

2021-07-28 04:14 UTC, selvakumaar5496 commented on py-utils/src/utils/kv_store/kv_payload.py
> +
we dont leave a blank line at the end of script right, As per our standard?
Please confirm

2021-07-28 11:05 UTC, suryakumar1024 approved these changes
Looks good

2021-07-28 11:08 UTC, ujjwalpl requested changes

2021-07-28 11:08 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def __init__(self, consul, delim):
Add description about the inputs.

2021-07-28 11:08 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def _set(self, key: str, val: str, *args, **kwargs):
Add return types to all the functions.

2021-07-28 11:16 UTC, ujjwalpl requested changes

2021-07-28 11:16 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +class ConsulStore(KvStore):
Name needs to be ConsulKvStore as per convention.

2021-07-28 11:16 UTC, ujjwalpl commented on py-utils/test/kv_store/test_kv_store.py
> +    #consul
Can we store Consul KV test in a separate file ?

2021-07-28 11:58 UTC, ujjwalpl requested changes

2021-07-28 11:58 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        self.c = Consul()
Lets check how we can make use of store_path, e.g. can it map to index ?

2021-07-28 12:00 UTC, ujjwalpl requested changes

2021-07-28 12:00 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def dump(self, *args, **kwargs):
dump signature must match to that of the base class.

2021-07-28 12:23 UTC, ujjwalpl requested changes

2021-07-28 12:23 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def _get(self, key: str, *args, **kwargs) -> str:
You will need to override get() instead of _get() because there is no concept of recurse in consul.

2021-07-28 13:00 UTC, ujjwalpl requested changes

2021-07-28 13:00 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        return ConsulKvPayload(self.c, self._delim)
Load can return the same payload i.e. 
```
ConsulKvStore: 
    __init__:
        self._payload = ConsulKvPayload(self.c, self._delim)
    load(...): 
        return self._payload
```

2021-07-28 17:14 UTC, ujjwalpl requested changes

2021-07-28 17:14 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def _get_keys(self, keys: list, *args, **kwargs) -> list:
You need to override get_keys() instead of _get_keys() to avoid recurse impact.

2021-08-03 03:15 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        key_list =  self._consul.kv.get("", keys=True)[1]
Done

2021-08-03 03:15 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        """ Return a list of all the keys present"""
Done.

2021-08-03 03:15 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_payload.py
> +
Done.

2021-08-03 04:10 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def __init__(self, consul, delim):
Done.

2021-08-03 04:10 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def _set(self, key: str, val: str, *args, **kwargs):
Done.

2021-08-03 04:10 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +class ConsulStore(KvStore):
Done.

2021-08-03 04:16 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        self.c = Consul()
store_path will be empty (/) in this case. storeurl will be consul:///.
I had to put because of the structure conf_store expects.

2021-08-03 04:18 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def _get(self, key: str, *args, **kwargs) -> str:
Handled it in init by passing the reference of _get to _shallow_get

2021-08-03 04:19 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def _get_keys(self, keys: list, *args, **kwargs) -> list:
Handled it in init by passing the reference of _get_keys to _shallow_get_keys

2021-08-10 07:06 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    def dump(self, *args, **kwargs):
Done

2021-08-10 07:07 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        return ConsulKvPayload(self.c, self._delim)
Done

2021-08-10 08:52 UTC, rahul-tripathi-git commented on py-utils/test/kv_store/test_kv_store.py
> +    #consul
Done

2021-08-10 16:50 UTC, vastradparayya commented on py-utils/test/conf_store/test_conf_store_conf.py
> +            val = Conf.get(index, "K1")
single quote for single word

2021-08-10 18:03 UTC, selvakumaar5496 commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +                          "Invalid response from consul: %d:%s", index, data)
Indent

2021-08-12 04:03 UTC, sachinpunadikar commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
This change is not required

2021-08-17 03:58 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
reversed

2021-08-17 03:58 UTC, rahul-tripathi-git commented on py-utils/test/conf_store/test_conf_store_conf.py
> +            val = Conf.get(index, "K1")
Done.

2021-08-18 03:02 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        self.c = Consul()
As discussed, store url will contain IP addresses for consul server (this will be taken in next PR)

2021-08-18 13:23 UTC, vastradparayya approved these changes
+1

2021-08-18 15:23 UTC, sachinpunadikar approved these changes
+1

2021-08-19 17:34 UTC, ujjwalpl approved these changes

2021-08-19 17:34 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        self, format_type: str = None, *args, **kwargs):
(style) Why wrap ? Lets follow the consistent convention if we need to wrap to next line

2021-08-19 17:39 UTC, selvakumaar5496 approved these changes

2021-08-19 17:51 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +        self, format_type: str = None, *args, **kwargs):
Done,

2021-08-19 18:25 UTC, sachinpunadikar commented
test this please

2021-08-20 04:37 UTC, merged