Convert the format of message to string
Seagate/cortx-utils pull request #356
Opened 2021-06-30 06:25 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-06-30 10:16 UTC, ujjwalpl requested changes

2021-06-30 10:16 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +                each_message = json.dumps(each_message.json)
Write simple logic
```
for message in messages:
    if isinstance(message, KvPayload):
        message = message.json()
    message_list.append(message)
```

2021-06-30 10:21 UTC, ujjwalpl requested changes

2021-06-30 10:21 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def _check_message_format(messages: list) -> list:
Name does match the function behaviour. Name be _get_str_message_list()

2021-06-30 10:34 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +                each_message = json.dumps(each_message.json)
done

2021-06-30 10:34 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def _check_message_format(messages: list) -> list:
done

2021-06-30 11:16 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def _get_str_message_list(messages: list) -> list:
suggestion 
_message_to_str(..)

2021-06-30 11:17 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            message_list.append(message)
I suppose we should check if the message is of not instance of str and throw an error

2021-06-30 11:18 UTC, sachinpunadikar requested changes
Please work on the comments

2021-06-30 11:57 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            message_list.append(message)
Done

2021-07-01 06:32 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus_client.py
> +                raise MessageBusError(errno.EINVAL, "Invalid message format. \
Invalid message format. -> Invalid message format, not of type kvpayload, str.

2021-07-01 07:05 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +                raise MessageBusError(errno.EINVAL, "Invalid message format. \
Done

2021-07-01 09:58 UTC, sachinpunadikar approved these changes
+1

2021-07-01 10:20 UTC, suryakumar1024 commented on py-utils/test/message_bus/test_kvpayload_message.py
> +    unittest.main()
Adding new line at end of each script is recommended. As per PEP it defies EOF. Correct me if you removed this line with any purpose

2021-07-01 10:59 UTC, selvakumaar5496 commented on py-utils/test/message_bus/test_kvpayload_message.py
> +    unittest.main()
As per our coding standard , we dont have any extra blank line after the last line. 
Also it will be reported in codacy issue

2021-07-02 10:37 UTC, ujjwalpl requested changes

2021-07-02 10:40 UTC, ujjwalpl approved these changes

2021-07-02 13:00 UTC, merged