WIP: Permission fix for message log file
Seagate/cortx-utils pull request #360
Opened 2021-07-02 09:15 UTC by suryakumar1024

Signei-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
- MessageBus Log file permission issue. Non admin user can't able to access or write message_log.py
- Fixed this issue by changing permissions for log directory and log file. 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-07-03 04:55 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus.py
> +        os.chmod("/var/log/cortx/utils/message_bus", stat.S_IWRITE)
Permissions on directory should be 775 -> (stat.S_IRWXU | stat.S_IRWXG | stat.S_IROTH | stat.S_IXOTH)

2021-07-03 04:57 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus.py
> +        os.chmod("/var/log/cortx/utils/message_bus/message_bus.log",
Permissions on file should be 664 -> (stat.S_IREAD | stat.S_IWRITE | stat.S_IRGRP | stat.S_IWGRP | stat.S_IROTH )

2021-07-03 04:58 UTC, sachinpunadikar requested changes
Please work on the comments. Expected permissions are 775 on directory & 664 on file

2021-07-03 04:59 UTC, sachinpunadikar commented
Add JIRA id to the title
Fill up the template

2021-07-04 10:26 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus.py
> +        os.chmod("/var/log/cortx/utils/message_bus", stat.S_IWRITE)
Updated in recent patch.

2021-07-04 10:26 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus.py
> +        os.chmod("/var/log/cortx/utils/message_bus/message_bus.log",
Updated in recent patch.

2021-07-05 04:30 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-07-05 04:31 UTC, sachinpunadikar approved these changes
+1

2021-07-05 05:09 UTC, merged