Add details about installing python deps
Seagate/cortx-utils pull request #371
Opened 2021-07-07 21:25 UTC by daniarherikurniawan

Initially, the Readme points to another Readme. However, it's a bit complicated from the reader's perspective since the other Readme contains many unrelated stuff. We only need 2 lines from that Readme, so it's better if we just write it down here. This PR will make this Readme to be complete and self-sufficient.

This PR will solve these issues : https://github.com/Seagate/cortx-utils/issues/370 and https://github.com/Seagate/cortx-utils/issues/362

I tested this on a baremetal server, and it works well. Let me know if you guys have another preferred update. Thanks. :)

2021-07-07 21:33 UTC, cortx-admin commented
Can one of the admins verify this patch?

2021-07-21 05:36 UTC, sachinpunadikar commented on py-utils/README.md
> +## Install python dependencies
This section is useful only when one is going build & install on the same system. If build system is different then these instructions are of no use.

2021-07-23 14:14 UTC, daniarherikurniawan commented on py-utils/README.md
> +## Install python dependencies
You right! But there is also a section about `Prerequisites for build`, isn't this `install python deps` part of the prerequisite? Thanks!
cc: @sachinpunadikar

2021-07-26 03:12 UTC, mengwanguc commented
Hello, I can confirm I was having the same problem as #370 , and this PR successfully resolved my problem. Thanks!

2021-08-02 18:30 UTC, johnbent commented on py-utils/README.md
> +## Install python dependencies
@sachinpunadikar , since Dan and Meng have both reported that the file is broken and that this PR fixes the problem, can we please merge it?  FYI @ujjwalpl

2021-08-03 05:11 UTC, sachinpunadikar commented on py-utils/README.md
> -Note : The rpm package installation will fail if any dependent python package is not installed.
Please restore this section. This will be needed for non dev kind of setup

2021-08-03 05:22 UTC, sachinpunadikar commented on py-utils/README.md
> +## Install python dependencies
## Install python dependencies -> ## Install python dependencies (dev setup)

2021-08-03 05:22 UTC, sachinpunadikar requested changes
work on the comments

2021-08-07 12:57 UTC, sachinpunadikar commented on py-utils/README.md
> -Please refer to WIKI (https://github.com/Seagate/cortx-utils/wiki/%22cortx-py-utils%22-single-node-manual-provisioning)
Please retain this sentence as well

2021-08-07 12:57 UTC, sachinpunadikar requested changes
Please retail the section as mentioned

2021-08-09 16:44 UTC, sachinpunadikar approved these changes
+1

2021-08-09 16:47 UTC, rohit-k-dwivedi approved these changes

2021-08-09 17:26 UTC, merged