EOS-21269: Discovery Lib API support for Manifest collection
Seagate/cortx-utils pull request #375
Opened 2021-07-12 03:57 UTC by mariyappanp

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-07-16 06:27 UTC, jjxsg commented on py-utils/src/utils/discovery/discovery.py
> +    def get_gen_manifest_status(request_id):
Both `get_gen_manifest_status` and `get_gen_node_health_status` solely depends on `request_id` so they can be merged to form a generalized method.

2021-07-21 12:23 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +    def get_gen_manifest_status(request_id):
agree. Since its exposed interface and we may want to take different routes for health/manifest in future, lets keep interfaces separate only.  However it can be a wrapper over that common function, which both function can depend upon. Here line 114 has this function reference from Node Health, which can also be made Discovery specific, and not in health or manifest
NodeHealth.get_processing_status()

2021-07-21 12:23 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.get_resource_map_location(request_id)
take out these functions out of NodeHealth and put it in under Discovery somewhere to be used
> NodeHealth.get_resource_map_location()

2021-07-21 12:23 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +    def update_resource_map(rpath, manifest):
all these functions, pull out from Node health, which ever are needed commonly both health, manifest

2021-07-21 12:23 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +                    if manifest:
Use function mapping approach here too, based on input

2021-07-21 12:23 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +        self.resource_provider_map = {
this is good

2021-07-22 07:08 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    def get_gen_manifest_status(request_id):
get_request_status(req_id) can be common and replace these two methods.
But need to intimate current users.

2021-07-22 09:02 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    def get_gen_manifest_status(request_id):
Please review, @cdeshmukh, @jjxsg

2021-07-22 09:04 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        return NodeHealth.get_resource_map_location(request_id)
NodeHealth is now renamed to RequestHanlder as per its functionality.
Now it could be relevant. Please review again.

2021-07-22 09:05 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +    def update_resource_map(rpath, manifest):
This file and its class is now renamed to request_handler.py and RequestHanlder.
Now, this is generic and both node health and manifest fits here.
Please review, @cdeshmukh

2021-07-22 09:05 UTC, mariyappanp commented on py-utils/src/utils/discovery/node_health.py
> +                    if manifest:
Done.

2021-07-22 10:04 UTC, satish-seagate commented on py-utils/src/utils/discovery/request_handler.py
>          req_register.set(["%s>time" % req_id], [int(time.time())])
Every time when we write a **set** it will open the file edit it and save it.
Try to save data in one go. it will reduce the time for execution.

request_dict = {
    '"%s>rpath" % req_id': rpath,
    '"%s>status" % req_id': RequestHandler.INPROGRESS,
    '"%s>url" % req_id': url,
    '"%s>time" % req_id': int(time.time())
}
req_register.set(request_dict.keys(), request_dict.values())

Only one time of **set** will reduce the time of execution.

2021-07-23 03:26 UTC, mariyappanp commented on py-utils/src/utils/discovery/request_handler.py
>          req_register.set(["%s>time" % req_id], [int(time.time())])
Done.

2021-07-23 06:37 UTC, satish-seagate commented on py-utils/src/utils/discovery/discovery.py
>      def get_gen_node_health_status(request_id):
Why this change is reverted?
I think we had changed it to "get_request_status" for both health and manifest.
https://github.com/Seagate/cortx-utils/pull/375#discussion_r673912042

2021-07-23 06:48 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
>      def get_gen_node_health_status(request_id):
Yes, get_request_status() is generic and can adapt any type of requests. 
But Chetan asked me to wrap this function and use for different APIs (health, manifest,..)

2021-07-23 07:13 UTC, cdeshmukh commented on py-utils/src/utils/discovery/resource.py
> +        """Look for solution specific __init__ module in given path"""
elaborate in the description, anyone looking at the code fresh may not be able to relate it

Also function name can be get_request_enabler() ? or something more intuitive

2021-07-23 07:13 UTC, cdeshmukh commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_health_gen.py
> +mock_manifest_data_url = "%s://%s" % (store_type, manifest_store_path)
again we are mixing health & manifest in tests too? separate it out in different files

2021-07-23 07:13 UTC, cdeshmukh commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_manifest.json
> +        "hw": {
hope this is inline with latest manifest data, shared by Satish

2021-07-23 07:29 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +        # decoding error due to key scanning happening at the same
Earlier request_handler.py updated request tracker file more frequently for,
```
    def add_discovery_request(rpath, req_id, url):
        """Updates new request information"""
        req_register.set(["%s>rpath" % req_id], [rpath])
        req_register.set(["%s>status" % req_id], [NodeHealth.INPROGRESS])
        req_register.set(["%s>status" % req_id], [RequestHandler.INPROGRESS])
        req_register.set(["%s>url" % req_id], [url])
        req_register.set(["%s>time" % req_id], [int(time.time())])
```
But now, above is simplified and one go we set these in backend as below.
```
    def add_discovery_request(rpath, req_id, url):
        """Updates new request information"""
        req_info = {
            "rpath": rpath,
            "status": RequestHandler.INPROGRESS,
            "url": url,
            "time": datetime.strftime(
                datetime.now(), '%Y-%m-%d %H:%M:%S')
        }
        req_register.set(["%s" % req_id], [req_info])
```

So we don't need this sleep time. By considering the worst case, I have it still. But the mentioned issue is not seen during unit testing.

2021-07-23 07:34 UTC, satish-seagate commented on py-utils/src/utils/discovery/discovery.py
>      def get_gen_node_health_status(request_id):
Okay

2021-07-23 07:40 UTC, satish-seagate commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_node_health.json
> +                  "fanmodule":[
It is "fan". please rename it.

2021-07-23 07:45 UTC, mariyappanp commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_health_gen.py
> +mock_manifest_data_url = "%s://%s" % (store_type, manifest_store_path)
Test perspective it is kept simple. 
Otherwise we need to keep same structure as SSPL solution path. 
```
lr2/server/mocked_manifest.py
lr2/server/mocked_health.py
lr2/server/server_resource_map.py

lr2/storage/mocked_manifest.py
lr2/storage/mocked_health.py
lr2/storage/storage_resource_map.py
```
This will take more time now and maintain later.

2021-07-23 07:46 UTC, satish-seagate requested changes
@cdeshmukh In the existing manifest, we have renamed the summary manifest file naming conversion as per the support IT team.
Do we need that same here for manifest generated file?
Please check this JIRA comment for more details. https://jts.seagate.com/browse/EOS-10616?focusedCommentId=1911187&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1911187 
FYI - @mariyappanp

2021-07-23 07:47 UTC, mariyappanp commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_manifest.json
> +        "hw": {
Yes, generated manifest using Satish's PR and added the required portion for manifest test.

2021-07-23 07:47 UTC, mariyappanp commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_node_health.json
> +                  "fanmodule":[
Okay

2021-07-23 07:53 UTC, mariyappanp commented
> @cdeshmukh In the existing manifest, we have renamed the summary manifest file naming conversion as per the support IT team.
> Do we need that same here for manifest generated file?
> Please check this JIRA comment for more details. https://jts.seagate.com/browse/EOS-10616?focusedCommentId=1911187&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1911187
> FYI - @mariyappanp

**Discovery returns store url only. Still that too can be customized with generate_manifest(store_url="").**

2021-07-23 08:47 UTC, cdeshmukh commented on py-utils/src/utils/discovery/discovery.py
> +    def get_gen_manifest_status(request_id):
am ok now

2021-07-23 08:50 UTC, cdeshmukh commented
> @cdeshmukh In the existing manifest, we have renamed the summary manifest file naming conversion as per the support IT team.
> Do we need that same here for manifest generated file?
> Please check this JIRA comment for more details. https://jts.seagate.com/browse/EOS-10616?focusedCommentId=1911187&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1911187
> FYI - @mariyappanp

That filename needs to be as part of support bundle i believe. But if Node manifest CLI expose download option, then we may need to align to that name too. So yes, lets do that @mariyappanp

2021-07-23 08:54 UTC, cdeshmukh commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_health_gen.py
> +mock_manifest_data_url = "%s://%s" % (store_type, manifest_store_path)
just copy paste the files, & maintain health & manifest feature tests in separate files, in same hierarchy

2021-07-23 10:14 UTC, satish-seagate approved these changes

2021-07-23 10:28 UTC, mariyappanp commented on py-utils/src/utils/discovery/resource.py
> +        """Look for solution specific __init__ module in given path"""
Done.

2021-07-23 10:28 UTC, mariyappanp commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_health_gen.py
> +mock_manifest_data_url = "%s://%s" % (store_type, manifest_store_path)
Okay

2021-07-23 10:29 UTC, mariyappanp commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_node_health.json
> +                  "fanmodule":[
Done.

2021-07-23 11:21 UTC, cdeshmukh commented on py-utils/src/utils/discovery/node_health.py
> +    def update_resource_map(rpath, manifest):
am good. I dont get option to resolve comments for cortx-utils, so feel free to do

2021-07-23 11:22 UTC, cdeshmukh approved these changes

2021-07-26 04:14 UTC, ujjwalpl requested changes

2021-07-26 04:14 UTC, ujjwalpl commented on py-utils/cortx.conf.sample
> +    "solution_platform_monitor": "/opt/seagate/cortx/sspl/bin/solution",
bin should only store binaries. Change the path to "/opt/seagate/cortx/sspl/extension/solution"

2021-07-26 04:22 UTC, ujjwalpl requested changes

2021-07-26 04:22 UTC, ujjwalpl commented on py-utils/src/utils/discovery/request_handler.py
> +    def update_resource_map(rpath, request_type):
Please rename all the internal class function to start with "_" so its easy to differentiate between interfaces and private functions

2021-07-26 09:12 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    def generate_manifest(rpath: str = None, store_url: str = None):
This function returns request_id.
In the background, it creates and updates manifest in below location.
json:///var/cortx/resources/node_manifest.json

2021-07-26 09:14 UTC, mariyappanp commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_health_gen.py
> +
Ok

2021-07-26 12:15 UTC, mariyappanp commented on py-utils/src/utils/discovery/discovery.py
> +    def generate_manifest(rpath: str = None, store_url: str = None):
Looking forward what is missing as part of this method. Please elaborate, @ujjwalpl

2021-07-26 12:19 UTC, mariyappanp commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_health_gen.py
> +    def get_manifest_info(self, rpath):
This test code will serve response during test.
Before SSPL post_install, discovery won't have backend to collect resource information. So for test and unittest purpose we have this. 

Still, this mock code should be removed? @ujjwalpl

2021-07-26 12:20 UTC, mariyappanp commented on py-utils/cortx.conf.sample
> +    "solution_platform_monitor": "/opt/seagate/cortx/sspl/bin/solution",
Okay

2021-07-26 12:31 UTC, mariyappanp commented on py-utils/src/utils/discovery/request_handler.py
> +    def update_resource_map(rpath, request_type):
Done.

2021-07-26 12:32 UTC, mariyappanp commented on py-utils/cortx.conf.sample
> +    "solution_platform_monitor": "/opt/seagate/cortx/sspl/bin/solution",
Done.

2021-07-26 12:32 UTC, mariyappanp commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_health_gen.py
> +
Done.

2021-07-26 12:35 UTC, mariyappanp commented on py-utils/test/discovery/mocked_health_gen/lr2/mocked_health_gen.py
> +mock_manifest_data_url = "%s://%s" % (store_type, manifest_store_path)
Done.

2021-07-26 12:49 UTC, ujjwalpl approved these changes

2021-07-26 13:06 UTC, jjxsg commented on py-utils/src/utils/discovery/discovery.py
> +    def get_gen_manifest_status(request_id):
Me too.

2021-07-26 13:19 UTC, jjxsg approved these changes

2021-07-26 13:21 UTC, cdeshmukh approved these changes

2021-07-26 13:22 UTC, cdeshmukh commented
@sachinpunadikar can you please review and approve if all seen good ?

2021-07-26 17:39 UTC, sachinpunadikar approved these changes
+1

2021-07-26 18:06 UTC, sachinpunadikar commented
@mariyappanp please work on the codacy issues. Rest all looks fine. Refer https://github.com/Seagate/cortx-utils/pull/375/checks?check_run_id=3164273464 for suggestions.

2021-07-27 06:58 UTC, merged