Feature audit logs
Seagate/cortx-utils pull request #376
Opened 2021-07-12 04:53 UTC by soniyamoholkar

# Problem Statement
- Problem statement 1. Sorting is not working with text fields in ES. 2. s3-rsys-index should not be generated through generic DB framework.

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/494600216/Rsyslog+and+Elasticsearch
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/486114207/Elasticsearch-+Sorting+on+text+fields

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-07-12 08:08 UTC, ujjwalpl requested changes

2021-07-12 08:08 UTC, ujjwalpl commented on py-utils/src/utils/data/db/consul_db/storage.py
> +    async def create_database(cls, config, model_settings,
- Why is there no type associated with model_settings. 
- Adding variable in the middle without default value will break the backward compatibility. Need to find all the uses and ensure call is changed to include new interface.

2021-07-12 08:08 UTC, ujjwalpl commented on py-utils/src/utils/data/db/elasticsearch_db/storage.py
> +        :param :param model_settings: Model settings
Description is not clear enough to know what is model settings.

2021-07-19 07:49 UTC, soniyamoholkar commented on py-utils/src/utils/data/db/consul_db/storage.py
> +    async def create_database(cls, config, model_settings,
Addressed the comments, added new optional parameter create_schema with default value as True. Please check

2021-07-19 07:49 UTC, soniyamoholkar commented on py-utils/src/utils/data/db/elasticsearch_db/storage.py
> +        :param :param model_settings: Model settings
Updated the comments. Please check

2021-07-20 04:26 UTC, ujjwalpl approved these changes

2021-07-20 05:28 UTC, sachinpunadikar commented on py-utils/src/utils/data/db/db_provider.py
> +                                                                         self._model,
indentation do not look good in browser, please cross check

2021-07-20 05:56 UTC, soniyamoholkar commented on py-utils/src/utils/data/db/db_provider.py
> +                                                                         self._model,
Addressed the review comment. Please check once.

2021-07-20 06:57 UTC, sachinpunadikar approved these changes
+1

2021-07-20 09:56 UTC, merged