EOS-22130: Make use of support bundle code from utils to create support bundle
Seagate/cortx-utils pull request #384
Opened 2021-07-19 11:50 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- Make use of support bundle code from utils to create support bundle 
- Should be able generate support bundle from utils repo

# Design
-  [EOS-22130](https://jts.seagate.com/browse/EOS-22130)
-  [Support Bundle Framework](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework)

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: NA
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: NA
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-07-19 12:32 UTC, ujjwalpl requested changes

2021-07-19 12:32 UTC, ujjwalpl commented on py-utils/src/utils/support/support_bundle_script.py
> +def generate_support_bundle():
Please follow OO

2021-07-19 12:32 UTC, ujjwalpl commented on py-utils/src/utils/support/support_bundle_script.py
> +    nodename = 'srvnode-1'
Hard coding.

2021-07-19 12:32 UTC, ujjwalpl commented on py-utils/src/utils/support/support_bundle_script.py
> +import asyncio
Location should be src/support.

2021-07-20 05:10 UTC, vastradparayya commented on py-utils/src/utils/support/bundle_generate.py
> +        print(msg+'\nGenerated tar file on path -> ', tar_file_name)
Added to check to location where SB generated

2021-07-20 05:14 UTC, vastradparayya commented on py-utils/src/utils/support/support_bundle.py
> +# from cortx.utils.support.services import ProvisionerServices
Commented provisioner code to check the SB generation when you install only  utils repo

2021-07-21 13:23 UTC, vastradparayya commented on py-utils/src/utils/support/support_bundle_script.py
> +def generate_support_bundle():
Added class

2021-07-21 13:24 UTC, vastradparayya commented on py-utils/src/utils/support/support_bundle_script.py
> +import asyncio
Moved file to src/support

2021-07-21 13:33 UTC, vastradparayya commented on py-utils/src/utils/support/support_bundle_script.py
> +    nodename = 'srvnode-1'
Fetching node_name from conf file

2021-07-21 14:32 UTC, sachinpunadikar commented on py-utils/src/support/support_bundle_script.py
> +        loop.run_until_complete(ComponentsBundle.init(cmd_obj))
What about node_name ? Are we not running this on all nodes ?

2021-07-22 12:58 UTC, vastradparayya commented on py-utils/src/support/support_bundle_script.py
> +        components=['utils'])
Done. 
Components is optional parameter if not specified support bundle will be created for all components, also you can specify components in list ['utils', 'csm']

2021-07-22 12:59 UTC, vastradparayya commented on py-utils/src/support/support_bundle_script.py
> +        loop.run_until_complete(ComponentsBundle.init(cmd_obj))
Done.
We are running on all nodes

2021-07-22 13:02 UTC, vastradparayya commented on py-utils/src/support/support_bundle_script.py
> +    print(bundle_obj)
Added print() to check the path where support bundle is generated. 
bundle_obj will be having bundle_id and bundle_path

2021-07-22 18:16 UTC, sachinpunadikar approved these changes
+1

2021-07-23 07:28 UTC, ujjwalpl requested changes

2021-07-23 07:28 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_script.py
> +class SupportBundleScript:
Please use a better name for the class like SupportBundle.

2021-07-23 07:28 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_script.py
> +    def get_bundle_status(bundle_id: str):
Rename to get_status (preferred and enough) or get_generation_status as Bundle is already qualified by class name

2021-07-23 09:21 UTC, ujjwalpl requested changes

2021-07-23 09:21 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_script.py
> +        Log.init('support_bundle', '/var/log/cortx/utils/support', level='INFO',
Why do we want to create yet another folder. 
Bundle logs can be in. /var/log/cortx/utils directory itself.

2021-07-23 09:21 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_script.py
> +            {'type': 'direct', 'target': 'csm.cli.support_bundle', 'method': \
Utils should be generic code and should not refer to csm.

2021-07-23 09:22 UTC, ujjwalpl requested changes

2021-07-23 09:22 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_script.py
> +        print('\n\nStatus - ', res, '\n')
Avoid printing status on the screen. This is class interface and should return status.

2021-07-26 04:45 UTC, vastradparayya commented on py-utils/src/support/support_bundle_script.py
> +    def get_bundle_status(bundle_id: str):
Done. 
changed name to get_status.

2021-07-26 05:13 UTC, sachinpunadikar commented on py-utils/src/support/support_bundle_script.py
> +        Log.init('support_bundle', '/var/log/cortx/utils/support', level='INFO',
We are following the convention of having directory for every subcomponent/framework. Like we have /varlog/cortx/utils/message_bus/message_bus.log.

2021-07-26 05:20 UTC, sachinpunadikar commented on py-utils/src/support/support_bundle_script.py
> +import asyncio
@ujjwalpl  This is a wrapper script, for us, to test the support bundle framework related code. This will not be used by other components, and towards the end of PI-3 or in PI-4, we will remove this script.
The script is for easy invocation of support bundle only.

2021-07-26 05:22 UTC, sachinpunadikar commented on py-utils/src/support/support_bundle_script.py
> +        print('\n\nStatus - ', res, '\n')
As mentioned this is only for dev purpose only, printing status is fine.
Eventually this script will be removed once all code for support bundle framework is ready

2021-07-26 05:35 UTC, vastradparayya commented on py-utils/src/support/support_bundle_script.py
> +class SupportBundleScript:
There will conflict with imported SupportBundle class name. And 
the SupportBundleScript is stand-alone way of invoking support bundle from utils code .. it is a temporary thing, and can be considered as test purpose code (or a cli kind script)

2021-07-26 05:36 UTC, vastradparayya commented on py-utils/src/support/support_bundle_script.py
> +            {'type': 'direct', 'target': 'csm.cli.support_bundle', 'method': \
Done. Removed csm target

2021-07-26 06:51 UTC, ujjwalpl requested changes

2021-07-26 06:51 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_script.py
> +class SupportBundleScript:
There are two classes
1. Bundle - This represents a file set containing debug logs. 
2. SupportBundle - This is the module who is responsible for generating bundle. 

Other Option is...
1. SupportBundle - This can represent a file set containing debug logs. 
2. SupportBundleHandler - This can be the module who is responsible for generating bundle. 

Any other class that has a conflict ?

2021-07-26 08:53 UTC, ujjwalpl requested changes

2021-07-26 10:37 UTC, vastradparayya commented on py-utils/src/support/support_bundle_script.py
> +        comment='Test support bundle generation', components=['provisioner'])
Done.

2021-07-26 10:52 UTC, sachinpunadikar commented on py-utils/src/support/support_bundle_cli.py
> +import asyncio
Add copyright

2021-07-26 12:52 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +import asyncio
Done

2021-07-26 14:54 UTC, ujjwalpl requested changes

2021-07-26 14:54 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_cli.py
> +    print(status)
status should not be printed instead you should exit with status i.e. `sys.exit(status)`

So that caller can check 

```
# supportbundle generate...
# echo $?
```

2021-07-26 14:54 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_cli.py
> +#!/bin/env python3
Add this command to 
/opt/seagate/cortx/utils/bin/supportbundle

2021-07-26 14:54 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_cli.py
> +    # componets parameter is optional, if not specified support bundle
Add comment with the usage of the Support Bundle CLI command.

2021-07-27 03:22 UTC, selvakumaar5496 commented on py-utils/src/support/support_bundle_cli.py
> +        # status
Please write something meaningful. 
For ex: # Get the status of bundle

2021-07-27 03:23 UTC, selvakumaar5496 approved these changes

2021-07-27 05:35 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +    print(status)
Added sys.exit(status)

2021-07-27 05:36 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +#!/bin/env python3
Added support_bundle_cli to /opt/seagate/cortx/utils/bin/supportbundle

2021-07-27 05:37 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +    # componets parameter is optional, if not specified support bundle
Added example usage of support bundle command

2021-07-27 05:38 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +        # status
Done

2021-07-27 06:37 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +    # support_bundle bin path is temporary and  will be replaced with support_bundle command
This is for utils internal use only. For support_bundle cli will be creating a separate ticket.

2021-07-30 11:55 UTC, ujjwalpl approved these changes

2021-07-30 14:21 UTC, ujjwalpl approved these changes

2021-07-30 15:22 UTC, merged