WIP - EOS-22314: SupportBundle - NorthBound interfaces
Seagate/cortx-utils pull request #400
Opened 2021-07-24 18:19 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- SupportBundle - NorthBound interfaces

# Design
-  JIRA - https://jts.seagate.com/browse/EOS-22314
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework#North-Bound-interface-(for-CLI%2FGUI)

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-07-26 12:28 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/bundle.py
> +class Bundle:
Add copyright text

2021-07-27 03:42 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/support_bundle.py
> +    async def get_active_nodes():
make it internal method _get_active_nodes()

2021-07-27 03:43 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/support_bundle.py
> +    async def get_bundle_status(command):
rename method to get_status

2021-07-27 03:52 UTC, sachinpunadikar requested changes
Work on the comments

2021-07-27 11:51 UTC, selvakumaar5496 commented on py-utils/src/utils/support_framework/bundle_generate.py
> +ERROR = "error"
single quote

2021-07-27 11:53 UTC, selvakumaar5496 commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        :return: None.
Should look like a table
For ex:
msg:            Message to Be added :type: str.
bundle_id:   Unique Bundle Id for the Bundle :type:str.
level:            Level for the Log. :type: Log.ERROR/LOG.INFO.

2021-07-27 11:55 UTC, selvakumaar5496 commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        result = "Success"
Single quote

2021-07-27 12:21 UTC, selvakumaar5496 commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        path = os.path.join(Conf.get("cortx_config","support>support_bundle_path"))
space after comma

2021-07-27 12:24 UTC, selvakumaar5496 requested changes
Change to single quote wherever applicable. I could see double quotes in many places for single word

2021-07-27 14:42 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/support_bundle.py
> +# CORTX-CSM: CORTX Management web and CLI interface.
Correct this line  .. should be cortx-py-utils

2021-07-27 15:02 UTC, vastradparayya commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        path = os.path.join(Conf.get("cortx_config","support>support_bundle_path"))
Done

2021-07-27 15:03 UTC, vastradparayya commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        result = "Success"
Done

2021-07-27 15:03 UTC, vastradparayya commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        :return: None.
Done

2021-07-27 15:03 UTC, vastradparayya commented on py-utils/src/utils/support_framework/support_bundle.py
> +    async def get_bundle_status(command):
Done

2021-07-28 04:01 UTC, vastradparayya commented on py-utils/src/utils/support_framework/support_bundle.py
> +# CORTX-CSM: CORTX Management web and CLI interface.
Done

2021-07-28 04:07 UTC, sachinpunadikar approved these changes
Looks good to me

2021-07-28 04:18 UTC, selvakumaar5496 commented on py-utils/src/utils/support_framework/const.py
> +SB_COMMENT = "comment"
please take care of this double quote

2021-07-29 02:32 UTC, selvakumaar5496 commented on py-utils/src/utils/support_framework/bundle_generate.py
> +from datetime import datetime
As per the guideline, this should be imported before local packages right?

2021-07-29 02:34 UTC, selvakumaar5496 reviewed
Docstrings are inconsistent. Added spaces in some places. And no spaces in some places

2021-07-29 05:50 UTC, selvakumaar5496 approved these changes

2021-07-29 11:08 UTC, sachinpunadikar commented
test this please

2021-07-29 11:43 UTC, merged