Check message delivery status
Seagate/cortx-utils pull request #403
Opened 2021-07-27 06:57 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-07-27 08:57 UTC, ujjwalpl requested changes

2021-07-27 08:57 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    _message_timeout = 5000
Why is it hard coded ?

2021-07-27 08:57 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                callback=self.delivery_callback)
delivery_callback is static method but the call is with self. May have issues. 

Also, I dont see any test code.

2021-07-28 17:23 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
>      _kafka_socket_timeout = 15000
rename this to generic name like socket_timeout

2021-07-29 02:19 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
>      _kafka_socket_timeout = 15000
Done

2021-07-29 08:15 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                callback=self.delivery_callback)
![image](https://user-images.githubusercontent.com/66383213/127456537-c505b8f0-12e4-4616-abbb-473cad8ea069.png)

Should be called with self. But delivery_callback method doesnt take self as argument.

2021-07-29 09:22 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    _message_timeout = 5000
Reading it from config file.

2021-07-29 09:22 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                callback=self.delivery_callback)
Test code is included in #410

2021-07-29 11:25 UTC, sachinpunadikar approved these changes
+1

2021-07-30 11:30 UTC, ujjwalpl requested changes

2021-07-30 11:30 UTC, ujjwalpl commented on py-utils/src/setup/templates/utils.config.tmpl.1-node
> +      config:
Timeouts can be generic timeouts and not specific to kafka and can be used and mapped to kafka. 
```
kafka:
    servers:
message_bus: 
    default_timeout: 2
    socket_timeout: 15000
    message_timeout: 5000
```
Also need to expand timeout properly like it is not clear what is default_timeout or message_timeout.

2021-07-30 11:33 UTC, ujjwalpl requested changes

2021-07-30 11:33 UTC, ujjwalpl commented on py-utils/src/setup/templates/utils.config.tmpl.1-node
> +        default_timeout: 2
Where is default_timeout used in the code ?

2021-07-30 12:08 UTC, selvakumaar5496 commented on py-utils/src/setup/templates/utils.config.tmpl.1-node
> +        default_timeout: 2
used in consumer.poll()

2021-07-30 12:09 UTC, selvakumaar5496 commented on py-utils/src/setup/templates/utils.config.tmpl.1-node
> +      config:
Added with comments

2021-08-03 12:29 UTC, ujjwalpl requested changes

2021-08-03 12:29 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +                {'server': message_server_list[i], 'port': port_list[i]})
We can not / should not set value as dict. It should be key (string) and value (string)

Conf.set('index', f'message_broker>cluster[{i}]>server', message_server_list[i])
Conf.set('index', f'message_broker>cluster[{i}]>post', port_list[i])

2021-08-03 12:59 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +                {'server': message_server_list[i], 'port': port_list[i]})
Done with above suggested way

2021-08-09 04:55 UTC, ujjwalpl approved these changes

2021-08-09 05:45 UTC, merged