Improved test cases
Seagate/cortx-utils pull request #410
Opened 2021-07-28 11:21 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-07-28 17:08 UTC, sachinpunadikar commented on py-utils/test/message_bus/test_message_bus.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
revert this change or make copyright year as 2020, 2021. I would prefer not to change the year. For new addition, the year will be current year. For changes in a file, no need to update the year

2021-07-28 17:10 UTC, sachinpunadikar commented on py-utils/test/message_bus/test_message_bus.py
> +# Declared global to track threaded consumers
Number of Consumer Threads

2021-07-28 17:21 UTC, sachinpunadikar commented
Fill up the PR template. I added few comments, work on that

2021-07-29 05:19 UTC, selvakumaar5496 commented on py-utils/test/message_bus/test_message_bus.py
> +# Declared global to track threaded consumers
done

2021-07-29 05:19 UTC, selvakumaar5496 commented on py-utils/test/message_bus/test_message_bus.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
Done

2021-07-29 07:16 UTC, sachinpunadikar approved these changes
+1

2021-07-29 10:02 UTC, ujjwalpl requested changes

2021-07-29 10:02 UTC, ujjwalpl commented on py-utils/src/utils/errors.py
> +ERR_INVALID_MESSAGE_TYPE = 0x1506
Why dont you use EINVAL ?

2021-07-29 17:43 UTC, selvakumaar5496 commented on py-utils/src/utils/errors.py
> +ERR_INVALID_MESSAGE_TYPE = 0x1506
Done. Reverted back to EINVAL

2021-07-30 11:56 UTC, ujjwalpl approved these changes

2021-07-30 14:23 UTC, ujjwalpl approved these changes

2021-07-30 15:23 UTC, merged