Enhanced reset and cleanup
Seagate/cortx-utils pull request #414
Opened 2021-07-30 12:25 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- Enhance Cleanup n Reset phases for utils_setup.

# Design
-  [https://jts.seagate.com/browse/EOS-22981](https://jts.seagate.com/browse/EOS-22981)

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: Y
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: N
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-05 17:49 UTC, ujjwalpl requested changes

2021-08-05 17:49 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +        cmd = "find /var/log/cortx/utils/ -type f -name '*.log' -exec truncate -s 0 {} +"
```
ujjwal@dev1:~>find /var/log/cortx/utils/ -type f -name '*.log' -exec truncate -s 0 {} +
find: ‘/var/log/cortx/utils/’: No such file or directory
ujjwal@dev1:~>
```

Reset should not fail if /var/log/cortx/utils/  does not exist. Please try some negative tests. 

Can do this 
```
if os.path.exists('/var/log/cortx/utils/'): 
    cmd = ....
```

2021-08-06 03:43 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        cmd = "find /var/log/cortx/utils/ -type f -name '*.log' -exec truncate -s 0 {} +"
Done. Added path check.
In utils_setup we initializing log at location '/var/log/cortx/utils/', if we are calling any phase of mini-provisioning this path would be exist.

2021-08-09 12:30 UTC, ujjwalpl approved these changes

2021-08-09 13:37 UTC, sachinpunadikar approved these changes
+1

2021-08-09 14:14 UTC, merged