EOS-22367:Bundle R2 Manifest in Support Bundle (generate, get_status)
Seagate/cortx-utils pull request #419
Opened 2021-08-03 09:36 UTC by satish-seagate

Signed-off-by: Satish Darade <satish.darade@seagate.com>

# Problem Statement
Improvement task.

# Design
--> Added manifest generate interface
--> Added manifest get_status interface

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-04 11:43 UTC, cdeshmukh commented on py-utils/src/support/manifest_support_bundle.py
> +        "In-progress": None,
Wherever mapping is different, can maintain that alone, otherwise same status can be used. so maintain only 'In-progress' here

2021-08-04 11:43 UTC, cdeshmukh commented on py-utils/src/support/manifest_support_bundle.py
> +            .startswith(("Success", "Failed")): time.sleep(0.5)
there should be a timeout here, worst of lets say 5 mins? whats the highest time seen till now? after which we can callout request as failed & cleanup tmp files ?

2021-08-06 13:59 UTC, satish-seagate commented on py-utils/src/support/manifest_support_bundle.py
> +import errno
Done

2021-08-06 13:59 UTC, satish-seagate commented on py-utils/src/setup/manifest.yaml
> +# CORTX-PY-UTILS: CORTX common utility code
Done

2021-08-06 14:01 UTC, satish-seagate commented on py-utils/src/support/manifest_support_bundle.py
> +    _tmp_src = '/tmp/cortx/manifest/'
Done. I have followed the same way what the existing "utils" support bundle is doing.
https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/support/utils_support_bundle.py

2021-08-06 14:01 UTC, satish-seagate commented on py-utils/src/support/manifest_support_bundle.py
> +        "In-progress": None,
Done

2021-08-06 14:18 UTC, satish-seagate commented on py-utils/src/support/manifest_support_bundle.py
> +            .startswith(("Success", "Failed")): time.sleep(0.5)
The request is already sent to the discovery library to generate manifest data at "line no. 84"
Anyway, here we are checking just the status of the ongoing discovery manifest data request.
Support bundle code will not be stuck here because it is an async call from the support bundle framework. after generating a request from the sb framework it will call only the get_status method every time to see the status.

If we set timeout here and exit the code here then how we can stop ongoing requests which are with discovery?
Anyway, I will ask provision that how much time they will wait for sb generation and is any timeout set by them.
If it is set in the sb framework then no need to take care of anything here.

2021-08-09 06:28 UTC, cdeshmukh commented on py-utils/src/support/manifest_support_bundle.py
> +    _tmp_dir = '/tmp/cortx'
@sachinpunadikar is there any support bundle specific dat dir which we can use for these temp files also? Usually we have been trying to avoid /tmp usage in sspl, because of sometimes /tmp cleanup by cron. 

Also codacy highlighting here
>Codacy Production
/ Codacy Static Code Analysis
py-utils/src/support/manifest_support_bundle.py#L43
Probable insecure usage of temp file/directory.

2021-08-09 06:28 UTC, cdeshmukh commented on py-utils/src/support/manifest_support_bundle.py
> +        if status != "In-progress":
So what are the possible values in support bundle ? Whats given support bundle generation in progress ?

2021-08-09 06:28 UTC, cdeshmukh commented on py-utils/src/support/manifest_support_bundle.py
> +            .startswith(("Success", "Failed")): time.sleep(0.5)
Am talking about ongoing request status collection only here. in feature description of 4-E we have called out timeout, which applies here too. We dont have a way to discard any ongoing collection through a separate request, but again to avoid falling into trap of a failed request but its status never got updated, i tought there was a timeout with discovery lib api too, @mariyappanp can confirm.

But yes support bundle framework / feature can confirm if they seek timeout and if not, we will avoid here then

2021-08-09 13:30 UTC, mariyappanp commented on py-utils/src/support/manifest_support_bundle.py
> +            .startswith(("Success", "Failed")): time.sleep(0.5)
`whats the highest time seen till now?` ~ 4 minutes.
Discovery Library: Any ongoing request will be marked as failed after 1800 seconds(30 minutes). Same for any discorded or lost request. Then corresponding request status will be marked as failed.

2021-08-09 18:21 UTC, cdeshmukh commented on py-utils/src/support/manifest_support_bundle.py
> +        if status != "In-progress":
As discussed, i understand, no in-progress status needed by CLI as of now

2021-08-09 18:22 UTC, cdeshmukh commented on py-utils/src/support/manifest_support_bundle.py
> +            .startswith(("Success", "Failed")): time.sleep(0.5)
>Any ongoing request will be marked as failed after 1800 seconds(30 minutes)

Hope this is configurable, if not we should do it.

So we are covered with Discovery lib apis already, we dont need to add it again here then.

2021-08-09 18:23 UTC, cdeshmukh commented on py-utils/src/support/manifest_support_bundle.py
> +    _tmp_dir = '/tmp/cortx'
Given cron job will cleanup any stale old files only from /tmp, it doesnt seem to be any major concern. So am fine here

2021-08-09 18:23 UTC, cdeshmukh approved these changes

2021-08-10 09:31 UTC, sachinpunadikar commented on py-utils/src/support/manifest_support_bundle.py
> +    def __update_bundle_id(bundle_id: str, manifest_id: str, tar_file: str):
Provide more generic name

2021-08-10 10:26 UTC, vastradparayya commented on py-utils/src/support/manifest_support_bundle.py
> +        Conf.load("cluster", ManifestSupportBundle._conf_file, skip_reload=True)
Utils is following coding standards to look code consistent
- single quotes for character, single_word and path 
- double quotes for sentences. Can you check wherever applicable?
Eg: "cluster" -> 'cluster'

2021-08-10 16:52 UTC, sachinpunadikar commented on py-utils/src/support/manifest_support_bundle.py
> +#!/usr/bin/env python3
path should be py-utils/src/utils/manifest/manifest_support_bundle.py
Accordingly change path at other places

2021-08-10 16:53 UTC, sachinpunadikar requested changes
work on the comments

2021-08-11 06:16 UTC, satish-seagate commented on py-utils/src/setup/manifest_setup.yaml
> +# CORTX-PY-UTILS: CORTX common utility code
@sachinpunadikar As I am seeing after deployment we need this file in **/opt/seagate/cortx/<component>/conf/support.yaml** location (https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework#Node-centric-support-bundle). And I am seeing that with parallel PR for utils support bundle we are creating the same file (https://github.com/Seagate/cortx-utils/pull/404) please check support.yaml file inside this PR.
So after deployment of this two support.yaml file will present inside the conf directory (utils and manifest), there will be conflict. how we can make those two files separate in the conf directory?
@rahul-tripathi-git @suryakumar1024 @vastradparayya 
Please suggest how we can make it correct.

2021-08-11 07:00 UTC, sachinpunadikar commented on py-utils/src/setup/manifest_setup.yaml
> +# CORTX-PY-UTILS: CORTX common utility code
Good point @satish-seagate  we have 2 choices - 
1. /opt/seagate/cortx/manifest/conf/support.yaml
2. /opt/seagate/cortx/utils/conf/manifest_support.yaml
@ujjwalpl your view on this

2021-08-13 09:42 UTC, satish-seagate commented on py-utils/src/support/manifest_support_bundle.py
> +    _tmp_src = '/tmp/cortx/manifest/'
Done

2021-08-13 09:42 UTC, satish-seagate commented on py-utils/src/support/manifest_support_bundle.py
> +    def __update_bundle_id(bundle_id: str, manifest_id: str, tar_file: str):
Done

2021-08-13 09:42 UTC, satish-seagate commented on py-utils/src/support/manifest_support_bundle.py
> +        Conf.load("cluster", ManifestSupportBundle._conf_file, skip_reload=True)
Done

2021-08-13 09:45 UTC, satish-seagate commented on py-utils/src/setup/manifest_setup.yaml
> +# CORTX-PY-UTILS: CORTX common utility code
> [Yesterday 5:29 PM] Ujjwal Lanjewar
    Sachin Punadikar Satish Darade Manifest are integral attributes of SupportBundle Framework. So it should be part of the framework itself. 
​[Yesterday 7:36 PM] Sachin Punadikar
    Thanks Ujjwal Lanjewar, as I understand, we should not treat this as separate component , and by default should be collected 
​[Yesterday 8:50 PM] Ujjwal Lanjewar
    Yes
(1 liked)

So, no requirement of support.yaml for manifest support bundle.

2021-08-13 09:45 UTC, satish-seagate commented on py-utils/src/support/manifest_support_bundle.py
> +#!/usr/bin/env python3
Done

2021-08-16 06:08 UTC, suryakumar1024 commented on py-utils/src/utils/manifest/__init__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Need to update this to 2021

2021-08-16 06:11 UTC, suryakumar1024 commented on py-utils/src/utils/manifest/__init__.py
> +from cortx.utils.manifest.manifest_support_bundle import ManifestSupportBundle
Can use the below statement to address this codacy warning. Also, it helps us in wildcard import. 
__all__ = ['ManifestSupportBundle']

2021-08-16 06:47 UTC, sachinpunadikar reviewed
Looks good.
Need to call this for every node. 
@suryakumar1024 please help @satish-seagate to have that additional code. That can be a separate PR

2021-08-16 07:35 UTC, cdeshmukh commented on py-utils/src/utils/manifest/manifest_support_bundle.py
> +        main()
To be part of cortx support bundle itself, manifest generation needs to be independent script now and not accessed through python interfaces ?

2021-08-16 07:36 UTC, cdeshmukh reviewed
> Where its getting integrated in CORTC support bundle itself, i dont see any related code ?

@cdeshmukh, This will be taken care of by the foundation team as a part of the common support bundle framework.
@sachinpunadikar Please confirm.

2021-08-16 07:39 UTC, satish-seagate commented on py-utils/src/utils/manifest/manifest_support_bundle.py
> +        main()
Yes @cdeshmukh , I am okay with removing it.
@sachinpunadikar Please confirm that we are accessing this file method inside the support bundle framework only and we are not calling this file directly through command arguments?
cc. @suryakumar1024

2021-08-16 07:45 UTC, satish-seagate commented on py-utils/src/utils/manifest/__init__.py
> +from cortx.utils.manifest.manifest_support_bundle import ManifestSupportBundle
Done

2021-08-16 07:45 UTC, satish-seagate commented on py-utils/src/utils/manifest/__init__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Done

2021-08-16 07:46 UTC, sachinpunadikar commented on py-utils/src/utils/manifest/manifest_support_bundle.py
> +        main()
Yup @satish-seagate , hence asked @suryakumar1024  to help in having that internal call from SB framework

2021-08-16 07:48 UTC, cdeshmukh commented on py-utils/src/utils/manifest/manifest_support_bundle.py
> +        main()
@sachinpunadikar tomorrow if we want to add filters, just to get manifest in cortx support bundle, python interfaces won be useful ? Am just thinking, no concrete opinion on this

2021-08-16 07:50 UTC, cdeshmukh commented
> @cdeshmukh, This will be taken care of by the foundation team as a part of the common support bundle framework.

I believe integration for single node should happen here otherwise PR wont satisfy the purpose. Cluster manifest collection, SB framework may take care

2021-08-17 05:28 UTC, sachinpunadikar commented on py-utils/src/utils/manifest/manifest_support_bundle.py
> +#!/usr/bin/env python3
This package & executable needs to installed. Make required changes in setup.py to achieve the same

2021-08-17 05:28 UTC, sachinpunadikar requested changes
Installation related changes are missing

2021-08-17 06:08 UTC, satish-seagate commented on py-utils/src/utils/manifest/manifest_support_bundle.py
> +#!/usr/bin/env python3
Done

2021-08-17 06:09 UTC, satish-seagate commented on py-utils/src/utils/manifest/manifest_support_bundle.py
> +        main()
@sachinpunadikar, Can I remove these options from here? or keep at is.

2021-08-17 06:42 UTC, sachinpunadikar commented on py-utils/src/utils/manifest/manifest_support_bundle.py
> +        main()
Let these options be there

2021-08-17 06:44 UTC, sachinpunadikar approved these changes
+1

2021-08-17 07:02 UTC, suryakumar1024 approved these changes
Good to merge

2021-08-17 07:36 UTC, rahul-tripathi-git approved these changes
+1

2021-08-17 08:18 UTC, cdeshmukh approved these changes

2021-08-17 08:18 UTC, cdeshmukh commented on py-utils/src/utils/manifest/manifest_support_bundle.py
> +        main()
alright

2021-08-17 17:12 UTC, merged