Utils-specific-supportbundle: Added kafka log files into support bundle tar
Seagate/cortx-utils pull request #421
Opened 2021-08-03 18:15 UTC by suryakumar1024

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
- Added log files from /opt/kafka/logs dir

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-06 07:38 UTC, ujjwalpl requested changes

2021-08-06 07:38 UTC, ujjwalpl commented on py-utils/src/support/utils_support_bundle.py
> +        if os.path.exists('/opt/kafka/logs/'):
Why is Kafka logs going to /opt/ It should go to /var/log only. Can we fix that ?

2021-09-06 14:18 UTC, ujjwalpl requested changes

2021-09-06 14:18 UTC, ujjwalpl commented on py-utils/src/support/utils_support_bundle.py
> +        if os.path.exists('/var/log/kafka/'):
Please do not hard code. Log path may change to /share/var/log. So we should be prepared to get this as config input.

2021-09-06 14:19 UTC, ujjwalpl approved these changes

2021-09-07 04:35 UTC, selvakumaar5496 commented on py-utils/src/support/utils_support_bundle.py
> +            ignore =shutil.ignore_patterns('*.log.*-*-*-*')
provide a space after =

2021-09-07 04:35 UTC, selvakumaar5496 commented on py-utils/src/support/utils_support_bundle.py
> +                UtilsSupportBundle._tmp_src, 'kafka_log') , ignore=ignore)
remove space before comma

2021-09-07 05:36 UTC, suryakumar1024 commented on py-utils/src/support/utils_support_bundle.py
> +            ignore =shutil.ignore_patterns('*.log.*-*-*-*')
updated in recent patch

2021-09-07 05:37 UTC, suryakumar1024 commented on py-utils/src/support/utils_support_bundle.py
> +                UtilsSupportBundle._tmp_src, 'kafka_log') , ignore=ignore)
updated in recent patch

2021-09-07 05:43 UTC, selvakumaar5496 approved these changes

2021-09-07 05:44 UTC, rohit-k-dwivedi approved these changes

2021-09-07 08:02 UTC, sachinpunadikar approved these changes
+1

2021-09-07 14:41 UTC, merged