EOS-23314: Support of suuport_bundle_cli for support_framework
Seagate/cortx-utils pull request #423
Opened 2021-08-04 10:32 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- Support of suuport_bundle_cli for support_framework

# Design
https://jts.seagate.com/browse/EOS-23314

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [x] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: Y
- [x] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [x] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-04 12:21 UTC, ujjwalpl requested changes

2021-08-04 12:21 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_cli.py
> +    Conf.load('config_file', 'json:///etc/cortx/cortx.conf')
"config_file" seems too generic.  Config names need to be more meaningful like "cortx_conf". any reason for the change ?

2021-08-04 12:21 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_cli.py
> +    Log.init('support_bundle', '/var/log/cortx/utils/support_framework/', \
Why support_framework ? 
Just this is sufficient ... /var/log/cortx/utils/support/

2021-08-04 12:21 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_cli.py
> +    def generate(args):
Do we support running multiple support bundle command at the same time ? If not, then we may need to add a check.

2021-08-04 14:21 UTC, sachinpunadikar commented on py-utils/src/support/support_bundle_cli.py
> +    def generate(args):
@ujjwalpl , this will be detected by underneath support bundle framework and likewise error / message will be provided. So this check is not required here.

2021-08-04 17:39 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +    Log.init('support_bundle', '/var/log/cortx/utils/support_framework/', \
Done

2021-08-04 17:45 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +    Conf.load('config_file', 'json:///etc/cortx/cortx.conf')
Previously kept as temporary name.
changed from  'config_file' to 'cortx_conf'

2021-08-05 08:06 UTC, ujjwalpl requested changes

2021-08-05 08:06 UTC, ujjwalpl commented on py-utils/src/support/support_bundle_cli.py
> +    def generate(args):
Please provide pointer to the code, where this condition is handled.

2021-08-05 17:44 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +    def generate(args):
Created separate ticket for multiple support bundle command at the same time.

2021-08-05 17:45 UTC, vastradparayya commented on py-utils/src/support/support_bundle_cli.py
> +
Done

2021-08-09 12:33 UTC, ujjwalpl approved these changes

2021-08-09 14:21 UTC, sachinpunadikar approved these changes
+1

2021-08-09 14:49 UTC, merged