EOS-23391: Code changes to trigger to utils bundle_generate
Seagate/cortx-utils pull request #427
Opened 2021-08-09 04:51 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- Code changes to trigger to utils bundle_generate

# Design
-  https://jts.seagate.com/browse/EOS-23391

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [x] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: Y
- [x] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [x] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: N
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-09 06:38 UTC, suryakumar1024 approved these changes
Good to merge.

2021-08-09 06:50 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/bundle_generate.py
>          if os.path.isdir(path):
This part of the code should be under "delete"

2021-08-09 06:58 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/services.py
> +            Conf.load('index', 'json:///opt/seagate/cortx_configs/provisioner_cluster.json', \
index -> basic_cluster_info

2021-08-09 07:00 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/__init__.py
> +Conf.load('cortx_cluster', 'json:///etc/cortx/cluster.conf', skip_reload=True)
Please remove this load statements

2021-08-09 09:32 UTC, vastradparayya commented on py-utils/src/utils/support_framework/__init__.py
> +Conf.load('cortx_cluster', 'json:///etc/cortx/cluster.conf', skip_reload=True)
Removed load from init

2021-08-09 09:32 UTC, vastradparayya commented on py-utils/src/utils/support_framework/services.py
> +            Conf.load('index', 'json:///opt/seagate/cortx_configs/provisioner_cluster.json', \
Done

2021-08-09 09:33 UTC, vastradparayya commented on py-utils/src/utils/support_framework/bundle_generate.py
>          if os.path.isdir(path):
Commented as of now

2021-08-09 10:15 UTC, selvakumaar5496 commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        path = os.path.join(Conf.get('cortx_conf', \
why os.path.join when you have only 1 parameter

2021-08-09 13:23 UTC, vastradparayya commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        path = os.path.join(Conf.get('cortx_conf', \
Done

2021-08-10 12:48 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/bundle_generate.py
>          symlink_path = const.SYMLINK_PATH
Remove code lines 202 -> 216

2021-08-10 12:50 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        Conf.load('cortx_conf', 'json:///etc/cortx/cortx.conf', \
This change not needed, other PR will take care of this

2021-08-10 12:53 UTC, sachinpunadikar requested changes
work on the comments

2021-08-10 14:06 UTC, vastradparayya commented on py-utils/src/utils/support_framework/bundle_generate.py
>          symlink_path = const.SYMLINK_PATH
Done.

2021-08-10 14:09 UTC, vastradparayya commented on py-utils/src/utils/support_framework/bundle_generate.py
> +        Conf.load('cortx_conf', 'json:///etc/cortx/cortx.conf', \
Not removed as of now, for testing it will not work. While integrating with other PR this can removed

2021-08-10 14:12 UTC, sachinpunadikar approved these changes
+1

2021-08-10 14:12 UTC, merged