Feature Implementation of Openldap Mini Provisioner
Seagate/cortx-utils pull request #443
Opened 2021-08-10 06:26 UTC by vimalraghwani20

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-16 09:40 UTC, shahidSTX approved these changes

2021-08-16 09:47 UTC, shalakadharap approved these changes

2021-08-16 09:52 UTC, sachinpunadikar commented on py-utils/setup.py
> +                'cortx.template','cortx.support',
keep the space

2021-08-16 09:54 UTC, sachinpunadikar commented on py-utils/setup.py
> -            'iem = cortx.utils.iem_framework.iem_cli:main',
Why this is removed, keep it

2021-08-16 09:54 UTC, sachinpunadikar commented on py-utils/setup.py
> -            'utils_support_bundle = cortx.support.utils_support_bundle:main'
This should be retained

2021-08-16 09:57 UTC, sachinpunadikar commented on py-utils/setup.py
> +                     'src/utils/setup/openldap/templates/openldap.prepare.tmpl',
All template files should be represented as done at line no 124. See how tmpl_files are defined and do that way

2021-08-16 10:07 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
Suggestion - can we not have this as file ? And may be the same can be extended at other applicable places.

2021-08-16 11:23 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/configcmd.py
> +  utils_tmp_dir = "/opt/seagate/cortx/utils/tmp"
/opt/seagate/abc/xyz is install directory, tmp directory should not be there. Instead use /var/tmp/<your-preferred-name>

2021-08-16 11:27 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/setupcmd.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-08-16 11:35 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node
> +    cluster_id: "TMPL_CLUSTER_ID"
Suggestion -  TMPL_* indicates placeholder. That can be without "".

2021-08-16 11:38 UTC, sachinpunadikar commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +             print('Error while deleting '+ policyFile)
Are you printing on screen ? If so who is going to read & take further action ?
Better log this in a log file.

2021-08-16 11:42 UTC, sachinpunadikar commented on py-utils/utils-post-install
> -# Copy support/utils_support_bundle.py to $utils_path/bin
Retain this code line 36-45

2021-08-16 11:43 UTC, sachinpunadikar requested changes
Work on review comments.
Please do not remove any existing code especially from setup.py, utils-post-install kind of files

2021-08-16 11:44 UTC, sachinpunadikar commented
Fill in the PR template

2021-08-16 11:53 UTC, shalakadharap commented on py-utils/setup.py
> +                'cortx.template','cortx.support',
Fixed

2021-08-16 11:56 UTC, shalakadharap commented on py-utils/setup.py
> -            'iem = cortx.utils.iem_framework.iem_cli:main',
Accidently got removed while rebasing our branch with main

2021-08-16 11:57 UTC, shalakadharap commented on py-utils/setup.py
> -            'utils_support_bundle = cortx.support.utils_support_bundle:main'
Accidently got removed while rebasing our branch with main. Fixed now

2021-08-16 12:01 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/configcmd.py
> +  utils_tmp_dir = "/opt/seagate/cortx/utils/tmp"
Fixed

2021-08-16 12:02 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/setupcmd.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Fixed

2021-08-16 12:07 UTC, shalakadharap commented on py-utils/src/utils/third_party/openldap/base_configure_ldap.py
> +             print('Error while deleting '+ policyFile)
Not sure on this dir and file.
This file is present under - src/utils/setup/openldap/

2021-08-16 12:11 UTC, shalakadharap commented on py-utils/utils-post-install
> -# Copy support/utils_support_bundle.py to $utils_path/bin
Fixed

2021-08-16 12:15 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node
> +    cluster_id: "TMPL_CLUSTER_ID"
Fixed in all template files

2021-08-16 12:27 UTC, shalakadharap commented on py-utils/setup.py
> +                     'src/utils/setup/openldap/templates/openldap.prepare.tmpl',
Fixed

2021-08-16 12:28 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
Keeping this as is . Changing this will invite sanity so.

2021-08-16 12:42 UTC, shalakadharap commented
> Work on review comments.
> Please do not remove any existing code especially from setup.py, utils-post-install kind of files

Accidently got removed while rebasing the branch.
Now files in sync with main branch

2021-08-16 12:48 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
Create improvement ticket if my suggestion is valid

2021-08-16 12:51 UTC, sachinpunadikar approved these changes
+1

2021-08-16 14:49 UTC, ujjwalpl requested changes

2021-08-16 14:49 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/configcmd.py
> +      shutil.copy('/opt/seagate/cortx/s3/install/ldap/rsyslog.d/slapdlog.conf',
There should be no reference to S3 server or any of the path. Please note S3 server rpm is not installed when open LDAP mini provisioner is called.

2021-08-16 14:49 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/postupgradecmd.py
> +      # Remove temporary .old files from S3 temporary location
There should be no assumption about S3 server.

2021-08-16 14:49 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/setupcmd.py
> +    for service_name in s3services_list:
We can not refer to S3 server. This is all about provisioning Open LDAP independent of CORTX.

2021-08-16 14:56 UTC, ujjwalpl requested changes

2021-08-16 14:56 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +    def performbaseconfig(rootpassword, forcecleanup, config_values):
Lets follow a consistent naming conventions. This function should be named as perform_base_config(..). 

Also all the internal functions (which are called from within the class must start with _, e.g. _perform..)

2021-08-16 14:56 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/olcDatabase={2}mdb.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Licensing content needs correction. Please refer to other files which are existing in the utils and correct to match the same.

2021-08-16 14:58 UTC, ujjwalpl requested changes

2021-08-16 14:58 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
I would prefer lets not defer as this never gets corrected later. We anyways need to make changes in the code for other suggestions. Rerunning sanity should not be a problem if automated. Will need to rerun anyways in all the cases due to other requested changes in the code.

2021-08-17 04:12 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
I think we need a discussion here

2021-08-17 04:15 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/postupgradecmd.py
> +      # Remove temporary .old files from S3 temporary location
Fixed

2021-08-17 04:17 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/setupcmd.py
> +    for service_name in s3services_list:
Updated variable name

2021-08-17 04:26 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +    def performbaseconfig(rootpassword, forcecleanup, config_values):
Have renamed perform_base_config to keep in sync with other method names but not renaming other internal functions because its not followed in other files so if I change here then I will have to rename all internal functions accross all the files which is difficult.

2021-08-17 04:28 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/olcDatabase={2}mdb.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Fixed

2021-08-17 04:44 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/configcmd.py
> +      shutil.copy('/opt/seagate/cortx/s3/install/ldap/rsyslog.d/slapdlog.conf',
Handled

2021-08-17 05:26 UTC, t7ko-seagate commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
@sachinpunadikar -- we are not clear on what exactly is the suggestion.  Do we need to create some new file?  Or remove some existing file?  Which file?  What content?  Can you please post details here, or please accept call from Shalaka and give details please.  Thank you.

2021-08-17 05:51 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
Suggestion was simple. Instead of having this long data in the code, can we have this in a file & read it from there. 
@t7ko-seagate @shalakadharap

2021-08-17 09:43 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
Will need some time for exploration on same. So I think ,better if we handle it separately after this merge.

2021-08-17 10:48 UTC, ujjwalpl requested changes

2021-08-17 10:48 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
Let me explain 
Problem 1: Currently code is unreadable.
Problem 2: Entries are hard coded and if there are any changes required, we will have to modify source code. 

Solution:
Place all the records in the ldif file and use python-ldap package to read those ldif file into memory variables like add_record

2021-08-17 10:51 UTC, ujjwalpl requested changes

2021-08-17 10:51 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +    Log.init('OpenldapProvisioning', '/var/log/seagate/utils/openldap', level='DEBUG')
/var/log/cortx/utils/openldap

2021-08-17 11:16 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +        add_record = [
Totally agree with you @ujjwalpl 
but for loading and reading from ldif, python-ldap package is not sufficient. We will also need ldif3 library (pip install ldif3) which requires separate BSD license. As every component has been asked to minimize external dependency I have avoided using the same and went ahead with hard coding.
Sent you mail for the same.

2021-08-17 12:09 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +    Log.init('OpenldapProvisioning', '/var/log/seagate/utils/openldap', level='DEBUG')
Fixed

2021-08-17 13:37 UTC, ujjwalpl approved these changes

2021-08-17 14:19 UTC, bkirunge7 approved these changes

2021-08-17 16:25 UTC, merged