EOS-14157: Moving security extention to cortx-utils
Seagate/cortx-utils pull request #45
Opened 2020-10-09 12:20 UTC by AjinkyaDhumal

Signed-off-by: Ajinkya Dhumal <ajinkya.dhumal@seagate.com>

2020-10-09 12:34 UTC, ujjwalpl requested changes

2020-10-09 12:34 UTC, ujjwalpl commented on py-utils/src/utils/security/cipher.py
> +    #'ujjwal': ['sshd'],
Remove this comment.

2020-10-12 09:56 UTC, AjinkyaDhumal commented on py-utils/src/utils/security/cipher.py
> +    #'ujjwal': ['sshd'],
Done

2020-10-12 11:13 UTC, closed without merging

2020-10-12 11:14 UTC, AjinkyaDhumal commented
Deferred to LDRr2