EOS-23637: Manifest integration
Seagate/cortx-utils pull request #466
Opened 2021-08-19 04:21 UTC by suryakumar1024

# Problem Statement
- Adding logs for manifest component bundling thread

# Design
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-19 09:49 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/bundle_generate.py
> +            f"{' '.join(components_list)}")
Shouldn't we add manifest here, something like below:
Log.debug(f"Generating for  manifest and {const.SB_COMPONENTS} " \

2021-08-19 09:51 UTC, sachinpunadikar requested changes
See if suggestion is meaningful

2021-08-19 09:58 UTC, suryakumar1024 commented on py-utils/src/utils/support_framework/bundle_generate.py
> +            f"{' '.join(components_list)}")
Updated in recent commit.

2021-08-19 12:22 UTC, ujjwalpl approved these changes

2021-08-20 04:42 UTC, sachinpunadikar approved these changes
+1

2021-08-20 04:45 UTC, merged