EOS23627 - Implement ldifParser and remove data hardcoding
Seagate/cortx-utils pull request #467
Opened 2021-08-19 08:50 UTC by shalakadharap

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-19 12:28 UTC, ujjwalpl approved these changes

2021-08-19 13:21 UTC, bkirunge7 approved these changes

2021-08-20 05:22 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/iam-constraints.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-08-20 05:23 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/ppolicy-default.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-08-20 05:23 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/ppolicymodule.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-08-20 05:23 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/ppolicyoverlay.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-08-20 05:24 UTC, sachinpunadikar requested changes
Minor comments

2021-08-20 06:31 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/ppolicyoverlay.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Fixed

2021-08-20 06:31 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/ppolicymodule.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Fixed

2021-08-20 06:31 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/ppolicy-default.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Fixed

2021-08-20 06:31 UTC, shalakadharap commented on py-utils/src/utils/setup/openldap/iam-constraints.ldif
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Fixed

2021-08-20 06:46 UTC, sachinpunadikar approved these changes
+1

2021-08-20 07:12 UTC, merged