EOS-23517: Elasticsearch Miniprovisioner.
Seagate/cortx-utils pull request #471
Opened 2021-08-20 15:38 UTC by shriya-deshmukh

# Problem Statement
- Problem statement 
ElasticsearchMiniProvisioning

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-23 07:54 UTC, cdeshmukh requested changes

2021-08-23 07:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_setup.py
> +    def get_command(desc: str, argv: dict):
These are exact functions used in utils_setup.

@sachinpunadikar any plans to pull this Cmd class & member functions in common place, so every setup make use of it?
Or we can directly use Cmd class by directly importing from utils_setup.py too, but that will bring in unnecessary  dependency on utils setup for 3rd party services like elastic search here

2021-08-23 07:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/setup.yaml
> +        cmd: elasticsearch_setup post_install
absolute path maintained in https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/setup/setup.yaml
while for openldap, no path used as required modules soft linked in utils bin dir.
@sachinpunadikar  which one is recommended approach? Is this one fine ?

2021-08-23 07:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_setup.py
> +                             help='Factory cleanup.')
what about pre-factory support?

2021-08-23 07:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/openldap/__init__.py
> +from .configcmd import ConfigCmd
why touching openldap files in this PR?

2021-08-23 07:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +
this looks unnecessary. plz dont touch files unless needed
mostly PEP warnings ? if yes, then fine

2021-08-23 07:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/openldap/cleanupcmd.py
> +from .setupcmd import SetupCmd, OpenldapPROVError
why these needed, are they creating problem for elastic-search, how ?

2021-08-23 07:54 UTC, cdeshmukh commented on py-utils/utils-post-install
> +# Copy elasticsearch.yml.sample to openldap_config.yaml
typo
> Copy elasticsearch.yml.sample to elasticsearch.yaml

2021-08-23 15:02 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +    elasticsearch_config_path = "/etc/elasticsearch/elasticsearch.yml"
sample file I have just added for reference, in config stage we are adding all required config entries in /etc/elasticsearch/elasticsearch.yml file.
required config entries:
`cluster.name: elasticsearch_cluster
node.name: srvnode-1
network.bind_host: ['localhost', 'srvnode-1']
network.publish_host: ['srvnode-1']
discovery.seed_hosts: ['nodename']
cluster.initial_master_nodes: ['nodename']
http.port: 9200
`

2021-08-23 15:04 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_setup.py
> +                             help='Factory cleanup.')
pre-factory support added in cleanup interface. 
 py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py L-203

2021-08-23 15:07 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/openldap/cleanupcmd.py
> +from .setupcmd import SetupCmd, OpenldapPROVError
While executing elasticsearch_setup it was giving import error for files which are present utils/setup/openldap/openldap dir  as follows,

`[root@ssc-vm-3165 ~]# /opt/seagate/cortx/utils/bin/elasticsearch_setup post_install --config yaml:///etc/sspl_global_config_copy.yaml
Traceback (most recent call last):
  File "/opt/seagate/cortx/utils/bin/elasticsearch_setup", line 24, in <module>
    from cortx.utils.setup.elasticsearch.elasticsearch import Elasticsearch
  File "/usr/lib/python3.6/site-packages/cortx/utils/setup/__init__.py", line 21, in <module>
    from cortx.utils.setup.openldap import OpenldapSetupError
  File "/usr/lib/python3.6/site-packages/cortx/utils/setup/openldap/__init__.py", line 18, in <module>
    from cortx.utils.setup.openldap.openldap import Openldap
  File "/usr/lib/python3.6/site-packages/cortx/utils/setup/openldap/openldap.py", line 28, in <module>
    from configcmd import ConfigCmd
ModuleNotFoundError: No module named 'configcmd'`

2021-08-23 15:11 UTC, shriya-deshmukh commented on py-utils/utils-post-install
> +# Copy elasticsearch.yml.sample to openldap_config.yaml
Removed this line as it is not required.

2021-08-23 15:13 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/setup.yaml
> +        cmd: elasticsearch_setup post_install
we need to add absolute path, updated path as per utils_setup file.

2021-08-23 15:15 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/openldap/__init__.py
> +from .configcmd import ConfigCmd
As mention in [comment](https://github.com/Seagate/cortx-utils/pull/471#discussion_r694060071), wile executing elasticsearch_setup it was giving import errors for openldap_setup files.

2021-08-24 13:47 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/config/elasticsearch.yml.sample
> +cluster.name: elasticsearch_cluster
true, still maintain these enabled configs after respective comments (sections), or there remains no point of these detailed sections in config

2021-08-24 13:47 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +        if self._rc == 0: return self._desc
address all codacy issues, until conflicting ones were seen

2021-08-24 13:47 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +    elasticsearch_config_path = "/etc/elasticsearch/elasticsearch.yml"
Ok, got it

2021-08-24 13:47 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +        elasticsearch_cluster_name = "elasticsearch_cluster"
elasticsearch_cluster_name = "elasticsearch_cluster"
http_port = 9200
These config values should be maintained as Class vars at the top to maintain from one place, refer easily & use.

2021-08-24 13:47 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +                raise
@nitin-seagate Should any provisioning step should failout if any required srvice restart fails, like rsyslog here. Worst case, added config wont be in effect until rsyslog is restarted. Any late stage where provisioner would do such restart of 3rd party services, i doubt hearing that yet, in which case we should fail out here only then

we dont need to fail out of rsyslog restart fails, logging would suffice

2021-08-24 13:47 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +        # TODO: Perform actual steps. Obtain inputs using Conf.get(index, ..)
anything needed here even ?

2021-08-24 14:55 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +        elasticsearch_cluster_name = "elasticsearch_cluster"
Done.

2021-08-24 14:55 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +                raise
>> we dont need to fail out of rsyslog restart fails, logging would suffice

okay, done.

2021-08-24 14:55 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +        # TODO: Perform actual steps. Obtain inputs using Conf.get(index, ..)
For now nothing is needed for prepare inetrface.

2021-08-25 04:54 UTC, soniyamoholkar reviewed
Please use fully qualified import path instead of relative path. 
e.g. instead of `from .setupcmd import SetupCmd, OpenldapPROVError` use  
`from cortx.utils.conf_store import Conf`

2021-08-25 05:19 UTC, udayan-y21 requested changes

2021-08-25 05:19 UTC, udayan-y21 commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +                DbusServiceHandler().restart('rsyslog.service')
Instead of directly using `DbusServiceHandler` Use ` Service` class which will internally call Dbservicehandler.
```
           from cortx.utils.service.service_handler import Service
           service_obj = Service('rsyslog.service')
           service_obj.restart()
```
Please make changes wherever applicable in PR

2021-08-25 05:19 UTC, udayan-y21 commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +                opendistro-reports-scheduler opendistro-security"
In pre-factory, 
System should go in Just before Post-install stage. So dont have to remove rpms from system. 
Pre-factory will include, reverting post-install phase.
So ypur rpms will remain as it is.

2021-08-25 05:19 UTC, udayan-y21 commented on py-utils/src/utils/setup/elasticsearch/setup.yaml
> +        args: --config $URL [--pre-factory]
Add `Pre-upgrade` and `Post-upgrade` in setup.yaml

2021-08-25 05:21 UTC, soniyamoholkar requested changes

2021-08-25 05:21 UTC, soniyamoholkar commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_setup.py
> +            f"cmd   post_install, config, init, reset, test, cleanup\n"
add prepare, pre-upgrade and post-upgrade

2021-08-25 07:20 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +                DbusServiceHandler().restart('rsyslog.service')
done.

2021-08-25 07:27 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +                opendistro-reports-scheduler opendistro-security"
Removed RPM removal code and logs and date dir deletion from pre-factory to make miniprovisioner cycle(postinsgtall-prepre-config-init-reset-cleanup-cleanup_prefactory - then again the same) works.

.
>> Pre-factory will include, reverting post-install phase.
In post_install we are just deleting opendistro-security plugins from config file. and in default config stage we are resetting config, so for pre-factory we don't need to do anything, logs and data dir will get removed  during rpm removal.

2021-08-25 07:27 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/setup.yaml
> +        args: --config $URL [--pre-factory]
Done.

2021-08-25 07:27 UTC, shriya-deshmukh commented on py-utils/setup.py
> +                     ('%s/conf/elasticsearch' % utils_path, elasticsearch_tmpl_files),
Done.

2021-08-25 07:27 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_setup.py
> +            f"cmd   post_install, config, init, reset, test, cleanup\n"
Done.

2021-08-25 07:28 UTC, shriya-deshmukh commented
> Please use fully qualified import path instead of relative path.
> e.g. instead of `from .setupcmd import SetupCmd, OpenldapPROVError` use
> `from cortx.utils.conf_store import Conf`

Done.

2021-08-25 07:37 UTC, shriya-deshmukh commented on py-utils/setup.py
> +                     ('%s/conf/elasticsearch' % utils_path, elasticsearch_tmpl_files),
Done.

2021-08-25 09:10 UTC, soniyamoholkar approved these changes

2021-08-25 10:19 UTC, udayan-y21 approved these changes

2021-08-25 12:23 UTC, ujjwalpl requested changes

2021-08-25 12:23 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +from cortx.utils.setup.openldap.setupReplication import Replication
Please remove ldap related changes in this PR.

2021-08-25 12:24 UTC, ujjwalpl requested changes

2021-08-25 12:24 UTC, ujjwalpl commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_service.py
> +    def validate(self, phase: str):
all internal functions must start with "_"

2021-08-25 13:00 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +from cortx.utils.setup.openldap.setupReplication import Replication
Removed ldap changes from this PR.
Created separate PR for addressing same: https://github.com/Seagate/cortx-utils/pull/483

2021-08-31 10:16 UTC, kupranay approved these changes

2021-08-31 12:15 UTC, cdeshmukh approved these changes

2021-08-31 16:54 UTC, sachinpunadikar commented on py-utils/src/utils/setup/__init__.py
> +from cortx.utils.setup.elasticsearch import Elasticsearch
I think these 2 entries can be safely removed from this file.

2021-08-31 17:07 UTC, sachinpunadikar commented on py-utils/utils-post-install
> +elasticsearch_conf_path=$utils_path/conf/elasticsearch
why "elasticsearch_conf_path" defined ? where it is used ?

2021-08-31 17:15 UTC, sachinpunadikar commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +        """ Perform initialization. Raises exception on error """
comment & logging is wrong

2021-08-31 17:16 UTC, sachinpunadikar commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +        """ Perform initialization. Raises exception on error """
comment & logging is wrong

2021-08-31 17:17 UTC, sachinpunadikar commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +        """ Performs Configuration reset. Raises exception on error """
correct the comment

2021-08-31 17:17 UTC, sachinpunadikar commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +        """ Perform initialization. Raises exception on error """
correct the comment

2021-08-31 17:21 UTC, sachinpunadikar requested changes
Please work on the comments

2021-09-01 08:24 UTC, shriya-deshmukh commented on py-utils/utils-post-install
> +elasticsearch_conf_path=$utils_path/conf/elasticsearch
No required here, removed.

2021-09-01 08:24 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +        """ Perform initialization. Raises exception on error """
Done.

2021-09-01 08:24 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +        """ Perform initialization. Raises exception on error """
Done.

2021-09-01 08:24 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +        """ Performs Configuration reset. Raises exception on error """
Done.

2021-09-01 08:24 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +        """ Perform initialization. Raises exception on error """
Done.

2021-09-01 08:25 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +                raise Exception(msg)
Done.

2021-09-01 08:39 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/__init__.py
> +from cortx.utils.setup.elasticsearch import Elasticsearch
Done.

2021-09-01 08:40 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_setup.py
> +        self.elasticsearch.validate("post_install")
Done.

2021-09-01 09:26 UTC, sachinpunadikar approved these changes
+1

2021-09-01 09:52 UTC, cdeshmukh approved these changes
approved with minor comments

2021-09-01 09:52 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
> +                raise Exception(msg)
if someone passes unsupported phase i meant. Anyways, thats fine, its suppressed silently then.

2021-09-01 09:52 UTC, cdeshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_setup.py
> +        # TODO: Add actions here
remove the TODO, guess its residual

2021-09-01 10:04 UTC, sachinpunadikar commented
test this please

2021-09-01 10:04 UTC, shriya-deshmukh commented on py-utils/src/utils/setup/elasticsearch/elasticsearch_setup.py
> +        # TODO: Add actions here
Removed.

2021-09-01 10:13 UTC, cdeshmukh approved these changes

2021-09-01 12:06 UTC, merged