EOS-22576: Implement cortx setup mini provisioner interfaces
Seagate/cortx-utils pull request #474
Opened 2021-08-23 10:28 UTC by sandeepsgt

- Add post_install, config, init, prepare, test, reset, cleanup interfaces

Signed-off-by: Sandeep Anjara <sandeep.anjara@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-23 11:40 UTC, knekrasov requested changes

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +        return 0
Why do you need to return a C-style code when you use exceptions?

If I run the method and it raises an exception, I don't need the return code.
If the invocation didn't throw an exception, then there is no need to check the return code. No exception means "OK" already.

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +    def run_as_server(self, server_node):
I don't see where this method runs anything. It just returns a bool according to some conditions.

Suggestion:
```suggestion
    def is_server_node(self, node_name: str) -> bool:
```

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +                return True
Let's keep it simple.
```suggestion
            return node_id < 4
```

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +        elif storage_set_count == 6:
BTW can you please elaborate why (and how) this server node distribution works?

The fact is that Hare requires to run Consul in server mode if and only if the node runs `confd` process (this is connected with RC leader election and the fact that only server nodes can participate in the election). Is this requirement considered in your algorithm somehow?

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +        if "TestConsul" in globals():
This looks more like a hack, sorry.

Suggestion: use [null object pattern](https://en.wikipedia.org/wiki/Null_object_pattern) instead. The idea is that somewhere in your code you should have a function that returns either "real" TestConsul or a stub one (that would either do nothing or log the corresponding message). All the rest of your code doesn't actually need to know about the fact that `TestConsul` could be not imported or something.

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +        return 0
C-style return codes are redundant and error prone. Please use exceptions if you want to report about an issue.

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +            test_consul = TestConsul()
It seems like this "TestConsul" is something that tests that consul is sane.

Isn't it a better idea to have this functionality written as normal `unittest` or `pytest` driven  tests? 
Benefits:
1. The list of tests can be extensible (there is no risk to forget to run some test from this code - a newly added test will be applied as soon as it is placed into the right folder and has the corresponding signature)
2. If some tests fail, the corresponding error report can be more user-friendly (usually the test name already describes the predicate being checked by this test; so if, say, `test_my_function_returns_0` fails, I can understand, which invariant is violated in the code).

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul_setup.py
> +class Cmd:
This class looks like an over-complication.

We could either use argparse directly or start using [`click`](https://click.palletsprojects.com/en/8.0.x/) library if we want to have a nicer syntax. 

What problem does this `Cmd` class solve?

2021-08-23 11:40 UTC, knekrasov commented on py-utils/test/consul/test_consul.py
> +        result = self.consul.kv.delete("test_key")
It seems like this test assumes that "test_key" key already exists although neither this test creates this key nor `setUp()` takes care of it. So this means that the order in which the tests should run cannot be arbitrary and this is totally incorrect,

2021-08-23 11:40 UTC, knekrasov commented on py-utils/test/consul/test_consul.py
> +if __name__ == "__main__":
No need to have the test as a runnable script.

Normally, the user runs the tests either as `python -m unittest` or just `mypy`.

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +        SimpleProcess(command).run()
Of the command fails, will `SimpleProcess.run`  raise an exception?
If not then, the error can be potentially swallowed.

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +                   f"ConditionFileNotEmpty={config_path}/consul.hcl",
It seems like the code is not formatted properly. Please consider https://github.com/google/yapf to format the sources automatically so they become PEP-8 compliant.

2021-08-23 11:40 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +#!/bin/env python3
Shebangs are needed for executable scripts only.

2021-08-23 12:28 UTC, vaibhavparatwar commented
Please address codacy issues which ever are remvable @sandeepsgt

2021-08-23 12:31 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul.py
> +        with open("/usr/lib/systemd/system/consul.service") as f:
opening in write mode will enable to read & write both, why to open in read mode first separately ?

2021-08-23 12:31 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul.py
> +        return 0
what about consul user creation? Am referring the table
https://seagate-systems.atlassian.net/wiki/spaces/sspl/pages/626000390/Miniprovisioner+interfaces+for+3rd+party+services.

2021-08-23 12:31 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul.py
> +        if storage_set_count < 5:
add more comments around this code. Atleast 3 consul agents needed as server to form the quorum, is the logic here i believe. Same case for remaining below cases

Also instead of hardcoding, we can come up with some formula, which can applied to various number of cluter (storage set) nodes and doesnt limit to 12, so scaling doesnt remain an issue

2021-08-23 12:31 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul.py
> +            return 0
no consul user reference here too

2021-08-23 12:31 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_setup.py
> +class Cmd:
This Cmd class code can be pulled in one common file, from where all classes would use it, right now its getting duplicated.
Sync with Shriya for elastic search mini provisioner, had similar command for that PR too. Both needs to have same structure so PRs doesnt conflict later

2021-08-23 12:31 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/templates/consul.config.tmpl.1-node.sample
> +        private_fqdn: 10.230.249.168
dont expose internal IP range, put 0.0.0.0, which documentation should call out to update

2021-08-23 12:31 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/templates/consul.config.tmpl.3-node.sample
> +        private_fqdn: 10.230.249.168
same comment

2021-08-23 12:31 UTC, cdeshmukh commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +from .setupReplication import Replication
not sure why these ldap setup file changes needed, had seen in elastic search PR too

2021-08-23 13:19 UTC, ujjwalpl requested changes

2021-08-23 13:19 UTC, ujjwalpl commented on py-utils/src/utils/setup/openldap/base_configure_ldap.py
> +from .setupReplication import Replication
Consul Provisioner needs to be independent provisioner with any dependency on LDAP, or even CORTX.

2021-08-23 13:28 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +        with open("/usr/lib/systemd/system/consul.service") as f:
In the way it is written there is no need to rewind the cursor within the file. We firstly read the text, then we replace something in sed-like manner and then we write the updated text into the same file. So we don't need to jump over this file back and forth. In case you described the logic would be more complicated but hardly it brings any benefit.

2021-08-23 19:26 UTC, mssawant commented on py-utils/src/utils/setup/consul/consul.py
> +        PkgV().validate('rpms', ['consul-1.9.1-1'])
I think it would be good to take version as a configurable parameter from conf-store, otherwise we will have to make a code change every time we bump up the version.
So, Cortx components must test with a particular version of Consul and if everything is working fine that version must be used by the provisioner and Consul mini-provisioner must validate that with the installed rpm.

2021-08-23 21:07 UTC, mssawant commented on py-utils/src/utils/setup/consul/consul.py
> +        elif storage_set_count == 6:
@knekrasov, It needs to be the other way around, `consul_server` role must be added to the roles for a given node in conf-store to the following kv,
```
<html>
<body>
<!--StartFragment-->

prepare | server_node>{machine-id}>roles | ["primary", "openldap_master", "kafka_server"]
-- | -- | --


<!--EndFragment-->
</body>
</html>
```

Hare will do the following (this is there in Hare consul-sep branch)
```
        roles = store.get(f'server_node>{machine_id}>roles')
        if 'consul_server' in roles:
            servers.value.append(M0ServerDesc(
                io_disks=DisksDesc(
                    data=DList([], 'List Text'),
                    meta_data=Maybe(None, 'Text')),
                runs_confd=Maybe(True, 'Bool')))
```

2021-08-23 21:50 UTC, mssawant commented on py-utils/src/utils/setup/consul/consul.py
> +        if storage_set_count < 5:
Overall it depends on how many node failures a cluster needs to tolerate. Worst case if all the node failures are Consul server node failures then the entire cluster will be non-functional. But this was agreed upon and accepted to lose the entire cluster is Consul cluster is down. So 2 points,
1. Ideally 3 - 5 servers should be enough per data center. It actually depends upon the over all kv access and server load, for now we can,
    -  start with 3 and increase by 2 for every 18 nodes, 18 nodes = 3 consul servers, 36 = 5 and so on.
    - or have it passed as a configurable parameter using conf-store.
2. Algorithm to distribute the Consul server nodes across the cluster to minimize the impact.
    - This we have simplified to select first N nodes from the cluster resulting from above calculation.

2021-08-24 07:27 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul.py
> +        elif storage_set_count == 6:
@mssawant Correct. But according to what you've described, the server distribution algorithm in this PR should use `consul_server` role instead of this `>` or `>=` comparisons. Is that correct?

2021-08-31 05:57 UTC, ujjwalpl approved these changes

2021-08-31 12:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +    def validate_post_install(self):
Like in elastic search mini provisioner, validate() can stay as one function, with arguments stating validation needed at what stage i.ep post_install or config. Looks more structured & cleaner interfaces

2021-08-31 12:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +    def post_install(self):
So RE has created consul rpm, whose spec file has these steps already? If i remember correctly, in SSPL we kept minimal & must steps in spec files, rest all moved to mini provisioner stages, so reset / cleanup can be done from mini provisioner interfaces again, without uninstalling rpm !?

2021-08-31 12:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +        with open("/usr/lib/systemd/system/consul.service", "w") as f:
yes, approach itself doesnt seem right to me. Opening same file twice, to read and write separately, can be avoided easily.

2021-08-31 12:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +        server_node_fqdn = Conf.get(self.index,
>bootstrap_expect = len(server_node_fqdns)

is fine

> server_node_fqdn = Conf.get(self.index, f"server_node>{machine_id}>network>data>private_fqdn")

though i dont see the need for this check again, not sure why not optimizing as mentioned in comment [here ](https://github.com/Seagate/cortx-utils/pull/474#discussion_r696375180)

2021-08-31 12:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +        PkgV().validate('rpms', ['consul'])
>mssawant 8 days ago
I think it would be good to take version as a configurable parameter from conf-store, otherwise we will have to make a code change every time we bump up the version.
So, Cortx components must test with a particular version of Consul and if everything is working fine that version must be used by the provisioner and Consul mini-provisioner must validate that with the installed rpm.

I agree with @mssawant, we should add version field in confstore config , to allow upgrade in future. Would be useful if no code is affected in upgraded version and we would be able to support version upgrade without any code in CORTX

2021-08-31 12:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +        with open("/usr/lib/systemd/system/consul.service") as f:
yes, check comment at line 133

2021-08-31 12:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_setup.py
> +class Cmd:
Changes to Cmd class member functions would reflect for derived classes in one go, be it argparse related logic or something else. Where in sub-classes you see direct usage of subparsers? Without direct usage, they are abstracted only for derive classes.

On introducing new sub-classes, yes i agree overhead there to align with interfaces, even if each of them doesnt need, thats cost of consistency sometimes.

2021-08-31 12:54 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/templates/consul.config.tmpl.3-node.sample
> +    cluster_id: "3f670dd0-17cf-4ef3-9d8b-e1fb6a14c0f6"
so for reverse lookup, from node to cluster config. When is this needed really ?

2021-08-31 12:54 UTC, cdeshmukh commented on py-utils/test/consul/consul.py
> +        self.consul.kv.put("test_key", "test_value")
> If something is failing, then exception will be raise. How test can pass?

Where are the exception blocks? You mean assertions here? If yes, still read my previous comment

>what if delete failed earlier, put failed now. get will still pass. its rare case, but would happen

1st iteration, delete fail result will show up.
lets say in 2nd test iteration, put failed, again shows up in results.
Will test will still go ahead & try get()? If yes, it will pass. so 50% in this case would be wrong rather, given should have failed too

2021-08-31 14:07 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul_setup.py
> +class Cmd:
> Where in sub-classes you see direct usage of subparsers? 

Ok, I don't see subparsers. But there is definitely the use of parsers (CleanupCmd), so the abstraction still seems to be leaky.

> Changes to Cmd class member functions would reflect for derived classes in one go

I'm afraid you're misleading yourself. Deriving usually means OOP and polymorphism. But the users of this approach should clearly understand that bi OOP features will work because the most of the methods in `Cmd` class are static. Static methods cannot be overridden and even if a developer tries to re-define such a method in a subclass, the modified version of the function will apply if and only if the caller uses the exact class name (FYI that's the reason why Singleton is often [considered as anti-pattern](https://stackoverflow.com/a/138012): the code becomes coupled).


The fact is that such a code is approved in `cortx-utils` means that this strange (and quite dangerous) habit will be spread out through all the components and may be understood as a "best practice".

2021-09-01 10:14 UTC, sandeepsgt commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +    def validate_post_install(self):
Done

2021-09-01 10:15 UTC, sandeepsgt commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +        server_node_fqdn = Conf.get(self.index,
Updated

2021-09-01 10:17 UTC, sandeepsgt commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +        PkgV().validate('rpms', ['consul'])
As I mentioned earlier , Version related information we cannot add in conf-store. I checked with @nitin-seagate

2021-09-01 10:21 UTC, sandeepsgt commented on py-utils/src/utils/setup/consul/templates/consul.config.tmpl.3-node.sample
> +    cluster_id: "3f670dd0-17cf-4ef3-9d8b-e1fb6a14c0f6"
Removed cluster_id and storage_set, directly iterating over keys in server_node now

2021-09-01 10:27 UTC, shailesh-vaidya commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +    def post_install(self):
@sandeepsgt RE team is not creating a custom consul package. We are using the locally downloaded `consul-1.9.1-1.x86_64.rpm` package.

2021-09-01 10:28 UTC, sandeepsgt commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +        with open("/usr/lib/systemd/system/consul.service", "w") as f:
Done

2021-09-01 10:43 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +    def post_install(self):
ok, then fine

2021-09-01 11:04 UTC, cdeshmukh approved these changes

2021-09-01 11:04 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul_setup.py
> +class Cmd:
> But there is definitely the use of parsers (CleanupCmd),

Yes, sure its not perfect. Though it serves the major purpose. When needed to change base, we can still change with minimal impact

> Deriving usually means OOP and polymorphism.

Yes obviously, where polymorphism gives an option to override, however if not needed derived classes free to use same base class implementation, same applies here with static member functions.

>Static methods cannot be overridden 

Not sure why discussion going this way. As i see it, its not intended to over ride later, otherwise functions would not have been declared static. Discussion started with purpose of the class and now it has become strange & dangerous, with arguments !!?

2021-09-02 10:05 UTC, knekrasov commented on py-utils/src/utils/setup/consul/consul_setup.py
> +class Cmd:
Ok, summarizing the discussion:
1. `Cmd` approach is awkward and wordy but it is good because everybody in this component does this way.
2. Technical arguments that the approach could have been better (initially; this is not a question to this particular PR) are not accepted.

I have no other comments then.

2021-09-02 17:51 UTC, mssawant commented on py-utils/src/utils/setup/consul/consul.py
> +        if storage_set_count < 5:
@sandeepsgt, the roles key will become obsolete with supporting containerization as per my latest information. So we need to have some different algorithm to decide where to start a Consul server and where not.
But, I think this can be done as a separate task.

2021-09-02 17:59 UTC, mssawant commented
@sandeepsgt, please fixup the multiple commits to have just one single relevant commit, following commit messages are not really relevant and does not provide much information about the actual problem and the solution,
```
EOS-22576: Move directory creation to config stage 

- Fix test interface

Signed-off-by: Sandeep Anjara <sandeep.anjara@seagate.com>
@sandeepsgt
sandeepsgt committed 7 days ago
 
EOS-22576: Add config validation 

Fix codacy issues

Signed-off-by: Sandeep Anjara <sandeep.anjara@seagate.com>
@sandeepsgt
sandeepsgt committed 7 days ago
 
EOS-22576: Fix codacy issue 

Signed-off-by: Sandeep Anjara <sandeep.anjara@seagate.com>
@sandeepsgt
sandeepsgt committed 6 days ago
  
Commits on Sep 1, 2021
EOS-22576: Address review comments 

@sandeepsgt
sandeepsgt committed yesterday
  
EOS-22576: Use unique key per node for test 
```

2021-09-02 18:26 UTC, mssawant approved these changes
Looks good mostly. Few comments. No further review round needed.

2021-09-02 18:26 UTC, mssawant commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +            max_retry = 3
Retries are tricky, things may work at ith iteration and fail at i + 1th iteration. Either you retry infinitely until things work or fail at the first attempt.

2021-09-02 18:26 UTC, mssawant commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +        if stage == "post_install":
Readability will improve if we have separate validation functions per stage, e.g. post_install_validate(), config_validate(), etc and then you can do,
```
getattr(self, '{}_validate'.format(stage.lower()))()
```
Code will be much less and readable.

2021-09-02 18:26 UTC, mssawant commented on py-utils/src/utils/setup/consul/consul_prvsnr.py
> +        """Performs configurations. Raises exception on error."""
This extremely generic documentation does not provide any value, instead we can replace  with,
" Configures sets up Consul config and data directory paths and configures Consul agent".

2021-09-03 05:44 UTC, cdeshmukh commented on py-utils/src/utils/setup/consul/consul.py
> +        if storage_set_count < 5:
Yes, K8 specific tweaks needs to be addressed separately, as i know in 'kubernetes' branch

2021-09-03 10:31 UTC, sachinpunadikar approved these changes
+1

2021-09-03 16:05 UTC, merged