Updating template files to add quotes
Seagate/cortx-utils pull request #476
Opened 2021-08-23 11:23 UTC by shalakadharap

# Problem Statement
- Adding quotes to template

# Design
-  Added quotes to template

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-23 17:25 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node
> +    - server_nodes: "['TMPL_MACHINE_ID']"
This is the only required change, rest all should be reverted back for this file

2021-08-23 17:25 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.3-node
> +    - server_nodes: "['TMPL_MACHINE_ID1','TMPL_MACHINE_ID2','TMPL_MACHINE_ID3']"
This is the only required change, rest all should be reverted back for this file

2021-08-23 17:26 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.1-node
> +    - server_nodes: "['TMPL_MACHINE_ID']"
This is the only required change, rest all should be reverted back for this file

2021-08-23 17:26 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.3-node
> +    - server_nodes: "['TMPL_MACHINE_ID1','TMPL_MACHINE_ID2','TMPL_MACHINE_ID3']"
This is the only required change, rest all should be reverted back for this file

2021-08-23 17:27 UTC, sachinpunadikar commented on py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.3-node
> +    - server_nodes: "['TMPL_MACHINE_ID1','TMPL_MACHINE_ID2','TMPL_MACHINE_ID3']"
This is the only required change, rest all should be reverted back for this file

2021-08-23 17:27 UTC, sachinpunadikar requested changes
Work on comments. If you need any clarification reach to @gauravchaudhari02

2021-08-24 04:28 UTC, closed without merging

2021-08-24 04:28 UTC, shalakadharap commented
Duplicate