Purge fails on reset due to less timeout
Seagate/cortx-utils pull request #488
Opened 2021-08-30 11:30 UTC by selvakumaar5496

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-30 14:16 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                return MessageBusError(errors.ERR_OP_FAILED,\
Will this change the signature of this method ? Will it impact S3 ?

2021-08-31 04:39 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                return MessageBusError(errors.ERR_OP_FAILED,\
No, it wont.

2021-08-31 04:54 UTC, sachinpunadikar approved these changes
+1

2021-08-31 06:04 UTC, ujjwalpl requested changes

2021-08-31 06:04 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +                    while True:
This cant be an indefinite cycle. Code may hang. you should try for retry_count times and fail if it did not succeed.

2021-08-31 06:04 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                return MessageBusError(errors.ERR_OP_FAILED,\
Exception needs to be raised and handled by the caller as standard mechanism.

2021-08-31 10:57 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +                    while True:
That is the current behavior, It will fail if it reaches the retry_count.

2021-08-31 12:29 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +                    while True:
Done. Retried for 20 counts and it will fail it it reach beyond the count

2021-09-01 05:55 UTC, sachinpunadikar approved these changes
+1

2021-09-01 13:35 UTC, ujjwalpl requested changes

2021-09-01 13:35 UTC, ujjwalpl commented on py-utils/src/setup/utils.py
> +                        time.sleep(2*retry_count)
Remove hard coded value 2 and replace with variable called wait_factor and set that value as 0. 
See if you can make retry_count value configurable from outside. 

def reset(retry_count):
....

2021-09-02 17:01 UTC, ujjwalpl approved these changes

2021-09-02 17:45 UTC, sachinpunadikar commented
test this please

2021-09-03 05:10 UTC, sachinpunadikar commented
run vm-deployment

2021-09-03 05:23 UTC, sachinpunadikar commented
test this please

2021-09-03 07:12 UTC, sachinpunadikar commented
run vm-deployment

2021-09-03 09:51 UTC, sachinpunadikar commented
rerun vm-deployment

2021-09-03 14:44 UTC, merged