EOS-13938: MD5 Hash Algorithm for computing checksum of a given buffer
Seagate/cortx-utils pull request #49
Opened 2020-10-16 06:16 UTC by Shreya-18

# Problem Statement:
https://jts.seagate.com/browse/EOS-13938 Calculate hash of a given buffer
## Problem Description:
_Currently, for the control-server REST APIs there is no concurrency control which could lead to data corruption. This can be avoided by implementing the Entity Tag (ETag) header in the HTTP request. This can be achieved via hash for every resource request and adding it to the Etag header._

## Solution:

Library used - **<openssl/md5.h>** 
APIs used :
- MD5_Init() - initializes a MD5_CTX structure.  
- MD5_Update() - can be called repeatedly with chunks of the message to be hashed (len bytes at data).  
- MD5_Final() - places the message digest in md, which must have space for D5_DIGEST_LENGTH == 16 bytes of output, and erases the MD5_CTX. 

Helper functions:
- Function to get hex string from char array message digest. 
- Function to validate the hash

2020-10-16 08:32 UTC, SeagateChaDeepak commented on c-utils/src/management/md5hash.c
> +	rc = MD5_Update(&hash->md5ctx, input, length);
i sort of expected the usage of MD5_Update as follows :

md5sum(const char *str, int length) {
    int n;
    MD5_CTX c;
    unsigned char digest[16];
    char *out = (char*)malloc(33);

    MD5_Init(&c);

    while (length > 0) {
        if (length > 512) {
            MD5_Update(&c, str, 512);
        } else {
            MD5_Update(&c, str, length);
        }
        length -= 512;
        str += 512;
    }

    MD5_Final(digest, &c);
}

If we receive a large input buffer then, we can divide it into blocks and call MD5_Update on each block seperately. This might improve memory usage.... what are your thoughts?

2020-10-16 08:35 UTC, SeagateChaDeepak commented on c-utils/src/management/md5hash.c
> +		strncat(hex, &hex_tbl[ch & 15], sizeof(char));
codacy checks are failing for strncat

2020-10-16 09:33 UTC, Shreya-18 commented on c-utils/src/management/md5hash.c
> +	rc = MD5_Update(&hash->md5ctx, input, length);
It's a very good idea of using MD5_Update() efficiently. Thanks, I will work on it.

2020-10-16 11:32 UTC, Shreya-18 commented on c-utils/src/management/md5hash.c
> +	rc = MD5_Update(&hash->md5ctx, input, length);
Done, please have a look.

2020-10-19 05:13 UTC, s-arya requested changes
Looks good overall, some minor comments.

2020-10-19 05:13 UTC, s-arya commented on c-utils/src/management/md5hash.c
> +
Please remove the extra newline.

2020-10-19 05:13 UTC, s-arya commented on c-utils/src/management/md5hash.c
> +#define BLK_SIZE 512
Can we rename this to less generic term, MD5_BLK_SIZE or HASH_BLK_SIZE?

2020-10-19 05:13 UTC, s-arya commented on c-utils/src/management/md5hash.c
> +		log_err("Requested hash is doesn't match with calculated hash");
Please rephrase this error message.

2020-10-19 05:13 UTC, s-arya commented on c-utils/src/test/management/md5hash_test.c
> +	printf("rc(%d) hash calculated= %s\n", rc, hex_str.s_str);
Do we need a printf here or anywhere in the test code? Ideally test should only print if test passed or failed and print an error message in case test fails.

2020-10-19 06:02 UTC, Shreya-18 commented on c-utils/src/management/md5hash.c
> +
done

2020-10-19 06:02 UTC, Shreya-18 commented on c-utils/src/management/md5hash.c
> +#define BLK_SIZE 512
Sure, nice idea. Done

2020-10-19 06:03 UTC, Shreya-18 commented on c-utils/src/management/md5hash.c
> +		log_err("Requested hash is doesn't match with calculated hash");
yes, done

2020-10-19 06:04 UTC, Shreya-18 commented on c-utils/src/test/management/md5hash_test.c
> +	printf("rc(%d) hash calculated= %s\n", rc, hex_str.s_str);
yes, you are correct, I was testing it for my purpose. I have removed it now... as it's no longer useful.

2020-10-19 06:55 UTC, s-arya approved these changes

2020-10-19 06:55 UTC, s-arya commented on c-utils/src/management/md5hash.c
> +		strncat(hex, &hex_tbl[ch >> 4], size);
Could you please add the significance of 4 and 15( line below) in the comment. As far as possible, let's avoid the hardcoded values, see if we can #define these.

2020-10-19 07:35 UTC, SeagateChaDeepak approved these changes
+1 LGTM

2020-10-19 08:19 UTC, Shreya-18 commented on c-utils/src/management/md5hash.c
> +		strncat(hex, &hex_tbl[ch >> 4], size);
Sure, let me explain it.
> conversion of ASCII char to hex format gives 2 bytes
4 and 15 is for 
ascii higher 4 bits (right shift 4) -> to hex
ascii lower 4 bits (AND 15)--> to hex 

Thanks, I will add #defines and add the significance in the description comment.

2020-10-19 09:51 UTC, Shreya-18 commented on c-utils/src/test/management/md5hash_test.c
> +	printf("rc(%d) hash calculated= %s\n", rc, hex_str.s_str);
done

2020-10-19 09:51 UTC, Shreya-18 commented on c-utils/src/management/md5hash.c
> +		strncat(hex, &hex_tbl[ch >> 4], size);
done

2020-10-19 10:07 UTC, Shreya-18 commented on c-utils/src/management/md5hash.c
> +		strncat(hex, &hex_tbl[ch & 15], sizeof(char));
Yes, thanks! Along with Subhash's review comments, I have changed it to snprinf(). Now codacy checks pass.

2020-10-19 10:08 UTC, Shreya-18 commented on c-utils/src/management/md5hash.c
> +		strncat(hex, &hex_tbl[ch >> 4], size);
Done.

2020-10-20 11:08 UTC, merged