EOS-24098: Configure log directory
Seagate/cortx-utils pull request #491
Opened 2021-08-31 06:37 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

# Problem Statement
- Log directory for cortx-py-utils should be configurable

# Design
-  Read log directory from cortx.conf file

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [x] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-08-31 06:54 UTC, sachinpunadikar commented on py-utils/cortx.conf.sample
> +    "log_dir": "/var/log",
This should not be utils specific. The way install_path is for entire CORTX, we can have log_path

2021-08-31 07:34 UTC, selvakumaar5496 commented on py-utils/cortx.conf.sample
> +    "log_dir": "/var/log",
Done

2021-08-31 07:37 UTC, sachinpunadikar commented on py-utils/src/setup/utils_setup.py
> +    log_path = os.path.join(log_dir, 'cortx/utils')
log_path -> utils_log_path

2021-08-31 07:41 UTC, sachinpunadikar commented
Need to get the log_dir from passed in confstore (from provisioner / template file) in mini-provisioning. If this is not provided, there should be a default value

2021-08-31 08:11 UTC, selvakumaar5496 commented on py-utils/src/setup/utils_setup.py
> +    log_path = os.path.join(log_dir, 'cortx/utils')
done

2021-08-31 13:43 UTC, vastradparayya approved these changes

2021-08-31 17:55 UTC, sachinpunadikar commented on py-utils/src/setup/utils_setup.py
> +    log_dir = Conf.get('config_file', 'log_dir', '/var/log')
this should be read from passed in information (like populated template file)

2021-08-31 17:59 UTC, sachinpunadikar requested changes
please work on comment

2021-09-01 06:40 UTC, selvakumaar5496 commented on py-utils/src/setup/utils_setup.py
> +    log_dir = Conf.get('config_file', 'log_dir', '/var/log')
done in utils_setup config phase

2021-09-01 07:24 UTC, sachinpunadikar commented on py-utils/src/setup/utils_setup.py
> +    log_dir = Conf.get('config_file', 'log_dir', '/var/log')
config phase will set the log_dir for rest of the code.
But utils_setup log will go to the default place (i.e. /var/log/..). Hence asking to get the required log directory here as well, and create log file for utils_setup in that directory.

2021-09-01 09:43 UTC, sachinpunadikar approved these changes
+1

2021-09-01 12:10 UTC, merged