EOS-23255: Introducing logging for IEM framework
Seagate/cortx-utils pull request #498
Opened 2021-09-01 11:37 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

# Problem Statement
- Introducing IEM logging

# Design
-  if Logger is intialized by parent (caller) script, Log class is not initialized.

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-09-03 04:14 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +        os.chmod('/var/log/cortx/utils/message_bus/iem.log', 0o0666)
@rahul-tripathi-git path should be '/var/log/cortx/utils/iem/iem.log' right? Just confirming.

2021-09-03 04:16 UTC, vastradparayya commented on py-utils/src/support/utils_support_bundle.py
> +        'iem': '/var/log/cortx/utils/message_bus/iem.log'
/var/log/cortx/utils/message_bus/iem.log -> /var/log/cortx/utils/iem/iem.log

2021-09-03 04:17 UTC, vastradparayya reviewed
Please confirm this

2021-09-03 04:27 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        os.chmod('/var/log/cortx/utils/message_bus/iem.log', 0o0666)
changed it to iem directory.

2021-09-03 04:27 UTC, rahul-tripathi-git commented on py-utils/src/support/utils_support_bundle.py
> +        'iem': '/var/log/cortx/utils/message_bus/iem.log'
Done

2021-09-03 05:27 UTC, vastradparayya approved these changes

2021-09-03 06:14 UTC, selvakumaar5496 approved these changes

2021-09-06 12:49 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +        #message_bus
Declare LOG_PATH=/var/log and use that down the line. This will help in being ready with future where we need to read the log path from config & use that.
Follow the same at other places in this PR.

2021-09-06 12:50 UTC, sachinpunadikar requested changes
Please work the suggestion

2021-09-07 08:50 UTC, rahul-tripathi-git commented on py-utils/src/setup/utils.py
> +        #message_bus
Done

2021-09-07 11:07 UTC, sachinpunadikar approved these changes
+1

2021-09-07 14:53 UTC, rahul-tripathi-git commented
Manual deployment success link: http://eos-jenkins.mero.colo.seagate.com/job/Cortx-Deployment/job/VM-Deployment-1Node-CentOS-7.9/57/console

2021-09-07 15:30 UTC, merged