Generic Validator framework base implementation.
Seagate/cortx-utils pull request #52
Opened 2020-10-19 17:20 UTC by shrimetta

**Problem Statement**
Generic Validator framework

**Problem Description**
Implement Generic Validator framework.

**Solution Overview**
This is the base implementation of generic validator framework with sample network related validations.
 

Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>

2020-10-20 05:26 UTC, ujjwalpl requested changes

2020-10-20 05:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/error.py
> +class VError(Exception):
Add description to the class. 
"Class representing a generic error with error code and output of a command"

2020-10-20 05:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/error.py
> +
Base class constructor needs to be called. 
        error = "%s: %s" % (self._rc, self._desc)
        super(VError, self).__init__(error)

2020-10-20 05:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/error.py
> +    def __str__(self):
You can remove this as this is in the base class now.

2020-10-20 05:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +            raise VError(errno.EINVAL, "Invalid parameters")
"Invalid parameters %s" %args

2020-10-20 05:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        # TODO write
`#` TODO: This is sample. Need to add actual network validation

2020-10-20 05:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +# Test Network
Please move this test code to cortx-utils/py-utils/test/test_v_network.py Refer to other test files

2020-10-20 05:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/__init__.py
> +# This program is free software: you can redistribute it and/or modify
Add a line before this, e.g. Also remove "CORTX-Py-Utils:"

# CORTX Python common library.
# 
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
# ...

2020-10-20 05:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +        parser1 = parser.add_parser(NetworkVCommand._name, help='Network Validations')
Add a blank line before this line

2020-10-20 05:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/validate.py
> +        parser = argparse.ArgumentParser(description)
""" Obtains the Command after parsing the command line. """

2020-10-20 12:36 UTC, shrimetta commented on py-utils/src/utils/validator/error.py
> +class VError(Exception):
done

2020-10-20 12:36 UTC, shrimetta commented on py-utils/src/utils/validator/error.py
> +
done

2020-10-20 12:37 UTC, shrimetta commented on py-utils/src/utils/validator/error.py
> +    def __str__(self):
done

2020-10-20 12:37 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +            raise VError(errno.EINVAL, "Invalid parameters")
done

2020-10-20 12:37 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +        # TODO write
done

2020-10-20 12:37 UTC, shrimetta commented on py-utils/src/utils/validator/__init__.py
> +# This program is free software: you can redistribute it and/or modify
done

2020-10-20 12:37 UTC, shrimetta commented on py-utils/src/utils/validator/commands.py
> +        parser1 = parser.add_parser(NetworkVCommand._name, help='Network Validations')
done

2020-10-20 12:38 UTC, shrimetta commented on py-utils/src/utils/validator/validate.py
> +        parser = argparse.ArgumentParser(description)
done

2020-10-21 07:49 UTC, ujjwalpl requested changes

2020-10-21 07:49 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_controller.py
> +            result = Pillar.get_pillar(f"storage_enclosure:controller:{controller}:ip")
We should expect the higher levels to pass the input parameters. We should not communicate to salt directly. that is up to the caller. 

```
def validate(self, args):
    if args[0] == "accessibility" 
          self.validate_accessibility(args[1], args[2])

def validate_accessibilty(self, primary_ip, secondary_ip): 
....
```

2020-10-21 07:49 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_consul.py
> +    def validate(self):
We need to write extensible source code, so that you dont have to change the interfaces in future. 

 ```
def validate(self, args):  
     """ Process consul valiations """
     if args[0] == "service": 
        self.validate_service()
     raise VError(..)

def validate_service():
        # Check Consul service
        check_output_log = subprocess.check_output(const.CONSUL_STATUS_CHECK_CMD, shell=True)
....
```

2020-10-21 07:49 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +    def verify_management_vip(self):
Use either "validate" or "verify" consistently.

2020-10-21 07:49 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        res = Pillar.get_pillar("cluster:cluster_ip")
Please remove all the Pillar calls from the code here. It should be higher layers which should obtain the details. This is required to facilitate loose coupling. 

You can move the Pillar code to test to show how to obtain and make use of it.

2020-10-21 07:49 UTC, ujjwalpl commented on py-utils/src/utils/validator/validator_utils.py
> +class Pillar:
Pilar should not be part of the validations. Please remove any code related to Pillar. It can be another utils component for storing information into a generic DB like Pillar. Do not hard code to Pillar.

2020-10-21 07:49 UTC, ujjwalpl commented on py-utils/src/utils/validator/validator_utils.py
> +class NetworkValidations:
Remove this class. There is already a class NetworkV. All the logic should be part of it.

2020-10-21 07:49 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_controller.py
> +            result = NetworkValidations.check_ping(result['response'])
Use NetworkV class for anything related to network.

2020-10-21 07:49 UTC, ujjwalpl commented on py-utils/src/utils/validator/validator_utils.py
> +#!/bin/env python3
Remove this file. This is not required. We do not want to add a place holder like this. It will become a dump yard for all non-OO code.

2020-10-21 15:15 UTC, shrimetta commented on py-utils/src/utils/validator/v_controller.py
> +            result = Pillar.get_pillar(f"storage_enclosure:controller:{controller}:ip")
done

2020-10-21 15:16 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +    def validate(self):
done

2020-10-21 15:16 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +    def verify_management_vip(self):
Using validate. done

2020-10-21 15:16 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +        res = Pillar.get_pillar("cluster:cluster_ip")
done

2020-10-21 15:17 UTC, shrimetta commented on py-utils/src/utils/validator/validator_utils.py
> +class Pillar:
Removed this file as per review comment below.

2020-10-21 15:17 UTC, shrimetta commented on py-utils/src/utils/validator/validator_utils.py
> +class NetworkValidations:
Removed this file as per review comment below.

2020-10-21 15:17 UTC, shrimetta commented on py-utils/src/utils/validator/v_controller.py
> +            result = NetworkValidations.check_ping(result['response'])
done

2020-10-21 15:17 UTC, shrimetta commented on py-utils/src/utils/validator/validator_utils.py
> +#!/bin/env python3
done

2020-10-22 11:29 UTC, ujjwalpl requested changes

2020-10-22 11:29 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_consul.py
> +    def validate_consul_service_status(self, host, port):
Too big and redundant name. Consul is already qualified by the class name
Use "validate_service_status"

2020-10-22 11:29 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +    def validate_management_vip(self, management_vip):
validate_management_vip and validate_cluster_ip and other functions are all same and redundant. 
They can be merged into one interface "validate_ip_connectivity".

2020-10-22 11:29 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        action = args[0]
It would be good to document the args in the function header.  
`     $ validate network connectivity <ip1> <ip2> <ip3> 
`
We dont need to care if that is management or data IP. 

```
def validate(self, args):
    """Process Network Validations"""

    if action == "connectivity": 
        self.validate_ip_connectivity(args[1:])

    raise VError(errno.EINVAL, "Invalid parameter %s" % args)
```

2020-10-22 11:29 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +
Add the command line here
$ validate network connectivity ip1 ip2 ip3...

2020-10-22 11:29 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +
Add the command line here. 
$ validate consul status

2020-10-22 11:29 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        return unreachable_ips
Framework is exception based. So for consistency raise exception from here. No need to return the list. For example check validate_consul_service_status. It doesnt return value but raises exception. 

If you want to return values, that is ok, but then 
1. There must a a reason
2. There must be a consistency (i.e. return values from all the validate_xxx functions)

2020-10-22 11:29 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +class NetworkV:
I dont see test code for NetworkV. I had requested you to move the test code to a test file. Same is the case for consulV.

2020-10-22 11:37 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        res = Pillar.get_pillar("cluster:cluster_ip")
I dont see the code has been moved to test.

2020-10-22 11:38 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +# Test Network
Looks like this is still pending. I do not see file cortx-utils/py-utils/test/test_v_network.py

2020-10-22 14:07 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +class NetworkV:
done

2020-10-22 14:08 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +        return unreachable_ips
done

2020-10-22 14:08 UTC, shrimetta commented on py-utils/src/utils/validator/commands.py
> +
done

2020-10-22 14:08 UTC, shrimetta commented on py-utils/src/utils/validator/commands.py
> +
done

2020-10-22 14:08 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +        action = args[0]
done

2020-10-22 14:08 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +    def validate_management_vip(self, management_vip):
done

2020-10-22 14:09 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +    def validate_consul_service_status(self, host, port):
done

2020-10-22 14:10 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +        res = Pillar.get_pillar("cluster:cluster_ip")
I will update the test files when KVDb logic is merged

2020-10-22 14:11 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +# Test Network
done

2020-10-22 15:06 UTC, ujjwalpl requested changes

2020-10-22 15:06 UTC, ujjwalpl commented on py-utils/src/utils/validator/validate.py
> +            "usage: %s [-h] [network <args>] [consul <args>]\n" % prog)
Need to print detailed usage here.

2020-10-22 15:06 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +            if run_result[2]:
Can SimpleProcess throw exception ? If so, you need to put this in try catch block.

2020-10-22 16:23 UTC, ajaysrivas commented on py-utils/src/utils/validator/v_consul.py
> +    def validate_service_status(self, host, port):
For every validation, the output of executed command should be dumped in a log file. It will be very helpful for the service personnel or debugger to find out the actual problem.
If output is huge, it can be limited by first n lines where n could be 50. It can be made configurable.

2020-10-22 16:23 UTC, ajaysrivas commented on py-utils/src/utils/validator/v_network.py
> +    def validate_ip_connectivity(self, ips):
The validators can be categorized as -
1. Validators using shell commands 
2. Validators using http calls

These validators can have common code to execute the validator and can be used ConsulV, NetworkV and other such classes.

2020-10-22 20:50 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +            if run_result[2]:
SimpleProcess will not throw exception.

2020-10-23 06:12 UTC, ajaysrivas commented
@shrimetta where can I get design document for the feature?

2020-10-23 10:13 UTC, shrimetta commented on py-utils/src/utils/validator/test_consul_validator.py
> +#!/usr/bin/env python3
I had added it to test but during testing it got misplaced. Fixed it now.

2020-10-23 10:13 UTC, shrimetta commented on py-utils/src/utils/validator/test_network_validator.py
> +
I had added it to test but during testing it got misplaced. Fixed it now.

2020-10-23 10:13 UTC, shrimetta commented on py-utils/src/utils/validator/test_network_validator.py
> +                          'connectivity', '11.230.249.110'])
done

2020-10-23 10:13 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +        if args_length == 0:
done

2020-10-23 10:14 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +                raise VError(errno.ECONNREFUSED, "Consul is not running")
done

2020-10-23 10:14 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +        if args_length == 0:
done

2020-10-23 10:14 UTC, shrimetta commented on py-utils/src/utils/validator/validate.py
> +            "usage: %s [-h] [network <args>] [consul <args>]\n" % prog)
done

2020-10-23 10:33 UTC, shrimetta commented
> @shrimetta where can I get design document for the feature?

I don't have it yet. But I will create one and share it accross.

2020-10-23 12:18 UTC, ujjwalpl requested changes

2020-10-23 12:18 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_consul.py
> +        except requests.exceptions.RequestException:
In all the exceptions details about failures must be included. In this case status_code must be included in the exception being returned.

2020-10-23 12:18 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +    def validate_ip_connectivity(self, ips):
There is already an abstractions named SimpleProcess for this. Even for http, we are using request which is enough for now. Hence we will look at it in future if required.

2020-10-23 12:18 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_consul.py
> +            raise VError(errno.ECONNREFUSED,
This should be errno.EINVAL because this relates to input.

2020-10-23 12:21 UTC, ujjwalpl requested changes

2020-10-23 12:21 UTC, ujjwalpl commented on py-utils/test/test_consul_validator.py
> +
Please store this py-utils/test/validator/test_consul_validator.py

2020-10-23 15:14 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +    def validate_service_status(self, host, port):
done

2020-10-23 15:15 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +            raise VError(errno.ECONNREFUSED,
fixed

2020-10-23 15:15 UTC, shrimetta commented on py-utils/test/test_consul_validator.py
> +
moved

2020-10-23 15:16 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +        except requests.exceptions.RequestException:
done

2020-10-23 18:05 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_consul.py
> +                             f"Error connecting to consul service on {host}:{port} with status code {response_status_code}.")
This is grammatically incorrect sentence. 

f"Error {response_status_code} obtained while connecting to consul service on {host}:{port}."

2020-10-23 18:05 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_consul.py
> +            response_status_code = requests.get(url).status_code
Please use status_code or response_code.

2020-10-24 10:03 UTC, ujjwalpl requested changes

2020-10-24 10:03 UTC, ujjwalpl commented on py-utils/test/validator/test_consul_validator.py
> +
Add following so that someone can run the tests

```
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))
```

2020-10-24 10:03 UTC, ujjwalpl commented on py-utils/test/validator/test_network_validator.py
> +
Add following so that someone can run the tests

```
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))
```

2020-10-24 10:03 UTC, ujjwalpl commented on py-utils/test/validator/test_network_validator.py
> +    unittest.main()
I tried to run this test and it hanged. Please ensure that code is tested.

2020-10-24 20:43 UTC, shrimetta commented on py-utils/test/validator/test_network_validator.py
> +    unittest.main()
I tested it. It takes 20 secs to complete as it retries to connect to ips.

![network_test](https://user-images.githubusercontent.com/66473115/97093194-98724400-1667-11eb-83c0-a4cdce25fb5f.PNG)

2020-10-25 07:50 UTC, shrimetta commented on py-utils/test/validator/test_network_validator.py
> +
done

2020-10-25 07:51 UTC, shrimetta commented on py-utils/test/validator/test_consul_validator.py
> +
done

2020-10-25 07:51 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +            response_status_code = requests.get(url).status_code
done

2020-10-25 07:51 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +                             f"Error connecting to consul service on {host}:{port} with status code {response_status_code}.")
done

2020-10-26 11:30 UTC, ujjwalpl commented on py-utils/test/validator/test_network_validator.py
> +    unittest.main()
This is not practical. We need to conclude this in not more than 1 sec.

2020-10-26 12:50 UTC, ujjwalpl requested changes

2020-10-26 12:50 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +            cmd = f"ping -c 1 {ip}"
If you assume that inputs are ip, then you must validate that its an ip address. If you allow host name as well, then you must change the interface name to validate_host_connectivity(self, host_addr):

```
for ip in ips:
      if ip.count(".") == 3 and all(self._is_valid_ipv4(i) for i in ip.split(".")):
      ....

def _is_valid_ipv4(s):
    try: 
         return str(int(s)) == s and 0 <= int(s) <= 255
    except: 
         return False
```

2020-10-26 12:50 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +            cmd = f"ping -c 1 {ip}"
ping command needs to change to
`cmd = f"ping -c 1 -W 1 {ip}"`

2020-10-26 12:50 UTC, ujjwalpl commented on py-utils/test/validator/test_network_validator.py
> +    unittest.main()
Please change the ip command to `ping -c 1 -W 1 {ip}`

2020-10-27 10:04 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_consul.py
> +                             f"Error {status_code} obtained while connecting to consul service on {host}:{port}.")
Please follow consistent indentation and try not to exceed 80 odd chars per line. Example....

```
raise VError(
    errno.ECOMM, f"Error {status_code} obtained while connecting to \
    consul service on {host}:{port}.")
```

2020-10-27 12:26 UTC, shrimetta commented on py-utils/src/utils/validator/v_consul.py
> +                             f"Error {status_code} obtained while connecting to consul service on {host}:{port}.")
done

2020-10-27 12:26 UTC, shrimetta commented on py-utils/src/utils/validator/v_network.py
> +            if ip.count(".") == 3 and all(self._is_valid_ipv4_part(ip_part) for ip_part in ip.split(".")):
done

2020-10-27 12:59 UTC, ujjwalpl approved these changes

2020-10-27 13:50 UTC, ajaysrivas approved these changes

2020-10-27 14:32 UTC, sachinpunadikar approved these changes
+1

2020-10-27 14:33 UTC, merged

2020-10-28 09:12 UTC, knekrasov reviewed
As a developer, I don't understand how this framework is supposed to be used, in which circumstances and what problems of the end developer it solves.

2020-10-28 09:12 UTC, knekrasov commented on py-utils/src/utils/validator/validate.py
> +class ValidatorCommandFactory:
Why do you need the factory if commands use static methods?

2020-10-28 09:12 UTC, knekrasov commented on py-utils/src/utils/validator/validate.py
> +        ValidatorCommandFactory.usage(argv[0])
Why command factory is responsible for usage of CLI? Doesn't it violate single responsibility principle? Moreover, it violates encapsulation (why can't one use the factory in non-CLI environment?).

2020-10-28 09:12 UTC, knekrasov commented on py-utils/src/utils/validator/validate.py
> +        return errno.EINVAL
So VError class has error codes put quite carefully. But when an exception occurs, the application exits with EINVAL always. Is that correct?