Merge Generic DB framework  changes for OpenLdap to Kubernetes branch
Seagate/cortx-utils pull request #526
Opened 2021-09-16 09:48 UTC by udayan-y21

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-09-16 13:53 UTC, sachinpunadikar commented on py-utils/src/utils/data/db/examples/openldap/cortxuser_model.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
correct the copyright year

2021-09-17 11:50 UTC, udayan-y21 commented on py-utils/src/utils/data/db/examples/openldap/cortxuser_model.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Modifications done.

2021-09-20 10:45 UTC, sachinpunadikar commented on py-utils/src/utils/data/db/examples/openldap/cortxuser_model.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-09-20 10:45 UTC, sachinpunadikar commented on py-utils/src/utils/data/db/examples/openldap/openldap_storage.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-09-20 10:46 UTC, sachinpunadikar commented on py-utils/src/utils/data/db/openldap/__init__.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 -> 2021

2021-09-20 10:47 UTC, sachinpunadikar commented on py-utils/src/utils/data/db/openldap/storage.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
2020 ->2021

2021-09-20 10:49 UTC, sachinpunadikar requested changes
Please work on comments.
Add copyright text to empty files

2021-09-20 17:34 UTC, sachinpunadikar approved these changes
+1

2021-09-20 17:35 UTC, merged