EOS-24934: package validation restored in post_install phases
Seagate/cortx-utils pull request #532
Opened 2021-09-16 17:56 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

# Problem Statement
- Python packages should be validated in post_install

# Design
-  The validation of correct python packages should be restored in both, utils rpm post_install as well as utils mini-prov post_install phase

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-09-16 18:04 UTC, sachinpunadikar commented on jenkins/build.sh
> +     pip3 freeze | grep \$package > /dev/null
Per my observation, this command needs an update. Refer to the code from main branch

2021-09-16 18:05 UTC, sachinpunadikar requested changes
work on the comment

2021-09-16 18:12 UTC, rahul-tripathi-git commented on jenkins/build.sh
> +     pip3 freeze | grep \$package > /dev/null
Updated.

2021-09-17 06:19 UTC, sachinpunadikar approved these changes
+1

2021-09-17 13:06 UTC, suryakumar1024 approved these changes

2021-09-17 13:13 UTC, vastradparayya approved these changes

2021-09-17 13:21 UTC, veerendra-simha-garikipati approved these changes

2021-09-17 13:38 UTC, merged