EOS-24947: log dir needs to be updated with pod_id(machine_id)
Seagate/cortx-utils pull request #536
Opened 2021-09-24 11:19 UTC by suryakumar1024

# Problem Statement
Log files should be created inside a separate directory for all the pods.

In the k8s environment, pod_id will be machine_id. We need to add a directory named, {machine_id} inside every component log location

Created a generic method inside common module that should return log dir path till machine_id-> /var/log/cortx/utils/{machine_id}

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-09-27 11:35 UTC, selvakumaar5496 commented on py-utils/src/utils/common/common.py
> +    def load_config() -> None:
make this function internal

2021-09-27 11:36 UTC, selvakumaar5496 commented on py-utils/src/utils/common/common.py
> +class CortxConf:
Store index in a variable

2021-09-28 06:40 UTC, suryakumar1024 commented on py-utils/src/utils/common/common.py
> +    def load_config() -> None:
updated in recent patch

2021-09-28 06:40 UTC, suryakumar1024 commented on py-utils/src/utils/common/common.py
> +class CortxConf:
Updated in recent patch

2021-09-28 08:17 UTC, ujjwalpl requested changes

2021-09-28 08:17 UTC, ujjwalpl commented on py-utils/src/utils/common/common.py
> +        Get the log path with machine-id/ pod-id as sub directory
Please avoid using pod or any k8s construct in the code.

2021-09-28 14:15 UTC, suryakumar1024 commented on py-utils/src/utils/common/common.py
> +        Get the log path with machine-id/ pod-id as sub directory
Updated comment in the recent patch

2021-09-28 14:19 UTC, ujjwalpl approved these changes

2021-09-28 17:20 UTC, selvakumaar5496 commented on py-utils/src/utils/common/common.py
> +        return Conf.save(CortxConf._index)
Does save return anything ?

2021-09-28 17:24 UTC, selvakumaar5496 commented on py-utils/src/utils/common/common.py
> +    def get_key(key: str, default_val: str = None, **filters):
I think this interface should be renamed as get_value

2021-09-29 13:04 UTC, suryakumar1024 commented on py-utils/src/utils/common/common.py
> +        return Conf.save(CortxConf._index)
Updated in recent patch

2021-09-29 13:06 UTC, suryakumar1024 commented on py-utils/src/utils/common/common.py
> +    def get_key(key: str, default_val: str = None, **filters):
@selvakumaar5496 but it given a purposeful meaning if we call it as get_key/ set_key as we are setting/ getting a key into a conf store.

2021-09-29 14:07 UTC, suryakumar1024 commented on py-utils/src/utils/common/common.py
> +    def get_key(key: str, default_val: str = None, **filters):
As discussed i updated the method name to get and set

2021-09-30 07:59 UTC, selvakumaar5496 approved these changes

2021-09-30 08:19 UTC, sachinpunadikar approved these changes
+1

2021-09-30 08:20 UTC, merged