Utils proper return code
Seagate/cortx-utils pull request #548
Opened 2021-10-01 09:40 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-10-01 10:29 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +        rc = 0
err = None should be added

2021-10-01 10:29 UTC, sachinpunadikar requested changes
A small change reqd

2021-10-01 11:22 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +            if ret_code != 0:
make rc =-1 inside the if block

2021-10-01 11:23 UTC, sachinpunadikar commented on py-utils/src/setup/utils_setup.py
> +        rc, err = command.process()
remove err

2021-10-04 04:39 UTC, selvakumaar5496 commented
Closing this as it is not required anymore

2021-10-04 04:39 UTC, closed without merging

2021-12-06 13:00 UTC, rahul-tripathi-git commented
> Closing this as it is not required anymore

what was the alternate to rhis?