EOS-25313: SSL certificate generation check-in
Seagate/cortx-utils pull request #578
Opened 2021-10-11 11:12 UTC by rohitkolapkar

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-10-14 03:45 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +    def generate_private_key():
Remove static methods wherever

2021-10-14 03:46 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +    def generate_ssl_certificate(private_key:rsa.RSAPrivateKeyWithSerialization, dns_list:list,
generate_ssl_certificate -> prepare_ssl_certificate

2021-10-14 03:46 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +            x509.NameAttribute(NameOID.COUNTRY_NAME, u"IN"),
do not use hardcoded values

2021-10-14 03:55 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +            os.makedirs(directory, exist_ok=True)
Add error handling

2021-10-14 03:57 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +    def ensure_dir(file_path):
ensure_dir --> make_dir

2021-10-18 12:49 UTC, rohitkolapkar commented on py-utils/src/utils/security/ssl_cert.py
> +    def generate_private_key():
done

2021-10-18 12:49 UTC, rohitkolapkar commented on py-utils/src/utils/security/ssl_cert.py
> +            x509.NameAttribute(NameOID.COUNTRY_NAME, u"IN"),
done

2021-10-18 12:49 UTC, rohitkolapkar commented on py-utils/src/utils/security/ssl_cert.py
> +    def ensure_dir(file_path):
done

2021-10-18 12:49 UTC, rohitkolapkar commented on py-utils/src/utils/security/ssl_cert.py
> +    def dump_ssl_cert_key(dump_cert_path:str, dns_list:list, expiry_days:int = 3650):
done

2021-10-18 15:03 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/certificate.py
> +        return cert[cert_type]
Change return cert[cert_type] --> return cert[cert_type]()

2021-10-18 15:04 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/certificate.py
> +    def __init__(self, cert_path, dns_list, expiry_days = 3650, **ssl_cert_configs):
Accept the parameters in generate function not in __init__

2021-10-18 18:20 UTC, pawankumarsrivastava requested changes

2021-10-18 18:20 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/certificate.py
> +            raise SSLCertificateError(f"Unexpected error occured: {e}")
Spell check "occured"

2021-10-19 03:16 UTC, rohitkolapkar commented on py-utils/src/utils/security/certificate.py
> +            raise SSLCertificateError(f"Unexpected error occured: {e}")
done

2021-10-19 03:16 UTC, rohitkolapkar commented on py-utils/src/utils/security/certificate.py
> +    def __init__(self, cert_path, dns_list, expiry_days = 3650, **ssl_cert_configs):
done

2021-10-19 03:16 UTC, rohitkolapkar commented on py-utils/src/utils/security/certificate.py
> +        return cert[cert_type]
done

2021-10-19 03:16 UTC, rohitkolapkar commented on py-utils/src/utils/security/certificate.py
> +    def factory(cert_type):
done

2021-10-19 03:45 UTC, rohitkolapkar commented
Added an example for how to use Certificate class.
@pawankumarsrivastava

2021-10-19 04:12 UTC, soniyamoholkar approved these changes

2021-10-19 04:54 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +    def generate_private_key():
This can be resolved now.

2021-10-19 04:54 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +            x509.NameAttribute(NameOID.COUNTRY_NAME, u"IN"),
This can be resolved now.

2021-10-19 04:54 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +            os.makedirs(directory, exist_ok=True)
This can be resolved now.

2021-10-19 04:55 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +    def ensure_dir(file_path):
This can be resolved now.

2021-10-19 04:55 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/ssl_cert.py
> +    def dump_ssl_cert_key(dump_cert_path:str, dns_list:list, expiry_days:int = 3650):
This can be resolved now.

2021-10-19 04:55 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/certificate.py
> +        return cert[cert_type]
This can be resolved now.

2021-10-19 04:55 UTC, pawankumarsrivastava commented on py-utils/src/utils/security/certificate.py
> +            raise SSLCertificateError(f"Unexpected error occured: {e}")
This can be resolved now.

2021-10-19 08:56 UTC, merged