EOS-14529: Appliance information - Read Unique ID from file to Display
Seagate/cortx-utils pull request #59
Opened 2020-10-26 20:06 UTC by pawankumarsrivastava

2020-10-27 08:36 UTC, cdeshmukh requested changes

2020-10-27 08:36 UTC, cdeshmukh commented on py-utils/src/utils/appliance_info/appliance.py
> +    def _get(self, key, data):
_getval() would suit better i feel.

Also do you see the need to keep this private call, any other function may need this functionality in future ? If yes, then ok to keep it separate

2020-10-27 08:36 UTC, cdeshmukh commented on py-utils/src/utils/appliance_info/appliance.py
> +                ret = self._data
this is what will get used effectively in LDR R1, so keep this as first condition

2020-10-27 08:36 UTC, cdeshmukh commented on py-utils/src/utils/appliance_info/appliance.py
> +    def _set(self, key, val, data):
_setval() plz

2020-10-27 08:36 UTC, cdeshmukh commented on py-utils/src/utils/appliance_info/appliance.py
> +    def set(self, key, value):
as discussed, dont expose this. keep it private
_set()

2020-10-27 08:36 UTC, cdeshmukh commented on py-utils/src/utils/appliance_info/appliance.py
> +            data[new_key[0]] = val
this will just set in memory, not updating in file. But again, we dont need this in LDR r1

2020-10-27 14:21 UTC, navalkp commented on py-utils/setup.py
> +                'cortx.utils.appliance_info', 'cortx.utils.appliance_info.appliance'
You cannot specify file here, only folders are required, 2nd entry is file, remove it

2020-10-27 19:04 UTC, pawankumarsrivastava commented on py-utils/src/utils/appliance_info/appliance.py
> +    def _get(self, key, data):
Changed _get -> _getval.

Since I have made _getval as recursive function so just kept it separate for better readability.

2020-10-27 19:04 UTC, pawankumarsrivastava commented on py-utils/src/utils/appliance_info/appliance.py
> +                ret = self._data
Done.

2020-10-27 19:05 UTC, pawankumarsrivastava commented on py-utils/src/utils/appliance_info/appliance.py
> +    def _set(self, key, val, data):
Done

2020-10-27 19:05 UTC, pawankumarsrivastava commented on py-utils/src/utils/appliance_info/appliance.py
> +    def set(self, key, value):
Done

2020-10-27 19:06 UTC, pawankumarsrivastava commented on py-utils/src/utils/appliance_info/appliance.py
> +            data[new_key[0]] = val
Only CSM is using this class and is not using set method. I have written the code so that it can be used later after LDR r1

2020-10-27 19:07 UTC, pawankumarsrivastava commented on py-utils/setup.py
> +                'cortx.utils.appliance_info', 'cortx.utils.appliance_info.appliance'
Done

2020-10-28 08:11 UTC, navalkp approved these changes

2020-10-29 06:06 UTC, cdeshmukh commented
Pending comments are for future usage, current implementation looks fine

2020-10-29 06:50 UTC, cdeshmukh commented on py-utils/src/utils/const.py
> +ITEMS_SEPARATOR = ", "
delimiter should just be ',', any space may or may not be there and needs to be stripped off while reading

2020-10-29 07:28 UTC, sachinpunadikar approved these changes
+1

2020-10-29 07:42 UTC, merged