EOS-25744: Merged message bus and iem conf into single utils conf file utils.conf
Seagate/cortx-utils pull request #608
Opened 2021-11-08 06:40 UTC by suryakumar1024

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
- We need to move away from messagebus.conf and iem.conf and merge them both into a single file, utils.conf.

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-11-08 10:15 UTC, rohit-k-dwivedi commented on py-utils/src/setup/utils.py
> +                     message_server_list[i])
using enumerate instead of range(len(iterator)) can be useful when you need both index and value
```
        for index, server in enumerate(message_server_list, start=0):
            Conf.set(utils_index, f'message_broker>cluster[{index}]>server', server)
```

2021-11-08 11:28 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +        message_bus_conf = os.path.join(local_storage ,'utils/conf/utils.conf')
lets change the variable also to utils.conf

2021-11-08 11:28 UTC, selvakumaar5496 commented on py-utils/src/utils/iem_framework/event_message.py
> +        iem_conf = os.path.join(local_storage, 'utils/conf/utils.conf')
lets change the variable also to utils.conf

2021-11-08 11:33 UTC, selvakumaar5496 commented on py-utils/src/setup/utils.py
> +        utils_index = 'utils_ind'
Please add the multiline comments

2021-11-08 11:36 UTC, selvakumaar5496 requested changes
Please work on the comments

2021-11-10 05:13 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus.py
> +        message_bus_conf = os.path.join(local_storage ,'utils/conf/utils.conf')
Updated in recent patch.

2021-11-10 05:13 UTC, suryakumar1024 commented on py-utils/src/utils/iem_framework/event_message.py
> +        iem_conf = os.path.join(local_storage, 'utils/conf/utils.conf')
Updated in recent patch.

2021-11-10 05:13 UTC, suryakumar1024 commented on py-utils/src/setup/utils.py
> +        utils_index = 'utils_ind'
Updated in recent patch.

2021-11-10 05:17 UTC, suryakumar1024 commented on py-utils/src/setup/utils.py
> +                     message_server_list[i])
Yes, nice to have that way also. Hope the existing code servers have the same purpose in a different way.

2021-11-10 05:40 UTC, selvakumaar5496 approved these changes

2021-11-10 06:50 UTC, rohit-k-dwivedi approved these changes

2021-11-10 06:58 UTC, sachinpunadikar approved these changes
+1

2021-11-10 07:02 UTC, merged