WIP: MessageBus read passed in config values
Seagate/cortx-utils pull request #610
Opened 2021-11-10 19:19 UTC by selvakumaar5496

Signed-off-by: Selvakumar <selva.k.nambi@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-11-11 13:04 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus.py
> +            self._broker_conf = Conf.get('utils_index', 'message_broker')
this is 'utils_ind' - refer Surya's PR

2021-11-11 13:11 UTC, sachinpunadikar requested changes
work on the comment

2021-11-11 14:39 UTC, suryakumar1024 requested changes
Changing signature in MessageBus requires code changes in mini-provisioning stages also. kindly fix below issue

# /opt/seagate/cortx/utils/bin/utils_setup init --config yaml:///etc/cortx/cluster.conf
error: __init__() got an unexpected keyword argument 'cluster_conf'

Traceback (most recent call last):
  File "/opt/seagate/cortx/utils/bin/utils_setup", line 258, in main
    rc = command.process()
  File "/opt/seagate/cortx/utils/bin/utils_setup", line 136, in process
    rc = Utils.init(self.config_path)
  File "/usr/lib/python3.6/site-packages/cortx/setup/utils.py", line 218, in init
    admin = MessageBusAdmin(admin_id='register', cluster_conf=config_path)
TypeError: __init__() got an unexpected keyword argument 'cluster_conf'

2021-11-11 14:52 UTC, suryakumar1024 commented
@selvakumaar5496 
Add below code to utils init phase

local_storage = CortxConf.get_storage_path('local')
utils_conf = os.path.join(local_storage, 'utils/conf/utils.conf')
utils_conf = f'json://{utils_conf}'
Conf.load('utils_ind', utils_conf, skip_reload=True)
config_params = {}
config_params['node'] = Conf._conf.get('utils_ind', 'node')
config_params['message_broker'] = Conf._conf.get('utils_ind', 'message_broker')
MessageBus.init(config_params)

2021-11-12 05:44 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +            self._broker_conf = Conf.get('utils_index', 'message_broker')
done

2021-11-12 08:19 UTC, suryakumar1024 approved these changes
Good to merge

2021-11-16 16:46 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus.py
> +            raise MessageBusError(errno.EINVAL, "Config is not loaded")
This will force receive/ MessageBus consumer __init__ to call messagebus init(). Is that right one?

2021-11-25 06:47 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +            raise MessageBusError(errno.EINVAL, "Config is not loaded")
Yes

2021-12-06 17:39 UTC, sachinpunadikar approved these changes
+1

2021-12-07 11:15 UTC, merged