EOS-26043: Implement Expiration time filter for messages for a particular topic
Seagate/cortx-utils pull request #621
Opened 2021-11-22 09:40 UTC by suryakumar1024

# Problem Statement
- A message type should have an expiration time, such that if a message was not read within the expiration time, it should get removed from message bus.
- mb_admin.set_message_type_expire('message_type', time_to_expire_in_milli_sec)

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-11-23 05:37 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-11-24 03:53 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +        self._broker.set_message_type_expire(client_id,message_type, \
provide space after comma

2021-11-24 03:58 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            raise MessageBusError(errno.ENOENT, "Unknow topic: Could not"+\
Correction needed Unknow -> Unknown

2021-11-24 03:58 UTC, selvakumaar5496 requested changes
Please work on the comments.

2021-11-24 03:58 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def set_message_type_expire(self, message_type, expire_time: int):
specify type of message_type also

2021-11-24 03:58 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            " found the topic %s in topic list %s", message_type, \
indent to 4 table spaces

2021-11-24 03:58 UTC, selvakumaar5496 commented on py-utils/test/message_bus/test_message_bus.py
> +        """Test set message type expiry"""
providing a period symbol will remove this codacy issue. Refer to other testcases

2021-11-24 03:58 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            " found the topic %s in topic list %s", message_type, \
found -> find

2021-11-24 04:01 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        if message_type not in message_type_list:
Do we need this validation here? We usually dont have any validation in client code.
We shall do the same in KafkaMessageBroker class. 
Please confirm @sachinpunadikar

2021-11-24 04:02 UTC, sachinpunadikar commented on py-utils/test/message_bus/test_message_bus.py
> +        message = TestMessageBus._consumer.receive()
In test code, one should wait for the expiry time to exceed & try to read the message. Should not get the message, also 1 more test case needed where one reads the message before expiry time.

2021-11-24 05:34 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus.py
> +        self._broker.set_message_type_expire(client_id,message_type, \
Updated in recent patch

2021-11-24 05:34 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            raise MessageBusError(errno.ENOENT, "Unknow topic: Could not"+\
Updated in recent patch

2021-11-24 05:34 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +    def set_message_type_expire(self, message_type, expire_time: int):
Updated in recent patch

2021-11-24 05:35 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            " found the topic %s in topic list %s", message_type, \
Updated in recent patch

2021-11-24 05:35 UTC, suryakumar1024 commented on py-utils/test/message_bus/test_message_bus.py
> +        """Test set message type expiry"""
Updated in recent patch

2021-11-24 05:35 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +            " found the topic %s in topic list %s", message_type, \
Updated in recent patch

2021-11-30 03:51 UTC, rahul-tripathi-git commented on py-utils/test/message_bus/test_message_bus.py
> +        """Test set message type expiry"""
looks like your changes are not update here, please check.

2021-11-30 11:29 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus.py
> +            expire_time)
Make this as a single line comment and provide a period symbol(.)

2021-11-30 11:41 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        if message_type not in message_type_list:
I agree, lets move it to appropriate place.

2021-11-30 15:25 UTC, suryakumar1024 commented on py-utils/test/message_bus/test_message_bus.py
> +        """Test set message type expiry"""
updated in recent patch

2021-11-30 15:25 UTC, suryakumar1024 commented on py-utils/test/message_bus/test_message_bus.py
> +        message = TestMessageBus._consumer.receive()
added in recent patch

2021-11-30 15:29 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        return 0
do we need this return statement ?

2021-11-30 15:29 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus.py
> +            expire_time)
Updated in recent patch

2021-11-30 15:33 UTC, sachinpunadikar commented on py-utils/test/message_bus/test_message_bus.py
> +    def test_015_message_type_read_before_expiry(self):
Update the test case name. Here you are trying to read after expiry of messages
test_015_message_type_read_before_expiry -> test_015_message_type_read_after_expiry

2021-11-30 15:36 UTC, suryakumar1024 commented on py-utils/test/message_bus/test_message_bus.py
> +    def test_015_message_type_read_before_expiry(self):
Updated in recent patch

2021-11-30 15:39 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus.py
> +        """
make this comment as single line

2021-11-30 15:39 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus.py
> +        self._broker.set_message_type_expire(client_id, message_type, \
check the return value here

2021-11-30 16:05 UTC, suryakumar1024 commented on py-utils/test/message_bus/test_message_bus.py
> +        """
Updated in a recent patch.

2021-11-30 16:05 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus.py
> +        self._broker.set_message_type_expire(client_id, message_type, \
Updated in a recent patch.

2021-11-30 16:05 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus.py
> +        """
Updated in a recent patch.

2021-11-30 16:07 UTC, sachinpunadikar approved these changes
+1

2021-11-30 16:08 UTC, selvakumaar5496 approved these changes

2021-11-30 16:14 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-11-30 16:15 UTC, merged