Add SupportBundle Filter Interfaces.
Seagate/cortx-utils pull request #625
Opened 2021-11-24 12:09 UTC by gargpalak048

# Problem Statement
- Provide interfaces for filters in SB Framework for components to use.

# Design
-  Added a class FiletrSupportBundle under SB Framework to mock filter interfaces

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-11-25 04:06 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/sb_filters.py
> +    def limit_size(src_dir, file_name_reg_ex, size, dest_dir):
Copy the input file to the dest_dir as it is

2021-11-25 04:06 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/sb_filters.py
> +    def limit_time(start_time_and_duration, src_dir, file_name_reg_ex, dest_dir):
Copy the input file to the dest_dir as it is

2021-11-25 04:07 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/sb_filters.py
> +        return msg
Log this message in SB log file, do not return it.

2021-11-25 04:07 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/sb_filters.py
> +        return msg
Log this message in SB log file, do not return it.

2021-11-25 04:07 UTC, sachinpunadikar requested changes
work on comments

2021-11-25 06:06 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/sb_filters.py
> +    def limit_size(src_dir, file_name_reg_ex, size, dest_dir):
Addressed

2021-11-25 06:06 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/sb_filters.py
> +    def limit_time(start_time_and_duration, src_dir, file_name_reg_ex, dest_dir):
Addressed

2021-11-25 06:07 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/sb_filters.py
> +        return msg
removed the return statement

2021-11-25 06:07 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/sb_filters.py
> +        return msg
removed the return statement

2021-11-26 04:54 UTC, sachinpunadikar approved these changes
+1

2021-11-26 06:27 UTC, cdeshmukh commented on py-utils/src/utils/support_framework/sb_filters.py
> +class FilterLog:
i think 'Logs' can be the class name, filters are of member functions acting on those logs

2021-11-26 06:51 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/sb_filters.py
> +#!/usr/bin/env python3
file name -> log_filters.py

2021-11-26 06:53 UTC, sachinpunadikar commented on py-utils/src/utils/support_framework/sb_filters.py
> +class FilterLog:
In my opinion the current class-name is correct as we are handing filtering only. 
"Logs" may indicate we are handing everything related to logs, so current name is good.

2021-11-26 06:58 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/sb_filters.py
> +#!/usr/bin/env python3
done.

2021-11-26 07:41 UTC, rahul-tripathi-git requested changes
Please refer: https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/749076684/Node+level+Support+Bundle+Collection#Future-implementations-(PI-5)
and make the needed changes.

2021-11-26 07:42 UTC, cdeshmukh commented on py-utils/src/utils/support_framework/sb_filters.py
> +class FilterLog:
> "Logs" may indicate we are handing everything related to logs,

Not necessarily right, we will publish what is supported for class or even code can be checked.
Ideally class name needs to be noun, and any action on it as member functions.

2021-11-26 07:43 UTC, cdeshmukh commented on py-utils/src/utils/support_framework/sb_filters.py
> +class FilterLog:
anyways, in interest of mock interfaces availability, am to merge this PR and address class name during actual implementation

2021-11-26 07:43 UTC, cdeshmukh approved these changes

2021-11-26 08:19 UTC, gargpalak048 commented
> Please refer: https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/749076684/Node+level+Support+Bundle+Collection#Future-implementations-(PI-5) and make the needed changes.

Changed the sequence of args for filter interfaces.

2021-11-29 07:36 UTC, rahul-tripathi-git approved these changes

2021-11-29 07:45 UTC, rahul-tripathi-git commented on py-utils/src/utils/support_framework/sb_filters.py
> +class FilterLog:
Resolving this conversation.

2021-11-29 09:12 UTC, merged