Problem: Cortx-py-utils package does not install python depedencies
Seagate/cortx-utils pull request #63
Opened 2020-10-29 05:42 UTC by mssawant

Even installing cortx-py-utils python dependencies using pip during rpm installation fails
due to some packages requiring development environments to build.
For example, yarl
```
    writing manifest file 'yarl.egg-info/SOURCES.txt'
    copying yarl/__init__.pyi -> build/lib.linux-x86_64-3.6/yarl
    copying yarl/_quoting_c.c -> build/lib.linux-x86_64-3.6/yarl
    copying yarl/_quoting_c.pyi -> build/lib.linux-x86_64-3.6/yarl
    copying yarl/_quoting_c.pyx -> build/lib.linux-x86_64-3.6/yarl
    copying yarl/py.typed -> build/lib.linux-x86_64-3.6/yarl
    running build_ext
    building 'yarl._quoting_c' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/yarl
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstacong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/prl/_quoting_c.c -o build/temp.linux-x86_64-3.6/yarl/_quoting_c.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xbsfsfw6/yarl/setup.py';f=getattr(to open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmrecord/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-xbsfsf
warning: %post(cortx-py-utils-1.0.0-27_955e5de.noarch) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package cortx-py-utils-1.0.0-27_955e5de.noarch
Cannot uninstall requirement aiohttp, not installed
error: %preun(cortx-py-utils-1.0.0-26_d78a85c.noarch) scriptlet failed, exit status 1
Error in PREUN scriptlet in rpm package cortx-py-utils-1.0.0-26_d78a85c.noarch
```
This leads to installation failure.

Solutions:
To avoid such situations, it is better to include the dependencies as part of the cortx-py-utils package
itself.
- Added Makefile and specs file to facilitate rpm building to include the required dependent packages.

2020-10-29 06:32 UTC, ajay-paratmandali commented on py-utils/Makefile
> +# Licensed under the Apache License, Version 2.0 (the "License");
@mssawant can you please update
https://github.com/Seagate/cortx-utils/blob/main/py-utils/README.md
also as it will change step of creating rpm.

2020-10-29 07:31 UTC, ajaysrivas requested changes

2020-10-29 07:31 UTC, ajaysrivas commented on py-utils/Makefile
> +	@echo '  build          - build binary components (hax)'
hax ?

2020-10-29 07:31 UTC, ajaysrivas commented on py-utils/Makefile
> +PY_SRC_FILES := py-utils/setup.py py-utils/src/*.py py-utils/src/utils/*.py py-utils/src/utils/amqp/*.py \
Is it possible to use shell command to get the desired files otherwise for every module we have to change makefile?

2020-10-29 07:34 UTC, ajaysrivas commented
@mssawant we need to inform other components (provisioner, sspl, csm, ha, probably S3) that packaging for py-utils is being changed and provide custom rpm to every component to do the sanity testing. This PR should be merged after that.

2020-10-29 12:48 UTC, mssawant commented on py-utils/Makefile
> +	@echo '  build          - build binary components (hax)'
typo, removing it.

2020-10-29 12:54 UTC, mssawant commented
>we need to inform other components (provisioner, sspl, csm, ha, probably S3) that packaging for py-utils is being changed and provide custom rpm to every component to do the sanity testing. This PR should be merged after that.

@ajaysrivas, makes sense, although other components should not be affected we still need to test it thoroughly. I think instead of giving custom rpms to everyone if we know how the sanity testing for the components is done or someone who knows (may be from QA) would reduce the time overall. what do you think?

2020-10-29 12:58 UTC, mssawant commented on py-utils/Makefile
> +PY_SRC_FILES := py-utils/setup.py py-utils/src/*.py py-utils/src/utils/*.py py-utils/src/utils/amqp/*.py \
Yeah that was on my mind. We are using globs per module, but let me see if we can simplify this.

2020-10-29 23:46 UTC, mssawant commented on py-utils/Makefile
> +# Licensed under the Apache License, Version 2.0 (the "License");
Yes.

2020-10-29 23:46 UTC, mssawant commented on py-utils/Makefile
> +	@echo '  build          - build binary components (hax)'
fixed.

2020-10-29 23:46 UTC, mssawant commented on py-utils/Makefile
> +PY_SRC_FILES := py-utils/setup.py py-utils/src/*.py py-utils/src/utils/*.py py-utils/src/utils/amqp/*.py \
fixed.

2020-10-30 00:05 UTC, mssawant commented
Instead of links I have updated the PYTHONPATH env variable because links may lead to conflicts. Another way is to install the `/opt/seagate/cortx/utils/lib and lib64` to `/usr/lib`  tried this as well, which I find better but during installation there can be conflicts with already existing installations of the same packages. These conflicts an be still be overridden using `--force` flag during rpm installation which seems a bit overkill. So I think using PYTHONPATH env variable will have minimal impact else all the users need to use the `/opt/seagate/cortx/utils/lib` path in their python scripts.
cc @prathameshrodi , @ajaysrivas

2020-10-30 03:41 UTC, mssawant commented on py-utils/Makefile
> +# Licensed under the Apache License, Version 2.0 (the "License");
Done.

2020-10-31 06:39 UTC, ajaysrivas commented on py-utils/Makefile
> +UTILS_SRC := $(shell find . -type f -regex ".*\.py")
Is this going to include test directory? I think we should exclude tests.

2020-10-31 07:19 UTC, mssawant commented on py-utils/Makefile
> +UTILS_SRC := $(shell find . -type f -regex ".*\.py")
We build tests but do not install it,
```
[root@sm6-r23 ~]# ls /opt/seagate/cortx/utils/
bin/         conf/        lib/         lib64/       LICENSE.txt  share/
[root@sm6-r23 ~]# ls /opt/seagate/cortx/utils/bin
chardetect  easy_install  easy_install-3.6  hac  wheel
[root@sm6-r23 ~]# ls /opt/seagate/cortx/utils/conf
requirements.txt
[root@sm6-r23 ~]# ls /opt/seagate/cortx/utils/lib
python3.6
[root@sm6-r23 ~]# ls /opt/seagate/cortx/utils/lib64
python3.6
[root@sm6-r23 ~]# ls /opt/seagate/cortx/utils/share
doc
```

2020-11-02 04:12 UTC, ajay-paratmandali commented
@mssawant 

can you please update README.md
i tried README and not able to create rpm.

Prerequisite for build package missing

I got

```
--> Building rpm packages
error: Failed build dependencies:
        binutils-devel is needed by cortx-py-utils-1.0.0-1_git5eb79ce.el7.x86_64
make[1]: *** [__rpm] Error 1
make[1]: Leaving directory `/home/708945/src/Repos/rough/cortx-utils/py-utils'
make: *** [rpm] Error 2
```
**binutils-devel this package missing in README**

I installed package
but facing
```
Error: Command '['/root/rpmbuild/BUILD/cortx-py-utils/.py3venv/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
make[2]: *** [dist/cortx_py_utils-1.0.0-py3-none-any.whl] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/cortx-py-utils'
error: Bad exit status from /var/tmp/rpm-tmp.9WVahz (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.9WVahz (%build)
make[1]: *** [__rpm] Error 1
make[1]: Leaving directory `/home/708945/src/Repos/rough/cortx-utils/py-utils'
make: *** [rpm] Error 2
```

Here dir not available
```
 /root/rpmbuild/BUILD/cortx-py-utils/.py3venv/bin/python3.6 -Im ensurepip --upgrade --default-pip
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.6/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/usr/lib64/python3.6/ensurepip/__init__.py", line 232, in _main
    default_pip=args.default_pip,
  File "/usr/lib64/python3.6/ensurepip/__init__.py", line 129, in _bootstrap
    shutil.copy(whl, tmpdir)
  File "/usr/lib64/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/python3.6/ensurepip/_bundled/setuptools-40.6.2-py2.py3-none-any.whl'
```

2020-11-02 04:27 UTC, mssawant commented
@ajay-paratmandali , build was successful at http://cortx-storage.colo.seagate.com/releases/cortx/components/github/custom-ci/release/centos-7.8.2003/dev/cortx-py-utils/13/ I think its present in our build environment, probably your local environment is missing it?

2020-11-04 14:47 UTC, chumakd commented on py-utils/utils.spec
> +%define _python_bytecompile_errors_terminate_build 0
Please, see this [commit](https://github.com/Seagate/cortx-hare/commit/ae12ad4044fdc2de30b32fcc83237838a57baaf4) from cortx-hare for a better fix of this issue.

2024-02-08 16:19 UTC, shailesh-vaidya commented
Closing as an obsolete

2024-02-08 16:19 UTC, closed without merging