EOS-25997: Implement limit_size API
Seagate/cortx-utils pull request #637
Opened 2021-12-08 14:40 UTC by gargpalak048

# Problem Statement
- Provide a general interface to Optimize Support Bundle Size

# Design
-  SB Framework will provide a general interface for the components to use to limit the size of the log file to be collected. 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [x] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [x] Check Acceptance Criterion is defined. 
- [x] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [x] Changes done to WIKI / Confluence page
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/749076684/Node+level+Support+Bundle+Collection

2021-12-09 07:05 UTC, cdeshmukh commented on py-utils/src/utils/support_framework/log_filters.py
> +            os.truncate(os.path.join(dest_dir, file_name), required_file_size)
Will this pickup latest log lines from the file ? I think it will pickup from top, which would be oldest to whatever lines possible to fit in the size

2021-12-09 09:06 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +                open(os.path.join(dest_dir, file_name), "r+b") as writing:
> flags here should be w+b !?

r+ mode gives both reading & writing permissions.
w+ creates a file if not exist or truncates the file to 0 if present,
as no file will be present at dest_dir at first, so any mode can be used
changed it to w+

> Also can you rename reading something more intuitive readHandle & writeHandle
Done.

2021-12-09 09:11 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +            os.truncate(os.path.join(dest_dir, file_name), required_file_size)
The code is tested & verified, it will pick up the latest logs. 
The file will be truncated from the beginning.
seek() will change the cursor from top of the file

2021-12-09 11:23 UTC, vastradparayya commented on py-utils/src/utils/support_framework/log_filters.py
> +                open(os.path.join(dest_dir, file_name), "w+b") as WriteHandle:
"r+b" can be 'r+b'
"w+b" can be 'w+b'

2021-12-09 16:39 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +                open(os.path.join(dest_dir, file_name), "w+b") as WriteHandle:
done

2021-12-10 07:36 UTC, vastradparayya approved these changes

2021-12-13 04:03 UTC, sachinpunadikar approved these changes
+1

2021-12-13 04:27 UTC, rahul-tripathi-git requested changes
Please use your best judgement to cater these comments.

2021-12-13 06:15 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +                size_in_bytes = int(float(num_units)) * multiplier
so if we pass any float value say "1.5MB", it gives base10 invalid literal error.
To avoid it we need to first convert it float,
one modification I have made, instead of casting num_units to int, we can return the final output in int.
so, done the changes, please review

2021-12-13 06:16 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +    def truncate_file_size(src_dir, dest_dir, file_name,
Yes agree, done

2021-12-13 06:16 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +    def get_size_in_bytes(size):
done

2021-12-13 06:16 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +    def get_size_in_bytes(size):
done.

2021-12-13 06:18 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +            if file_name.startswith(file_name_reg_ex):
Ack.
Handled the special ch (*)
There is no scenario where (.) will be passed.
It will something like:
FilterLog.limit_size('/var/log', '/tmp/test_dir', '1.5MB', 'messages')
FilterLog.limit_size('/var/log', '/tmp/test_dir', '1.5MB', 'messages*')

Handled both the cases.

2021-12-13 06:18 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +                elif file_size > required_file_size:
done

2021-12-13 06:21 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +            if file_name.startswith(file_name_reg_ex):
Handled.

2021-12-13 06:38 UTC, selvakumaar5496 commented on py-utils/src/utils/support_framework/log_filters.py
> +    def _get_size_in_bytes(size):
Can you please update with function annotations?
def _get_size_in_bytes(size: **int**):

2021-12-13 06:49 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +    def _get_size_in_bytes(size):
the size param will be str expected.
like:- "200KB" etc
this size str will be handled in the func.

2021-12-13 07:04 UTC, rahul-tripathi-git commented on py-utils/src/utils/support_framework/log_filters.py
> +            if file_name.startswith(file_name_reg_ex):
Lets mention the same in the spec doc: https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/749076684/Node+level+Support+Bundle+Collection#Current-Development-(PI-5)

Also mention the case where `*` is in the begining of the file name. (please see if that makes sense.

2021-12-13 07:12 UTC, rahul-tripathi-git commented on py-utils/src/utils/support_framework/log_filters.py
> +            os.makedirs(dest_dir)
Please add a validation check for source directory check, 
raise an exception if the source destination is not present.

2021-12-13 07:13 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +            if file_name.startswith(file_name_reg_ex):
Added in the Page.

> Also mention the case where * is in the begining of the file name. (please see if that makes sense.
currently we support the format where starting file name is parsed.
This can be a future optimization where a file extension can be parsed (for eg:- *.log), & it will process all the log files

2021-12-13 07:32 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +            os.makedirs(dest_dir)
done

2021-12-13 07:32 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +    def _truncate_file_size(src_dir, dest_dir, file_name,
done.

2021-12-13 07:32 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
>      def limit_size(src_dir, dest_dir, size, file_name_reg_ex):
done

2021-12-13 07:32 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +        required_file_size = size_in_bytes
done

2021-12-13 07:34 UTC, gargpalak048 commented on py-utils/src/utils/support_framework/log_filters.py
> +            os.makedirs(dest_dir)
done.

2021-12-13 08:20 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2021-12-13 08:29 UTC, selvakumaar5496 approved these changes

2021-12-13 08:49 UTC, cdeshmukh approved these changes

2021-12-13 08:49 UTC, cdeshmukh commented on py-utils/src/utils/support_framework/log_filters.py
> +            os.truncate(os.path.join(dest_dir, file_name), required_file_size)
i dont get option to resolve comment for this repo, please do so if you get

2021-12-13 09:50 UTC, merged