EOS-26878: add cortx.const in utils for defining constants of service name and components
Seagate/cortx-utils pull request #640
Opened 2021-12-09 10:47 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

# Problem Statement
- Added cortx constants for service names and component names

# Design
-  Added a new subpackage.module -> cortx.utils.cortx.const.py

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-12-09 10:52 UTC, sachinpunadikar commented on py-utils/src/utils/cortx/const.py
> +    # Services
don't we need SERVICE_MESSAGE_SERVER  = "message_server" ?

2021-12-09 10:58 UTC, nitin-seagate requested changes
@rahul-tripathi-git Please update the constants in-line with ticket specifications (some new constants added in ticket)

2021-12-09 10:58 UTC, nitin-seagate commented on py-utils/src/utils/cortx/const.py
> +    # Services
@sachinpunadikar If its utils specific then lets add it as:
`SERVICE_UTILS_MSGSERVER = "message_server"`

2021-12-09 11:11 UTC, rahul-tripathi-git commented on py-utils/src/utils/cortx/const.py
> +    # Services
Added as suggested by @nitin-seagate below. Kindly re-review.
`SERVICE_UTILS_MSGSERVER = "message_server"`

2021-12-09 11:12 UTC, rahul-tripathi-git commented
> @rahul-tripathi-git Please update the constants in-line with ticket specifications (some new constants added in ticket)

Done.

2021-12-09 11:36 UTC, vastradparayya commented on py-utils/src/utils/cortx/const.py
> +    SERVICE_S3_OPENLDAP    = "openldap"
@rahul-tripathi-git  should values be in single as all are single words?

2021-12-09 11:38 UTC, shriya-deshmukh commented on py-utils/src/utils/cortx/const.py
> +    SERVICE_S3_SERVER       = "s3server"
Can we define it as SERVICE_S3_S3SERVER , As we have followed same format('SERVICE_<COMP-NAME>_<SERVICE-NAME>') for all other keys?

2021-12-09 12:02 UTC, sachinpunadikar approved these changes
+1

2021-12-09 12:04 UTC, rahul-tripathi-git commented on py-utils/src/utils/cortx/const.py
> +    SERVICE_S3_OPENLDAP    = "openldap"
Done.

2021-12-09 12:05 UTC, rahul-tripathi-git commented on py-utils/src/utils/cortx/const.py
> +    SERVICE_S3_SERVER       = "s3server"
@ujjwalpl kindly suggest on above.

2021-12-09 12:19 UTC, vastradparayya approved these changes

2021-12-09 13:36 UTC, rahul-tripathi-git commented on py-utils/src/utils/cortx/const.py
> +    """Enum class to define constants for components and service names."""
https://github.com/PyCQA/pydocstyle/issues/141

2021-12-10 04:34 UTC, nitin-seagate approved these changes
LGTM

2021-12-10 04:35 UTC, nitin-seagate commented on py-utils/src/utils/cortx/const.py
> +    SERVICE_S3_SERVER       = "s3server"
SERVICE_S3_S3SERVER will make it cumbersome to read...

2021-12-10 04:37 UTC, nitin-seagate commented on py-utils/src/utils/cortx/const.py
> +    SERVICE_S3_SERVER       = "s3server"
SERVICE_S3_SERVER should be fine to understand and read...

2021-12-10 04:39 UTC, shriya-deshmukh approved these changes

2021-12-10 06:06 UTC, merged