EOS-26730: Consumer message_type Expiration filter for particular topic
Seagate/cortx-utils pull request #648
Opened 2021-12-14 10:10 UTC by suryakumar1024

# Problem Statement
- Analyze and work on existing expiration time argument per topic basis,

From the consumer side, work on a message filter that should skip expired messages for a given topic.

Existing:

Users can define an expiration time for messages under individual topics dynamically by the below statement.
Example:
admin.set_message_type_expire(message_type, time_out_period)
Current timeout logic will clean the offset after expire time of the entire message logs. In this way, the new consumer joins after the log cleanup won't receive the old message.
Need to be done:

The next step needs to sketch a logic to ensure that the existing consumer who try to read messages that already passed their expiration period must not receive any old message logs.

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-12-14 10:40 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            topic_resource.set_config('file.delete.delay.ms', 1)
Should there be any checks on the passed in keys, like should we check if both keys present or not ?

2021-12-14 10:41 UTC, sachinpunadikar reviewed
Check the comment

2021-12-14 10:46 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            topic_resource.set_config('file.delete.delay.ms', 1)
No, If the user passes any valid keys we do update the configuration. else we do nothing

2021-12-14 11:34 UTC, sachinpunadikar approved these changes
+1

2021-12-14 12:34 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        if 'expire_time_ms' in kwargs.keys() and 'data_limit_bytes' in kwargs.keys():
Updated in recent patch

2021-12-14 13:29 UTC, vastradparayya approved these changes

2021-12-14 15:05 UTC, selvakumaar5496 requested changes
Use the

2021-12-14 15:05 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            topic_resource.set_config('file.delete.delay.ms', 1)
Add this key, val to passed in kwargs in set_message_type_expire method

'file.delete.delay.ms' configuration is specific to set_message_type_expire and not for all

2021-12-14 15:05 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        """
Log.debug() --> 'set message type expire'

2021-12-14 15:05 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        return self._configure_message_type(admin_id, message_type, **kwargs)
Log.debug() --> 'successfully set message type expire'

2021-12-17 07:05 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        return self._configure_message_type(admin_id, message_type, **kwargs)
I have a different view here. Since in this method we are just creating configuration dict and passing it to below generic configuration change method. So in that method only the configuration will be updated also we have success message there in that generic configuration method.

2021-12-17 07:05 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        """
Updated in recent patch

2021-12-17 07:06 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                if key == 'expire_time_ms':
As discussed yesterday I have addressed above kind of same change in recent patch.

2021-12-17 07:06 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        """Set configuration for given message type."""
Updated in recent patch

2021-12-17 09:32 UTC, rohit-k-dwivedi commented on py-utils/test/message_bus/test_message_bus.py
> +            TestMessageBus._message_type, expire_time_ms=604800000)
can have a comment indication 604800000 calculates to 7 days for expire_time_ms=7*24*60*60*1000 makes it easy to identify as 7 days

2021-12-17 10:44 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            and 'data_limit_bytes' not in kwargs.keys():
Can be simplified to:
if 'expire_time_ms' and 'data_limit_bytes' not in kwargs.keys():

2021-12-17 10:47 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                topic_resource.set_config(key, val)
```
for key, val in kwargs.items():
    topic_resource.set_config(self._config_prop_map[key], val)
```

2021-12-17 10:50 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        return self._configure_message_type(admin_id, message_type, **config)
```
        config = {}
        for key, val in kwargs.items():
            if key in self._config_prop_map.keys():
                config[self._config_prop_map[key]] = val
        config[self._config_prop_map['file_delete_ms']] = 1
```
optimise to below;
```
	kwargs['file.delete.ms'] = 1
	return self._configure_message_type(admin_id, message_type, **kwargs)
```

2021-12-17 11:33 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                topic_resource.set_config(key, val)
Its not required to handle here. Since generic configuration method gets proper key map. from the set expire method.

2021-12-17 12:19 UTC, suryakumar1024 commented on py-utils/test/message_bus/test_message_bus.py
> +            TestMessageBus._message_type, expire_time_ms=604800000)
Yes that's cool. Updated in recent patch

2021-12-17 12:20 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            and 'data_limit_bytes' not in kwargs.keys():
Addressed in recent patch

2021-12-17 12:20 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                topic_resource.set_config(key, val)
As discussed Updated in recent patch.

2021-12-17 12:20 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        return self._configure_message_type(admin_id, message_type, **config)
As discussed Updated in recent patch.

2021-12-17 12:48 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug(f"Set configuration for message " \
Change Set configuration --> Alter configuration

2021-12-17 12:48 UTC, selvakumaar5496 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        """Set message_type expiration for given message type."""
let it be """Set expiration time for given message type."""

2021-12-17 12:48 UTC, selvakumaar5496 approved these changes

2021-12-17 14:44 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug(f"Set configuration for message " \
Instead one can say "New configuration for message type ... "

2021-12-17 14:45 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.ENOENT, "Unknown Message type: Could"+\
Keep it simple:
"Unknown message type <>, not listed in <>"

2021-12-17 14:46 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug("Successfully updated message type configurations.")
Make it Log.info

2021-12-17 14:48 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        return self._configure_message_type(admin_id, message_type, **kwargs)
Add success  message using Log.info
This is client facing API, so Log.info is required to let know the success
In case of failure say Log.error

2021-12-17 14:49 UTC, sachinpunadikar commented on py-utils/src/utils/message_bus/message_bus_client.py
>          return self._message_bus.set_message_type_expire(client_id,\
Add success message using Log.info
This is client facing API, so Log.info is required to let know the success
In case of failure say Log.error

2021-12-17 14:50 UTC, sachinpunadikar requested changes
Work on comments, rest all looks good

2021-12-17 14:53 UTC, rohit-k-dwivedi approved these changes

2021-12-20 05:23 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            raise MessageBusError(errno.ENOENT, "Unknown Message type: Could"+\
Updated in recent patch.

2021-12-20 05:23 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus_client.py
> +        """Set message_type expiration for given message type."""
Updated in recent patch.

2021-12-20 05:23 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +        Log.debug(f"Set configuration for message " \
Updated in the recent patch.

2021-12-20 05:25 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus_client.py
>          return self._message_bus.set_message_type_expire(client_id,\
The success/ failure log will be handled inside internal methods.

set_message_type_expiure - will internally call-> _config_message_type()

2021-12-20 06:59 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_bus_client.py
>          return self._message_bus.set_message_type_expire(client_id,\
Updated in recent patch

2021-12-20 08:12 UTC, ujjwalpl requested changes

2021-12-20 08:12 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    _config_prop_map={
space before / after =

2021-12-20 08:14 UTC, ujjwalpl requested changes

2021-12-20 08:14 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                topic_resource.set_config(self._config_prop_map[key], val)
Need to handle the case where key is not part of _config_prop_map.

2021-12-20 10:31 UTC, sachinpunadikar approved these changes
+1

2021-12-20 14:06 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                topic_resource.set_config(self._config_prop_map[key], val)
Updated in recent patch.

2021-12-20 14:06 UTC, suryakumar1024 commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +    _config_prop_map={
Updated in recent patch.

2021-12-20 14:18 UTC, ujjwalpl requested changes

2021-12-20 14:18 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +                    "Invalid configuration %s for message_type %s.", key,\
Add indentation here

2021-12-20 14:29 UTC, ujjwalpl approved these changes

2021-12-20 17:31 UTC, merged