EOS-26899: Message bus server common init in utils server
Seagate/cortx-utils pull request #649
Opened 2021-12-14 13:02 UTC by suryakumar1024

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
- Make message bus init  call inside utils server itself so that other URLs method defined in utils routs can able to access the message config

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-12-14 13:28 UTC, vastradparayya approved these changes

2021-12-17 09:07 UTC, selvakumaar5496 commented on py-utils/test/message_bus/test_message_bus_server.py
> +    _message_type = 'testit12'
Why message_type is changed?

2021-12-17 10:54 UTC, selvakumaar5496 commented on py-utils/src/utils/utils_server/utils_server.py
> +    log_dir = CortxConf.get('log_dir')
We need to get rid of CortxConf. 
log_path should be read from confstore

2021-12-17 12:18 UTC, suryakumar1024 commented on py-utils/test/message_bus/test_message_bus_server.py
> +    _message_type = 'testit12'
reverted in recent patch

2021-12-20 05:09 UTC, suryakumar1024 commented on py-utils/src/utils/utils_server/utils_server.py
> +    log_dir = CortxConf.get('log_dir')
Updated in recent patch

2021-12-20 08:45 UTC, ujjwalpl requested changes

2021-12-20 08:45 UTC, ujjwalpl commented on py-utils/src/utils/utils_server/utils_server.py
> +        MessageBus.init(message_server_endpoints=message_server_endpoints)
utils_sever is a framework and MUST not call Message Bus Init. 

Create a class called MesageServer, derive from UtilsServer and Message Bus Init should be included in that.

2021-12-27 10:58 UTC, veerendra-simha-garikipati requested changes

2021-12-27 12:50 UTC, selvakumaar5496 approved these changes

2021-12-27 14:41 UTC, veerendra-simha-garikipati approved these changes

2022-01-07 04:14 UTC, suryakumar1024 commented
Closing this PR. Raised new one for the same requirements https://github.com/Seagate/cortx-utils/pull/677

2022-01-07 04:14 UTC, closed without merging