EOS-14525: SSPL: Add support for BMC & enclosure controller accessibility validators
Seagate/cortx-utils pull request #66
Opened 2020-10-29 13:26 UTC by mariyappanp

2020-10-30 14:46 UTC, mariyappanp commented
@cdeshmukh , please review.

2020-11-02 07:45 UTC, cdeshmukh commented on py-utils/requirements.txt
> +paramiko==2.7.2
@ujjwalpl we are adding this dependency for cortx-pyutils. Its already being used by sspl, so its not a new package which is getting pulled. just fyi

2020-11-02 08:44 UTC, cdeshmukh requested changes

2020-11-02 08:44 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +            node_bmc = self.fetch_salt_data('pillar.get', 'cluster')[node]['bmc']
what bmc config being collected per node?

2020-11-02 08:44 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +        """Check BMC IP is reachable"""
In LDR R1, we need to check BMC accessibility through inband KCS channel access, where we dont need username/passwd/ip. This was discussed earlier.

2020-11-02 08:44 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +    valid_msg = "Command completed successfully"
better check for one the field & its value, like "Bundle Version" and with supported value having "GN265" or "GN280" in it.

> show versions
                Controller A Versions        Controller B Versions
                ---------------------        ---------------------
Bundle Version: GN265R009-03                 GN265R009-03
Build Date:     Wed Sep 19 13:36:08 MDT 2018 Wed Sep 19 13:36:08 MDT 2018
Success: Command completed successfully. (2020-11-02 08:42:36)

2020-11-02 08:44 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +    def fetch_salt_data(func, arg):
this function can go in any common existing or new class

2020-11-02 08:44 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +        response = stdout.read().decode()
check for supported firmware version per controller, contained in "Bundle Version", compare with supported value having "GN265" or "GN280".

> show versions
                Controller A Versions        Controller B Versions
                ---------------------        ---------------------
Bundle Version: GN265R009-03                 GN265R009-03
Build Date:     Wed Sep 19 13:36:08 MDT 2018 Wed Sep 19 13:36:08 MDT 2018
Success: Command completed successfully. (2020-11-02 08:42:36)

2020-11-02 13:58 UTC, mariyappanp commented on py-utils/test/test_bmc_and_controller_ip.py
> +            node_bmc = self.fetch_salt_data('pillar.get', 'cluster')[node]['bmc']
> >>> import salt.client
> >>> salt.client.Caller().function('pillar.get', 'cluster')['srvnode-1']['bmc']
> {'ip': '10.237.65.48', 'user': 'bmcadmin', 'secret': 'gAAAAABfn-riM1XZbyvU-wDyjzansNqccWjXnsHk2yG8MGX5mQaNoUwLHY5_9dvbZor6EBK4ciclZaYpwNmH7jwF0duNB_kbfA=='}
> >>>
> >>> salt.client.Caller().function('pillar.get', 'cluster')['srvnode-2']['bmc']
> {'ip': '10.237.64.250', 'user': 'bmcadmin', 'secret': 'gAAAAABfn-riHY6D7q_jWhxhVCe3wVPacKCuIilPpf6wQahQpPdqApScJiDka5M90_L1z1qIg-BGmgaGKV4EsgMHUVUVRuvz4g=='}

2020-11-02 14:29 UTC, mariyappanp commented on py-utils/test/test_bmc_and_controller_ip.py
> +    valid_msg = "Command completed successfully"
Okay

2020-11-02 14:29 UTC, mariyappanp commented on py-utils/test/test_bmc_and_controller_ip.py
> +        response = stdout.read().decode()
Okay

2020-11-02 16:09 UTC, mariyappanp commented on py-utils/test/test_bmc_and_controller_ip.py
> +        """Check BMC IP is reachable"""
Done.

2020-11-02 16:09 UTC, mariyappanp commented on py-utils/test/test_bmc_and_controller_ip.py
> +        response = stdout.read().decode()
Done.

2020-11-02 16:43 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +        """Check BMC IP is reachable"""
I dont see code reflecting the ask as per previous comment. Still ip/username/passwd being used to access bmc.

2020-11-02 16:45 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +    expected_versions = ['GN265', 'GN265']
G265,G280

2020-11-02 16:47 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +            f"Storage enclosure primary IP {self.primary_mc} is reachable but, not accessible."
we need to differentiate the checks. If controller is accessible with given ip & credentials, if command is responding (check 'Success' in response) & then check for supported versions.

2020-11-02 16:48 UTC, cdeshmukh requested changes
Please update the patch with latest code if missed somehow. as i see review comment replies that its addressed but dont see the corresponding code.

2020-11-03 05:16 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +        """Check BMC IP is reachable"""
Actually @mariyappanp these validators are at cortx level, where BMC is accessed both ways, inband kcs channel & out of band using network ip. So i guess both checks will be useful. So dont remove the changes for ip, sorry for those previous comments, add that back with ip/user/passwd as one of the test. And keep other test for BMC accessibility using kcs channel

@kaushalSM please address pending comments take this forward as @mariyappanp is on leave.

2020-11-03 10:39 UTC, mariyappanp commented on py-utils/test/test_bmc_and_controller_ip.py
> +        """Check BMC IP is reachable"""
@kaustubh-d , thanks for the sync up and mentioning "channel info" command.
I have addressed the remaining comments as well. Please watch and update this script for any further comments.

2020-11-04 08:33 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +    def test_bmc_accessibility(self):
rename to  test_bmc_inband_accessibility. Update comment to on next line

2020-11-04 08:33 UTC, cdeshmukh commented on py-utils/test/test_bmc_and_controller_ip.py
> +        ip = self.node_bmc['ip']
we dont need to look for ip in this case, can remove

2020-11-04 08:35 UTC, cdeshmukh requested changes
minor comments

2020-11-06 13:20 UTC, cdeshmukh requested changes

2020-11-06 13:20 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_bmc.py
> +            if 'KCS' not in ch_info:
if command working through any other channel also its fine. Main validation is that the command works. If not KCS, we can print other channel or stdout and return true still if command passed

2020-11-06 13:20 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_bmc.py
>      def __ping_bmc(self, node):
__check_bmc_access()

This is no ping without ip now

2020-11-06 13:20 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_controller.py
> +            raise VError(errno.EINVAL,
we can use required & ignore extra arguments, why fail out ?

2020-11-06 13:20 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_controller.py
> +    def __get_bundle_info(self, conn):
__get_fw_info()

bundle can be confused with support bundle easily. I know as fw bundle 5u84 maintains it, but at cortx side, we can limit to fw info to avoid confusion

2020-11-06 13:20 UTC, cdeshmukh commented on py-utils/test/validator/test_controller_validator.py
> +    def test_accessibility_no_args_error(self):
why we are checking for negative cases, purpose?

2020-11-06 13:31 UTC, mariyappanp commented on py-utils/src/utils/validator/v_bmc.py
> +        cmd = "ssh {node} ipmitool channel info"
srvnode-1, srvnode-2 are added as known hosts during setup. So I believe ssh is preferred here for passwordless command execution.

validator.py bmc accessible <**node1**> <**node2**>
It takes two nodes and performs ipmitool command execution on both node one by one during iteration.

2020-11-06 13:33 UTC, mariyappanp commented on py-utils/src/utils/validator/v_bmc.py
> +            if 'KCS' not in ch_info:
Sure, I will update the script.

2020-11-06 13:34 UTC, mariyappanp commented on py-utils/src/utils/validator/v_controller.py
> +    def __get_bundle_info(self, conn):
Okay, I will rename this as suggested.

2020-11-06 13:37 UTC, mariyappanp commented on py-utils/src/utils/validator/v_controller.py
> +            raise VError(errno.EINVAL,
If so, when test pass, user may think extra arguments are also accepted and validated.
But we strict to number of arguments and show usage details if extra arguments will be passed.(VError takes care of instructing the user what is required to pass.)

2020-11-06 13:40 UTC, mariyappanp commented on py-utils/test/validator/test_controller_validator.py
> +    def test_accessibility_no_args_error(self):
Yes, I referred other unit test cases too. 
This is to confirm no functionality broken later any changes introduced in v_controller module by anyone.

2020-11-06 14:04 UTC, ujjwalpl requested changes

2020-11-06 14:04 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_controller.py
> +    def __establish_ssh_connection(self, ip, user, passwd, port=22):
Please create a class called SshSession in the common code and use that here. 

```
class SshSession: 
    def __init__(ip, port, passwd, timeout):

    def run(cmd): 
        ...
        return rc, output, error

   def __cleanup__():
        disconnect. 

```

2020-11-06 14:04 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_controller.py
> +                errno.EINVAL, f"Failed to establish connection to controller IP, {ip}")
We need to provide all kinds of information in the exception. Please ensure this is the case with all the VErrors

2020-11-09 07:54 UTC, mariyappanp commented on py-utils/src/utils/validator/v_bmc.py
>      def __ping_bmc(self, node):
I have covered BMC accessibility on inband, outband setup using `channel info` command.
__ping_bmc() is existing code and still it is additional validation after inband, outband coverage.

2020-11-09 08:02 UTC, sanjognaik commented on py-utils/src/utils/validator/v_bmc.py
> +        cmd = f"ipmitool -H {bmc_ip} -U {bmc_user} -P {bmc_passwd} -I lan {self.channel_cmd}"
Please accept 'node' as argument so that you can execute this command on given node 'ssh {node}'.

2020-11-09 08:17 UTC, sanjognaik commented on py-utils/src/utils/validator/validate.py
>                          "\t[bmc accessible <node1> <node2> <...>]\n"
Please update this with new arguments.

2020-11-09 08:40 UTC, mariyappanp commented on py-utils/src/utils/validator/v_bmc.py
> +        cmd = "ssh {node} ipmitool channel info"
We can use paramiko also, but it requires explicit credentials params. Since nodes are in cluster and passwordless ssh connection is possible, we utilize the same here for reducing the effort.

**channel info over lan:**
This is additional check on BMC accessibility which uses paramiko.
Main purpose is validation over the mapped BMC IP and Authentication.

2020-11-09 08:42 UTC, mariyappanp commented on py-utils/src/utils/validator/v_bmc.py
> +            if 'KCS' not in ch_info:
Done.

2020-11-09 08:43 UTC, mariyappanp commented on py-utils/src/utils/validator/v_controller.py
> +            raise VError(errno.EINVAL,
Like other validator design.

2020-11-09 08:43 UTC, mariyappanp commented on py-utils/src/utils/validator/v_controller.py
> +    def __establish_ssh_connection(self, ip, user, passwd, port=22):
Done. @ujjwalpl please review.

2020-11-09 08:45 UTC, mariyappanp commented on py-utils/src/utils/validator/v_controller.py
> +                errno.EINVAL, f"Failed to establish connection to controller IP, {ip}")
I added SSHSession class in comm.py where different exceptions are handled.

2020-11-09 08:52 UTC, mariyappanp commented on py-utils/src/utils/validator/v_bmc.py
> +        cmd = f"ipmitool -H {bmc_ip} -U {bmc_user} -P {bmc_passwd} -I lan {self.channel_cmd}"
I feel that 'ssh {node}' is not required here.
This command can be executed remotely if it takes valid bmc information.
@sanjognaik pls let me know if that is necessary still.

2020-11-09 10:22 UTC, mariyappanp commented on py-utils/src/utils/validator/validate.py
>                          "\t[bmc accessible <node1> <node2> <...>]\n"
Done

2020-11-09 14:14 UTC, sanjognaik commented on py-utils/test/validator/test_bmc_validator.py
>          """ Check Stonith configuration """
The error is due to BMC IP. Please update this test same as test_accessibility_ok() to fix the error. Thanks.

2020-11-09 15:04 UTC, mariyappanp commented on py-utils/test/validator/test_bmc_validator.py
>          """ Check Stonith configuration """
Done.

2020-11-10 05:36 UTC, sanjognaik approved these changes

2020-11-10 06:28 UTC, cdeshmukh approved these changes

2020-11-10 06:28 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_bmc.py
>      def __ping_bmc(self, node):
Ok

2020-11-10 06:28 UTC, cdeshmukh commented on py-utils/src/utils/validator/v_bmc.py
> +        cmd = f"ipmitool -H {bmc_ip} -U {bmc_user} -P {bmc_passwd} -I lan {self.channel_cmd}"
agree with @mariyappanp

2020-11-11 05:43 UTC, ujjwalpl requested changes

2020-11-11 05:43 UTC, ujjwalpl commented on py-utils/src/utils/comm.py
> +
Remove blank line

2020-11-11 05:43 UTC, ujjwalpl commented on py-utils/src/utils/comm.py
> +    def __connect(self):
Connect should be an exposed interface. Imagine if the command fails with disconnection caller call connect again without having to reinstatiate.

2020-11-11 05:43 UTC, ujjwalpl commented on py-utils/src/utils/comm.py
> +        self.client.close()
Please add test code for this class. 
Also submit this as separate patch

2020-12-04 03:07 UTC, mariyappanp commented on py-utils/src/utils/comm.py
> +
Done.

2020-12-04 03:07 UTC, mariyappanp commented on py-utils/src/utils/comm.py
> +    def __connect(self):
Done.

2020-12-04 03:08 UTC, mariyappanp commented on py-utils/src/utils/comm.py
> +        self.client.close()
Done, merged.

2020-12-04 03:09 UTC, closed without merging