WIP - EOS-26066: REST API to accept webhook information in utils rest server
Seagate/cortx-utils pull request #660
Opened 2021-12-21 04:12 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- REST API to accept webhook information in utils rest server

# Design
-  https://jts.seagate.com/browse/EOS-26066

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: Y
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-12-23 13:28 UTC, sachinpunadikar commented on py-utils/src/utils/audit_log/audit_log_server.py
> +                producer = MessageProducer(producer_id='audit_log_send', \
producer can be defined outside, so no need to define it for every send .. this producer is fixed as message_type is fixed

2021-12-23 13:30 UTC, sachinpunadikar commented on py-utils/src/utils/audit_log/audit_log_server.py
> +            if not external_server_info:
Code can be optimized if you handle sending of audit message to external server first

2021-12-23 13:33 UTC, sachinpunadikar commented on py-utils/src/utils/audit_log/audit_log_server.py
> +            external_server_info = payload.get('external_server_info')
external_server_info is not part of the payload, its part of POST request of webhook
why you are trying get external_server_info here ?

2021-12-23 13:53 UTC, sachinpunadikar commented on py-utils/src/utils/audit_log/audit_log_server.py
> +            Log.error(f"Unable to post audit webhook information, status code: " \
We are not POSTing .. actually we are receiving , correct the message

2021-12-23 13:54 UTC, sachinpunadikar commented on py-utils/src/utils/audit_log/audit_log_server.py
> +            Log.error(f"Internal error while sending webhook info." \
We are not sending, we are receiving it

2021-12-23 13:58 UTC, sachinpunadikar requested changes
work on comments

2021-12-27 08:00 UTC, rohit-k-dwivedi reviewed
please work on comments and codacy issued

2021-12-27 10:35 UTC, vastradparayya commented on py-utils/src/utils/audit_log/audit_log_server.py
> +                producer = MessageProducer(producer_id='audit_log_send', \
Done

2021-12-27 10:35 UTC, vastradparayya commented on py-utils/src/utils/audit_log/audit_log_server.py
> +            if not external_server_info:
Done

2021-12-27 10:36 UTC, vastradparayya commented on py-utils/src/utils/audit_log/audit_log_server.py
> +            external_server_info = payload.get('external_server_info')
Done. fetched from file

2021-12-27 10:36 UTC, vastradparayya commented on py-utils/src/utils/audit_log/audit_log_server.py
> +            Log.error(f"Unable to post audit webhook information, status code: " \
Done

2021-12-27 10:36 UTC, vastradparayya commented on py-utils/src/utils/audit_log/audit_log_server.py
> +            Log.error(f"Internal error while sending webhook info." \
Done

2021-12-27 11:28 UTC, selvakumaar5496 commented on py-utils/src/utils/audit_log/audit_log_server.py
> +    message_type='audit_log_message', method='sync')
When or Who will create this message type

2021-12-27 11:29 UTC, selvakumaar5496 approved these changes

2021-12-27 18:05 UTC, vastradparayya commented on py-utils/src/utils/audit_log/audit_log_server.py
> +    message_type='audit_log_message', method='sync')
audit_log_message message_type created as mini-provisioning's init phase

2021-12-28 04:01 UTC, sachinpunadikar commented on py-utils/src/setup/utils.py
> +            admin.register_message_type(message_types=['IEM', 'audit_log_message'], \
Suggestion 
audit_log_message -> audit_messages

2021-12-28 04:04 UTC, sachinpunadikar approved these changes
Added a suggestion, rest all looks good

2021-12-28 04:23 UTC, vastradparayya commented on py-utils/src/setup/utils.py
> +            admin.register_message_type(message_types=['IEM', 'audit_log_message'], \
Changed message_type from audit_log_message -> audit_messages

2021-12-28 04:34 UTC, rohit-k-dwivedi approved these changes

2021-12-28 04:44 UTC, merged