WIP: No conf msg server
Seagate/cortx-utils pull request #677
Opened 2021-12-31 06:13 UTC by suryakumar1024

…py files

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-01-03 10:06 UTC, sachinpunadikar approved these changes
+1

2022-01-05 03:11 UTC, vastradparayya commented on py-utils/src/utils/utils_server/utils_server.py
> +    log_dir = Conf.get('config','cortx>common>storage>log')
Hi @suryakumar1024, can we use CortxConf.get_storage_path here?
```
log_dir = CortxConf.get_storage_path('log')
```

2022-01-05 05:05 UTC, rohit-k-dwivedi commented on py-utils/src/utils/utils_server/utils_server.py
>  from cortx.utils.log import Log
please add a blank line between cortx imports and other library imports

2022-01-05 05:38 UTC, rohit-k-dwivedi approved these changes

2022-01-05 06:32 UTC, ujjwalpl requested changes

2022-01-05 06:32 UTC, ujjwalpl commented on py-utils/src/utils/utils_server/utils_server.py
> +class MessageServer(UtilsServer):
Please move this class to message_bus folder.

2022-01-05 06:36 UTC, ujjwalpl requested changes

2022-01-05 06:36 UTC, ujjwalpl commented on py-utils/src/utils/utils_server/utils_server.py
> +            'cortx>external>kafka>endpoints')
kafka is hard coded. It should be obtained from the variable. 
message_bus_backend = Conf.get('utils>message_bus_backend')
message_server_endpoints = Conf.get('config', f'cortx>external>{message_bus_backend}>endpoints')

2022-01-05 15:01 UTC, sachinpunadikar commented on py-utils/src/utils/utils_server/utils_server.py
> +class MessageServer(UtilsServer):
@ujjwalpl as I understand, this class is catering to all kind of messages and working on top of message bus library.
So it will not be a good idea to move this class in message_bus folder.
Instead we can have separate file in current folder having this class.
Please confirm

2022-01-06 02:29 UTC, selvakumaar5496 approved these changes

2022-01-06 04:58 UTC, vastradparayya approved these changes

2022-01-06 05:45 UTC, suryakumar1024 commented on py-utils/src/utils/utils_server/utils_server.py
>  from cortx.utils.log import Log
updated in recent patch

2022-01-06 05:45 UTC, suryakumar1024 commented on py-utils/src/utils/utils_server/utils_server.py
> +    log_dir = Conf.get('config','cortx>common>storage>log')
updated in recent patch

2022-01-07 08:22 UTC, sachinpunadikar commented
test this please

2022-01-07 09:25 UTC, sachinpunadikar commented
Going ahead with merge, as Ujjwal's suggestion can be handled separately

2022-01-07 09:25 UTC, merged