EOS-26183: Filters support for Support bundle creation for Utils
Seagate/cortx-utils pull request #678
Opened 2021-12-31 06:19 UTC by vastradparayya

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>

# Problem Statement
- Filters support for Support bundle creation for Utils

# Design
-  https://jts.seagate.com/browse/EOS-26183

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [x] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: Y
- [x] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- [x] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [x] Is there a change in filename/package/module or signature [Y/N]: N
- [x] If yes for above point, Is a notification sent to all other cortx components [Y/N] NA
- [x] Jira is updated
- [x] Check if the description is clear and explained. 
- [x] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2021-12-31 08:54 UTC, selvakumaar5496 commented on py-utils/src/support/utils_support_bundle.py
> +        size_limit: str, binlogs: bool, coredumps: bool, stacktrace: bool):
Instead of increasing the no of params, Can you please have a kwargs and name it as **filters?

2021-12-31 09:49 UTC, vastradparayya commented on py-utils/src/support/utils_support_bundle.py
> +        size_limit: str, binlogs: bool, coredumps: bool, stacktrace: bool):
Done

2022-01-01 17:36 UTC, ujjwalpl requested changes

2022-01-01 17:36 UTC, ujjwalpl commented on py-utils/src/support/utils_support_bundle.py
> +def str2bool(value):
Do not add global functions.

2022-01-03 05:24 UTC, vastradparayya commented on py-utils/src/support/utils_support_bundle.py
> +def str2bool(value):
Removed str2bool global method

2022-01-03 09:56 UTC, sachinpunadikar approved these changes
+1

2022-01-03 10:30 UTC, ujjwalpl requested changes

2022-01-03 10:30 UTC, ujjwalpl commented on py-utils/src/support/utils_support_bundle.py
> +            raise argparse.ArgumentTypeError('Boolean value expected.')
Can you check and confirm passing an arbitrary value e.g. "foo" results in CORTX level exception e.g. SupportBundleError and does not lead to ArgumentTypeError exception to user unhandled ?

2022-01-03 10:49 UTC, vastradparayya commented on py-utils/src/support/utils_support_bundle.py
> +            raise argparse.ArgumentTypeError('Boolean value expected.')
```
[root@ssc-vm-g3-rhev4-1094 cortx-utils]# utils_support_bundle -b SBag9s2g0355678_445c7c22dbaa4a3d978c0c98c3889c42_utils -t /var/log/cortx/support_bundle/SBag9s2g0355678/ -c yaml:///etc/cortx/cluster.conf -s all --duration P5D --size_limit 625.0MB --binlogs False --coredumps False **--stacktrace foo**
usage: utils_support_bundle [-h] [-b BUNDLE_ID] [-t [PATH]] [-c CLUSTER_CONF]
                            [-s SERVICES [SERVICES ...]] [-d DURATION]
                            [--size_limit SIZE_LIMIT] [--binlogs BINLOGS]
                            [--coredumps COREDUMPS] [--stacktrace STACKTRACE]
                            [--modules MODULES]
**utils_support_bundle: error: argument --stacktrace: Boolean value expected.**
```

2022-01-03 11:31 UTC, ujjwalpl approved these changes

2022-01-03 12:18 UTC, selvakumaar5496 approved these changes

2022-01-03 17:35 UTC, sachinpunadikar commented
Ignoring codacy issues as the unused variables will be used in upcoming changes.
Ignoring whitesource issue as it was not added by this PR

2022-01-03 17:35 UTC, merged