EOS-27087:Version compatibility check.
Seagate/cortx-utils pull request #684
Opened 2022-01-03 14:00 UTC by shriya-deshmukh

Signed-off-by: Shriya Deshmukh <shriya.deshmukh@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-01-03 17:50 UTC, ujjwalpl requested changes

2022-01-03 17:50 UTC, ujjwalpl commented on py-utils/src/utils/schema/release.py
> +        if not deploy_version:
We will need to separate provisioner specific things like actions from this code and move it to provisioner. This class should limit to release schema representation and comparison.

2022-01-03 17:51 UTC, ujjwalpl requested changes

2022-01-03 17:51 UTC, ujjwalpl commented on py-utils/src/utils/schema/release.py
> +    _release_info_url = 'yaml:///opt/seagate/cortx/RELEASE.INFO'
Common code like utils must not have anything related to CORTX.

2022-01-04 05:12 UTC, shriya-deshmukh commented on py-utils/src/utils/schema/release.py
> +    _release_info_url = 'yaml:///opt/seagate/cortx/RELEASE.INFO'
Removed.

2022-01-04 05:15 UTC, shriya-deshmukh commented on py-utils/src/utils/schema/release.py
> +        if not deploy_version:
Done,  instead of action, returning return code as below, based on ret_code we can decide action in provisioner code. 
Return code:
            0 - If both versions are equal.
            1 - If deployed_version > release_version.
            -1 - If deployed_version < release_version.

2022-01-04 09:34 UTC, ujjwalpl requested changes

2022-01-04 09:34 UTC, ujjwalpl commented on py-utils/src/utils/schema/release.py
> +class Release(Manifest):
You are assuming Manifest to be abstract class but deriving from that. Manifest should be a normal class so that you can derive from there.

2022-01-04 09:37 UTC, ujjwalpl requested changes

2022-01-04 09:37 UTC, ujjwalpl commented on py-utils/src/utils/schema/release.py
> +    def __init__(self, file_path):
You are hard coding the parameter to 
1. file path 
2. yaml

You should accept URL as input to remain agnostic.

2022-01-04 09:45 UTC, ujjwalpl requested changes

2022-01-04 09:45 UTC, ujjwalpl commented on py-utils/src/utils/schema/release.py
> +    def _get_rpm_version(rpm_name: str):
Manifest is generic class and not specific to release. Adding things like rpm makes it specific to release. 
Move this to the release class.

2022-01-04 09:45 UTC, ujjwalpl commented on py-utils/src/utils/schema/release.py
> +    def _get_val(index, key):
This is one line function. Typically avoid one line function unless they are there for specific reasons. 

Another problem. You are assuming caller to use conf. This splits responsibility inconsistently between this class and derived class, i.e. caller must initialize and this class must use it. If you need conf then...

class Manifest: 
    __init__(manifest_url):
        self._index = Conf.load(manifest_url)

    _get_manifest_val(key):
        return Conf.get(self._index, key)

2022-01-04 09:47 UTC, ujjwalpl requested changes

2022-01-04 09:47 UTC, ujjwalpl commented on py-utils/src/utils/schema/release.py
> +    def _get_digits(version_str: str):
This again is release specific thing and needs to be in the release (derrived) class.

2022-01-04 11:40 UTC, shriya-deshmukh commented on py-utils/src/utils/schema/release.py
> +    def _get_rpm_version(rpm_name: str):
Done

2022-01-04 11:41 UTC, shriya-deshmukh commented on py-utils/src/utils/schema/release.py
> +    def __init__(self, file_path):
Done

2022-01-04 11:41 UTC, shriya-deshmukh commented on py-utils/src/utils/schema/release.py
> +    def _get_val(index, key):
Now Manifest cls handles all 'Conf' related function (load/get_value).

2022-01-04 11:53 UTC, ujjwalpl approved these changes

2022-01-05 09:28 UTC, sachinpunadikar commented on py-utils/src/utils/schema/release.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
copyright year should be 2022

2022-01-05 09:30 UTC, sachinpunadikar approved these changes
Minor comment, rest all looks good

2022-01-05 09:33 UTC, shriya-deshmukh commented on py-utils/src/utils/schema/release.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Done.

2022-01-05 11:10 UTC, merged