Implement KV store
Seagate/cortx-utils pull request #70
Opened 2020-10-30 06:01 UTC by shrimetta

**Problem Statement**
KV store

**Solution Overview**
Implemented KVStore with PillarDB 

Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>

2020-10-30 15:00 UTC, ujjwalpl requested changes

2020-10-30 15:00 UTC, ujjwalpl commented on py-utils/src/utils/store/pillar.py
> +        except json.decoder.JSONDecodeError:
There may be other exceptions as well. For example if 'local' is not the key in the res.

2020-10-31 06:30 UTC, ajaysrivas requested changes

2020-10-31 06:30 UTC, ajaysrivas commented on py-utils/src/utils/store/dstore.py
> +class KvDB:
Name of KvDB should be KvStorage.
Name of KvStore should be KvManager.

2020-10-31 06:30 UTC, ajaysrivas commented on py-utils/src/utils/store/dstore.py
> +    def set(self, key, value):
Some of the stores may not allow update of keys.
We need distinction between key-value creation and key-value update so that underlying storage can throw exception for update.

2020-10-31 06:30 UTC, ajaysrivas commented on py-utils/src/utils/store/dstore.py
> +#!/bin/python3
why the name of file is dstore.py? Should it be kvstore.py?

2020-11-02 08:11 UTC, shrimetta commented on py-utils/src/utils/store/pillar.py
> +        except json.decoder.JSONDecodeError:
fixed

2020-11-02 08:11 UTC, shrimetta commented on py-utils/src/utils/store/dstore.py
> +class KvDB:
done

2020-11-02 08:11 UTC, shrimetta commented on py-utils/src/utils/store/dstore.py
> +    def set(self, key, value):
done

2020-11-02 08:12 UTC, shrimetta commented on py-utils/src/utils/store/dstore.py
> +#!/bin/python3
renamed to kvstore

2020-11-02 10:33 UTC, ajaysrivas approved these changes

2020-11-02 11:34 UTC, ujjwalpl requested changes

2020-11-02 11:34 UTC, ujjwalpl commented on py-utils/src/utils/kvstore/kvstore.py
> +    def create(self, key, value):
create is not required. We only neet following interfaces for a typical keystore
1. get
2. set (same as create / update)
3. delete

2020-11-02 11:34 UTC, ujjwalpl commented on py-utils/src/utils/kvstore/kvstore.py
> +class KvManager:
Lets Keep this as KVStore itself. For external modules, this is KVStore.

2020-11-02 11:45 UTC, ujjwalpl requested changes

2020-11-02 11:45 UTC, ujjwalpl commented on py-utils/src/utils/kvstore/kvstore.py
> +    def create(self, key, value):
Interfaces should be 
get
set (same as create / update)
delete

2020-11-02 12:04 UTC, ujjwalpl requested changes

2020-11-02 13:30 UTC, shrimetta commented on py-utils/src/utils/store/pillar.py
> +        # TODO: Implement
I will add the its implementation in next checkin.

2020-11-02 13:30 UTC, shrimetta commented on py-utils/src/utils/kvstore/kvstore.py
> +    def create(self, key, value):
done

2020-11-02 13:30 UTC, shrimetta commented on py-utils/src/utils/kvstore/kvstore.py
> +class KvManager:
done

2020-11-02 13:30 UTC, shrimetta commented on py-utils/src/utils/kvstore/kvstore.py
> +    def create(self, key, value):
done

2020-11-02 13:31 UTC, shrimetta commented on py-utils/src/utils/kvstore/pillar.py
> +class PillarDB(KvStorage):
done

2020-11-02 13:39 UTC, ujjwalpl approved these changes

2020-11-02 13:40 UTC, merged