WIP: Iem server event message integrations changes
Seagate/cortx-utils pull request #702
Opened 2022-01-11 18:36 UTC by suryakumar1024

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
- Iem server fail to send and receive message since Event message api params are changed

# Design
-  Integrated Iem server with new event message api changes

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: NA
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: NA
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: N
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]: NA
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-01-12 11:12 UTC, rohit-k-dwivedi approved these changes
LGTM

2022-01-12 13:56 UTC, sachinpunadikar commented on py-utils/src/utils/iem_framework/iem_server.py
> +            print(cluster_conf)
remove this line

2022-01-12 13:56 UTC, sachinpunadikar requested changes
work on comment

2022-01-12 14:08 UTC, suryakumar1024 commented on py-utils/src/utils/iem_framework/iem_server.py
> +            print(cluster_conf)
Updated in recent patch

2022-01-12 14:20 UTC, sachinpunadikar approved these changes
+1

2022-01-13 04:32 UTC, selvakumaar5496 approved these changes

2022-01-13 05:08 UTC, merged