Added validation for lvm, luns , salt_connectivity and passwordless ssh
Seagate/cortx-utils pull request #71
Opened 2020-10-30 11:14 UTC by mazinamdar

Signed-off-by: mazinamdar <mazhar.inamdar@seagate.com>

Added few checks
1) passwordless ssh
   network passwordless user [nodes]

2) salt connectivity
   network salt_connectivity [nodes]

3) luns consistency (should be multiple of 16)
  storage luns_check  [nodes]

4) lvm are present
 storage lvms_check  [nodes]

2020-10-30 14:55 UTC, ujjwalpl requested changes

2020-10-30 14:55 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        elif v_type == "salt_connectivity":
Salt is not a OS network component. It should be designed separately. Refer to consul. It should be a similar one. 
If required (only if there are common code) a common class can be implemented between Consul and Salt.

2020-10-30 14:55 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        elif v_type == "passwordless":
Please add this spec to the wiki page.

2020-10-30 14:55 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
Please add a comment to list down all the v_types and args.

2020-10-30 14:55 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +        if v_type == "luns_check":
validation means check. Explicit qualification, i.e. "_check" is not required. 
$ validate storage luns a b c
$ validate storage lvm a b c

2020-11-02 05:21 UTC, mazinamdar commented on py-utils/src/utils/validator/v_network.py
> +        elif v_type == "salt_connectivity":
comment is addressed, created salt as separate class

2020-11-02 05:21 UTC, mazinamdar commented on py-utils/src/utils/validator/v_network.py
> +        elif v_type == "passwordless":
comment is addressed

2020-11-02 05:21 UTC, mazinamdar commented on py-utils/src/utils/validator/v_network.py
Done

2020-11-02 05:22 UTC, mazinamdar commented on py-utils/src/utils/validator/v_storage.py
> +        if v_type == "luns_check":
removed _check from both

2020-11-02 07:50 UTC, ujjwalpl requested changes

2020-11-02 07:50 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +            cmd = f"ssh {user}@{node} exit"
I tried to use this method however it hanged waiting for the input. We need to find a more reliable way to check. 

```
ujjwal@dev:validator(validator-framework-2)>ssh root@0 exit
The authenticity of host '0 (0.0.0.0)' can't be established.
ECDSA key fingerprint is SHA256:5alVuRjcNTZrkyi8ThfV1164DRvFIzXpTza+mNEJYuw.
ECDSA key fingerprint is MD5:e5:a5:11:8e:fb:66:f5:12:f0:96:61:f3:e3:a7:04:dc.
Are you sure you want to continue connecting (yes/no)? ^C
ujjwal@dev:validator(validator-framework-2)>
```
Correct method is to use the following command
```
ujjwal@dev:validator(validator-framework-2)>ssh -o PreferredAuthentications=publickey root@localhost /bin/true
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
ujjwal@dev:validator(validator-framework-2)>echo $?
255
ujjwal@dev:validator(validator-framework-2)>ssh -o PreferredAuthentications=publickey ujjwal@localhost /bin/true
/etc/bashrc
ujjwal@dev:validator(validator-framework-2)>echo $?
0
ujjwal@dev:validator(validator-framework-2)>
```

2020-11-02 07:54 UTC, ujjwalpl requested changes

2020-11-02 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_salt.py
> +        if v_type == "connectivity":
Please use the same v_type as the consul. I think, the purpose here is the same i.e. if consul or salt is accessible. Please correct me if that is not the case.  

$ validate salt service node1 node2 ...

2020-11-02 07:54 UTC, ujjwalpl commented on py-utils/test/validator/test_storage_validator.py
> +        self.assertRaises(VError, StorageV().validate, 'luns_check',
Did you run the tests ? _check is removed, I think

2020-11-02 08:09 UTC, mazinamdar commented on py-utils/src/utils/validator/v_network.py
> +            cmd = f"ssh {user}@{node} exit"
` [root@ssc-vm-c-1112 utils]# ssh -o PreferredAuthentications=publickey  root@ssc-vm-c-1002 /bin/true `
The authenticity of host 'ssc-vm-c-1002 (10.230.250.84)' can't be established.
RSA key fingerprint is SHA256:O2TOR/n0PfK41SX2SG2eR/OuFe4kiY77DLDw/ZD4OR8.
RSA key fingerprint is MD5:95:fb:68:8f:4c:b7:b3:b8:5f:30:85:63:ed:f7:46:d0.
Are you sure you want to continue connecting (yes/no)?

Above command is also asking for adding host to known found a way to handle that as well

``` ssh -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no  root@ssc-vm-c-1002 /bin/true  ```

2020-11-02 08:11 UTC, mazinamdar commented on py-utils/src/utils/validator/v_salt.py
> +        if v_type == "connectivity":
It checks for minions are connected or not , so kept v_type as connectivity.

2020-11-02 08:22 UTC, mazinamdar commented on py-utils/test/validator/test_storage_validator.py
> +        self.assertRaises(VError, StorageV().validate, 'luns_check',
I missed that , updated unit test and tested

2020-11-02 13:38 UTC, ujjwalpl requested changes

2020-11-02 13:38 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_salt.py
> +        if v_type == "connectivity":
connectivity is too generic and unrelated and does not give hints about minions. You need to ask yourself and answer becomes your key here. 

$ validate salt minions node1 node2 ...

2020-11-02 13:38 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +            run_result = cmd_proc.run()
This logic is not working on my machine. Did you test for both positive and negative cases ?

```
ujjwal@dev:process>./test_process.py ujjwal localhost
ssh -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no {user}@{node} /bin/true
(b'', b'ssh: Could not resolve hostname {node}: Name or service not known\r\n', 255)
error
ujjwal@dev:process>
ujjwal@dev:process>ssh -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no ujjwal@localhost /bin/true
ujjwal@dev:process>echo $?
0
ujjwal@dev:process>cat test_process.py
...
    user = sys.argv[1]
    node = sys.argv[2]
    cmd = "ssh -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no {user}@{node} /bin/true"
    cmd_proc = SimpleProcess(cmd)
    run_result = cmd_proc.run()
    print(cmd)
    print(run_result)
    if run_result[1] or run_result[2]:
        print('error')
```

2020-11-02 14:12 UTC, mazinamdar commented on py-utils/src/utils/validator/v_network.py
> +            run_result = cmd_proc.run()
I have tested both positive and negative , both are working , I think in above script f-string is missing at line cmd. please let me know if I missed anything else.

2020-11-02 15:07 UTC, mazinamdar commented on py-utils/src/utils/validator/v_salt.py
> +        if v_type == "connectivity":
comment is addressed

2020-11-02 18:46 UTC, ujjwalpl approved these changes

2020-11-03 04:54 UTC, ajaysrivas commented on py-utils/src/utils/validator/commands.py
> +        sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
The path is being appended in each class. It would be good to move this to Base class.
Why do we need to append this path? @shrimetta

2020-11-03 04:54 UTC, ajaysrivas commented on py-utils/src/utils/validator/v_storage.py
> +
General comment - we should return the output of command when validation fails. The output will be helpful in troubleshooting the problem.

2020-11-03 04:55 UTC, ypise approved these changes

2020-11-03 05:00 UTC, ypise reviewed
These are suggestions that would be good to have.

2020-11-03 05:03 UTC, ypise commented on py-utils/src/utils/validator/v_storage.py
> +
In addition to command output, it also helps if the executed command is provided so that reproduction of problem becomes easy.
If possible, please do add the command and the output (srdout + stderr) in case of failure.

2020-11-03 05:06 UTC, ypise commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Luns are not consistent {node}.")
Message improvement: 
"""
The query resulted in number of LUNs that are not as per desired configuration on node {node}. 
To troubleshoot this issue execute command: 'lsblk -S | grep sas'
"""

2020-11-03 05:07 UTC, ypise commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Luns are not consistent {node}.")
This is a tricky bit for a user to understand. Hence, we need to be more verbose with error.

2020-11-03 05:17 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +        sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
This is not required for all the classes. 
It is up to the command class to handover the request and call the business logic. 
But In general sys.path.append is not required. We can assume that cortx-utils is already in the path. 
Please remove sys.path from all the command classes.

2020-11-03 05:18 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +
Output + Error needs is being returned the exception when validation fails
@shrimetta Please validate this is the case at all the places.

2020-11-03 05:20 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_salt.py
> +            cmd = f"salt -t 5 {node} test.ping"
Please check if this command requires root privileges. If so, you will have to add the check and raise exception if its called with non root privileges.

2020-11-03 05:22 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Luns are not consistent {node}.")
Valid Point. We need to add more details about the reason / root cause of exception. 
@shrimetta Please check at all the places where exception is raised if we include 
1. Precise Error
2. Root Cause of the Error
3. Additional Information like output + error or Caller's recommendation e.g. 
     "Please check the volume is mounted"
     "Please ensure there is root privilege"
     "etc."

2020-11-03 09:27 UTC, mazinamdar commented on py-utils/src/utils/validator/commands.py
> +        sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
removed sys.path from  command class

2020-11-03 09:27 UTC, mazinamdar commented on py-utils/src/utils/validator/v_storage.py
> +
Added ouput + err_msg in VError

2020-11-03 09:28 UTC, mazinamdar commented on py-utils/src/utils/validator/v_storage.py
> +            if not res or (int(res) != len(nodes)):
comment is addressed

2020-11-03 09:29 UTC, mazinamdar commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Luns are not consistent {node}.")
Added output + err_msg for all when raising exception also added improved msg in case of luns

2020-11-03 09:30 UTC, mazinamdar commented on py-utils/src/utils/validator/v_salt.py
> +            cmd = f"salt -t 5 {node} test.ping"
For now allowed only root user to run this check.

2020-11-03 10:07 UTC, ujjwalpl requested changes

2020-11-03 10:07 UTC, ujjwalpl commented on py-utils/src/utils/validator/error.py
> +    def __init__(self, rc, desc, output=None, err_msg=None):
We should not personalize VError.  "desc" was originally meant for output and error both. The responsibility of adding output and/or error should be with the caller. This will generically work for all the cases i.e. case where we have only output or when we have output + error, or an error which does not have output or error.

Two ways to solve this. 
1. Caller does the job of integrating output + error, Example:

```
     rc, output, error = process.run(cmd) 
     raise VError(rc, "CMD %s failed. %s. %s" %(cmd, output, error))
     if cond: raise VError(rc, "Invalid command %s" %cmd)
     if cond: raise VError(rc, "Function Not Implemented")

```
2. Write a wrapper Exception class to handle Command output error. 

```
     class VCmdError(VError):
        def __init__(self, rc, cmd, output, error):
             desc = "Command %s failed. %s. %s." %(cmd, output, error)
             super(VError, self).__init__(desc)
             rc, output, error = process.run(cmd) 
             raise VError(rc, cmd, output, error)
```

2020-11-03 10:16 UTC, ujjwalpl requested changes

2020-11-03 10:16 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_salt.py
> +            res = "Root user is required to run salt minions check."
res = "validate_salt_minion: This interface requires root privileges."

2020-11-03 10:18 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Luns are not consistent {node}.")
Added more comments on the changes

2020-11-03 10:24 UTC, ajaysrivas approved these changes

2020-11-03 11:22 UTC, mazinamdar commented on py-utils/src/utils/validator/error.py
> +    def __init__(self, rc, desc, output=None, err_msg=None):
Used option 1 , caller's job to describe error

2020-11-03 11:22 UTC, mazinamdar commented on py-utils/src/utils/validator/v_salt.py
> +            res = "Root user is required to run salt minions check."
Added

2020-11-03 11:22 UTC, mazinamdar commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Luns are not consistent {node}.")
Done

2020-11-03 16:55 UTC, ujjwalpl requested changes

2020-11-03 16:55 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        """Check if IP/Hosts are reachable."""
We need to decide on the spec. Any reason you are including host here ? It gets complicated with host. You need to do a DNS lookup before ping else if host is not in the DNS it takes 10 seconds per host which is a very time consuming and adds to delay. Lets revert this change, design it properly and then bring the change which can work in positive / negative cases in aprx a second.

2020-11-03 17:06 UTC, ujjwalpl requested changes

2020-11-03 17:06 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        """Check if IP/Hosts are reachable."""
```
ujjwal@dev:validator(validator-framework-2)>time host -W 1 www1.google.com && ping -c 1 -W 1 www1.google.com
;; connection timed out; no servers could be reached

real	0m2.045s
user	0m0.008s
sys	0m0.006s
ujjwal@dev:validator(validator-framework-2)>time host -W 1 www.google.com && ping -c 1 -W 1 www.google.com
www.google.com has address 216.58.203.4
www.google.com has IPv6 address 2404:6800:4009:804::2004

real	0m0.109s
user	0m0.006s
sys	0m0.006s
```

2020-11-03 17:06 UTC, ypise approved these changes

2020-11-04 04:30 UTC, mazinamdar commented on py-utils/src/utils/validator/v_network.py
> +        """Check if IP/Hosts are reachable."""
reverted code for network connectivity for now , will raise another PR for this.

2020-11-04 05:32 UTC, ujjwalpl approved these changes

2020-11-04 05:32 UTC, merged