EOS-27349: MessageBus dynamic port from cluster conf file
Seagate/cortx-utils pull request #710
Opened 2022-01-16 17:26 UTC by suryakumar1024

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
-  Current MessageBus server listens on hard coded port 28300. Which need to be fixed.

# Design
-  Updated MessageBus Server code dynamically allocate the server port by reading the port number from cluster.conf file

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: N
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: NA
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: Y 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N] Y
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-01-17 04:32 UTC, selvakumaar5496 approved these changes

2022-01-17 05:03 UTC, ujjwalpl requested changes

2022-01-17 05:03 UTC, ujjwalpl commented on py-utils/src/utils/utils_server/utils_server.py
> +    def run_app(self, web, port=28300):
Utils server is base for many derived servers hence cant run on the same port. 
The default port should be part of the derived class, i.e. MessageServer.

2022-01-17 05:03 UTC, ujjwalpl requested changes

2022-01-17 05:03 UTC, ujjwalpl commented on py-utils/src/utils/utils_server/utils_server.py
> +    def __init__(self, message_server_endpoints, message_server_port):
Add the default port here. Its Message Server default port.

2022-01-17 11:26 UTC, suryakumar1024 commented on py-utils/src/utils/utils_server/utils_server.py
> +    def run_app(self, web, port=28300):
Addressed your comment in the recent patch.

2022-01-17 11:26 UTC, suryakumar1024 commented on py-utils/src/utils/utils_server/utils_server.py
> +    def __init__(self, message_server_endpoints, message_server_port):
Addressed your comment in the recent patch.

2022-01-18 10:06 UTC, sachinpunadikar approved these changes
+1

2022-01-18 10:11 UTC, rohit-k-dwivedi approved these changes

2022-01-18 10:13 UTC, vastradparayya approved these changes

2022-01-21 07:55 UTC, ujjwalpl approved these changes

2022-01-21 10:22 UTC, sachinpunadikar commented
test this please

2022-01-21 11:35 UTC, merged