Enhanced py-utils test_framework to generate test_report after tests execution.
Seagate/cortx-utils pull request #713
Opened 2022-01-19 11:49 UTC by veerendra-simha-garikipati

Signed-off-by: Veerendra Garikipati <veerendra.garikipati@seagate.com>

# Problem Statement
- Enhance py-utils test_framework to generate test_report after tests execution.

# Design
-  https://jts.seagate.com/browse/EOS-23188

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: N
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: N
- [ ] Confirm Testing was performed with installed RPM [Y/N]: Y

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: N
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]: 
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-01-19 11:52 UTC, veerendra-simha-garikipati commented
Sample test_report.html:
![image](https://user-images.githubusercontent.com/84907462/150124554-ac61ba1e-b856-45b8-bd8f-73f5360b1352.png)

2022-01-19 13:39 UTC, rohit-k-dwivedi approved these changes

2022-01-20 10:08 UTC, sachinpunadikar approved these changes
+1

2022-01-20 10:27 UTC, rahul-tripathi-git requested changes
Please use your best judgement to cater this comment.

2022-01-20 10:27 UTC, rahul-tripathi-git commented on py-utils/src/test_framework/generate_test_report.py
> +        duration = int(list(value.values())[0])
Is casting to list required? looks like an overhead. Please check.

2022-01-21 14:41 UTC, rahul-tripathi-git approved these changes
+1

2022-01-21 15:31 UTC, merged