WIP: Updated Iem and MessageBus server cortxconf usage removed
Seagate/cortx-utils pull request #718
Opened 2022-01-20 10:34 UTC by suryakumar1024

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>

# Problem Statement
- Since CortxConf class is no more in use, Need to update all the usage of this class all over the utils code.

# Design
-  Removed the usage in IEM server and MessageServer scripts

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-01-21 07:54 UTC, ujjwalpl requested changes

2022-01-21 07:54 UTC, ujjwalpl commented on py-utils/src/utils/iem_framework/iem_server.py
> +        message_bus_backend = Conf.get(MappedConf._conf_idx,\
MappedConf must not be used as class instance. Instantiate and keep object reference or use Conf class.

2022-01-21 15:21 UTC, rohit-k-dwivedi approved these changes
LGTM

2022-01-21 15:42 UTC, sachinpunadikar approved these changes
+1

2022-01-21 16:04 UTC, suryakumar1024 commented on py-utils/src/utils/iem_framework/iem_server.py
> +        message_bus_backend = Conf.get(MappedConf._conf_idx,\
Addressed your comment in recent patch.

2022-01-21 19:11 UTC, ujjwalpl approved these changes

2022-01-24 04:40 UTC, sachinpunadikar commented
test this please

2022-01-24 04:58 UTC, sachinpunadikar commented
retest this please

2022-01-24 07:12 UTC, merged