Add BMC validations
Seagate/cortx-utils pull request #72
Opened 2020-11-02 09:35 UTC by sanjognaik

- Added check for BMC accessibility
- Added check for Stonith confiduration using BMC IP, user and password
- Added support function check_output() in SimpleProcess class
- Added pillar_get() functionality.
- Added function to decrypt secret.

Signed-off-by: Sanjog Vikram Naik <sanjog.naik@seagate.com>

2020-11-04 05:39 UTC, ajaysrivas requested changes

2020-11-04 05:39 UTC, ajaysrivas commented on py-utils/src/utils/common.py
> +def get_cmd_error_msg(msg:str, cmd:str=None, result:list=None):
Please add description and why is this method required?

2020-11-04 05:39 UTC, ajaysrivas commented on py-utils/src/utils/decrypt_secret.py
> +def decrypt_secret(enc_key, secret):
There is already a class for executing salt command. You may not need it.

2020-11-04 05:39 UTC, ajaysrivas commented on py-utils/src/utils/pillar_get.py
> +class PillarGet():
There is already a class for Pillar command. This may not be required.

2020-11-04 05:39 UTC, ajaysrivas commented on py-utils/src/utils/validator/commands.py
> +        sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
Remove.  sys path append is not required.

2020-11-04 05:45 UTC, ujjwalpl requested changes

2020-11-04 05:45 UTC, ujjwalpl commented on py-utils/src/utils/common.py
> +def get_cmd_error_msg(msg:str, cmd:str=None, result:list=None):
Please avoid global functions in the code. We need to have proper class design and fit in the code where required.

2020-11-04 05:45 UTC, ujjwalpl commented on py-utils/src/utils/decrypt_secret.py
> +def decrypt_secret(enc_key, secret):
Same here. Please prepare a class design and have a design review before the code.

2020-11-04 05:45 UTC, ujjwalpl commented on py-utils/src/utils/pillar_get.py
> +class PillarGet():
Please refer to https://github.com/Seagate/cortx-utils/pull/70 for the example with class design

2020-11-04 05:45 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_bmc.py
> +            cmd, bmc_ip_get = PillarGet.get_pillar(f"cluster:{node}:bmc:ip")
Validation code should receive inputs and validates information based on the inputs. 
There should not be no direct coupling with pillar or any other DB for inputs.

2020-11-04 12:00 UTC, sanjognaik commented on py-utils/src/utils/common.py
> +def get_cmd_error_msg(msg:str, cmd:str=None, result:list=None):
Function and file removed.

2020-11-04 12:00 UTC, sanjognaik commented on py-utils/src/utils/decrypt_secret.py
> +def decrypt_secret(enc_key, secret):
Function and file removed.

2020-11-04 12:01 UTC, sanjognaik commented on py-utils/src/utils/validator/commands.py
> +        sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
Done.

2020-11-04 12:01 UTC, sanjognaik commented on py-utils/src/utils/common.py
> +def get_cmd_error_msg(msg:str, cmd:str=None, result:list=None):
Function and file removed.

2020-11-04 12:01 UTC, sanjognaik commented on py-utils/src/utils/decrypt_secret.py
> +def decrypt_secret(enc_key, secret):
Function and file removed.

2020-11-04 12:01 UTC, sanjognaik commented on py-utils/src/utils/pillar_get.py
> +class PillarGet():
Function and file removed.

2020-11-04 12:02 UTC, sanjognaik commented on py-utils/src/utils/validator/v_bmc.py
> +            cmd, bmc_ip_get = PillarGet.get_pillar(f"cluster:{node}:bmc:ip")
Updated this function.

2020-11-04 13:11 UTC, ujjwalpl requested changes

2020-11-04 13:11 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_bmc.py
> +    def ping_bmc(self, node):
_ping_bmc. This will be internal function. Only validate interfaces are exposed.

2020-11-04 13:18 UTC, sanjognaik commented on py-utils/src/utils/validator/v_bmc.py
> +    def ping_bmc(self, node):
Done

2020-11-04 13:53 UTC, ujjwalpl approved these changes

2020-11-04 15:25 UTC, ypise approved these changes

2020-11-05 05:21 UTC, ajaysrivas approved these changes

2020-11-05 05:24 UTC, merged