Change CORTX Constant for RGW
Seagate/cortx-utils pull request #723
Opened 2022-02-02 08:19 UTC by kailashyadav11

Signed-off-by: Ujjwal Lanjewar <ujjwal.lanjewar@seagate.com>

# Problem Statement
- s3 service related constants to be replaced by rgw instead

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-02-02 09:29 UTC, ujjwalpl requested changes

2022-02-02 09:29 UTC, ujjwalpl commented on py-utils/src/utils/cortx/const.py
> +    SERVICE_MOTR_FSM       = 'fsm'
This "fsm", can be moved to deprecated.

2022-02-02 09:59 UTC, kupranay approved these changes
looks good

2022-02-02 11:53 UTC, ArchanaLimaye approved these changes
No changes from HA perspective

2022-02-03 06:12 UTC, kailashyadav11 commented on py-utils/src/utils/cortx/const.py
> +    SERVICE_MOTR_FSM       = 'fsm'
moved it under deprecated

2022-02-03 08:55 UTC, ujjwalpl approved these changes

2022-02-03 10:02 UTC, sachinpunadikar commented
@kailashyadav11  please fill in PR template

2022-02-03 10:03 UTC, sachinpunadikar approved these changes
+1

2022-02-03 11:11 UTC, rahul-tripathi-git approved these changes
+1

2022-02-03 11:29 UTC, kailashyadav11 commented
> @kailashyadav11 please fill in PR template

@sachinpunadikar added basic details in the template please check.

2022-02-04 04:13 UTC, merged