F45i create iam user
Seagate/cortx-utils pull request #731
Opened 2022-02-15 08:51 UTC by avrnv

# Problem Statement
- F45I: IAM user CRUD operations with RGW.

# Design
-  Add low-level HTTP client to RGW, that asynchronously sends signed requests.

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-02-17 13:00 UTC, pawankumarsrivastava approved these changes

2022-02-18 04:30 UTC, Pranali04796 approved these changes

2022-02-18 05:18 UTC, rahul-tripathi-git requested changes
Please change the copyright year to 2022 in all the new files.

2022-02-18 05:18 UTC, rahul-tripathi-git commented on py-utils/src/utils/http/__init__.py
> +from .exceptions import HTTPClientException
Kindly use absolute imports.

2022-02-18 05:18 UTC, rahul-tripathi-git commented on py-utils/src/utils/http/client.py
> +from .exceptions import HTTPClientException
Use absolute imports.

2022-02-18 05:18 UTC, rahul-tripathi-git commented on py-utils/src/utils/rgwadmin/__init__.py
> +from .exceptions import RGWAdminClientException
Use Absolute imports.

2022-02-18 05:18 UTC, rahul-tripathi-git commented on py-utils/src/utils/rgwadmin/client.py
> +from .exceptions import RGWAdminClientException
Use absolute imports

2022-02-18 05:18 UTC, rahul-tripathi-git commented on py-utils/src/utils/http/__init__.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
Change the copyright year to 2022.

2022-02-18 05:18 UTC, rahul-tripathi-git commented on py-utils/src/utils/http/client.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
Change the copyright year to 2022.

2022-02-18 10:11 UTC, avrnv commented on py-utils/src/utils/http/__init__.py
> +from .exceptions import HTTPClientException
Done.

2022-02-18 10:11 UTC, avrnv commented on py-utils/src/utils/http/client.py
> +from .exceptions import HTTPClientException
Done.

2022-02-18 10:11 UTC, avrnv commented on py-utils/src/utils/rgwadmin/__init__.py
> +from .exceptions import RGWAdminClientException
Done.

2022-02-18 10:11 UTC, avrnv commented on py-utils/src/utils/rgwadmin/client.py
> +from .exceptions import RGWAdminClientException
Done.

2022-02-18 10:12 UTC, avrnv commented on py-utils/src/utils/http/__init__.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
Done.

2022-02-18 10:12 UTC, avrnv commented on py-utils/src/utils/http/client.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
Done.

2022-02-18 10:30 UTC, rahul-tripathi-git approved these changes
+1

2022-02-18 10:31 UTC, merged