Cortx 27956 : Implement Action status update framework
Seagate/cortx-utils pull request #735
Opened 2022-02-17 09:31 UTC by gauri-bhosale

# Problem Statement
-  Add "Health Status Event Message Schema" with the default values.

# Design
-  Create Event Message Schema Class with initialize default value.
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/891781277/Action+Status+Update+LLD?focusedCommentId=909705441#Health-Status-Event-Message-Schema

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]:  Y
-  Confirm All CODACY errors are resolved [Y/N]:  Y

# Review Checklist 
  Before posting the PR please ensure
- [X] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: N
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [X] Jira is updated
- [X] Check if the description is clear and explained. 
- [ Y] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [X] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [X] Changes done to WIKI / Confluence page

#Testing :
Calling sample code which create event object and print default payload and header 
and shows data after set function call : 
 python3 event.py

 default event header : event.header
{'version': '1.0', 'timestamp': '1645160753', 'event_id': '1645160753_a4d38c5bd0b949469808178ec8422705'}

 Default event payload : event.payload
{'source': None, 'cluster_id': None, 'site_id': None, 'rack_id': None, 'storageset_id': None, 'node_id': None, 'resource_type': None, 'resource_id': None, 'event_type': None, 'specific_info': {}}

payload from producers
{'rack_id': 5, 'node_id': 6, 'data': '1'}

After set Payload =
{'source': None, 'cluster_id': None, 'site_id': None, 'rack_id': 5, 'storageset_id': None, 'node_id': 6, 'resource_type': None, 'resource_id': None, 'event_type': None, 'specific_info': {'data': '1'}}

 HEADER =
{'version': '1.0', 'timestamp': '1645160753', 'event_id': '1645160753_a4d38c5bd0b949469808178ec8422705'}

2022-02-17 09:37 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-02-18 04:46 UTC, Madhura-08 commented on py-utils/src/utils/health/event.py
> +    def set_or_update_payload(self, _input):
From below code, I can see that _input is a dictionary. Please define type here. and please give one example of such input.

2022-02-18 04:47 UTC, Madhura-08 commented on py-utils/src/utils/health/event.py
> +        for key in _input.keys():
Just iterating over keys?
How can we assign value then?

2022-02-18 04:48 UTC, Madhura-08 commented on py-utils/src/utils/health/event.py
> +            else:
specific_info is also a part of payload. Right?
In __init__(), I can see that. So, how it will go to else part. Sorry, but I didn't get that!

2022-02-18 05:55 UTC, indrajitzagade commented on py-utils/src/utils/health/event.py
> +    def set_or_update_payload(self, _input):
yes

2022-02-18 05:56 UTC, indrajitzagade commented on py-utils/src/utils/health/event.py
> +        for key in _input.keys():
Also, we need to be sure that the expected keys are there in the passed dictionary.

2022-02-18 09:40 UTC, indrajitzagade commented on py-utils/src/utils/health/const.py
> +    RESOURCE_STATUS = "event_type"
*RESOURCE_STATUS = "resource_status"

2022-02-18 09:42 UTC, indrajitzagade commented on py-utils/src/utils/health/event.py
> +        self.header = {}
The new message schema starts with "event" at root, I do not see that here.

2022-02-18 09:43 UTC, indrajitzagade commented on py-utils/src/utils/health/event.py
> +            "_" + str(uuid.uuid4().hex)
Does adding '_' helps in some way? If not, lets remove it.

2022-02-18 13:30 UTC, mariyappanp commented on py-utils/src/utils/health/const.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Please correct the year.

2022-02-18 13:31 UTC, mariyappanp commented on py-utils/src/utils/health/event.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
Please correct the year.

2022-02-20 16:54 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +    def set_or_update_payload(self, _input):
added example for payload input on set_payload function also rename function name to set_payload.

2022-02-20 16:55 UTC, gauri-bhosale commented on py-utils/src/utils/health/const.py
> +    RESOURCE_STATUS = "event_type"
fixed.

2022-02-20 16:56 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +        self.header = {}
added event dict, previously thought its event.payload for Event object 
now changed to event.event[payload]

2022-02-20 16:56 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +            "_" + str(uuid.uuid4().hex)
removed '_'

2022-02-20 16:56 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
fixed.

2022-02-20 17:03 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +            else:
@Madhura-08  @indrajitzagade 
As per LLD : 
This is a dictionary of key/value pairs specific to the resource type. The producer could add the kay/value pairs as agreed between the producer and HA e.g. “generation_id” sent by k8s monitor.

My understanding is if producer sends in _input generation_id but this key is not present in payload so it will add in specific_info dict.

Is producer will sends 'generation_id' in specific_info dict ? 

Please correct me if I am wrong.

2022-02-20 17:11 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +        for key in _input.keys():
getting value by using _input[key] in below lines.

2022-02-20 17:12 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +        for key in _input.keys():
Not all fields in this new schema are applicable to all the senders (producers) of this message, not applicable fields could be kept “None”.

Should I check all keys are present or not in passed dictionary ?

2022-02-21 03:39 UTC, rahul-tripathi-git requested changes

2022-02-21 03:39 UTC, rahul-tripathi-git commented on py-utils/src/utils/health/event.py
> +from const import HEALTH_EVENT_ATTRIBUTES, HEALTH_EVENT_HEADER, \
Use absolute imports

2022-02-21 03:39 UTC, rahul-tripathi-git commented on py-utils/src/utils/health/const.py
> +    SPECIFIC_INFO = "specific_info"
Please use single quotes for single word strings.
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/349175953/Cortx+Foundation+Python+Coding+Guidelines#Quotes%2C-Single-or-Double%3F%3F

2022-02-21 05:04 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +from const import HEALTH_EVENT_ATTRIBUTES, HEALTH_EVENT_HEADER, \
fixed.

2022-02-21 05:05 UTC, gauri-bhosale commented on py-utils/src/utils/health/const.py
> +    SPECIFIC_INFO = "specific_info"
Fixed.

2022-02-21 05:11 UTC, ujjwalpl requested changes

2022-02-21 05:11 UTC, ujjwalpl commented on py-utils/src/utils/health/const.py
> +    HA = 'ha'
We need to avoid hard coding of any of the things related to CORTX in utils code. 
Think if this module is used in some other project, it should just work seamlessly without a change. 
Think of this as a library. Move component / CORTX specific code to respective component source.

2022-02-21 05:18 UTC, ujjwalpl requested changes

2022-02-21 05:18 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +        payload = {}
Current payload is limited to kv. Ideally if should be possible for someone to send json / yaml etc. 

Please refer to utils/kv_store/kv_payload class and try to use that. Advantage is... 
it has capability to represent hierarchical information than just plain kv. 
Example, you can say set("a>b>c1=v1") and set ("a>b>c2=v2") and convert payload to json of yaml any time. 
You can use it just like dictionary without any change in your code here. 

Example: 
```
self._payload = KvPayload()
self._payload[HEALTH_EVENT_ATTRIBUTES.SOURCE] = None
...
```

2022-02-21 05:56 UTC, Madhura-08 reviewed
Please provide the details of how did you call set_payload()?
What arguments you have given ? 
Also, if update is required, how it will happen? Please provide example of update here.

2022-02-21 06:03 UTC, Madhura-08 commented on py-utils/src/utils/health/event.py
> +        for key in _input.keys():
And also, user needs that dictionary. We need to return this!

2022-02-21 06:19 UTC, Madhura-08 commented on py-utils/src/utils/health/event.py
> +                self.event[HEALTH_EVENT_PAYLOAD][key] = _input[key]
Now, self.event is already initialized with some values like
event = { 'event': 
                 {
                   'header': {}, 
                   'payload': {
                      'specific_info': {'generation_id': <some value>}
                   }
                }
              }
              
Now, if I request to update with _input as {'specific_info': {'is_status': True}}. So, with this specific_info of payload will be replaced {'is_status': True} and "generation_id" will be lost. Right?
We don't want this. Can you please recheck this again?

2022-02-21 09:10 UTC, indrajitzagade commented on py-utils/src/utils/health/const.py
> +    HA = 'ha'
Thanks @ujjwalpl.
@gauri-bhosale Lets move this class to HA component.

2022-02-21 09:15 UTC, indrajitzagade commented on py-utils/src/utils/health/event.py
> +        payload = {}
@ujjwalpl For our use-case we need to send just plain kv. Using KvPayload class and sending it as dictionary over message bus looks like the following:

{'event': {'header': {'version': '1.0', 'timestamp': '1645434342', 'event_id': '16454343424aa3fb75e95b41cd9937cb16a49cc485'}, 'payload': {'_data': {'source': None, 'cluster_id': None, 'site_id': None, 'rack_id': 5, 'storageset_id': None, 'node_id': 6, 'resource_type': None, 'resource_id': None, 'resource_status': None, 'specific_info': {'data': '1'}}, '_delim': '>', '_keys': ['source', 'cluster_id', 'site_id', 'rack_id', 'storageset_id', 'node_id', 'resource_type', 'resource_id', 'resource_status', 'specific_info']}}}

This adds an additional depth e.g. _data: and additional data is sent e.g. _delim and _keys.
Hence, can we keep it simple kv for this case?

2022-02-21 09:31 UTC, Madhura-08 commented on py-utils/src/utils/health/event.py
> +    def set_or_update_payload(self, _input):
Thanks!

2022-02-21 10:40 UTC, ujjwalpl requested changes

2022-02-21 10:40 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +    def set_payload(self, _input):
Please specify type
`def set_payload(self, _input: KvPayload):`

2022-02-21 10:40 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +        for key in _input.keys():
`for key in _input.get_keys():`

2022-02-21 10:40 UTC, ujjwalpl commented on py-utils/src/utils/health/const.py
> +class HEALTH_EVENT_ATTRIBUTES:
Naming convention for the class Canonical. Here is how this needs to be written 
Example: https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/utils/cortx/const.py
```
class HealthAttr(Enum): 
    VERSION = 'version'
    ...

from cortx.utils.health.const import  HealthAttr

2022-02-21 10:40 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +class Event:
Why dont we derive Event itself from KyPayload Something like this..

```
class Event(KvPayload):
    def __init__(self):
        self._attrs = KvPayload()
        self._attrs.set(f'header>{HealthAttr.VERSION}', VERSION)
        self._attrs.set(f'header>{HealthAttr.TIMESTAMP}', ...)

       for key in a, b, c, d:
                self._attrs.set(f'header>{key}', None)

    def set_payload(self, payload):
        for key in payload.get_keys():
            self._attrs.set(f'payload>{key}', payload.get(key))
```

2022-02-21 10:40 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +    def set_payload(self, _input):
We also need to add another interface 
```
    def get_payload(self):
        return self._attrs.get('payload')
```

2022-02-22 04:34 UTC, ArchanaLimaye commented on py-utils/src/utils/health/event.py
> +            if key in list(self.event[HEALTH_EVENT_PAYLOAD].keys()):
We should log a warning / error if key is not in list of keys.

2022-02-24 16:34 UTC, gauri-bhosale commented
Created New PR : https://github.com/Seagate/cortx-utils/pull/742
as this PR DOC issue not verified commits.
Addresses all comments in new PR.

2022-02-24 16:34 UTC, closed without merging