CORTX-28870: Adding the allowable list for Alex scan
Seagate/cortx-utils pull request #736
Opened 2022-02-18 14:47 UTC by venkuppu-chn

Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>

# Problem Statement
Alex scan generate false positive 

# Design
We have added some allowable list to ignore the false positives.

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [x] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-02-21 04:28 UTC, rahul-tripathi-git requested changes

2022-02-21 04:28 UTC, rahul-tripathi-git commented on .alexrc
> +  "allow": ["execute", "host-hostess", "remains", "reject", "traps", "invalid", "period", "invalid", "execution", "simple", "failure"]
Invalid is twice in this list. Please check.

2022-03-03 10:01 UTC, venkuppu-chn commented on .alexrc
> +  "allow": ["execute", "host-hostess", "remains", "reject", "traps", "invalid", "period", "invalid", "execution", "simple", "failure"]
Addressed. Done.

2022-03-04 09:11 UTC, rahul-tripathi-git approved these changes

2022-03-08 04:58 UTC, selvakumaar5496 approved these changes

2022-03-08 05:47 UTC, ajaysrivas commented
Merging in absence of code owners on request of @rahul-tripathi-git

2022-03-08 05:47 UTC, merged