F45I: Rename RGWAdminClient to S3SignedClient
Seagate/cortx-utils pull request #738
Opened 2022-02-21 14:51 UTC by avrnv

# Problem Statement
- As per discussion with Ujjwal, references to RGW are omitted for the signed S3 client.

# Design
- Rename RGWAdminClient to S3SignedClient

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-02-24 06:36 UTC, pawankumarsrivastava approved these changes

2022-02-28 11:07 UTC, rahul-tripathi-git approved these changes
+1

2022-02-28 11:07 UTC, rahul-tripathi-git approved these changes
+1

2022-02-28 11:12 UTC, ujjwalpl requested changes

2022-02-28 11:12 UTC, ujjwalpl commented on py-utils/src/utils/s3/client.py
> +class S3SignedClient(HTTPClient):
Can we make it simple "S3Client". Signed is kind of implicit. 

Also, please rename HTTPClient to HttpClient as per the canonical naming.

2022-02-28 11:16 UTC, rahul-tripathi-git requested changes
Kindly fix above comments.

2022-03-02 11:54 UTC, ujjwalpl approved these changes

2022-03-02 11:59 UTC, rahul-tripathi-git approved these changes
+1

2022-03-02 12:00 UTC, merged