Implement validator for elasticsearch
Seagate/cortx-utils pull request #74
Opened 2020-11-02 14:18 UTC by shrimetta

**Problem Statement**
Validator for elasticsearch service

**Solution Overview**
Implemented validator for elasticsearch service

Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>

2020-11-02 14:54 UTC, ujjwalpl requested changes

2020-11-02 14:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_elasticsearch.py
> +class ElasticsearchV:
This class implementation look similar to consul. OO recommends reuse. This is the time. 

1. Define service.py with ...

class Service: 
    def validate()
        raise ...

class HttpService(Service):
     def validate(v_type, host, port)
        move the logic here.

2. Derive consul and elastic search from this class
    class ElasticSearchV:(HttpService):
         
    class ConsulV()

2020-11-03 03:46 UTC, ajay-paratmandali approved these changes

2020-11-03 09:58 UTC, ypise reviewed
https://github.com/Seagate/cortx-utils/pull/74/files#diff-1a74910433ffc3078d7a90a37bdc39e407805a3efcd191fa18c9be6cd8293fdaR46

Could a static method refer to instance variable?

2020-11-03 10:33 UTC, ypise commented on py-utils/src/utils/validator/v_elasticsearch.py
> +                errno.EINVAL, "Action parameter %s not supported" % v_type)
Use f string instead of old styled string concatenation.

2020-11-03 10:33 UTC, ypise commented on py-utils/src/utils/validator/v_elasticsearch.py
> +            raise VError(errno.EINVAL, "Insufficient parameters. %s" % args)
Use f string instead of old styled string concatenation.

2020-11-04 07:47 UTC, shrimetta commented
Closing this to fix merge conflicts.

2020-11-04 07:47 UTC, closed without merging