CORTX-29052: fix: num_keys are missing for list/array type values in cluster.conf
Seagate/cortx-utils pull request #741
Opened 2022-02-24 09:41 UTC by kailashyadav11

# Problem Statement
- Missing num_data & num_metadata keys in cluster.conf
      cvg:
      - devices:
          data:
          - /dev/sdd
          - /dev/sde
          metadata:
          - /dev/sdc
        name: cvg-01
        type: ios
Expected num keys for data & metadata (wherever applicable)

      cvg:
      - devices:
          data:
          num_data: 2
          - /dev/sdd
          - /dev/sde
          metadata:
          num_metadata: 1
          - /dev/sdc
        name: cvg-01
        type: ios

# Design
-  https://jts.seagate.com/browse/CORTX-29052

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-02-24 10:51 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2022-02-24 13:34 UTC, ujjwalpl requested changes

2022-02-24 13:34 UTC, ujjwalpl commented on py-utils/test/conf_store/test_conf_store.py
> +        """Test Confstore Add Num keys to KV store"""
test should be written in self sufficient manner so that if only this test is run, it would work. 
Please confirm if this is the case.

2022-02-24 13:44 UTC, kailashyadav11 commented on py-utils/test/conf_store/test_conf_store.py
> +        """Test Confstore Add Num keys to KV store"""
[root@ssc-vm-g4-rhev4-0483 conf_store]# python3 -m unittest test_conf_store.TestConfStore.test_conf_store_add_num_keys -v
test_conf_store_add_num_keys (test_conf_store.TestConfStore)
Test Confstore Add Num keys to KV store ... ok

----------------------------------------------------------------------
Ran 1 test in 0.140s

OK
[root@ssc-vm-g4-rhev4-0483 conf_store]#

2022-02-24 16:27 UTC, kailashyadav11 commented on py-utils/test/conf_store/test_conf_store.py
> +        """Test Confstore Add Num keys to KV store"""
This testcase can be called  in isolation and it is self sufficient, above is a sample run.

2022-02-25 03:38 UTC, ujjwalpl approved these changes

2022-02-25 06:44 UTC, nitin-seagate approved these changes
LGTM

2022-02-25 08:44 UTC, rahul-tripathi-git commented
Hi @kailashyadav11 
Please fix the codacy issues.

2022-02-25 09:29 UTC, kailashyadav11 commented
> Hi @kailashyadav11 Please fix the codacy issues.

done

2022-02-25 14:59 UTC, merged