CORTX-28915 : Add attributes of Health Event creation in cortx-utils
Seagate/cortx-utils pull request #742
Opened 2022-02-24 16:29 UTC by gauri-bhosale

Add constants for Health Event creation.
Create Event class for event object data which contain all health event schema,
and set payload.

Signed-off-by: gauri.bhosale <gauri.bhosale@seagate.com>

# Problem Statement
Add "Health Status Event Message Schema" with the default values.

# Design
 - Create Event Message Schema Class with initialize default value.
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/891781277/Action+Status+Update+LLD?focusedCommentId=909705441#Health-Status-Event-Message-Schema
# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y 
-  Confirm All CODACY errors are resolved [Y/N]:  Y

# Testing 
Calling sample code which create event object and print default payload and header
and shows data after set function call :
python3 event.py

default event header : event.header
{'version': '1.0', 'timestamp': '1645160753', 'event_id': '1645160753_a4d38c5bd0b949469808178ec8422705'}

Default event payload : event.payload
{'source': None, 'cluster_id': None, 'site_id': None, 'rack_id': None, 'storageset_id': None, 'node_id': None, 'resource_type': None, 'resource_id': None, 'event_type': None, 'specific_info': {}}

payload from producers
{'rack_id': 5, 'node_id': 6, 'data': '1'}

self.ret_dict() : 
{'event': {'header': {'version': '1.0', 'timestamp': '1645720109', 'event_id': '1645720109ee6048a79a1f4db7b5940f45feabcb52'}, 'payload': {'source': 1, 'cluster_id': None, 'site_id': None, 'rack_id': 4, 'storageset_id': None, 'node_id': None, 'resource_type': None, 'resource_status': None, 'specific_info': {'data': 1}}}}

# Review Checklist 
  Before posting the PR please ensure
- [X] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]:  N
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]: N
- [X] Jira is updated
- [X ] Check if the description is clear and explained. 
- [ X] Check Acceptance Criterion is defined. 

# Documentation
- [X ] Changes done to WIKI / Confluence page

2022-02-24 16:37 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-02-25 06:25 UTC, ujjwalpl requested changes

2022-02-25 06:25 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +    def ret_dict(self):
Call it get_payload(). Unit of IO for set and get should be same.

2022-02-25 06:25 UTC, ujjwalpl requested changes

2022-02-25 06:25 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +        for key in payload.keys():
Input is KvPayload hence kvpayload interfaces should be used.

2022-02-28 12:44 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +        event = KvPayload(delim='.')
fixed.

2022-02-28 12:45 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +    def ret_dict(self):
add get_event and get_payload function. get_event is for to get all header and payload data in one place. Let me know your thought on that @ujjwalpl

2022-02-28 12:45 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +        for key in payload.keys():
fixed.

2022-02-28 12:48 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +        self.set(f'payload>{HealthAttr.SPECIFIC_INFO.value}', {})
added {} value in payload>specific_info key, tried to create KvPayload object instead of dict for specific_info key but then set method needs more loop to set inside nested keys value. let me your thought on this . @ujjwalpl jjwalpl  ?

2022-02-28 12:48 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +    def get_event(self):
This function is required to get header and payload data in one place output.

2022-02-28 14:12 UTC, ujjwalpl requested changes

2022-02-28 14:12 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +        self.set(f'payload>{HealthAttr.SPECIFIC_INFO.value}', {})
Nope. This is KvPayload that means its only Key and Value both are strings. You can not have {} as the value ideally

2022-02-28 14:12 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +            self.set(f'payload>{key.value}', None)
Do you mean header ? Attr is part of Header.

`self.set(f'header>{key.value}', None)`

2022-02-28 14:12 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +    def __init__(self):
Better to optionally take payload in the argument here
```
def __init__(self, payload=KvPayload()): 
    ....
    ....
    for key in payload.get_keys():
        self.set(f'payload>{key}', payload.get(key))
```

2022-02-28 14:12 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +        now = str(int(time.time()))
Why to conver to int ? You should write this as 
`now = str((time.time())`

2022-02-28 14:12 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +    def get_event(self):
There is no need of this function. Here is how caller needs to use this
```
e = Event(my_payload)
event_in_str_format = e.json()
```
This will work as_is because Event class derives from KvPayload. No need to wrap

2022-02-28 17:29 UTC, ujjwalpl requested changes

2022-02-28 17:29 UTC, ujjwalpl commented on py-utils/src/utils/health/const.py
> +#!/usr/bin/python3.6
change the folder name to 'event_framework'. UTILS is all about generic framework. Name should suggest this so that more event framework (other than health) can be added.

2022-02-28 17:29 UTC, ujjwalpl commented on py-utils/src/utils/health/event.py
> +#!/usr/bin/python3.6
Add test code in test folder

2022-03-01 14:05 UTC, gauri-bhosale commented
created New PR as design changes 
https://github.com/Seagate/cortx-utils/pull/747
closing this PR.

2022-03-01 17:21 UTC, ujjwalpl approved these changes

2022-03-02 04:25 UTC, indrajitzagade approved these changes

2022-03-02 04:27 UTC, indrajitzagade commented
@gauri-bhosale Please update the PR template and fix the failing checks.

2022-03-02 06:29 UTC, mukul-seagate11 commented
ok to test

2022-03-06 19:56 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +    def ret_dict(self):
Fixed, no need seperate function, KvPayload provide attribute 'json' to get object data.

2022-03-06 19:57 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +        self.set(f'payload>{HealthAttr.SPECIFIC_INFO.value}', {})
fixed, created seperate function for set_specific_info.

2022-03-06 19:57 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +    def get_event(self):
Fixed.

2022-03-06 19:57 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +            self.set(f'payload>{key.value}', None)
Done.

2022-03-06 19:57 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +    def __init__(self):
Done.

2022-03-06 19:58 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +        now = str(int(time.time()))
Fixed.

2022-03-06 19:58 UTC, gauri-bhosale commented on py-utils/src/utils/health/const.py
> +#!/usr/bin/python3.6
Done.

2022-03-06 19:58 UTC, gauri-bhosale commented on py-utils/src/utils/health/event.py
> +#!/usr/bin/python3.6
added test file.

2022-03-07 04:50 UTC, rahul-tripathi-git approved these changes

2022-03-07 07:41 UTC, ajaysrivas commented
Merging it on @NeeravChoudhari request as code owners are not in office.
There is a low severity issue related to docstring which is known issue.

2022-03-07 07:41 UTC, merged