WIP: CORTX-29024: Disable left shift of K:V pairs when lower indexes are deleted in a l…
Seagate/cortx-utils pull request #746
Opened 2022-03-01 10:55 UTC by suryakumar1024

…ist/array

# Problem Statement
- Existing conf store delete will do left shift k,v if any lower indexes are deleted. which makes the indexes to be a random and less confident for the external component to fetch data based on the index.

# Design
-  This patch will remove the left shift approach by placing none as value if any lower indexes got deleted.
- The last index of any list will be deleted (We don't add any none here ) if user calls delete explicitly 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-03-03 12:34 UTC, selvakumaar5496 approved these changes

2022-03-03 12:53 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_store.py
> +        return Conf._conf.delete(index, key)
Why is saving back to source file disabled?

Or can we add a flag for this, to let the user select if he wish to make the delete permanent?
CC: @ujjwalpl

2022-03-03 12:53 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_store.py
> -        Conf.save(index)
same goes for here.

2022-03-04 04:53 UTC, rahul-tripathi-git commented
Hi @suryakumar1024 
Patch looks good. Please ass a few test cases including the corner cases.

2022-03-04 05:09 UTC, rohit-k-dwivedi commented on py-utils/src/utils/kv_store/kv_payload.py
> +                if index == len(data[k[0]]) - 1:
any test addition or previous change required with these change?

2022-03-04 07:44 UTC, ujjwalpl approved these changes

2022-03-04 12:26 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_payload.py
> +                if index == len(data[k[0]]) - 1:
Added new test cases.

2022-03-04 12:26 UTC, suryakumar1024 commented on py-utils/src/utils/kv_store/kv_payload.py
> +                if index == len(data[k[0]]) - 1:
No changes required for previous test cases

2022-03-04 12:48 UTC, rohit-k-dwivedi approved these changes

2022-03-07 16:08 UTC, rahul-tripathi-git requested changes

2022-03-07 16:08 UTC, rahul-tripathi-git commented on py-utils/test/kv_store/test_kv_store.py
> +            [['1', '2', '3', '4']])
Please set it one by one .
Conf.set(str, str)

2022-03-08 05:32 UTC, suryakumar1024 commented on py-utils/test/kv_store/test_kv_store.py
> +            [['1', '2', '3', '4']])
Updated test cases.

2022-03-08 05:37 UTC, rahul-tripathi-git commented on py-utils/test/kv_store/test_kv_store.py
> +        result_list = TestStore.loaded_json[0].get(['bridge>end_name_list'])
Do not get a list .This functionality might get removed in near future.

2022-03-08 05:47 UTC, suryakumar1024 commented on py-utils/test/kv_store/test_kv_store.py
> +        result_list = TestStore.loaded_json[0].get(['bridge>end_name_list'])
Updated test cases

2022-03-08 06:35 UTC, rahul-tripathi-git approved these changes
+1

2022-03-08 06:35 UTC, merged