CORTX-23443: adding retry decorator in consul confstore
Seagate/cortx-utils pull request #753
Opened 2022-03-07 06:40 UTC by rahul-tripathi-git

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>

# Problem Statement
- Consul based confstore was getting failed incase of some network issues, with HTTPException or ConsulException etc. Hence a retry logic is added with default 5 retries every time it fails.

# Design
-  Added a common decorator 'retry' in common.common module, It can be used wherever retry decorator is needed.

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-03-07 08:43 UTC, ujjwalpl requested changes

2022-03-07 08:43 UTC, ujjwalpl commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    @retry((ConsulException, HttpError, RequestException))
JSon Implementation should not refer to Consul at all. This is clear violation of the design principle. .

2022-03-07 09:06 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    @retry((ConsulException, HttpError, RequestException))
Hi @ujjwalpl 
This change is just for ConsulKV payload and not JSON implementation.

2022-03-07 15:31 UTC, ujjwalpl requested changes

2022-03-07 15:31 UTC, ujjwalpl commented on py-utils/src/utils/common/common.py
> +def retry(ExceptionToCheck, tries=4, delay=3, backoff=2):
1. Lets avoid global functions. 
2. Also, let caller decide the retry values. 
3. Current delay pattern would be 3s, 6s, 12s, 24s. If system is ready in say 10s, then you would wait for 21s.
    Normally delay needs to be smaller and retry count needs to be bigger, e.g. retries=6, delay=1, backoff=2. 
    Delay pattern would be 1, 2, 4, 8, 16, 32s. If system is ready 10s, then we would wait for 15s.

2022-03-21 07:19 UTC, selvakumaar5496 commented on py-utils/src/utils/common/common.py
> +                def wrap(*x,**y):
space after comma

2022-03-21 07:19 UTC, selvakumaar5496 commented on py-utils/src/utils/common/common.py
> +                            return func(*x,**y)
space after comma

2022-03-21 07:19 UTC, selvakumaar5496 commented on py-utils/src/utils/common/common.py
> +                    return func(*x,**y)
space after comma

2022-03-21 07:20 UTC, selvakumaar5496 commented on py-utils/src/utils/common/common.py
> +            raise UtilsError(errno.EINVAL, "Invalid arguments passed to Retry decorator", '')
why do we have hardcoded kwargs?

2022-03-21 07:22 UTC, rohit-k-dwivedi commented on py-utils/src/utils/common/common.py
> +                            mtries -= 1
mtries and mdelay can be renames to better pronounceable variables, I guess m here stands for max?
max_tries and max_delay

2022-03-21 07:41 UTC, suryakumar1024 commented on py-utils/src/utils/common/common.py
> +                            mtries -= 1
@rohit-k-dwivedi good suggestion in that case

2022-03-21 08:38 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +                def wrap(*x,**y):
Done

2022-03-21 08:38 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +                            return func(*x,**y)
Done

2022-03-21 08:38 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +                    return func(*x,**y)
Done

2022-03-21 08:39 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +            raise UtilsError(errno.EINVAL, "Invalid arguments passed to Retry decorator", '')
We have hardcoded kwargs to set default values,

2022-03-21 08:39 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +                            mtries -= 1
Done

2022-03-21 08:42 UTC, rohit-k-dwivedi commented on py-utils/src/utils/common/common.py
> +                            mtries -= 1
please take care of *x and **y too.

2022-03-21 12:11 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +                            mtries -= 1
replaced it with *args and **kwargs

2022-03-21 20:21 UTC, rahul-tripathi-git commented
Codacy issue mentioned is wrong, ConsulException is imported in line 21 of py-utils/src/utils/kv_store/kv_store_collection.py.

2022-03-22 04:05 UTC, ujjwalpl requested changes

2022-03-22 04:05 UTC, ujjwalpl commented on py-utils/src/utils/common/common.py
> +                    return func(*args,**kwargs)
`return func(*args, **kwargs)`

2022-03-22 04:05 UTC, ujjwalpl commented on py-utils/src/utils/common/common.py
> +class Retries:
Few suggestions on the names...
1. ExponentialBackoff 
2. RetryBackoff
3. RetryCount

2022-03-22 04:21 UTC, selvakumaar5496 approved these changes

2022-03-22 04:31 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +                    time.sleep(max_delay)
Done.

2022-03-22 04:39 UTC, rahul-tripathi-git commented on py-utils/src/utils/kv_store/kv_store_collection.py
> +    @Retries(exception=(ConsulException, HttpError, RequestException), tries=4, delay=1, backoff=2)
Done

2022-03-22 04:39 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +                    return func(*args,**kwargs)
Done

2022-03-22 05:01 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +class Retries:
Done. Renamed to ExponentialBackoff.

2022-03-22 05:05 UTC, ujjwalpl approved these changes

2022-03-22 05:20 UTC, rahul-tripathi-git commented on py-utils/src/utils/common/common.py
> +                    time.sleep(max_delay)
Added a cap argument.
modified the sleep logis as -> sleep = min( cap, delay*backoff)

2022-03-22 05:23 UTC, merged

2022-04-19 07:09 UTC, cdeshmukh commented on py-utils/src/utils/common/common.py
> +        delay (int): 1      initiall delay (in seconds) between retries.
typo initiall -> initial

2022-04-19 07:12 UTC, cdeshmukh commented on py-utils/src/utils/common/common.py
> +class ExponentialBackoff:
This is interesting and unique. 
However latency for all these calls would change, these should be communicated to teams now