CORTX-28033: migrate unsupported features from ElasticSearch to Consul
Seagate/cortx-utils pull request #761
Opened 2022-03-14 09:21 UTC by avrnv

Signed-off-by: Alexander Voronov <alexander.voronov@seagate.com>

# Problem Statement
- [CORTX-28033](https://jts.seagate.com/browse/CORTX-28033): Implement unsupported service feature for CSM

# Design
-  As a first step for CORTX-28033 it's decided to migrate the current implementation of unsupported features from ElasticSearch to Consul KVS.

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing 
- [ ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [ ] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [ ] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-03-17 06:33 UTC, soniyamoholkar approved these changes

2022-03-17 09:51 UTC, rahul-tripathi-git approved these changes
Looks good to me, syntax wise. Can someone from relevant team review approve this PR?

2022-03-21 06:33 UTC, pawankumarsrivastava requested changes

2022-03-21 06:33 UTC, pawankumarsrivastava commented on py-utils/src/utils/schema/database.py
> +            "database": "consul_db",
Just changing the db backend to consul will not work in K8 env. The config if pointing to localhost for connecting with consul which will not work. 
Have this patch tested ?

2022-03-21 07:12 UTC, avrnv commented on py-utils/src/utils/schema/database.py
> +            "database": "consul_db",
Yes, the patch was tested and does not break anything.

2022-03-21 07:40 UTC, rahul-tripathi-git commented on py-utils/src/utils/schema/database.py
> +            "database": "consul_db",
In cortx-utils, confstore also connects to consul for its kv store. 
We found that the consul was reachable at localhost in a pod (we are not sure why, this needs to be looked into). But rather we decided to fetch consul endpoint from cluster.conf file.
The PR for above change is (tested by dev but) still under review: https://github.com/Seagate/cortx-utils/pull/765

2022-03-21 09:11 UTC, pawankumarsrivastava approved these changes

2022-03-21 09:50 UTC, ujjwalpl commented on py-utils/src/utils/schema/database.py
> +            "database": "consul_db",
Cases where consul agent is installed locally, this may work locally however that is not guaranteed to work always. Hence, It should always be consul endpoint.

2022-03-21 11:55 UTC, rahul-tripathi-git commented on py-utils/src/utils/schema/database.py
> +            "database": "consul_db",
> Cases where consul agent is installed locally, this may work locally however that is not guaranteed to work always. Hence, It should always be consul endpoint.

Unresolving this conversation to highlight above comment

2022-03-22 09:16 UTC, closed without merging