Cortx 29208
Seagate/cortx-utils pull request #765
Opened 2022-03-15 12:13 UTC by VidyaKabber

# Problem Statement
- Consul backend test cases is running on localhost in K8's environment

# Design
-  Fixed conf_store/test_conf_store_conf.py, kv_store/test_consul_kv_store.py and test_store/test_kv_store.py test cases by
    reading consul endpoints from cluster.conf

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y]: 

# Testing 
- [x] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [x] Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- [x] Confirm Testing was performed with installed RPM [Y/N]:  

# Review Checklist 
  Before posting the PR please ensure
- [x] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [x] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [x] All the tests performed should be mentioned before Resolving a JIRA. 
- [x] Verification needs to be done before marked as Closed/Verified 

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-03-16 07:53 UTC, rahul-tripathi-git requested changes
Please add a tittle for the PR.

2022-03-16 07:53 UTC, rahul-tripathi-git commented on py-utils/test/conf_store/test_conf_store_conf.py
> +LOGGER = logging.getLogger(__name__)
Please remove loggers. We dont log in test code.

2022-03-16 07:53 UTC, rahul-tripathi-git commented on py-utils/test/conf_store/test_conf_store_conf.py
> +LOGGER = logging.getLogger(__name__)
Please remove loggers. We dont log in test code.

2022-03-16 07:53 UTC, rahul-tripathi-git commented on py-utils/test/kv_store/test_consul_kv_store.py
> +            LOGGER.error(f'\nInvalid consul endpoint key : {endpoint_key}\n')
Instead or logging/raising error, assert this or raise KV error

2022-03-16 07:53 UTC, rahul-tripathi-git commented on py-utils/test/kv_store/test_consul_kv_store.py
> +            LOGGER.error(f'\nInvalid consul endpoint key : {endpoint_key}\n')
Instead or logging/raising error, assert this or raise KV error

2022-03-16 09:52 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store_conf.py
> +
Standard is One blank line between functions def's and two blank lines between class def's (PEP 8: E303)

2022-03-16 09:53 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store_conf.py
> +
Standard is One blank line between functions def's and two blank lines between class def's (PEP 8: E303)

2022-03-16 09:59 UTC, rohit-k-dwivedi commented on py-utils/test/conf_store/test_conf_store_conf.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
2022

2022-03-16 11:50 UTC, veerendra-simha-garikipati commented on py-utils/test/conf_store/test_conf_store_conf.py
> +            url = endpoint_key = index_url[1]
'url' variable is not being use here, so can remove it

2022-03-16 11:54 UTC, veerendra-simha-garikipati commented on py-utils/test/kv_store/test_consul_kv_store.py
> +url_config_file = os.path.join(dir_path, 'conf_store', 'config.yaml')
Create a new config.yaml file in kv_store directory instead of using conf_store's config.yaml file

2022-03-16 12:33 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store_conf.py
>  import yaml
one blank line before starting import statements

2022-03-16 13:35 UTC, veerendra-simha-garikipati requested changes

2022-03-17 08:33 UTC, VidyaKabber commented
PR changes are verified on K8s environment as well as on VM. Working as intended.

**Test execution Logs on K8s env:**
```
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 cortx-utils]# git checkout CORTX-29208
Branch 'CORTX-29208' set up to track remote branch 'CORTX-29208' from 'origin'.
Switched to a new branch 'CORTX-29208'
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 cortx-utils]#
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 cortx-utils]#
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 cortx-utils]# cd py-utils/test/kv_store/
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 kv_store]# python3 test_kv_store.py
...............................................
----------------------------------------------------------------------
Ran 47 tests in 0.237s

OK
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.10.20', 56588), raddr=('172.18.10.8', 8500)>
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 kv_store]# python3 test_consul_kv_store.py
.......
----------------------------------------------------------------------
Ran 7 tests in 0.329s

OK
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.10.20', 56886), raddr=('172.18.10.8', 8500)>
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 kv_store]# cd ..
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 test]# cd conf_store/
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 conf_store]# python3 test_conf_store_conf.py
.....
----------------------------------------------------------------------
Ran 5 tests in 0.363s

OK
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.18.10.20', 57274), raddr=('172.18.10.8', 8500)>
[root@cortx-server-headless-svc-ssc-vm-g2-rhev4-3107 conf_store]#
```


**Test execution Logs on VM :**
```
[root@ssc-vm-g2-rhev4-3107 ~]# cd cortx-utils/
[root@ssc-vm-g2-rhev4-3107 cortx-utils]#
[root@ssc-vm-g2-rhev4-3107 cortx-utils]#
[root@ssc-vm-g2-rhev4-3107 cortx-utils]# cd py-utils/test/conf_store/
[root@ssc-vm-g2-rhev4-3107 conf_store]# python3 test_conf_store_conf.py
.....
----------------------------------------------------------------------
Ran 5 tests in 0.464s

OK
[root@ssc-vm-g2-rhev4-3107 conf_store]# cd ..
[root@ssc-vm-g2-rhev4-3107 test]# cd kv_store/
[root@ssc-vm-g2-rhev4-3107 kv_store]#
[root@ssc-vm-g2-rhev4-3107 kv_store]# python3 test_kv_store.py
...............................................
----------------------------------------------------------------------
Ran 47 tests in 0.204s

OK
[root@ssc-vm-g2-rhev4-3107 kv_store]# python3 test_consul_kv_store.py
.......
----------------------------------------------------------------------
Ran 7 tests in 0.218s

OK
[root@ssc-vm-g2-rhev4-3107 kv_store]#

```

2022-03-17 08:37 UTC, rohit-k-dwivedi approved these changes

2022-03-17 11:43 UTC, rahul-tripathi-git requested changes

2022-03-17 13:28 UTC, veerendra-simha-garikipati commented
As you added a new file config.yaml in test/kv_store dirrectory , you need to add it to package_data in /py-utils/test/setup.py file

ex: "kv_store/*.yaml",

2022-03-17 13:32 UTC, veerendra-simha-garikipati commented
and also you need to update /py-utils/src/test_framework/const.py, add the below test commands as we will be passing cluster.conf path to tests.

Ex: 
conf_store.test_conf_store_conf,
kv_store.test_consul_kv_store,
kv_store.test_kv_store,

2022-03-18 08:15 UTC, veerendra-simha-garikipati commented on py-utils/test/conf_store/test_conf_store_conf.py
>      def setUpClass(cls):
While running tests from test_framework we need to make cluster.conf dynamic, coz in the future cluster.conf path might change right, so please add cluster.conf path argument in setupclass() of all three test scripts

Ex: 
def setUpClass(cls, \
        cluster_conf_path: str = 'yaml:///etc/cortx/cluster.conf'):

2022-03-18 08:16 UTC, veerendra-simha-garikipati commented on py-utils/test/conf_store/test_conf_store_conf.py
>      def setUpClass(cls):
While running tests from test_framework we need to make cluster.conf dynamic, coz in the future cluster.conf path might change right, so please add cluster.conf path argument in setupclass() of all three test scripts

Ex:
def setUpClass(cls,
cluster_conf_path: str = 'yaml:///etc/cortx/cluster.conf'):

2022-03-18 11:52 UTC, veerendra-simha-garikipati approved these changes

2022-03-21 07:44 UTC, selvakumaar5496 approved these changes

2022-03-21 07:52 UTC, rahul-tripathi-git approved these changes

2022-03-21 09:06 UTC, sachinpunadikar commented on py-utils/test/kv_store/test_consul_kv_store.py
> +# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates
instead of changing 2021 to 2022, better say:
Copyright (c) 2021, 2022 Seagate Technology LLC and/or its Affiliates

2022-03-21 09:06 UTC, sachinpunadikar requested changes
work on comments, and fix DCO issue

2022-03-21 09:38 UTC, sachinpunadikar commented on py-utils/test/conf_store/test_conf_store_conf.py
> +# Copyright (c) 2021, 2022 Seagate Technology LLC and/or its Affiliates
this is new file created in this year  .. so here just keep 2022

2022-03-21 09:40 UTC, sachinpunadikar approved these changes
+1

2022-03-21 12:16 UTC, cdeshmukh commented
run vm-deployment

2022-03-21 14:43 UTC, VidyaKabber commented
Closing this PR since new PR [https://github.com/Seagate/cortx-utils/pull/773](https://github.com/Seagate/cortx-utils/pull/773) raised for the same changes

2022-03-21 14:43 UTC, closed without merging