pre-deployment HW and storage checks
Seagate/cortx-utils pull request #78
Opened 2020-11-03 07:40 UTC by divya-vijay

1. Covers initial "pre-flight" or pre-deployment HW and storage checks and test cases.
2. All tests are run on all user-given nodes, ( ssh <node> ) but if this step happens even before .ssh/config is present, it may ask for node password interactively.

Signed-off-by: Divya Vijayakumar <divya.vijaykumar@seagate.com>

2020-11-03 17:42 UTC, ypise reviewed
@divya-vijay 
Do update the suggested messages.

2020-11-03 17:42 UTC, ypise commented on py-utils/src/utils/validator/v_hardware.py
> +                raise VError(errno.EINVAL, f"HCA Not Present on {node}.")
Since we are checking for Mellanox card, it would be good to mention the same as missing in Exception.
Preferred:
"Mellanox Host Channel Adapters card (possibly with Infiniband capability) is not detected on {node}"

2020-11-03 17:42 UTC, ypise commented on py-utils/src/utils/validator/v_hardware.py
> +                raise VError(errno.EINVAL, f"HCA Does Not Have Req Ports on {node}.")
Better to have:
"Mellanox Host Channel Adapters ports were not detected by command 'lspci -nn | grep \'Mellanox Technologies\''. For high-speed data network, it is expected to have at lease one port present over some PCIe slot.".

2020-11-03 17:42 UTC, ypise commented on py-utils/src/utils/validator/v_hardware.py
> +        """Check if Mellanox HBA is present"""
HBA is not Mellanox. It probably is LSI.

2020-11-03 17:42 UTC, ypise commented on py-utils/src/utils/validator/v_hardware.py
> +                raise VError(errno.EINVAL, f"HBA Not Present on {node}.")
"Host Bus Adapters (HBA) for SAS channels not detected on {node}."

2020-11-03 17:42 UTC, ypise commented on py-utils/src/utils/validator/v_hardware.py
> +                raise VError(errno.EINVAL, f"HBA Does Not Have Req Ports on {node}.")
"Host Bus Adapters (HBA) ports for SAS channels not detected on {node}. For storage connectivity over SAS channels to JBOD/RBOD there is expectation for a PCIe HBA card to be present. Please check HW, if this system expects a connection to either JBOD or RBOD."

2020-11-03 17:42 UTC, ypise commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Volumes are not accessible at {node}.")
These are LUNs.
Please correct this to:
f"LUNs from Direct Attached Storage (DAS) are not accessible/available on server {node}."

2020-11-03 17:42 UTC, ypise commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Failed to Get Volumes Mapped for {node}.")
f"Failed to detect volumes from Direct Attached Storage (DAS) (available as LUNs) mapped for server {node}."

2020-11-03 17:42 UTC, ypise commented on py-utils/src/utils/validator/v_storage.py
> +                             f"Volumes Are Not Properly Mapped in {node}.")
f"Volumes from Direct Attached Storage (DAS) are not properly mapped in multipath service for {node}. It's expected to detect LUNs in multiples for 16. Troubleshoot the issue and execute the following command on each node: 'multipath -ll | grep prio=50 | wc -l'"

2020-11-04 14:22 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Volumes are not accessible at {node}.")
Comment addressed.

2020-11-04 14:22 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +                             f"Volumes Are Not Properly Mapped in {node}.")
Comment addressed

2020-11-04 14:22 UTC, divya-vijay commented on py-utils/src/utils/validator/v_hardware.py
> +                raise VError(errno.EINVAL, f"HCA Does Not Have Req Ports on {node}.")
Comment addressed

2020-11-04 14:24 UTC, divya-vijay commented
> @divya-vijay
> Do update the suggested messages.

Thanks Yash, Comments addressed and all descriptions updated.

2020-11-05 05:21 UTC, ujjwalpl requested changes

2020-11-05 05:21 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +class HardwareVCommand(VCommand):
Hardware is too generic and covers everything. We need to stick to the identified categories.

2020-11-05 14:54 UTC, divya-vijay commented on py-utils/src/utils/validator/commands.py
> +class HardwareVCommand(VCommand):
@ujjwalpl Addressed the comment by adding all the checks under Storage category. Thanks!

2020-11-06 07:54 UTC, ujjwalpl requested changes

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +        1. storage rpm rpm_name nodes
`$ validate network drivers <spec> <spec>`

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +        2. storage hca nodes
network hca [nodes...]

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +    def validate_mlnx_hca_present(self, nodes):
def validate_hca(self, driver, nodes):

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +    def validate_mlnx_hca_req_ports(self, nodes):
Can merge into validate_hca

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +    def validate_lsb_hba_req_ports(self, nodes):
Merge into valdiate_hba, if separate interface is not required.

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +            print (f"LUN size on {node}:", set(run_result[0].decode('utf-8').splitlines()))
Remove prints

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"LUNs Are Not Equal-Sized on {node}.")
In case of failure, we need to send all the details like listing.

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +
Remove extra lines.

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +    def validate_volumes_mapped(self, nodes):
This can be covered under validate_luns by calling this from that function.

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +        8. storage volumes nodes
storage luns accessible <....>
storage luns mapped <...>

2020-11-06 07:54 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +                self.validate_luns_consistency(args)
if arg[0] == "accessible": 

elif argv[0] == "mapped":

2020-11-06 14:27 UTC, ujjwalpl requested changes

2020-11-06 14:27 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +            else:
raise will not return hence else is not required.

2020-11-06 14:27 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +            else:
else is not required as raise will nor return

2020-11-06 14:27 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +                cmd = f"ssh {node} lspci -nn | grep 'SCSI'"
Mark a todo to use paramiko. Refer to https://github.com/Seagate/cortx-utils/pull/66

2020-11-06 14:27 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +
remove blank line

2020-11-06 14:27 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_storage.py
> +
Remove blank line to be consistent.

2020-11-09 07:22 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +
Comment addressed.

2020-11-09 07:22 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +
Comment addressed.

2020-11-09 07:25 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +            else:
Comment addressed.

2020-11-09 07:25 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +        8. storage volumes nodes
Comment addressed.

2020-11-09 11:21 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +                self.validate_luns_consistency(args)
Comment addressed. The possibilities now are:
arg[0] == "accessible"
arg[0] == "size"
arg[0] == "mapped"

2020-11-09 11:21 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +
Comment addressed.

2020-11-09 11:21 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"LUNs Are Not Equal-Sized on {node}.")
Comment addressed.

2020-11-09 11:21 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +    def validate_lsb_hba_req_ports(self, nodes):
Comment addressed.

2020-11-09 11:21 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +    def validate_mlnx_hca_req_ports(self, nodes):
Comment addressed.

2020-11-09 11:22 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +    def validate_mlnx_hca_present(self, nodes):
Comment addressed.

2020-11-09 11:23 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +        2. storage hca nodes
Comment addressed. 
The Mellanox checks - driver_name and hca - are moved to network category.

2020-11-09 11:23 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +        1. storage rpm rpm_name nodes
Comment addressed.

2020-11-09 11:24 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +                raise VError(errno.EINVAL, f"Failed to Get Volumes Mapped for {node}.")
Comment addressed.

2020-11-09 11:25 UTC, divya-vijay commented on py-utils/src/utils/validator/v_hardware.py
> +                raise VError(errno.EINVAL, f"HBA Not Present on {node}.")
Comment addressed.

2020-11-09 11:25 UTC, divya-vijay commented on py-utils/src/utils/validator/v_hardware.py
> +        """Check if Mellanox HBA is present"""
Comment addressed. Moved to network category.

2020-11-09 11:25 UTC, divya-vijay commented on py-utils/src/utils/validator/v_hardware.py
> +                raise VError(errno.EINVAL, f"HCA Not Present on {node}.")
Comment addressed.

2020-11-09 11:25 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +            print (f"LUN size on {node}:", set(run_result[0].decode('utf-8').splitlines()))
Comment addressed.

2020-11-09 11:32 UTC, divya-vijay commented on py-utils/src/utils/validator/v_storage.py
> +    def validate_volumes_mapped(self, nodes):
Comment addressed. The possibilities now are:
validate_luns('accessible', node1, node2)
validate_luns('size', node1, node2)
validate_luns('mapped', node1, node2)

2020-11-10 02:55 UTC, ujjwalpl approved these changes

2020-11-10 04:17 UTC, ajaysrivas approved these changes

2020-11-10 04:17 UTC, merged