Problem: No infrastruture for running pacemaker checks
Seagate/cortx-utils pull request #79
Opened 2020-11-03 16:18 UTC by knekrasov

Solution:
1. Implement a 'client' for pacemaker-related operations.
2. Implement basic check:
```
./validate.py pacemaker --help
usage: CORTX Validator command pacemaker [-h] {configured} ...

positional arguments:
  {configured}
    configured  Basic sanity check of Pacemaker

optional arguments:
  -h, --help    show this help message and exit
```

2020-11-05 10:28 UTC, ujjwalpl requested changes

2020-11-05 10:28 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +class PacemakerCommand(VCommand):
Please rename to PacemakerVCommand to match the conventions or we will need to change all the other classes to match

2020-11-05 10:28 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +from .pacemaker import PacemakerHealth
Please move this import to PacemakerVCommand (where required) as followed in the code.

2020-11-05 10:31 UTC, ujjwalpl requested changes

2020-11-05 10:31 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +    def add_args(cls, parser):
This will break other classes that make use of the old interface.

2020-11-05 10:34 UTC, ujjwalpl requested changes

2020-11-05 10:34 UTC, ujjwalpl commented on py-utils/src/utils/validator/pacemaker.py
> +class CliExecutor:
There is already a class called SimpleProcess. Please use the same as all the other classes are using.

2020-11-05 10:34 UTC, ujjwalpl requested changes

2020-11-05 10:34 UTC, ujjwalpl commented on py-utils/src/utils/validator/pacemaker.py
> +class PacemakerHealth:
Please rename to PacemakerV, again as per conventions.

2020-11-06 11:06 UTC, knekrasov commented
Closed in favor of https://github.com/Seagate/cortx-utils/pull/87 and https://github.com/Seagate/cortx-utils/pull/85

2020-11-06 11:06 UTC, closed without merging