CORTX-30213: Added Task framework
Seagate/cortx-utils pull request #808
Opened 2022-04-25 21:11 UTC by kailashyadav11

# Problem Statement
- Add an infrastructure for maintaining information about various ongoing activities / tasks in the cluster and view them asynchronously.

# Design
-  For Bug describe the fix here. 
-  [For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/580550715/WIP+CORTX+Task+Framework](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/580550715/WIP+CORTX+Task+Framework)

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: Y
-  Confirm All CODACY errors are resolved [Y/N]: Y

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]: Y
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]:  Y
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  Y

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-04-27 07:55 UTC, ujjwalpl requested changes

2022-04-27 07:59 UTC, ujjwalpl requested changes

2022-04-27 07:59 UTC, ujjwalpl commented on py-utils/test/activity_framework/test_activity_store.py
> +    def test_activity_store_search_activity(self):
Need to add more cases of search.

2022-04-27 09:34 UTC, tanujashinde0405 commented on py-utils/setup.py
> +                'cortx.utils.http', 'cortx.utils.s3', 'cortx.utils.activity_framework'
done

2022-04-28 17:03 UTC, ujjwalpl approved these changes

2022-04-29 04:29 UTC, selvakumaar5496 commented on py-utils/src/utils/activity_tracker/__init__.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
Copyright (c) 2022

2022-04-29 04:33 UTC, tanujashinde0405 commented on py-utils/src/utils/activity_tracker/__init__.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
done

2022-04-29 04:34 UTC, tanujashinde0405 approved these changes

2022-04-29 04:56 UTC, selvakumaar5496 requested changes

2022-04-29 04:56 UTC, selvakumaar5496 commented on py-utils/src/utils/activity_tracker/activity_cli.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
Copyright (c) 2022

2022-04-29 04:56 UTC, selvakumaar5496 commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def __init__(self, *args, **kwargs):
*args is unused and can be removed

2022-04-29 04:56 UTC, selvakumaar5496 commented on py-utils/src/utils/activity_tracker/error.py
> +    """Generic Exception with error code and output."""
No need to rewrite this whole file. This class Can be derived from UtilsError

reference , https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/utils/common/errors.py

2022-04-29 04:56 UTC, selvakumaar5496 commented on py-utils/src/utils/activity_tracker/activity_store.py
> +                r=r.replace("'","")
spaces before and after '='

2022-04-29 04:56 UTC, selvakumaar5496 commented on py-utils/src/utils/activity_tracker/activity_store.py
> +                _ , r = [i.strip() for i in f.split("==")]
remove spaces before comma

2022-04-29 04:56 UTC, selvakumaar5496 commented on py-utils/src/utils/activity_tracker/activity_cli.py
> +    parser = argparse.ArgumentParser(description='Activity CLI',
Check if cmd framework can be used here. 

reference, https://github.com/Seagate/cortx-rgw-integration/blob/main/src/rgw/setup/rgw_setup

2022-04-29 04:56 UTC, selvakumaar5496 commented on py-utils/test/activity_tracker/test_activity_store.py
> +class TestActivityStore(unittest.TestCase):
1. Printing exceptions is not required
2. Add Unhappy path test cases

2022-04-29 06:48 UTC, tanujashinde0405 commented on py-utils/test/activity_tracker/test_activity_store.py
> +class TestActivityStore(unittest.TestCase):
done

2022-04-29 06:49 UTC, tanujashinde0405 commented on py-utils/src/utils/activity_tracker/activity_store.py
> +                _ , r = [i.strip() for i in f.split("==")]
done

2022-04-29 06:49 UTC, tanujashinde0405 commented on py-utils/src/utils/activity_tracker/activity_store.py
> +                r=r.replace("'","")
done

2022-04-29 06:49 UTC, tanujashinde0405 commented on py-utils/src/utils/activity_tracker/error.py
> +    """Generic Exception with error code and output."""
done

2022-04-29 06:49 UTC, tanujashinde0405 commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def __init__(self, *args, **kwargs):
done

2022-04-29 06:49 UTC, tanujashinde0405 commented on py-utils/src/utils/activity_tracker/activity_cli.py
> +# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
done

2022-04-29 08:34 UTC, selvakumaar5496 approved these changes

2022-04-29 09:41 UTC, merged