[Network] ip and host connectivity checks
Seagate/cortx-utils pull request #81
Opened 2020-11-04 07:04 UTC by mazinamdar

Signed-off-by: mazinamdar <mazhar.inamdar@seagate.com>

 1. network ip_connectivity <ip1> <ip2> <ip3>
 2. network host_connectivity <host1> <host2>

2020-11-04 07:28 UTC, ujjwalpl requested changes

2020-11-04 07:28 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +        for host in hosts:
We can have one interface i.e. validate_host_connectivity for both host and ip so they can be mixed up. More flexible. 

$ validate network connectivity host1.domain1.com 8.8.8.8 host2 ip2

Logic can be

```
for host in hosts:
    ip = host # assume host is ip for the time being. 
    if not self._is_ip(ip): 
        # resolve host from host to ip
        ip = self._resolve_host(host)
    self._validate_ip_connectivity(ip) 

def _validate_ip_connectivity(ip):
....
```

2020-11-04 09:47 UTC, mazinamdar commented on py-utils/src/utils/validator/v_network.py
> +        for host in hosts:
comment is addressed

2020-11-04 11:31 UTC, ujjwalpl requested changes

2020-11-04 11:31 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +    def _is_ip(self, ip):
Can be simplified 

```
def _is_ip(self, ip): 
    return if ip.count(".") == 3 and all(self._is_valid_ipv4_part(ip_part) \
           for ip_part in ip.split("."))
```

2020-11-04 11:49 UTC, mazinamdar commented on py-utils/src/utils/validator/v_network.py
> +            is_ip = True
actually this was not indentation error,for loop is belong to if condition ,BTW I have removed this added simplified version

2020-11-04 11:49 UTC, mazinamdar commented on py-utils/src/utils/validator/v_network.py
> +    def _is_ip(self, ip):
comment is addressed

2020-11-04 13:07 UTC, ujjwalpl approved these changes

2020-11-05 10:20 UTC, ajaysrivas approved these changes

2020-11-05 10:21 UTC, merged