CORTX-31132: added conf.compare in confstore for comparing two indexes
Seagate/cortx-utils pull request #817
Opened 2022-05-13 05:27 UTC by tanujashinde0405

Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>

# Problem Statement
Add Conf. compare utility in confstore for comparing two kVstores and return new/deleted/updated keys .

# Design
Using Confstore Compare, If Two Indexes are passed, this function should return the difference between two indexes in a way that it would return three lists: new keys, deleted keys, and updated keys.

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-05-13 05:58 UTC, ujjwalpl requested changes

2022-05-13 05:58 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +    def compare(self, conf_index: str, tmp_index: str):
Signature should be generic and simple. 

**def compare(self, index1: str, index2: str):**

2022-05-13 05:58 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        conf_index Gconf Index
There is nothing called GConf in utils. Please remove all references to CORTX design.

2022-05-13 05:58 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +    def compare(conf_index: str, tmp_index: str):
Same here

2022-05-13 05:58 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        return new_keys,deleted_keys,updated_keys
There is always space after comma ","

2022-05-13 05:59 UTC, ujjwalpl requested changes

2022-05-13 05:59 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        for key in key_list2:
Even though logic is correct for understanding.... for loop should be on list1 which is the base, old config. Its like refer to old config and see if any value has changed. 

``` 
filter(lambda key: key not in deleted_keys and self.get(index1, key) != self.get(index2, key), key_list1)
```

2022-05-13 06:05 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store.py
> +            actual_new_keys, actual_deleted_keys, actual_updated_keys = Conf.compare('conf1','conf4')
Space after comma

2022-05-13 06:05 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store.py
> +        actual_new_keys, actual_deleted_keys, actual_updated_keys = Conf.compare('conf1','conf2')
Space after comma

2022-05-13 06:06 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store.py
> +        expected_new_keys = ["bridge>protocol"]
quote inconsistency "bridge>protocol" -> 'bridge>protocol'

2022-05-13 06:06 UTC, selvakumaar5496 commented on py-utils/test/conf_store/test_conf_store.py
> +        expected_updated_keys = ["bridge>port"]
same as above

2022-05-13 06:48 UTC, tanujashinde0405 commented on py-utils/test/conf_store/test_conf_store.py
> +        expected_updated_keys = ["bridge>port"]
done

2022-05-13 06:48 UTC, tanujashinde0405 commented on py-utils/test/conf_store/test_conf_store.py
> +        expected_new_keys = ["bridge>protocol"]
done

2022-05-13 06:48 UTC, tanujashinde0405 commented on py-utils/test/conf_store/test_conf_store.py
> +        actual_new_keys, actual_deleted_keys, actual_updated_keys = Conf.compare('conf1','conf2')
done

2022-05-13 06:48 UTC, tanujashinde0405 commented on py-utils/test/conf_store/test_conf_store.py
> +            actual_new_keys, actual_deleted_keys, actual_updated_keys = Conf.compare('conf1','conf4')
done

2022-05-13 06:48 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        for key in key_list2:
done

2022-05-13 06:48 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        return new_keys,deleted_keys,updated_keys
done

2022-05-13 06:48 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +    def compare(conf_index: str, tmp_index: str):
done

2022-05-13 06:48 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        conf_index Gconf Index
done

2022-05-13 06:49 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +    def compare(self, conf_index: str, tmp_index: str):
done

2022-05-13 07:05 UTC, ujjwalpl approved these changes

2022-05-13 09:52 UTC, selvakumaar5496 approved these changes

2022-05-16 09:15 UTC, rahul-tripathi-git reviewed
Please test/verify if compare api is working with consul as well.

2022-05-16 16:46 UTC, ujjwalpl requested changes

2022-05-16 16:46 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "# conf yaml:///tmp/url1.file compare yaml:///tmp/url2.file\n\n")
Please remove references to file.

2022-05-16 16:49 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_cli.py
> +            "# conf yaml:///tmp/url1.file compare yaml:///tmp/url2.file\n\n")
done

2022-05-16 20:02 UTC, rahul-tripathi-git requested changes
Please update the PR template.

2022-05-16 20:02 UTC, rahul-tripathi-git commented on py-utils/src/utils/conf_store/conf_cli.py
> +        return Conf.compare(index1, index2)
Please share the output for Conf cli compare api.
(You can put it in PR template.)

2022-05-17 02:42 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_cli.py
> +        return Conf.compare(index1, index2)
done

2022-05-17 02:43 UTC, tanujashinde0405 commented on py-utils/test/conf_store/test_conf_cli.py
> +        self.assertEqual(result_data[0], b"(['bridge>port'], ['bridge>cli_name', 'bridge>has_internet'], ['version', 'branch'])\n")
No, Cmd_proc.run() returns data in this format which is tuple:
(b"(['bridge>port'], ['bridge>cli_name', 'bridge>has_internet'], ['version', 'branch'])\n", b'', 0)
<class 'tuple'>

and my command returns data in tuple only:
[root@ssc-vm-g3-rhev4-3062 ~]# conf yaml:///root/tmp.conf compare yaml:///root/tmp1.conf
(['cortx>rgw>protocol'], ['cortx>rgw>port'], ['cortx>rgw>name'])

2022-05-17 02:49 UTC, rahul-tripathi-git approved these changes

2022-05-17 02:55 UTC, tanujashinde0405 commented on py-utils/test/conf_store/test_conf_cli.py
> +        self.assertEqual(result_data[0], b"(['bridge>port'], ['bridge>cli_name', 'bridge>has_internet'], ['version', 'branch'])\n")
I have removed the second test as it wont work in case any other tests are added to manipulate file1 and file2.json.

2022-05-17 04:51 UTC, nitin-seagate approved these changes
LGTM

2022-05-18 05:03 UTC, ujjwalpl approved these changes

2022-05-18 05:28 UTC, cdeshmukh approved these changes

2022-05-18 05:29 UTC, cdeshmukh commented
Address https://github.com/Seagate/cortx-utils/pull/817/checks?check_run_id=6477693744 codacy issue plz

2022-05-18 05:38 UTC, tanujashinde0405 commented
> Address https://github.com/Seagate/cortx-utils/pull/817/checks?check_run_id=6477693744 codacy issue plz

Hi Chetan, It is a false positive codacy, Rahul has asked me to ignore it

2022-05-18 05:45 UTC, merged