Implemented elasticsearch validator
Seagate/cortx-utils pull request #82
Opened 2020-11-04 08:19 UTC by shrimetta

**Problem Statement**
Validator for elasticsearch service

**Solution Overview**
Implemented validator for elasticsearch service

Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>

2020-11-04 12:28 UTC, ujjwalpl requested changes

2020-11-04 12:28 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_elasticsearch.py
> +class ElasticsearchV(HttpService):
This derivation is not required. HttpService can just be used for validation. 

```
class ElasticsearchV():
    ...

        if v_type == "service":
            host = args[0]
            port = args[1]
            HttpServer(host, port).validate_service_status()

```

2020-11-04 12:28 UTC, ujjwalpl commented on py-utils/src/utils/validator/service.py
> +    def __init__(self):
init should take host, post, service as the parameters. They should not be default.

2020-11-04 12:30 UTC, ujjwalpl requested changes

2020-11-04 12:30 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_elasticsearch.py
> +        if v_type == "service":
Please make the similar change for consul as well so that code can be common for both.

2020-11-04 12:43 UTC, shrimetta commented on py-utils/src/utils/validator/v_elasticsearch.py
> +        if v_type == "service":
I will raise separate PR for this.

2020-11-04 15:32 UTC, shrimetta commented on py-utils/src/utils/validator/v_elasticsearch.py
> +class ElasticsearchV(HttpService):
done

2020-11-04 15:32 UTC, shrimetta commented on py-utils/src/utils/validator/service.py
> +    def __init__(self):
done

2020-11-04 16:53 UTC, ujjwalpl approved these changes

2020-11-05 05:27 UTC, ajaysrivas commented on py-utils/src/utils/validator/service.py
> +class HttpService(Service):
I guess, the purpose of introducing this was to use it in both elasticsearch and consul but I do not see the code changes in Consul validator to use this. Do you need to make changes in Consul validator too?

2020-11-05 05:43 UTC, shrimetta commented on py-utils/src/utils/validator/service.py
> +class HttpService(Service):
I will make changes for consul in separate checkin.

2020-11-05 06:53 UTC, shrimetta commented on py-utils/src/utils/validator/service.py
> +class HttpService(Service):
Created issue #84 for the above

2020-11-05 06:56 UTC, ajaysrivas approved these changes

2020-11-05 06:56 UTC, merged