Cortx 31365 version compatibility API
Seagate/cortx-utils pull request #821
Opened 2022-05-27 06:00 UTC by kailashyadav11

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-05-27 08:46 UTC, nitin-seagate approved these changes
LGTM

2022-05-29 11:56 UTC, cdeshmukh requested changes

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/const.py
> +BUILD_NAME_KEY = "cortx>common>release>name"
any common key hierarchy should be kept in a parent key and child keys build based on that, so any change in hierarchy would result in minimal changes
And why release is called build here, it has different purposes, release has build info too in extended format, better not to mix them

RELEASE_KEY = "cortx>common>release"
RELEASE_NAME_KEY = RELEASE_KEY + ">name"
RELEASE_VER_KEY = RELEASE_KEY + ">version"

same comment applies wherever else applicable

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +        resource: resources Node/Cluster (currently supports only node).
>  resource: resources Node/Cluster (currently supports only node).

Seems resource_type to me, if yes plz rename
Also state it as 
 **resource: resource type like node, cluster (currently supports only node).**

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +        reason - Reason why the given version is not compatible for update.
Just reason in string format ? Ideally an error code prepended error string should be supplied

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +            raise Exception("Compatibilty check at cluster level is not yet supported")
raise a NotImplementedError exception

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +                        break
when there can be multiple conditions in 'requires', how we can break on first condition satisfied or denied ?

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +                    if name in condition.split('>=')[0]:
condition can probably have all possible combinations, we are just restricting it to one '>=' in previous & new code also ?
conditions can be anything like >=, >, ==, <, <=
or in some cases no conditions even, stated with None or "" empty string?

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +        if matched_rules != len(installed_versions):
this check can very easily fail. what if there are no conditions in requires, for such cases matched_rules wont get updated

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +            raise Exception("Invalid compatibility rules.")
if error codes needed beyond system errno, define an enum capturing all such error codes and every exception should pass such error codes

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +                node_list.append(version_conf.get(const.NODE_ID_KEY % (storage_set, resource_idx)))
can you add some examples as comment code, so it becomes easy to visualize

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +        build_name =  version_conf.get(const.BUILD_NAME_KEY)
rename
build_name -> release_name
build_version -> release_version

2022-05-29 11:56 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +        if len(version_info) != (num_components + 1):
how this check can be against whole node_list, it should be per node(resource) right?

2022-05-30 18:35 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +            raise Exception("Invalid compatibility rules.")
added system exception with errno

2022-05-30 18:36 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +                node_list.append(version_conf.get(const.NODE_ID_KEY % (storage_set, resource_idx)))
added example of the input key and output result

2022-05-30 18:36 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +        build_name =  version_conf.get(const.BUILD_NAME_KEY)
updated the variable names

2022-05-30 18:37 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +        if len(version_info) != (num_components + 1):
The check is per node basis, modified the code for more clarity.

2022-05-30 18:38 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +        if matched_rules != len(installed_versions):
Confirmed with RE team there will would not be a scenario where there are no conditions, and the API will consider the input to be invalid in such case.

2022-05-30 18:42 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +                    if name in condition.split('>=')[0]:
Correct, conditions will be more as the API evolves but for now upgrade is the supported scenario.
Modified the logic to be in a more generic method to include other version operators (>=, >, ==, <, <=) in future.
None or empty string will be considered as invalid input argument by the API.

2022-05-30 18:46 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +                        break
All the version compatibility clauses are planned to be in a single condition of the 'requires' section. 
as per the below example
`REQUIRES:
- cortx-rgw >= 2.0.0-0 <= 2.0.0-0,`

the above condition will have all the necessary compatibility clauses related to 'cortx-rgw', so once the condition is satisfied we are breaking the loop to move to other components. We will have more checks in future when downgrade will be supported.

2022-05-30 18:47 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +            raise Exception("Compatibilty check at cluster level is not yet supported")
done

2022-05-30 18:49 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +        reason - Reason why the given version is not compatible for update.
'reason' - here is not an error response it is a return value from the method which basically says due to what condition the versions are incompatible.
for example:
utils deployed version 2.0.0-5252 is older than the compatible version 2.0.0-5260.'

2022-05-30 18:49 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +        resource: resources Node/Cluster (currently supports only node).
renamed variable

2022-05-30 18:50 UTC, kailashyadav11 commented on py-utils/src/utils/const.py
> +BUILD_NAME_KEY = "cortx>common>release>name"
done, used a constant for common hierarchy.

2022-05-31 03:21 UTC, rahul-tripathi-git reviewed
Please use your best judgement to cater these comments.

2022-05-31 03:21 UTC, rahul-tripathi-git commented on py-utils/src/utils/const.py
> +CONSUL_CONF = "/etc/cortx/consul_conf"
Please confirm if this should be a hardcoded path.
Ideally we should not hardcode paths to conf files.

@nitin-seagate

2022-05-31 03:21 UTC, rahul-tripathi-git commented on py-utils/src/utils/schema/release.py
> +class ReleaseError(Exception):
Suggestion: SetupError, UpgradeError or something like that. Release error doesnt seem right.

2022-05-31 03:21 UTC, rahul-tripathi-git commented on py-utils/src/utils/schema/release.py
> +        reason - Reason why the given version is not compatible for update.
If reason will always be related to version mismatch, lets mention this specifically. or you can use something like status_string which clearly defines the motive.

2022-05-31 04:16 UTC, kailashyadav11 commented on py-utils/src/utils/const.py
> +CONSUL_CONF = "/etc/cortx/consul_conf"
this is not a conf path, the conf url is stored by provisioner at this location. Since utils do not have the memory of gconf location, the API can go and fetch whatever url is stored at this path.

2022-05-31 04:28 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +class ReleaseError(Exception):
Using CompatibilityErrror instead.

2022-05-31 04:29 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +        reason - Reason why the given version is not compatible for update.
done renamed to status_string

2022-05-31 06:06 UTC, kupranay commented on py-utils/src/utils/const.py
> +CONSUL_CONF = "/etc/cortx/consul_conf"
this should not be hardcoded. @ujjwalpl  please suggest

2022-05-31 06:29 UTC, rahul-tripathi-git commented on py-utils/src/utils/schema/release.py
> +class ReleaseError(Exception):
SetupError is decided and put as name. Resolving this comment.

2022-05-31 06:32 UTC, kailashyadav11 commented on py-utils/src/utils/const.py
> +CONSUL_CONF = "/etc/cortx/consul_conf"
that is not a conf path, the conf url is stored by provisioner at this location. Since utils do not have the memory of gconf location, the API can go and fetch whatever url is stored at this path. The hard coded path is the location where the gconf url is stored and not the gconf itself.

2022-05-31 06:35 UTC, abhijit1patil commented on py-utils/src/utils/schema/release.py
> +class SetupError(Exception):
can we move SetupError class to cortx-utils/py-utils/cortx/utils/errors.py ?
cortx-utils/py-utils/cortx/utils/errors.py ==> has all utils error defined

2022-05-31 06:37 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +class SetupError(Exception):
@rahul-tripathi-git  please suggest

2022-05-31 09:14 UTC, rahul-tripathi-git commented on py-utils/src/utils/schema/release.py
> +class SetupError(Exception):
yes this is a good suggestion, otherwise a separate error.py module can be added to this module.
Refer below:
[class BundleError(BaseError):](https://github.com/Seagate/cortx-utils/blob/632c85707a782481eb1e940ea5952c3937687012/py-utils/src/utils/support_framework/errors.py#L18)

2022-05-31 13:40 UTC, cdeshmukh commented on py-utils/src/utils/schema/release.py
> +            if len(clause.split('>=')) < 1:
so we are ignoring checks for other operators for now? any TODOs for future ?

2022-05-31 14:15 UTC, rahul-tripathi-git commented on py-utils/src/utils/const.py
> +CONSUL_CONF = "/etc/cortx/consul_conf"
There is no config file for utils, hence there is no way to store the consul path or any other value from Gconf. So this workaround was discussed and put in.
@kailashyadav11  please create a enhancement story in case some other way to handle this comes up.

Similar situation happened with support bundle where install path was needed to be saved so we had some workaround for that too.

2022-05-31 14:22 UTC, rahul-tripathi-git commented
Codacy D203 is an expected codacy warning. It will be suppressed in future for this repo as It conflicts with D211.

2022-05-31 14:23 UTC, kailashyadav11 commented on py-utils/src/utils/schema/release.py
> +    """Generic Exception with error code and output."""
D211 contradicts with D203 error and can be ignored.

2022-05-31 16:41 UTC, merged