CORTX-31530: Observed cortx-ha-k8s-monitor restart after ~115 hours of IO's
Seagate/cortx-utils pull request #830
Opened 2022-06-07 10:46 UTC by Madhura-08

…f IO's.

HA k8s monitor service restart was observed because at some point of time
it failed at parsing the alert message because of some type mismatch. The
basic health event gets created using utils HealthEvent class. This event's
payload attribute "specific_info" has default value as 'str'. So, if
'set_specifc_info' gets called, then only, this value will change to 'dict'.
Otherwise it will remain as 'str' and the parsing will fail. So, This should be
dictionary as its purpose is to carry additional information in key value
format.

Signed-off-by: Madhura Mande <madhura.mande@seagate.com>

# Problem Statement
[- Problem statement ]
https://github.com/Seagate/cortx-utils/pull/new/CORTX-31530

# Design
Make default value of "specific_info" of payload as dictionary

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-06-07 11:06 UTC, gauri-bhosale approved these changes
please test for specific_info for empty string change.

2022-06-08 02:55 UTC, rahul-tripathi-git requested changes
Quoting below from ticket:
> Namespace(config='yaml:///etc/cortx/cluster.conf', services='k8s_monitor')
The driver process with pid 7, and args ['/usr/bin/python3', '/usr/lib/python3.6/site-packages/ha/monitor/k8s/monitor.py'] started successfully.
Exception in thread Monitor-node-Thread:
Traceback (most recent call last):
File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/site-packages/ha/monitor/k8s/object_monitor.py", line 166, in run
if self._is_published_alert(alert):
File "/usr/lib/python3.6/site-packages/ha/monitor/k8s/object_monitor.py", line 203, in _is_published_alert
if payload["specific_info"].get("generation_id"):
AttributeError: 'str' object has no attribute 'get'

Above condition can be changed to below:
if payload.get("specific_info>generation_id")

2022-06-08 02:55 UTC, rahul-tripathi-git commented on py-utils/src/utils/event_framework/health.py
> +        payload.set('specific_info', {})
Setting up a dictionary is not the correct way. Key and value both should be strings.

2022-06-08 04:09 UTC, cdeshmukh commented on py-utils/src/utils/event_framework/health.py
> +        payload.set('specific_info', {})
Its initializing it to dict instead of string, i dont see a problem. Also if specific_info supposed to be used as dict atlast, it should have dict at first place

2022-06-08 04:11 UTC, Madhura-08 commented on py-utils/src/utils/event_framework/health.py
> +        payload.set('specific_info', {})
May I know why?
Please note that, this event will be sent across components and this will not be stored or fetched from confstore KV. and according to the structure that was decided. This is supposed to be dictionary not string!

2022-06-08 04:13 UTC, Madhura-08 reviewed
@rahul-tripathi-git 
if payload.get("specific_info>generation_id")
-> This is not confstore kv. At run time this will be fetched from alert. So, we can not do this.

2022-06-08 04:17 UTC, Madhura-08 reviewed
please test for specific_info for empty string change.
@gauri-bhosale  Can you please check my testing details? And if still you have questions, we can talk then.

2022-06-08 04:32 UTC, cdeshmukh commented on py-utils/src/utils/event_framework/health.py
> +        val: value to be set for a given key.
value to set for given key

2022-06-08 04:32 UTC, cdeshmukh commented on py-utils/src/utils/event_framework/health.py
> +        val: value to be set for a given key.
value to set for given key

2022-06-08 04:41 UTC, cdeshmukh commented on py-utils/src/utils/event_framework/health.py
> +"""Module which creates the health event with required key value."""
"""Module to generate the health events"""

2022-06-08 05:02 UTC, gauri-bhosale commented
> please test for specific_info for empty string change. @gauri-bhosale Can you please check my testing details? And if still you have questions, we can talk then.
thanks @Madhura-08  looks good testing details

2022-06-08 10:44 UTC, Madhura-08 commented on py-utils/src/utils/event_framework/health.py
> +        val: value to be set for a given key.
Done

2022-06-08 10:44 UTC, Madhura-08 commented on py-utils/src/utils/event_framework/health.py
> +        val: value to be set for a given key.
Done

2022-06-08 10:44 UTC, Madhura-08 commented on py-utils/src/utils/event_framework/health.py
> +"""Module which creates the health event with required key value."""
Done

2022-06-08 11:48 UTC, rahul-tripathi-git commented on py-utils/src/utils/event_framework/health.py
> +        payload.set('specific_info', {})
In HA code, the KVPayload although used is reduced to a dictionary in the end. Hence agreed that the complete key will not fetch the value. Hence initializing the dictionary in the beginning will solve this issue.

2022-06-08 11:49 UTC, rahul-tripathi-git approved these changes

2022-06-09 01:21 UTC, ujjwalpl approved these changes

2022-06-09 04:25 UTC, cdeshmukh approved these changes

2022-06-09 04:44 UTC, merged