Activity framework Modifications [Draft]
Seagate/cortx-utils pull request #834
Opened 2022-06-13 04:26 UTC by rohitkolapkar

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-06-14 09:42 UTC, abhijit1patil approved these changes

2022-06-14 11:30 UTC, ujjwalpl requested changes

2022-06-14 11:30 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    FAILED = const.FAILED
Valid states are NEW, IN_PROGRESS, COMPLETED, SUSPENDED

2022-06-14 11:30 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +            description = kwargs.get(const.DESCRIPTION)
What is any of the kwargs is missing ? Did you test ? Do we raise exception, handle it ?

2022-06-14 11:30 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +            self._payload[const.PROGRESS] = 0
self._payload[const.PCT_COMPLETE] = 0

2022-06-14 11:30 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def set_status(self, progress: int, status: str, status_description: str):
I think this interface should be modified to 
```
def set_progress(self, pct_complete: int, description: str):
  self._payload[const.STATUS] = IN_PROGRESS
  ...
```

2022-06-14 11:30 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +        self._payload[const.PROGRESS] = progress
Also need to add an interface name 'suspend'. Refer to the state machine

2022-06-14 11:30 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +        activity.set_status(progress, status, status_description)
Did you test if search is working ?

2022-06-14 11:30 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def update(activity: ActivityEntry, progress: int, status: str, status_description: str):
`def update(activity: ActivityEntry, pct_complete: int, description: str):`

2022-06-14 11:30 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def create(name:str, resource_path: str, description: str):
Did you test this with say Json or consul backend ?

2022-06-14 11:30 UTC, ujjwalpl commented on py-utils/test/activity_tracker/test_activity_store.py
> +        activity = Activity.create("Activity","Activities", "Activity Status")
space after comma

2022-06-14 11:34 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def create(name:str, resource_path: str, description: str):
Tested with json and consul both. CSM CRUD APIs are using consul backend.

2022-06-14 11:38 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +        activity.set_status(progress, status, status_description)
Search is not working. Im going to work on search interface in next sprint.

2022-06-14 11:41 UTC, ujjwalpl requested changes

2022-06-14 11:41 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def create(name:str, resource_path: str, description: str):
Search may not work with consul. Hence its important to confirm that it works.

2022-06-14 11:41 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +        activity.set_status(progress, status, status_description)
Ok

2022-06-14 11:41 UTC, ujjwalpl commented on py-utils/test/activity_tracker/test_activity_store.py
> +            Activity.create("Activity","Activities", None)
Space after comma

2022-06-14 11:43 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +            description = kwargs.get(const.DESCRIPTION)
ActivityEntry will be called through Activity.create() interface, there we have ensured this.

2022-06-14 11:47 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def create(name:str, resource_path: str, description: str):
sure

2022-06-14 11:48 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +            self._payload[const.PROGRESS] = 0
As per discussion, I have changed this from 'pct_complete' -> progress. 
do you want me to change it to ''pct_complete' ?

2022-06-14 11:57 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def set_status(self, progress: int, status: str, status_description: str):
yes, currently, user can provide the 'status' value too, that is why Im accepting status. 
Im going to work on this, once we finalize the design for the update interface in next sprint for different scenarios.
eg. For updating the status to "SUSPENDED", user needs to provide status value too.

2022-06-14 11:58 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +        self._payload[const.PROGRESS] = progress
sure

2022-06-14 11:58 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def update(activity: ActivityEntry, progress: int, status: str, status_description: str):
yes, currently, user can provide the 'status' value too, that is why Im accepting status.
Im going to work on this, once we finalize the design for the update interface in next sprint for different scenarios.
eg. For updating the status to "SUSPENDED", user needs to provide status value too.

2022-06-14 12:00 UTC, rohitkolapkar commented on py-utils/test/activity_tracker/test_activity_store.py
> +        activity = Activity.create("Activity","Activities", "Activity Status")
updated

2022-06-14 12:00 UTC, rohitkolapkar commented on py-utils/test/activity_tracker/test_activity_store.py
> +            Activity.create("Activity","Activities", None)
updated

2022-06-14 13:52 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +            description = kwargs.get(const.DESCRIPTION)
> What if any of the kwargs is missing ? Did you test ? Do we raise exception, handle it ?

Hi @ujjwalpl, this is handled, if the key is missing, the value would be None and I can see None check is already applied, we also raise an exception.

2022-06-14 13:55 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +            self._payload[const.PROGRESS] = 0
> self._payload[const.PCT_COMPLETE] = 0

As we discussed, changed it to const.PCT_PROGRESS

2022-06-14 14:54 UTC, ujjwalpl requested changes

2022-06-14 14:54 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +            description = kwargs.get(const.DESCRIPTION)
Every module is responsible for own validations unless its completely internal module and not exposed to anything

2022-06-14 14:54 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +            self._payload[const.PROGRESS] = 0
**pct_complete** or **pct_progress**. 
We need to be more meaningful. progress can be 0 to 10000. pct_progress means 0 to 100.

2022-06-15 06:59 UTC, pawankumarsrivastava approved these changes

2022-06-15 07:01 UTC, rohitkolapkar commented
@kupranay please merge this PR to feature branch. All the suggested changes will be taken care in https://jts.seagate.com/browse/CORTX-32261

2022-06-15 08:09 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def update(activity: ActivityEntry, progress: int, status: str, status_description: str):
updated

2022-06-15 08:09 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +        self._payload[const.PROGRESS] = progress
added

2022-06-15 10:24 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +            self._payload[const.PROGRESS] = 0
yes.

2022-06-15 10:24 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def set_status(self, progress: int, status: str, status_description: str):
done

2022-06-15 15:23 UTC, ujjwalpl requested changes

2022-06-15 15:23 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def set_progress(self, pct_progress: int, status_desc: str):
We need to track start time for the activity.

2022-06-15 15:23 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def update(activity: ActivityEntry, pct_progress: int, status_desc: str = const.IN_PROGRESS_DESC):
Pls use less than 80 chars

2022-06-15 15:23 UTC, ujjwalpl commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def finish(self, status_desc: str):
you need to accept return code. Please refer to the state machine.

2022-06-15 15:34 UTC, mssawant commented on py-utils/src/utils/activity_tracker/activity_store.py
> +        if activity_data.get(const.STATUS) == const.COMPLETED:
[suggestion] this condition is redundant, instead you can have `activity.is_complete(activity_data)`

2022-06-15 18:13 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +        if activity_data.get(const.STATUS) == const.COMPLETED:
done

2022-06-15 18:14 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def update(activity: ActivityEntry, pct_progress: int, status_desc: str = const.IN_PROGRESS_DESC):
done

2022-06-15 18:15 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def set_progress(self, pct_progress: int, status_desc: str):
Hi, as we have discussed, create and start is one and the same. so when an activity is created, we are recording current_time as created_time.

And when we call update, suspend or finish, we are recording current_time as updated_time.

2022-06-16 10:24 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def finish(self, status_desc: str):
done

2022-06-16 11:42 UTC, ujjwalpl approved these changes

2022-06-17 04:28 UTC, suryakumar1024 approved these changes

2022-06-17 08:14 UTC, rahul-tripathi-git requested changes
There are changes in method signatures. Please answer following questions:
1. Which component/s will be affected by these changes.
2. If there are associated PR/s in other repos please mention them.

Also please make sure that the test cases added are added to sanity and other relevant plan files. (it will include these test cases in utils test framework.)

2022-06-17 08:14 UTC, rahul-tripathi-git commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def set_progress(self, pct_progress: int, status_desc: str):
changes in method signature.

2022-06-17 08:14 UTC, rahul-tripathi-git commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def finish(self, rc: int, status_desc: str):
changes in method signature.

2022-06-17 08:14 UTC, rahul-tripathi-git commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def create(name:str, resource_path: str, description: str) -> ActivityEntry:
changes in method signature.

2022-06-17 08:14 UTC, rahul-tripathi-git commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def finish(activity: ActivityEntry, rc: int, status_desc: str = \
changes in method signature.

2022-06-17 08:14 UTC, rahul-tripathi-git commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def suspend(activity: ActivityEntry, status_desc: str = \
changes in method signature.

2022-06-17 08:14 UTC, rahul-tripathi-git commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def get(activity_id: str) -> ActivityEntry:
changes in method signature.

2022-06-17 08:38 UTC, rohitkolapkar commented
> There are changes in method signatures. Please answer following questions:
> 
> 1. Which component/s will be affected by these changes.
> 2. If there are associated PR/s in other repos please mention them.
> 
> Also please make sure that the test cases added are added to sanity and other relevant plan files. (it will include these test cases in utils test framework.)

1 and 2 -> Component/s will not be affected as No one is using it. CSM is going to use it in upcoming sprint.

Added test pln file, aslo added in sanity and regression pln.

2022-06-17 08:39 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def set_progress(self, pct_progress: int, status_desc: str):
No component will be affected as No one is using it. Method signature change is a part of enhancement to framework.

2022-06-17 08:40 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def finish(self, rc: int, status_desc: str):
No component will be affected as No one is using it. Method signature change is a part of enhancement to framework.

2022-06-17 08:40 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def create(name:str, resource_path: str, description: str) -> ActivityEntry:
No component will be affected as No one is using it. Method signature change is a part of enhancement to framework.

2022-06-17 08:40 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def finish(activity: ActivityEntry, rc: int, status_desc: str = \
No component will be affected as No one is using it. Method signature change is a part of enhancement to framework.

2022-06-17 08:41 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def suspend(activity: ActivityEntry, status_desc: str = \
This is not a method signature change, suspend is a new interface.

2022-06-17 08:43 UTC, rohitkolapkar commented on py-utils/src/utils/activity_tracker/activity_store.py
> +    def get(activity_id: str) -> ActivityEntry:
No method signature change,  this method has been returning  ActivityEntry, added code readability.

2022-06-17 17:45 UTC, rahul-tripathi-git approved these changes
Looks good to me.

2022-06-17 17:45 UTC, merged