CORTX-31536: Added timeout for list_topics to prevent Control POD from hanging
Seagate/cortx-utils pull request #836
Opened 2022-06-15 04:50 UTC by pawankumarsrivastava

Signed-off-by: Pawan Kumar Srivastava <pawan.kumarsrivastava@seagate.com>

# Problem Statement
- Problem statement 

# Design
-  For Bug describe the fix here. 
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-06-16 06:44 UTC, selvakumaar5496 approved these changes

2022-06-17 14:42 UTC, abhijit1patil approved these changes

2022-06-17 18:14 UTC, rahul-tripathi-git approved these changes

2022-06-20 04:31 UTC, Pranali04796 approved these changes

2022-06-20 07:15 UTC, rahul-tripathi-git commented
retest this please

2022-06-20 08:09 UTC, kupranay approved these changes

2022-06-20 10:42 UTC, sachinpunadikar approved these changes
LGTM

2022-06-20 10:42 UTC, merged

2022-06-20 12:11 UTC, ujjwalpl requested changes

2022-06-20 12:11 UTC, ujjwalpl commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            message_type_metadata = admin.list_topics(timeout=self._admin_api_timeout).__dict__
There should be a way to block indefinitely if someone wants to configure it that way. Please check 
- if value of -1 would result into indefinite wait. 
- Document the meaning of -1 in the config file.

2022-06-21 04:25 UTC, rahul-tripathi-git commented on py-utils/src/utils/message_bus/message_broker_collection.py
> +            message_type_metadata = admin.list_topics(timeout=self._admin_api_timeout).__dict__
@pawankumarsrivastava 
Please address the above comment.