CORTX-32734_lock_interface: Conf store generic soft lock interface
Seagate/cortx-utils pull request #853
Opened 2022-07-14 12:22 UTC by kailashyadav11

Signed-off-by: Kailash Yadav <kailash.yadav@seagate.com>

# Problem Statement
-  Implement an interface to soft lock and unlock a config from Confstore, to avoid concurrent access and redundant effort from multiple config service instances.

# Design
-  For Bug describe the fix here. 
-  [For Feature, Post the link to the solution page on the confluence CORTX Foundation Library ](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/1074626828/HLD+Distributed+Locks+using+Conf+Store)

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-07-14 14:53 UTC, ujjwalpl requested changes

2022-07-14 14:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +    def lock(self, lock_key:str):
`def lock(self, lock_key: str):`

2022-07-14 14:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +        self.test_lock(lock_key)
return self.test_lock(lock_key)

2022-07-14 14:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +        """Lock the config."""
Write comment describing the behaviour. e.g. blocking or non blocking. When does it return True or False.

2022-07-14 14:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +        self.test_lock(lock_key)
lock(key)

lock(key, timeout=0, cond_key=None):
  while (True):
    if lock(): return True
    return False
    for i in range(timeout):
      if (cond_key): get(cond_key) == True: return True
      wait(1); timeout--;

_lock(key):
   me = ?
   who = test_lock()
   if who == me: return True
   set(me) << Overwrite
   who = test_lock() 
   return (who == me)

2022-07-14 14:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_cache.py
> +        return self.delete(lock_key)
test_lock and then delete

2022-07-14 14:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +            if key == "lock_key":
if key in [a, b, c]: error

2022-07-14 14:53 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        for key, val in kwargs.items():
```
for key, val in kwargs.items():
       if key not in [a, b, c,]: error
       self.set_attr('_%s' %key, val)
```

2022-07-15 10:55 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_cache.py
> +    def lock(self, lock_key:str):
done

2022-07-15 10:56 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_cache.py
> +        self.test_lock(lock_key)
updated

2022-07-15 10:56 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_cache.py
> +        """Lock the config."""
done

2022-07-15 10:56 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_cache.py
> +        return self.delete(lock_key)
updated

2022-07-15 10:56 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_store.py
> +            if key == "lock_key":
modified

2022-07-15 10:56 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_store.py
> +        for key, val in kwargs.items():
optimized

2022-07-15 10:58 UTC, kailashyadav11 commented
``
from cortx.utils.conf_store import Conf
>>> Conf.load('p1', 'consul://ssc-vm-rhev4-2927.colo.seagate.com:8500/gconf')
>>> Conf.load('p2', 'consul://ssc-vm-rhev4-2927.colo.seagate.com:8500/gconf')
>>> Conf.load('m1', 'consul://ssc-vm-rhev4-2927.colo.seagate.com:8500/gconf')
>>> Conf.load('m2', 'consul://ssc-vm-rhev4-2927.colo.seagate.com:8500/gconf')

Process set 1:
=============
# test_lock_status:
=============
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
False
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
False
>>> 

# test lock:
===============
>>> Conf.lock('p1', lock_key="cortx>p>lock", lock_owner="p1")
True
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
True
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
True
>>> 

# test lock repeat
==============
>>> Conf.lock('p1', lock_key="cortx>p>lock", lock_owner="p1")
True
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
True
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
True
>>> 

# test_lock_from_different_thread
============================
>>> Conf.lock('p2', lock_key="cortx>p>lock", lock_owner="p2")
False
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
True
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
True
>>> 

# test_unlcok_from_different_thread
==============================
>>> Conf.unlock('p2', lock_key="cortx>p>lock", lock_owner = 'p2')
False
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
True
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
True
>>> 

# test_unlock
============
>>> Conf.unlock('p1', lock_key="cortx>p>lock", lock_owner = 'p1')
True
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
False
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
False
>>> 

# test_unlock_repeat
================
>>> Conf.unlock('p1', lock_key="cortx>p>lock", lock_owner = 'p1')
False
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
False
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
False
>>> 

# test_lock_from_other_thread_after_unlock
=====================================
>>> Conf.lock('p2', lock_key="cortx>p>lock", lock_owner="p2")
True
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
True
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
True
>>> 
# test_force_unlock_from_other_thread
=================================
>>> Conf.unlock('p1', lock_key="cortx>p>lock", force=True)
True
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
False
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
False
>>> 
# test_repeat_unlock_from_other_thread
==================================
>>> Conf.unlock('p2', lock_key="cortx>p>lock", lock_owner = 'p2')
False
>>> Conf.test_lock('p1', lock_key="cortx>p>lock")
False
>>> Conf.test_lock('p2', lock_key="cortx>p>lock")
False
>>> 

Process set 2:
============
# test_lock_with_timeout
=====================
>>> Conf.lock('m2', lock_key="cortx>m>lock", lock_owner="m2", timeout=10)
True
>>> Conf.test_lock('m2', lock_key="cortx>m>lock")
True
>>> Conf.test_lock('m1', lock_key="cortx>m>lock")
True

2022-07-18 05:19 UTC, nitin-seagate requested changes

2022-07-18 05:19 UTC, nitin-seagate commented on py-utils/src/utils/const.py
> +LOCK_TIME_KEY = "%s>lock_time"
Lets keep this value as:
`%s>time`

2022-07-18 05:20 UTC, nitin-seagate approved these changes
LGTM

2022-07-18 05:22 UTC, kailashyadav11 commented on py-utils/src/utils/const.py
> +LOCK_TIME_KEY = "%s>lock_time"
done

2022-07-19 08:42 UTC, kailashyadav11 commented
Process took the lock and died. Process was able to recover from it.

Race Conditions between test and set. By injecting fault in between, e.g. sleep (1).

Process calling lock twice in a row (should be allowed).



5 threads trying to acquire lock at the same time.
=========================================

2022-07-18 22:57:45.915911 Lock Status for ITQ0U1AIMDE0: False 
2022-07-18 22:57:45.921836 Lock Status for ITQ0U1AIMDE3: False 
2022-07-18 22:57:45.917919 Lock Status for ITQ0U1AIMDE1: False 
2022-07-18 22:57:45.923640 Lock Status for ITQ0U1AIMDE4: False 
2022-07-18 22:57:45.919966 Lock Status for ITQ0U1AIMDE2: True 

3 processes trying to acquire lock 5 times each:
======================================

Run Count: 1
Thread count: 3
Repeat: 5
2022-07-19 00:39:41.070084 Reset status: True
Run: 1
Lock Rep TOWWI7NC9VQ0 1
Lock Rep TOWWI7NC9VQ1 1
Done
Lock Rep TOWWI7NC9VQ2 1
2022-07-19 00:39:41.114015 Lock Status for TOWWI7NC9VQ1: False 
Lock Rep TOWWI7NC9VQ1 2
2022-07-19 00:39:41.115860 Lock Status for TOWWI7NC9VQ2: True 
Lock Rep TOWWI7NC9VQ2 2
2022-07-19 00:39:41.117784 Lock Status for TOWWI7NC9VQ0: False 
Lock Rep TOWWI7NC9VQ0 2
2022-07-19 00:39:41.119718 Lock Status for TOWWI7NC9VQ2: True 
Lock Rep TOWWI7NC9VQ2 3
2022-07-19 00:39:41.122798 Lock Status for TOWWI7NC9VQ0: False 
Lock Rep TOWWI7NC9VQ0 3
2022-07-19 00:39:41.123541 Lock Status for TOWWI7NC9VQ1: False 
Lock Rep TOWWI7NC9VQ1 3
2022-07-19 00:39:41.127345 Lock Status for TOWWI7NC9VQ2: True 
Lock Rep TOWWI7NC9VQ2 4
2022-07-19 00:39:41.127843 Lock Status for TOWWI7NC9VQ0: False 
Lock Rep TOWWI7NC9VQ0 4
2022-07-19 00:39:41.132311 Lock Status for TOWWI7NC9VQ2: True 
Lock Rep TOWWI7NC9VQ2 5
2022-07-19 00:39:41.132908 Lock Status for TOWWI7NC9VQ1: False 
Lock Rep TOWWI7NC9VQ1 4
2022-07-19 00:39:41.137638 Lock Status for TOWWI7NC9VQ0: False 
Lock Rep TOWWI7NC9VQ0 5
2022-07-19 00:39:41.137977 Lock Status for TOWWI7NC9VQ2: True 
2022-07-19 00:39:41.143745 Lock Status for TOWWI7NC9VQ1: False 
Lock Rep TOWWI7NC9VQ1 5
2022-07-19 00:39:41.148938 Lock Status for TOWWI7NC9VQ0: False 

Multiple threads trying to lock unlock multiple times.
===========================================
2022-07-19 00:32:45.766863 Lock Status for HITNFB63AIZ1: True 
Unlock Rep HITNFB63AIZ1 1
2022-07-19 00:32:45.769798 UnLock Status for HITNFB63AIZ2: False 
Rep HITNFB63AIZ2 3
Lock Rep HITNFB63AIZ2 1
2022-07-19 00:32:45.774361 Lock Status for HITNFB63AIZ2: False 
Unlock Rep HITNFB63AIZ2 1
2022-07-19 00:32:45.777631 UnLock Status for HITNFB63AIZ1: True 
Rep HITNFB63AIZ1 2
Lock Rep HITNFB63AIZ1 1
2022-07-19 00:32:45.778707 UnLock Status for HITNFB63AIZ2: False 
Rep HITNFB63AIZ2 4
Lock Rep HITNFB63AIZ2 1
2022-07-19 00:32:45.801120 Lock Status for HITNFB63AIZ1: False 
Unlock Rep HITNFB63AIZ1 1
2022-07-19 00:32:45.804985 Lock Status for HITNFB63AIZ2: True 
Unlock Rep HITNFB63AIZ2 1
2022-07-19 00:32:45.806915 UnLock Status for HITNFB63AIZ1: False 
Rep HITNFB63AIZ1 3
Lock Rep HITNFB63AIZ1 1
2022-07-19 00:32:45.811191 Lock Status for HITNFB63AIZ1: False 
Unlock Rep HITNFB63AIZ1 1
2022-07-19 00:32:45.817819 UnLock Status for HITNFB63AIZ2: True 
Rep HITNFB63AIZ2 5
Lock Rep HITNFB63AIZ2 1
2022-07-19 00:32:45.818138 UnLock Status for HITNFB63AIZ1: False 
Rep HITNFB63AIZ1 4
Lock Rep HITNFB63AIZ1 1
2022-07-19 00:32:45.834761 Lock Status for HITNFB63AIZ1: False 
Unlock Rep HITNFB63AIZ1 1
2022-07-19 00:32:45.839163 UnLock Status for HITNFB63AIZ1: False 
Rep HITNFB63AIZ1 5
Lock Rep HITNFB63AIZ1 1
2022-07-19 00:32:45.845217 Lock Status for HITNFB63AIZ1: False 
Unlock Rep HITNFB63AIZ1 1
2022-07-19 00:32:45.849586 UnLock Status for HITNFB63AIZ1: False 
2022-07-19 00:32:45.851468 Lock Status for HITNFB63AIZ2: True 
Unlock Rep HITNFB63AIZ2 1
2022-07-19 00:32:45.865772 UnLock Status for HITNFB63AIZ2: True 


multiple threads lock and force unlock 
===============================

Run Count: 1
Thread count: 2
Repeat: 5
2022-07-19 00:37:18.418555 Reset status: True
Run: 1
Done
Rep ZVG27VDAQHD0 1
Lock Rep ZVG27VDAQHD0 1
Rep ZVG27VDAQHD1 1
Lock Rep ZVG27VDAQHD1 1
2022-07-19 00:37:18.546460 Lock Status for ZVG27VDAQHD0: False 
2022-07-19 00:37:18.549559 Lock Status for ZVG27VDAQHD1: True 
2022-07-19 00:37:18.555484 Reset status: True
Rep ZVG27VDAQHD0 2
Lock Rep ZVG27VDAQHD0 1
2022-07-19 00:37:18.556951 Reset status: True
Rep ZVG27VDAQHD1 2
Lock Rep ZVG27VDAQHD1 1
2022-07-19 00:37:18.572553 Lock Status for ZVG27VDAQHD0: False 
2022-07-19 00:37:18.575213 Lock Status for ZVG27VDAQHD1: True 
2022-07-19 00:37:18.581313 Reset status: True
Rep ZVG27VDAQHD0 3
Lock Rep ZVG27VDAQHD0 1
2022-07-19 00:37:18.583240 Reset status: True
Rep ZVG27VDAQHD1 3
Lock Rep ZVG27VDAQHD1 1
2022-07-19 00:37:18.603573 Lock Status for ZVG27VDAQHD0: False 
2022-07-19 00:37:18.613574 Reset status: True
Rep ZVG27VDAQHD0 4
Lock Rep ZVG27VDAQHD0 1
2022-07-19 00:37:18.620750 Lock Status for ZVG27VDAQHD1: False 
2022-07-19 00:37:18.633491 Reset status: True
Rep ZVG27VDAQHD1 4
Lock Rep ZVG27VDAQHD1 1
2022-07-19 00:37:18.635291 Lock Status for ZVG27VDAQHD0: False 
2022-07-19 00:37:18.645258 Reset status: True
Rep ZVG27VDAQHD0 5
Lock Rep ZVG27VDAQHD0 1
2022-07-19 00:37:18.649250 Lock Status for ZVG27VDAQHD1: False 
2022-07-19 00:37:18.658955 Reset status: True
Rep ZVG27VDAQHD1 5
Lock Rep ZVG27VDAQHD1 1
2022-07-19 00:37:18.666740 Lock Status for ZVG27VDAQHD0: False 
2022-07-19 00:37:18.678441 Reset status: True
2022-07-19 00:37:18.695686 Lock Status for ZVG27VDAQHD1: False 
2022-07-19 00:37:18.708616 Reset status: True


Process calling more than once should be allowed
==========================================
[root@ssc-vm-rhev4-2199 conf_store]# python3 conf_store_lock.py
Run Count: 1
Thread count: 1
Repeat: 10
2022-07-19 00:47:35.428155 Reset status: True
Run: 1
Done
Lock Rep PJFT7CNMX8K0 1
2022-07-19 00:47:35.468186 Lock Status for PJFT7CNMX8K0: True 
Lock Rep PJFT7CNMX8K0 2
2022-07-19 00:47:35.473115 Lock Status for PJFT7CNMX8K0: True 
Lock Rep PJFT7CNMX8K0 3
2022-07-19 00:47:35.478589 Lock Status for PJFT7CNMX8K0: True 
Lock Rep PJFT7CNMX8K0 4
2022-07-19 00:47:35.483908 Lock Status for PJFT7CNMX8K0: True 
Lock Rep PJFT7CNMX8K0 5
2022-07-19 00:47:35.488946 Lock Status for PJFT7CNMX8K0: True 
Lock Rep PJFT7CNMX8K0 6
2022-07-19 00:47:35.494625 Lock Status for PJFT7CNMX8K0: True 
Lock Rep PJFT7CNMX8K0 7
2022-07-19 00:47:35.498637 Lock Status for PJFT7CNMX8K0: True 
Lock Rep PJFT7CNMX8K0 8
2022-07-19 00:47:35.506253 Lock Status for PJFT7CNMX8K0: True 
Lock Rep PJFT7CNMX8K0 9
2022-07-19 00:47:35.512072 Lock Status for PJFT7CNMX8K0: True 
Lock Rep PJFT7CNMX8K0 10
2022-07-19 00:47:35.517620 Lock Status for PJFT7CNMX8K0: True 
[root@ssc-vm-rhev4-2199 conf_store]# 

Race condition between test and set:
==============================
Run Count: 1

Thread count: 3
Repeat: 2
2022-07-19 01:32:22.684650 Reset status: True
Run: 1
Rep OO6JKBX0QVZ0 1
Lock Rep OO6JKBX0QVZ0 1
Rep OO6JKBX0QVZ1 1
Lock Rep OO6JKBX0QVZ1 1
Rep OO6JKBX0QVZ2 1
Lock Rep OO6JKBX0QVZ2 1
2022-07-19 01:32:22.725739 Lock Status for OO6JKBX0QVZ0: False 
2022-07-19 01:32:22.727230 Lock Status for OO6JKBX0QVZ1: False 
2022-07-19 01:32:22.729129 Lock Status for OO6JKBX0QVZ2: True 
Test Lock Rep OO6JKBX0QVZ0 1
Test Lock Rep OO6JKBX0QVZ1 1
Test Lock Rep OO6JKBX0QVZ2 1
2022-07-19 01:32:23.726355 Test Lock Status for OO6JKBX0QVZ0: True
Unlock Rep OO6JKBX0QVZ0 1
2022-07-19 01:32:23.728085 Test Lock Status for OO6JKBX0QVZ1: True
Unlock Rep OO6JKBX0QVZ1 1
2022-07-19 01:32:23.729524 Test Lock Status for OO6JKBX0QVZ2: True
Unlock Rep OO6JKBX0QVZ2 1
2022-07-19 01:32:23.733650 UnLock Status for OO6JKBX0QVZ0: False 
2022-07-19 01:32:23.734825 UnLock Status for OO6JKBX0QVZ1: False 
2022-07-19 01:32:23.741932 UnLock Status for OO6JKBX0QVZ2: True 
Test Lock Rep OO6JKBX0QVZ0 1
Test Lock Rep OO6JKBX0QVZ1 1
2022-07-19 01:32:24.735050 Test Lock Status for OO6JKBX0QVZ0: False
Rep OO6JKBX0QVZ0 2
Lock Rep OO6JKBX0QVZ0 1
2022-07-19 01:32:24.736099 Test Lock Status for OO6JKBX0QVZ1: False
Rep OO6JKBX0QVZ1 2
Lock Rep OO6JKBX0QVZ1 1
Test Lock Rep OO6JKBX0QVZ2 1
2022- [...]

2022-07-19 14:03 UTC, ujjwalpl approved these changes

2022-07-19 16:33 UTC, cdeshmukh commented
retest this please

2022-07-19 16:40 UTC, rahul-tripathi-git commented
Hi @kailashyadav11 
Please add test cases for the same, else raise a JIRA ticket if this needs to be merged immediately.

2022-07-19 16:45 UTC, kailashyadav11 commented
> Hi @kailashyadav11 Please add test cases for the same, else raise a JIRA ticket if this needs to be merged immediately.

@rahul-tripathi-git  https://jts.seagate.com/browse/CORTX-33672 please find the ticket for the same.

2022-07-19 17:02 UTC, cdeshmukh commented on py-utils/src/utils/conf_store/conf_store.py
> +        while self.timeout > 1:
what this timeout playing role here i dont nderstand. if lock acquire fails, it should retry until this timeout value, should be the logic i think, but here timeout being exhausted without lock being acquired?

2022-07-19 17:07 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_store.py
> +        self.lock_owner = self.default_owner
the parameters required for lock and unlock are a bit different in some cases like the parameter 'force' is not required in lock function

2022-07-19 17:08 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_store.py
> +        _is_locked = self._get_lock_owner(index, self.lock_key) == self.lock_owner
it holds a boolean value whether the lock owner  is the current owner and not the owner details hence _is_locked

2022-07-19 17:08 UTC, cdeshmukh commented on py-utils/src/utils/conf_store/conf_store.py
> +            if key == 'force' and not isinstance(value, bool):
so any thread can over ride with force!? how only one thread would over-ride and in what case?

2022-07-19 17:10 UTC, cdeshmukh commented on py-utils/src/utils/conf_store/conf_store.py
> +        _is_locked = self._get_lock_owner(index, self.lock_key) == self.lock_owner
yeah i updated comment while you were replying i guess. lock_owned clarify the expected value & its meaning

2022-07-19 17:11 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_store.py
> +            if key == 'force' and not isinstance(value, bool):
one thread can lock and do the job and unlock the resource, until then all other threads will be waiting.

and force unlock is when the lock is not released by the owner in an expected time say if it hanged, the other threads cna takeover the lock with force release

2022-07-19 17:18 UTC, cdeshmukh commented on py-utils/src/utils/conf_store/conf_store.py
> +            setattr(self, key, value)
why lock_key is being set here, which is already at line 349. And this set even needed when its only a check whether a lock exist, get should suffice !
> self.lock_key = const.LOCK_KEY

2022-07-19 17:21 UTC, cdeshmukh commented on py-utils/src/utils/conf_store/conf_store.py
> +        while self.timeout > 1:
> this was added to wait until an expected time known to user 

wait before acquiring lock? what usecase if this?

2022-07-19 17:22 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_store.py
> +            setattr(self, key, value)
if we check lock exists then other instances may not be able to create their own lock section

2022-07-19 17:26 UTC, cdeshmukh commented on py-utils/src/utils/conf_store/conf_store.py
> +            if key == 'force' and not isinstance(value, bool):
lets say thread 1 was hung after acquiring lock, and thread 2 & 3 started waiting, all threads initiated by different owners. After a threshold, thread 2 takes over lock by force, how its made sure thread 3 doesnt also initiate same take over by force, unless owner per lock acquisition is tracked.

2022-07-19 17:28 UTC, kailashyadav11 commented
https://jts.seagate.com/browse/CORTX-33673 Improvement ticket 
cc: @cdeshmukh  @jaikumargidwani  @rahul-tripathi-git  @nitin-seagate

2022-07-19 17:29 UTC, cdeshmukh commented on py-utils/src/utils/conf_store/conf_store.py
> +            setattr(self, key, value)
so conf lock can be used for common conf across CORTX component threads using const.LOCK_KEY, or within component threads with respective component locks !? If yes, then i understand

prior design discussion would have helped!

2022-07-19 17:31 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_store.py
> +        while self.timeout > 1:
if we expect certain resource to be unlocked in n time then we wait for n time and acquire the lock.
we can add keep retrying logic as you suggested in the loop.
I was planning to add a condition check in the loop which will exit the loop once satisified.

2022-07-19 17:34 UTC, cdeshmukh commented on py-utils/src/utils/conf_store/conf_store.py
> +        while self.timeout > 1:
> if we expect certain resource to be unlocked in n time then we wait for n time

how a thread can figure out in how much time lock can be available, there can a wait threshold for retry if lock acquisition fails, which is after 1st try

2022-07-19 17:35 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_store.py
> +            if key == 'force' and not isinstance(value, bool):
True, this scenario should be covered here. 
if thread 2 force unlocks and takes lock the waiting threads can also initiate force unlock.

2022-07-19 17:37 UTC, cdeshmukh commented
![image](https://user-images.githubusercontent.com/32053979/179814215-6c00d5ac-e1c9-494c-9ddb-bf70acf1949d.png)
1N deployment passed
https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/py-utils/549/

2022-07-19 17:44 UTC, cdeshmukh approved these changes

2022-07-19 17:44 UTC, kailashyadav11 commented on py-utils/src/utils/conf_store/conf_store.py
> +        while self.timeout > 1:
taking this in improvement

2022-07-19 17:44 UTC, merged