EOS-13955 : ETag changes for fs PUT Request
Seagate/cortx-utils pull request #86
Opened 2020-11-06 09:42 UTC by SeagateChaDeepak

If ETag is sent in request then its a modification request.
In this case we fail the request.

On successful execution of fs PUT Request we send the fs
object in response along with its ETag in http headers.

Signed-off-by: Deepak Mahale <deepak.mahale@seagate.com>

**Test Script Results :** 

> bash-4.2$ sudo ./scripts/test.sh
> [sudo] password for 753450:
> 
> Configuration Completed
> Clean indexes prepared
> NSAL Unit tests
> NS Tests
> Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
> Total tests  = 5
> Tests passed = 5
> Tests failed = 0
> 
> Iterator test
> Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
> Total tests  = 2
> Tests passed = 2
> Tests failed = 0
> 
> KVTree test
> Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
> Total tests  = 17
> Tests passed = 17
> Tests failed = 0
> 
> Global KVS Tests
> Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
> Total tests  = 4
> Tests passed = 4
> Tests failed = 0
> 
> CORTXFS Unit tests
> Endpoint ops Tests
> Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.logs
> Total tests  = 4
> Tests passed = 4
> Tests failed = 0
> 
> FS Tests
> Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
> Total tests  = 3
> Tests passed = 3
> Tests failed = 0
> 
> Directory tests
> Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
> Total tests  = 14
> Tests passed = 14
> Tests failed = 0
> 
> File creation tests
> Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
> Total tests  = 4
> Tests passed = 4
> Tests failed = 0
> 
> Link Tests
> Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
> Total tests  = 6
> Tests passed = 6
> Tests failed = 0
> 
> Rename tests
> Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
> Total tests  = 3
> Tests passed = 3
> Tests failed = 0
> 
> Attribute Tests
> Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
> Total tests  = 5
> Tests passed = 5
> Tests failed = 0
> 
> Xattr file Tests
> Test results are logged to /var/log/cortx/test/ut/xattr_file_ops.log
> Total tests  = 9
> Tests passed = 9
> Tests failed = 0
> 
> Xattr dir Tests
> Test results are logged to /var/log/cortx/test/ut/xattr_dir_ops.log
> Total tests  = 9
> Tests passed = 9
> Tests failed = 0
> 
> IO tests
> Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.log
> Total tests  = 7
> Tests passed = 7
> Tests failed = 0
> 
> DSAL Unit tests
> Dsal basic test
> Test results are logged to /var/log/cortx/test/ut/ut_dsal.log
> Total tests  = 11
> Tests passed = 11
> Tests failed = 0
> 
> Dsal IO test
> Test results are logged to /var/log/cortx/test/ut/ut_dsal.log
> Total tests  = 2
> Tests passed = 2
> Tests failed = 0
> 
> Dsal space stats test
> Test results are logged to /var/log/cortx/test/ut/ut_dsal.log
> Total tests  = 2
> Tests passed = 2
> Tests failed = 0

2020-11-10 10:41 UTC, Shreya-18 requested changes

2020-11-10 10:41 UTC, Shreya-18 commented on c-utils/src/management/request-handler.c
> +	//Get the etag (object hash) for the request.
We follow comments in this style 
`/*      .....       */`

Please change it here and else where.

2020-11-10 10:41 UTC, Shreya-18 commented on c-utils/src/management/request-handler.c
> +	request_init_etag(request);
Question: Shouldn't we initialize the ETag field in the request object somewhere like `request_init()` or an appropriate place?

2020-11-10 10:56 UTC, Shreya-18 requested changes

2020-11-10 10:56 UTC, Shreya-18 commented on c-utils/src/management/request-handler.c
> +	request_set_input_etag_value(request, etag_str);
In most of the cases, there won't be "if-match" header, so  `etag_str ` will be null. Should we have a simple check to avoid an extra function call?
``` 
if (etag_str) {
       request_set_input_etag_value()
}
```

2020-11-10 15:01 UTC, SeagateChaDeepak commented on c-utils/src/management/request-handler.c
> +	//Get the etag (object hash) for the request.
Done.

2020-11-10 15:01 UTC, SeagateChaDeepak commented on c-utils/src/management/request-handler.c
> +	request_init_etag(request);
Done.

2020-11-10 15:01 UTC, SeagateChaDeepak commented on c-utils/src/management/request-handler.c
> +	request_set_input_etag_value(request, etag_str);
Done.

2020-11-11 05:22 UTC, Shreya-18 commented
LGTM, +1. Nicely integrated with the ETag header.

2020-11-11 05:22 UTC, Shreya-18 approved these changes

2020-11-11 07:53 UTC, sachinpunadikar approved these changes
+1

2020-11-11 08:01 UTC, merged