CORTX-32806: Query Deployment api
Seagate/cortx-utils pull request #863
Opened 2022-08-02 11:28 UTC by lakshita-jain

Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>

# Problem Statement
- Query Deployment API code for CSM to utilize for query deployment api which returns the topology as per the requirement of the API using Gconf Data

# Design
Approach followed for generating query deployment topology:

1.  Load input url and copy it to temporary yaml url
2. Remove num_ and unwanted keys from temporary url
3. convert temporary url to dict 
4. process dict data to according to given topology format in HLD.
5. return dict topology.

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-08-02 11:40 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-08-02 12:44 UTC, tanujashinde0405 requested changes

2022-08-02 12:44 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +            _config["nodes"].append(json.dumps(nodes_info))
follow wither single quotes or double quotes for variables

2022-08-02 12:44 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        not_required_keys=['num_','nodes']
resolve codacy issues.

2022-08-02 12:44 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +    _local_file = '/tmp/local_conf.conf'
either follow single quotes or double quotes for strings

2022-08-02 12:45 UTC, tanujashinde0405 requested changes

2022-08-02 12:45 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +                        if storage_key!='nodes':
add spaces before and after =

2022-08-02 12:47 UTC, tanujashinde0405 requested changes

2022-08-02 12:47 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +            # if 'nodes'in key:
remove this commented code if not required

2022-08-02 12:47 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        #cortx_info
write proper comments on what the code section is fetching

2022-08-02 12:47 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +                if key=='provisioning':
check if such hardcoded values can be added to const.py

2022-08-02 14:11 UTC, tanujashinde0405 approved these changes
LGTM

2022-08-02 14:28 UTC, nitin-seagate requested changes

2022-08-02 14:28 UTC, nitin-seagate commented on py-utils/src/utils/query_deployment/query_deployment.py
> +    """Query Data."""
Query Configuration Data

2022-08-02 14:28 UTC, nitin-seagate commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _f = QueryConfData._local_file
We should not delete any file here in init.... Please move this to section where we create file

2022-08-02 14:28 UTC, nitin-seagate commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        from cortx.utils.conf_store import ConfStore
Remove this, reuse included header from top...

2022-08-02 14:28 UTC, nitin-seagate commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _data = _cs.get_data(QueryConfData._data_idx)
Just before returning data, unload and cleanup local file

2022-08-02 14:28 UTC, nitin-seagate commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        # to fetch cortx info
# to fetch common info

2022-08-02 14:28 UTC, nitin-seagate commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        # to fetch cluster_info
# to fetch cluster info

2022-08-02 14:28 UTC, nitin-seagate commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        # to fetch Nodes Info
# to fetch nodes info

2022-08-02 14:49 UTC, tanujashinde0405 requested changes

2022-08-02 14:49 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +    def _get_cortx_topology(data: dict) -> dict:
please make sure , After deployment API is working and returning correct topology.
Paste the results in PR description.

2022-08-02 14:49 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        nd = lambda: defaultdict(nd)
rename nd

2022-08-02 15:46 UTC, tanujashinde0405 requested changes

2022-08-02 15:46 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +class QueryDeploymentError(Exception):
move this class to error.py and use utilsError

2022-08-02 15:48 UTC, tanujashinde0405 requested changes

2022-08-02 15:48 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _f = QueryConfData._local_file
move this variable and move the delete code at the end of return data

2022-08-02 15:55 UTC, tanujashinde0405 requested changes

2022-08-02 15:55 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _cs = ConfStore()
Lets remove this _cs and directly load _data_idx using Conf which is already imported

2022-08-02 15:55 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _config["cortx"]["common"]["release"] = data["cortx"]["common"]["release"]
replace double quoted with single quotes in data[]

2022-08-02 16:35 UTC, tanujashinde0405 approved these changes
please make sure , After deployment API is working and returning correct topology.
Paste the results in PR description.

2022-08-02 18:12 UTC, lakshita-jain commented
@tanujashinde0405 : here's the output
`>>> from cortx.utils.query_deployment import QueryDeployment
>>> QueryDeployment.get_cortx_topology('consul://cortx-consul-server:8500/conf')
{'cortx': {'common': {'release': {'name': 'CORTX', 'version': '2.0.0-7423'}}}, 'cluster': ['{"security": {"device_certificate": "/etc/cortx/solution/ssl/stx.pem", "domain_certificate": "/etc/cortx/solution/ssl/stx.pem", "ssl_certificate": "/etc/cortx/solution/ssl/s3.seagate.com.pem"}, "storage_set": [{"durability": {"dix": {"data": "1", "parity": "0", "spare": "0"}, "sns": {"data": "1", "parity": "0", "spare": "0"}}, "name": "storage-set-1"}]}'], 'nodes': ['{"machine_id": "3b404b96fc01319b5edb2e84e323595a", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "hare", "version": "2.0.0-7423"}, {"name": "rgw", "services": ["rgw_s3"], "version": "2.0.0-7423"}], "hostname": "cortx-server-1.cortx-server-headless.cortx.svc.cluster.local", "name": "cortx-server-1", "node_id": "cortx-server-1.cortx-server-headless.cortx.svc.cluster.local", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "server_node"}', '{"machine_id": "6ac2b08cfe659acf910fed4d11b7df53", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "motr", "services": ["io"], "version": "2.0.0-7423"}, {"name": "hare", "version": "2.0.0-7423"}], "cvg": [{"devices": {"data": ["/dev/sdd", "/dev/sde"], "metadata": ["/dev/sdc"]}, "name": "cvg-01", "type": "ios"}], "hostname": "cortx-data-g0-2.cortx-data-headless.cortx.svc.cluster.local", "name": "cortx-data-g0-2", "node_group": "ssc-vm-g2-rhev4-3385.colo.seagate.com", "node_id": "cortx-data-g0-2.cortx-data-headless.cortx.svc.cluster.local", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "data_node/0"}', '{"machine_id": "7ba8990a85d38508ca9bac4ff516d3ea", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "motr", "services": ["io"], "version": "2.0.0-7423"}, {"name": "hare", "version": "2.0.0-7423"}], "cvg": [{"devices": {"data": ["/dev/sdd", "/dev/sde"], "metadata": ["/dev/sdc"]}, "name": "cvg-01", "type": "ios"}], "hostname": "cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local", "name": "cortx-data-g0-0", "node_group": "ssc-vm-g2-rhev4-3387.colo.seagate.com", "node_id": "cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "data_node/0"}', '{"machine_id": "7d9ee991ae6ce628a0e10294bdebaa6b", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "ha", "version": "2.0.0-7423"}], "hostname": "cortx-ha-headless", "name": "cortx-ha", "node_id": "cortx-ha-headless", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "ha_node"}', '{"machine_id": "aa378e768a2ba5291d786b3dc48d5650", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "motr", "services": ["io"], "version": "2.0.0-7423"}, {"name": "hare", "version": "2.0.0-7423"}], "cvg": [{"devices": {"data": ["/dev/sdg", "/dev/sdh"], "metadata": ["/dev/sdf"]}, "name": "cvg-02", "type": "ios"}], "hostname": "cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local", "name": "cortx-data-g1-0", "node_group": "ssc-vm-g2-rhev4-3387.colo.seagate.com", "node_id": "cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "data_node/1"}', '{"machine_id": "ac2f9656e38a92990522025e1f3ccaef", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "hare", "version": "2.0.0-7423"}, {"name": "rgw", "services": ["rgw_s3"], "version": "2.0.0-7423"}], "hostname": "cortx-server-0.cortx-server-headless.cortx.svc.cluster.local", "name": "cortx-server-0", "node_id": "cortx-server-0.cortx-server-headless.cortx.svc.cluster.local", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "server_node"}', '{"machine_id": "cd1e4c61d297a784245dd88106262cd3", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "motr", "services": ["io"], "version": "2.0.0-7423"}, {"name": "hare", "version": "2.0.0-7423"}], "cvg": [{"devices": {"data": ["/dev/sdd", "/dev/sde"], "metadata": ["/dev/sdc"]}, "name": "cvg-01", "type": "ios"}], "hostname": "cortx-data-g0-1.cortx-data-headless.cortx.svc.cluster.local", "name": "cortx-data-g0-1", "node_group": "ssc-vm-g2-rhev4-3386.colo.seagate.com", "node_id": "cortx-data-g0-1.cortx-data-headless.cortx.svc.cluster.local", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "data_node/0"}', '{"machine_id": "d62dc0d2c3ee12aee9b946379519133a", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "hare", "version": "2.0.0-7423"}, {"name": "rgw", "services": ["rgw_s3"], "version": "2.0.0-7423"}], "hostname": "cortx-server-2.cortx-server-headless.cortx.svc.cluster.local", "name": "cortx-server-2", "node_id": "cortx-server-2.cortx-server-headless.cortx.svc.cluster.local", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "server_node"}', '{"machine_id": "ecabccb4bced858e282f568d6bf04558", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "csm", "services": ["agent"], "version": "2.0.0-7423"}], "hostname": "cortx-control", "name": "cortx-control", "node_id": "cortx-control", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "control_node"}', '{"machine_id": "f488442b875fe8c4328e148f8aca7aa7", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "motr", "services": ["io"], "version": "2.0.0-7423"}, {"name": "hare", "version": "2.0.0-7423"}], "cvg": [{"devices": {"data": ["/dev/sdg", "/dev/sdh"], "metadata": ["/dev/sdf"]}, "name": "cvg-02", "type": "ios"}], "hostname": "cortx-data-g1-2.cortx-data-headless.cortx.svc.cluster.local", "name": "cortx-data-g1-2", "node_group": "ssc-vm-g2-rhev4-3385.colo.seagate.com", "node_id": "cortx-data-g1-2.cortx-data-headless.cortx.svc.cluster.local", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "data_node/1"}', '{"machine_id": "fae544140e673b0f2a0d26cb2011516a", "cluster_id": "8ba28deb-4e10-4f07-a32d-ab0d2aed7ffe", "components": [{"name": "utils", "version": "2.0.0-7423"}, {"name": "motr", "services": ["io"], "version": "2.0.0-7423"}, {"name": "hare", "version": "2.0.0-7423"}], "cvg": [{"devices": {"data": ["/dev/sdg", "/dev/sdh"], "metadata": ["/dev/sdf"]}, "name": "cvg-02", "type": "ios"}], "hostname": "cortx-data-g1-1.cortx-data-headless.cortx.svc.cluster.local", "name": "cortx-data-g1-1", "node_group": "ssc-vm-g2-rhev4-3386.colo.seagate.com", "node_id": "cortx-data-g1-1.cortx-data-headless.cortx.svc.cluster.local", "version": "2.0.0-7423", "storage_set": "storage-set-1", "type": "data_node/1"}']}
`

2022-08-02 18:18 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +    def _get_cortx_topology(data: dict) -> dict:
I have Pasted the results below

2022-08-03 01:13 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        # to fetch Nodes Info
Done

2022-08-03 01:14 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _data = _cs.get_data(QueryConfData._data_idx)
Done

2022-08-03 01:14 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _f = QueryConfData._local_file
Done

2022-08-03 01:14 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +    """Query Data."""
Done

2022-08-03 02:57 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        from cortx.utils.conf_store import ConfStore
Done

2022-08-03 02:58 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        # to fetch cluster_info
Done

2022-08-03 02:58 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        # to fetch Nodes Info
Done

2022-08-03 02:58 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +    def _get_cortx_topology(data: dict) -> dict:
Done

2022-08-03 02:58 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _data = _cs.get_data(QueryConfData._data_idx)
Done

2022-08-03 03:17 UTC, nitin-seagate approved these changes
LGTM

2022-08-03 03:23 UTC, sachinpunadikar approved these changes
+1

2022-08-03 03:26 UTC, lakshita-jain commented
Deployement  successful; https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/10281/

2022-08-03 03:27 UTC, merged