[WIP] CORTX-33673: Improvement for lock-unlock interface with lock end time…
Seagate/cortx-utils pull request #869
Opened 2022-08-05 06:55 UTC by tanujashinde0405

… implementation

Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>

# Problem Statement
- Improve lock unlock interfaces code written in utils by adding the duration of lock to be acquired by a thread.

# Design
Added new parameter in lock as duration which will update for how much time a thread can acquire lock.
if a new thread wants to acquire the lock, test_lock() interface will check if the lock_end time which is calculated by duration is less than current time and if the new thread can acquire the lock or not.

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-08-09 15:59 UTC, ujjwalpl requested changes

2022-08-09 15:59 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +            if self.get(index, const.LOCK_OWNER_PREFIX % self.domain) == self.lock_owner:
Add comment about why we are calling this.

2022-08-09 15:59 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        lock_owner(optional, default=machine_id): Unique instance of the domain who is sending  unlock request.
Same here. Limit chars in a single line.

2022-08-09 15:59 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        rc = False
Instead of setattr() or making class variables which may hamper other functions, its better to contain the values in local variables and not modify 'self'.

```
for key in kwargs.keys():
  if key not in allowed_keys:
    raise...

lock_owner = self.lock_owner if 'owner' not in kwargs.keys() else kwargs['owner']
if self.test_lock(index, lock_owner=self.lock_owner, domain=self.domain):
  ...
```

2022-08-09 15:59 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        allowed_keys = { 'domain' , 'lock_owner'}
We should not modify lock_owner for self. Instead use from the args. 

You should initialize the lock_owner in this function as well. Imagine calls like this.. 
```
Conf.test_lock('cortx', other_thread_id) # Testing for someone else. 
Conf.test_lock('cortx') # Testing for myself as per the spec. However this will test someone else
```

2022-08-09 15:59 UTC, ujjwalpl commented on py-utils/src/utils/conf_store/conf_store.py
> +        rc = False
Remove setattr(). please note self should not be modified as it may hamper the defaults. It should remain as parameters. 

```
for key in kwargs.keys():
  if key not in allowed_keys:
    raise...

lock_owner = self.lock_owner if 'owner' not in kwargs.keys() else kwargs['owner']
if self.test_lock(index, lock_owner=self.lock_owner, domain=self.domain):
  ...

2022-08-09 17:18 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        self.lock_owner = self._get_machine_id()
done

2022-08-09 17:19 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        self.lock_owner = self._get_machine_id()
done

2022-08-09 17:19 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        lock_owner(optional, default=machine_id): Unique instance of domain who is sending lock request.
done

2022-08-09 17:19 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        allowed_keys = { 'domain', 'lock_owner', 'duration' }
changed all to domain, owner , duration

2022-08-09 17:19 UTC, tanujashinde0405 commented on py-utils/src/utils/const.py
> +LOCK_OWNER_PREFIX = "lock>%s>owner"
done

2022-08-09 17:19 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +            if self.get(index, const.LOCK_OWNER_PREFIX % self.domain) == self.lock_owner:
done

2022-08-09 17:19 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        lock_owner(optional, default=machine_id): Unique instance of the domain who is sending  unlock request.
done

2022-08-09 17:19 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        rc = False
done

2022-08-09 17:20 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        allowed_keys = { 'domain' , 'lock_owner'}
done

2022-08-09 17:20 UTC, tanujashinde0405 commented on py-utils/src/utils/conf_store/conf_store.py
> +        rc = False
done

2022-08-09 18:00 UTC, ujjwalpl approved these changes

2022-08-09 18:05 UTC, ujjwalpl approved these changes

2022-08-10 05:47 UTC, nitin-seagate approved these changes
LGTM

2022-08-12 04:37 UTC, tanujashinde0405 reviewed
5 Node deployment successful with utils and provisioner feature branch:
https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/10825/

2022-08-12 04:39 UTC, lakshita-jain approved these changes

2022-08-12 05:58 UTC, merged