CORTX-33856: str to dict in topology
Seagate/cortx-utils pull request #870
Opened 2022-08-05 11:15 UTC by lakshita-jain

Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>

# Problem Statement
- The data in clusters field of output topology of query deployment is in string format need to change it into dictionary.

# Design
-  convert json.dumps value to dict by doing json.loads
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library 

# Coding 
-  Coding conventions are followed and code is consistent [Y/N]: 
-  Confirm All CODACY errors are resolved [Y/N]: 

# Testing
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:
- Confirm that Test Cases are added for new features added [Y/N]: 
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  

# Review Checklist 
####  Before posting the PR please ensure:
- [ ] PR is self reviewed
- [ ] Is there a change in filename/package/module or signature [Y/N]: 
- [ ] If yes for above point, Is a notification sent to all other cortx components [Y/N]
- [ ] New package/s added to setup.py?
- [ ] Jira is updated
- [ ] Check if the description is clear and explained. 
- [ ] Check Acceptance Criterion is defined. 
- [ ] All the tests performed should be mentioned before Resolving a JIRA. 
- [ ] Verification needs to be done before marked as Closed/Verified.

# KVstore/Confstore feature (changes/fixes) checklist
#### Confirm changes are made for:
- [ ] ConfStore
- [ ] KVStore
- [ ] ConfCli
- [ ] Test cases added for all above 3
- [ ] changes done in all the KVpayloads (ConsulKvPayload, IniKvPayload, KvPayload)

# Documentation
- [ ] Changes done to WIKI / Confluence page

2022-08-05 11:25 UTC, tanujashinde0405 requested changes

2022-08-05 11:25 UTC, tanujashinde0405 commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _config['clusters'].append((json.loads(json.dumps(cluster_info))))
@Pranali04796 @kupranay , do we have to change this to 'clusters'? or csm is going to handle it internally?

2022-08-08 04:21 UTC, tanujashinde0405 requested changes
Please post the schema outout getting returned in proper format here so we can validate it.

2022-08-08 04:28 UTC, pawankumarsrivastava commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        _config['clusters'].append((json.loads(json.dumps(cluster_info))))
CSM is currently handling it internally. Since, you are using 'nodes' as the key so 'clusters' here make sense. We can have the keys in sync but it is not mandatory.

2022-08-08 05:00 UTC, lakshita-jain commented
>>> from cortx.utils.query_deployment import QueryDeployment
>>> QueryDeployment.get_cortx_topology('consul://cortx-consul-server:8500/conf')
{'cortx': {'common': {'release': {'name': 'CORTX', 'version': '2.0.0-7451'}}}, 'clusters': [{'security': {'device_certificate': '/etc/cortx/solution/ssl/stx.pem', 'domain_certificate': '/etc/cortx/solution/ssl/stx.pem', 'ssl_certificate': '/etc/cortx/solution/ssl/s3.seagate.com.pem'}, 'storage_set': [{'durability': {'dix': {'data': '1', 'parity': '0', 'spare': '0'}, 'sns': {'data': '1', 'parity': '0', 'spare': '0'}}, 'name': 'storage-set-1'}]}], 'nodes': [{'machine_id': '7ba8990a85d38508ca9bac4ff516d3ea', 'cluster_id': '76997d94-6e2b-4918-ae13-fb368700dcea', 'components': [{'name': 'utils', 'version': '2.0.0-7451'}, {'name': 'motr', 'services': ['io'], 'version': '2.0.0-7451'}, {'name': 'hare', 'version': '2.0.0-7451'}], 'cvg': [{'devices': {'data': ['/dev/sdd', '/dev/sde'], 'metadata': ['/dev/sdc']}, 'name': 'cvg-01', 'type': 'ios'}], 'hostname': 'cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local', 'name': 'cortx-data-g0-0', 'node_group': 'ssc-vm-g4-rhev4-1881.colo.seagate.com', 'node_id': 'cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local', 'deployment_time': '1659693937', 'version': '2.0.0-7451', 'storage_set': 'storage-set-1', 'type': 'data_node/0'}, {'machine_id': '7d9ee991ae6ce628a0e10294bdebaa6b', 'cluster_id': '76997d94-6e2b-4918-ae13-fb368700dcea', 'components': [{'name': 'utils', 'version': '2.0.0-7451'}, {'name': 'ha', 'version': '2.0.0-7451'}], 'hostname': 'cortx-ha-headless', 'name': 'cortx-ha', 'node_id': 'cortx-ha-headless', 'deployment_time': '1659693922', 'version': '2.0.0-7451', 'storage_set': 'storage-set-1', 'type': 'ha_node'}, {'machine_id': 'aa378e768a2ba5291d786b3dc48d5650', 'cluster_id': '76997d94-6e2b-4918-ae13-fb368700dcea', 'components': [{'name': 'utils', 'version': '2.0.0-7451'}, {'name': 'motr', 'services': ['io'], 'version': '2.0.0-7451'}, {'name': 'hare', 'version': '2.0.0-7451'}], 'cvg': [{'devices': {'data': ['/dev/sdg', '/dev/sdh'], 'metadata': ['/dev/sdf']}, 'name': 'cvg-02', 'type': 'ios'}], 'hostname': 'cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local', 'name': 'cortx-data-g1-0', 'node_group': 'ssc-vm-g4-rhev4-1881.colo.seagate.com', 'node_id': 'cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local', 'deployment_time': '1659693942', 'version': '2.0.0-7451', 'storage_set': 'storage-set-1', 'type': 'data_node/1'}, {'machine_id': 'ac2f9656e38a92990522025e1f3ccaef', 'cluster_id': '76997d94-6e2b-4918-ae13-fb368700dcea', 'components': [{'name': 'utils', 'version': '2.0.0-7451'}, {'name': 'hare', 'version': '2.0.0-7451'}, {'name': 'rgw', 'services': ['rgw_s3'], 'version': '2.0.0-7451'}], 'hostname': 'cortx-server-0.cortx-server-headless.cortx.svc.cluster.local', 'name': 'cortx-server-0', 'node_id': 'cortx-server-0.cortx-server-headless.cortx.svc.cluster.local', 'deployment_time': '1659693982', 'version': '2.0.0-7451', 'storage_set': 'storage-set-1', 'type': 'server_node'}, {'machine_id': 'ecabccb4bced858e282f568d6bf04558', 'cluster_id': '76997d94-6e2b-4918-ae13-fb368700dcea', 'components': [{'name': 'utils', 'version': '2.0.0-7451'}, {'name': 'csm', 'services': ['agent'], 'version': '2.0.0-7451'}], 'hostname': 'cortx-control', 'name': 'cortx-control', 'node_id': 'cortx-control', 'deployment_time': '1659693925', 'version': '2.0.0-7451', 'storage_set': 'storage-set-1', 'type': 'control_node'}]}
>>>

2022-08-08 06:28 UTC, kupranay requested changes

2022-08-08 06:28 UTC, kupranay commented on py-utils/src/utils/query_deployment/query_deployment.py
>  class QueryConfData:
QueryClassData seems not to be a valid class name. It seems more like an action then a noun

class QueryDeployment: does not seems to be correct classname, its more like a verb then noun

2022-08-08 06:28 UTC, kupranay commented on py-utils/src/utils/query_deployment/query_deployment.py
>  class QueryConfData:
_local_file = "/tmp/local_conf.conf"
    _local_conf = "yaml://" + _local_file

what is the use of these variables. what if we are using this on and windows system and not on a linux system?
who is generating/creating local_conf file.  Not sure why file read and write is required. Can't we achieve it with in-memory data. File read write is a costly information and we should avoid it as much as possible

Conf.load(QueryConfData._data_idx, QueryConfData._local_conf)
        Conf.copy(QueryConfData._query_idx, QueryConfData._data_idx, _data_keys)
        Conf.save(QueryConfData._data_idx)


I dont think conf.save is required

2022-08-08 06:31 UTC, kupranay commented on py-utils/src/utils/query_deployment/query_deployment.py
>  class QueryConfData:
I can see a lot of useage of private variables which is being used as a statick variable. for example
QueryConfData._query_idx should be accessed as self.query_idx

2022-08-08 09:09 UTC, pawankumarsrivastava requested changes

2022-08-08 09:09 UTC, pawankumarsrivastava commented on py-utils/src/utils/query_deployment/query_deployment.py
>      """Query Configuration Data."""
QueryConfData, QueryDeployment and Topology are these 3 classes necessary? Also, this implementation is strongly attached to CORTX. 
In Utils it is advised to have interfaces that are nt directly bound to CORTX.

2022-08-08 09:09 UTC, pawankumarsrivastava commented on py-utils/src/utils/query_deployment/query_deployment.py
>      """Query Configuration Data."""
![image](https://user-images.githubusercontent.com/66408908/183381888-900a66af-c9f7-4b1b-b4fd-c6e1905001c0.png)
Codacy was also failing for thr initial checkin done

2022-08-08 09:09 UTC, pawankumarsrivastava commented on py-utils/src/utils/query_deployment/query_deployment.py
>      """Query Configuration Data."""
No test cases were added for this feature. Also, we should add an example on how to use the interface

2022-08-08 10:10 UTC, lakshita-jain commented
{'cortx': {'common': {'release': {'name': 'CORTX',
      'version': '2.0.0-7471'}}}, 'clusters': [{
    'security': {'device_certificate': '/etc/cortx/solution/ssl/stx.pem'
                 ,
                 'domain_certificate': '/etc/cortx/solution/ssl/stx.pem'
                 ,
                 'ssl_certificate': '/etc/cortx/solution/ssl/s3.seagate.com.pem'
                 },
    'id': '97811c6a-f072-473f-b5cf-3cc01ced699b',
    'name': 'cortx',
    'storage_set': [{'durability': {'dix': {'data': '1', 'parity': '0',
                    'spare': '0'}, 'sns': {'data': '1', 'parity': '0',
                    'spare': '0'}}, 'name': 'storage-set-1'}],
    }], 'nodes': [{
    'machine_id': '7ba8990a85d38508ca9bac4ff516d3ea',
    'cluster_id': '97811c6a-f072-473f-b5cf-3cc01ced699b',
    'components': [{'name': 'utils', 'version': '2.0.0-7471'},
                   {'name': 'motr', 'services': ['io'],
                   'version': '2.0.0-7471'}, {'name': 'hare',
                   'version': '2.0.0-7471'}],
    'cvg': [{'devices': {'data': ['/dev/sdd', '/dev/sde'],
            'metadata': ['/dev/sdc']}, 'name': 'cvg-01', 'type': 'ios'
            }],
    'hostname': 'cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local' ,
    'name': 'cortx-data-g0-0',
    'node_group': 'ssc-vm-g4-rhev4-1881.colo.seagate.com',
    'node_id': 'cortx-data-g0-0.cortx-data-headless.cortx.svc.cluster.local' ,
    'deployment_time': '1659941348',
    'version': '2.0.0-7471',
    'storage_set': 'storage-set-1',
    'type': 'data_node/0',
    }, {
    'machine_id': '7d9ee991ae6ce628a0e10294bdebaa6b',
    'cluster_id': '97811c6a-f072-473f-b5cf-3cc01ced699b',
    'components': [{'name': 'utils', 'version': '2.0.0-7471'},
                   {'name': 'ha', 'version': '2.0.0-7471'}],
    'hostname': 'cortx-ha-headless',
    'name': 'cortx-ha',
    'node_id': 'cortx-ha-headless',
    'deployment_time': '1659941329',
    'version': '2.0.0-7471',
    'storage_set': 'storage-set-1',
    'type': 'ha_node',
    }, {
    'machine_id': 'aa378e768a2ba5291d786b3dc48d5650',
    'cluster_id': '97811c6a-f072-473f-b5cf-3cc01ced699b',
    'components': [{'name': 'utils', 'version': '2.0.0-7471'},
                   {'name': 'motr', 'services': ['io'],
                   'version': '2.0.0-7471'}, {'name': 'hare',
                   'version': '2.0.0-7471'}],
    'cvg': [{'devices': {'data': ['/dev/sdg', '/dev/sdh'],
            'metadata': ['/dev/sdf']}, 'name': 'cvg-02', 'type': 'ios'
            }],
    'hostname': 'cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local' ,
    'name': 'cortx-data-g1-0',
    'node_group': 'ssc-vm-g4-rhev4-1881.colo.seagate.com',
    'node_id': 'cortx-data-g1-0.cortx-data-headless.cortx.svc.cluster.local'
        ,
    'deployment_time': '1659941344',
    'version': '2.0.0-7471',
    'storage_set': 'storage-set-1',
    'type': 'data_node/1',
    }, {
    'machine_id': 'ac2f9656e38a92990522025e1f3ccaef',
    'cluster_id': '97811c6a-f072-473f-b5cf-3cc01ced699b',
    'components': [{'name': 'utils', 'version': '2.0.0-7471'},
                   {'name': 'hare', 'version': '2.0.0-7471'},
                   {'name': 'rgw', 'services': ['rgw_s3'],
                   'version': '2.0.0-7471'}],
    'hostname': 'cortx-server-0.cortx-server-headless.cortx.svc.cluster.local',
    'name': 'cortx-server-0',
    'node_id': 'cortx-server-0.cortx-server-headless.cortx.svc.cluster.local',
    'deployment_time': '1659941375',
    'version': '2.0.0-7471',
    'storage_set': 'storage-set-1',
    'type': 'server_node',
    }, {
    'machine_id': 'ecabccb4bced858e282f568d6bf04558',
    'cluster_id': '97811c6a-f072-473f-b5cf-3cc01ced699b',
    'components': [{'name': 'utils', 'version': '2.0.0-7471'},
                   {'name': 'csm', 'services': ['agent'],
                   'version': '2.0.0-7471'}],
    'hostname': 'cortx-control',
    'name': 'cortx-control',
    'node_id': 'cortx-control',
    'deployment_time': '1659941332',
    'version': '2.0.0-7471',
    'storage_set': 'storage-set-1',
    'type': 'control_node',
    }]}

2022-08-12 14:15 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
>  class QueryConfData:
Thanks, We will take this as a part of the improvement ticket

2022-08-16 05:28 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
>  class QueryConfData:
this is the improvement ticket: https://jts.seagate.com/browse/CORTX-33877

2022-08-16 05:29 UTC, lakshita-jain commented on py-utils/src/utils/query_deployment/query_deployment.py
>      """Query Configuration Data."""
Noted and will be taken as a part of this improvement ticket
https://jts.seagate.com/browse/CORTX-33877

2022-08-16 06:28 UTC, pawankumarsrivastava commented on py-utils/src/utils/query_deployment/query_deployment.py
>      """Query Configuration Data."""
Resolving the conversation as code improvements will be taken care with CORTX-33877

2022-08-16 06:28 UTC, pawankumarsrivastava approved these changes

2022-08-17 03:20 UTC, kupranay commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        try:
can we validate first which if conf is already loaded with require info... in this way we can save unnecessary call to Consul

2022-08-17 03:22 UTC, kupranay commented on py-utils/src/utils/query_deployment/query_deployment.py
> +        try:
We can do it as part of improvement ticket you have created

2022-08-17 03:24 UTC, kupranay commented on py-utils/src/utils/query_deployment/query_deployment.py
>          for key in Conf.get_keys(QueryConfData._data_idx):
Probably we are adding logic specific to CORTX, that we should avoid. Lets discuss it with @ujjwalpl  as part of improvement ticket and get his views

2022-08-17 03:24 UTC, kupranay approved these changes

2022-08-18 06:09 UTC, tanujashinde0405 approved these changes

2022-08-18 06:10 UTC, merged