Network pre-checks as a new patch
Seagate/cortx-utils pull request #88
Opened 2020-11-06 14:08 UTC by divya-vijay

Splitting the pre-checks as a separate patch for easy review:
1. Has Network mellanox driver check
2. Network mellanox HCA presence and ports check

2020-11-06 14:32 UTC, ujjwalpl requested changes

2020-11-06 14:32 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +                    nodes = ['srvnode-1', 'srvnode-2']
nodes should be passed as parameters. No hard coding in the code

2020-11-06 14:34 UTC, ujjwalpl requested changes

2020-11-06 14:34 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +                cmd = f"ssh {node} lspci -nn | grep 'Mellanox Technologies'"
Mellanox can be passed as input and not hardcoded.

2020-11-06 14:34 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_network.py
> +                    res = ("Mellanox Host Channel Adapters ports were not "
Avoid hard coding

2020-11-10 08:50 UTC, divya-vijay commented on py-utils/src/utils/validator/v_network.py
> +                    nodes = ['srvnode-1', 'srvnode-2']
@ujjwalpl nodes were not hardcoded for passing as arg, this was to ensure driver name is not empty.
Comment addressed and code updated now.

2020-11-10 08:50 UTC, divya-vijay commented on py-utils/src/utils/validator/v_network.py
> +                    res = ("Mellanox Host Channel Adapters ports were not "
Yes, code updated to get the provider value dynamically. It looks like, 
network hca <provider> nodes

2020-11-10 08:51 UTC, divya-vijay commented on py-utils/src/utils/validator/v_network.py
> +                cmd = f"ssh {node} lspci -nn | grep 'Mellanox Technologies'"
Sure, Thanks. 
Code is now updated to get the provider value dynamically.

2020-11-11 05:27 UTC, ujjwalpl approved these changes

2020-11-12 10:24 UTC, ajaysrivas approved these changes

2020-11-12 10:25 UTC, merged