Validators to ensure that consul or elasticsearch processes are running
Seagate/cortx-utils pull request #91
Opened 2020-11-09 13:46 UTC by knekrasov

Example of use:
```
$ ./validate.py process running consul

$ ./validate.py process running elasticsearch
```

2020-11-09 14:25 UTC, ujjwalpl requested changes

2020-11-09 14:25 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +    def _validate_process_by_name(self, name: str) -> None:
Please remove this interface from this class and move to actual ProcessV class so that it can be called from all the environment including non CLI. Commands is purely a translation and shim layer.

2020-11-09 14:25 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_process.py
> +    def validate_process_exists(self, command_pattern: str) -> None:
Please rename to validate_process_running to match CLI and API.

2020-11-09 14:45 UTC, knekrasov commented on py-utils/src/utils/validator/commands.py
> +    def _validate_process_by_name(self, name: str) -> None:
The interface tells about process() method. It comes from the base class. 

> Commands is purely a translation and shim layer.

Please look at this situation from another point of view:
If Command doesn't do anything (and even doesn't parse the input arguments) but only forwards the execution to one single class classed validator, then Command is not needed. It doesn't buy anything. BTW if you look into the commands that we have in v_command.py file, they are meaningless, they have no responsibility.

2020-11-09 14:46 UTC, knekrasov commented on py-utils/src/utils/validator/v_process.py
> +    def validate_process_exists(self, command_pattern: str) -> None:
Why? ProcessV is a layer of busyness logic. It is better to have the method name self-descriptive and have the parameters explicit. It will help the programmers to reuse the code properly, understand the contracts etc.

2020-11-11 06:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +    def _validate_process_by_name(self, name: str) -> None:
Commands code should be generic layer with objective of parsing the command line and passing the inputs to next layer. No business logic / semantics to be added at this layer, please. 
Request please incorporate as suggested. Thanks

2020-11-11 06:26 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_process.py
> +    def validate_process_exists(self, command_pattern: str) -> None:
ProcessV is also an API interface. Not everyone will use command line to invoke. Please refer to wiki page.

2020-11-11 10:06 UTC, knekrasov commented on py-utils/src/utils/validator/v_process.py
> +    def validate_process_exists(self, command_pattern: str) -> None:
Exactly. That's why ProcessV should not parse CLI arguments and should not accept "generic" v_type and args list. This is a programmer's API. The end programmer must understand what the function is, what it will do (i.e. the name of the function must be descriptive) and which parameters are acceptable.

When those who create a framework do care about the interfaces, those interfaces are declared in the form of code - e.g. by means of defining abstract classes with methods to be overriden, class hierarchy with strategies, factories etc. So that when the programmer takes the SDK, he/she will understand the idea, rules of the game and still it will be hard to make a mistake while working with such an API. 

In this Framework we don't see an attempt doing that way and I can't see any of such interfaces. So your requirement doesn't look justified, sorry.

2020-11-11 11:14 UTC, knekrasov commented on py-utils/src/utils/validator/commands.py
> +    def _validate_process_by_name(self, name: str) -> None:
Generic layer without a specific logic and without specific responsibility doesn't sound reasonable. Please remember that [SOLID](https://en.wikipedia.org/wiki/SOLID) tells about Single Responsibility, not about Zero Responsibility 😉 

As I described below in this PR, if we parse everything in validator and do nothing in Command, then it means that the Command classes need to be removed. They are meaningless and the buy nothing in terms of general Framework architecture. Let's give them a single responsibility: "understand the CLI and route the execution to the proper method of the validator". In this case validators are allowed to have meaningful signature and they become not aware of CLI specifics. So that they can potentially be used outside of CLI context (I guess this is what "generic" is meant to be for).

I don't mean that other validator writers need to follow this rule. I just ask to allow my code to be written that way.

2022-03-04 09:31 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-08-08 11:34 UTC, hessio commented
@ujjwalpl is this PR necessary anymore? if not can we close it?

2022-08-16 04:33 UTC, sachinpunadikar commented
@tanujashinde0405 please check whether this code change is required

2024-02-08 16:18 UTC, shailesh-vaidya commented
Closing as an obsolete

2024-02-08 16:18 UTC, closed without merging