Problem: no validator for io-stack is available
Seagate/cortx-utils pull request #94
Opened 2020-11-10 13:06 UTC by knekrasov

Solution: implement validator as follows, implement unit tests.

```
./validate.py ha io-stack
```

Unit tests implemented:
```
python -m unittest -v test/validator/test_ha_status.py
test_services_found (test.validator.test_ha_status.TestHaValidator) ... ok
test_validator_fails_when_io_unknown (test.validator.test_ha_status.TestHaValidator) ... ok
test_validator_fails_when_no_services_found (test.validator.test_ha_status.TestHaValidator) ... ok
test_validator_fails_when_status_not_understood (test.validator.test_ha_status.TestHaValidator) ... ok
test_validator_works_when_all_io_started (test.validator.test_ha_status.TestHaValidator) ... ok
test_validator_works_when_all_started (test.validator.test_ha_status.TestHaValidator) ... ok
```

2020-11-11 05:34 UTC, ujjwalpl requested changes

2020-11-11 05:34 UTC, ujjwalpl commented on py-utils/src/utils/validator/commands.py
> +        v_type = self._v_type
v_type check logic should be moved to v_ha.py. Command line is just the translation layer. 
1. This way if you add another option like "mgmt-stack", no change is required in commands.py
2. API and Command can have common semantics.

2020-11-11 05:34 UTC, ujjwalpl commented on py-utils/src/utils/validator/v_ha.py
> +        io_service_names = {'m0_client', 'ioservice'}
Avoid hard coding in the validation code. All such things should be passed as parameters. Validation is not specific to Motr.

2020-11-11 08:53 UTC, knekrasov commented on py-utils/src/utils/validator/commands.py
> +        v_type = self._v_type
Sorry, I don't agree. Command class needs to do something meaningful. It sounds quite natural that Command class parses the CLI and "converts" the request from CLI to the layer of business logic (validator class). So in these terms Command is a way to publish validator API through CLI. I don't see a reason why validators should be coupled with CLI specifics. 

And even if validators do need to parse CLI arguments, then VCommands have no sense. In this case they are meaningless.

cc @NeeravChoudhari, @ajaysrivas

2020-11-11 09:03 UTC, knekrasov commented on py-utils/src/utils/validator/v_ha.py
> +        io_service_names = {'m0_client', 'ioservice'}
The excel sheet specifies m0_client explicitly. 

Passing everything as a parameter has another drawback: validator tool will depend on how well the caller understands our stack and whether the validator is invoked "in proper way". This means that instead of improving and simplifying the procedure of error identification, we'll add more work to ourselves: the first question the developers will need to answer is "whether validator was invoked properly so that we can trust the result we got".

2022-03-04 09:31 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-08-08 11:34 UTC, hessio commented
@ujjwalpl is this PR necessary anymore or can we close it?

2024-02-08 16:18 UTC, shailesh-vaidya commented
Closing as an obsolete

2024-02-08 16:18 UTC, closed without merging