EOS-15069: Add SSH Session into comm.py
Seagate/cortx-utils pull request #97
Opened 2020-11-12 07:47 UTC by mariyappanp

Unit test result:

> [root@smc39-m09 utils]# python3 -m unittest -v cortx/test/test_ssh_connection.py
> test_command_execution_ok (cortx.test.test_ssh_connection.TestSSHSession)
> Check if command is executed successfully ... useradd: cannot create directory /home/utiltester
> ok
> test_connection_ok (cortx.test.test_ssh_connection.TestSSHSession)
> Check if ssh connection is alive ... useradd: cannot create directory /home/utiltester
> ok
> test_reconnect_ok (cortx.test.test_ssh_connection.TestSSHSession)
> Check ssh re-connect after disconnection caller ... useradd: cannot create directory /home/utiltester
> ok
> 
> ----------------------------------------------------------------------
> Ran 3 tests in 9.483s
> 
> OK

2020-11-18 10:56 UTC, cdeshmukh commented on py-utils/src/utils/comm.py
> +    def disconnect(self):
this is a must call by any cortx client, need to make clients comply by calling it explicitly after every exec_command() ? Copying stdin, stdout, stderr to other vars before closing connection & setting self.client to 'None' ?

Warning from paramiko python doc http://docs.paramiko.org/en/stable/api/client.html
>Warning
Failure to do this may, in some situations, cause your Python interpreter to hang at shutdown (often due to race conditions). It’s good practice to close your client objects anytime you’re done using them, instead of relying on garbage collection.

Or tests will handle this automatically through teardown? Am worried about usage of these functions beyond validator framework.

2020-11-18 11:23 UTC, ujjwalpl requested changes

2020-11-18 11:23 UTC, ujjwalpl commented on py-utils/src/utils/comm.py
> +        self.connect()
disconnect should be called from the destructor similar to the way connect is called from the constructor

2020-11-18 11:25 UTC, ujjwalpl requested changes

2020-11-18 11:25 UTC, ujjwalpl commented on py-utils/src/utils/comm.py
> +    def disconnect(self):
disconnect needs to be called once we are done executing all the commands (need not be after every command). But disconnect must be called from the destructor.

2020-11-18 11:25 UTC, ujjwalpl commented on py-utils/src/utils/comm.py
> +        self.port = 22
port should be passed as parameter and not assumed to be 22. Default value can be 22. 

def __init__(self, host, port=22, username, password):

2020-11-19 03:38 UTC, mariyappanp commented on py-utils/src/utils/comm.py
> +        self.connect()
Done.

2020-11-19 03:49 UTC, mariyappanp commented on py-utils/src/utils/comm.py
> +    def disconnect(self):
`disconnect needs to be called once we are done executing all the commands (need not be after every command)`
Agreed. That's really the best practice too.

`tests will handle this automatically through teardown?`
Yes, if disconnect() is called. Now I added the required changes in SSHSession class itself. Hence, usage of this function beyond the validator framework won't waste or leak connection resources. Please review.

2020-11-19 04:08 UTC, mariyappanp commented on py-utils/src/utils/comm.py
> +        self.port = 22
Done.

2020-11-19 04:56 UTC, cdeshmukh approved these changes

2020-11-19 04:56 UTC, cdeshmukh commented on py-utils/src/utils/comm.py
> +    def disconnect(self):
Ack

2020-11-23 05:36 UTC, ujjwalpl approved these changes

2020-11-23 05:51 UTC, ajaysrivas requested changes

2020-11-23 05:51 UTC, ajaysrivas commented on py-utils/src/utils/comm.py
> +class SSHSession:
SSHSession neither implement(inherit) Channel or Comm interface. So, what is the use of keeping this class here? Moreover, comm.py has interfaces, the implementation should be in separate module. Please check ampq implementation.

2020-11-23 06:17 UTC, mariyappanp commented on py-utils/src/utils/comm.py
> +class SSHSession:
Let me separate this from interface module(comm.py).
**cortx-utils/py-utils/src/utils/ssh.py** would be fine.

2020-11-23 08:56 UTC, ajaysrivas commented on py-utils/src/utils/comm.py
> +class SSHSession:
@ujjwalpl should SSHSession implement Channel/Comm interface? SSH will not have send/receive functions so it doesn't fit this interface.

2020-11-26 10:25 UTC, ujjwalpl approved these changes

2020-11-30 06:22 UTC, ajaysrivas commented on py-utils/src/utils/comm.py
> +class SSHSession:
As per my discussion with Ujjwal, this can be done later when we stop using paramiko library.

2020-11-30 06:23 UTC, ajaysrivas approved these changes

2020-11-30 06:23 UTC, merged